openshift/installer

CHANGELOG.md

CHANGELOG: Document changes since v0.12.0

---

pkg/destroy/libvirt/libvirt.go

Otherwise we don't clean up anything.
Fixes: d137c801ca419b00418348fe652425bae4b71ae3

libvirt: Pass correct InfraID prefix to destroy

---

docs/user/aws/limits.md

https://github.com/openshift/installer/commit/4a0967200a6bfea056ed7a635f560dee0d6ecf99 did not document the addition of this resource and its effects on limits within the AWS account. This PR addresses this.

updating docs to include deails about VPC gateway endpoints

---

data/data/aws/route53/base.tf

masters appear to take 3-5m to resolve their ignition config due to timeout.
according to https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resource-record-sets-values-alias.html#rrsets-values-alias-alias-target , aws docs claim we should not enable health checking if using simple policy.
testing this out to see if it helps drop ignition config time.

data: route53 A records with SimplePolicy should not use health check

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

When render commands failed, we left the directory. Another bootkube.sh run skipped that part. This hides errors and lead to undefined and untested behaviour.
https://github.com/openshift/installer/pull/1273 was an example. The issue was not visible because we kept going on the 2nd bootkube.sh try.

bootkube.sh: do not hide problems with render

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
pkg/asset/ignition/bootstrap/bootstrap.go

It was added to the image via openshift/etcd@5d267b9f (openshift/etcd#4).  This way we don't have to bump our version by hand (#1060, #1304).

data/bootstrap/files/usr/local/bin/bootkube: etcdctl from release image

---

pkg/types/validation/installconfig.go

I'd kept this in 3b393da8 (#1154) to support CI.  But with openshift/release@d31f601e (openshift/release#2772) landed, we no longer need the workaround.

pkg/types/validation: Drop v1beta1 backwards compat hack

---

pkg/asset/tls/etcd.go

Detach etcd-client-ca from the root-ca chain in order to make it a proper independent chain of trust.
Part of https://jira.coreos.com/browse/CORS-999
/cc @abhinavdahiya

pkg/asset/tls: self-sign etcd-client-ca

---

pkg/asset/tls/aggregator.go

Detach aggregator-ca from the root-ca chain in order to make it a proper independent chain of trust
Part of https://jira.coreos.com/browse/CORS-999
/cc @abhinavdahiya

pkg/asset/tls: self-sign aggregator-ca

---

pkg/types/validation/installconfig.go

When we pivoted to `v1beta3` in ccdc32e3 (#1157), we dropped support for the old `machines` JSON property.  Instead of silently ignoring that property in `v1beta2` configs, error out to avoid surprising users later when they notice us not picking up their `machines` configuration.
Or internal consumers pivoted to `v1beta3` in openshift/release@e1d729c6 (openshift/release#2787) and openshift/hive@3eda6d12 (openshift/hive#228).
CC @staebler

pkg/types/validation/installconfig: Drop nominal v1beta2 support

---

data/data/aws/main.tf
data/data/aws/variables-aws.tf
docs/user/aws/install.md
pkg/destroy/aws/aws.go
pkg/tfvars/aws/aws.go

This is a quick hack to get encrypted masters.  Ideally we'd want to deregister these on bootstrap-teardown, but handling that nicely will be easier after some cleanups from #1148.  As it stands, we'll need to deregister this as part of the general cluster teardown (hence the WIP).  CC @ericavonb.

data/aws: Encrypt the AMI used by the bootstrap and master machines

---

pkg/asset/installconfig/aws/permissions.go

currently the logs from creds checker do not match the installer output.
```console
WARN[0019] Action not allowed with tested creds action="ec2:CreateSecurityGroup"
WARN[0019] Action not allowed with tested creds action="ec2:CreateSubnet"
WARN[0019] Action not allowed with tested creds action="ec2:CreateTags"
WARN[0019] Action not allowed with tested creds action="ec2:CreateVpc"
WARN[0019] Action not allowed with tested creds action="ec2:CreateVpcEndpoint"
WARN[0019] Action not allowed with tested creds action="ec2:CreateVolume"
WARN[0019] Action not allowed with tested creds action="ec2:DescribeAccountAttributes"
WARN[0019] Action not allowed with tested creds action="ec2:DescribeAddresses"
WARN[0019] Action not allowed with tested creds action="ec2:DescribeAvailabilityZones"
WARN[0019] …
```

aws: use the standard logger for creds checking

---

data/data/aws/bootstrap/main.tf

In 6c10827b (#1306), we restricted master SSH access to the cluster, catching up with 6add0ab4 (#1045).  But the bootstrap node is a useful SSH bastion for debugging hung installs (until we get far enough along to tear down the bootstrap resources).  This commit restores global SSH access to the bootstrap node, now that it is no longer provided by the master security group.

data/aws/bootstrap: Restore global SSH access

---

data/data/aws/master/outputs.tf

data/aws/master: drop 2 unused outputs

---

pkg/asset/installconfig/aws/permissions.go

@csrwng reporting earlier today that the latest master branch cluster installs are failing with:
ERROR
ERROR Error: Error applying plan:
ERROR
ERROR 1 error occurred:
ERROR     * aws_ami_copy.main: 1 error occurred:
ERROR     * aws_ami_copy.main: UnauthorizedOperation: You are not authorized to perform this operation.
ERROR     status code: 403, request id: 96aa0046-aea7-447f-b03d-3dd5550e1dc9
ERROR
this was resolved by granting the AWS user the ec2:CopyImage permission/capability. add ec2:CopyImage to the pre-flight permission checks.

add ec2:CopyImage as a required permission

---

data/data/aws/main.tf
data/data/aws/master/main.tf
data/data/aws/master/outputs.tf
data/data/aws/master/variables.tf
data/data/aws/variables-aws.tf
data/data/aws/vpc/common.tf
data/data/aws/vpc/outputs.tf
pkg/asset/cluster/tfvars.go
pkg/tfvars/aws/aws.go

These changes pass the availability zones to use for the masters set in 99_openshift-cluster-api_master-machines.yaml through to terraform. Prior to these changes the masters were always placed in the first 3 availability zones.
There is no validation done on the availability zones to verify that the are valid for the region.
Fix for https://bugzilla.redhat.com/show_bug.cgi?id=1662119.

data/aws: use azs for master set in manifests

---

data/data/openstack/main.tf
data/data/openstack/topology/private-network.tf
data/data/openstack/topology/variables.tf
data/data/openstack/variables-openstack.tf
docs/user/openstack/README.md
pkg/types/openstack/platform.go

openstack: Support setting network UUID via terraform variable.
Technically, network names in OpenStack are not unique.  We would
expect almost every deployment to be using a unique name for its
external network, though.
In the rare case where you must disambiguate networks, it's possible
to specify the UUID via a terraform variable.
$ env TF_VAR_openstack_external_network_id="6a32627e-d98d-40d8-9324-5da7cf1452fc" \
> bin/openshift-install create cluster

openstack: Support setting network UUID via terraform variable.

---

pkg/asset/installconfig/aws/permissions.go

Now that the installer creates the encrypted AMI, we also need the ability to delete the AMI on cluster destroy. Otherwise we get these errors:
DEBUG deleting arn:aws:ec2:us-east-1:125931421481:image/ami-0c82315f404e184a8: UnauthorizedOperation: You are not authorized to perform this operation.
status code: 403, request id: b57ae4d9-5c9c-4e69-a7de-81f03eea3b15
Add ec2:DeregisterImage to the list of permissions the installer needs.

add ec2:DeregisterImage permission to pre-flight checks

---

docs/user/troubleshooting.md

xref: https://jira.coreos.com/browse/CORS-1011

docs/troubleshooting: add sections to cover all post-create phases

---

CHANGELOG.md

Through 563f71fd (#1306).  Also backporting #1316, so we can build the 0.13.1 docs on top of the complete 0.13.0 docs (which branched off from master before the release's 563f71fd, but which landed after).
Base commit was chosen by:
```console
$ oc adm release info --commits quay.io/openshift-release-dev/ocp-release:4.0.0-0.6 | grep installer
installer                                     https://github.com/openshift/installer                                     563f71fdfb75f96177912ca9b1d4285c7f03cea1
```

CHANGELOG: Document changes since 0.13.0

---

hack/release.sh

I've been working these up by hand for the last several releases to give users who trust my key but not GitHub (possibly an empty set ;) a way to verify the authenticity of downloaded installers.  This commit just institutionalizes the procedure.

hack/release: Compute release.sha256(.sig)

---

pkg/asset/installconfig/aws/permissions.go
pkg/destroy/aws/aws.go

When the encrypted AMI used by the cluster is created, a snapshot is created as well. This snapshot needs to be explicitly deleted when the cluster is destroyed to avoid leaking resources. Unfortunately,
the snapshot does not have any tags when it is created. The snapshot can be found from the AMI's block device mappings, though. When the destroyer finds an AMI to delete, the destroyer will tag the snapshots used by the AMI with tags that match the filter used to find the AMI. This will allow the destroyer to find the snapshots on subsequent queries using that filter.
It would be preferably if the snapshot were tagged during the cluster creation. There is no way that I see to tag the snapshot when the AMI is created, using the terraform aws provider. There may be a way to have terraform …

destroy: delete snapshots used in ami copies

---

cmd/openshift-install/create.go
cmd/openshift-install/destroy.go
pkg/asset/ignition/bootstrap/bootstrap.go
pkg/asset/ignition/machine/master.go
pkg/asset/ignition/machine/worker.go
pkg/asset/installconfig/installconfig.go
pkg/asset/kubeconfig/kubeconfig.go
pkg/asset/manifests/cluster_k8s_io.go
pkg/asset/manifests/operators.go
pkg/asset/store/store.go
pkg/destroy/aws/aws.go

No need for formatting in these cases.  I've also adjusted the "Could not {attempted thing}" message to be more consistent with our other "failed to {attempted thing}" messages.
Personally I prefer "{attempted thing}", because the fact that we're returning an error sufficiently expresses our failure.  But that's been occasionally contentious before, so I'm punting on it while touching these lines ;).

*: Wrapf(err, "...") -> Wrap(err, "...")

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

Need to get the pod image for the MCO so that it can be set
in crio.conf.
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

Add infra-image to MCO bootstrap

---

data/data/aws/main.tf
data/data/aws/vpc/outputs.tf

https://github.com/openshift/installer/pull/1121/commits/afa0b599b76163b08ea393bc36e94e6248042a8e had moved the bootstrap node to private
subnet based on https://github.com/openshift/installer/pull/1121#issuecomment-466563682, but we need the bootstrap node in public subnet to be able to ssh.
The bootstrap node is accesible on ssh again.
```console
$ ush core@18.215.154.240
Warning: Permanently added '18.215.154.240' (ECDSA) to the list of known hosts.
Red Hat CoreOS 4.0 Beta
WARNING: Direct SSH access to machines is not recommended.
This node has been annotated with machineconfiguration.openshift.io/ssh=accessed
---
This is the bootstrap node; it will be destroyed when the master is fully up.
The primary service is "bootkube.service". To watch its status, run e.g.
journalctl -b -f -u …
```

data/aws: create bootstrap machine in first public subnet

---

images/installer/Dockerfile.ci
images/installer/Dockerfile.ci.rhel7

This reverts commit 71d199c55e0e897801765d4283049486562beb92, #1262
Since openshift/release@00d7b3f31 (openshift/release#2911), the release repository no longer users the installer image for the teardown containers.

Revert "image: Take explicit dependency on util-linux for uuidgen and gzip"

---

docs/user/customization.md

xref: https://jira.coreos.com/browse/CORS-799

Document entry-point for user-provided custom MachineConfig

---

data/data/aws/vpc/sg-master.tf
data/data/aws/vpc/sg-worker.tf
data/data/openstack/topology/sg-master.tf

We allow ports 9000-9999 for general-purpose system services. This change opens them up for UDP as well.

aws, openstack: open ports 9000-9999 between nodes on UDP too.

---

data/data/aws/master/main.tf
data/data/aws/master/outputs.tf
pkg/destroy/aws/aws.go

Today we create the network interface for master nodes implicitly as part
of the instance creation. We then use the IPs from those nodes to create
DNS records we use to set up etcd. This change creates the Network Interface
for masters explicitly instead of implicitly. Since this can be done before
the AMI copy is complete it means we can get DNS complete before we ever
launch a node. It looks like it saves at least 1m in the terraform time.
It might be more since DNS never will get an NXDOMAIN and cache that either.
I don't know about that yet

data/aws: explicitly create the network interface for masters to speed up DNS

---

data/data/openstack/service/main.tf
data/data/openstack/topology/private-network.tf
data/data/openstack/topology/sg-lb.tf
data/data/openstack/topology/sg-master.tf
data/data/openstack/topology/sg-worker.tf

This will allow for running multiple OCP clusters under the same tenant
without conflicting names and resources.

openstack: Prefix all openstack resources with the cluster name

---

docs/user/aws/customization.md
pkg/asset/ignition/machine/master_test.go
pkg/asset/ignition/machine/worker_test.go
pkg/asset/installconfig/installconfig.go
pkg/asset/installconfig/installconfig_test.go
pkg/asset/manifests/network.go
pkg/asset/tls/apiserver.go
pkg/types/conversion/installconfig.go
pkg/types/conversion/installconfig_test.go
pkg/types/defaults/installconfig.go
pkg/types/defaults/installconfig_test.go
pkg/types/installconfig.go
pkg/types/validation/installconfig.go
pkg/types/validation/installconfig_test.go

Renames:
- serviceCIDR -> serviceNetwork
- clusterNetworks -> clusterNetwork
- type -> networkType
- hostSubnetLength -> hostPrefix
Add significantly more network validation, especially around overlapping cidrs.
This adds an upconversion step to loading install config. It will convert any deprecated install configs to the latest version.

types: rename network type to match Network.config.openshift.io.

---

pkg/asset/machines/aws/machines.go

Add credentials secret to AWS provider config in order to support CredentialsRequest

---

data/data/aws/vpc/common.tf
pkg/asset/machines/aws/zones.go

Zones can also be impaired, unavailable, or "information" (docs [here][1] and [here][2]).  I dunno what that last one is about.  But we only want to put machines in available zones ;).
This is a bit racy, because we could get different responses at both call-sites.  Moving forward, we'll want to shift this request into a single available-zones asset.
Fixes #1209.
[1]: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeAvailabilityZones.html
[2]: https://www.terraform.io/docs/providers/aws/d/availability_zones.html#state

pkg/asset/machines/aws: Only return available zones

---

CHANGELOG.md

Through c8b3b553 (#1338).
I've left 8d0847c02 (#794) undocumented, since it seems like an unstable-enough user-facing API approach that I don't think we want to noise it about and deal with the fall-out when we change the API ;).  That commit also made it into this history via 44a9cd38 (#1294).
I've also left off eecf4968 (#1294), because I have no idea what that's about ;).  I'll fill in an entry for it later once one of the OpenStack devs explains it to me :p.  CC @flaper87, @trown
CC @abhinavdahiya, @crawford

CHANGELOG: Document changes since 0.13.1

---

data/data/openstack/bootstrap/main.tf
data/data/openstack/bootstrap/variables.tf
data/data/openstack/main.tf
data/data/openstack/masters/main.tf
data/data/openstack/masters/variables.tf
data/data/openstack/service/main.tf

Now that we're not using neutron DNS anymore, we must set the hostnames
on the nodes so that it's possible to communicate between VMs

openstack: Set hostnames for nodes

---

pkg/asset/machines/worker.go
pkg/asset/manifests/openshift.go

When the platform is none, there should be no worker machineset object created.
Currently when using the None platform, following file is created:
```console
$ ls -l dev-metal/openshift
total 20
-rw-r--r--. 1 adahiya adahiya  293 Mar  7 16:11 99_binding-discovery.yaml
-rw-r--r--. 1 adahiya adahiya  181 Mar  7 16:11 99_kubeadmin-password-secret.yaml
-rw-r--r--. 1 adahiya adahiya  330 Mar  7 16:11 99_openshift-cluster-api_cluster.yaml
-rw-r--r--. 1 adahiya adahiya   49 Mar  7 16:11 99_openshift-cluster-api_worker-machineset.yaml
-rw-r--r--. 1 adahiya adahiya 2689 Mar  7 16:11 99_openshift-cluster-api_worker-user-data-secret.yaml
```
The contents of the 99_openshift-cluster-api_worker-machineset.yaml are:
```console
$ cat dev-metal/openshift/99_openshift-cluster-api_worker-machineset.yaml …
```

assets: no worker machinesets file for None

---

data/data/aws/vpc/sg-master.tf

Noticed extra ports exposed on master security group. Nothing listening on these ports during or after the install. Appears there used to be a temporary etcd used by the bootstrap, but sitting in the master security group still. Removed the unnecessary rule.

[AWS] Remove unused/legacy boostrap etcd ports in master security group

---

pkg/destroy/aws.go
pkg/destroy/aws/aws.go

Today we find instance profiles that we need to delete through either the
associated role or the associated instance. We find those objects via aws
tags. If those objects have been deleted we are unable to find the instance
profiles because those are not tagged.
Since we now embed both cluster id inside the name this PR adds the ability to find those object and to delete them even if the roles and instances have been deleted.

pkg/destroy: data/aws: delete instance profiles even if they are detached

---

cmd/openshift-install/log.go
cmd/openshift-install/version.go
hack/build.sh
pkg/version/version.go

And include that hash in the `openshift version` and log output. This makes it easier to troubleshoot reports from official builds, which currently reference internal tags:
```console
$ RELEASE=quay.io/openshift-release-dev/ocp-release:4.0.0-0.7
$ INSTALLER="$(oc adm release info "${RELEASE}" --image-for installer)"
$ oc image extract "${INSTALLER}" --file=/usr/bin/openshift-install
$ chmod +x openshift-install
$ ./openshift-install version
./openshift-install v4.0.15-1-dirty
```
although you can currently extract the commit given the pullspec and access to the backing registry:
```console
$ oc image info --output=json "${INSTALLER}" | jq -r '.config.config.Labels["io.openshift.build.commit.id"]'
c8b3b5532694c7713efe300a636108174d623c52
```

pkg/version: Include the commit hash

---

data/data/openstack/main.tf

We currently name the swift container according to cluster_domain.
However, swift container names are global scope, and cluster_domain
may not be unique in an entire openstack cloud. Instead, we should
use cluster_id, which is also in line with how other resources are
named.

openstack: name swift container according to cluster_id

---

pkg/asset/cluster/cluster.go

Right now it seems like we are spending that time creating our cluster stuff.
In reality we are taking that time creating VMs and load balancers, and DNS
entries in the cloud. So try to say something which indicates 'this time is not
out fault!'

create cluster: change Creating cluster to Creating infrastructure resources

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

* adds new flag kube-client-agent-imag and populates with release image metadata
* update etcdCertSignerImage to use openshift 4.0 release image
depends on: https://github.com/openshift/machine-config-operator/pull/538
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1684670

Bug 1684670: data/data/bootstrap: add kube-client-agent-image flag

---

data/data/aws/vpc/master-elb.tf

Follow-up of https://github.com/openshift/origin/pull/22322.
Goal: make the ELB notice termination of kube-apiserver early in order to have time to take the node out of the loop.
`/healthz` in contrast to `/readyz` only fails when the pod was actually gone, not when the termination process (which now takes 30+ seconds) has been started.
Prerequisite: https://github.com/openshift/origin/pull/22322

Switch api ELBs to /readyz for healthz checks

---

pkg/destroy/aws/aws.go

We've been explicitly creating and tagging network interfaces since 4fcdc1cb (#1361).  But sometimes Terraform errors halt creation between creation and tagging, leading to destroy loops like:
```
...
time="2019-03-18T09:57:08-07:00" level=debug msg="search for and delete matching resources by tag in us-east-1 matching aws.Filter{\"openshiftClusterID\":\"null\"}"
time="2019-03-18T09:57:08-07:00" level=debug msg="search for and delete matching resources by tag in us-east-1 matching aws.Filter{\"kubernetes.io/cluster/ci-op-7dc8l67n-28622-nxrw2\":\"owned\"}"
time="2019-03-18T09:57:09-07:00" level=debug msg="deleting arn:aws:ec2:us-east-1:460538899914:dhcp-options/dopt-07f625baad68c14fe: DependencyViolation: The dhcpOptions 'dopt-07f625baad68c14fe' has dependencies and cannot be …
```

pkg/destroy/aws: Add deleteEC2NetworkInterfaceByVPC

---

data/data/openstack/main.tf
data/data/openstack/service/main.tf
data/data/openstack/service/variables.tf
data/data/openstack/topology/outputs.tf

We used to set the API entry in the DNS to point only to the floating
IP. We should set it to the internal IP if a fIP for the API service
doesn't exist.
The deployment should be able to move forward even in a scenario like
this.

openstack: Always set the api DNS entry 

---

cmd/openshift-install/create.go

Like:
```
Working towards 4.0.0-0.alpha-2019-03-18-091023: 64% complete
```
These seem to advance slowly, but having slowly-changing information about progress is better than having no information ;).  And with this change, we will pass along more detailed progress information if/when the cluster-version operator adds it.

cmd/openshift-install/create: Log progressing messages

---

images/nested-libvirt/Dockerfile

This PR updates the Dockerfile used in CI to build the libvirt image.  Repo epel-testing is not available, so build errors out.  We don't need this so I've removed it. 
I'm working to get the libvirt CI job running, with CRC team.

libvirt CI Dockerfile fix

---

upi/vsphere/machine/main.tf
upi/vsphere/machine/variables.tf
upi/vsphere/main.tf
upi/vsphere/terraform.tfvars.example
upi/vsphere/variables.tf

Add support for rchos template that use thin provisioning.
Update terraform.tfvars.example to give details about the rchos-latest
template.
This also removed some unused variables and commented out code around setting static IP addresses for the machines. Static IP addresses are not working yet.

upi/vsphere: support rhcos-latest template

---

data/data/bootstrap/systemd/units/chown-gatewayd-key.service
pkg/asset/ignition/bootstrap/bootstrap.go

In RHEL8 journald switched to `DynamicUser=yes`, we can't reference
the user at Ignition time.  Let's hack around this by adding a fixed
version of the user and doing the chown.

bootstrap: Work around systemd-journal-gateway DynamicUser=yes

---

images/installer/Dockerfile.upi.ci

It builds an image containing binaries like jq, terraform, awscli, oc, etc. to allow bringing up UPI infrastructure.
It also contains the `upi` directory that contains various terraform and cloud formation templates that are used to create infrastructure resources.
```console
$ docker run --user 0 -ti --entrypoint /bin/bash abhinavdahiya/upi-installer:latest
bash-4.2# oc
OpenShift Client
This client helps you develop, build, deploy, and run your applications on any OpenShift or Kubernetes compatible
platform. It also includes the administrative commands for managing a cluster under the 'adm' subcommand.
To create a new application, login to your server and then run new-app:
oc login https://mycluster.mycompany.com
oc new-app centos/ruby-25-centos7~https://github.com/sclorg/ruby-ex.git
oc …
```

images/installer: add image that can be used to instal UPI platforms

---

pkg/asset/ignition/bootstrap/bootstrap.go
pkg/asset/ignition/bootstrap/release_image.go

As part of our release process we build container images for installer
that are added to the release image (which has a cryptographic
relationship to the images it contains, giving strong integrity). A
consumer should be able to download and install a locked installer
binary that uses the payload. However, we would prefer to not
rebuild the binary outside of the image, but instead have:
1. a source for the binary from the payload
2. the binary be locked to the payload it comes from
This commit allows a build system above the payload to extract the
installer binary for linux from the image (other platforms later)
and perform a replacement on the binary itself, patching:
```
_RELEASE_IMAGE_LOCATION_XXXXXXXXXXX
```
with
```
quay.io/openshift/ocp-release:v4.0\x00
```
without requiring a …

release: Allow release image to be directly substituted into binary

---

pkg/asset/machines/openstack/machines.go
pkg/asset/machines/openstack/machinesets.go

This PR adds back the support to create machines and machinesets
with trunk support enabled.

Re-add support for trunk ports

---

hack/build.sh
pkg/rhcos/builds.go

The "bootimage" is the one we use before pivoting.  Bump this
so we don't need to support RHEL7 anymore even there.
This rolls in #1423

 rhcos: Bump bootimage to 410.8.20190325.0

---

data/data/manifests/openshift/cluster-networkconfig-crd.yaml

This has already been merged in the operator; just need to update
the installer's cache of the crd.
Someday we can get rid of this, but not yet.

Re-group the network operator crd.

---

docs/user/metal/install_upi.md
upi/metal/.gitignore
upi/metal/README.md
upi/metal/bootstrap/matchbox.tf
upi/metal/bootstrap/outputs.tf
upi/metal/bootstrap/packet.tf
upi/metal/bootstrap/variables.tf
upi/metal/config.tf
upi/metal/main.tf
upi/metal/outputs.tf
upi/metal/terraform.tfvars.example

* Adds an example implementation for UPI Bare Metal in `upi/metal` using Packet.net and AWS.
* Adds docs on requirements and how-to on using OpenShift Installer to create a Bare Metal cluster.

Add initial docs and example implementation for UPI bare-metal

---

pkg/types/aws/validation/machinepool.go
pkg/types/aws/validation/machinepool_test.go
pkg/types/aws/validation/platform.go
pkg/types/validation/installconfig.go
pkg/types/validation/machinepools.go
pkg/types/validation/machinepools_test.go

In the excitement of a zone outage, this one [bit me][1], leading to [errors like][2]:
```
ERROR  * module.masters.aws_network_interface.master[1]: key "us-east-1c" does not exist in map var.az_to_subnet_id in:
ERROR
ERROR ${var.az_to_subnet_id[var.availability_zones[count.index]]}
ERROR  * module.masters.aws_network_interface.master[2]: key "us-east-1d" does not exist in map var.az_to_subnet_id in:
ERROR
ERROR ${var.az_to_subnet_id[var.availability_zones[count.index]]}
ERROR  * module.masters.aws_network_interface.master[0]: key "us-east-1a" does not exist in map var.az_to_subnet_id in:
ERROR
ERROR ${var.az_to_subnet_id[var.availability_zones[count.index]]}
ERROR  * module.bootstrap.var.subnet_id: key "us-east-1a" does not exist in map module.vpc.az_to_public_subnet_id in:
ERROR
ERROR …
```

pkg/types/aws/validation: Require machine-pool zones in platform region

---

docs/user/openstack/README.md

In the OpenStack installer README, the description of the wildcard DNS entry and the example did not match.

Fixed DNS record description for OpenStack

---

upi/vsphere/route53/main.tf

Create wildcard `*.apps` for VSphere UPI so that authentication and console operators would work

upi/vsphere: create apps dns entry

---

pkg/asset/machines/master.go
pkg/asset/machines/worker.go

for each machinepool (install-config), we have 3 things that make it up: <RHCOS only>
- userdata-secret with stub ignition that can be used to start machines...
- machineconfigs with configuration like sshAuthorizedKeys, hyperthreading options
- machine-api resources..
for UPI based platforms the asset must include:
- userdata-secret,  because it is harmless allows users to fetch the ignition configs from inside their cluster (can be used for automation in machine-api supported UPIs)
- machineconfigs, these are always required.

machines: fix machine asset for None, VSphere platform

---

images/installer/Dockerfile.upi.ci

Fix Dockerfile.upi.ci syntax - image has to be in `FROM` before `COPY --from` is used

Dockerfile.upi.ci: declari cli image as input image

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

This PR adds metric-signer CA's to kube-etcd-signer-server as part of voyage to etcd metrics by default. The eventual result is the etcd static pod procuring TLS certs with a separate chain of trust vs `Peer` and `Server` .

BUG 1670700: data/data/bootstrap: set metric-ca flags for kube-etcd-signer-server

---

pkg/types/installconfig.go

PR 1498 [1] include vsphere in the platfoms that show up in TUI.
```console
$ ./openshift-install create cluster
? SSH Public Key /home/adahiya/.ssh/id_rsa_aws.pub
? Platform  [Use arrows to move, type to filter]
> aws
vsphere
```
all UPI platforms are install-config only. These should not show up in TUI for installer.
[1]: https://github.com/openshift/installer/pull/1458
/cc @staebler

types: move vsphere out of tui

---

upi/vsphere/folder/main.tf
upi/vsphere/folder/output.tf
upi/vsphere/folder/variables.tf
upi/vsphere/machine/main.tf
upi/vsphere/machine/variables.tf
upi/vsphere/main.tf

- Creates a vm folder
- Virtual Machines are deployed into the folder created

vSphere UPI - Use a folder for virtual machines

---

cmd/openshift-install/create.go

The templates target didn't quite end up being what we had in mind. To
avoid confusing users, this target is being removed from the set of
available targets. It may be reintroduced later.
This is what the help text looks like after this change:
Available Commands:
cluster          Create an OpenShift cluster
ignition-configs Generates the Ignition Config asset
install-config   Generates the Install Config asset
manifests        Generates the Kubernetes manifests

cmd/openshift-install/create: remove templates

---

cmd/openshift-install/version.go
pkg/asset/ignition/bootstrap/bootstrap.go
pkg/asset/ignition/bootstrap/release_image.go

When the installer is updated to have the locked release version
the version command should show that info to assist in debugging.
Identified while testing the transformation - I wanted to see what
the binary was locked to as the bootstrap code would see it.
Related to https://github.com/openshift/origin/pull/22439

cmd: Report locked release image pull spec in `version` command

---

data/data/aws/route53/base.tf

We've been using the tagged private zone to look up the public zone since the non-Terraform destroy code landed in a8fc89bec1 (#324).  When there's an existing cluster with a given domain, that can lead to false-positive removals [like][1]:
1. Cluster 1 comes up like usual.
2. Cluster 2 creates a private zone.
3. Cluster 2 dies when its public record conflicts with cluster 1 (new since d1c17b7f83, #1442).
4. 'destroy cluster' on cluster 2's metadata.json removes cluster 2 resources (good) and cluster 1's public record (bad).
With the explicit dependency in this commit, we ensure that we only ever create the private zone after we have successfully claimed ownership of the public record.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1659970#c7

Bug 1659970: data/aws/route53: Block private Route 53 zone on public record

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

This PR is the last commit required to complete chicken/egg adding `--etcd-metric-ca` flag to MCO.
Flag was added to MCO via: https://github.com/openshift/machine-config-operator/pull/590

BUG 1670700: data/data/bootstrap: add --etcd-metric-ca to MCO bootstrap

---

images/installer-artifacts/Dockerfile.rhel

To ensure the payload is reproducible, we will include images for both cli
and installer commands for non linux platforms that allow users to get the
correct tools to install the release image. Since the installer binary is
not small and we don't want to take the cost to pull it on each node when
in use from hive, create a new image installer-artifacts that layers on top
of installer (inheriting the default installer Linux binary) and places the
darwin binary into
/usr/share/openshift/mac/openshift-install. This directory structure is
kept deliberately simple for end users - if we do in the future need to
deal with multi-arch concerns we'll do that at a higher level and in
practice neither 32bit nor arm will be "supported" as part of the core
distro yet.
The dockerfile matches the desired …

image: Add a production "installer-artifacts" image for Mac binary

---

pkg/destroy/aws/aws.go

Sometimes these slip through without getting tagged.  For example:
```console
$ aws ec2 describe-nat-gateways --filter Name=vpc-id,Values=vpc-030a62e79bc5bc0d3 --output json | jq '.NatGateways[] | {NatGatewayId, CreateTime, NumTags: (.Tags | length)}'
{
"NatGatewayId": "nat-0f85c55eae154e749",
"CreateTime": "2019-03-28T15:10:30.000Z",
"NumTags": 3
}
{
"NatGatewayId": "nat-0aba1c63954afbe32",
"CreateTime": "2019-03-28T15:10:31.000Z",
"NumTags": 3
}
{
"NatGatewayId": "nat-0b87f04521788a765",
"CreateTime": "2019-03-28T15:12:06.000Z",
"NumTags": 0
}
{
"NatGatewayId": "nat-0f26b4e1ba6ef97a5",
"CreateTime": "2019-03-28T15:11:44.000Z",
"NumTags": 0
}
{
"NatGatewayId": "nat-0f49c9061debf9777",
"CreateTime": "2019-03-28T15:10:30.000Z",
"NumTags": 3
}
{
"NatGatewayId": "nat-004b67f754f85ea4a", …
```

pkg/destroy/aws: Destroy NAT gateways by VPC too

---

images/installer-artifacts/Dockerfile.rhel

Assets are required to build, but hack/build-go.sh cannot handle
cross architecture asset generation. Explicitly generate before
invoking the script.
Failed when CI tried to build:
```
+ go build ... ./cmd/openshift-install
data/unpack.go:12:15: undefined: Assets
```
in https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_release/3321/rehearse-3321-pull-ci-openshift-installer-master-images/1

image: Asset generation is required

---

README.md
cmd/openshift-install/create.go
docs/user/aws/install.md
docs/user/openstack/README.md

The kubeadmin user should only be used to temporarily access the
console, and only until an admin configures a proper Identity Provider.
There is no reason to login as the kubeadmin user via CLI.  If oauth
is broken in a cluster, an admin can still access via CLI as system:admin,
but will not be able to access via kube:admin.
@enj https://jira.coreos.com/browse/AUTH-293

Modify kubeadmin usage message, admins should not use kubeadmin via CLI

---

pkg/terraform/exec/Gopkg.lock

See linked issue for details.
fixes #1471

fix: Gopkg.lock after running dep ensure on pkg/terraform/exec

---

upi/metal/bootstrap/packet.tf
upi/metal/main.tf
upi/metal/outputs.tf

Bootstrap node is failing to uncompress the bios image with `t1.small` capacity.
and also packet seems to be failing to deploy servers in SJC1. Using `any` allows terraform to create the servers in any available datacenter.
/cc @wking @sdodson

upi/metal: update the instance location and size

---

pkg/asset/tls/aggregator.go

When working on the Ignition v2s3 move, we noticed that we were
generating a duplicate asset. That one had the same name
"apiserver-proxy". The correct name _should_ be "aggregator-client".
This may just have been a copy/paste error.
We're not sure how it worked _before_ because what this is doing is overwriting an already written file (the other asset wrote that already and this piece of code is re-writing it with the same name)
Signed-off-by: Antonio Murdaca <runcom@linux.com>

pkg/asset: fix client cert key name

---

Gopkg.lock
vendor/github.com/stretchr/testify/LICENSE
vendor/github.com/stretchr/testify/assert/assertions.go

Pulling in stretchr/testify@199de5f3a4 (stretchr/testify#648) to drop the "Please consider promoting this project..." deviation from the stock MIT license.
```console
$ dep ensure -update github.com/stretchr/testify
```
using:
```console
$ dep version
dep:
version     : v0.5.1
build date  : 2019-03-20
git hash    : faa61893
go version  : go1.10.3
go compiler : gc
platform    : linux/amd64
features    : ImportDuringSolve=false
```

vendor: Bump stretchr/testify to v1.3.0

---

upi/aws/cloudformation/02_cluster_infra.yaml

Names for ELBv2 TargetGroup names must be unique per region [1]. With the name hardcoded in this file, it doesn't allow more than one of these stacks to be created in a region (per account). We desire multiple clusters created this way per region.
[1]: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html#cfn-elasticloadbalancingv2-targetgroup-name

BUG 1695860: upi/aws: Removing hardcoded names on TargetGroup resources

---

data/data/rhcos.json
hack/build.sh
hack/update-rhcos-bootimage.py
pkg/asset/rhcos/image.go
pkg/rhcos/ami.go
pkg/rhcos/builds.go
pkg/rhcos/qemu.go

This way we avoid needing a service available at least for AWS
installs.  The AMIs now get hardcoded into the binary.
Further, in order to make it easier for developers to test
alternative builds of RHCOS, add an override environment variable
just like is available for the release payload.

rhcos: Embed full build metadata in binary

---

images/installer/Dockerfile.upi.ci

CI for bare-matal uses [`terraform-provider-matchbox`](https://github.com/coreos/terraform-provider-matchbox) and since it is not part of the official providers for terraform it cannot be downloaded on the fly.
This builds and include the binary for terraform-provider-matchox in the upi image.
/cc @wking @sdodson

images/installer: add matchbox provider to upi image

---

pkg/asset/cluster/cluster.go
pkg/asset/password/password.go
pkg/asset/targets/targets.go

The KubeadminPassword asset owns the kube admin password, so that asset should own creating the password file.

asset/password: KubeadminPassword responsible for the password file

---

pkg/destroy/aws/aws.go

We were passing a *string, not a string, so we logged garbage.
It also names "IAM instance profile" to "InstanceProfileName" and centralizes where it is set.

pkg/destroy/aws: Log InstanceProfile name correct on delete

---

data/data/manifests/openshift/role-cloud-creds-secret-reader.yaml.template

Fill out role-cloud-creds-secret-reader.yaml when the platform is vsphere so that there is proper rbac to the cloud creds secret.

data/manifests: fill out cloud creds role for vsphere platform

---

cmd/openshift-install/create.go
pkg/asset/store.go
pkg/asset/store/assetcreate_test.go
pkg/asset/store/store.go
pkg/asset/store/store_test.go

Pass in to the Fetch function all of the assets that should not be consumed when purging.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1686943

BUG 1686943: asset/store: include all assets to preserve when doing a fetch

---

upi/aws/cloudformation/02_cluster_infra.yaml
upi/aws/cloudformation/03_cluster_security.yaml
upi/aws/cloudformation/04_cluster_bootstrap.yaml
upi/aws/cloudformation/05_cluster_master_nodes.yaml
upi/aws/cloudformation/06_cluster_worker_node.yaml

Fixes bugzilla by allowing hyphen as part of the cluster name. Verified the ClusterName is only used in tags and other names where a hyphen is okay (or also being used to generate names).

Bug 1696085: Allow using "-" in ClusterName parameter

---

OWNERS_ALIASES
pkg/asset/installconfig/vsphere/OWNERS
pkg/asset/manifests/vsphere/OWNERS
pkg/types/vsphere/OWNERS
upi/vsphere/OWNERS

These directories are vSphere-specific, and the set of vSphere maintainers does not need to exactly match the folks maintaining the core, cross-platform installer components.  Add a new alias to make it easy to manage that distinction.
CC @abhinavdahiya, @staebler.  Also in this space: Azure approvers: #1569

OWNERS_ALIASES: Add vsphere-approvers

---

upi/vsphere/README.md
upi/vsphere/machine/cidr_to_ip.sh
upi/vsphere/machine/ignition.tf
upi/vsphere/machine/ip.tf
upi/vsphere/machine/main.tf
upi/vsphere/machine/output.tf
upi/vsphere/machine/variables.tf
upi/vsphere/main.tf
upi/vsphere/route53/main.tf
upi/vsphere/route53/variables.tf

The ip address reservation has been changed so that the ip address reservation is done by a resource instead of a data source. This prevents ip addresses from being reserved when doing terraform plan
and destroy. The ip address query is still done by a data source, since there is no way to get output from a null resource. And because data sources are run before resources are created, the ip addresses are not available on the first terraform apply. The user needs to run terraform apply twice.
The machines module has also been refactored to separate the ignition and ip address portions into their own separate files.

upi/vsphere: manage ip address reservation

---

pkg/destroy/openstack/OWNERS

This creates the `OWNERS` file with `openstack-approvers` in
`pkg/destroy/openstack`.

OWNERS: Add to `pkg/destroy/openstack`

---

data/data/aws/vpc/sg-master.tf
data/data/aws/vpc/sg-worker.tf

There was a typo in the rule that allowed icmp - it accidentally blocked all icmp.
Also, fix the ip block to match for both master and workers.
Fixes  https://bugzilla.redhat.com/show_bug.cgi?id=1689857

aws: fix ICMP ACL

---

data/data/aws/vpc/sg-master.tf
data/data/aws/vpc/sg-worker.tf

We open port 30000-32767 for NodePort services. We need to allow this for UDP too.
Fixes [bz1698210](https://bugzilla.redhat.com/show_bug.cgi?id=1698210).

Bug 1698210: aws: allow udp services as well

---

upi/vsphere/machine/cidr_to_ip.sh
upi/vsphere/machine/ip.tf

The cidr_to_ip.sh script used to reserve IP addresses uses ipcalc to determine the subnet from the CIDR. The CIDR is not used for anything else. These changes pass in the subnet to the script rather than the CIDR so that ipcalc is not needed. The motivation for this is that ipcalc is not available on RHEL7, which is the base image for the image used in CI.

upi/vsphere: remove dependency on ipcalc

---

data/data/openstack/service/main.tf

If the haproxy container fails to start, it will block creation of any
subsequent ones because the "haproxy" name is already taken.

openstack: don't set the haproxy container name

---

upi/vsphere/machine/ignition.tf
upi/vsphere/machine/variables.tf
upi/vsphere/main.tf
upi/vsphere/terraform.tfvars.example
upi/vsphere/variables.tf

The extra users were helpful when ramping up on booting rhcos on vsphere. The boot process is more stable now so the extra users are no longer needed. If problems do arise in the future where having a user that can log in with a password is helpful, that can easily be added manually to the ignition configs.

upi/vsphere: remove extra users

---

cmd/openshift-install/create.go
cmd/openshift-install/waitfor.go
docs/user/aws/install_upi.md
docs/user/metal/install_upi.md

@crawford, @smarterclayton, @derekwaynecarr, @eparis, and @sdodson got together to hash out naming, and they feel that `install-complete` is more intuitive than `cluster-ready`.

cmd/openshift-install/waitfor: Rename cluster-ready to install-complete

---

docs/user/vsphere/install_upi.md
upi/vsphere/README.md

Docs for installing on vSphere.

docs: vSphere installation docs

---

pkg/asset/store/assetcreate_test.go
pkg/asset/targets/targets.go

BZ#1696342 [1] pointed out that installer was not providing the kubeadmin secret when running the `create ignition-configs` target. That target is currently the primary
means to perform UPI type installations. Missing kubeadmin password file cause error like `FATAL open /root/installation/baremetal-0404/auth/kubeadmin-password: no such file or directory`
when running the wait-for command.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1696342
/cc @wking @staebler

BUG 1696342: pkg/asset: include kubeadmin password in the IgnitionConfig target

---

data/data/aws/route53/base.tf
data/data/libvirt/main.tf

wired to the same load balancer. But does mean you can change the certs
and CA for the apiserver on the public name, but let us continue to own
certs for the -int name used by kubelets

BUG 1685704: data/aws: create an api-int dns name

---

data/data/libvirt/main.tf

libvirt breaks api-int changes due to commit 60526fe3760d10b561ca99f46a9e2afec30f801b
Error: data.libvirt_network_dns_host_template.bootstrap: resource repeated multiple times
cc @wking @abhinavdahiya

libvirt/main.tf: Add correct entry for *api-int* hostname

---

data/data/rhcos.json
pkg/asset/installconfig/installconfig_test.go
pkg/asset/machines/machineconfig/hyperthreading.go
pkg/asset/machines/master.go
pkg/asset/machines/master_test.go
pkg/asset/machines/worker.go
pkg/asset/machines/worker_test.go
pkg/types/defaults/installconfig.go
pkg/types/defaults/installconfig_test.go
pkg/types/defaults/machinepools.go
pkg/types/defaults/machinepools_test.go
pkg/types/machinepools.go
pkg/types/validation/installconfig_test.go
pkg/types/validation/machinepools.go
pkg/types/validation/machinepools_test.go

Add a `hyperthreading` field to machine pools with options of `Enabled` or `Disabled`. The default is `Enabled`.
When a machine pool has hyperthreading disabled, the Machines asset for that pool creates a `MachineConfig` manifest for that pool. The ignition config lays down a file at `/etc/default/rhcos/karg/nosmt` with no contents. The machine-config-daemon is responsible for reading that file and setting the `nosmt` karg for the machine.

types: option to disable hyperthreading

---

data/data/rhcos.json

Update RHCOS to include cri-o 1.13.6, which has fixes for the
"Manifest does not match provided manifest digest" error. Also
change the baseURI to ART's artifacts, as they now have public
accessible storage.
Signed-off-by: Yu Qi Zhang <jerzhang@redhat.com>

data/data: update rhcos to 410.8.20190412.1

---

data/data/manifests/openshift/cloud-creds-secret.yaml.template
data/data/manifests/openshift/role-cloud-creds-secret-reader.yaml.template

Fill out role-cloud-creds-secret-reader.yaml when the platform is vsphere so that there is proper rbac to the cloud creds secret.
```console
$ > cat install-config.yaml                                                                                   
apiVersion: v1beta4
baseDomain: basename.com
compute:
- name: worker
platform: {}
replicas: 3
controlPlane:
name: master
platform: {}
replicas: 3
metadata:
creationTimestamp: null
name: mycluster
networking:
clusterNetwork:
- cidr: 10.128.0.0/14
hostPrefix: 23
machineCIDR: 10.0.0.0/16
networkType: OpenShiftSDN
serviceNetwork:
- 172.30.0.0/16
platform:
azure:
baseDomainResourceGroupName: os_domain
region: eastus
pullSecret: '...'
sshKey: |
ssh-rsa AAAAB3NzaC1yc2EAA...
$ > cat 99_role-cloud-creds-secret-reader.yaml
kind: Role
apiVersion: …
```

data/manifests: fill out cloud creds role for azure platform 

---

docs/user/aws/install_upi.md
upi/aws/cloudformation/01_vpc.yaml
upi/aws/cloudformation/02_cluster_infra.yaml

This PR resolves the DNS portion of the network edge UPI configuration. It ensures the Hosted Zone matches what the default Ignition configuration generates and updates the doc to explain how the user may extract the infrastructure ID. 
Will handle the subnet portion for BZ1697236 in a separate PR.

BZ1697262: Add infrastructure ID to private HostedZone

---

upi/vsphere/machine/ignition.tf

Some domains may exceed 63 char limit and the node won't join the cluster. This happens on CI currently

upi/vsphere: user short hostname

---

docs/user/metal/install_upi.md
upi/metal/main.tf

Add DNS record for api-int that points to the control plane hosts.
infrastructure architecture change happening for https://bugzilla.redhat.com/show_bug.cgi?id=1685704

BUG 1685704: upi/metal: add the api-int dns

---

upi/aws/cloudformation/02_cluster_infra.yaml
upi/aws/cloudformation/03_cluster_security.yaml
upi/aws/cloudformation/04_cluster_bootstrap.yaml
upi/aws/cloudformation/05_cluster_master_nodes.yaml
upi/aws/cloudformation/06_cluster_worker_node.yaml

This PR brings all naming conventions and instance tags inline to use the InfrastructureName. Should help resolve remaining issue with BZ1697236 being reported.

BZ1697236: Updating tags/names to use InfrastructureName

---

data/data/bootstrap/files/usr/local/bin/installer-gather.sh
data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh

Initial version of a script, which collects information from bootstrap and control-plane nodes for use when the bootstrap never completes. This is just a first pass and intended to be good enough that we'll start deriving value from it in our CI testing where we often get bootstrap failures and lack the requisite logging to debug those failures.
```
$ ssh -A core@bootstrap /usr/local/bin/installer-gather.sh                                                                                                         
Gathering bootstrap journals ...
Gathering bootstrap containers ...
Gathering cluster resources ...
Waiting for logs ...
Gather remote logs
Gathering master journals ...
Gathering master containers ...
Waiting for logs ...
Gathering master journals ...
Gathering master containers …
```

data/bootstrap: add a script to collect info if cluster failed to start

---

pkg/asset/ignition/bootstrap/release_image.go

On Mon, Apr 15, 2019 at 10:07 AM @smarterclayton wrote:
> Install team developers:
>
> Can continue building the installer locally, but the location we publish origin to has been updated to registry.svc.ci.openshift.org/origin/release:v4.1 and this is only if you are hacking the installer.

pkg/asset/ignition/bootstrap/release_image: Bump default to v4.1

---

pkg/asset/manifests/azure/cloudproviderconfig.go
pkg/asset/manifests/azure/cloudproviderconfig_test.go
pkg/asset/manifests/azure/types.go
pkg/asset/manifests/cloudproviderconfig.go

To run openshift on azure we need to configure the cloud provider config.
I brought in the data types from kubernetes to simplify marshalling
Adding the dependency was overkill, so copying seemed more pragmatic.
This PR is dependent on #1555

pkg/asset/manifests: add azure cloud provider config manifests

---

data/data/bootstrap/files/usr/local/bin/installer-gather.sh

Use updated label to fetch a list of API server (both openshift and kube) pods

bootstrap/installer-gather.sh: update label for api pods

---

pkg/destroy/aws.go
pkg/destroy/aws/aws.go

Avoid looping forever [with][1]:
```
INFO get tagged resources: NoCredentialProviders: no valid providers in chain. Deprecated.
For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```
and so on for all the other calls.  With this commit, I'm allowing callers to provide their own session, which they can pre-check as they like.
I'm not adjusting `pkg/destroy/aws` to use `GetSession` internally, because it would drag in a bunch of mostly-unrelated dependencies that `pkg/destroy/aws` consumers like [Hive][2] won't want.  And Hive's consumer isn't interactive anyway, so our prompting logic would not be a good fit for them.  With this commit, *we* can use our prompting `GetSession` without forcing it onto Hive.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1684951
[2]: …

Bug 1684951: pkg/destroy/aws: Use GetSession() to prompt when missing

---

data/data/openstack/bootstrap/main.tf
data/data/openstack/masters/main.tf
data/data/openstack/service/main.tf

The terraform-created OpenStack hostnames now have the short name rather than
FQDN. This is consistent with the worker nodes and makes sure the actuator's
nodelink-controller is able to match the names and sync the nodes.
The node names without FQDN are now resolvable as well.

openstack: Remove FQDN from node hostnames

---

data/data/manifests/bootkube/openshift-config-configmap-etcd-serving-ca.yaml.template
data/data/manifests/bootkube/openshift-config-secret-etcd-client.yaml.template
pkg/asset/templates/content/bootkube/configmap-etcd-serving-ca.go
pkg/asset/templates/content/bootkube/secret-etcd-client.go

To get to API freeze, we need to ensure that all shared configmaps and secrets are in openshift-config or openshift-config-managed.  This moves the interlock for etcd to kas-o to openshift-config.  We have to ratchet these in, so this creates the new, but does not remove the old.
/assign @hexfusion

move etcd connection information to openshift-config

---

cmd/openshift-install/create.go
data/data/bootstrap/files/usr/local/bin/report-progress.sh
data/data/bootstrap/systemd/units/progress.service

Modify the progress service so that it creates a configmap when bootstrapping is done rather than an event. This is done so that the installer can determining whether bootstrapping has completed even when run later, after the bootstrap-complete event would otherwise have expired and been deleted.
https://bugzilla.redhat.com/show_bug.cgi?id=1698573

BUG 1698573: cmd: level-driven bootstrap complete

---

cmd/openshift-install/create.go
cmd/openshift-install/gather.go
cmd/openshift-install/main.go
cmd/openshift-install/waitfor.go
data/data/bootstrap/files/usr/local/bin/installer-gather.sh

Adds a new subcommand to assists with debugging a failed bootstrap by collecting logs from the cluster. Currently, it outputs the shell commands to run in order to gather these logs. It can later be extended to gather the logs itself. It is called automatically from the create cluster subcommand on a failed bootstrap.
https://jira.coreos.com/browse/CORS-1050

New gather subcommand to assist debugging bootstrap failures.

---

data/data/aws/vpc/sg-master.tf
data/data/openstack/topology/sg-master.tf
upi/aws/cloudformation/03_cluster_security.yaml

Recently, the control plane switched to secure ports in [1] and [2].
This aligns them in the installer.
[1]
https://github.com/openshift/cluster-kube-scheduler-operator/pull/88
[2]
https://github.com/openshift/cluster-kube-controller-manager-operator/pull/207
/cc @brancz @sttts

controller-manager/scheduler: switch to secure ports

---

upi/vsphere/machine/ignition.tf

RHCOS has changed the name of the NIC from eth0 to ens192 [1]. The ifcfg file laid down to set the static IP address of the machines needs to be updated to reflect the new name of the NIC.
[1] https://github.com/coreos/coreos-assembler/pull/442

upi/vsphere: use ens192 nic name

---

pkg/asset/machines/aws/machines.go
pkg/asset/machines/aws/machinesets.go

Related:
https://github.com/openshift/cluster-api-provider-aws/pull/182
https://github.com/openshift/machine-api-operator/pull/255
/cc @enxebre

Drop unused machine labels

---

docs/user/aws/customization.md
docs/user/metal/install_upi.md
pkg/asset/installconfig/installconfig_test.go
pkg/types/conversion/installconfig.go
pkg/types/installconfig.go
upi/vsphere/README.md

We're locking ourselves in for stability going forward.  Hopefully we got this right ;).
CC @abhinavdahiya, @crawford

pkg/types/installconfig: Bump v1beta4 to v1

---

data/data/aws/vpc/master-elb.tf

These were changes from two to three in 16dfbb3541 (#594):
```console
$ git show 16dfbb354120 | grep _threshold | sort | uniq
-    healthy_threshold   = 2
-  #   healthy_threshold   = 2
+    healthy_threshold   = 3
-    unhealthy_threshold = 2
-  #   unhealthy_threshold = 2
+    unhealthy_threshold = 3
```
@crawford doesn't remember intentionally making that change, and the lower thresholds will hopefully help mitigate some issues with continued connection attempts to API servers which are in the process of shutting down.

data/aws/vpc/master-elb: Set thresholds back to two

---

data/data/manifests/bootkube/kube-system-configmap-etcd-serving-ca.yaml.template
data/data/manifests/bootkube/kube-system-secret-etcd-client.yaml.template
pkg/asset/templates/content/bootkube/configmap-etcd-serving-ca.go
pkg/asset/templates/content/bootkube/secret-etcd-client.go

completes the work already done in the rest of the operators to rely on the openshift-config namespace.

tls: only write etcd certs into openshift-config

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

Code research by Seth Jennings indicates that even though this was built
against a serving CA, it is used to terminate client connections for the kubelet.
Switch to using client-ca bundle.

tls: update MCO to take client ca bundle

---

data/data/bootstrap/files/usr/local/bin/openshift.sh

openshift.sh runs after bootkube and attemps to wait for the kube-apiserver to look healthy.
The wait is a little unusual in and of itself (you contacted the server, why wait), but
it should wait on the openshift-kube-apiserver namespace since that's the one that runs
the kube-apiserver.
/assign @wking

openshift: update wait for kube-apiserver to correct namespace

---

data/data/bootstrap/files/usr/local/bin/openshift.sh

This reverts commit 989839e2e661374c88b815a744e6524bd081cc0e.
the prior merge job looks to be missing the entire directory. This is probably the failure, but it's not obvious why CI failed.

Revert "openshift: update wait for kube-apiserver to correct namespace"

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
pkg/asset/kubeconfig/admin.go
pkg/asset/kubeconfig/kubeconfig.go
pkg/asset/kubeconfig/kubeconfig_test.go
pkg/asset/kubeconfig/kubelet.go
pkg/asset/manifests/utils.go

BZ1685704 requires that all internal client ie openshift cluster-infra clients inside the cluster that talk to the apiserver on LB needs to move to using `api-int.$cluster_domain` so that customers can modify the external LB URL for apiserver without affecting the internal clients.
*  `data/data/bootstrap/files/usr/local/bin/bootkube.sh.template`
All the internal clients which includes the etcd cert agent moved to contacting the apiserver on `api-int.$cluster_domain` therefore the etcd signer on the bootstrap node needs to use the serving cert for the `api-int`
*  `pkg/asset/kubeconfig/`
The admin kubeconfig that installer provides its users needs to continue the apiserver on `api.$cluster_domain`
The kubelet kubeconfig is moved to use `api-int.$cluster_domain` as kubelets are internal …

BUG 1685704: assets: use internal apiserver name for all internal clients

---

docs/user/metal/install_upi.md
docs/user/vsphere/install_upi.md

image-registry operator modified the opertor config object to reduce the supported storage options [1].
This commit updates the docs to follow the new structure
[1]: https://github.com/openshift/cluster-image-registry-operator/pull/257

upi: update the registry patch command

---

pkg/asset/machines/master.go

Setup k8s apimachinery for the azure version of the specs
of the cluster-api-azure-provider specs.

pkg/asset/machines: add azure machine api scheme

---

data/data/bootstrap/files/usr/local/bin/openshift.sh

The openshift unit runs after the bootkube unit, so the control plane is up.
We no longer have any need to wait.
Alternative https://github.com/openshift/installer/pull/1658
/assign @wking

bootstrap: don't make openshift unit wait for kas

---

OWNERS

This reverts commit c1aa02274f3d64760f1d177f87ecac581c0238cc, #618.
We've made a lot of progress separating out the per-platform components since that went in, so take another run at formally separating approval for per-platform and core changes.
CC @flaper87, @tomassedovic, @hardys: any concerns about this?  If so, point me at the code you're concerned about not being able to bump independently, and as long as it's not `vendor/`, I'll see if I can make the core/platform separation cleaner there.

Revert "Add OpenStack team as reviewers"

---

images/installer/Dockerfile.upi.ci

The govc tool is needed to create a vSphere VM template from an OVA file. This is needed so that vSphere e2e tests can use the rhcos boot image referenced in rhcos.json.

images: add govc to UPI CI image

---

images/installer/Dockerfile.upi.ci

The vSphere e2e tests need to create a VM template from an OVA. The location from which to download the OVA is in the rhcos.json file. This change makes the rhcos.json file available to the CI tests.

images: add rhcos.json to the upi ci image

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

Catching up to MCO supporting reading the cloud conf file on bootstrap node only when the infrastructures.config.openshift.io
has the cloud provider config location set [1]
[1]: https://github.com/openshift/machine-config-operator/pull/591
/cc @staebler @wking

data/bootstrap: update the mco bootstrap to include the cloudconf file path

---

docs/user/metal/install_upi.md
docs/user/vsphere/install_upi.md

This was added out of an abundance of caution about how etcd metrics were being scraped, because the Prometheus scrapers can run on compute nodes.  We've now confirmed that etcd-metrics are being scraped from port 9979, which is part of the existing "OpenShift reserved" and so does not need a specific call-out.
CC @abhinavdahiya, @hexfusion

docs/user: Drop compute access to etcd server from UPI docs

---

data/data/bootstrap/files/usr/local/bin/installer-gather.sh

I've got a broken pull https://github.com/openshift/machine-config-operator/pull/626, but in general, any future asset rendering error requires the rendered assets to make a determination of the failure.  This gathers those.
@sdodson 
/assign @vrutkovs

gather rendered assets as part of install-gather

---

data/data/bootstrap/systemd/units/kubelet.service.template

Bootstrap kubelet attempts to create /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ for flexvolume plugins and warns readonly FS in kubelet log:
```
Apr 25 13:53:45 ip-10-0-8-85 hyperkube[1358]: W0425 13:53:45.762647    1358 probe.go:271] Flexvolume plugin directory at /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ does not exist. Recreating.
Apr 25 13:53:45 ip-10-0-8-85 hyperkube[1358]: E0425 13:53:45.762700    1358 plugins.go:517] Error initializing dynamic plugin prober: Error (re-)creating driver directory: mkdir /usr/libexec/kubernetes: read-only file system
```
This PR would ensure /etc/kubernetes/kubelet-plugins/volume/exec is used for flexvolume plugins, this would prevent this misleading warning from showing.
MCO does the same on masters: …

data/bootstrap: pass volume-plugin-dir to kubelet param to avoid flexvolume warnings

---

data/data/bootstrap/files/usr/local/bin/installer-gather.sh

This fixes a shell substitution part for mapfile when nodes didn't join the cluster

data/bootstrap: fix fetch master addresses when API is not up

---

OWNERS_ALIASES
data/data/libvirt/OWNERS
docs/dev/libvirt/OWNERS
pkg/asset/cluster/libvirt/OWNERS
pkg/asset/installconfig/libvirt/OWNERS
pkg/asset/machines/libvirt/OWNERS
pkg/destroy/libvirt/OWNERS
pkg/tfvars/libvirt/OWNERS
pkg/types/libvirt/OWNERS
tests/bdd-smoke/suites/config/libvirt/OWNERS

This is to give ownership of libvirt backend of Installer to CRC team. For now I've only added two members from CRC team (myself and Praveen). I also added two members of Installer team who seem to have been the most active devs developing the relevant code.

Setup ownership of libvirt code

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

Multiple locations for control plane pods was required for cluster-bootstrap so that control plane can transition to the correct
namespace.
Since the control plane pods are in openshift-* namespace, the alternative locations can be droppped.
/cc @openshift/sig-master

data/bootkube: remove old control plane pod names from bootstrap required list

---

data/data/aws/bootstrap/main.tf
data/data/aws/vpc/sg-master.tf
data/data/aws/vpc/sg-worker.tf
data/data/aws/vpc/vpc-private.tf
data/data/aws/vpc/vpc-public.tf

Using [operation timeouts][1] from terraform-providers/terraform-provider-aws#3599 and terraform-providers/terraform-provider-aws#3639, both of which were added in v1.11, so we have them in our v2.2 AWS provider.  This should mitigate some of the issues we've been having in our busy CI account, where out of ~1150 jobs in the last 24 hours, we've had the following failures (using [this server][6]):
```console
$ curl -s 'http://localhost:8000/search?name=-e2e-aws&.&q=level%3Derror.*timeout+while+waiting+for+state' | jq -r '. | to_entries[].value[] | to_entries[].value[]' | sed 's/(i-[^)]*/(i-.../;s/(igw-[^)]*/(igw-.../;s/\(master\|nat_gw\|private_routing\|route_net\)\.[0-9]/\1.../' | sort | uniq -c | sort -n
2 level=error msg="\t* aws_instance.master...: Error waiting for instance (i-...) …
```

data/aws: 20-minute create timeouts for routes and security groups

---

data/data/libvirt/bootstrap/variables.tf

found while wondering why `git grep "boostrap node"` only returned one reference. (Answer: because I can't type.)

description typo in data/data/libvirt/bootstrap/variables.tf

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

Requires etcd-signer-server to support multiple certs for serving [1]
Currently the etcd-signer-server only serves request using `api-int` serving certificate which causes errors like,
```console
time="2019-04-24T13:25:11-07:00" level=debug msg="Still waiting for the Kubernetes API: Get https://api.adahiya-0.tt.testing:6443/version?timeout=32s: x509: certificate is valid for api-int.adahiya-0.tt.testing, not api.adahiya-0.tt.testing"
```
as the installer is hitting the etcd-signer-server on api.$cluster_domain.
Setting up etcd-signer-server to use multiple certs ie one for api and another for api-int allows both internal and external client to hot etcd-signer-server and not get x509 errors.
[1]: https://github.com/coreos/kubecsr/pull/28

data/bootstrap: update etcd-signer-server to use certs for api and api-int

---

images/installer-artifacts/Dockerfile.rhel
images/installer/Dockerfile.ci
images/installer/Dockerfile.ci.rhel7
images/installer/Dockerfile.upi.ci
images/mock/Dockerfile
images/nested-libvirt/Dockerfile
images/openstack/Dockerfile.ci

The images in use should be consistent across all components, and
pointing to the right versions. Doing this will allow the installer
CI repo to benefit from binary build reuse in ci-operator. Prevent
local dev builders from grabbing the wrong images.

images: Clean up image FROM to be consistent

---

data/data/manifests/bootkube/etcd-namespace.yaml

**Why this change?**
When https://github.com/openshift/cluster-kube-apiserver-operator/pull/394 merges, all the pods running openshift cluster will have a [defaultNodeSelector](https://docs.openshift.com/container-platform/3.11/admin_guide/managing_projects.html#setting-the-cluster-wide-default-node-selector) if it has been set by cluster-admin including pods running in `openshift-*` namespace. The main advantage of having that feature is in a multi-tenant environment, any new project created can be steered towards compute nodes(non-master nodes).
**What should I do?**
If you think, the pods in your namespace shouldn't have defaultNodeSelector set, please review this PR. If not feel free to close this. The annotation added as part of this PR lets all the pods created within your project …

Add defaultNodeSelector annotation to openshift-etcd namespace

---

data/data/manifests/bootkube/cvo-overrides.yaml.template
docs/user/troubleshooting.md

This is the channel that the beta4 drop and later will be in.
CC @abhinavdahiya, @smarterclayton, @steveeJ.  We may need to wait on the production Cincinnati to also switch.
/hold

data/data/manifests/bootkube/cvo-overrides: Move to stable-4.1

---

pkg/asset/machines/aws/machines.go
pkg/asset/machines/aws/machinesets.go

We dropped aws role labels in https://github.com/openshift/installer/pull/1474 to reduce the surface to what's actually needed by our core controllers. However having this lables provides better UX and searchability for end users and consumers like machineAutoscaler resource so we are putting them back

BUG 1702050: Add aws role labels back (revert #1474)

---

docs/user/aws/install_upi.md
upi/aws/cloudformation/01_vpc.yaml
upi/aws/cloudformation/02_cluster_infra.yaml
upi/aws/cloudformation/03_cluster_security.yaml
upi/aws/cloudformation/04_cluster_bootstrap.yaml
upi/aws/cloudformation/05_cluster_master_nodes.yaml
upi/aws/cloudformation/06_cluster_worker_node.yaml

I'm still testing this, but folks keep talking about it, so pushing my current status somewhere public ;).

Drop AWS UPI control-plane Machines and compute MachineSets

---

cmd/openshift-install/gather.go

Compound adjectives are seperated by hyphens. The copy as-is is a little
hard to parse.

cmd: fix some copy in the help text

---

Gopkg.lock
Gopkg.toml
hack/verify-vendor.sh

#1688 updated the vendor that left the master vedoring in inconsistent.
```console
$ git --no-pager log --pretty=oneline -1 -U
30e4f71 (HEAD -> master, upstream/master) Merge pull request #1696 from patrickdillon/update-owners
$ dep ensure
Solving failure: No versions of github.com/openshift/cluster-api-provider-libvirt met constraints:
c23986b36a2521cd69ac22d7adb74a22bca9f7aa: Could not introduce github.com/openshift/cluster-api-provider-libvirt@c23986b36a2521cd69ac22d7adb74a22bca9f7aa, as it has a dependency on github.com/openshift/cluster-api with constraint 91fca585a85b163ddfd119fd09c128c9feadddca, which has no overlap with existing constraint d8958b539e331bf5ebb056b7f872541e13fb8e01 from (root)
v0.2.0: Could not introduce github.com/openshift/cluster-api-provider-libvirt@v0.2.0, as …
```

 vendor: fix inconsistent state 

---

upi/aws/cloudformation/02_cluster_infra.yaml
upi/aws/cloudformation/03_cluster_security.yaml
upi/aws/cloudformation/04_cluster_bootstrap.yaml
upi/aws/cloudformation/05_cluster_master_nodes.yaml
upi/aws/cloudformation/06_cluster_worker_node.yaml

So we can still add a few chars and stay under the AWS limits, avoiding stuff like:
```
The load balancer name 'api-int-ci-op-mk19233w-38af6-us-east-1' cannot be longer than '32' characters (Service: AmazonElasticLoadBalancingV2; Status Code: 400; Error Code: ValidationError; Request ID: 2acccf34-6d74-11e9-ac17-cf3d0e8e1c6d)
```
This brings us in line with [`InfrastructureStatus.InfrastructureStatus`][1].
[1]: https://github.com/openshift/api/blob/168fd4e3c55217ad0042c4ee1ec79e9ce40d5c21/config/v1/types_infrastructure.go#L36

upi/aws/cloudformation: Cap InfrastructureName at 27 chars

---

pkg/asset/manifests/azure/cloudproviderconfig.go
pkg/asset/manifests/azure/cloudproviderconfig_test.go

The cloud provider needs the clientID which is only known after terraform has run.
When left empty, the existing managed identity on the VM will be used.
By leaving it empty, we don't have to create the identity before running the installer.
We only need to know that there will be one assigned to the VM, and we control this.
ref: https://github.com/kubernetes/kubernetes/blob/4b7c607ba47928a7be77fadef1550d6498397a4c/staging/src/k8s.io/legacy-cloud-providers/azure/auth/azure_auth.go#L69

pkg/asset/manifests/azure: leave cloud-provider identity empty

---

data/data/openstack/topology/private-network.tf

Do not hardcode the resolvers for the service VM, use the defaults from
the cloud instead.

openstack: Rely on the cloud configured nameservers

---

images/installer/Dockerfile.upi.ci

Repo `github.com/coreos/terraform-provider-matchbox` has moved ownership to `github.com/poseidon/terraforn-provider-matchox` [1]
So the previous `go get github.com/coreos/terraform-provider-matchbox` now fails to build [2] as the new repo moved to new module [3]
So the move to fetching the binary from the github released artifacts [4] seems like the better move.
[1]: https://github.com/poseidon/terraform-provider-matchbox
[2]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1729/pull-ci-openshift-installer-master-images/4202
[3]: https://github.com/poseidon/terraform-provider-matchbox/pull/43
[4]: https://github.com/poseidon/terraform-provider-matchbox/releases/tag/v0.2.3
/cc @wking @staebler

images/installer: update upi Dockerfile to fetch matchbox using releases

---

data/data/rhcos.json

/cc @tbielawa @miabbott @yuqi-zhang @darkmuggle @cgwalters @abhinavdahiya

rhcos: Bump to 410.8.20190508.1

---

images/openstack/Dockerfile.ci
images/openstack/rdo-stein.repo

The openstack repo provided by the release rpm was providing a broken .repo file. Instead, we can use our own static .repo file.

openstack: use static .repo file for openstack client

---

pkg/asset/tls/apiserver.go

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1709869
We can't break legacy apps using the "openshift" service hostname.
/cc @smarterclayton 
/cc @wking

Bug 1709869: tls: add openshift service to DNS names

---

data/data/bootstrap/files/usr/local/bin/approve-csr.sh
data/data/bootstrap/files/usr/local/bin/installer-gather.sh
data/data/bootstrap/systemd/units/approve-csr.service
pkg/asset/ignition/bootstrap/bootstrap.go

PR for cluster-machine-approver [1] is taking over the approval of CSRs for client certificates for Machines that end up
as Nodes in Openshift clusters.
But during bootstrapping, cluster-machine-approver is not available and therefore, this service is required to approve CSRs until
we have successfully bootstrapped the control plane, after which cluster-machine-approver or users take over the role of approving any new CSRs.
Currently, all CSRs are automatically approved without any condition, this PR scopes it to only during bootstrapping phase, securing the endpoint for later use.
[1]: https://github.com/openshift/cluster-machine-approver/pull/26

data: add approve-csr service to approve CSRs until bootstrap is complete

---

pkg/asset/ignition/bootstrap/bootstrap.go
pkg/asset/ignition/machine/master.go
pkg/asset/ignition/machine/worker.go
pkg/asset/installconfig/installconfig.go
pkg/asset/kubeconfig/kubeconfig.go
pkg/asset/manifests/operators.go

Before this commit, errors looked like:
```
failed to fetch Terraform Variables: failed to load asset "Install Config": failed to unmarshal: error converting YAML to JSON: yaml: line 39: could not find expected ':'
```
With this commit, they will look like:
```
failed to fetch Terraform Variables: failed to load asset "Install Config": failed to unmarshal install-config.yaml: error converting YAML to JSON: yaml: line 39: could not find expected ':'
```
The filename was already implicit in the asset name (e.g. "Install Config"), but it makes it slightly easier on users if we go ahead and spell out the filename for them.
CC @umohnani8

pkg/asset: Add filenames to "failed to unmarshal" errors

---

pkg/asset/ignition/bootstrap/release_image.go

The master branch is now tracking 4.2 work and therefore tracking 4.2 release image stream [2] is more appropiate.
[1]: https://origin-release.svc.ci.openshift.org/
[2]: `registry.svc.ci.openshift.org/origin/release:4.2`
/cc @smarterclayton @wking

bootstrap: update default release image to track 4.2 origin

---

pkg/types/conversion/installconfig.go

Currently the error returned is `failed to upconvert install config: cannot upconvert from version ` and empty version is not
visible to users explicitly.
/cc @wking

types/conversion: return no version provided error when trying to convert

---

data/data/rhcos.json

Putting WIP for now so we can discuss the URI (and destination branch) here

Bug 1712562: pin the 4.1 GA candidate RHCOS build boot images

---

data/data/azure/main.tf
data/data/azure/variables-azure.tf
pkg/asset/cluster/tfvars.go
pkg/tfvars/azure/azure.go

Terraform azurerm provider supports supports 4 kinds of authentication methods [here][1].
The installer uses the `Service Principal and a Client Secret` [here][2] method because it best suites the requirement for installer as this type of auth methods can be passed into the cluster as secret.
By default when no authentication is specified for Azurerm provider, the ordering followed is (service principal + client secret) > (service principal + client secret) > (msi) > (azure cli token) [here][3]
Currently since the provider is not setup with any authentication in the templates, it usually falls back to the azure cli method.
Now since installer sets up the creds for users, there is no way to use the ENV input for (service principal + client secret) and terraform
Azurerm provider doesn't …

azure: pass credentials provided to installer to terraform 

---

data/data/rhcos.json

Per a comment from @abhinavdahiya, we may as well have parity between the boot images used in the 4.1 GA installer branch and in master.  This does that.

pin to the 4.1 GA candidate RHCOS images

---

pkg/types/aws/defaults/platform.go
pkg/types/aws/validation/platform.go
platformtests/aws/default_instance_class_test.go

The Hong Kong region is [new 2019-04-25][1] and does not support the older m4 types.  This pull-request adds it (commented out in validation, because we don't push RHCOS AMIs there, see also #1528).  It also expands the seeded regions in `TestGetDefaultInstanceClass` to gets the tests to pass:
```console
platformtests/aws$ AWS_PROFILE=openshift-dev go test .
ok  							 github.com/openshift/installer/platformtests/aws			26.282s
```
[1]: https://aws.amazon.com/blogs/aws/now-open-aws-asia-pacific-hong-kong-region/

aws/defaults/platform: Default to m5 in ap-east-1

---

docs/dev/libvirt/README.md

docs/dev/libvirt: Add troubleshooting docs for libvirt console issue.

---

data/data/azure/bootstrap/variables.tf
data/data/azure/dns/dns.tf
data/data/azure/dns/variables.tf
data/data/azure/main.tf
data/data/azure/master/variables.tf

From the Private DNS Overview Doc [here][1]
```
The virtual network needs to be empty (that is, no VM records exist) when it initially (that is, for the first time) links to a private zone as a registration or resolution virtual network. However, the virtual network can then be non-empty for future linking as a registration or resolution virtual network, to other private zones.
```
Therefore, it looks like there needs to be an explicit dependency between private zone and VMs being created in the VNET.
Moving the private zone resource to main.tf and making bootstrap, masters, dns module consume a variable with value from private zone resource, makes terraform create the DNS Zone before creating any resources from those modules.
There is hope that the constraint might be lifted when private …

data/azure: create an explicit dependency on private zone before VMs are created

---

data/data/azure/master/master.tf

Master Machines are named `<id>-master-<idx>`, while the terraform creates VMs with name `<id>-master<idx>`. Equality is required for adoption in the cluster.
/cc @wking @jstuever

data/azure: make machine object name and VM name created by terraform same

---

hack/build.sh

ART copies occasional snapshots from upstream repositories like this one into dist-git repositories for their builds.  That means their commit hashes diverge from ours, because they have a different history behind them.  Tree hashes should still match, but we don't want to have to explain the difference between commits and trees to users.  ART is going to set the `SOURCE_GIT_COMMIT` environment variable for us with the associated upstream commit.  With this commit, we'll use that when it's set, and fall back to querying the local repository when it isn't.

hack/build: Use SOURCE_GIT_COMMIT if set

---

docs/user/aws/install.md

The OS/arch suffix was an artifact of our GitHub release approach (e.g. [here][1]).  With the new mirror approach, the flow is going to be more like:
```console
$ wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-install-linux-4.1.0-rc.5.tar.gz
$ tar xf openshift-install-linux-4.1.0-rc.5.tar.gz
$ ./openshift-install ...
But folks could install into their `PATH`, and our current docs prefer the in-the-`PATH` form, so that's what I've gone with here.
[1]: https://github.com/openshift/installer/releases/tag/v0.16.1

docs/user/aws/install: openshift-install-linux-amd64 -> openshift-install

---

pkg/types/aws/defaults/platform.go
platformtests/aws/default_instance_class_test.go

Some regions have per-zone support differences for available instance classes.  For example, us-west-2 has m4 instances in zones a through c, but [not in zone d][1].  It supports m5 instances in all four zones.
Unfortunately, we can't switch to just using the reserved-instance offerings, because Paris claims those for m4.large in all three of its zones:
```console
$ AWS_PROFILE=ci aws --region eu-west-3 ec2 describe-reserved-instances-offerings --instance-tenancy default --instance-type m4.large --product-description 'Linux/UNIX' --filters Name=scope,Values='Availability Zone' | jq -r '[.ReservedInstancesOfferings[].AvailabilityZone] | sort | unique[]'
eu-west-3a
eu-west-3b
eu-west-3c
```
but still does not price on-demand compute instances for that region:
```console
$ AWS_PROFILE=ci aws …
```

Bug 1713157: pkg/types/aws/defaults/platform: Default us-west-2 to m5

---

pkg/asset/installconfig/azure/session.go

Installer uses `NewAuthorizerFromFileWithResource` [here][1], which uses `GetSettingsFromFile` [here][2] to locate and load the file with auth credentials.
`GetSettingsFromFile` [here][2] uses the `AZURE_AUTH_LOCATION` env [here][3] to locate the file with no way to override or specify explicitly.
Currently the installer uses the hard-coded location `~/.azure/osServicePrincipal.json` to load the credentials. But for CI, it would be important to override this
location to another location like we do for AWS [here][4]. So this change allows users to set `AZURE_AUTH_LOCATION` env to provider installer custom location to auth file.
[1]: https://github.com/Azure/go-autorest/blob/v12.0.0/autorest/azure/auth/auth.go#L243
[2]: https://github.com/Azure/go-autorest/blob/v12.0.0/autorest/azure/auth/au …

azure: allow installer to consume `AZURE_AUTH_LOCATION` env for credentials file

---

cmd/openshift-install/gather.go
pkg/terraform/exec/state.go
pkg/terraform/gather/aws/ip.go
pkg/terraform/gather/libvirt/ip.go
pkg/terraform/gather/openstack/ip.go
pkg/terraform/state.go

- pkg/terraform: utilize the vendored terraform to read tfstate
Utilizing the vendored statefile serialize/deserialize helps installer to no worry about the statefile
version conversions. Installer can always assume to use the latest/chosen version of state file from vendored code.
For example, terraform 0.12 moves the terraform state to version 4, compared to version 3. With this change installer can assume the terraform state
deserialized for use will always be version 4, as it will be upconverted by vendored terraform statefile package.
- pkg/terraform: add gather package to store platform specific code from terraform
This adds bootstrap and control plane hosts ip gather from state file for platforms.
- cmd/openshift-install: update gather code to utilize new terraform packages
/cc …

gather: update the state handling for terraform 0.12

---

data/data/bootstrap/files/usr/local/bin/approve-csr.sh

`touch /opt/openshift/.bootkube.done` [1] from bootkube.service creates the file on successful completion.
The approve-csr needs to stop approving CSRs after bootkube has finshed successfully, but PR 1747 [2] has wrong file location in the while condition.
[1]: https://github.com/openshift/installer/blob/1723ee626f17c479d14841d167f45a2e5d03bc7f/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template#L299
[2]: https://github.com/openshift/installer/commit/c5d4d0f3ab3b0e65cb8d6af3ff6dfb3162dfa1d6
/cc @wking 
/cc @sjenning 
^^ as he noticed this behavior that approve-csr was active after bootkube completed.
Previous discussion why systemd constructs wouldn't work very well https://github.com/openshift/installer/pull/1747#discussion_r284525835

data/approve-csr.sh: fix the exit condition to use correct file path for bootkube done

---

data/data/azure/main.tf
data/data/azure/vnet/common.tf
data/data/azure/vnet/outputs.tf
data/data/azure/vnet/variables.tf
data/data/azure/vnet/vnet.tf

Previous commit [1] created explicit deps to make sure VMs were not created before internal DNS zone and VNET attachement.
There is still cases where LBs etc like resources in VNET block the internal DNS zone creation because of azure issues [2]
[1]: https://github.com/openshift/installer/commit/08c8bc55881197210f162b1587c38f352759a73f
[2]: https://github.com/MicrosoftDocs/azure-docs/issues/13728
/cc @jstuever @wking

data/azure: create explicit deps to internal dns zone before any resource in vnet

---

data/data/manifests/bootkube/cvo-overrides.yaml.template
docs/user/troubleshooting.md

4.1 has branched off, so we can [bump master to track stable-4.2][1]. This bump is like the previous 4cc6e707c2 (#1599).
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1715108

Bug 1715108: data/data/manifests/bootkube/cvo-overrides: Move to stable-4.2

---

cmd/openshift-install/gather.go
data/data/bootstrap/files/usr/local/bin/installer-gather.sh
pkg/terraform/gather/azure/ip.go

This change enables the gather bootstrap subcommand to output the
necessary commands to execute based on an Azure cluster's tfstate.
https://jira.coreos.com/browse/CORS-1099

gather: add support for azure

---

README.md

The Bare Metal and vSphere platforms are no longer experimental. They should not be listed as experimental in the README.

README: remove experimental designation for bare metal and vSphere

---

data/data/azure/bootstrap/main.tf
data/data/azure/master/master.tf

The Azure ARM API requires that a username and password are provided
when creating a VM, even if it isn't going to be used. RHCOS doesn't
actually apply this password because WALA (the Azure Linux agent) isn't
shipped in the OS. This change just aims to make this fact more clear to
future readers.

data/azure: clarify that the password isn't used

---

pkg/asset/machines/libvirt/machines.go

Volume should be identified by their names and their paths should be left to their container pools. This change is needed to allow for custom storage locations.
This is the needed update in Installer for the actual change in the libvirt actuator: https://github.com/openshift/cluster-api-provider-libvirt/pull/144
Fixes #308.

machines/libvirt: Drop volume paths

---

upi/aws/cloudformation/01_vpc.yaml
upi/aws/cloudformation/02_cluster_infra.yaml
upi/aws/cloudformation/03_cluster_security.yaml
upi/aws/cloudformation/04_cluster_bootstrap.yaml
upi/aws/cloudformation/05_cluster_master_nodes.yaml
upi/aws/cloudformation/06_cluster_worker_node.yaml

Because we can no longer use "UPI" in customer-facing documentation and the CloudFormation templates in /installer are published in /openshift-docs, I want to change the source templates instead of having to always reproduce the fix in the docs repo.
I'm making a few other style and changes to the parameter descriptions.

Text edits for the CloudFormation templates

---

docs/user/azure/install.md

For the time being, it is necessary to manually approve the CSRs for the
compute nodes.

docs/azure: add instructions for approving CSRs

---

data/data/openstack/service/main.tf

Two checks within the haproxy-watcher.sh script use the following conditionals:
`if [[ $MASTERS -eq "" ]]`
`if [[ ! $CHANGED -eq "" ]]`
These are apparently invalid expressions, as the following errors are generated when the script is run, respectively:
`./haproxy-watcher.sh: line 29: [[: 192.168.126.24 : syntax error: invalid arithmetic operator (error token is ".168.126.24 ")`
`./haproxy-watcher.sh: line 20: [[: 6,13c6: value too great for base (error token is "13c6")`
Changing the conditionals to use the `-z` operator appears to fix the errors and preserve the intended functionality.

Fix /usr/local/bin/haproxy-watch.sh if-conditionals

---

pkg/asset/installconfig/openstack/openstack.go

the CLI showing 'RegionOne' but it only accepts 'regionOne'
Fixes #1810

update default Region name

---

data/data/openstack/bootstrap/main.tf
data/data/openstack/masters/main.tf

The convention for the fully-qualified names is
`master-$index.$cluster_name.$domain_name`, but the hostnames we were
setting were in the `$cluster_name-master-$index` format.
The master and bootstrap Ignition configs now drop the `$cluster_name`
prefix and only set the `master-$index` / `bootstrap` part.

data/data/openstack: Remove cluster name from servers

---

docs/user/troubleshooting.md

`machine-api-controllers` should now be used instead of
`clusterapi-manager-controllers`

Refresh troubleshooting doc to use machine api

---

docs/dev/libvirt/README.md

Instead of telling what the content of a manifest should be like, provide a command to modify it as needed.

libvirt,docs: Make console workaround a bit easier

---

pkg/asset/manifests/network.go
pkg/types/installconfig.go
pkg/types/validation/installconfig.go
pkg/types/validation/installconfig_test.go
pkg/validate/validate.go

As a step toward cluster proxies, add support for proxies to the InstallConfig. This PR creates the `Proxy` type struct and adds it to the InstallConfig. It also adds validation and unit tests for the validation.
Jira: [CORS-1075](https://jira.coreos.com/browse/CORS-1075)
Related PRS: openshift/api#335, openshift/cluster-config-operator#66
This is a work in progress but I am looking for feedback:
- I think this is close so I need to know what is missing
- Confirm: httpProxy & httpsProxy must include scheme, i.e. start with http:// or https://
- Do we need further validation?
- Suggestions on how to validate NoProxy. Currently "bad-proxy" receives no error when passed to validate.DomainName
Just realized I also need to fill in the commit messages.

Add Proxy to InstallConfig

---

pkg/types/validation/installconfig.go
pkg/types/validation/installconfig_test.go
pkg/validate/validate.go
pkg/validate/validate_test.go

the clustername is a subdomain [1] when we create the private DNS zone ie `clustername.basedomain`
but when creating the public records, clustername is a dns label [1] as we create records under the `basedomain`
So the clustername needs to be valid subdomain but can be max 63 bytes, compared to currently allowed 255 bytes.
[1]: https://tools.ietf.org/html/rfc1123
/cc @openshift/openshift-team-installer @csrwng

restrict clustername validation to include DNS subdomain and DNS label requirements.

---

pkg/asset/machines/openstack/machines.go

With openshift/machine-api-operator#315 the Machine API Operator
doesn't have access to the `kube-system` namespace anymore.
We now need to issue a CredentialsRequest in MAO and retrieve it from
the `openshift-machine-api` namespace here.
Needs openshift/machine-api-operator#324

openstack: Retrieve namespaced credentials

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

This is a prep step for folding all mco component images into one mco image.
A corresponding mco image flag has been added in the MCO repo via openshift/machine-config-operator#847
Related-to: openshift/machine-config-operator#739
Related-to: openshift/machine-config-operator#847
Required-by: openshift/machine-config-operator#850
cc: @runcom

bootkube: add mco image

---

Gopkg.lock
data/data/azure/vnet/vnet.tf
pkg/asset/machines/azure/machines.go
pkg/asset/machines/azure/machinesets.go
vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1alpha1/azuremachineproviderconfig_types.go

With changes in the cluster-api-provider-azure from https://github.com/openshift/cluster-api-provider-azure/pull/35, the Azure IPI fails to create worker VMs like
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/4006/rehearse-4006-pull-ci-openshift-origin-master-e2e-azure/1/artifacts/e2e-azure/must-gather/namespaces/openshift-machine-api/pods/machine-api-controllers-c95fb75b5-rzjks/machine-controller/machine-controller/logs/current.log
```console
2019-06-07T19:38:06.7703507Z E0607 19:38:06.770317       1 actuator.go:79] failed to reconcile machine ci-op-pqj0zh18-849ce-9765f-worker-qg7fj: failed to create nic ci-op-pqj0zh18-849ce-9765f-worker-qg7fj-nic for machine ci-op-pqj0zh18-849ce-9765f-worker-qg7fj: MachineConfig subnet is missing on machine …
```

machines/azure: Set subnets for control plane and compute machines 

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

The command line option for mco image to `podman run bootstrap` is
indented incorrectly. 
Really nitpicky, but I noticed it when rebasing kni-installer

bootkube: fix indentation of mco image option

---

upi/aws/cloudformation/05_cluster_master_nodes.yaml
upi/aws/cloudformation/06_cluster_worker_node.yaml

Noticed when researching the io1 volumes and configurability of root volumes the installer overrides the default 16G size of the root RHCOS volume to 120G. Changing the CloudFormation templates to match for both masters and workers.

[AWS] Correcting UPI gp2 volumes to match IPI sizes

---

cmd/openshift-install/create.go

The message reported by the cluster-version operator is already fairly clear on this being a timeout error.  For example, with this commit,
```
failed to initialize the cluster: Some cluster operators are still updating: console, image-registry: timed out waiting for the condition
```
will become:
```
failed to initialize the cluster: Some cluster operators are still updating: console, image-registry
```

cmd/openshift-install/create: Drop "timed out waiting for the condition"

---

pkg/gather/ssh/agent.go
pkg/gather/ssh/ssh.go

This attempts to use the user's existing SSH agent when gathering
diagnostics -- if the SSH_AUTH_SOCK environment variable is set and no
keys are explicitly given.  This is important as some users may not
have their private keys available on disk.
Fixes: #1865

pkg/gather/ssh: Attempt to use existing SSH agents

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

The kube-apiserver is switching to use hyperkube, but we cannot break in the interim,
so we need to pass old and new image, then switch the flag back
We want to use hyperkube instead of hypershift. To do so in an orderly fashion will take a few steps with pulls to different repos.
--newImage allows us to change our image to one with a different binary without breaking functionality at intermediate steps
1. allow --newImage
1. installer passes --image=old and --new-image=new
1. operator render uses --new-image only
1. installer passes --image=new and --new-image=new
1. operator switches back to --image
1. installer passes --image=new
1. operator removes --new-image
This is step 2

bootkube: new image for kube-apiserver

---

data/data/openstack/variables-openstack.tf
docs/user/openstack/README.md

openstack: update the doc link for up to date info
https://docs.openstack.org/os-client-config/latest
has been superceded by openstacksdk, also, add a link
for OS_CLOUD setting as well.

openstack:update doc link

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

In order to switch to using hyperkube, we have a little dance of rachets to move through.
This updates the existing flag name to match the temporary flag.  Step 4.
Next from https://github.com/openshift/installer/pull/1881
We want to use hyperkube instead of hypershift. To do so in an orderly fashion will take a few steps with pulls to different repos.
--newImage allows us to change our image to one with a different binary without breaking functionality at intermediate steps
1. allow --newImage
1. installer passes --image=old and --new-image=new
1. operator render uses --new-image only
1. installer passes --image=new and --new-image=new
1. operator switches back to --image
1. installer passes --image=new
1. operator removes --new-image

bootkube: pass the hyperkube image as main image

---

pkg/destroy/aws/aws.go

We ran into the situation that the call to get resources by tag was returning an s3 bucket arn, however, when querying the s3 api directly, the bucket didn't exist. The uninstaller should not fail a delete when the item it's trying to delete doesn't exist.
Fixes https://github.com/openshift/installer/issues/1886

pkg/destroy/aws: do not fail uninstall on absent s3 bucket

---

pkg/asset/machines/libvirt/machines.go

Bump up worker resources so that all the prometheus pods can start.
Fixes #1860.

Bump worker resources

---

pkg/destroy/openstack/openstack_deprovision.go

platform: openstack
before delete router, we should remove gateway otherwise
a 409 (conflict) error will block the deletion of the router.
Fixes: #1859

[openstack] Remove gateway before delete router

---

pkg/asset/machines/azure/machines.go

Azure actuator already allows to set both vnet and managed identity
explicitly. Once the installer does the same, logic of implicit naming
of both resources can be dropped from the actuator. Installer can
then choose any name for the resource.

Azure assets: set machine vnet and managed identity explicitly

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

To swap images used by the kas-o, we needed a temporary flag.  We no longer need to pass that flag.
This is part 6 of the 7 part plan.
/assign @abhinavdahiya 
cleaning cruft as promised.

bootkube: stop passing temporary image flag to kas

---

data/data/bootstrap/files/etc/profile.d/proxy.sh.template
data/data/bootstrap/files/etc/systemd/system.conf.d/10-default-env.conf.template
docs/dev/proxy.md
pkg/asset/ignition/bootstrap/bootstrap.go
pkg/asset/manifests/proxy.go

Modification of `bootstrapTemplateData` struct to include proxy requirements.
Modification of `getTemplateData` and `addStorageFiles` to support proxy
Added:
- /etc/profile.d/proxy.sh.template
- /etc/systemd/system.conf.d/10-default-env.conf.template

Add proxy configuration to bootstrap node

---

data/data/rhcos.json

This moves `master` off of `410` builds as a base and on to `420` builds.
/cc @cgwalters @runcom @miabbott @darkmuggle @abhinavdahiya @imcleod

rhcos: Bump to 420.8.20190624.0

---

pkg/asset/cluster/tfvars.go

OpenShift telemetry is currently unable to report _how_ a cluster was
installed (i.e. user-provisioned vs installer-provisioned). We currently
use a heuristic to try to determine this information.
This patch adds a ConfigMap immediately before cluster creation with
information about the installer. This ConfigMap is not present when the
user provisions the cluster themselves since it isn't injected until the
Terraform variables are generated. This ConfipMap contains the installer
version and the name of the invoker (can be overridden with the
OPENSHIFT_INSTALL_INVOKER environment variable). This will allow us to
determine whether a cluster was user-provisioned or installer-
provisioned, whether or not a custom build of the installer was used,
and who created the cluster (e.g. Hive, CI).

asset/cluster: inject installer info when creating

---

pkg/types/defaults/installconfig.go
pkg/types/gcp/defaults/platform.go
pkg/types/gcp/doc.go
pkg/types/gcp/machinepools.go
pkg/types/gcp/platform.go
pkg/types/gcp/validation/machinepool.go
pkg/types/gcp/validation/machinepool_test.go
pkg/types/gcp/validation/platform.go
pkg/types/gcp/validation/platform_test.go
pkg/types/installconfig.go
pkg/types/machinepools.go
pkg/types/validation/installconfig.go
pkg/types/validation/installconfig_test.go

Adds required types for creating the GCP platform from the install config, including validation and tests.
Does not include defaults, but has a stub placeholder.
Jira: CORS-1114

Add required GCP types

---

pkg/types/conversion/installconfig.go
pkg/types/conversion/installconfig_test.go

Currently the error returned is failed to upconvert install config: cannot upconvert from version and empty version is not visible to users explicitly.
Combines (supercedes) #1764 & #1901
4.2.0 bz: https://bugzilla.redhat.com/show_bug.cgi?id=1723565
/cc @eparis

Bug 1722221: [release-4.1] blank api version

---

pkg/types/azure/machinepool.go
pkg/types/azure/platform.go

We are not currently using UserTags or Zones in Azure. This PR removed them. 
https://jira.coreos.com/browse/CORS-1090

azure: reduce the install-config api to smallest set

---

.github/ISSUE_TEMPLATE.md

With the current template, people just fill in the name of their platform, leaving the list of platforms as is. This makes it a bit hard to label issues. Let's modify the template a bit so reporters simply remove the irrelevant platforms from the list and the issue description only mentions the relevant platform.

issue-template: Make it easy to remove irrelevant platforms

---

pkg/asset/machines/master.go
pkg/asset/machines/worker.go
pkg/tfvars/azure/azure.go
pkg/types/azure/defaults/machines.go
pkg/types/azure/defaults/platform.go

This PR attempts to set the default machine type by region. According to Microsoft documentation, the Dsv3-Series is generally available across all regions. Master nodes are assigned Standard_D4s_v3 while worker nodes and default machine type is set to Standard_D2s_v3.
https://jira.coreos.com/browse/CORS-1091

azure: set default machine types by region

---

Gopkg.lock
pkg/destroy/openstack/openstack.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/apiversions/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/apiversions/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/apiversions/results.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/apiversions/urls.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/l7policies/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/l7policies/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/l7policies/results.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/l7policies/urls.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/results.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/urls.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/results.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/urls.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/monitors/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/monitors/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/monitors/results.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/monitors/urls.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/results.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/urls.go

This PR adds support for Load Balancer deletion on cluster destroy.
It detects when tag is supported in Octavia and if it is, uses it to filter and so delete Octavia resources, otherwise uses the descriptions field to filter the resources.

openstack: delete loadbalancer resources

---

pkg/asset/machines/azure/machines.go
pkg/asset/machines/worker.go
pkg/types/azure/machinepool.go
pkg/types/azure/validation/machinepool.go
pkg/types/azure/validation/machinepool_test.go

This also updates the default disk size for Azure to 128 GB
This brings up the IOPS to 500 and through-put to 100 MB/second [1] to get it closer to AWS defaults.
[1]: https://azure.microsoft.com/en-us/pricing/details/managed-disks/
/cc @jhixson74 @smarterclayton

 types/azure: allow specifying the disk size for pools 

---

docs/user/openstack/README.md

current doc contains wrong info
https://github.com/openshift/installer/blob/master/pkg/asset/rhcos/image.go#L64
only support rhcos
and per test, change image name to rhcos-xxx such as rhcos-112
ERROR
ERROR Error: Your query returned no results. Please change your search criteria and try again.
ERROR
ERROR   on ../../../../../../tmp/openshift-install-590981577/bootstrap/main.tf line 58, in data "openstack_images_image_v2" "bootstrap_image":
ERROR   58: data "openstack_images_image_v2" "bootstrap_image" {

openstack: Fix rhcos version wrong info in doc

---

pkg/destroy/openstack/openstack.go

The load balancer destroy step on the cluster destroy is expecting
for the cloud to have octavia service enabled, in case it is not
enabled the destroy command will fail. This commit fixes the issue
by skipping load balancers deletion in case no octavia endpoints
are enabled, which avoids a fatal error.
Fixes #1919

OpenStack: fix cluster destroy

---

data/data/openstack/topology/sg-master.tf

The mdns port is going to be used for updating the internal DNS
records necessary for the installation to succeed (the master & etcd A
as well as the SRV records).
Some OpenStack deployments allow UDP traffic by default, but some
don't so we need to create this Security Group Rule explicitly.

data/data/openstack: Open UDP 5353 (mdns) port

---

pkg/destroy/aws/aws.go
pkg/destroy/aws/register.go
pkg/destroy/azure/azure.go
pkg/destroy/azure/register.go
pkg/destroy/destroyer.go
pkg/destroy/libvirt/libvirt.go
pkg/destroy/libvirt/register.go
pkg/destroy/openstack/openstack.go
pkg/destroy/openstack/register.go
pkg/destroy/providers/registry.go
pkg/destroy/providers/types.go

Moves the destroyer registry to its own package. This decouples individual destroyers from their parent destroy package which has a dependency on pkg/asset/cluster which ends up having a dependency on a lot of the pkg/terraform/* code. These dependencies make it much harder to vendor installer code in hive.

Decouple Destroyer interface and registry from destroy command

---

pkg/asset/manifests/infrastructure.go

.status.platformType was being set twice by changes in https://github.com/openshift/installer/pull/1930
This move the assignment to single location after the switch.

manifests/infrastructure.go: drop double assignment for .status.platformType

---

pkg/types/aws/defaults/platform.go
platformtests/aws/default_instance_class_test.go

AWS allows m4 class for reserved instances in all AZs for ap-northeast-2
```console
aws --region ap-northeast-2 ec2 describe-reserved-instances-offerings --instance-tenancy default --instance-type m4.large --product-description 'Linux/UNIX' --filters Name=scope,Values='Availability Zone' | jq -r '[.ReservedInstancesOfferings[].AvailabilityZone] | sort | unique[]'
ap-northeast-2a
ap-northeast-2b
ap-northeast-2c
```
But the on-demand instances in ap-norteast-2b was failing with error
```
Unsupported: Your requested instance type (m4.xlarge) is not supported in your requested Availability Zone (ap-northeast-2b). Please retry your request by not specifying an Availability Zone or choosing ap-northeast-2a, ap-northeast-2c.
```
So moving to m5 class for ap-northeast-2 should allow creating …

 Bug 1725524: types/aws/default: move ap-northeast-2 to m5 instance class 

---

data/data/gcp/main.tf
data/data/gcp/network/common.tf
data/data/gcp/network/firewall-compute.tf
data/data/gcp/network/firewall-control.tf
data/data/gcp/network/network.tf
data/data/gcp/network/outputs.tf
data/data/gcp/network/variables.tf
data/data/gcp/variables-google.tf

This change adds the terraform bits to create the network infrastructure
for the google platform. It creates the control and compute networks for
the control plane and compute instances. It also creates firewall rules
to allow ingress ping and internal tcp.

google: create network infrastructure

---

data/data/gcp/bootstrap/main.tf
data/data/gcp/bootstrap/variables.tf
data/data/gcp/main.tf
data/data/gcp/master/main.tf
data/data/gcp/master/outputs.tf
data/data/gcp/master/variables.tf
data/data/gcp/network/common.tf
data/data/gcp/network/firewall-compute.tf
data/data/gcp/network/firewall-control.tf
data/data/gcp/network/network.tf
data/data/gcp/network/outputs.tf
data/data/gcp/network/variables.tf
data/data/gcp/variables-google.tf

This change adds the terraform bits to create the bootstrap and control
plane virtual machines for the google platform. It also creates groups
for use by the load balancers with one for bootstrap and one for each
control plane zone.

google: create virtual machines

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

Remove references to mcc/mcd/mcs and setupetcd images now that the MCO has 1
super-image containing all of the sub-images
Requires: openshift/machine-config-operator#850
Related-to: openshift/machine-config-operator#739

bootkube.sh: remove image refs for mco components

---

data/data/aws/vpc/sg-master.tf
data/data/aws/vpc/sg-worker.tf

1) Allow GENEVE (6081) between all nodes (masters & workers)
2) Allow OVN databases (6641 & 6642) between all masters
3) Allow OVN databases (6641 & 6642) between masters and workers, but not between workers themselves
@squeed  @pecameron @danwinship @JacobTanenbaum @rcarrillocruz
[question: should these be enabled by default even if the install isn't using ovn-kubernetes? Or, how do SG rules get selectively added based on specific network plugin requirements? eg when running ovn-kubernetes we don't need VXLAN between nodes, and when running openshift-sdn we don't need GENEVE...]

aws: allow GENEVE (6081) and OVN database ports (6641 & 6642)

---

data/data/openstack/main.tf
data/data/openstack/masters/main.tf
data/data/openstack/masters/variables.tf

These variables are going to be used by the machine-config-operator to
seed the initial DNS and LB static pod configuration on each master.

data/data/openstack: Generate master clustervars

---

hack/tf-fmt.sh

So that the output is more useful and actionable. Otherwise, you just see the list of files in the CI job (or any other users of this script) output and that's not great.

Make `terraform fmt` output diff

---

data/data/rhcos.json

updates the rhcos.json from https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.2/420.8.20190703.0/meta.json

data/data/rhcos.json: update the bootimage to 420.8.20190708.2 for CRI-O 1.14

---

pkg/asset/installconfig/basedomain.go
pkg/asset/installconfig/gcp/dns.go
pkg/asset/installconfig/gcp/gcp.go
pkg/asset/installconfig/gcp/session.go
pkg/asset/installconfig/installconfig.go
pkg/types/gcp/validation/platform.go

Add interactive terminal prompts to allow users to select region, project id and base domain when using the GCP platform. Automatically populate available regions and base domains based on project. Validate project ID.
WIP: Working on completing regions, considering moving region validation to work in both install config and terminal prompts. 
[CORS-1115](https://jira.coreos.com/browse/CORS-1115)

Add terminal prompts for GCP: region, project id, & base domain.

---

data/data/bootstrap/baremetal/README.md
data/data/bootstrap/baremetal/files/etc/coredns/Corefile
data/data/bootstrap/baremetal/files/etc/dhcp/dhclient.conf
data/data/bootstrap/baremetal/files/etc/keepalived/keepalived.conf.tmpl
data/data/bootstrap/baremetal/files/usr/local/bin/coredns.sh
data/data/bootstrap/baremetal/files/usr/local/bin/fletcher8
data/data/bootstrap/baremetal/files/usr/local/bin/get_vip_subnet_cidr
data/data/bootstrap/baremetal/files/usr/local/bin/keepalived.sh
data/data/bootstrap/baremetal/systemd/units/coredns.service
data/data/bootstrap/baremetal/systemd/units/keepalived.service
docs/design/baremetal/networking-infrastructure.md
pkg/asset/ignition/bootstrap/bootstrap.go

This is broken out from https://github.com/openshift/installer/pull/1873. See individual commits for details, but some of the configuration on the bootstrap node should only be enabled for the baremetal platform, so we move these to data/data/bootstrap/baremetal and adjust the code to conditionally read this depending on the platform name.

bootstrap: add platform-specific configuration for baremetal

---

data/data/gcp/main.tf

Fixes variable names to correspond to variables in `variables-gcp.tf`

[gcp] data/data: fix machine var names

---

pkg/destroy/gcp/network.go

Some local routes in a vpc cannot be deleted. It should not stop us from trying to delete the vpc itself.

[gcp] pkg/destroy: call network destroy regardless of route delete errors

---

pkg/types/validation/installconfig.go
pkg/types/validation/installconfig_test.go

We were passing the platform type rather than the incorrect value when creating the error message for an invalid platform. This caused the error message to look like this:
```
FATAL failed to fetch Install Config: failed to generate asset "Install Config": invalid install config: platform: Invalid value: types.Platform{AWS:(*aws.Platform)(nil), Azure:(*azure.Platform)(nil), GCP:(*gcp.Platform)(nil), Libvirt:(*libvirt.Platform)(nil), None:(*none.Platform)(nil), OpenStack:(*openstack.Platform)(nil), VSphere:(*vsphere.Platform)(nil)}: must specify one of the platforms (aws, azure, gcp, none, openstack, vsphere)
```
when it should look like this:
```
FATAL failed to fetch Install Config: failed to generate asset "Install Config": invalid install config: platform: Invalid value: "foobar": must …
```

pkg/types/validation/installconfig: Fix platform value in error message

---

data/data/gcp/bootstrap/main.tf
data/data/gcp/bootstrap/output.tf
data/data/gcp/main.tf
data/data/gcp/master/main.tf
data/data/gcp/master/outputs.tf
data/data/gcp/network/external-lb.tf
data/data/gcp/network/firewall-control.tf
data/data/gcp/network/internal-lb.tf
data/data/gcp/network/outputs.tf
data/data/gcp/network/variables.tf

This change adds internal and external load balancers to the google
provider. Due to the nature of gcp load balancing, there are a few
challenges to consider:
- The internal balancer uses backend services. It will be difficult to
maintain their memberships.
- The external balancer uses target pools, which only supports legacy
google_compute_http_health_check.

gcp: Create public and private load balancers

---

data/data/config.tf
data/data/gcp/dns/base.tf
data/data/gcp/dns/variables.tf
data/data/gcp/main.tf
data/data/gcp/master/outputs.tf
data/data/gcp/variables-gcp.tf
pkg/asset/cluster/tfvars.go
pkg/tfvars/gcp/gcp.go
pkg/tfvars/tfvars.go

Adds resources for the internal DNS managed zone, its records and API record in the public zone.
Depends on https://github.com/openshift/installer/pull/1971

[gcp] add dns resources

---

data/data/gcp/network/network.tf
pkg/destroy/gcp/gcp.go
pkg/destroy/gcp/network.go

Based on internet-access-reqs docs [1], the private instances need Cloud-NAT [1] resources to allow egress to internet.
The Cloud NAT gateways provide an automatically scaling-ha way to access the internet, so creating one per subnet (master and worker) should be
enough.
Cloud NATs also require a Cloud Router [3] for the control-plane, no data flows through Cloud router. This change creates one Cloud Router for the cluster.
Both the resources are regional and created in the same region as the cluster.
Also adds:  pkg/destroy/gcp: add cleanup for cloud routers
the nat-gateways are automatically cleaned up on deletion of cloud routers
[1]: https://cloud.google.com/vpc/docs/vpc#internet_access_reqs
[2]: https://cloud.google.com/nat/docs/overview
[3]: …

 data/gcp/network: create nat-gateways per subnet for egress from private instances

---

pkg/destroy/gcp/network.go

We create regional backend services and not global ones. This fixes the gcp destroyer to destroy the right kind of resource.

[gcp] destroy region backend services

---

pkg/destroy/gcp/gcp.go
pkg/destroy/gcp/network.go

Other destroyers only output errors at the debug level. This makes the
gcp destroyer behave the same way.

[gcp] pkg/destroy/gcp - use debug for error logging

---

pkg/destroy/gcp/gcp.go
pkg/destroy/gcp/network.go

Adds deletion of HTTP health checks to the GCP destroyer.

[gcp] destroy legacy HTTP health checks

---

pkg/asset/manifests/network.go

In OpenShift 3.x, Service.ExternalIP was not allowed to be set by default. Administrators had to explicitly whitelist network blocks.
4.1 allowed all ExternalIP values. We re-added the ability to restrict ExternalIP in 4.2. Correspondingly, new clusters should be initialized in a default-deny state.
(API PR: https://github.com/openshift/api/pull/347)

network: block ExternalIPs by default.

---

data/data/gcp/bootstrap/main.tf
data/data/gcp/bootstrap/output.tf
data/data/gcp/bootstrap/variables.tf
data/data/gcp/main.tf
data/data/gcp/network/external-lb.tf
data/data/gcp/network/internal-lb.tf
data/data/gcp/network/variables.tf
data/data/gcp/variables-gcp.tf
pkg/destroy/bootstrap/bootstrap.go

This changes removes the bootstrap instance from the cluster's load
balancers and then deletes the bootstrap instance and instance_group
prior to destroying bootstrap module. This removes the dependencies
of the bootstrap assets so that terraform does not destroy the load
balancers.

gcp: workaround terraform dependencies with bootstrap destroy

---

Gopkg.lock
pkg/destroy/openstack/openstack.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/subnetpools/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/subnetpools/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/subnetpools/results.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/subnetpools/urls.go

This PR adds support for subnet pool deletion on cluster destroy. It uses tags to filter the subnet pools and delete them.

OpenStack: Add subnet pools destroy

---

data/data/openstack/bootstrap/main.tf
data/data/openstack/masters/main.tf

According to https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#node-name-4 to enable OpenStack cloud provider hostnames, node names & nova names must match.
This patch sets correct hostnames for masters and the bootstrap machine during the initial deployment.
To set hostnames for workers and masters that are added later we also need: https://github.com/openshift/machine-config-operator/pull/964
Reverts: #1820

data/data/openstack: set correct hostnames for machines during bootstrap

---

data/data/libvirt/bootstrap/main.tf
data/data/libvirt/bootstrap/variables.tf
data/data/libvirt/main.tf
data/data/libvirt/volume/main.tf
data/data/libvirt/volume/variables.tf
docs/dev/libvirt/README.md
pkg/asset/machines/libvirt/machines.go
pkg/terraform/exec/plugins/Gopkg.lock
pkg/terraform/exec/plugins/Gopkg.toml
pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/domain.go
pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/pool.go
pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/provider.go
pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_domain.go
pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_pool.go

Don't assume `default` storage pool and create a new custom one.
Fixes #1457.

Manage and use own storage pool

---

data/data/gcp/network/internal-lb.tf

This change limits the internal load balancer to only have the bootstrap
instance during bootstrap (before bootstrap destroy). This resolves a
bug where the masters are redirecting to themselves during this time.
Depends on #1993

gcp: limit internal load balancer during bootstrap 

---

data/data/gcp/dns/base.tf

similar to other platforms like AWS: https://github.com/openshift/installer/blob/37f72577e0dc6debc2facc52221531e6dd62abfd/data/data/aws/route53/base.tf#L53
/cc @csrwng @jstuever

data/gcp/dns: api.cluster_domain inside the VPC must point to internal LB for consistency

---

docs/dev/alternative_release_image_sources.md
pkg/asset/manifests/imagesourcepolicy.go
pkg/types/installconfig.go
pkg/types/validation/installconfig.go
pkg/types/validation/installconfig_test.go

These are minor doc updates based on my review of #1910. It seemed better to open a PR for docs than hold that up for code review.
Minor corrections to comments and developer reference docs related to the oc adm release mirrors.
/cc @abhinavdahiya

Update docs for release mirrors.

---

data/data/openstack/service/main.tf

The OpenStack deployment started failing with the following message:
Error: error pulling image "openshift/origin-coredns:v4.0": unable to pull openshift/origin-coredns:v4.0: image name provided is a short name and no search registries are defined in the registries config file.
That caused the `local-dns` service on the Service VM to fail which
resulted in none of the nodes receiving Ignition and booting up.
Specifying the `quay.io` registry explicitly fixes this issue.

data/data/openstack: Add registry to coredns image

---

data/data/gcp/bootstrap/main.tf
data/data/gcp/network/firewall-compute.tf
data/data/gcp/network/firewall-control.tf

This change ensures all of the "Name" fields in the terraform google
provider templates adhere to the max length of 63.

gcp: Ensure terraform object names have max length 63

---

pkg/destroy/bootstrap/bootstrap.go

This change simplifies libvirt's passing of the bootstrap_dns variable to
terraform when tearing down the bootstrap components. It is now more like like
the corresponding gcp code. Instead of writing a vars file to disk, it is now
set as a command line argument.

libvirt: simplify how bootstrap_dns is passed to terraform

---

pkg/asset/rhcos/image.go
pkg/types/aws/platform.go

ref: https://jira.coreos.com/browse/CORS-1103
for aws the new order for osImage is:
- env OPENSHIFT_INSTALL_OS_IMAGE_OVERRIDE
- platform.aws.amiID
- embedded ami for the region
/cc @crawford @openshift/openshift-team-installer

pkg/types/aws: allow specifying AMI ID for machines

---

cmd/openshift-install/gather.go
pkg/terraform/gather/gcp/ip.go

Adds support for the gather command for the GCP platform. 
There might be a more elegant way to parse the terraform state file for GCP using the unstructured package, but this implementation works and has error checking at each step.
[CORS-1123](https://jira.coreos.com/browse/CORS-1123)

Add gather support for gcp

---

pkg/types/machinepools.go

Correct typo for Azure.
Azure is the configuration used when installing on OpenStack.

correct typo for Azure

---

data/data/gcp/main.tf
data/data/gcp/network/common.tf
data/data/gcp/network/outputs.tf
data/data/gcp/variables-gcp.tf
pkg/tfvars/gcp/gcp.go

Currenlty the installer picks the zones for each machine when creating their Machine object, and then
terrafor code picks the zones again, this can lead to cases where the teo code-paths pick different results.
Using the zones from Machine objects and passing them to terraform directly reduce the possibility of the diff.

gcp: use the zones from machine objects in terraform

---

docs/user/metal/install_ipi.md

This fixes a copy/paste error in the docs for the baremetal
install-config. A worker host should have the 'worker' role,
not 'master'.

docs/metal: worker host should have role 'worker'

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
data/data/gcp/network/external-lb.tf
data/data/gcp/network/firewall-control.tf

Before this change, the internal health check was using an unencrypted
google_compute_http_health_check while trying to access the cluster over
an encrypted https port: 6443.
This change moves to the port 6080 where the api/readyz should be
available unencrypted for this use case.
This change also opens up 6443 on the masters through the load balancers.
Depends on openshift/cluster-kube-apiserver-operator#525

gcp: move external health_check to http port 6080

---

docs/user/metal/install_ipi.md

The "ns1" DNS record is currently required.  The intention is for this
to go away and be replaced by reading this VIP out of the
platformstatus field of the infrastructure resource.  That work is
underway, but this doc change reflects the current state of code.

baremetal: Note short-term requirement for ns1 DNS record.

---

pkg/asset/machines/azure/machines.go

This sets resource group explicitly for machines. We should remove unnecessary assumptions coming from the secret and be API input driven or fail otherwise.
Unless there's a reason to keep it we might drop location and rg requirement from the secret in follow ups for https://github.com/openshift/cluster-api-provider-azure/pull/55

Set resource group explicitly for machines

---

pkg/asset/cluster/tfvars.go

253126f introduced this so that our telemetry could distinguish between
a user, our CI, and other future invokers of the installer. There are
privacy concerns around collecting the actual username, so we'll just
use "user" instead.

asset/cluster: don't record usernames

---

pkg/types/openstack/validation/realvalidvaluesfetcher.go

In order to detect if Octavia service is enabled in the cloud
the service catalog must be retrieved. Right now, we rely on
the project domain to authenticate, and if this parameter
is not provided we set it as default. However, other clouds
could have another value for that parameter resulting in failure
when retrieving the catalog list. This commit fixes the issue by
using the user domain when no project domain is defined.

OpenStack: Fix Octavia support detection

---

pkg/asset/manifests/gcp/clouduid.go
pkg/asset/manifests/infrastructure.go
pkg/types/gcp/clouduid.go

Using a pre-generated configmap with a known UID makes it simpler to
identify and cleanup load balancer related resources generated by the
GCP provider for the cloud controller.

[gcp] Add load balancer UID asset to manifests and metadata

---

data/data/gcp/bootstrap/main.tf

There seemed to be some concerns about using an ephemeral ip address for the bootstrap node and its effects on the gather command. Although the tests were fine, why not just give it a static address?
Replace the current ephemeral external ip address for the bootstrap node with a static one. This will prevent a new ip address from being assigned to the bootstrap node in the event that the node is stopped and restarted. 

Add static external ip address to GCP bootstrap node.

---

pkg/asset/manifests/infrastructure.go
pkg/types/baremetal/platform.go
pkg/types/baremetal/validation/platform.go

We need to have these VIPs available in platform status so they are available to the static pod configurations rendered by MCO.

baremetal: Add VIPs to status.platformStatus.baremetal

---

data/data/baremetal/main.tf
data/data/baremetal/variables-baremetal.tf
pkg/tfvars/baremetal/baremetal.go

Rename the terraform os_image variable to bootstrap_os_image to make it clear that this boot image is only used for the bootstrap VM.
Related to openshift/installer#2037

baremetal: rename os_image to bootstrap_os_image

---

docs/user/metal/install_ipi.md

The ingress VIP is discussed both in docs/user/metal/install_ipi.md
and docs/design/baremetal/networking-architecture.md.  This option
already exists, but was not included in the sample configuration.

baremetal: Add ingressVIP to sample install config.

---

pkg/destroy/gcp/compute.go
pkg/destroy/gcp/dns.go
pkg/destroy/gcp/gcp.go
pkg/destroy/gcp/iam.go
pkg/destroy/gcp/network.go
pkg/destroy/gcp/storage.go

Updates GCP destroy to handle async call results by using the same
request id every time a particular item is deleted. The resulting
operation should return the latest results of the particular request.
It updates the destroy function interface to return a boolean indicating
whether there are items still pending to be deleted. It also returns a
slice of errors instead of a single error so that all items of a
particular type are attempted instead of up to the first failure.
Info log statements are now logged when an item is successfully deleted.

[gcp] pkg/destroy: handle async call results, log delete info messages

---

docs/dev/libvirt/README.md
docs/dev/libvirt/customization.md

Adds a comment about the `tt0` bridge for libvirt.
Fixes #708

Adds a customize doc for libvirt with tt0 bridge customization

---

pkg/destroy/gcp/compute.go
pkg/destroy/gcp/gcp.go

Adds code to delete disks that are prefixed with the cluster's infra
ID. Disks that are dynamically created should get this prefix when the
controller-manager is passed the infra ID as the --cluster-name
argument.

 [gcp] pkg/destroy: delete disks

---

data/data/azure/bootstrap/main.tf
data/data/azure/bootstrap/variables.tf
data/data/azure/main.tf
data/data/azure/master/master.tf
data/data/azure/master/variables.tf
data/data/azure/variables-azure.tf
pkg/asset/cluster/tfvars.go
pkg/asset/machines/azure/machines.go
pkg/asset/rhcos/image.go
pkg/tfvars/azure/azure.go

previously the terraform expected an Azure Image [1] provided to the cluster, but that approach had some disadvantages:
* the image needed to be created before creating the cluster
* the image location was hardcoded to a specific resource-group
And since RHCOS isn't avaiable on the Public Registry of images, the new flow is using the vhd blob from Azure storage and creating an Azure Image from it for the cluster.

azure: create an image for booting machines for the cluster from vhd blob

---

pkg/asset/installconfig/gcp/dns.go

Fixes bug in GCP installer prompts where validation fails on valid choices, because validation expects domains to be sorted. This would also be better UI on a long list of domains.
Installer prompts were only working by chance.
This fixes bug that looks like this: 
```
X Sorry, your reply was invalid: invalid base domain "gcp.devcluster.openshift.com"
```
where gcp.devcluster.openshift.com was a valid domain.

Sort GCP basedomains in installer prompts.

---

pkg/asset/installconfig/gcp/session.go

The function that creates a GCP session when using default credentials needs to pass a scope, just as the function for using JSON service account keys already does.
This fixes a bug when users have default gcloud credentials set to a valid service account which results in this error:
```
oauth2: cannot fetch token: 400 Bad Request
Response: {
"error": "invalid_scope",
"error_description": "Empty or missing scope not allowed."
}
```
Default credentials are:
```
1. A JSON file whose path is specified by the GOOGLE_APPLICATION_CREDENTIALS environment variable.
2. A JSON file in a location known to the gcloud command-line tool. On Windows, this is %APPDATA%/gcloud/application_default_credentials.json. On other systems, $HOME/.config/gcloud/application_default_credentials.json.
3. On Google …
```

GCP client: pass scope when using default credentials.

---

.github/ISSUE_TEMPLATE.md

Instead of updating this comment to list "baremetal" as a valid
platform type, just reference the README.md, which lists the platforms
currently supported by the installer.  That saves one more place to
update each time a platform is updated.

ISSUE_TEMPLATE.md: List baremetal and none as paltform types

---

data/data/gcp/bootstrap/main.tf
data/data/gcp/master/main.tf
pkg/asset/installconfig/clusterid.go
pkg/asset/installconfig/clusterid_test.go
pkg/asset/machines/gcp/machines.go
pkg/asset/machines/gcp/machinesets.go

The GCE kubelet uses the `os.Hostname()` to create node names and there's a har limit on hostnames to be 64 characters. based on [1]
On GCP, the hostnames are `<instance name>.c.<project-id>.internal` and since the project ids on GCP can be of max 30 characters, an instance name can be max 22 characters.
The instances created by a machineset have the `6` character of randomness added to machineset's name, therefore the max length of machineset's name can be 16 characters. Therefore to accomodate the pool's name and zone (as we create machineset per zone) :
the mastes machines are now `<infra-id>-m-<idx>` and
the worker machinesets are now `<infra-is>-w-<zone>`, where the infra-id can be max 12 characters on GCP.
[1]: https://tools.ietf.org/html/rfc2181#section-11
/cc @csrwng @jstuever

 gcp: reduce the length of the names of machines 

---

pkg/destroy/gcp/gcp.go
pkg/destroy/gcp/network.go

Handles the deletion of additional service LB related resources. Clears
health checks from both backend services and target pools so those
resources can be deleted last and we don't lose track of load balancers
that need to be deleted.

 [gcp] pkg/destroy: handle deletion of lb related resources

---

pkg/asset/installconfig/gcp/session.go

Fixes bug #2096 where we were passing formatted string, but not using the formatted string function.

Fix string fmt bug in saving credentials message.

---

pkg/asset/ignition/bootstrap/bootstrap.go
pkg/asset/kubeconfig/kubeconfig.go
pkg/asset/kubeconfig/loopback.go

This code generates a kubeconfig that uses localhost for API access. 
This is necessary due to a limitation with Azure internal load balancers. See limitation #2 here: https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-overview#limitations
"Unlike public Load Balancers which provide outbound connections when transitioning from private IP addresses inside the virtual network to public IP addresses, internal Load Balancers do not translate outbound originated connections to the frontend of an internal Load Balancer as both are in private IP address space. This avoids potential for SNAT port exhaustion inside unique internal IP address space where translation is not required. The side effect is that if an outbound flow from a VM in the backend pool attempts a flow to frontend …

azure: generate loopback kubeconfig to access API locally

---

data/data/gcp/bootstrap/main.tf
data/data/gcp/bootstrap/variables.tf
data/data/gcp/main.tf
data/data/gcp/master/main.tf
data/data/gcp/master/variables.tf
data/data/gcp/variables-gcp.tf
pkg/asset/cluster/tfvars.go
pkg/asset/machines/gcp/machines.go
pkg/asset/rhcos/image.go
pkg/rhcos/gcp.go
pkg/tfvars/gcp/gcp.go

Specifies a URL which points to a gcp storage bucket where the RHCOS pipeline publishes an RHCOS image for gcp (coreos/coreos-assembler#650). Use that tar.gz file to create a compute image for the cluster and boot the instances from that.
JIRA: [CORS-1164](https://jira.coreos.com/browse/CORS-1164)

Set GCP to pull boot images from RHCOS pipeline.

---

data/data/gcp/master/main.tf

This provides master machines access to compute.firewalls.* as it is required by the k8s cloud provider
/cc @csrwng 

data/gcp/masters: add roles/compute.securityAdmin to masters

---

pkg/asset/manifests/cloudproviderconfig.go
pkg/asset/manifests/gcp/cloudproviderconfig.go
pkg/asset/manifests/gcp/cloudproviderconfig_test.go

GCP cloud provider needs to be configured to be Regional and MultiZone so that it is looking for resources like instances in all Zones for the region it's deployed in.
/cc @csrwng 

set the cloud-provider-config for GCP

---

data/data/baremetal/masters/main.tf

Currently, ironic inspection data from the masters isn't used anywhere,
and increases deployment time. We can re-enable it if and when the data
is used.

data/data/baremetal: disable introspection on masters

---

data/data/bootstrap/baremetal/systemd/units/coredns.service
data/data/bootstrap/baremetal/systemd/units/keepalived.service

The latest bootimage enables the crio-wipe service, which cannot run
successfully if we've started containers directly with podman prior
to the crio service coming up.
The final fix for this will be to move these services to the MCO
which is in progress via https://github.com/openshift/installer/issues/2067
but this implements a stopgap solution which is to ensure the podman
containers aren't started until crio is up.
Closes: #2014

baremetal: Start coredns/keepalived after crio

---

data/data/bootstrap/systemd/units/kubelet.service.template

Removed the unwanted backslash newline escape char from the service file
While testing on the fedora coreos, have seen these extra backslash newline escape chars were creating issues and couldn't start the service, hence removing them anyways which aren't required here.
Fixes: #2080

Bug 1734157: data/bootstrap: Remove the unwanted backslash newline escape char

---

pkg/asset/rhcos/image.go
pkg/rhcos/azure.go

Use bootimage artifact from the data/data/rhcos.json file rather than hard coding path.

azure: source Azure OS bootimage from RHCOS pipeline

---

data/data/openstack/topology/private-network.tf
data/data/openstack/topology/variables.tf

In order to collect logs from the bootstrap node during CI, we
need to have a floating IP attached to the node. Otherwise, there
is no way for the installer to run must-gather against the
bootstrap node.
Note: we also need to pass a private-key in CI. Handled by:
https://github.com/openshift/release/pull/4504

openstack: Add a floating IP to bootstrap node for must-gather

---

pkg/asset/manifests/scheduler.go
pkg/types/validation/installconfig.go

This change makes use of a new configuration item on the scheduler CR
that specifies that control plane hosts should be able to run
workloads.  This option is off by default, but will now be turned on
if there are no compute machine pools with non-zero replicas defined.
This change also removes a validation and warning when no compute
hosts are defined, as an install with this configuration will now
complete successfully.

scheduler: Use schedulable masters if no compute hosts defined.

---

pkg/destroy/libvirt/libvirt.go

Two patches that ensures we delete the volumes and storage pool when destroying the relevant cluster.
Fixes #2074.

libvirt: Delete volumes & storage pool directory

---

data/data/gcp/dns/base.tf

The internal zone name expected by the cluster is `<cluster-id>-private-zone` [1]
[1]: https://github.com/openshift/installer/blob/0055065143ee52ee6252cd7896d551e374500a59/pkg/asset/manifests/dns.go#L109
/cc @jstuever @csrwng

data/gcp/dns: fix resource name for internal dns zone

---

pkg/destroy/gcp/compute.go
pkg/destroy/gcp/gcp.go
pkg/destroy/gcp/network.go

Improves logging of errors coming from failed operations
Fixes bugs related to deleting internal and external load balancers created by the Kubernetes cloud  controller.

[gcp] pkg/destroy/gcp: Fix external and internal load balancer deletion

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

bootkube.sh largely uses long form flags for shell commands, this fixes
the remaining ones that do not.

bootkube: use long flags for consistency

---

data/data/openstack/topology/private-network.tf

Tag the floating IP with the cluster ID. Without it we are leaking floating IPs.

openstack: add tag and desc to bootstrap floating IP

---

pkg/asset/manifests/gcp/cloudproviderconfig.go
pkg/asset/manifests/gcp/cloudproviderconfig_test.go

Adds subnetwork name to cloud config so that the cloud controller knows where to create internal load balancers.

[gcp] pkg/assets/manifest: add subnetwork name to cloud config

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

The last consumer was removed in 8c58a999f7 (#1885).

data/bootstrap/files/usr/local/bin/bootkube.sh.template: Drop OPENSHIFT_HYPERSHIFT_IMAGE

---

Gopkg.lock
pkg/asset/machines/gcp/machines.go
vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/gcpmachineproviderconfig_types.go

Adds the GCP project ID to the machine provider spec to ensure that
machines are created in the project where the cluster is being
installed.

[gcp] pkg/asset/machines - add project id to machines

---

data/data/gcp/master/main.tf

The service user role is required for the control plane to be able to attach a
disk to an instance running as a different role.
See https://cloud.google.com/compute/docs/disks/add-persistent-disk
(Under permissions required for this task for mounting a disk):
```
If you are connecting to a VM instance that can run as a service account, you must also grant the roles/iam.serviceAccountUser role.
```
In 3.x we accomplished this via scopes and the default service account:
https://github.com/openshift/openshift-ansible/blob/release-3.11/roles/openshift_gcp/templates/provision.j2.sh#L109

[gcp] data/data: add service user role to masters

---

docs/user/metal/install_ipi.md

This is described in the network prerequisites section earlier in the
doc, but was not reflected in the sample install-config.
The ns1 DNS record is also no longer required.

baremetal: Add dnsVIP to sample install-config.

---

data/data/libvirt/bootstrap/main.tf
data/data/libvirt/bootstrap/variables.tf
data/data/libvirt/main.tf

This is needed for gather logs from the nodes.
Related: https://github.com/openshift/release/pull/4395

libvirt: Assign fully-qualified domain names to master & bootstrap nodes

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

Address:
```console
$ sed 's/{{//g;s/}}//g' data/data/bootstrap/files/usr/local/bin/bootkube.sh.template | shellcheck -
...
In - line 114:
--manifest-image=${OPENSHIFT_HYPERKUBE_IMAGE} \
^-- SC2086: Double quote to prevent globbing and word splitting.
...
```
and similar.

data/bootstrap/files/usr/local/bin/bootkube.sh.template: Quote image expansions

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

We had an issue ([bz 1723798](https://bugzilla.redhat.com/show_bug.cgi?id=1723798)) where bootstrap failed because the default podman IP range conflicted with the user's internal range. Since we don't rely on podman for network isolation, the easiest way to fix this is just to run all bootstrapping pods in the host network.

Bug 1723798: bootkube: run all podman commands in the host network.

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
data/data/bootstrap/systemd/units/approve-csr.service
data/data/bootstrap/systemd/units/openshift.service

This code copies the loopback kubeconfig into the kubernetes configuration so that static pods can use it. approve-csr is also modified to use it in its service script. 
This is necessary due to a limitation with Azure internal load balancers. See limitation #2 here: https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-overview#limitations
"Unlike public Load Balancers which provide outbound connections when transitioning from private IP addresses inside the virtual network to public IP addresses, internal Load Balancers do not translate outbound originated connections to the frontend of an internal Load Balancer as both are in private IP address space. This avoids potential for SNAT port exhaustion inside unique internal IP address space where translation is not required. …

data/data/bootstrap: use loopback kubeconfig for API access

---

data/data/azure/dns/dns.tf
data/data/azure/vnet/internal-lb.tf
data/data/azure/vnet/nsg.tf
data/data/azure/vnet/public-lb.tf

This reverts commit 619d0b28f377ab0c397b1a8b169dac5429599a38.
xref: https://jira.coreos.com/browse/CORS-1095

Revert "data/data/azure/dns: use public ip behind internal apis"

---

Gopkg.lock
pkg/asset/machines/openstack/machines.go
vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/apis/openstackproviderconfig/v1alpha1/doc.go
vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/apis/openstackproviderconfig/v1alpha1/register.go
vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/apis/openstackproviderconfig/v1alpha1/types.go
vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/apis/openstackproviderconfig/v1alpha1/zz_generated.deepcopy.go

This patch changes OpenStack provider API from openstackproviderconfig.k8s.io/v1alpha1
to openstackproviderconfig.openshift.io/v1alpha1

OpenStack: change provider API

---

docs/user/metal/install_ipi.md
pkg/types/baremetal/validation/platform.go
pkg/types/validation/installconfig.go
pkg/types/validation/installconfig_test.go

The API, DNS, and Ingress virtual IPs (VIPs) should be contained within
the MachineCIDR, but not ClusterNetworks, or ServiceNetworks. This adds those
validations for the baremetal platform.
Closes: #2006

baremetal: Validate VIPs are in MachineCIDR

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

In #2001 we set all containers to use host-network. Remove some duplicate arguments.
I don't understand how #2001 passed CI.

bootkube.sh: remove duplicate --net args to podman.

---

pkg/asset/manifests/cloudproviderconfig.go
pkg/asset/manifests/openstack/cloudproviderconfig.go
pkg/asset/manifests/openstack/cloudproviderconfig_test.go

This parameter is needed for correct volume labeling.

OpenStack: Add region to the cloud provider config

---

data/data/gcp/network/network.tf

The number of concurrent connections to single host:port depends on the minimum number of ports per VM configuration of the cloud NAT [1]. This esp important for pulling images, as those are pulled in parallel by CRI-O
Increasing the default from 64 to 256 for control-plane for better bootstrapping throughput, and increasing the default from 64 to 128 for compute for better baseline.
[1]: https://cloud.google.com/nat/docs/overview#number_of_nat_ports_and_connections
/cc @csrwng

gcp: increase the ports per VM for NAT

---

docs/design/openstack/OWNERS

This adds a new directory for documents about the design of the
OpenStack platform and sets up `openstack-approvers` as its owners.
For example content see the existing Bare Metal folder:
https://github.com/openshift/installer/tree/master/docs/design/baremetal
Or this pull request:
https://github.com/openshift/installer/pull/2148

openstack: set up `docs/design/openstack` OWNERS

---

data/data/azure/master/master.tf

In search for find the performance bottleneck for etcd on control-plane host, I contacted the Microsoft Support with the FIO results. They mentioned that the Disks for the control-plane were using Read/Write caches and for Premium SSDs certain applications can benefit from switching to Read-only cache.
`Azure Red Hat Openshift` deployments already use Read-only cache for etcd data disks [1][1]
Switching to read-only has provided definite speed ups. This is still not comparable to AWS/GCP but I think this is definitely required as we optimize more.
[1]: https://github.com/openshift/openshift-azure/blob/ced59421d8f8122315d5b649ba89c43b52c5e183/pkg/arm/v5/resources.go#L475

Bug 1737660: data/azure/master: use ReadOnly caching for OSDisk

---

pkg/destroy/gcp/compute.go
pkg/destroy/gcp/gcp.go
pkg/destroy/gcp/iam.go

- Changes service account and IAM policy deletion code to only declare success if
no items are returned when queried.
- Removes filter for list of instances
- Fixes aggregateError utility function
- Fixes prefix used to clear IAM policy bindings

[gcp] pkg/destroy/gcp: Fix orphan service accounts

---

pkg/asset/manifests/proxy.go

Splitting an empty string:
```
len(strings.Split("", ",")))
```
returns a slice with a single empty string in it.  No need to inject an empty string in the noProxy set.  This will also protect us from install-config entries that begin or end with a comma, giving us a cleaner in-cluster config in those cases.

pkg/asset/manifests/proxy: Do not inject empty-string noProxy

---

data/data/gcp/master/main.tf

The storage.admin role (which we already include) is a superset of storage.objectAdmin. This PR
removes the unnecessary additional role binding.

[gcp] data/data/gcp: remove role binding to storage.objectAdmin

---

docs/user/gcp/install.md
docs/user/gcp/install_upi.md

Broadly following the analogous AWS wording, but I've removed the "IPI" and "UPI" acronyms based on [rhbz#1706179][1].
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1706179

docs/user/gcp/install: Link to the UPI install docs

---

images/baremetal/Dockerfile.ci
images/installer/Dockerfile.upi.ci
images/nested-libvirt/Dockerfile
images/openstack/Dockerfile.ci

This fixes the failing yum commands in the installer images.  It looks like yum's `skip_missing_names_on_install` is now False, which errors on invalid `yum install` commands. baremetal had an isuse where it had a yum install without arguments, the others were installing various unnecessary and unavailable packages: epel-release, awscli, etc.

image: fix invalid yum commands in images

---

pkg/destroy/gcp/iam.go

We were not initially using email because infra ID could be larger than
what the credential operator was allocating for it in the email name (max 30
chars). However, now we are limiting gcp infra ID's to a much smaller
size that does fit in the email. We are not guaranteed that a
displayName will be set on a service account, but we are guaranteed that
an email will be set.

[gcp] pkg/destroy/gcp: Use email to destroy service accounts

---

images/baremetal/Dockerfile.ci

On the first stage of the **baremetal** build, the command `go build
...` already requires `libvirt-devel` to be present, otherwise it fails
horribly with the following message if the package is not present in
the base container:
```
Package libvirt was not found in the pkg-config search path.
Perhaps you should add the directory containing `libvirt.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libvirt' found
pkg-config: exit status 1
```

baremetal: add `libvirt-devel` dependency for building

---

pkg/asset/machines/aws/machinesets.go
pkg/asset/machines/gcp/machinesets.go

Both 'machine.openshift.io/cluster-api-machine-role' and 'machine.openshift.io/cluster-api-machine-type' labels
in machineset matching labels are redundant. Only machineset name is needed. Given all other providers
set only cluster ID and machineset name in the matchine labels, let's honor the set of two items only.

Bug 1713374: Do not use machine role and in machineset matching labels

---

pkg/asset/cluster/tfvars.go
pkg/tfvars/openstack/openstack.go
pkg/types/openstack/defaults/platform.go

To allow users to provide custom cloud names in the install config we need to remove hardcoded 'openstack' name.
To do so and to keep the compatibility with the current behavior, we read cloud name from the install config first, and if it's empty, set it to the value of OS_CLOUD env variable. If both values are not specified, then cloud name defaults to "openstack".
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1732858

Bug 1732858: unhardcode the cloud name for openstack

---

hack/build.sh

The location of the defaultReleaseImage variable has moved to
pkg/asset/releaseimage, and this doesn't currently work. It also appears
nothing is relying on this feature so we can remove it.  If you want to
override the release image, you can do at run time with
OPENSHIFT_RELEASE_IMAGE_OVERRIDE, which functions the same other than
not being embedded in the produced openshift-install binary.

 hack: remove compile time RELEASE_IMAGE override

---

docs/user/azure/credentials.md

In order to properly mint credentials for components, your service principal needs to request for the following API permission before you can deploy OpenShift on Azure:
Azure Active Directory Graph -> Application.ReadWrite.OwnedBy
/cc @jhixson74 @ingvagabund

docs/user/azure/credential.md: add section for requesting additional required permissions

---

pkg/asset/installconfig/openstack/openstack.go
pkg/types/openstack/validation/mock/validvaluesfetcher_generated.go
pkg/types/openstack/validation/realvalidvaluesfetcher.go
pkg/types/openstack/validation/validvaluesfetcher.go

Without a floating IP address, the cluster will not be accessible from
the outside, which means the installer will fail when it tries to
communicate with the OpenShift API.
This adds the necessary prompt that lists all floating IPs that are
available on the previously selected external network.

Bug 1741637: openstack: Add API Floating IP survey question

---

data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template

Updated the CACHEURL env variable to utilise $PROVISIONING_NIC instead of default.
The default route works in virtualised environments but typically not in baremetal
ones. This shouldresolve for both.
Closes #2232

startironic.sh uses wrong route IP for CACHEURL

---

pkg/types/aws/defaults/platform.go
platformtests/aws/default_instance_class_test.go

This PR cherry-picks #1935 back to release-4.1.  It's not a clean cherry-pick, because we [decided][1] to not backport the ap-east-1 addition from #1755 to 4.1.z.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1734136#c4

Bug 1725524: types/aws/default: move ap-northeast-2 to m5 instance class

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

Reduce noise like:
```
Aug 20 17:36:29 localhost openshift.sh[1621]: error: unable to recognize "./90_metal3_baremetalhost_crd.yaml": Get https://localhost:6443/api?timeout=32s: x509: certificate is valid for api.ostest.test.metalkube.org, not localhost
```
from the bootkube.service logs.

Bug 1743840: data/bootstrap/files/usr/local/bin/bootkube.sh.template: Localhost keys for etcd-signer

---

pkg/terraform/exec/plugins/Gopkg.lock
pkg/terraform/exec/plugins/Gopkg.toml
pkg/terraform/exec/plugins/vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/resource_ironic_deployment.go
pkg/terraform/exec/plugins/vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/resource_ironic_node_v1.go
pkg/terraform/exec/plugins/vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/workflow.go

This updates the terraform-provider-ironic to v0.1.7, which includes a
fix for retrying when Ironic returns a 409 Conflict error. Ironic can
return this error when it's busy talking to the hardware's baseboard
management controller (BMC) to get the power status for example, so we
should retry when that happens.

Bug 1743871: vendor: update terraform-provider-ironic to v0.1.7

---

pkg/destroy/gcp/compute.go
pkg/destroy/gcp/dns.go
pkg/destroy/gcp/iam.go
pkg/destroy/gcp/network.go
pkg/destroy/gcp/storage.go

LIST operations in GCP provide `nextPageToken` field in response for clients to loop through multiple pages.
Using the `fields` options while making the response only returns the requested fields ie. if the `nextPageToken` is not explicitly mentioned in the request it is not returned by the API.
Missing the `nextPageToken` causes the `req.Pages` to only work for the first page. This ensures we are looping through all pages.
Note:
- we didn't see this for most resources because most List support server side filtering and therefore we covered all resources for the clusters as the count converges to 0, just across multiple requests.
- serviceaccount list doesn't support server-side list and therefore not being able to correctly loop over all the service accounts caused us to leak all those.

pkg/destroy/gcp: ensure nextPageToken is present in response to correctly handle pages

---

pkg/terraform/gather/openstack/ip.go

OpenStack installations may have floating IPs that get used for
bootstrap nodes. This patch updates the bootstrap IP code so that
it looks for the floating IP first. If found it will be used.
Otherwised it can be silently ignored in favor of direct
access via the openstack instances access_ipv4 address.
As OpenShift CI for OpenStack uses floating IPs this should resolve
issues in obtaining bootstrap logs in our CI scripts.

openstack: have gather bootstrap look for FIP

---

data/data/openstack/bootstrap/main.tf
data/data/openstack/bootstrap/variables.tf
data/data/openstack/main.tf
data/data/openstack/topology/outputs.tf
data/data/openstack/topology/private-network.tf
data/data/openstack/topology/variables.tf

This patch moves the related to bootstrap machine resources from  the topology module to the bootstrap module.
This allows to destroy the bootstrap FIP along with the machine.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1740543
Fixes: #1047

Bug 1740543: Consolidate bootstrap resources to bootstrap module

---

pkg/asset/manifests/proxy.go

Proxy controller (I think) changed this https://github.com/openshift/cluster-network-operator/pull/295 but the installer isn't doing the same. This is causing a different proxy config being generated between bootstrap and in-cluster which in turn causes the MCO to generates different machineconfigs and resulting in https://bugzilla.redhat.com/show_bug.cgi?id=1744532#c13
Signed-off-by: Antonio Murdaca <runcom@linux.com>

Bug 1744532: proxy: add .svc and .cluster.local to default noProxy

---

images/installer/Dockerfile.upi.ci

As part of the proxy ci work contained within the VPC we need to generate certs and the proxy password file using `openssl`

Adding openssl for proxy ci work

---

upi/vsphere/machine/main.tf

RHCOS switch from using other26xLinux64Guest to rhel7_64guest.
This changes uses the templates guest_id for use within the machine creation.

Bug 1737102: vSphere UPI - Use template guest_id for machines guest_id

---

pkg/terraform/gather/openstack/ip.go

Patch #2128 moved this resource from topology to bootstrap module. We have to change the gather part accordingly.

Bug 1719808: openstack: change bootstrap_fip module for gather

---

data/data/rhcos.json

This update pulls in:
- an early Azure checkin module, which shortens OS boot time from
~7min to ~2min30s in terraform
- bare metal ip persist via the coreos-installer
(Note: this is intended as 4.2 bugfixing)

RHCOS: update to release 42.80.20190823.0

---

data/data/openstack/bootstrap/main.tf
data/data/openstack/bootstrap/variables.tf
data/data/openstack/main.tf

When bootstrapping is completed we no longer need the container with the ignition file.
This commit moves the container Terraform resource to the bootstrap module, so that it can be deleted along with the rest of the resources.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1737802

Bug 1737802: openstack: move swift container to the bootstrap module

---

docs/user/aws/install_upi.md

Some users [want to provide their own `*.apps` DNS records][1] instead of delegating that to the ingress operator [1].  With this commit, we tell the ingress operator not to worry about managing any hosted zones, and walk users through how they can create [the expected records][2] themselves.
This is a WIP until I fill in a few outstanding FIXMEs.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1715635
[2]: https://github.com/openshift/cluster-ingress-operator/blob/9ce86811e6aeea58d3b2b8955591d50cd9311885/pkg/operator/controller/ingress/dns.go#L75-L115

Bug 1715635: docs/user/aws/install_upi: Document bring-your-own-DNS

---

data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
data/data/bootstrap/baremetal/systemd/units/ironic.service
data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
data/data/bootstrap/files/usr/local/bin/installer-gather.sh
data/data/bootstrap/files/usr/local/bin/release-image-download.sh.template
data/data/bootstrap/files/usr/local/bin/release-image.sh.template
data/data/bootstrap/systemd/units/bootkube.service
data/data/bootstrap/systemd/units/release-image.service.template

startironic.sh now uses the ironic images specified in the release. In
order to do that, this change pulls out the code from bootkube to
get the images to it's own script, and adds a service that downloads the
release image so it only happens once.
fixes #2090

Bug 1743873: data/bootstrap: extract ironic images from release image

---

cmd/openshift-install/create.go

Many users seem to misinterpret the failure of the gather command to collect logs as the error message for why their cluster failed to install. An example error message looks like this:
```
ERROR failed to create SSH client, ensure the proper ssh key is in your keyring or specify with --key: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
FATAL waiting for Kubernetes API: context deadline exceeded
```
This change will switch the error prefix to INFO. I have opted to hide the error message entirely. I think this is the best approach here, but am definitely open to other ideas.
Here are some examples from internal slack channel where users have been confused:
- August 20: @here Having a problem bringing up aws cluster. …

Update error message when automatic gather boostrap fails on cluster fail.

---

data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template

Some people are hitting issues where the containers appear running in
podman ps output, but are in fact unresponsive and podman exec/inspect
CLI options fail.
This may be a libpod bug (looking for related issues), but as a workaround
we can check the inspect status, which should mean we can detect zombie
containers and restart the ironic.service which appears to solve the
issue.
Related: https://github.com/openshift-metal3/dev-scripts/issues/753

Bug 1745004:  baremetal: Use podman inspect to check ironic service status 

---

data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template

This comment should have been adjusted following code-review
updates in #2249 but I missed it, now we are using the --format
option clarify the comment to explain the multiple templating

Bug 1745004: baremetal: Clarify comment in startironic.sh.template 

---

pkg/types/validation/installconfig.go
pkg/types/validation/installconfig_test.go
pkg/validate/validate.go
pkg/validate/validate_test.go

To provide compatibility with [OCP 3.x ](https://docs.openshift.com/container-platform/3.11/install_config/http_proxies.html), the installer should allow leading `.` for `proxy.noProxy` values. This will allow subdomains preceding `.` to bypass proxy.

Adds support for leading dots in domain names

---

hack/build.sh

Like 3313c08266 (#1744), but for tags.  This should fix #1828:
```console
$ ./openshift-install version
./openshift-install v4.1.0-201905212232-dirty
...
```
Doozer [sets `SOURCE_GIT_TAG`][2] just like it sets `SOURCE_GIT_COMMIT`.
Fixes #1828.
[1]: https://github.com/openshift/installer/issues/1828
[2]: https://github.com/openshift/doozer/blob/a36e072a87d403c09519a1d0c9be4757f8bee941/doozerlib/distgit.py#L1229

Bug 1715001: hack/build: Use BUILD_VERSION if non-empty

---

Gopkg.lock
pkg/asset/machines/gcp/machines.go
vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/gcpmachineproviderconfig_types.go
vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/zz_generated.deepcopy.go

This commit adds masters to targetPools on gcp.
This commit also updates cluster-api-provider-gcp dep.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1746230

Bug 1746230: Add target pools to gcp masters

---

pkg/destroy/aws/aws.go

The destroyer is expecting that the error returned when attempting to delete a missing snapshot is "InvalidSnapshotID.NotFound". The actual error returned in "InvalidSnapshot.NotFound". [1]
https://bugzilla.redhat.com/show_bug.cgi?id=1746459
[1] https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html

Bug 1746459: destroy/aws: fix error expected when snapshot not found

---

docs/user/openstack/README.md
docs/user/openstack/troubleshooting.md

Add info that if cluster deletion fails, users should try it again.
Related bug: https://bugzilla.redhat.com/show_bug.cgi?id=1746748

OpenStack: update troubleshooting docs

---

data/data/openstack/topology/sg-worker.tf

The worker security group did not have the mDNS port (UDP 5353) open.
This means that in OpenStack environments that block it by default,
the worker nodes' names were not resolvable via the CoreDNS static
pods running on the masters.
Fixes #2291

Bug 1733867: openstack: Open mdns port for workers

---

docs/user/gcp/install_upi.md

Multiple documentation changes to assist with the successful deployment of gcp upi clusters.
- Document how to disable automation of the `*.apps` DNS records and how to add them manually.
- Specify the region in certain gcloud invocations for when it differs from the default region.
- Removes the api load balancer pivot in order to remove bootstrap-complete race condition.

Bug 1745907: upi/gcp: enable manual DNS entry for *.apps

---

CONTRIBUTING.md

I'd missed this when removing the consuming text in dfa406b23b (#531).

CONTRIBUTING: Drop CoreOS disclosure anchor

---

docs/user/gcp/install_upi.md

This is a documentation only change that clarifies the requirement to have the `Service Account Key Admin` role added to the service account for GCP UPI. It is required later in the doc when adding a key to the service account used to create the bootstrap.ign temp url.

upi/gcp: clarify that Service Account Key Admin role is required

---

pkg/destroy/aws/aws.go

Fix races like:
1. The installer removes a bucket
2. The still-running registry operator tries to self-heal and creates a new bucket, but before it can push tags...
3. The installer terminates the instance where the registry operator was running.
4. The installer leaks the new, untagged bucket.
This has been happening in CI in jobs like [this][1] [one][2], where CloudFormation logs show:
1. 12:56:32, registry operator creates the bucket
2. 14:31:10, installer deletes the bucket
3. 14:31:11, registry operator creates the bucket again
4. 14:31:11, installer starts requesting instance termination
And it could theoretically happen to any resource (not just buckets) which we discover by tag, but which is not tagged atomically on creation.
[1]: …

Bug 1740933: pkg/destroy/aws: Terminate instances before other resources

---

docs/user/aws/customization.md
docs/user/azure/customization.md

API version v1beta4 of install-config deprecated a few options names. While
not dramatic -- the installer knows how to update to the new format --
we should stop using deprecated options in the configuration examples
we provide.

Stop using deprecated options in documentation examples

---

docs/user/metal/install_ipi.md
docs/user/vsphere/install_upi.md

Most of our docs were bumped in befde3c232 (#1589), but these v1beta4 references snuck in with 0ec07d0769 (#1545) and 0055065143 (#1873).

docs/user: Bump vSphere and metal from v1beta4 to v1

---

data/data/aws/vpc/master-elb.tf

Bug 1749624: data/aws/vpc/master-elb: Bump load-balancer timeouts to 20m

---

data/data/gcp/bootstrap/main.tf
data/data/gcp/master/main.tf

In GCP, terraform apply is run during bootstrap destroy to remove the bootstrap node from the LB. If control plane machine_type is set to the n2-standard series, master & bootstrap instances are created with min_cpu_platform = "Intel Cascade Lake," but the terraform configuration has min_cpu_platform = null. As terraform tries to switch min_cpu_platform back to null, installer will error with:
>level=error msg="Error: Changing the machine_type, min_cpu_platform, or service_account on an instance requires stopping it. To acknowledge this, please set allow_stopping_for_update = true in your config."
By using lifecycle ignore_changes we can prevent TF from mistakenly trying to switch min_cpu_platform back to null.

Bug 1746119: GCP Terraform ignore changes to min_cpu_platform

---

Gopkg.lock
pkg/destroy/openstack/openstack.go

Now we delete OpenStack resources in parallel using goroutines. It can lead to the fact that a resource can already been deleted when another goroutine sends a request.
Instead of returning an error in this case and quitting the installer we should tolerate this type of errors and continue to remove resources.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1746748

Bug 1746748: OpenStack: idempotent cluster deletion

---

docs/user/gcp/limits.md

I could combine this into the update I will do of GCP docs later this week with [CORS--1192](https://jira.coreos.com/browse/CORS-1192) but link is currently broken so perhaps we want to merge immediately.

Fix reference links in GCP quota limit docs.

---

pkg/destroy/aws/aws.go

Sometimes CI leaks untagged security groups and subnets.  Because we are allowed to remove all resources from within a cluster-owned VPC, add `*ByVPC` walkers to remove these indirectly-owned resources.

Bug 1747519: pkg/destroy/aws: Delete security groups and subnets by VPC

---

data/data/openstack/topology/sg-master.tf
data/data/openstack/topology/sg-worker.tf

The OpenStack security groups have diverged from AWS. Some of these
cause real problems. This makes sure that all the SGs open in AWS are
also open for OpenStack.
This also fixes some obvious typos and updates some of the names to
match AWS.

data/openstack/topology: update security groups

---

docs/user/openstack/README.md
docs/user/openstack/known-issues.md
pkg/types/openstack/validation/platform.go
pkg/types/openstack/validation/platform_test.go
pkg/types/validation/installconfig.go

OpenStack is shipping with some known issues for this release. We are choosing to address them with preventative validation in the installer, and with documentation so that customers don't mistakenly deploy buggy clusters. 
https://bugzilla.redhat.com/show_bug.cgi?id=1749816

Bug 1749816: OpenStack: Validates cluster name length and document known issues

---

pkg/asset/installconfig/openstack/openstack.go

We now recommend at least 16GB RAM for masters, and 8GB for workers.

openstack: Bump recommended memory in prompt doc

---

pkg/asset/machines/libvirt/machines.go

With current resource, the extended tests which are part of CI are failing
because of resource constraint.
```
event for s2i-build-quota-1-build: {default-scheduler } FailedScheduling: 0/2 nodes are available: 1 Insufficient memory, 1 node(s) had taints that the pod didn't tolerate.
```

Bump libvirt resource from 6GB to 7GB

---

data/data/gcp/network/firewall-compute.tf
data/data/gcp/network/firewall-control.tf
upi/aws/cloudformation/03_cluster_security.yaml
upi/gcp/03_security.py

We already opened the GENEVE port for AWS IPI. This opens it for GCP IPI and AWS + GCP UPI.
The other platforms (Vsphere, Azure) do not have intra-cluster firewalls.

Bug 1748162: Open GENEVE wherever possible

---

docs/user/openstack/known-issues.md

OSP releases prior to OSP15 do not have support for Ceph with temp-url.
Point to the in-flight patch to remove temp-url requirement.

OpenStack: Document Ceph RGW limitation with temp-url

---

pkg/destroy/aws/aws.go

When there are multiple untagged security groups, a security group may fail deletion with `DependencyViolation`.  Before this PR, that aborted that round of `deleteEC2VPC`, and when the blocking dependency was another untagged security group, deletion would [hang][1].
With this commit, we keep iterating through all untagged security groups (just like we do for tagged security groups).  For security group cycles, deletion will fail for the first few groups while we drain out their ingress and egress rules.  But deletion will succeed for at least some of the cycle.  And the rule draining will have completely deconstructed the cycle, so the second pass through will clear out all the security groups.
So prior to 55630a3043 (#2214), destroy would hang on *any* untagged security group.  And …

Bug 1747519: pkg/destroy/aws: Do not failFast for deleteEC2SecurityGroupsByVPC

---

images/installer/Dockerfile.upi.ci

Similar to https://github.com/openshift/origin/pull/22592
Addresses being able to add a user entry for container user id to be able to ssh to squid proxy
```
Agent pid 90
Identity added: /etc/openshift-installer/ssh-privatekey (/etc/openshift-installer/ssh-privatekey)
No user exists for uid 1451760000
```

Add g+w /etc/passwd to be able to collect proxy access logs in teardown

---

images/openstack/Dockerfile.ci

Some unit tests need to run git command and fail if the git username
and email are not set. This copies the instructions from the test image
Dockerfile at [1] to setup needed test dependencies.
[1] https://github.com/openshift/origin/blob/master/images/tests/Dockerfile.rhel

OpenStack: Install test dependencies into openstack-installer image

---

pkg/asset/releaseimage/pullspec.go

`ReleaseImage` is not a thing we reference elsewhere in user facing
descriptions, a `release image` is.

asset: Make warning message read for humans

---

pkg/destroy/gcp/network.go

Previous commit e9fa901b04bbed1da2558cf2c978fa2b6b9e8f1d missed certain call sites in `network.go`
`nextPageToken` is required to make sure Paging works for Lists.

pkg/destroy/gcp/network.go: fix missing nextPageToken

---

docs/user/azure/customization.md

Based on `pkg/types/azure/machinepool.go` , I am adding the availability zones customization section for machine pools and including a custom availability zone config in the custom machine pool example because it was missing.

docs/user/azure/customization: Add azure availability zones

---

docs/user/customization.md

Leaning on the design doc in `docs/dev/alternative_release_image_sources.md`, which I'm not linking because it's more focused on design/internals than I think users need to be.  Also leaning on @christianh814's [blog][1] for the `oc adm release mirror` invocation.  Tested with:
```console
$ oc adm release mirror --from=quay.io/openshift-release-dev/ocp-release-nightly:4.2.0-0.nightly-2019-09-11-114314 --to=registry.svc.ci.openshift.org/wking/openshift4 --to-release-image=registry.svc.ci.openshift.org/wking/openshift4:4.2.0-0.nightly-2019-09-11-114314
```
using the `oc` extracted from that same nightly.
[1]: https://github.com/christianh814/blogs/tree/278ac1cf8268511c1d6cad9aaaace62e681d573e/docs/openshift-4.2-disconnected#mirroring-images

docs/user/customization: Add a section on imageContentSources

---

docs/user/azure/limits.md
pkg/asset/machines/master.go
pkg/types/azure/defaults/machines.go

To support the throughput for uncached writes to 1024 GB Preimum SSD disks [P30 200MB/second](https://azure.microsoft.com/en-us/pricing/details/managed-disks/) the instance size also need to be bumped to `D8s_v3` [192Mb/second](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-general#dsv3-series-1)
This increases the default vCPU requirement for default single cluster to `34` from `22`, and the default disk requirements for deafult single cluster to `4480 GB` from `896GB`

Bug 1751375: Azure: bump disk size to 1TB for control plane 

---

data/data/openstack/main.tf
data/data/openstack/masters/main.tf
data/data/openstack/masters/variables.tf
data/data/openstack/variables-openstack.tf

This is a stop gap solution to allow using a faster storage (if there
is a more performant storage type in cinder) than the default ephemeral
disk. This setting will later be reworked to be exposed as under the
machinepool as it is for other platforms.

Bug 1753187: OpenStack: Permit choosing the volume type for instances

---

docs/user/gcp/limits.md

Removes unintentional token
/assign @wking

Fix typo in GCP limits doc.

---

upi/vsphere/machine/ignition.tf
upi/vsphere/machine/main.tf
upi/vsphere/machine/variables.tf
upi/vsphere/main.tf

Slow DNS propagation potentially causing CI failure.  Test with alternative nameservers

 Bug 1754644: vsphere upi: changes to resolve ci issues

---

docs/user/azure/credentials.md
docs/user/azure/install.md

This information is redundant as the install.md already provides information about installer prompting for the credentials.
Also this causes confusion for users who rerun the described command and end up creating a new service principal that doesn't have the necessary permissions from Step 2.
see https://bugzilla.redhat.com/show_bug.cgi?id=1753419#c5
/assign @jhixson74

docs/user/azure: remove the out-of-place sp creation instructions

---

data/data/gcp/bootstrap/variables.tf
data/data/gcp/master/variables.tf
pkg/tfvars/gcp/gcp.go

We've clobbered these with values exported from Go since ca3580146d (#2192).  Remove the distracting, unused strings from Terraform.

[4.3] data/gcp: Drop unused defaults for control-plane/bootstrap volumes

---

data/data/bootstrap/baremetal/systemd/units/ironic.service

This is a mistake, and results in a warning from systemd then the type
is ignored (defaulting to "simple" due to the ExecStart), so lets remove
it to avoid the warning.
Fixes: #2309

baremetal: Remove spurious Type from ironic.service

---

pkg/asset/manifests/proxy.go

Adds GCP metadata hostnames to default noProxy according to https://cloud.google.com/vpc/docs/special-configurations

Fixes Bug 1753930: Adds GCP metadata hostnames to default noProxy

---

docs/user/gcp/install_upi.md
upi/gcp/04_bootstrap.py
upi/gcp/05_control_plane.py

Before this change, the GCP UPI workflow hard coded the zones in the
bootstrap and control-plane templates. It assumed every region had zones
$REGION-{a,b,c}. However, in some regions this is not the case.
This change adds the zone(s) as parameters to the templates and updates
the docs accordingly. The list of zones is now fetched from gcp, and
then used to populate the templates.

upi/gcp: templates to use zone paramaters

---

data/data/gcp/dns/base.tf
data/data/gcp/main.tf
data/data/gcp/master/variables.tf
data/data/gcp/network/common.tf
data/data/gcp/network/firewall-compute.tf
data/data/gcp/network/firewall-control.tf
data/data/gcp/network/network.tf
data/data/gcp/network/outputs.tf
data/data/gcp/network/variables.tf
data/data/gcp/variables-gcp.tf
pkg/asset/cluster/tfvars.go
pkg/asset/machines/gcp/machines.go
pkg/asset/manifests/cloudproviderconfig.go
pkg/asset/manifests/gcp/cloudproviderconfig.go
pkg/asset/manifests/gcp/cloudproviderconfig_test.go
pkg/tfvars/gcp/gcp.go
pkg/types/gcp/platform.go

JIRA: [CORS-1213](https://jira.coreos.com/browse/CORS-1213)
This is the basic setup for installing to an existing VPC on GCP: users can specify their own VPC and subnets in install config and terraform will perform the installation. There is currently no validation. This is tested and installs the cluster successfully. 
The easiest way to create your own VPC, router, etc is to follow step [Create the VPC from the UPI docs](https://github.com/openshift/installer/blob/master/docs/user/gcp/install_upi.md#create-the-vpc).
This differs from the design doc in that I did add `VPC.name` to the install config (rather than just the subnets). I believe it is necessary to have the cluster network in order to create the firewall rules and to make sure the network is using the private DNS zone. 
I …

GCP: Add install-config and terraform support for BYO VPC

---

docs/user/customization.md

Typo is from a947609d66 (#2162).

docs/user/customization: Fix "utalize" -> "utilize" typo

---

pkg/asset/releaseimage/default.go

since master now tracks 4.3, bumping the master release-image to use 4.3
/cc @wking @smarterclayton

asset/releaseimage/default.go: bump to 4.3 release image

---

docs/user/openstack/README.md

The command needs to be run as the user for installation not
admin.
Signed-off-by: Sai Sindhur Malleni <smalleni@redhat.com>

Fix openstack docs for swift temp url support

---

docs/user/openstack/README.md

The OpenStack QCOW2 is delivered in compressed format and needs to be
retrieved with the proper options for it to be usable.
See https://bugzilla.redhat.com/show_bug.cgi?id=1755506 for additional
info.

openstack:  add note about compressed image format

---

pkg/destroy/openstack/openstack.go

The teardown of a cluster often fails because a floating IP cannot be
found, and the relative router deleted.
With this PR, a missing FIP does not break cluster destruction any more.

Destroy cluster fails for a missing FIP

---

pkg/types/aws/validation/machinepool.go
pkg/types/aws/validation/machinepool_test.go

The value printed in the error message was the one for storage IOPS
instead of storage size.

Fix AWS storage size validation error message

---

upi/gcp/03_security.py

Before this change, the gcp upi firewall rules limited access to the
nodePort ports from worker to worker and master to master. Access
between worker and master was denied. However, because gcp upi produces
masters that have the 'worker' role, the nodePort services could run on
masters and need to be accessed from pods on other workers. Or pods on
masters might need access to nodePort services on workers.
This change modifies the gcp upi firewall rules to allow the nodePort
services across the entire cluster.
Depends on #2419

gcp upi: allow nodePort between masters and workers 

---

pkg/types/conversion/installconfig.go

Install config validation uses k8s apimachinery validation. This commit updates pkg/types/conversion/ to use the same package in order to provide more context when field validation fails. 
Users were complaining about error messages that looked like this:
`FATAL failed to fetch Master Machines: failed to load asset "Install Config": failed to upconvert install config: cannot upconvert from version vi1`
The new error messages include the field that failed validation and the bad value:
`FATAL failed to fetch Master Machines: failed to load asset "Install Config": failed to upconvert install config: apiVersion: Invalid value: "vi1": cannot upconvert from version vi1`

Bug 1750494: Use standard field validation in pkg/types/conversion/

---

data/data/aws/vpc/common.tf

The final consumers were removed in c80edadeb5 (#769).

data/aws/vpc/common: Drop unused (private|public)_subnet_count variables

---

data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh

The machine-config daemon usually runs in a Pod, and that's already being gathered.  But pivots happen via [the systemd service][1] I'm gathering with this commit.  Also attempt to gather `pivot.service`, which takes precedence as described [here][1].
[1]: https://github.com/openshift/machine-config-operator/blob/ead45a28a7df3bb89f4d18d34982b875df82aadd/templates/common/_base/units/machine-config-daemon-host.service

data/bootstrap/files/usr/local/bin/installer-masters-gather: Gather MCD logs

---

pkg/destroy/gcp/gcp.go

This change resolves a cut-n-paste typo in gcp destroy error reporting. When an error is thrown while creating the `iamSvc`, it now properly indicates it is an `iam service` and not a `compute service` that has failed.

gcp/destroy: Fix typo on failure to create aim service.

---

pkg/types/baremetal/validation/platform.go
pkg/types/baremetal/validation/platform_test.go

As mentioned in #2079 we should validate these IPs as they must
be on a different subnet than the machine CIDR, these IPs are used
to configure a dedicated network for provisioning machines via pxe.
This also adds some tests for the existing validation as a pre-requisite to adding tests for the new validation.
Closes: #2210

baremetal: Add validation for provisioning network IPs 

---

data/data/aws/vpc/common.tf
data/data/aws/vpc/master-elb.tf
data/data/aws/vpc/vpc-private.tf
data/data/aws/vpc/vpc-public.tf

Builds on #2432; no need to review until that one lands.
The zone-count variables date back to f828666224 (coreos/tectonic-installer#3092).  But with Terraform 0.12, which we've used since 64c44cde21 (#1739), we have better array handling, and no longer need count
variables.
Similarly, there's no need for `vpc_id`, when we can extract that ID from `data.aws_vpc.cluster_vpc`.

data/aws/vpc: Drop new_az_count and vpc_id locals

---

upi/aws/cloudformation/02_cluster_infra.yaml

Copy-edits for some output descriptions.  Internal and external are not proper nouns or otherwise in need of special capitalization.  Also insert some missing articles.  And drop the trailing "created" (short for "created by this template"?), because all of these outputs are related to resources generated by this template, otherwise we wouldn't need to output them.

upi/aws/cloudformation/02_cluster_infra: "the External" -> "the external", etc.

---

upi/gcp/05_control_plane.py

This change updates the gcp upi templates to use pd-ssd disk types on
the control plane instances just like we do in gcp ipi.

upi/gcp: control plane to use pd-ssd

---

upi/vsphere/machine/main.tf
upi/vsphere/machine/variables.tf
upi/vsphere/main.tf

This allows for customizing the number of CPUs assigned to a VM for vSphere UPI using terraform.

add customizable num_cpu for vsphere UPI installation

---

pkg/asset/store/store.go

This PR changes asset fetching/generating logging to not output quotes. We currently use the %q string fmt verb when logging asset fetching/generating. I don't think this is a technical (or security) requirement. This results in extra " characters in log output, e.g.:
```
DEBUG   Using "Certificate (system:kube-apiserver-proxy)" loaded from state file 
DEBUG   Loading "Certificate (aggregator-signer)"... 
DEBUG   Loading "Certificate (system:kube-apiserver-proxy)"... 
DEBUG     Loading "Certificate (aggregator)"...    
DEBUG   Using "Certificate (system:kube-apiserver-proxy)" loaded from state file 
DEBUG   Loading "Certificate (etcd-ca-bundle)"...  
DEBUG   Loading "Certificate (etcd-metric-ca-bundle)"... 
DEBUG   Loading "Certificate (etcd-metric-signer)"... 
DEBUG   Loading …
```

Remove quotes from installer log.

---

docs/user/aws/install_upi.md
docs/user/gcp/install_upi.md

We grew replicas-zeroing in c22d042 (#1649) to set the stage for changing the `replicas: 0` semantics from "we'll make you some dummy MachineSets" to "we won't make you MachineSets".  But that hasn't happened yet, and since 64f96df (#2004) `replicas: 0` for compute has also meant "add the `worker` role to control-plane nodes".  That leads to racy problems when ingress comes through a load balancer, because Kubernetes load balancers exclude control-plane nodes from their target set (see [here][1] and [here][2], although this [may get relaxed soonish][3]).  If the router pods get scheduled on the control plane machines due to the `worker` role, they are not reachable from the load balancer and [ingress routing breaks][4].  @sjenning says:
> pod `nodeSelectors` are not like …

Bug 1755073: docs/user/*/install_upi: explicitly-set-control-plane-unschedulable

---

data/data/rhcos.json

```console
$ hack/update-rhcos-bootimage.py https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.2/42.80.20191002.0/meta.json
```
[Comparing][1] (currently private tool, sorry, but public RHCOS history [here][1b]) with our previous 42.80.20190827.1:
```console
$ ./differ.py --first-endpoint art --first-version 42.80.20190827.1 --second-endpoint art --second-version 42.80.20191002.0
{
"sources": {
"42.80.20190827.1": "https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.2/42.80.20190827.1/commitmeta.json",
"42.80.20191002.0": "https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.2/42.80.20191002.0/commitmeta.json"
},
"diff": {
"bash": {
"42.80.20190827.1": …
```

Bug 1758312: data/rhcos: Bump to rhcos-4.2/42.80.20191002.0

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

The keepalived container image is not available in RHEL 7 on s390x. As a
result, this container image cannot be built and included in the release
image. As a short term workaround, this allows the bootstrapping process
to proceed without having a valid container image for keepalived. This
is okay because the consumer of the pullspec, the Machine Config
Operator, only references this image when installing on "baremetal" and
"openstack". Installs on s390x will be okay because they will be using
"libvirt" (for CI) and "none" (for UPI installations).

data/bootstrap: allow for missing keepalived image

---

data/data/bootstrap/systemd/units/kubelet.service.template

See https://github.com/openshift/machine-config-operator/commit/8f86081d651d7114bae767eee830960bf74c8995
I'm trying to update the RHCOS bootimage to 4.3 with Kube 1.16
and this is now a fatal error.

bootstrap: Remove --allow-privileged from kubelet flags

---

data/data/rhcos.json

```console
$ hack/update-rhcos-bootimage.py https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.3/43.80.20191002.1/x86_64/meta.json
```
[Comparing][1] (currently private tool, sorry, but public RHCOS history [here][1b]) with our previous 42.80.20190827.1:
```console
$ ./differ.py --first-endpoint art --first-version 42.80.20190827.1 --second-endpoint art --second-version 43.80.20191002.1
{
"sources": {
"42.80.20190827.1": "https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.2/42.80.20190827.1/commitmeta.json",
"43.80.20191002.1": "https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.3/43.80.20191002.1/x86_64/commitmeta.json"
},
"diff": {
"kernel": {
"42.80.20190827.1": …
```

Bug 1758306: data/rhcos: Bump to rhcos-4.3/43.80.20191002.1

---

Gopkg.lock
pkg/destroy/aws/aws.go

Partitions are more complicated than I thought when I wrote the hard-coded `arn:aws:ec2:...` prefix in 54cfed55a4 (#2169).  While most of our regions use `aws`, [China uses `aws-cn`][1], [GovCloud uses `aws-us-gov`][2], and there may be more.  Pull this ARN componet from the AWS SDK instead to track that sort of thing.
[1]: https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#arns-syntax
[2]: https://docs.aws.amazon.com/sdk-for-go/api/aws/endpoints/#pkg-overview

pkg/destroy/aws: Dynamic partitions, fixing hard-coded 'aws'

---

pkg/destroy/aws/aws.go

I'd added this to save on AWS API-call volume in fc70eb221c (#1704).  But now that we support user-provided VPCs with installer-provided network interfaces, it's no longer feasible.  Happily, the tagged network interfaces are just for installer-created control-plane machines, see 4fcdc1cbb4 (#1361).  And since cf69c1e52a (#2169) we are terminating instances first and waiting for their termination to complete before proceeding to other resources.  So we should no longer have the long runs of failed network-interface deletion attempts while we wait for the instances to terminate, and this commit should make our removal more robust without increasing our API-call volume.

pkg/destroy/aws: Stop skipping direct network-interface deletion

---

data/data/rhcos.json

The current baseURI is pointing at
releases-rhcos-art.cloud.privileged.psi.redhat.com, which is an internal
URL and signed by the corporate CA. This is breaking any 4.2 install that relies on downloading RHCOS (e.g. some UPI installs, baremetal IPI, etc), and the user is not on the VPN or is on the VPN and the particular server doesn't trust RH's corporate CA.

Bug 1759146: data/rhcos: fix base url to use correct baseURI

---

hack/update-rhcos-bootimage.py

Don't allow people to point to e.g. an RHT-internal endpoint.
See: https://github.com/openshift/installer/pull/2462

hack/update-rhcos-bootimage: Require ART endpoint

---

docs/user/gcp/install_upi.md

We could have used "create ... in", but "add" echos:
```sh
gcloud dns record-sets transaction add ...
```
/assign @jstuever

docs/user/gcp/install_upi: "create ... to" -> "add ... to" typo fix

---

pkg/asset/manifests/proxy.go

External cluster resources such as routes should not be automatically no-proxied. We should provide cluster admins the choice on whether or not to proxy these connections. This PR removes the external api-server hostname from the default noProxy list.

Fixes Bug 1757975: asset/manifests: Removes external api server from default noProxy

---

data/data/aws/main.tf
data/data/aws/variables-aws.tf
data/data/aws/vpc/common.tf
data/data/aws/vpc/master-elb.tf
data/data/aws/vpc/outputs.tf
data/data/aws/vpc/variables.tf
data/data/aws/vpc/vpc-private.tf
data/data/aws/vpc/vpc-public.tf
data/data/aws/vpc/vpc.tf

Builds on #2437; no need to review before that lands.
The installer will no longer create (vs. the fully-IPI flow):
* Internet gateways (`aws_internet_gateway`)
* NAT gateways (`aws_nat_gateway`, `aws_eip.nat_eip`)
* Subnets (`aws_subnet`)
* Route tables (`aws_route_table`, `aws_route`, `aws_route_table_association`, `aws_main_route_table_association`)
* VPCs (`aws_vpc`)
* VPC DHCP options (`aws_vpc_dhcp_options`, `vpc_dhcp_options_association`)
* VPC endpoints (`aws_vpc_endpoint`)
because those resources define the VPC/subnet networking and we can't pick values for CIDRs and routing and such without a risk of picking something that collides with some other VPC/subnet consumer.
The installer will continue to create (vs. the fully-IPI flow):
* AMI copies (`aws_ami_copy`)
* IAM roles and …

data/aws/vpc: Lay the groundwork for bring-your-own VPC/subnets

---

upi/gcp/01_vpc.py

This change increases the minimum ports per control-plane instance to
allow much higher resiliency. It is based on #2376, which did the same
for GCP IPI.

upi/gcp: increase the NAT ports for control plane to 7168

---

data/data/gcp/network/firewall.tf

The ranges can be found at
NLB: https://cloud.google.com/load-balancing/docs/health-checks#fw-netlb
ILB: https://cloud.google.com/load-balancing/docs/health-checks#fw-rule
commit https://github.com/openshift/installer/pull/2050/commits/6c2e7f7f6ef7c87fead16be2e2fcc6391035db4f seems to have followed the wrong doc
and kept the ranges for ILB when that change move to single NLB.

Bug 1759965: data/gcp/network/firewall.tf: allow complete health check range for ILBs and NLBs

---

data/data/gcp/network/firewall-control.tf

The ranges can be found at
NLB: https://cloud.google.com/load-balancing/docs/health-checks#fw-netlb
ILB: https://cloud.google.com/load-balancing/docs/health-checks#fw-rule
commit https://github.com/openshift/installer/pull/2050/commits/6c2e7f7f6ef7c87fead16be2e2fcc6391035db4f seems to have followed the wrong doc
and kept the ranges for ILB when that change move to single NLB.
Backports https://github.com/openshift/installer/pull/2480

Bug 1759966: data/gcp/network/firewall-control.tf: allow complete health check range for ILBs and NLBs

---

data/data/azure/main.tf

Fixing a typo from 5416b42b9d (#1976).  Carries #2468.

data/azure/main: Set metadata to URL, not the string "var.azure_image_url"

---

data/data/azure/main.tf
data/data/azure/master/master.tf
data/data/azure/master/variables.tf
data/data/azure/variables-azure.tf
pkg/tfvars/azure/azure.go

Like most of the other platforms, the disk type for master machines is present in the machine object, and the terraform should
use that to create control plane machines.
This allows users to use multi-stage installs to modify the control-plane root volume disk type.
This change explicitly skips the addition of making it easy for users to specify this setting in install-config for future work.
/assign @jhixson74

azure: set the os disk type based on machine objects

---

pkg/gather/ssh/agent.go
pkg/gather/ssh/ssh.go

Log the choice to use `SSH_AUTH_SOCK`, since that will clarify [cases where we fail to gather logs because a pre-existing agent lacks the required SSH key][1].
Also log key loading, because that will give us a handle on which keys we inject when we create our own agent.
I'd like to log the `ag.Add` calls in `newAgent` as well, but I couldn't figure out how to convert the private-key `interface{}` to a fingerprint or something else that I could safely log.
[1]: https://github.com/openshift/installer/issues/2349#issuecomment-534690793

pkg/gather/ssh: Add logging for agent generation

---

data/data/aws/vpc/master-elb.tf

It is [not valid for network load balancers][1].  We've been setting this in our Terraform config since 0a96415026 (coreos/tectonic-installer#725) when we were using classic load balancers and should have dropped it in 16dfbb3541 (#594).
Spun off from #2279 at @abhinavdahiya's [request][2].
[1]: https://github.com/terraform-providers/terraform-provider-aws/commit/d25a227e639d770ecec3a50aaae6191d68f17c98#diff-f4b0dbdc7e3eede6ba70cd286c834f37R78
[2]: https://github.com/openshift/installer/pull/2279#issuecomment-525589712

data/aws/vpc/master-elb: Drop idle_timeout from aws_lb resources

---

data/data/manifests/bootkube/cvo-overrides.yaml.template
docs/user/troubleshooting.md

4.2 has branched off, so we can bump master to track stable-4.3.  This bump is like the previous 8eeb26840c (#1801).
```console
$ sed -i 's/stable-4.2/stable-4.3/' $(git grep -l stable-4.2)
```

data/manifests/bootkube/cvo-overrides: Move to stable-4.3

---

upi/gcp/03_security.py

This is the UPI equivalent of 4c346afcde38e26b9a416a250c6ddfe36aff3bac. The initial implementation of both UPI & IPI was not allowing the complete range of network load balancers. This includes the fix for UPI and also leaves the ranges for internal load balancers.
/assign @jstuever

Bug 1760425: Change GCP UPI firewall rules for network LB health check.

---

docs/user/aws/install_upi.md

I just dropped this in at the end in 14e06912a3 (#2221), but you need it for a functioning cluster (something about console and OAuth and mumble mumble).  @jstuever got the placement right for GCP in 16d4d388ac (#2289).  This commit updates AWS to match.

docs/user/aws/install_upi: Wait for install-complete after manual DNS creation

---

pkg/destroy/openstack/openstack.go

Now we use ExponentialBackoff timeout with 100 steps, which gives us approx. 262000 years of waiting.
Although it is quite obvious that the cluster will be destroyed during this time, we must terminate the process earlier than this time frame.
This commit increases the initial duration from 10 to 15 seconds and also reduces the number of steps from 100 to 10. So the timeout will be 10 minutes after that.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1754452

Bug 1754452: OpenStack: reduce the timeout for deleting the cluster

---

docs/user/metal/install_upi.md
docs/user/vsphere/install_upi.md

Broken since the docs landed in 0ec07d0769 (#1545).

docs/user/vsphere/install_upi: Fix [...][#...] references, etc.

---

pkg/destroy/aws/aws.go

Fix a bug from 37a7f49c77 (#2214), where `failFast=false` lead to all deleteEC2Subnet errors being ignored.  Luckily we have `failFast: true` for them, so no exposed change, but fixing this bug protects us from exposing it if we toggle failFast in the future.

pkg/destroy/aws: Fix fail-slow error handling in deleteEC2SubnetByVPC

---

cmd/openshift-install/gather.go
data/data/bootstrap/files/usr/local/bin/installer-gather.sh
data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh

Support running multiple gather commands without cluster-side collisions. For example:
1. Alice runs `gather bootstrap`, her command writes a tarball on the bootstrap machine and starts downloading it.
2. Bob runs `gather bootstrap`, his command starts writing to the same tarball on the bootstrap machine.
3. Alice's download croaks on the truncated file.
But maybe Alice's download already has an open file descriptor, so Bob's clobber doesn't break the download?  I guess it depends on the specifics of how `installer-gather.sh`'s `> ~/log-bundle.tar.gz` worked.  With this pull request, we avoid potential issues by passing in an optional gather ID which the cluster-side scripts use to uniquify their collection directories.  We still race if multiple gathers are launched in the same second, …

cmd/openshift-install/gather: Guard against cluster-side artifact collisions

---

pkg/destroy/aws/aws.go

Remove any `kubernetes.io/cluster/{id}: shared` tags, such as those that we'll use for bring-your-own subnet workflows (spun out of #2438).  The 20-tag limit that leads to the loop is from [here][1].  We're unlikely to exceed 20 with just the VPC and subnets, but it seemed reasonable to plan for the future to avoid surprises if we grow this list going forward.
Including `tagClients` allows us to find and remove tags from Route 53 resources, which live in us-east-1 regardless of the rest of the cluster's region.  More on that under "The us-east-1 business..." in e24c7dc419 (#1039).  I have not added untag support for IAM resources (which are not supported by `resourcegroupstaggingapi`, more on that in e24c7dc419 too), but we could add untagging for them later if we want to support …

pkg/destroy/aws: Untag shared resources

---

docs/user/aws/install_upi.md

We shouldn't assume folks will have a private zone they can dedicate to the sole use of the new cluster.  This pull-request talks users through adjusting their DNS configuration to consume an existing private zone with arbitrary identification.
CC @ewolinetz, @kalexand-rh

docs/user/aws/install_upi: Explain DNS-zone lookup

---

data/data/azure/dns/dns.tf
data/data/azure/dns/variables.tf
data/data/azure/main.tf
data/data/azure/master/master.tf
data/data/azure/variables-azure.tf
data/data/azure/vnet/common.tf
data/data/azure/vnet/internal-lb.tf
data/data/azure/vnet/nsg.tf
data/data/azure/vnet/outputs.tf
data/data/azure/vnet/variables.tf
data/data/azure/vnet/vnet.tf
pkg/asset/cluster/tfvars.go
pkg/asset/machines/azure/machines.go
pkg/asset/manifests/azure/cloudproviderconfig.go
pkg/asset/manifests/azure/cloudproviderconfig_test.go
pkg/asset/manifests/cloudproviderconfig.go
pkg/tfvars/azure/azure.go
pkg/types/azure/platform.go

Add NetworkResourceGroupName, VirtualNetwork, ControlPlaneSubnet, and
ComputeSubnet to the Azure platform struct and pass them to terraform. This is
the initial implementation, therefore, there is no error checking, isolation,
destroying, or terminal prompts. This is for install-config only.
For existing virtual networks, the installer will no longer create route tables, subnets,
virtual networks or network security groups. 
https://jira.coreos.com/browse/CORS-1206

Azure: Allow customer provisioned virtual networks & subnets

---

Gopkg.lock
data/data/openstack/bootstrap/main.tf
data/data/openstack/bootstrap/variables.tf
data/data/openstack/main.tf
data/data/openstack/masters/main.tf
data/data/openstack/masters/variables.tf
data/data/openstack/variables-openstack.tf
pkg/asset/cluster/tfvars.go
pkg/asset/machines/master.go
pkg/asset/machines/worker.go
pkg/asset/rhcos/image.go
pkg/destroy/openstack/openstack.go
pkg/rhcos/openstack.go
pkg/tfvars/openstack/openstack.go
vendor/github.com/gophercloud/gophercloud/internal/pkg.go
vendor/github.com/gophercloud/gophercloud/internal/util.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/results.go
vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/results.go
vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/types.go
vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/urls.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/results.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/results.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/monitors/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/results.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/results.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/subnetpools/results.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/results.go

This PR allows to automatically populate a Glance image if it was not pre-created by the user.
Goals:
1. Automatically create a Glance image with the required version for the cluster.
2. The name of the created image must be unique. We have chosen names in format "\<InfraID\>-rhcos".
3. Delete the image together with the cluster.
4. If OPENSHIFT_INSTALL_OS_IMAGE_OVERRIDE variable is set and it is not a URL, do not create an image in Glance, but reuse the existing one and do not delete it when deleting the cluster.
5. If OPENSHIFT_INSTALL_OS_IMAGE_OVERRIDE variable is set and it is a URL - create a new Glance image from the URL ignoring rhcos.json file data, delete the Glance image along with the cluster.
Not included in goals of this work:
Generation of the URL from which we download the …

OpenStack: automatically populate RHCOS image

---

docs/user/gcp/README.md
docs/user/gcp/apis.md
docs/user/gcp/iam.md

You need to enable to enable the APIs before you do things like set up DNS. Pulling this out into it's own step for clarity.

docs: clarify enabling GCP service APIs

---

cmd/openshift-install/create.go
cmd/openshift-install/gather.go
cmd/openshift-install/waitfor.go

We currently show ClusterVersion messages when we time out, based on the expectation that the cluster-version operator (CVO) would bubble up and summarize any operator-level errors.  But while the CVO does expose the fact that there *was* an error, it sometimes simplifies to the point where [users can no longer determine the underlying condition][1], while [the ClusterOperator conditions are more useful][2].  With this pull-request, we'll gather and log surprising ClusterOperator conditions (`Available=false`, `Degraded=true`, etc.) to give the user a bit more information to dig into before they need to drop into `openshift-install gather bootstrap ...` or `oc adm must-gather ...`.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1754939#c10
[2]: …

Bug 1754939: cmd/openshift-install/gather: Gather ClusterOperator errors

---

cmd/openshift-install/gather.go

Fixing typos from de5a26aa42 (#2450).
WIP because I have an `|| True` in there for testing, which I'll pull once we see that the new formatting is working.

cmd/openshift-install/gather: Fix '{}' -> %s formatting

---

pkg/terraform/exec/plugins/Gopkg.lock
pkg/terraform/exec/plugins/Gopkg.toml
pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/domain.go
pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/domain_def.go
pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_domain.go
pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_volume.go
pkg/terraform/exec/plugins/vendor/github.com/dmacvicar/terraform-provider-libvirt/libvirt/volume_def.go

Update terraform-provider-libvirt version to v0.6.0.
The terraform-provider-libvirt v0.6.0 contains the support of guestfs for s390 platform.
So this PR is to update erraform-provider-libvirt version.
Fixes #2499.

Update terraform-provider-libvirt version to v0.6.0.

---

data/data/gcp/network/common.tf
data/data/gcp/network/lb-private.tf
data/data/gcp/network/outputs.tf

The creation of internal load balancers was not taking into account custom-provided networks. This was causing failure on BYO VPC installs with the error:
```
ERROR                                              
ERROR Error: Error creating ForwardingRule: googleapi: Error 400: Invalid value for field 'resource.backendService': 'https://www.googleapis.com/compute/v1/projects/openshift-dev-installer/regions/us-east4/backendServices/pd-6bk9x-api-internal'. Forwarding rule network projects/openshift-dev-installer/global/networks/default must be the same as backend service network projects/openshift-dev-installer/global/networks/byovpc-network., invalid 
ERROR                                              
ERROR   on ../../../../../../../../tmp/openshift-install-913030725/network/lb-private.tf …
```

Update GCP internal load balancers to use custom-provided networks.

---

pkg/asset/cluster/aws/aws.go
pkg/asset/cluster/cluster.go
pkg/asset/cluster/tfvars.go
pkg/asset/installconfig/aws/metadata.go
pkg/asset/installconfig/aws/subnet.go
pkg/asset/installconfig/installconfig.go
pkg/asset/machines/aws/machines.go
pkg/asset/machines/aws/machinesets.go
pkg/asset/machines/master.go
pkg/asset/machines/worker.go
pkg/tfvars/aws/aws.go
pkg/types/aws/platform.go

Building on #2438 (which has landed) and #2467 (which I'm building on top of in this PR; review it first), this PR adds subnet handling to install-config and the Go asset handling.  Fiddly details in the commit messages ;).

pkg: AWS shared-subnet handling in Go

---

docs/user/aws/install_upi.md

Creating manifests:
```
$ openshift-install create manifests
WARNING There are no compute nodes specified. The cluster will not fully initialize without compute nodes. 
INFO Consuming "Install Config" from target directory 
```
Produces the following yaml files:
```
$ ls -lah openshift/
total 68K
drwxr-xr-x. 2 jdoss jdoss 4.0K Oct 10 14:39 .
drwxrwxr-x. 4 jdoss jdoss 4.0K Oct 10 14:39 ..
-rw-r--r--. 1 jdoss jdoss  293 Oct 10 14:39 99_binding-discovery.yaml
-rw-r--r--. 1 jdoss jdoss  219 Oct 10 14:39 99_cloud-creds-secret.yaml
-rw-r--r--. 1 jdoss jdoss  181 Oct 10 14:39 99_kubeadmin-password-secret.yaml
-rw-r--r--. 1 jdoss jdoss 1.5K Oct 10 14:39 99_openshift-cluster-api_master-machines-0.yaml
-rw-r--r--. 1 jdoss jdoss 1.5K Oct 10 14:39 99_openshift-cluster-api_master-machines-1.yaml …
```

docs/user/aws/install_upi: Fix "machinesets" -> "machineset" typo

---

data/data/bootstrap/files/usr/local/bin/installer-gather.sh
data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh

To help in cases where we die before getting far enough to launch a kubelet (or we have an issue with some other systemd-managed service).  In cases where there are no failing units, this will only add a small file and an empty directoy to the gathered tarball.
~To help in cases like [this][1], where one machine has no etcd running~
[The POSIX locale][2] gets us asterix prefixes in the `list-units` output, which are easier to match with sed than the default U+25CF (BLACK CIRCLE) it prints with `LANG=en_US.UTF-8`.  I'm not actually sure what locale we usually run on our control-plane machines, but it seems safest to not leave that up to the machines in this case.  Unfortunately I haven't found a way to have `list-units` spit out a more structured output format.
[1]: …

data/bootstrap/files/usr/local/bin/installer-*gather: Gather failed systemd units

---

docs/user/aws/customization.md

Catching up with 32356ddc99 (#2477).

docs/user/aws/customization: Document platform subnets

---

pkg/asset/manifests/gcp/cloudproviderconfig.go
pkg/asset/manifests/gcp/cloudproviderconfig_test.go

Tags for both master and worker need to be set, because in 4.3 both master and control-plane can be backends for k8s service type Load balancer and these are used
to create the correct firewal rules.
The cuurrent impl uses `gopkg.in/ini.v1` for writing the configuration, but the gce k8s code uses `gopkg.in/gcfg.v1` to read the configuration.
Although both are similar, gcfg handles multi-valued differently [1] which is esp problamatic for node-tags.
gcfg multi-value
```
node-tags = a
node-tags = b
```
ini multi-value
```
node-tags = [a, b]
```
Also gcfg only implements a reader and no Marshaller [2], therefore for the purpose of installer which is onl supposed to control few thing using go-templates to perform
the operation of marshalling seems acceptable.
[1]: …

asset/manifests/gcp: update the config to inlude master and worker node-tags

---

data/data/aws/bootstrap/main.tf
data/data/aws/bootstrap/variables.tf
data/data/aws/main.tf
data/data/aws/master/main.tf
data/data/aws/master/variables.tf
data/data/aws/route53/base.tf
data/data/aws/route53/variables.tf
data/data/aws/variables-aws.tf
data/data/aws/vpc/common.tf
data/data/aws/vpc/master-elb.tf
data/data/aws/vpc/outputs.tf
data/data/aws/vpc/variables.tf
docs/user/customization.md
pkg/asset/cluster/tfvars.go
pkg/asset/installconfig/installconfig_test.go
pkg/asset/machines/aws/machines.go
pkg/asset/machines/master.go
pkg/asset/manifests/dns.go
pkg/tfvars/aws/aws.go
pkg/types/defaults/installconfig.go
pkg/types/defaults/installconfig_test.go
pkg/types/installconfig.go
pkg/types/validation/installconfig.go
pkg/types/validation/installconfig_test.go

pkg/types: add the publish strategy to install-config
This commit adds a enum(string) type PublishingStrategy. It supports 2 options
* ExternalPublishingStrategy : the endpoints are exposed to the Internet
* InternalPublishingStrategy : the endpoints are exposed to the `Private Network` only
This enum type is added to the InstallConfig to control the strategy for the cluster endpoints. Cluster endpoints include the API server,
the default Ingress controller, public IPs etc.
Also adds the defaulting to make sure this strategy is `External` by default, keeping the backward-compatible behavior, and validation to make sure only valid enum options are set.
pkg/asset: update machines and DNS for external-internal strategy
For aws, only when the strategy is External, do we set the public Route53 …

AWS: Enable clusters with no public endpoints

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

Render ingress operator manifests during bootstrap. This enables users to bring
their own default ingresscontroller resource by using `openshift-install create
manifests` and placing ingresscontroller YAML into the `manifests/` directory.
At the time of this commit, the rendered output on the bootstrap node will be
the ingressoperator CRD[1] and namespace[2].
This is the first part of the "User Defined Default Ingress Controller"
enhancement proposal[3].
[1] https://github.com/openshift/cluster-ingress-operator/blob/master/manifests/00-custom-resource-definition-internal.yaml
[2] https://github.com/openshift/cluster-ingress-operator/blob/master/manifests/00-namespace.yaml
[3] https://github.com/openshift/enhancements/blob/master/enhancements/user-defined-default-ingress-controller.md …

Enable user defined default ingresscontroller

---

docs/dev/libvirt/README.md

Issue: https://github.com/code-ready/snc/issues/112 have been raised. It is for permission denied errors that was caused by SElinux. SElinux isn't available on Debian/Ubuntu, and should be disabled in `qemu.conf`.

Adding docs on running via libvirt on Debian/Ubuntu

---

upi/gcp/03_security.py

This is an equivalent change to f0e25273cf9512b4aa99c26acdd153007d046e2d for UPI. The firewall rules did not allow for the complete range of network load balancer health checks.

Bug 1760197: Change GCP UPI firewall rules for network LB health check.

---

pkg/asset/installconfig/aws/metadata.go
pkg/asset/installconfig/aws/subnet.go

If no default region is setup in aws credentials, or the default region is different from the picked region, list subnets call fails with `could not find region configuration`.
xref: https://bugzilla.redhat.com/show_bug.cgi?id=1763927
/assign @wking 
/cc @wking

Bug 1763927: asset/installconfig/aws: configure region when listing subnets

---

pkg/terraform/gather/aws/ip.go

aws_instance has 2 attributes for IP: [public_ip][1] and [private_ip][2]. For bootstrap instance the [associate_public_ip_address][3] is set to true unless
the cluster needs to be private.
[1]: https://www.terraform.io/docs/providers/aws/r/instance.html#public_ip
[2]: https://www.terraform.io/docs/providers/aws/r/instance.html#private_ip-1
[3]: https://www.terraform.io/docs/providers/aws/r/instance.html#associate_public_ip_address
xref: https://jira.coreos.com/browse/CORS-1225
/cc @wking

pkg/terraform/gather/aws: fallback to private_ip when public_ip is empty for bootstrap instance

---

pkg/tfvars/openstack/openstack.go

When the image is provided by user, i.e. not created automatically by the installer, we need to check that the image exists and there are no other images with this name.

OpenStack: Image name validations

---

hack/build.sh
hack/go-fmt.sh
hack/go-lint.sh
hack/go-test.sh
hack/go-vet.sh
hack/run-bdd-suite.sh
hack/verify-vendor.sh
images/baremetal/Dockerfile.ci
images/installer-artifacts/Dockerfile.rhel
images/installer/Dockerfile.ci
images/installer/Dockerfile.ci.rhel7
images/installer/Dockerfile.upi.ci
images/mock/Dockerfile
images/nested-libvirt/Dockerfile
images/openstack/Dockerfile.ci
pkg/asset/cluster/tfvars.go
pkg/asset/kubeconfig/kubeconfig.go
pkg/asset/tls/tls.go
pkg/tfvars/aws/aws.go
pkg/types/azure/validation/platform_test.go
pkg/types/validation/installconfig_test.go

This PR updated the current building system and ci images from golang 1.10 to 1.12.

Bump golang version to 1.12

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

allow cloud-cred-operator to run on the bootstrap node to allow processing of CredentialsRequests for components that need early cloud credentials
details of the request for this comes from the network-operator team ( https://github.com/openshift/cluster-network-operator/pull/211#issuecomment-537984649 ):
Kuryr is a CNI plugin that provides networking to Pods and Services through OpenStack Neutron and OpenStack Octavia. This is desirable when OpenShift is running on OpenStack as avoiding double encapsulation (OpenStack SDN + OpenShift SDN) is a performance improvement. To achieve that Kuryr needs access to APIs of the underlying OpenStack cloud in order to create networks, subnets, ports (ifaces) and loadbalancers for the OpenShift resources. That obviously requires clouds credentials to …

add cloud-cred-operator as static pod

---

pkg/asset/manifests/openstack/cloudproviderconfig.go
pkg/asset/manifests/openstack/cloudproviderconfig_test.go

kubeconfig-path parameter was deprecated and not used anymore, so we can remove it from the config.
https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/openstack/openstack.go#L177-L178

OpenStack: clean-up cloud provider config

---

data/data/gcp/network/firewall.tf

This PR is part of the effort to improve cluster isolation ([CORS-1217](https://jira.coreos.com/browse/CORS-1217)). Prior to this, the MCS firewall was open to any machine in the MachineCIDR. Only the control plane and compute nodes need access to the MCS, so this reduces the exposure.

GCP: restrict MCS access to control plane & nodes

---

docs/user/openstack/README.md

The wget parameter should be "compression" instead of "compresion".
See: https://www.gnu.org/software/wget/manual/wget.html

Fix OpenStack QCOW2 download command

---

docs/user/openstack/known-issues.md

With #2311 being merged, and having removed the need for Swift tempurls,
the issue is no longer afflicting OpenStack installations.
Ref.: https://github.com/openshift/installer/pull/2311

openstack: Remove reference to tempurl known issue

---

data/data/bootstrap/files/usr/local/bin/installer-gather.sh

[Fix][1]:
time="2019-10-24T15:16:14Z" level=debug msg="/usr/local/bin/installer-gather.sh: line 12: /tmp/artifacts-20191024151613/failed-units.txt: No such file or directory"
from 8830652bbe (#2525).
[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/5518/rehearse-5518-pull-ci-openshift-library-go-release-4.4-e2e-aws-encryption/4/artifacts/e2e-aws-encryption/installer/.openshift_install.log

data/bootstrap/files/usr/local/bin/installer-gather: Make ${ARTIFACTS}

---

pkg/types/validation/installconfig_test.go
pkg/validate/validate.go

Save a few characters and get safer quoting if the user gives us a candidate IP address that contains a single quote or some such.

pkg/validate: '%s' -> %q for IP quoting

---

data/data/openstack/main.tf
data/data/openstack/topology/private-network.tf
data/data/openstack/topology/variables.tf
data/data/openstack/variables-openstack.tf
pkg/asset/cluster/tfvars.go
pkg/tfvars/openstack/openstack.go
pkg/types/openstack/platform.go
pkg/types/openstack/validation/platform.go
pkg/types/openstack/validation/platform_test.go

Adds an option in the installer that allows users to add the ip addresses of dns servers. These IP's will be added to the nodes subnet. 
Bug Fix for: https://bugzilla.redhat.com/show_bug.cgi?id=1734539

Bug 1734539: Openstack: Option to set multiple external DNS IP Addresses

---

docs/user/openstack/customization.md
docs/user/openstack/install_upi.md
docs/user/openstack/known-issues.md

Provide documentation for OpenStack `externalDNS` install-config.yaml's property, and explain how to overcome limitation of some OpenStack clouds caused by lack of default DNS resolvers on created subnets.

Openstack external dns doc

---

docs/user/customization.md
docs/user/gcp/customization.md

This PR creates a standard customization.md for GCP platform. It also attempts to document cluster isolation when multiple networks are installed in the same VPC ([CORS-1217](https://jira.coreos.com/browse/CORS-1217)).
/assign @jhixson74

GCP: Add install-config.yaml customization doc & document cluster isolation

---

pkg/tfvars/libvirt/cache.go

Installer was upgraded to golang 1.12, so we can start using this function.

Libvirt: start using os.UserCacheDir to find the cache folder

---

hack/go-sec.sh

gosec does static code analysis and checks for common security issues in
golang codebases.
This PR introduces a script that will run gosec similarly to other check
tools.

Introduce gosec for security checks

---

data/data/rhcos.json

$ ./hack/update-rhcos-bootimage.py https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.3/43.80.20191022.1/x86_64/meta.json
This contains latest machine-config-daemon on host which includes
Karg Day1 support feature https://github.com/openshift/machine-config-operator/issues/798

data/rhcos: Bump to rhcos-4.3/ 43.81.20191028.2

---

docs/user/azure/customization.md

Add documents for new install-config fields for BYO vnets. Document cluster isolation.
JIRA: [CORS-1209](https://jira.coreos.com/browse/CORS-1209)
Regarding cluster isolation, I assume this level of documentation is sufficient. If we were to document how cluster isolation should be performed manually that would be through official docs channels.
I left out details about what is required when supplying subnets because Azure validation is pending. I assume all of these resources need to be in the specified resourceGroup, but that is also probably somewhat self-evident, beyond that I'm not certain, but could definitely dig in if that should be added to this PR.

Azure: document custom VNets & cluster isolation

---

data/data/gcp/bootstrap/common.tf
data/data/gcp/bootstrap/main.tf
data/data/gcp/bootstrap/variables.tf
data/data/gcp/dns/base.tf
data/data/gcp/dns/variables.tf
data/data/gcp/main.tf
data/data/gcp/network/firewall.tf
data/data/gcp/network/lb-public.tf
data/data/gcp/network/outputs.tf
data/data/gcp/network/variables.tf
data/data/gcp/variables-gcp.tf
pkg/asset/cluster/tfvars.go
pkg/asset/manifests/dns.go
pkg/tfvars/gcp/gcp.go

This change allows the distinction between public and private clusters
in GCP based on installConfig.PublishingStrategy. It only creates the
public endpoints when installConfig.PublishingStrategy is "External".

gcp: Enable clusters with no public endpoints

---

upi/openstack/OWNERS
upi/openstack/README.md

This PR sets the ownership of the upi/openstack directory tree to the ShiftOnStack team.

openstack UPI: Ansible scripts

---

pkg/asset/machines/baremetal/machines.go
pkg/asset/machines/baremetal/machinesets.go

We've had the argument since the package landed in 0055065143 (#1873), but it has never been used.  Drop it to simplify the function calls, and to make it easier to use `grep` to answer questions like "does metal actually care about machineCIDR?" (apparently not).

pkg/asset/machines/baremetal: Drop unused networkInterfaceAddress from provider()

---

docs/user/openstack/install_upi.md

This doc contains the steps needed to use Kuryr as the SDN
when deploying OpenShift on OpenStack and using a User Provided
Infrastructure.
This commit lists all the necessary steps manually, using the
`openstack` command to create and delete the resources.

Add Kuryr UPI Documentation

---

OWNERS_ALIASES

This should help us to iterate faster and override e2e results until these are passing.
This only affects `fcos` branch and won't be transferred into `master` or `release-*`

[fcos] Add vrutkovs and LorbusChris to OWNERS

---

pkg/asset/cluster/tfvars.go

Baremetal: get external and provision from configuration

pkg/tfvars/baremetal: don't hardcode external and provision interfaces

---

Gopkg.lock
data/data/openstack/bootstrap/main.tf
data/data/openstack/bootstrap/variables.tf
data/data/openstack/main.tf
data/data/openstack/variables-openstack.tf
pkg/asset/cluster/tfvars.go
pkg/destroy/bootstrap/bootstrap.go
pkg/destroy/openstack/swift.go
pkg/tfvars/openstack/bootstrap_ignition.go
pkg/tfvars/openstack/openstack.go
vendor/github.com/gophercloud/gophercloud/openstack/client.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/microversions.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/results.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/results.go
vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/types.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/results.go
vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/requests.go
vendor/github.com/gophercloud/gophercloud/provider_client.go
vendor/github.com/kubernetes/apimachinery/LICENSE
vendor/github.com/kubernetes/apimachinery/pkg/util/rand/rand.go

Create Bootstrap Ignition shim 100% in GO code in order to use the latest versions of ignition.

Bug 1735192: OpenStack Self Signed Certs Fix

---

pkg/asset/installconfig/aws/permissions.go
pkg/asset/installconfig/platformcredscheck.go

If the user provides subnets in the install-config.yml, do not include network creation credentials in the ValidateCreds check.
https://jira.coreos.com/browse/CORS-1250

AWS credential validation, preexisting networking

---

data/data/openstack/main.tf
data/data/openstack/variables-openstack.tf
pkg/rhcos/builds.go
pkg/rhcos/openstack.go
pkg/tfvars/internal/cache/cache.go
pkg/tfvars/openstack/openstack.go

This PR allows to validate RHCOS images sha256 checksums to prevent possible MITM attacks.
To do so we extract the uncompressed sha256 checksum from `rhcos.json` file and attach it to the URL like `?sha256=...`
Next step is to download the file from the given URL and put it in the cache folder. Previously it was done by Terraform, but it doesn't support checksum validation feature, so we have to do it ourselves.
Files in the cache are called based on their ETags.
Terraform default cache folder was located in `~/.terraform/image_cache`. Now we put images in `<user_cache_dir>/openshift-installer/image_cache`, for linux it is `~/.cache/openshift-installer/image_cache`. 
If sha256 checksum was provided we validate it.
The final step is to give Terraform local file path of the image file.

OpenStack: Security enhancement: RHCOS image checksum validations

---

pkg/asset/manifests/gcp/cloudproviderconfig.go
pkg/asset/manifests/gcp/cloudproviderconfig_test.go

To allow re-using the instance groups that control-plane machines already belong to for backend of internal LBs, the upstream PR [1]
requires we set the external-instance-groups-prefix to filter the instance groups for the clusters.
The upstream PR [1] is in flight, but origin backport [2] might actually be merged for now for the time we work with upstream to support the use-case.
[1]: https://github.com/kubernetes/kubernetes/pull/84466
[2]: https://github.com/openshift/origin/pull/24036
/cc @jstuever @sdodson @smarterclayton

manifests/gcp: add infra-id as prefix for external IGs

---

data/data/rhcos.json

This build contains some networking fixes we want for the bootimage,
among other things.
This build has already passed promotion to `machine-os-content`.

Bug 1766739: rhcos: Bump to 43.81.201911011153.0

---

pkg/asset/cluster/aws/aws.go

fixes the error described in https://bugzilla.redhat.com/show_bug.cgi?id=1763927#c2
/assign @wking 
/test e2e-aws-shared-vpc

Bug 1763927: asset/cluster/aws: create resourcetaggingapi client with region

---

pkg/asset/machines/baremetal/machines.go
pkg/asset/machines/baremetal/machinesets.go
pkg/tfvars/baremetal/baremetal.go

https://github.com/openshift/installer/pull/2528 has caused platform/baremetal IPI deployments to break because it adds a new query string to the openstack image URL, which we also use
for IPI deployments
So we strip the query string from the tfvars and machine provider spec to restore the previous behavior, and the new checksum will be consumed in the downloader container as a follow-up.

Bug 1768564: baremetal: Fix image URL generation

---

images/openstack/Dockerfile.ci

The POSIX default locales cause the following error while retrieving
nova console logs:
UnicodeEncodeError: 'ascii' codec can't encode characters in position
As explained in [1] we should set the locales to UTF8 to workaround the
issue.
[1] https://docs.openstack.org/python-novaclient/train/cli/nova.html#nova-console-log

OpenStack: Use UTF-8 locales in CI container image

---

pkg/tfvars/internal/cache/cache.go
pkg/tfvars/libvirt/cache.go

If the installer crashes (OOM, checksum validations, etc.) while downloading an OS image, temporary files remain in the system, clogging it.
This commit makes sure that temporary files are deleted before starting a new download.
Fixes: https://github.com/openshift/installer/issues/1668

Remove temporary cached files

---

pkg/asset/manifests/azure/cloudproviderconfig_test.go

Catch this example up with cfa5d59c6c (#2556).  This is just a dummy value for the unit tests, but it's nice to be internally consistent anyway ;).

pkg/asset/manifests/azure/cloudproviderconfig_test: node-subnet -> worker-subnet

---

docs/user/openstack/README.md

This makes a more explicit description of the various floating IPs
used throughout the deployment, highlights why they don't seem to
be attached to the servers and links the OpenStack networking doc.

openstack: Improve the Floating IP documentation

---

pkg/tfvars/openstack/bootstrap_ignition.go
pkg/tfvars/openstack/openstack.go

Openstack installer leaves a swift container behind due to the delete script only fully running when terraform runs. This only happens when the base image check fails, so to prevent it, we move the swift container create after the base image check that way an image is never created if it fails. We also added some logging for better clarity.

Bug 1770006: Orphaned Swift resources

---

data/data/bootstrap/systemd/units/crio-configure.service.template

Systemd will run as much as possible in parallel, and run dependencies
of units even before units are started.  Hence we need to ensure
that we've configured crio before it's started.
https://bugzilla.redhat.com/show_bug.cgi?id=1770101

BZ 1770101: bootstrap: Ensure we've configured crio before it's started

---

data/data/rhcos.json

Build 43.81.201911061504.0 has all the necessary bits for FIPS day 1
support in RHCOS, with necessary dracut modules.
Signed-off-by: Yu Qi Zhang <jerzhang@redhat.com>

Bug 1768978: RHCOS: bump to 43.81.201911081536.0 for FIPS support

---

pkg/asset/ignition/bootstrap/bootstrap.go
pkg/asset/kubeconfig/admin_internal.go

Prior to this change, the default kubeconfig on the bootstrap host used
the external api url. This caused issues when the external api was not
available such as when proxy is configured but the noProxy list does not
contain the external api. In such situation, the bootstrap host fails to
report bootstrap complete to the cluster. As a result, the installer
fails during the wait-for bootstrap-complete stage.
This change adds a new kubeconfig (adminInternal) which points to
api-int. The bootstrap host defaults to this new kubeconfig. Api-int
is already in the noProxy list. As a result, the bootstrap host can
report complete even when the external api is inaccessible.

Bug 1762618: pkg/asset/ignition: bootstrap kubeconfig to use api-int

---

pkg/asset/installconfig/aws/metadata.go
pkg/asset/installconfig/installconfig.go

Because when the asset store loads the `InstallConfig` asset from state, it wasn't initializing the `Metadata` structure (vs. generating a new `InstallConfig` or loading it from a file, both of which hit `InstallConfig.finish()` and its `NewMetadata` call).  With this PR, we store copies of the region and subnets (if set) in the serialized `Metadata` state to avoid:
```console
$ openshift-install create ignition-configs
$ openshift-install create cluster
FATAL failed to fetch Terraform Variables: failed to generate asset "Terraform Variables": no subnets configured
```
I'm not super-excited about having multiple copies of this data in the state file, but the alternative would be to add `Finish()` to the `Asset` or `WritableAsset` interfaces, and that seems a bit heavy too.

Bug 1771431: pkg/asset/installconfig/aws: Serialize region and subnets

---

images/openstack/Dockerfile.ci

This adds the necessary dependencies (see `upi/openstack/requirements.txt`) to run the OpenStack UPI playbooks in the CI.
This is a prerequisite for adding the OpenStack UPI CI job.

openstack: Add ansible to the CI image

---

pkg/asset/machines/baremetal/machines.go
pkg/tfvars/baremetal/baremetal.go

This was recently added to the rhcos.json data but we uncompress
the image in ironic-rhcos-downloader, so the appropriate path
to give to terraform and the machine does not contain this suffix.
Related-Bug: #2661

Bug 1772080: Strip ".gz" suffix from baremetal image vars 

---

docs/user/openstack/README.md

The installer automatically uploads the required RHCOS image to glance,
there is no need to explain how to manually upload the image anymore.

OpenStack: Remove IPI instruction to upload RHCOS

---

docs/user/openstack/install_upi.md

In 4.3 Kuryr images are based on RHEL 8. Running RHEL 8 on RHEL 7 was
proved to be problematic and is unsupported. This commit adds a note in
UPI documentation explaining that RHEL 7 nodes are not supported on
deployments with Kuryr.

Add note on Kuryr not supported with RHEL 7 nodes

---

docs/user/gcp/customization.md

Correcting typo project -> projectID for GCP customization.
hat tip: @kalexand-rh

Fix projectID typo in GCP customization docs

---

pkg/asset/manifests/openstack/cloudproviderconfig.go
pkg/asset/manifests/openstack/cloudproviderconfig_test.go

We can't use "go-ini" library to generate the config, because it's incompatible with "gcfg" library that we use to read the data.
For instance, if there is a string with a # character, then "go-ini" wraps it in bacticks, like \`aaa#bbb\`, but gcfg doesn't recognize it and  parses the data as \`aaa, skipping everything after the #.
So, we have to generate the config manually, avoiding possible issues with "go-ini".

Bug 1772002: manually prepare cloud provider's config

---

pkg/types/baremetal/validation/libvirt.go
pkg/types/baremetal/validation/platform.go
pkg/types/baremetal/validation/platform_test.go
pkg/validate/validate.go

The current validation assumes that interfaces exist on the same host as
running the installer, although we expose the ability to change the
libvirtURI.  This means the bootstrap VM could theoretically be placed
on a remote host, so we should validate the interfaces through libvirt
to handle that case.
Because the platform validators always get compiled, we add a new
mechanism for registering dynamic validators that are only used when the
baremetal platform has been compiled into the openshift-install.

Bug 1773002: baremetal: validate interfaces through libvirt API 

---

images/openstack/Dockerfile.ci

The OpenStack CI will use Route 53 to create the DNS records necessary
for the tests. We will use the `awscli` tool to create and delete them.

OpenStack CI: add awscli to the CI image

---

cmd/openshift-install/main.go

The commit https://github.com/openshift/installer/commit/e3a504467d3e9be5f9a6b575b7d0005f27de0a9e changed
With switch to kubernetes-1.16.0, all the k8s libs are using klog [2], that doesn't add the flags and also allows to set the default Ouput writer
for all levels. Setting the klog output to ioutil.Discard keeps the current behavior
But the commit left some of the stderr outputs from klog still visible, turning on sterrThreshold to highest turns that off too.

Bug 1771784: cmd/openshift-install: silence the logs from klog by setting sterrThreshold to highest

---

pkg/terraform/gather/gcp/ip.go

The BootstrapIP func is missing a length check for access configs, which causes a panic on private clusters because access configs is empty. This commit adds a length check and also looks up the private ip address of the bootstrap node to use instead.

Bug 1773686: GCP Gather: use bootstrap internal ip when missing external

---

data/data/bootstrap/files/etc/ignition-machine-config-encapsulated.json.template
pkg/asset/ignition/bootstrap/bootstrap.go

Adds `ignition-machine-config-encapsulated.json.template` to enable FIPS on bootstrap node if required.
Fixes #2634

Add fips for bootstrap node; template ign machine config encap

---

data/data/rhcos.json

The current version of RHCOS pinned in the installer has a bug where
CRI-O is overriding the PodIP for the baremetal IPI platform's
containers that use host networking, resulting in cluster installation
failing.
fixes #2646

Bug 1772154: RHCOS: Bump to 43.81.201911192044.0 for CRI-O bug fix

---

docs/user/openstack/install_upi.md

Some Compute Security Group rules had their description matching the
pattern we're using for CP rules.
/cc @tomassedovic

openstack: Minor fixes to the UPI docs

---

pkg/asset/ignition/bootstrap/bootstrap.go
pkg/asset/kubeconfig/admin_internal.go
pkg/asset/manifests/proxy.go

Prior to this change, the default kubeconfig on the bootstrap host used
the external api url. This caused issues when the external api was not
available such as when proxy is configured but the noProxy list does not
contain the external api. In such situation, the bootstrap host fails to
report bootstrap complete to the cluster. As a result, the installer
fails during the wait-for bootstrap-complete stage.
This change adds a new kubeconfig (adminInternal) which points to
api-int. The bootstrap host defaults to this new kubeconfig. Api-int
is already in the noProxy list. As a result, the bootstrap host can
report complete even when the external api is inaccessible.
This change also reinstates a previously reverted commit removing the
external api from the proxy list now that the issue has …

Bug 1770223: bootstrap kubeconfig to use api-int

---

docs/dev/libvirt/README.md

Fedora 31 manages the libvirtd control sockets via systemd.

Bug 1775279: libvirt installer instructions need updating for Fedora 31

---

data/data/gcp/bootstrap/main.tf
data/data/gcp/bootstrap/output.tf
data/data/gcp/main.tf
data/data/gcp/master/main.tf
data/data/gcp/master/variables.tf
data/data/gcp/network/lb-private.tf
data/data/gcp/network/lb-public.tf
data/data/gcp/network/variables.tf
data/data/gcp/variables-gcp.tf
pkg/destroy/bootstrap/bootstrap.go

Previously the bootstrap node has been added to the first master instance group. This commit creates an independent instance group for the bootstrap node so that Kubernetes will not consider the master instance group to have a non-cluster node.

Bug  1774813: Create a bootstrap instance group in GCP.

---

pkg/asset/machines/gcp/machines.go
pkg/asset/machines/gcp/machines_test.go
pkg/asset/machines/master.go

Stop setting non existent public target pool when InternalPublishingStrategy on GCP master machines

bug 1774388: Stop setting non existent public target pool when InternalPublishingStrategy on GCP master machines

---

docs/user/vsphere/install_upi.md

docs: fixed broken link
The link to the terraform example file was broken:
upi/vsphere/terraform.tfvar.example -> upi/vsphere/terraform.tfvars.example

Fixed link to terraform/upi template

---

images/openstack/Dockerfile.ci

The OpenStack CI will use Route 53 to create the DNS records necessary
for the tests. We will use the `aws` CLI tool to create and delete them.
This adds the tool to the CI image.
Backport of: https://github.com/openshift/installer/pull/2663
/cc @tomassedovic

Bug 1775531: images/openstack: add awscli to image

---

images/openstack/Dockerfile.ci

Replace a valid and registered domain with an IETF "invalid" domain for
testing purposes.
Ref: https://tools.ietf.org/html/rfc2606
/hold
until master branch is open.

openstack: Use an invalid domain for testing

---

docs/user/openstack/install_upi.md

The information on how to create an image in Glance was removed from IPI docs, so we need to add it to UPI docs since it's still required there.

Docs: Add info about RHCOS image uploading to UPI docs

---

upi/openstack/02_security-groups.yaml
upi/openstack/down-02_security-groups.yaml
upi/openstack/inventory.yaml

Create an Ansible playbook for deploying the Security Groups required
for a User Provided Infrastructure installation.
Implements https://jira.coreos.com/browse/OSASINFRA-785
Depends on #2580

openstack UPI: Automate Security Group creation

---

data/data/baremetal/main.tf
pkg/terraform/exec/plugins/Gopkg.lock
pkg/terraform/exec/plugins/Gopkg.toml
pkg/terraform/exec/plugins/vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/resource_ironic_deployment.go
pkg/terraform/exec/plugins/vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/workflow.go

With 1.56 of the Ironic API, we can send Ironic the JSON data for a config
drive, rather than a base64-encoded, gzipped ISO9660 image. This avoids
a dependency on the host running the installer to have mkisofs
available.

baremetal: update terraform-provider-ironic and use newer API

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

The trap command to delete etcd-signer on failure isn't getting invoked as functions don't inherit trap commands without -E option.

data/bootstrap: Add -E option to make the functions inherit trap

---

data/data/rhcos.json

This has fixes for encryption, see e.g.:
- https://bugzilla.redhat.com/show_bug.cgi?id=1775728

Bug 1775728: rhcos: Bump to 43.81.201911221453.0

---

images/openstack/Dockerfile.ci

The POSIX default locales cause the following error while retrieving
nova console logs:
UnicodeEncodeError: 'ascii' codec can't encode characters in position
As explained in [1] we should set the locales to UTF8 to workaround the
issue.
[1] https://docs.openstack.org/python-novaclient/train/cli/nova.html#nova-console-log

Bug 1775062:OpenStack: Use UTF-8 locales in CI container image

---

pkg/tfvars/baremetal/baremetal.go

When using redfish accessDetails.Type() differs from
accessDetails.Driver(), we simply need "redfish"(without
the http/https)
Closes: metal3-io/baremetal-operator#352

baremetal: Use accessDetails.Driver() in terraform config

---

docs/user/openstack/install_upi.md

Are allow address pairs necessary for Workers? Ingress port IP address is. 
Are API and DNS needed too? They are for Master role, aren't they?
Also, I believe ingress IP address is not needed for Bootstrap. At least not in the fully automated Openstack installation
https://github.com/openshift/installer/search?q=allowed_address_pairs&unscoped_q=allowed_address_pairs

Allowed address pairs for bootstrap and workers

---

pkg/tfvars/openstack/openstack.go
pkg/types/openstack/validation/realvalidvaluesfetcher.go

We obtain the service catalog in several places inside the code, but each time we expect that project_name is specified in the clouds.yaml, and if it's not there, installation fails.
In general it's not necessary and users can specify just project_id instead of the name.
This commit updates the service catalog downloading functions by removing this restriction.

Bug 1776272: OpenStack: fix getting service catalog

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
data/data/manifests/bootkube/etcd-host-service-endpoints.yaml.template
pkg/asset/ignition/bootstrap/bootstrap.go
pkg/asset/manifests/operators.go

In 4.4 cluster-etcd-operator will take over the process of bootstrapping the etcd cluster. To provide a clear path to disable/revert these changes we have setup the following conditional logic.
**MCO**: The MCO render command invoked in bootkube has a new optional flag to pass the value of the `cluster-etcd-operator` image[1]. The availability of this flags value[2] is used to conditionally adjust the `etcd-member` static pod spec allowing it to use the new bootstrapping method via the operator or fall back to the 4.3 SRV method.
**Installer**: The installer in 4.4 has a few notable changes introduced by this PR. First of all the `render` command populates a static pod manifest which creates a single member etcd cluster. After we have the single node cluster we can progress and …

*: add support for cluster-etcd-operator

---

data/data/baremetal/main.tf
pkg/terraform/exec/plugins/Gopkg.lock
pkg/terraform/exec/plugins/Gopkg.toml
pkg/terraform/exec/plugins/vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/resource_ironic_deployment.go
pkg/terraform/exec/plugins/vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/workflow.go

Cherry pick of #2571
With 1.56 of the Ironic API, we can send Ironic the JSON data for a config
drive, rather than a base64-encoded, gzipped ISO9660 image. This avoids
a dependency on the host running the installer to have mkisofs
available.

Bug 1778894: baremetal: update terraform-provider-ironic and use newer API

---

upi/openstack/04_control-plane.yaml
upi/openstack/down-04_control-plane.yaml
upi/openstack/inventory.yaml

Create an Ansible playbook for deploying the Control Plane required for
a User Provided Infrastructure installation.
Implements https://jira.coreos.com/browse/OSASINFRA-787

openstack UPI: Automate Control Plane creation

---

pkg/asset/installconfig/clusterid.go
pkg/asset/installconfig/clusterid_test.go
pkg/destroy/gcp/bucket.go

The registry-operator removes multiple dashes for the storage bucket name [1]. And since GCP does name based mathcing we leak the storage bucket.
And looks like the image-regsitry operator is removing the repeating dashes for all plaforms [2] even though looks like Azure is the only platform that has the restriction.
[1]: https://github.com/openshift/cluster-image-registry-operator/blob/a0efd48f8bc2c8d18d53fc5a9e5b8515b94bc2a4/pkg/storage/util/util.go#L140-L143
[2]: openshift/cluster-image-registry-operator#382

Bug 1764812: pkg/destroy/gcp/bucket.go: join multipe dashes when looking for cluster bucket prefix

---

upi/vsphere/machine/ignition.tf

v1.2.0 of the ignition provider breaks the vSphere UPI terraform with
invalid json
Fixes #2748

Bug 1779740: vSphere UPI: set specific version of ignition provider

---

Gopkg.lock
pkg/asset/installconfig/aws/session.go
pkg/asset/installconfig/azure/session.go
pkg/asset/installconfig/gcp/session.go
pkg/asset/installconfig/installconfig.go
pkg/asset/installconfig/openstack/openstack.go
pkg/asset/installconfig/openstack/realvalidvaluesfetcher.go
pkg/asset/installconfig/openstack/session.go
pkg/asset/installconfig/platformcredscheck.go
pkg/asset/manifests/cloudproviderconfig.go
vendor/github.com/gophercloud/utils/env/env.go
vendor/github.com/gophercloud/utils/env/env_windows.go
vendor/github.com/gophercloud/utils/openstack/clientconfig/doc.go
vendor/github.com/gophercloud/utils/openstack/clientconfig/requests.go
vendor/github.com/gophercloud/utils/openstack/clientconfig/utils.go

Fixes https://jira.coreos.com/browse/CORS-1219
On AWS, Azure and GCP, provide `INFO` logs with the full path of the file where credentials were loaded from, and if possible `DEBUG` logs with all paths tried. OpenStack will be provided on a separate PR: https://github.com/openshift/installer/pull/2655.

Log credentials loading for AWS, Azure, GCP, OpenStack

---

upi/openstack/05_compute-nodes.yaml
upi/openstack/down-05_compute-nodes.yaml
upi/openstack/inventory.yaml

Create an Ansible playbook for deploying the Compute nodes required for
a User Provided Infrastructure installation.
Implements https://jira.coreos.com/browse/OSASINFRA-788

openstack UPI: Automate Compute nodes creation

---

upi/vsphere/machine/ignition.tf

v1.2.0 of the ignition provider breaks the vSphere UPI terraform with
invalid json
cherry-pick: #2749

[release-4.3] Bug 1779791:vSphere UPI: set specific version of ignition provider

---

upi/openstack/inventory.yaml

We don't support running clusters with less than 3 compute nodes, even if it is theoretically possible, because it is unreliable.

OpenStack UPI: Set Default Compute Nodes to 3

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

This PR adds the cluster-config-file flag to render for CEO. This is important so that we can conclude if the cluster is singleStack IPv6.
We also internally changed render to not install CA certs on bootstrap node and instead manually move these assets for visibility as it is existing in current logic with other operators.
Signed-off-by: Sam Batschelet <sbatsche@redhat.com>

bootkube.sh: CEO: add cluster-config-file to parse sdn cidr

---

upi/openstack/01_network.yaml
upi/openstack/down-01_network.yaml
upi/openstack/inventory.yaml

Adds a router to the cluster network. This allows floating ips to be allocated and the cluster to be reached from outside the cluster.

OpenStack UPI: add a router to cluster network

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

This PR resolves an issue where on retry `ETCD_ENDPOINTS` was not properly handled. The result was an invalid list which could lead to installer timeouts.
This issue would not yet have affected any clusters as the issue would only be possible if CEO was in a Managed state which to date has not been true.

bootkube.sh: CEO: properly handle etcd endpoints on retry

---

pkg/asset/manifests/openstack/cloudproviderconfig.go

After the change in how the CloudProviderConfig INI file is generated,
the struct is no longer used and may cause confusion.
This change does not impact any currently running code.

openstack: Remove dead code

---

Gopkg.lock
data/data/baremetal/masters/main.tf
data/data/baremetal/masters/variables.tf
data/data/baremetal/variables-baremetal.tf
pkg/tfvars/baremetal/baremetal.go
vendor/github.com/metal3-io/baremetal-operator/pkg/apis/metal3/v1alpha1/baremetalhost_types.go
vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/access.go
vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/idrac.go
vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/ipmi.go
vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/irmc.go
vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/redfish.go

In order to support additional mechanisms for provisioning machines
beyond iPXE, such as Virtual Media, we need to be able to configure
various interfaces (boot_interface, power_interface, etc). This data comes from baremetal-operator, as baremetal-operator's BMC code now handles providers that use virtual media. Venoring was updated using the following command:
dep ensure -update github.com/metal3-io/baremetal-operator

baremetal: configure ironic interfaces for other boot mechanisms

---

pkg/asset/installconfig/clustername.go
pkg/types/gcp/validation/platform.go
pkg/types/validation/installconfig.go
pkg/types/validation/installconfig_test.go

Validation of the Cluster Name in the wizard or metadata.name in the install-config only ensures validity as a domain name. The cluster name is also used to name resources created by the installer, and this commit adds validation to ensure that the domain name meets the requirements for naming resources in GCP. This has caused failed installs in GCP when cluster names begin with numbers.

Bug 1777232: Add GCP-specific validation of cluster name.

---

pkg/asset/asset.go
pkg/asset/store/store.go

By default, kubeconfig and kubeadmin-password are installed with world readable
permissions. This fix addresses that.
See CVE-2019-19335
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1778972

Bug 1778972: Default new file and directory permissions to not be world readable

---

pkg/destroy/gcp/policybinding.go

Based on https://cloud.google.com/resource-manager/reference/rest/Shared.Types/Binding
The members values can be:
```
deleted:serviceAccount:{emailid}?uid={uniqueid}: An email address (plus unique identifier) representing a service account that has been recently deleted. For example, my-other-app@appspot.gserviceaccount.com?uid=123456789012345678901. If the service account is undeleted, this value reverts to serviceAccount:{emailid} and the undeleted service account retains the role in the binding.
```
this looks like a new addition to the API since the archive from Oct 26, 2019 doesn't have these value type. see https://web.archive.org/web/20181026092140/https://cloud.google.com/resource-manager/reference/rest/Shared.Types/Binding
Also it doesn't look like the API is being consistent …

Bug 1782583: destroy/gcp/policybinding.go: identity deleted service accounts belonging to the cluster

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
data/data/bootstrap/files/usr/local/bin/crio-configure.sh.template

This would ensure CRIO's bootstrap would use FCOS-compatible hooks dir.
PR https://github.com/openshift/machine-config-operator/pull/1311 would 
do the same for masters and workers.
This also ensures mkdir calls have `--parent` so that these would not fail if dirs already exist
/cc @LorbusChris @smarterclayton

[FCOS] bootstrap: replace CRIO's hooks dir on bootstrap

---

data/data/openstack/bootstrap/main.tf

Now we create the bootstrap floating ip in the beginning of the installation and then wait the bootstrap machine to become ready. If the provisioning takes more than 10 minutes, due to long image uploading or other reasons, fip creation fails with timeout. 
To prevent this we should create the fip when the machine is already available.

Bug 1780534: create bootstrap floating ip after the bootstrap machine

---

data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh

Save journal output of machine-config-daemon service. This simplifies debugging when MCD image is being pulled.
/cc @smarterclayton @LorbusChris

[FCOS] install-masters-gather: gather logs for machine-config-daemon-pull

---

pkg/asset/manifests/openstack/cloudproviderconfig.go
pkg/asset/manifests/openstack/cloudproviderconfig_test.go

We can't use "go-ini" library to generate the config, because it's incompatible with "gcfg" library that we use to read the data.
For instance, if there is a string with a # character, then "go-ini" wraps it in bacticks, like \`aaa#bbb\`, but gcfg doesn't recognize it and parses the data as \`aaa, skipping everything after the #.
So, we have to generate the config manually, avoiding possible issues with "go-ini".

[release-4.2] Bug 1771358: manually prepare cloud provider's config

---

pkg/destroy/gcp/iam.go

This is a cherry pick of https://github.com/openshift/installer/pull/2790
Based on https://cloud.google.com/resource-manager/reference/rest/Shared.Types/Binding
The members values can be:
```
deleted:serviceAccount:{emailid}?uid={uniqueid}: An email address (plus unique identifier) representing a service account that has been recently deleted. For example, my-other-app@appspot.gserviceaccount.com?uid=123456789012345678901. If the service account is undeleted, this value reverts to serviceAccount:{emailid} and the undeleted service account retains the role in the binding.
```
this looks like a new addition to the API since the archive from Oct 26, 2019 doesn't have these value type. see https://web.archive.org/web/20181026092140/https://cloud.google.com/resource-manager/reference/rest/Share …

[release-4.2] Bug 1782588: destroy/gcp/policybinding.go: identity deleted service accounts belonging to the cluster

---

docs/user/aws/install_upi.md

In the IPI-based installation flow, we added a step which takes the official RHCOS images and encrypts them for the user's AWS account. There is a misconception this is not possible or advised in the UPI-based flow. This PR adds a few notes to describe how and where it would be performed during a UPI flow as well as provides a couple doc links.

Adding optional AMI encryption step to the AWS UPI docs

---

data/data/rhcos.json

This has encryption/FIPS fixes.  Among other things, TPM2 binding
by default on metal is disabled by default.  See also
https://github.com/openshift/enhancements/pull/140
Note this is not a direct cherry-pick because RHCOS has branched for 4.4.
https://bugzilla.redhat.com/show_bug.cgi?id=1775388

Bug 1782546: rhcos: Bump to 43.81.201912091858.0

---

data/data/bootstrap/files/usr/local/bin/crio-configure.sh.template
data/data/rhcos.json

There aren't yet large changes from 4.3, but among other things
this one is at least officially version stamped 4.4, which should
help us distinguish fresh 4.4 installs from 4.3.
This also includes a fix for partitioning.

rhcos: Bump to 44.81.201912121813.0

---

docs/user/metal/install_ipi.md

baremetal has additional troubleshooting steps related to the use of a
libvirt bootstrap VM that hosts an instance of Ironic. This adds some
additional information beyond the normal OpenShift troubleshooting
material.

docs/baremetal: add additional troubleshooting information

---

docs/user/aws/limits.md

AWS recently changed the instance limit to a vCPU limit
Fixes #2736

aws: add new vCPU limit to docs

---

upi/openstack/03_bootstrap.yaml
upi/openstack/down-03_bootstrap.yaml

The `auto_ip` option to `os_server` is unreliable as it may not pick an
IP address from the floating IP pool we want in case the cloud has
multiple floating IP pools. Instead we create the FIP and assign it to
the node in a separate task.
We need to explicitely disable `auto_ip` as the default value is yes.

openstack UPI: Do not rely on auto_ip to create bootstrap FIP

---

upi/openstack/01_network.yaml
upi/openstack/02_security-groups.yaml
upi/openstack/03_bootstrap.yaml
upi/openstack/04_control-plane.yaml
upi/openstack/05_compute-nodes.yaml
upi/openstack/down-01_network.yaml
upi/openstack/down-02_security-groups.yaml
upi/openstack/down-03_bootstrap.yaml
upi/openstack/down-04_control-plane.yaml
upi/openstack/down-05_compute-nodes.yaml

As the target of Ansible is technically localhost, there is no need to
gather facts prior the playbook runs. This cuts on unnecessary waiting
time during execution.

openstack UPI: Skip gathering facts

---

data/data/bootstrap/files/etc/zincati/config.d/90-disable-feature.toml

FCOS update has been recently so bootstrap/masters get rebooted in the middle of pivot.
This would disable Zincati so that it would not hit FCOS update servers on bootstrap.
/cc @smarterclayton @LorbusChris

[FCOS] bootstrap: disable zincati on bootstrap

---

upi/openstack/01_network.yaml
upi/openstack/02_security-groups.yaml
upi/openstack/03_bootstrap.yaml
upi/openstack/04_control-plane.yaml
upi/openstack/05_compute-nodes.yaml
upi/openstack/down-01_network.yaml
upi/openstack/down-02_security-groups.yaml
upi/openstack/down-03_bootstrap.yaml
upi/openstack/down-04_control-plane.yaml
upi/openstack/down-05_compute-nodes.yaml
upi/openstack/inventory.yaml

- get cluster-name from infraID generated by the installer from the metadata.json now
- Make the naming scheme uniform with how we name resources in IPI

[OpenStack][UPI]: tweaks

---

images/openstack/Dockerfile.ci

Analog to https://github.com/openshift/installer/blob/master/images/installer/Dockerfile.upi.ci#L11-L14
cc @vrutkovs

images/openstack: Make cli stage overrideable

---

upi/openstack/02_network.yaml
upi/openstack/README.md
upi/openstack/requirements.txt

Ensure reproducibility by pinning specific versions for all Ansible
dependencies.
Additionally, this patch removes the instructions for installing with
YUM, as YUM-provided versions are not fully compatible with the
playbooks.
Implements OSASINFRA-1085

openstack UPI: Pin dependencies

---

data/data/rhcos.json

Use F31 as a base to follow latest stable version

[FCOS] rhcos.json: update AMIs to FCOS 31.20191211.1

---

docs/user/azure/customization.md
docs/user/customization.md
docs/user/metal/install_ipi.md
docs/user/openstack/known-issues.md
pkg/asset/cluster/tfvars.go
pkg/asset/installconfig/aws/validation.go
pkg/asset/installconfig/aws/validation_test.go
pkg/asset/installconfig/azure/validation.go
pkg/asset/installconfig/azure/validation_test.go
pkg/asset/installconfig/gcp/validation.go
pkg/asset/installconfig/gcp/validation_test.go
pkg/asset/installconfig/installconfig_test.go
pkg/asset/machines/libvirt/machines.go
pkg/asset/machines/libvirt/machinesets.go
pkg/asset/manifests/operators_test.go
pkg/asset/manifests/proxy.go
pkg/types/baremetal/validation/platform.go
pkg/types/baremetal/validation/platform_test.go
pkg/types/conversion/installconfig.go
pkg/types/conversion/installconfig_test.go
pkg/types/defaults/installconfig.go
pkg/types/defaults/installconfig_test.go
pkg/types/installconfig.go
pkg/types/openstack/defaults/platform.go
pkg/types/validation/installconfig.go
pkg/types/validation/installconfig_test.go
pkg/validate/validate.go
pkg/validate/validate_test.go
upi/vsphere/README.md

Better support future IPv6 and dual stack by allowing some platforms
to accept multiple machine CIDRs. Add validation logic that checks
for some known IPv6 behaviors at the same time.

types: Deprecate MachineCIDR, replace with MachineNetwork: []

---

docs/user/openstack/install_upi.md

Replace MachineCIDR in UPI documentation with MachineNetwork: []
Ref: https://github.com/openshift/installer/pull/2829
/cc @mandre @iamemilio

Openstack UPI: Deprecate MachineCIDR

---

docs/user/openstack/install_upi.md

A previous change referenced the cluster network instead of the machine
network.
ref: https://github.com/openshift/installer/pull/2829
ref: https://github.com/openshift/installer/pull/2892
/label platform/openshift
/cc @mandre @iamemilio

Openstack UPI: machineCIDR machineNetwork.[].cidr

---

pkg/destroy/openstack/openstack.go

When using Kuryr SDN the number of resources created on the
OpenStack side is way larger than for the OpenShift SDN case.
For this reason, as there is no specific order for the resources
to be deleted, the chances of the deletion of one resource (e.g.,
a network) being blocked by the deletion of another (e.g. a port
on that network) are higher, thus needed more retries.

Bug 1789746: Ensure enough number of retries for cluster with Kuryr SDN

---

cmd/openshift-install/log.go
cmd/openshift-install/version.go
pkg/asset/releaseimage/default.go
pkg/version/version.go

Set a marker for oc to inject the release version to avoid potential confusion from:
```console
$ oc adm release extract --command=openshift-install quay.io/openshift-release-dev/ocp-release:4.2.7
$ ./openshift-install version
./openshift-install v4.2.5
built from commit 425e4ff0037487e32571258640b39f56d5ee5572
release image quay.io/openshift-release-dev/ocp-release@sha256:bac62983757570b9b8f8bc84c740782984a255c16372b3e30cfc8b52c0a187b9
```
The actual oc injection logic is in openshift/oc#165.

Bug 1773257: pkg/version: Prepare of extract-time oc version injection

---

images/libvirt/Dockerfile.ci

When we built the installer for CI, we discovered that the dependency on epel-release, which was required to build locally, doesn't seem to be present when building from openshift/release.

images/libvirt: remove epel-release

---

pkg/asset/installconfig/installconfig_test.go
pkg/types/defaults/installconfig.go
pkg/types/installconfig.go
pkg/types/validation/installconfig_test.go

Switch default SDN plugin to OVN. It has more features, upstream community and OCP would eventually switch to it. 
Short-term goal is to work around https://bugzilla.redhat.com/show_bug.cgi?id=1781575

[FCOS] Use OVNKubernetes network config by default

---

docs/user/vsphere/customization.md
docs/user/vsphere/install_upi.md

It's been `vCenter` since the property landed in 3e73413069 (#1591).  This commit fixes `vcenter` typos from 0ec07d0769 (#1545) and a947609d66 (#2162).

docs/user/vsphere: Fix "vcenter" -> "vCenter"

---

images/libvirt/Dockerfile.ci
images/libvirt/README.md
images/libvirt/google-cloud-sdk.repo
images/libvirt/mock-nss.sh

The current nested-libvirt CI image is capable of provisioning libvirt clusters by creating a GCE VM instance that has all of the libvirt dependencies and using it as a hypervisor. This new image supports that workflow as well as providing the dependencies for running a libvirt installation against a remote libvirt service hosted on external hardware. This requires access to the libvirt client locally, which the nested libvirt image did not provide.

images: add a new generic libvirt CI image

---

data/data/rhcos.json

This bump fixes an updated issue with NIC bonding as well as the `growpart` issue.
Fixes:
- https://bugzilla.redhat.com/show_bug.cgi?id=1789601
- https://bugzilla.redhat.com/show_bug.cgi?id=1789014
**NOTE**: Another PR to master will take place soon which will be different artifacts :slightly_smiling_face: 
/cc @imcleod @cuppett @crawford @miabbott @jlebon

Bug 1789601: rhcos: Bump to 43.81.202001141554.0

---

upi/openstack/01_security-groups.yaml
upi/openstack/02_network.yaml
upi/openstack/03_bootstrap.yaml
upi/openstack/04_control-plane.yaml
upi/openstack/05_compute-nodes.yaml
upi/openstack/README.md
upi/openstack/common.yaml
upi/openstack/down-01_security-groups.yaml
upi/openstack/down-02_network.yaml
upi/openstack/down-04_control-plane.yaml
upi/openstack/down-05_compute-nodes.yaml
upi/openstack/down-06_load-balancers.yaml
upi/openstack/inventory.yaml
upi/openstack/library/os_delete_lb_resources.py
upi/openstack/library/os_delete_network_resources.py
upi/openstack/library/os_delete_ports_on_router.py
upi/openstack/library/os_tag.py
upi/openstack/library/os_trunk.py

Update ansile playbooks to support setting Kuryr as networking
type for a User Provided installation.

OpenStack: Automate UPI with Kuryr

---

pkg/asset/installconfig/pullsecret.go
pkg/validate/validate.go

This PR lets the installer CLI accept empty pull secrets without throwing an error, since OKD does not require a valid pull secret.

[FCOS] pkg/asset: Drop requirement for CLI specified pull secret

---

data/data/rhcos.json

Signed version of https://github.com/openshift/installer/pull/2914.
/cc @sdodson @jtligon @cuppett @miabbott @crawford

Bug 1791332: rhcos: Bump to 43.81.202001142154.0 for signed packages

---

data/data/rhcos-amd64.json
docs/user/customization.md
hack/update-rhcos-bootimage.py
pkg/asset/installconfig/installconfig_test.go
pkg/asset/manifests/operators_test.go
pkg/asset/rhcos/bootstrap_image.go
pkg/asset/rhcos/image.go
pkg/rhcos/ami.go
pkg/rhcos/azure.go
pkg/rhcos/builds.go
pkg/rhcos/gcp.go
pkg/rhcos/openstack.go
pkg/rhcos/qemu.go
pkg/types/defaults/machinepools.go
pkg/types/defaults/machinepools_test.go
pkg/types/machinepools.go
pkg/types/validation/installconfig.go
pkg/types/validation/installconfig_test.go
pkg/types/validation/machinepools.go
pkg/types/validation/machinepools_test.go

This doesn't actually include support for s390x, since we don't have any s390x builds yet. The intent is that this will be backported (where we do have builds) and the master branch will be updated once builds are available.
/cc @cgwalters @jaypoulz @dgoodwin 
/hold

*: add groundwork for muiti-arch bootimages

---

Gopkg.lock
pkg/asset/cluster/tfvars.go
pkg/asset/machines/master.go
pkg/asset/machines/vsphere/machines.go
pkg/asset/machines/vsphere/machinesets.go
pkg/asset/machines/worker.go
pkg/types/vsphere/machinepool.go
pkg/types/vsphere/platform.go
vendor/github.com/openshift/machine-api-operator/pkg/apis/vsphereprovider/addtoscheme_vsphereprovider_v1alpha1.go
vendor/github.com/openshift/machine-api-operator/pkg/apis/vsphereprovider/apis.go

Adds machines and machinesets for VSphere workers and control plane. Plumbs values through to tfvars.
/cc @jcpowermac

Add machines and machinesets for VSphere

---

pkg/asset/manifests/proxy.go

The installer creates a manifest for proxy configuration, automatically
adding specific addresses to NO_PROXY depending on the platform. One of
those addresses is the metadata service, hosted at 169.254.169.254. The
installer assumes this must be done for all platforms other than None of
vSphere, whereas the cluster-network-operator has an explicit list of
platforms:
https://github.com/openshift/cluster-network-operator/blob/adaf257b4d63661726443ab2b059a9b4209a02d1/pkg/util/proxyconfig/no_proxy.go#L67-L69
When using a proxy with baremetal IPI, the installer adds this address,
however when the CNO comes up, it does not, causing the rendered
machine configs to differ, and installation to fail, with MCO reporting
errors like:
```
pool master has not progressed to latest configuration: …
```

Bug 1791993: proxy: use explicit list of platforms for metadata addresses

---

pkg/terraform/exec/plugins/Gopkg.lock
pkg/terraform/exec/plugins/Gopkg.toml
pkg/terraform/exec/plugins/vendor/github.com/Azure/azure-sdk-for-go/services/network/mgmt/2018-12-01/network/loadbalancers.go
pkg/terraform/exec/plugins/vendor/github.com/Azure/azure-sdk-for-go/services/network/mgmt/2018-12-01/network/models.go
pkg/terraform/exec/plugins/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/data_source_subnet.go
pkg/terraform/exec/plugins/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_loadbalancer.go
pkg/terraform/exec/plugins/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_public_ip.go
pkg/terraform/exec/plugins/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_subnet.go

The azurerm provider does not fully support IPv6. Until that time, switch
to a fork of the provider based on 1.27.1 plus three specific fixes that
allow dual stack configuration on Azure.
When we switch to newer azurerm/terraform, we can drop these. To do Azure
CI, we need these changes.

pkg/terraform/exec/plugins: Switch to Azure 1.27.1 fork with Azure fixes

---

images/installer/Dockerfile.upi.ci
upi/vsphere/machine/ignition.tf

See https://github.com/openshift/installer/pull/2952#issuecomment-576450372
Current issues:
* ~~[x] Update code to tf 0.12~~
* ~~[ ] Fix `No instance found for the given address!` for `terraform state show 'module.bootstrap.external.ip_address'` call~~

WIP [FCOS] vSphere: update UPI files to tf 1.12

---

data/data/azure/vnet/vnet.tf

Remove Azure route table
Azure route table resource is not used anywhere and is not linked to any vnet. It is confusing to end-users and its additional cost in the long run.

Azure: remove unused resources

---

pkg/asset/installconfig/clustername.go
pkg/types/validation/installconfig.go

When the user chooses to create an install config using the installer console, picks the GCP environment and gives an improper cluster name, the error message that is being displayed now is that the name fails to match the norms of openshift but a better error message is to show that GCP needs the name in a specific format.
Another bug was found when the user loads the install configs with an improper cluster name, both the GCP error message and the openshift error messages were being displayed. Fixed the UI errors.

Bug 1786268: Set GCP validation to precede domain validation.

---

upi/openstack/02_network.yaml
upi/openstack/inventory.yaml
upi/openstack/library/os_create_subnet_pool.py

Update UPI playbook to account for user provided subnet pool
for pods when Kuryr SDN is used.
Depends on: #2746

OpenStack: Add support to user provided subnet pool

---

data/data/vsphere/bootstrap/main.tf
data/data/vsphere/bootstrap/variables.tf
data/data/vsphere/main.tf
data/data/vsphere/master/ignition.tf
data/data/vsphere/master/main.tf
data/data/vsphere/master/variables.tf
data/data/vsphere/variables-vsphere.tf
docs/user/vsphere/customization.md
pkg/asset/machines/master.go
pkg/asset/machines/vsphere/machines.go
pkg/asset/machines/worker.go
pkg/tfvars/vsphere/vsphere.go
pkg/types/vsphere/machinepool.go

- updates ignition in vSphere terraform code to use `id` instead of `rendered`, this prevents an error due to the version of the ignition provider used by the installer
- read and use `eagerly_scrub` and `thin_provision` from template to ensure that these settings are not changed after vm creation (causing failures)
- set default resources in tf amd machinesets based on [docs](https://docs.openshift.com/container-platform/4.2/installing/installing_vsphere/installing-vsphere.html#minimum-resource-requirements_installing-vsphere)
- require cluster in platform based on current terraform code, which must use a prexisting cluster
This can be tested in our vsphere dev cluster by hardcoding ` var.vsphere_template` to `rhcos-latest`. ~~and setting `allow_unverified_ssl` to true. I have not been …

vSphere: fix disk issues in TF, include default CPU & memory

---

data/data/manifests/bootkube/cvo-overrides.yaml.template
docs/user/troubleshooting.md

Now that we are on 4.4 we need to update the default channel.
Make the example slightly simpler on version number to better reflect what
a human might see. Noticed this while updating the channel to stable-4.3 -
apparently we'd also found and replaced this value before.

bootkube: Update to stable-4.4 channel

---

cmd/openshift-install/gather.go
pkg/asset/ignition/machine/node.go
pkg/asset/machines/baremetal/machines.go
pkg/tfvars/baremetal/baremetal.go

You can't just manually join an IP and port because that will break
with an IPv6 address.  net.JoinHostPort() will do the right thing and
add square brackets around an IPv6 address.
Reported-by: Steven Hardy <shardy@redhat.com>

ipv6: Fix joining IP and port number

---

data/data/rhcos-amd64.json
data/data/rhcos.json

This commit is a result of running:
`./hack/update-rhcos-bootimage.py https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.4/44.81.202001240222.0/x86_64/meta.json amd64`
```sh
$ ./differ.py --first-endpoint art --first-version 44.81.202001171431.0 --second-endpoint art --second-version 44.81.202001240222.0
{
"sources": {
"44.81.202001171431.0": "https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.4/44.81.202001171431.0/x86_64/commitmeta.json",
"44.81.202001240222.0": "https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.4/44.81.202001240222.0/x86_64/commitmeta.json"
},
"diff": {
"cri-o": {
"44.81.202001171431.0": "cri-o-1.17.0-0.2.rc1.rhaos4.4.gitb89a5fc.el8.x86_64",
"44.81.202001240222.0": …
```

Bump RHCOS to 44.81.202001240222.0

---

pkg/asset/ignition/machine/node.go

Does not set vSphere specific ignitionHost if APIVIP is not provided.

Correct ignitionHost for vSphere UPI

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
data/data/bootstrap/gcp/files/usr/local/bin/report-progress.sh

In order for the [call](https://github.com/openshift/installer/blob/b385f165cea0c7340742423df0c9b433ff76dca6/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template#L396) to the controle plane api work on gcp,
the gcp-routes.service needs to be stopped.

bootkube.sh.template: stop gcp-routes.service after cvo-bootstrap

---

cmd/openshift-install/gather.go
pkg/terraform/gather/vsphere/ip.go

Use terraform state to find virtual machines
managed object reference value (vm-#).
Using the value create a ManagedObjectReference
to create a NewVirtualMachine.
For each vm wait for the ip address and return results

Add gather bootstrap for vsphere

---

data/data/rhcos-amd64.json
data/data/rhcos.json

```
./hack/update-rhcos-bootimage.py https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.4/44.81.202001241932.0/x86_64/meta.json amd64
```
Notably, this includes a fix for IPv6 single-stack:
https://bugzilla.redhat.com/show_bug.cgi?id=1787620
https://bugzilla.redhat.com/show_bug.cgi?id=1793591
```
$ ./differ.py --first-endpoint art --first-version 44.81.202001240222.0 --second-endpoint art
--second-version 44.81.202001241932.0
{
"sources": {
"44.81.202001240222.0": "https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.4/44.81.202001240222.0/x86_64/commitmeta.json",
"44.81.202001241932.0": "https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.4/44.81.202001241932.0/x86_64/commitmeta.json"
},
"diff": { …
```

Bump RHCOS to 44.81.202001241932.0

---

OWNERS
data/data/bootstrap/files/etc/ignition-machine-config-encapsulated.json.template
data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
data/data/rhcos-amd64.json
pkg/asset/ignition/machine/node.go

* Dockerfile.upi: fix terraform-ignition bin path
* `data/data/rhcos.json -> data/data/rhcos-amd64.json` (not sure if the previous version should be kept)
* Add fcos-approvers group (me and Christian)
* Fix IgnitionHost in vSphere UPI setup
* bootstrap: ensure "runc" is used as a podman runtime, as its a bit more stable than crun
TODO:
```
[   10.567447] ignition[603]: error at $.storage.files.128.mode, line 1 col 319077: path not absolute
[   10.577928] ignition[603]: failed to fetch config: config is not valid
```

[FCOS] Post-Jan20 rebase fixes

---

upi/aws/cloudformation/03_cluster_security.yaml

This change allows access for udp ports 9000-9999 and 30000-32767 on aws upi clusters the same way we do on ipi clusters.

Bug 1763936: aws upi: enable udp ports 9000-9999 and 30000-32767

---

cmd/openshift-install/main.go

When openshift-install prints a usage message, it always uses the
hardcoded value "openshift-install", but in the case of the baremetal
installer, `oc` extracts it as `openshift-baremetal-install`.
In case the installer is renamed, we should look at `os.Args[0]` for the
correct name instead of having this hardcoded.
Before:
```
$ openshift-baremetal-install 
Creates OpenShift clusters
Usage:
openshift-install [command]
Available Commands:
completion  Outputs shell completions for the openshift-install command
create      Create part of an OpenShift cluster
destroy     Destroy part of an OpenShift cluster
gather      Gather debugging data for a given installation failure
graph       Outputs the internal dependency graph for installer
help        Help about any command
version     Print …
```

Bug 1794750: cmd/openshift-install: use binary name for usage

---

docs/dev/openstack/OWNERS
docs/dev/openstack/customization.md
docs/user/openstack/README.md
docs/user/openstack/known-issues.md
docs/user/openstack/troubleshooting.md

This PR updates OpenStack documentation based on recent changes.
1. Updates Swift requirements. Now Swift is not a mandatory service but just an optional backend for image registry.
2. Adds Glance requirements. Glance is used for storing RHCOS images and bootstrap ignition configs.
3. Adds RHCOS image customization section for disconnected environments.
4. Moves "Cluster destruction if its metadata has been lost" section from "known-issues" to "troubleshooting".

Docs: update OpenStack documentation

---

data/data/rhcos-amd64.json
data/data/rhcos.json

In https://github.com/openshift/installer/pull/2986 we updated RHCOS
to 44.81.202001241932.0, which happened to carry a COSA change
https://github.com/coreos/coreos-assembler/commit/1dc3cddb393fcab1000ee62908aaadb8d41d8ccd
which broke GCP metadata. Since we didn't run e2e-gcp on that 2986,
we didn't catch this. This seems to have broken GCP CI since it is
unable to find the tarball being referenced in the meta.
This temporarily reverts RHCOS to one version previous, which includes
the IPV6 changes but doesn't have the GCP break. This should fix GCP
for now as we fix COSA.
In the future we should probably have each RHCOS bump go through
all the platforms.
Signed-off-by: Yu Qi Zhang <jerzhang@redhat.com>

RHCOS: downgrade to 44.81.202001241431.0

---

cmd/openshift-install/create.go

`cluster-etcd-operator` introduces a new workflow for the installer. By having am etcd instance on the bootstrap node we can quickly move to API up.
But currently, the scaling process of etcd is in some circumstances cresting the 30 min timeout. This PR addresses this short term issue by reducing the api timeout to 20 mins and adding that to the bootstrap timeout.
I had a conversation about this with Clayton this is not a permanent change. CEO must reduce install times not increase.
related to: https://github.com/openshift/cluster-etcd-operator/pull/58

cmd/openshift-install: shift timeouts from api to bootstrap

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

The bootstrap MCS is responsible for serving Ignition configs to the
booting control plane machines while we wait for the full control plane
(which will host the in-cluster MCS). If we remove this too early, it
will prevent the control plane machines from booting and the control
plane from starting. The etcd health check, which is the gate before we
remove the MCS, reports healthly (since the one-node, bootstrap etcd
cluster is actually up) before the control plane machines had a chance
to boot. The result is that one or more of the control plane machines
get stuck during boot (because Ignition is still trying to fetch a
config) and the cluster fails to bootstrap.
This moves the bootstrap MCS removal after bootkube has finished, which
will ensure that all of the initial manifests have …

Bug 1795776: data/bootstrap: delay the removal of bootstrap mcs

---

pkg/asset/installconfig/openstack/session.go

Now, to unmarshal clouds from yaml files we always use type `Clouds`
https://github.com/gophercloud/utils/blob/master/openstack/clientconfig/results.go#L10-L15
But this is wrong because for clouds-public.yaml we should use `PublicClouds`
https://github.com/gophercloud/utils/blob/master/openstack/clientconfig/results.go#L3-L8
otherwise `LoadPublicCloudsYAML` function always returns an empty map.
Fixes: https://github.com/openshift/installer/issues/2997

OpenStack: Use correct type to unmarshal clouds

---

pkg/asset/manifests/vsphere/cloudproviderconfig.go
pkg/asset/manifests/vsphere/cloudproviderconfig_test.go

Before this change, the dependency used for INI generation was
incorrectly escaping special characters.
With this change, every value is double-quoted and escaped with Go
syntax.
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1747474
ref: https://github.com/openshift/installer/pull/2659
If values with quotes are OK for your use case, you may want to merge this change which builds the INI without the help of an external dependency. We found quoted values like these to be correctly parsed by `gopkg.in/gcfg.v1`.
/cc @wking 
/hold

Bug 1777516: Quote values in vSphere INI config

---

data/data/aws/vpc/sg-master.tf
data/data/aws/vpc/sg-worker.tf

This change explicitly allows access for ports 30000-32767 for both tcp
and udp protocols between the control plane and compute instances in
aws ipi at install time.

Bug 1763936: aws: enable node ports between control plane and compute

---

data/data/openstack/masters/main.tf

This makes ignition files FCOS-compatible and should fix error during openstack install:
```
ERROR Error: Unsupported argument                  
ERROR                                              
ERROR   on ../../../../../tmp/openshift-install-117723343/masters/main.tf line 7, in data "ignition_file" "hostname": 
ERROR    7:   filesystem = "root"                  
ERROR                                              
ERROR An argument named "filesystem" is not expected here. 
```

[fcos] openstack: remove "filesystem" from tf files

---

data/data/gcp/network/firewall.tf

This change explicitly allows access for ports 30000-32767 for both tcp
and udp protocols between the control plane and compute instances in
gcp ipi at install time.

Bug 1763936: gcp: enable node ports between control plane and compute

---

pkg/tfvars/openstack/bootstrap_ignition.go

The original pull request for OpenStack self-signed certificates
support [1] formatted the dataurl for the bootstrap ignition file
rather than using the dataurl library used everywhere in the installer.
Let's be consistent with the other parts of the installer creating
dataurls and use the dataurl library.
[1] https://github.com/openshift/installer/pull/2932

Bug 1794640: OpenStack: Use dataurl library

---

data/data/openstack/topology/sg-master.tf
data/data/openstack/topology/sg-worker.tf
upi/openstack/01_security-groups.yaml

Explicitly allows access for ports 30000-32767 for both tcp and udp protocols between the control plane and compute instances for OpenStack platform.

Bug 1763936: OpenStack: enable node ports between control plane and compute

---

cmd/openshift-install/create.go

For a variety of reasons, it may be useful to keep the bootstrap VM
around for debugging. My general approach has been to interrupt the
installer before it has a chance to delete the bootstrap VM.
If the environment variable OPENSHIFT_INSTALL_PRESERVE_BOOTSTRAP is set
to any value, the installer will not delete the bootstrap.

Bug 1796627: cmd/openshift-install/create: add env var to preserve bootstrap

---

docs/user/openstack/README.md

User Docs for openstack auth self signed certificates 
References: https://bugzilla.redhat.com/show_bug.cgi?id=1735192

Bug 1769879: Docs: openstack self signed certs docs

---

pkg/asset/machines/baremetal/hosts.go

We rely on vendored baremetal-operator code to handle various
information about baremetal servers including BMC credentials and
hardware profiles. The BMO uses the string 'unknown' as
`hardware.DefaultProfileName`.
As these string values are exposed to the user in the baremetal platform
as part of the install-config, it felt awkward if a user wanted to
explicitly use the default hardware profile to have to write the string
'unknown'. In golang, people are generally just writing the constant,
'hardware.DefaultProfileName`. So, in the terraform variables, we mapped
the string value 'default' to mean that, but it wasn't done for creating
the machines for workers.
Now that you can deploy workers during installation as a day-1
operation, if you specify the string  'default' for workers, they …

Bug 1796996: baremetal: map hardware profile to baremetal-operator default

---

go.mod
pkg/tfvars/internal/cache/cache.go

Some FCOS images are xz-compressed, however RHCOS is gzipped

[fcos] support xz-encoded images

---

cmd/openshift-install/create.go

Baremetal servers differ significantly from other platforms, especially
due to the length of time it can take to boot real hardware: servers go
through POST (power-on self checks) and hardware initializations that
can take many minutes to complete. When deploying the control plane as
well as workers in the installer, it reliably takes more than 30
minutes.
Recently, we added code to the installer and machine-api-operator that
now allows the installer to deploy workers on day 1. This change even on
virtualized baremetal is running up against the 30-minute time limit. On
real baremetal servers, it's guaranteed the install process is closer to
45 minutes.

Bug 1794755: cmd/openshift-install/create: wait 60 minutes for baremetal

---

pkg/asset/tls/kubelet.go

The revocation can be managed by deleting the configmap where we store
the kubelet trust from openshift-config-managed.
implements https://github.com/openshift/enhancements/pull/196
/assign @rphillips

Bug 1693951: tls: extended lifetime of master kubelet bootstrap credentials

---

docs/user/customization.md

Document how to switch from traditional to realtime kernel
on RHCOS node
Signed-off-by: Sinny Kumari <sinny@redhat.com>

Bug 1796322: [release-4.4] docs: Docs for setting kernelType during initial cluster install

---

docs/user/customization.md

So the relationship is less surprising.  The actual semantics of the `trustedCA` type should be defined in the API repository.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1771564

Bug 1771564: docs/user/customization: Document additionalTrustBundle vs. proxy

---

cmd/openshift-install/gather.go
pkg/asset/ignition/machine/node.go
pkg/asset/machines/baremetal/machines.go
pkg/tfvars/baremetal/baremetal.go

You can't just manually join an IP and port because that will break
with an IPv6 address.  net.JoinHostPort() will do the right thing and
add square brackets around an IPv6 address.
Anywhere we may be using an IPv6 address in a URL needs similar
handling.  We need to ensure the IPv6 address always has square
brackets in this case.  An easy way to do this is to always specify
the port number explicitly so we can use net.JoinHostPort().
Reported-by: Steven Hardy <shardy@redhat.com>

Bug 1794765: ipv6: Fix IPv6 address encoding

---

pkg/destroy/gcp/network.go
pkg/destroy/gcp/route.go

Default routes cannot be manually deleted in GCP, but that doesn't stop us from trying. These attempts result in error messages that look like this:
> Failed to delete route {default-route-013b0a83601b2182 default-route-013b0a83601b2182  route  }: failed to delete route default-route-013b0a83601b2182: googleapi: Error 400: The local route cannot be deleted., badRequest
These error messages have led some users, especially in CI to mistake these as significant errors. This commit attempts to make the error message look like something a l
ittle more expected:
> Failed to delete route default-route-bb10ec00c23c0493: this looks like a default route, which cannot be deleted manually but will be deleted with the corresponding network

Bug 1795436: update error message when deleting default GCP routes

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
data/data/openstack/bootstrap/variables.tf
docs/user/openstack/README.md
docs/user/openstack/known-issues.md
pkg/asset/cluster/tfvars.go
pkg/asset/manifests/cloudproviderconfig.go
pkg/asset/manifests/openstack/cloudproviderconfig.go
pkg/tfvars/openstack/bootstrap_ignition.go

This is a backport of #2932 and #2999 including docs from #3009. There were a few conflicts, mostly caused by #2664 missing from release-4.3.

[release-4.3] Bug 1796822: Support deployment on OpenStack with self-signed certificate

---

cmd/openshift-install/destroy.go

So `destroy cluster` gets you all the way back to a clean slate, even if the cluster in question died during infrastructure provisioning (leaking mentioned [here][1] and [here][2]).
This will obviously not clean up the original asset directory in workflows where the user copies their `metadata.json` over into a new directory and runs `destroy cluster` in the new directory.  But since we have existing asset-state removal code that also behaves that way, I don't think it's a big deal.
`cmd/openshift-install/destroy.go` is a convenient place to put this now, when all of our providers are Terraform-based.  If, in the future, we move some providers off of Terraform (or add new, non-Terraform providers), we can push this down into the platform-specific destroyers.  We could also leave it here, …

Bug 1791400: cmd/openshift-install/destroy: Remove terraform.tfstate in 'destroy cluster'

---

pkg/asset/installconfig/clustername.go
pkg/types/azure/validation/platform.go
pkg/types/validation/installconfig.go

The Azure platform requires a specific format for the names of the clusters which was not present in the installer. Added the checks during both the creation and loading of the install config files to check for Azure validation specifically before trying to create the cluster on Azure if the user chooses said cloud platform.
@patrickdillon

Bug 1784322: Added Azure validation for cluster names

---

pkg/asset/machines/aws/instance_types.go
pkg/asset/machines/master.go
pkg/asset/machines/master_test.go
pkg/asset/machines/worker.go
pkg/asset/machines/worker_test.go
pkg/types/aws/defaults/platform.go

Using new AWS API DescribeInstanceTypeOfferings [1] we can now check what instance types are available for specific region/AZs, which allows us to check which instance types are available in the selected AZs.
Since we default to m4 for most regions and only override to m5 for certain, in cases where new AZs are added to older regions like sa-east-1, see BZ 1774465 [2], we end up picking m4 when m5 is present in all the chosen AZs.
Now we can define a list in descreasing priority order for instance classes for a region and the installer can try to pick default based on what works for all the selected AZs. We still do not support heterogenous setup which different instance types in different regions, but this
solves the case when newer m5 needs to be used in certain regions based on the AZ …

Bug 1774465: aws: pick instance types based on selected availability zones

---

data/data/bootstrap/gcp/files/usr/local/bin/gcp-routes.sh
data/data/bootstrap/systemd/units/gcp-routes.service

This would ensure bootstrap node reports as healthy to GCP LBs
xref openshift/okd#38

[fcos] GCP: add a script and a service which ensure GCP routes are set correctly

---

pkg/destroy/gcp/gcp.go
pkg/destroy/gcp/instance.go

Prior to this change, the gcp destroy process would get stuck in an
infinite loop in the case where an instance has been provisioned in
a cluster subnetwork but the instance name does not contain the infra_id
identifier. As a result, the instance would be ignored and the google
api would complain that the subnetwork was still in use when attempting
to delete it. This can be experienced after adding new machine groups to
a cluster such that the new instance names do not contain the infra_id.
This change enables the destroy process to also delete instances that are
labeled with kubernetes-io-cluster-infraid:owned. This ensures all of
the instances created by the cluster are deleted. As a result, cluster
provisioned instances will no longer block on deletion of subnetworks. …

Bug 1742227: destroy/gcp: also remove instances with owned label.

---

pkg/asset/installconfig/installconfig.go

Right now, using a blank pull secret does not work as the kubelet expects valid auth json in `/root/.docker/config.json` on the bootstrap node. This PR just forces a phony pull secret instead of the empty string at install-config creation time to avoid any parsing issues with a completely empty pull secret. Can come up with a long term fix for no pull-secrets at all later.

[FCOS] pkg/asset: Force phony pull secret in place of no pull secret

---

pkg/destroy/gcp/dns.go

Previously, gcp destroy of dns records evaluated the response from
the dnsSvc.Changes.Create() call. However, sometimes this function
returns nil without returning an error. As a result, the installer
encountered 'panic: runtime error: invalid memory address or nil
pointer dereference'.
This change checks for a nil value before trying to evaluate the
returned object and returns an approperiate error.

Bug 1793627: gcp destroy: handle nil when evaluating dns response

---

data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
pkg/tfvars/baremetal/baremetal.go

Add support for provisioing over IPv6

Bug 1797638: baremetal: Changes needed for IPv6

---

pkg/asset/installconfig/aws/permissions.go

If the user doesn't have this permission, it creates error like
```
ERROR 	* module.masters.aws_network_interface.master[1]: 1 error occurred:
ERROR 	* aws_network_interface.master.1: Error creating ENI: UnauthorizedOperation: You are not authorized to perform this operation.
ERROR 	status code: 403, request id: 9b772002-65ad-4642-86f3-4d314dcfa2e5
```
/cc @sdodson @wking

bug 1729362: aws/permissions.go: add AttachNetworkInterface to required list

---

upi/azure/04_bootstrap.json
upi/azure/05_masters.json

Remove the `bootstrap-0` A and SRV records which are not required and make the remaining SRV records dynamic based on the number of masters being deployed.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1798223

Bug 1798223: Remove unused A and SRV records in Azure UPI

---

pkg/asset/cluster/tfvars.go
pkg/asset/manifests/openshift.go
pkg/asset/openshiftinstall/openshiftinstall.go

This is a follow-up for the logic introduced in 27de643e. The behavior
of the openshift-install ConfigMap is reverted, making it such that the
ConfigMap is always injected in an IPI installation, but never it a UPI
installation. A new ConfigMap, openshift-install-manifests, is
introduced, which is always injected at the manifests target. Both of
these ConfigMaps contain the same data: the invoker and the installer
version, at the time of their respective creation. This will allow us to
continue determining several things:
1. Was the cluster installed via IPI or UPI?
2. What invoked the installer to create the cluster?
It will also allow us to determine some new information:
1. Regardless of installation strategy, what invoked the installer to
create the manifests?
2. Was the version of …

Bug 1797806: asset/manifests: add new installation config map
