- cmd/openshift-install/create.go
* [Bug 1796627: cmd/openshift-install/create: add env var to preserve bootstrap](https://github.com/openshift/installer/pull/2935)
* [cmd/openshift-install: shift timeouts from api to bootstrap ](https://github.com/openshift/installer/pull/3005)
* ~[Add gather bootstrap for vsphere](https://github.com/openshift/installer/pull/2912)~
/cc @LorbusChris 
These should improve stability and help with debugging issues until the next branch rebase
> [fcos] backport several fixes from master

- docs/user/azure/install_upi.md
- upi/azure/01_vnet.json
- upi/azure/02_storage.json
- upi/azure/03_infra.json
- upi/azure/04_bootstrap.json
- upi/azure/05_masters.json
- upi/azure/06_workers.json
- upi/azure/setup-manifests.py
The previous version of Azure UPI provided a script called `setup-manifests.py` which was mandatory for the deployment and required editing the generated manifest files.
This PR removes the need of that script, making the primary workflow rely on the generated Infra ID and resource group names, while still providing the script as an option in case of a different resource group name and/or base resource names are desired.
This was also desired by the docs team.
> Remove the need for helper Python script in Azure UPI

- images/installer/Dockerfile.upi.ci
Adds the `az` (Azure CLI) dependency to the Dockerfile used by CI in UPI tests.
Based of the suggested installation method for yum-based distros here: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-yum?view=azure-cli-latest
> Add Azure CLI as a dependency in UPI CI image

- pkg/asset/cluster/cluster.go
- pkg/asset/installconfig/platformcredscheck.go
- pkg/asset/installconfig/platformpermscheck.go
Separates the permissions check logic from `PlatformCredsCheck` and creates a similar `PlatformPermsCheck`. While `PlatformCredsCheck` checks whether credentials can authenticate to a platform, the new `PlatformPermsCheck` ensures that an account has the necessary permissions to create a cluster. `PlatformPermsCheck` is only needed when a cluster is being created and is currently only implemented for AWS.
This fixes BZ-1796347 where UPI calls to create manifest were failing due to insufficient permissions.
> Bug 1796347: Move permissions check to cluster asset

- pkg/terraform/gather/azure/ip.go
The terraform variables are named slightly differently in dual-stack/ipv6 clusters, but the code to run must-gather wasn't updated to match.
Fixes #3026
> Bug 1801863: Azure: fix must-gather in ipv6/dual-stack clusters

- docs/user/openstack/README.md
- docs/user/openstack/customization.md
- docs/user/openstack/install_upi.md
- upi/openstack/README.md
Detail a working Ansible UPI workflow in the Openshift Openstack user documentation.
I have changed the order of the steps in order to group all the preparation work at the beginning. That way, the user can then run all playbooks in sequence, without having to go back-and-forth between Ansible and local editing.
Implements OSASINFRA-1108
> Bug 1802035: openstack UPI: Document Ansible

- Gopkg.lock
- Gopkg.toml
- vendor/gopkg.in/AlecAivazis/survey.v1/multiselect.go
- vendor/gopkg.in/AlecAivazis/survey.v1/select.go
The survey library incorrectly stated users should use "space" to make a selection rather than "enter." This vendors in a new patch to fix this. The commit was created by bumping the survey version in Gopkg.toml and running dep ensure.
> Bug 1773910: Vendor survey to fix typo

- data/data/rhcos-amd64.json
- data/data/rhcos.json
This bump brings in the change to the default kernel cmdline to use
`ip=dhcp,dhcp6`, which is required for proper bootstrapping of RHCOS
in an IPv6 environment.  (See BZ#1793591)
This also brings in the RHEL 8.1.1 content and a fix for properly
generating GCP images (coreos/coreos-assembler#1088).
[0] https://bugzilla.redhat.com/show_bug.cgi?id=1793591
Signed-off-by: Micah Abbott <miabbott@redhat.com>
> Bug 1793591:  use `ip=dhcp,dhcp6` by default on kernel command line 

- docs/user/customization.md
- docs/user/metal/customization_ipi.md
- docs/user/metal/install_ipi.md
The platform now has a bunch of optional possible customizations, this
expands the documentation to follow the other platforms by including a
customization.md that details each of the options and why you might want
to use them.
> baremetal: expand baremetal IPI docs to include customizations

- pkg/asset/installconfig/openstack/openstack.go
- pkg/types/openstack/validation/platform.go
- pkg/types/openstack/validation/platform_test.go
Currently if we are looking for extensions for Neutron or try to list
services, it might happen, that underlying OpenStack cloud doesn't
support listing either extension or services. This patch is fixing it,
and assumption is, that trunk support is disabled in a case of
inability of listing Neutron extensions, and/or octavia support is
disabled in case of inability of listing services, instead of aborting
installation.
> Bug 1791318: Don't fail on unavailable features on OpenStack.

- Gopkg.lock
- Gopkg.toml
- pkg/asset/installconfig/aws/permissions.go
- pkg/asset/installconfig/platformcredscheck.go
- vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1/credentialsrequest_types.go
- vendor/github.com/openshift/cloud-credential-operator/pkg/aws/utils.go
manually revendor github.com/openshift/cloud-credential-oeprator with the branch constraint of 'release-4.3' then:
`dep ensure -update github.com/openshift/cloud-credential-operator`
cherry pick b78bc858e98dad87429257414ddac5355bca1e77 from master
> [release-4.3] Bug 1757244: use region info when simulating permissions

- images/openstack/Dockerfile.ci
Building OpenStack CI image started failing because it cannot install
awscli package from the repositories.
Let's follow the instruction from AWS rather than installing via yum:
https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html
> Bug 1803174: OpenStack CI Install awscli from zip

- docs/user/azure/install_upi.md
- upi/azure/04_bootstrap.json
Adds support to accessing the bootstrap node through SSH in Azure UPI, and remove it at the bootstrap cleanup steps.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1802820
> Bug 1802820: SSH to bootstrap node in Azure UPI

- cmd/openshift-install/gather.go
This change clears up the error message displayed when gather bootstrap
fails due to not having the necessary private keys loaded into the
ssh-agent or specified with the --key parameter. In addition, this
error will now only be displayed when the ssh error is due to an
authentication failure.
> Bug 1791375: gather: only show ssh-agent error when auth failed

- data/data/rhcos-amd64.json
- data/data/rhcos.json
This reverts commit 5654e02cd044d10afe648c8b35d7fccfe9a6eaf7.
Seeing [reports via Slack](https://coreos.slack.com/archives/C68TNFWA2/p1581948277060100) that networking is not coming up properly on masters.  This is preventing bare metal installs from completing successfully.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1803926
**NOTE**: This is not a fix for the issue but a return to a previously working state for ipv4 usage on bare metal.
> Bug 1804284: Revert "RHCOS: bump to 44.81.202002071430-0"

- data/data/ovirt/template/main.tf
Use the ovirt_template_cpu variable in the template resource creation.
> Bug 1795625: ovirt's worker template is created with 1 CPU

- images/baremetal/OWNERS
- pkg/asset/ignition/bootstrap/baremetal/OWNERS
images/baremetal and ignition/bootstrap/baremetal directories are
missing OWNERS files
> baremetal: add OWNERS to missing directories

- data/data/bootstrap/files/usr/local/bin/approve-csr.sh
- data/data/bootstrap/files/usr/local/bin/installer-gather.sh
- data/data/bootstrap/files/usr/local/bin/report-progress.sh
- data/data/bootstrap/gcp/files/usr/local/bin/report-progress.sh
- docs/user/troubleshooting.md
--config has been deprecated
Resolves warning message in log files:
Flag --config has been deprecated, use --kubeconfig instead
> Replace --config with --kubeconfig for `oc` command

- data/data/bootstrap/files/usr/local/bin/installer-gather.sh
This change updates the installer-gather.sh script to work correctly
with ipv6 addresses. It wraps the master ip addresses in square
brackets for all evocations of the scp command. This behavior is
backward compatible with ipv4 and so it now works with both.
> Bug 1803321: gather: installer-gather.sh to work with ipv6 addresses

- data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
- pkg/asset/ignition/bootstrap/baremetal/template.go
- pkg/asset/ignition/bootstrap/baremetal/template_test.go
Note: This is solving a similar problem for baremetal as
https://github.com/openshift/machine-config-operator/pull/1421 did for MCO.
The bootstrap can now co-exist with machine-api being online. That
means there could be an instance of Ironic, dnsmasq, etc running in
both the cluster and the bootstrap. This causes problems, as it's not
deterministic which dnsmasq instance the worker provisioned by the
machine-api will use. If it uses the bootstrap, then the worker will not
come online.
This is causing a percentage of baremetal installs to fail, with the
worker being offline, ingress and other operators never come up.
This change blocks dhcp requests from anything but control plane hosts,
using iptables. DHCPv6 relies on DUID's instead which makes things more
complicated to use dnsmasq's …
> Bug 1800746: baremetal: only respond to dhcp for control plane mac's 

- data/data/bootstrap/files/etc/motd
Catching up with d1ec85a5cc (#2234).
> data/bootstrap/files/etc/motd: Mention release-image.service

- docs/user/metal/customization_ipi.md
- docs/user/metal/install_ipi.md
Provide a table describing all of the configuration parameters for IPI
deployments on bare metal. Include a more verbose description of the
libvirtURI parameter and the context in which specifying it is
useful. Include examples of BMC address values.
> document bare metal ipi configuration parameters

- docs/user/metal/install_ipi.md
When starting the static pods on a host, we determine the correct
address to use by comparing its subnet with the VIP subnet. If the
external address assigned by DHCP is in a different subnet from the
VIPs then we can't determine which address to use and deployment
will fail. This change makes the requirement for addresses to be in
the same subnet explicit.
> Baremetal: Be explicit that addresses must be in same subnet

- Gopkg.lock
- Gopkg.toml
- pkg/asset/installconfig/aws/permissions.go
- pkg/asset/installconfig/platformcredscheck.go
- vendor/github.com/openshift/cloud-credential-operator/pkg/aws/utils.go
manually revendor github.com/openshift/cloud-credential-oeprator with the branch constraint of 'release-4.2' then:
dep ensure -update github.com/openshift/cloud-credential-operator
cherry pick b78bc85 from master. not a clean backport, needed manual fixups.
> [release-4.2] Bug 1803221: use region info when simulating permissions

- upi/azure/06_workers.json
Minor fix: we don't need to manually associate workers to the ingress load balancer since they register themselves automatically. This change also allows us to create workers before the bootstrap process finishes.
> Azure UPI: no need to manually associate workers with LB

- pkg/asset/installconfig/ovirt/config.go
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1804228
> Bug 1804228: ovirt-config.yaml not getting generated by openshift-install

- data/data/rhcos-amd64.json
- data/data/rhcos.json
```
./hack/update-rhcos-bootimage.py https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.4/44.81.202002211631-0/x86_64/meta.json amd64
```
This includes cri-o 1.17, as well as OVA fixes for VMWare.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1779421
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1804413
```
$ ./differ.py --first-endpoint art --first-version 44.81.202001241431.0 --second-endpoint art --second-version 44.81.202002211631-0
{
"sources": {
"44.81.202001241431.0": "https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.4/44.81.202001241431.0/x86_64/commitmeta.json",
"44.81.202002211631-0": "https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.4/44.81.202002211631-0/x86_64/commit …
```
> Bug 1779421: Bump RHCOS to 44.81.202002211631-0

- data/data/rhcos-amd64.json
- data/data/rhcos.json
Fixes a kubelet issue setting the wrong cgroup memory limit.
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1802687
> Bug 1806571: bump rhcos for kubelet fix

- pkg/tfvars/openstack/bootstrap_ignition.go
Now we return "err" from the previous call, but instead we should return "res.Err".
> Return the correct error after uploading OpenStack image

- docs/user/zvm/install_upi.md
Small issue in a hyphen missing, without it the command fails and the initramfs file can not be punched to the virtual reader.
Signed-off-by: Pedro Ibáñez <pedro@redhat.com>
> hyphen missing in a command to punch the initramfs into the virtual reader

- pkg/asset/installconfig/aws/session.go
By default the retries was per aws service [1]. terraform has the default retry count for 25 [2] so we can probably just match that.
[1]: https://github.com/aws/aws-sdk-go/blob/172af2f58676e3d2cc733bc01f229fa4a27d6ba4/aws/config.go#L89-L92
[2]: https://github.com/terraform-providers/terraform-provider-aws/blob/4875ae5fef0990f4a7e3768c81fcc732b90e0f13/aws/provider.go#L68-L72
/cc @wking 
/cc @jstuever @patrickdillon
> Bug 1779312: pkg/asset/installconfig/aws/session.go: bump the retries to 25 for aws sdk

- pkg/asset/ignition/bootstrap/bootstrap.go
This fixes an issue in Ignition Spec v3 where contradictory and/or duplicate entries
in the Storage.Files array are not allowed.
Specifically, in order to solve openshift/okd#37,
`data/data/bootstrap/gcp/files/usr/local/bin/report-progress.sh` will
now replace `data/data/bootstrap/files/usr/local/bin/report-progress.sh`
instead of being appended.
It also solves openshift/okd#63 by ensuring
`99_openshift-machineconfig_99-{master,worker]-ssh.yaml` aren't added
to the generated Ignition config twice.
I'm sure there is a more elegant way to do this - feedback is welcome!
Fixes: openshift/okd#37
Fixes: openshift/okd#63
> bootstrap: replace Ignition files if they already exist instead of appending them

- pkg/asset/manifests/additionaltrustbundleconfig.go
When using `additionalTrustBundle` accept v1 certificates and non-CA
certificates. In place of the drop warn user that the
certificate provided is either v1 or a non-CA certificate.
Fixes https://github.com/openshift/installer/issues/2484
> Bug 1807103: additionalTrustBundle IsCA check to warn instead of drop

- data/data/rhcos-amd64.json
- data/data/rhcos.json
backport https://github.com/openshift/installer/pull/3173 to 4.4
> [release-4.4] Bug 1806576: bump rhcos for crio fix

- docs/user/metal/customization_ipi.md
The other sections show an example that places the configuration
parameter in the right part of the structure in the YAML document. Add
a similar example for the libvirtURI.
> add a more complete example of using libvirturi in metal docs

- docs/user/openstack/customization.md
- pkg/asset/rhcos/image.go
- pkg/types/openstack/platform.go
This PR adds `clusterOSImage` parameter to the install config, that allows to override default OS image location for users.
> OpenStack: allow to overwrite default os image in the install config

- data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
It is possible to use localhost for the short term to get unstuck and correctly predict "correct" values in individual render commands. This is a temporary workaround to ship 4.4.
The bootkube script should be aware of the 'correct' ipv6 address to configuring rendering of multiple components.
> bug 1807169: use localhost for bootstrap IP until bootkube is fixed

- docs/user/openstack/install_upi.md
- upi/openstack/04_control-plane.yaml
- upi/openstack/common.yaml
- upi/openstack/down-04_control-plane.yaml
This places the Control Plane servers in a Server Group that enforces
"soft anti-affinity" policy.
"Soft anti-affinity" will cause Nova to create VMs on separate hosts, if
that is possible.
Implements OSASINFRA-1015
> openstack UPI: soft-anti-affinity policy for CP

- data/data/openstack/main.tf
- data/data/openstack/variables-openstack.tf
- go.mod
- go.sum
- pkg/tfvars/openstack/openstack.go
- pkg/tfvars/openstack/rhcos_image.go
- vendor/github.com/gophercloud/gophercloud/.zuul.yaml
- vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
- vendor/github.com/gophercloud/gophercloud/errors.go
- vendor/github.com/gophercloud/gophercloud/go.mod
- vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/ports/requests.go
- vendor/github.com/gophercloud/gophercloud/openstack/baremetalintrospection/v1/introspection/results.go
- vendor/github.com/gophercloud/gophercloud/openstack/client.go
- vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/imageimport/doc.go
- vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/imageimport/requests.go
- vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/imageimport/results.go
- vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/imageimport/urls.go
- vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/requests.go
- vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/requests.go
- vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas/vips/results.go
- vendor/modules.txt
Now we use legacy image uploading that doesn't support image conversion. It leads to the fact that we upload qcow2 images to Ceph backend, which doesn't support this format:
https://access.redhat.com/solutions/2434691
By using the Image Import mechanism we make sure that all uploaded images will be automatically converted to Raw for Ceph (and only for Ceph) backends.
If the image import mechanism is not available we fallback to the legacy uploading.
> Bug 1806143: OpenStack: start using image import when possible

- pkg/asset/ignition/bootstrap/bootstrap.go
- pkg/asset/ignition/node.go
- pkg/asset/machines/master_test.go
- pkg/asset/machines/worker_test.go
- pkg/tfvars/openstack/bootstrap_ignition.go
Ignition v3 would merge file contents by default. Installer should
ensure "overwrite: true" is set in generated Ignition config to avoid
that.
This also reset appending information to motd, as on FCOS bootstrap node this makes motd being duplicated
> [FCOS] pkg: always overwrite files created

- go.mod
- go.sum
- vendor/github.com/hashicorp/terraform/command/meta_config.go
- vendor/modules.txt
Steps to create this commit:
1. update go.mod with new version of openshift/hashicorp-terraform
2. go mod tidy
3. go mod vendor
Fixes: #1839
> Bug 1767066: Vendor terraform update to fix symlink bug

- docs/user/vsphere/install_upi.md
The IP_ADDR should be IPADDR, otherwise NM fails thinking there
is no IP set.
Signed-off-by: Yu Qi Zhang <jerzhang@redhat.com>
> docs/vsphere: fix static ip reference

- go.mod
- go.sum
- pkg/tfvars/internal/cache/cache.go
- vendor/github.com/h2non/filetype/LICENSE
- vendor/github.com/h2non/filetype/matchers/application.go
- vendor/github.com/h2non/filetype/matchers/archive.go
- vendor/github.com/h2non/filetype/matchers/audio.go
- vendor/github.com/h2non/filetype/matchers/document.go
- vendor/github.com/h2non/filetype/matchers/font.go
- vendor/github.com/h2non/filetype/matchers/image.go
- vendor/github.com/h2non/filetype/matchers/isobmff/isobmff.go
- vendor/github.com/h2non/filetype/matchers/matchers.go
- vendor/github.com/h2non/filetype/matchers/video.go
- vendor/github.com/h2non/filetype/types/defaults.go
- vendor/github.com/h2non/filetype/types/mime.go
- vendor/github.com/h2non/filetype/types/split.go
- vendor/github.com/h2non/filetype/types/type.go
- vendor/github.com/h2non/filetype/types/types.go
- vendor/modules.txt
Uses `github.com/h2non/filetype` for MIME type checking
and `github.com/ulikunitz/xz` to uncompress artifacts, 
identified by `application/x-xz`
> Support xz-encoded images

- pkg/asset/ignition/bootstrap/bootstrap.go
Generated files have been mistakenly appended due to overwrite refactoring of `ignition.FileFromBytes`. This breaks GCP install, it gets `report-progress.sh` included twice and bootstrap Ignition is rendered with duplicate files.
Verified that it fixes bootstrap startup on GCP
> [fcos] bootstrap: check files for duplicates before appending

- pkg/destroy/openstack/openstack.go
There's no need to use Errorf when there is nothing to format. In this
case, let's use logger.Error() instead.
> Fix invocation of log.Errorf

- pkg/destroy/aws/aws.go
- pkg/destroy/aws/errortracker.go
This change makes it so that errors encountered while attempting to
delete objects from AWS during destroy cluster will be logged as
WARNING level once every 5 minutes (per object). Otherwise they will
continue to be logged as DEBUG as encountered.
This change also modifies the logging of instances "Terminating" to DEBUG
while "Terminated" becomes INFO.
> Bug 1713336: aws destroy: show warnings when things fail to delete after 5 minutes.

- data/data/aws/bootstrap/main.tf
- data/data/aws/iam/main.tf
- data/data/aws/master/main.tf
This change queries the default partition from aws and uses it when
deploying IAM role policies. This will enable provisioning of clusters
in partitions other than aws, which was previously hard coded.
> aws: update the IAM role policy to remove hard coded partition ID

- data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
When I was looking into which ports to block for DHCPv6, I misunderstood
the following:
DHCPv6 uses UDP port number 546 for clients and port number 547 for servers.
RFC8415 says:
Clients listen for DHCP messages on UDP port 546.  Servers and relay
agents listen for DHCP messages on UDP port 547.
We need to add 547/udp to block any incoming requests.
4.4 BZ 1809695
> Bug 1809691: baremetal: block 547/udp for DHCPv6 as well

- docs/user/openstack/install_upi.md
- upi/openstack/requirements.txt
The use of pip is not supported.
> Bug 1810196: Use RPM for UPI dependencies

- docs/user/openstack/customization.md
- pkg/asset/rhcos/image.go
- pkg/types/openstack/platform.go
This PR adds `clusterOSImage` parameter to the install config, that allows to override default OS image location for users.
> [release-4.3] Bug 1808482: OpenStack: allow to overwrite default os image in the install config

- docs/user/metal/install_ipi.md
The doc currently "strongly reccomends" static DHCP reservations in
machineCIDR. This updates the doc to be explicit that IP's must be
stable.
> baremetal: update docs to indicate stable IP's are required

- pkg/asset/cluster/cluster.go
- pkg/asset/installconfig/platformcredscheck.go
- pkg/asset/installconfig/platformpermscheck.go
This is a manual cherry pick of 6eec6240298276d5788d74bf6bf394588fea012a. Major differences:
-  there is no ovirt type in the new `PlatformPermsCheck`
- ~~#3056 has not been backported so the signature for `ValidateCreds` does not have an arg for region~~
Separates the permissions check logic from PlatformCredsCheck and creates a similar PlatformPermsCheck. While PlatformCredsCheck checks whether credentials can authenticate to a platform, the new PlatformPermsCheck ensures that an account has the necessary permissions to create a cluster. PlatformPermsCheck is only needed when a cluster is being created and is currently only implemented for AWS.
This fixes BZ-1801446 where UPI calls to create manifest were failing due to insufficient permissions.
> Bug 1801446: Move permissions check to cluster asset

- pkg/asset/installconfig/clustername.go
- pkg/types/azure/validation/platform.go
- pkg/types/gcp/validation/platform.go
- pkg/types/validation/installconfig.go
- pkg/types/validation/installconfig_test.go
- pkg/validate/validate.go
Prior to this change, GCP and Azure did not allow periods in the cluster
names because that would violate their API naming conventions. However,
newer versions of the installer create cloud assets based on the InfraID,
where all periods are now translated to dashes.
This change modifies the verification to allow periods. As a result,
users can now create clusters with names such as "my.prod". They must
otherwise comply with RFC1035 `[a-z]([-a-z0-9]*[a-z0-9])?`.
Because the InfraID adds several random characters to the end of the
cluster name, it will always satisfy the Azure minimum length requirement.
> Bug 1809820: gcp/platform: Allow periods in the cluster name.

- pkg/tfvars/openstack/bootstrap_ignition.go
Nova has a hard limit of 64KB [1] for user data when booting VMs. This
was not a problem previously when everything that went into the user
data was under our control and small enough. With the recent addition
of self-signed certificate feature, the ignition size now depends on
the size of the CA cert file the user passes, and it may cause it to
exceed nova limit if the file is too large.
This commit checks the size of the rendered file as it would be passed
to nova user data and fails early with an appropriate message if it
exceeds the 64KB limit.
[1] https://docs.openstack.org/nova/latest/user/metadata.html#user-data
Fixes #3177
> OpenStack: Fail early when boostrap ignition shim is to big

- data/data/bootstrap/files/usr/local/bin/installer-gather.sh
Today if you extract a bootstrap gather tarball, you end up with all the
files dumped into the current working directory. Ideally these should
all be encapsulated in their own directory so as not to make a mess.
Before:
```
$ tar -xzvf ../log-bundle-20200305162726.tar.gz
./
./failed-units.txt
./unit-status/
./unit-status/NetworkManager-wait-online.service.txt
[...]
```
After:
```
$ tar -xzvf log-bundle-20200305162329.tar.gz
log-bundle-20200305162329/
log-bundle-20200305162329/failed-units.txt
log-bundle-20200305162329/unit-status/
log-bundle-20200305162329/unit-status/NetworkManager-wait-online.service.txt
[...]
```
I'm not sure if this breaks any automation anywhere that relies on this structure, but it's really bad form to pollute the cwd like this when extracting a tarball.
> gather: ensure gather data is all in one directory

- data/data/rhcos-amd64.json
- data/data/rhcos.json
```
./hack/update-rhcos-bootimage.py https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.4/44.81.202003062006-0/x86_64/meta.json amd64
```
Includes fixes for the following bugs:
- https://bugzilla.redhat.com/show_bug.cgi?id=1803112
- https://bugzilla.redhat.com/show_bug.cgi?id=1803926
- https://bugzilla.redhat.com/show_bug.cgi?id=1804772
- https://bugzilla.redhat.com/show_bug.cgi?id=1806588
Differ diff:
```
"diff": {
"conmon": {
"44.81.202002241126-0": "conmon-2.0.9-1.rhaos4.4.el8.x86_64",
"44.81.202003062006-0": "conmon-2.0.11-1.rhaos4.4.el8.x86_64"
},
"dracut": {
"44.81.202002241126-0": "dracut-049-64.git20200123.el8.x86_64",
"44.81.202003062006-0": "dracut-049-70.git20200228.el8.x86_64"
},
"dracut-network": {
"44.81.202002241126-0": …
```
> data/data/rhcos.json: Update bootimage to 44.81.202003062006-0

- data/data/manifests/openshift/cloud-creds-secret.yaml.template
- pkg/asset/installconfig/ovirt/config.go
- pkg/asset/installconfig/ovirt/credentials.go
- pkg/asset/manifests/openshift.go
- pkg/asset/manifests/template.go
Some components of the cluster are interacting with oVirt API but don't
have way to verify it's certificate.
To support that the installer will ask for the CA bundle, and it
will be kept inside ovirt-credentials secret.
Once in ovirt-credentials secret it should be mounted into a container's
/etc/ssl/certs path. This way every https client will have the CA cert in
the trusted pool.
Related: https://github.com/openshift/cloud-credential-operator/pull/164
> Bug 1794313: Some cluster operators fail to come up because RHV CA is not trusted by a pod

- pkg/asset/installconfig/clustername.go
- pkg/types/gcp/validation/platform.go
- pkg/types/validation/installconfig.go
- pkg/types/validation/installconfig_test.go
- pkg/validate/validate.go
This is a manual cherry-pick of #3239
> [Release 4.3] Bug 1811154: validation: Allow periods in gcp and azure cluster names.

- upi/openstack/04_control-plane.yaml
The Ansible version that ships with RHEL does not have knowledge of Nova
microversions from 2.15; they will block the 'soft-anti-affinity'
policy.
This change replaces the use of the os_server_group module with a raw
HTTP call to the Nova API, in order to specify microversion 2.15, the
first compatible with soft-anti-affinity.
> Bug 1810916: openstack UPI: Adapt the script to older Ansible

- data/data/aws/main.tf
- data/data/aws/route53/base.tf
- data/data/aws/route53/variables.tf
- data/data/azure/dns/dns.tf
- data/data/azure/dns/variables.tf
- data/data/azure/main.tf
- data/data/bootstrap/baremetal/README.md
- data/data/bootstrap/files/usr/local/bin/installer-gather.sh
- data/data/gcp/dns/base.tf
- data/data/gcp/dns/variables.tf
- data/data/gcp/main.tf
- data/data/libvirt/main.tf
I'm not completely sure where all the DNS bits are, but this is my best starting guess.
Starting in 4.4, etcd does not rely on DNS entries.
> etcd: remove etcd DNS entries because etcd no longer uses DNS

- data/data/rhcos-amd64.json
- data/data/rhcos.json
This pulls bumps the RHCOS boot image to include signed RPMs for 4.4
as well as fixes for IPv6 support and handling of kernel arguments.
> Bug 1803926: bump RHCOS boot image to 44.81.202003110027-0

- data/data/manifests/bootkube/cvo-overrides.yaml.template
Like d7fb12c07a (#2940), but for 4.5 (no that release-4.4 is no longer being fast-forwarded to track master).
> data/manifests/bootkube/cvo-overrides: Bump default to stable-4.5

- pkg/tfvars/openstack/openstack.go
Now we parse the service catalog manually, but it is better to reuse the existing function from gophercloud, that does the same.
> OpenStack: reuse the existing function to get glance public URL

- data/data/rhcos.json
This bumps the RHCOS boot images to include fixes for IPv6 support
and handling of kernel arguments.
> Bug 1812599: bump RHCOS boot images to 43.81.202003111353.0

- docs/user/gcp/install_upi.md
- upi/gcp/02_dns.py
- upi/gcp/02_lb_ext.py
- upi/gcp/03_firewall.py
- upi/gcp/03_iam.py
- upi/gcp/04_bootstrap.py
Prior to this change, users needed to edit the gcp upi python templates
in order to provision an cluster using a shared VPC. This was prone to
user error.
This change breaks up the templates so that only the yaml files need to
be modified, thus greatly simplifying the process. All of the resources
that would be provisioned in the host project are now in their own
python templates (01_vpc.py, 02_dns.py, and 03_firewall.py). These
resources can be removed from the yaml files to be run against the
service project and placed into yaml files to be run against the host
project instead.
requires openshift/release#7540, openshift/release#7571
> gcp upi: split templates to simplify shared vpc workflow.

- docs/user/openstack/install_upi.md
This adds documentation on how to use UPI with self-signed certificates.
> Bug 1809921: Openstack UPI: Document use with Self-signed cert

- images/baremetal/Dockerfile.ci
These images are failing to build internally for OSE due to missing the
nss wrapper package.
The underyling problem we are seeing when trying to use the
baremetal-installer image in CI to ssh to the packet server is that
user ID's are generated dynamically. This results in errors like this
when attempting to use SSH:
No user exists for uid 102400000
The way most CI containers work around this is to echo a valid user to
/etc/passwd, as /etc/passwd is left writeable. The base images for
OpenShift now do this by default, so we can remove nss entirely.
> images/baremetal: remove nss package as it's no longer needed 

- images/baremetal/Dockerfile.ci
We'll be using baremetal-installer as the container we setup packet
for metal IPI CI. We need to use SSH, but it's broken without having a
valid user in /etc/passwd.
This change is required for our CI infrastructure to use SSH correctly
until we have completely moved CI to 4.x infrastructure where
/etc/passwd becomes dynamic.
This was restored to the tests container[1], and is now also being added
to the baremetal/installer container.
[1] https://github.com/openshift/origin/pull/24690
> images/baremetal: make /etc/passwd writeable

- go.mod
- go.sum
- pkg/asset/installconfig/aws/permissions.go
- vendor/github.com/openshift/cloud-credential-operator/pkg/aws/client.go
- vendor/modules.txt
previously the credential checker created an independent session, therefore all the configuration
done by installer like increasing MaxRetries etc were skipped.
> permissions.go: configure crendential check with installer session

- go.mod
- go.sum
- vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/network/resource_arm_loadbalancer.go
- vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/network/resource_arm_virtual_network.go
- vendor/modules.txt
When a subnet uses address_prefixes, address_prefix is null in the virtual network resource. Add address_prefixes to virtual network resource and allow null for address_prefix. Don't assume IPv4 for private_ip_address on load balancer resource.
https://bugzilla.redhat.com/show_bug.cgi?id=1808973
> bug 1805251: Master azure terraform address prefixes

- docs/user/gcp/install_upi.md
- upi/gcp/01_vpc.py
- upi/gcp/02_lb_ext.py
- upi/gcp/02_lb_int.py
- upi/gcp/03_firewall.py
This change adds 02_lb_int.py template to the workflow to enable
internal load balancers. The cluster will begin communicating to the api
and mcs through the internal load balancers. The external load balancer
can optionally be disabled for private clusters.
This change also updates the documentation to use the $(command) syntax
to be in line with the other platforms.
In addition, the variable definitions were all moved to immediately
after the associated resources were created. This will help make clear
where their origins are.
Depends on: #2574, openshift/release#7571
> gcp upi: enable internal load balancers

- upi/openstack/04_control-plane.yaml
Fix the Ansible playbook such as the server group ID is collected and
actually used to create the servers.
> Bug 1810916: openstack UPI: servers in group

- data/data/aws/bootstrap/main.tf
- data/data/aws/bootstrap/variables.tf
- data/data/aws/main.tf
- data/data/aws/master/main.tf
- data/data/aws/master/variables.tf
- data/data/aws/variables-aws.tf
- docs/user/aws/customization.md
- go.mod
- go.sum
- pkg/asset/cluster/tfvars.go
- pkg/asset/machines/aws/machines.go
- pkg/tfvars/aws/aws.go
- pkg/types/aws/machinepool.go
- vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machinehealthcheck_types.go
- vendor/modules.txt
- vendor/sigs.k8s.io/cluster-api-provider-aws/pkg/apis/awsproviderconfig/v1beta1/awsmachineproviderconfig_types.go
- vendor/sigs.k8s.io/cluster-api-provider-aws/pkg/apis/awsproviderconfig/v1beta1/zz_generated.deepcopy.go
xref: https://issues.redhat.com/browse/CORS-1352
depends on https://github.com/openshift/cluster-api-provider-aws/pull/303
Amazon supports using [encrypted root EBS volumes][1]. So instead of copying the AMI and encrypting in the process we can use the encypted EBS volumes instead which saves us making the AMI copy during install.
The change also allows the user to provide KMS key to the terraform instead of the default KMS key.
Using this change the instance boots with public RHCOS AMI, and the EBS volume is encrypted with default KMS key for the account and region.
```console
[4:42:15] ➜  installer git:(ami_no_copy) ✗ AWS_PROFILE=openshift-dev aws ec2 describe-volumes --region ca-central-1 --volume-ids vol-09ceb58bc9ac93602
{
"Volumes": [
{
"Attachments": [
{
"AttachTime": …
```
> AWS: replace aws copy for encryption with encrypted EBS volumes

- docs/user/openstack/install_upi.md
This adds documentation on how to use UPI with self-signed certificates.
Manual cherry-pick of #3290 because of conflicts in `docs/user/openstack/install_upi.md`.
> Bug 1813822: Openstack UPI: Document use with Self-signed cert

- docs/user/customization.md
Since f09413d1f9f, `clusterNetworks` is deprecated in favor of
`clusterNetwork`.
> Docs: stop using deprecated parameters

- data/data/aws/main.tf
- data/data/aws/route53/base.tf
- data/data/aws/route53/variables.tf
- data/data/azure/dns/dns.tf
- data/data/azure/dns/variables.tf
- data/data/azure/main.tf
- data/data/bootstrap/baremetal/README.md
- data/data/bootstrap/files/usr/local/bin/installer-gather.sh
- data/data/gcp/dns/base.tf
- data/data/gcp/dns/variables.tf
- data/data/gcp/main.tf
- data/data/libvirt/main.tf
This is a manual cherry pick of https://github.com/openshift/installer/pull/3265
Starting in 4.4, etcd does not rely on DNS entries.
> [release 4.4] Bug 1813004: etcd: remove etcd DNS entries because etcd no longer uses DNS

- data/data/bootstrap/vsphere/OWNERS
- data/data/bootstrap/vsphere/files/etc/dhcp/dhclient.conf.template
- pkg/asset/ignition/bootstrap/bootstrap.go
- pkg/asset/ignition/bootstrap/vsphere/OWNERS
- pkg/asset/ignition/bootstrap/vsphere/template.go
This change will set the bootstrap node to use local DNS servers when users provide VIPs in the VSphere install config. Self-hosted DNS is currently a requirement for installer-provisioned clusters, but is not a hard requirement for UPI.
I **assume** that having an empty dhclient.conf is fine in the case of UPI. I did not see a way of conditionally creating the file--only of conditionally changing the contents. I am curious if anyone can suggest an alternative approach.
> VSphere: populate bootstrap dhclient.conf if user provides VIPs.

- docs/user/aws/customization.md
- pkg/asset/machines/aws/machines.go
- pkg/asset/machines/aws/machinesets.go
- pkg/asset/machines/master.go
- pkg/asset/machines/worker.go
- pkg/types/aws/machinepool.go
users can set AMI for the platform or defaultMachinePool or individual machine pool, and the AMI used is based on increasing order of priority of the list mentioned before.
/assign @sdodson 
/cc @derekwaynecarr
> aws: allow users to provide AMI for each machine pool

- pkg/terraform/exec/plugins/Gopkg.lock
- pkg/terraform/exec/plugins/Gopkg.toml
- pkg/terraform/exec/plugins/vendor/github.com/apparentlymart/go-cidr/cidr/cidr.go
- pkg/terraform/exec/plugins/vendor/github.com/apparentlymart/go-cidr/cidr/wrangling.go
- pkg/terraform/exec/plugins/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_loadbalancer.go
- pkg/terraform/exec/plugins/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_virtual_network.go
The azure subnet resource allows for multiple address prefixes using the
address_prefixes argument. The virtual network resource allows inline subnets,
but does not current support this argument. When the address_prefixes argument
is used, address_prefix will be null when terraform refreshes its state causing
terraform to panic. This code updates the virtual network resource to allow
address_prefixes to be used and for address_prefix to be null.
https://bugzilla.redhat.com/show_bug.cgi?id=1808969
> [release-4.4] Bug 1808969: azure - vendor update to support multiple prefixes

- docs/user/gcp/install_upi.md
- upi/gcp/04_bootstrap.py
Previously, the bootstrap host was being added to the first master
instance group. This causes an issue if the gcp cloud provider attempts
to create internal load balancers for the cluster because it ignores the
first master's instance groupd and tries to put it into a new instance
group. If there are workers that are in a different subnet, then the
cloud provider throws an error and never creates the ingress lbs.
This change creates an instance group for the bootstrap host, and
updates the doc to utilize it. It also removes the steps of adding and
removing the bootstrap host from the external target pools, as that is
not what we are doing with ipi.
> gcp upi: add bootstrap to instance group

- docs/user/metal/install_ipi.md
This was updated in baremetal-operator but not
on the installer documentation.
Signed-off-by: Yolanda Robla <yroblamo@redhat.com>
> Add documentation for virtualmedia

- data/data/manifests/openshift/cloud-creds-secret.yaml.template
- pkg/asset/installconfig/ovirt/config.go
- pkg/asset/manifests/openshift.go
- pkg/asset/manifests/template.go
Some components of the cluster are interacting with oVirt API but don't
have way to verify it's certificate.
To support that the installer will ask for the CA bundle, and it
will be kept inside ovirt-credentials secret.
Once in ovirt-credentials secret it should be mounted into a container's
/etc/ssl/certs path. This way every https client will have the CA cert in
the trusted pool.
Fixes https://github.com/openshift/okd/issues/106
Signed-off-by: Roy Golan <rgolan@redhat.com>
> [FCOS] ovirt: Ask for the CA pem content ovirt API

- data/data/azure/vnet/internal-lb.tf
- data/data/azure/vnet/public-lb.tf
- data/data/gcp/network/lb-private.tf
- data/data/gcp/network/lb-public.tf
In general we want shorter health check intervals to detect apiserver
failures faster. The current defaults are on the long side, and we
have already standardized ingress to use the minimum intervals possible.
Azure and AWS can be tuned to 5s intervals, so make them consistent.
GCP is more efficient and can be tuned to 1s, but that may increase
idle load on the API servers, so set the default to 2s with 3 checks
to keep it closer to Azure and AWS.
This is consistent with the direction we are moving for general platform
recommendations.
> data: Tune all cloud load balancers to have consistent intervals

- docs/user/openstack/customization.md
We deprecated 'region' option in 4.3, but our examples still have it.
> OpenStack: remove 'region' from the examples

- images/baremetal/Dockerfile.ci
For the baremetal platform, we need to know where the images are in
order to mirror them.  Especially for IPv6 environments where we may not
have outbound internet access to download the images.
Typically, we download the rhcos.json from the sha reported by
`openshift-install version` but this doesn't work in CI, where PR's are
always rebased on master (or their target branch) and the sha reported doesn't exist on GitHub.
This is a temporary workaround until the machine OS content is part of
the release image itself.
> images/baremetal: save rhcos.json in container image

- images/installer/Dockerfile.upi.ci
A vSphere IPI install requires that the installer host have the vCenter's CA certificates. This commit adds the CA certs to the UPI image's system trust in order to enable CI for IPI installs.
The vSphere IPI install step would then use this upi image.
Blocks openshift/release#7586
> Add vCenter CA to UPI CI image.

- pkg/destroy/openstack/openstack.go
When the cloud doesn't have support for trunk ports, we should not try
to delete them.
> Bug 1814593: OpenStack: Allow destroying cluster without trunk ports

- data/data/openstack/main.tf
- data/data/openstack/masters/main.tf
- data/data/openstack/masters/variables.tf
- data/data/openstack/variables-openstack.tf
- docs/user/openstack/README.md
- go.mod
- go.sum
- pkg/asset/machines/openstack/machines.go
- pkg/asset/machines/openstack/machinesets.go
- pkg/destroy/openstack/openstack.go
- pkg/destroy/openstack/register.go
- pkg/tfvars/openstack/openstack.go
- vendor/modules.txt
- vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/apis/openstackproviderconfig/v1alpha1/types.go
This places the Control Plane servers in a Server Group that enforces "soft anti-affinity" policy.
"Soft anti-affinity" will cause Nova to create VMs on separate hosts, if that is possible.
Implements OSASINFRA-1300
/cc pierreprinetti
> openstack: soft-anti-affinity policy for CP

- docs/user/openstack/install_upi.md
The UPI documentation recommends keeping the worker Machineset in case
the user wants to create compute machines via the machine API. However,
the Machineset won't work unless the `image` property is updated to the
user-defined value.
This change adds a recommendation to update the OS image in case the
user wants to use the installer-provisioned Machineset.
> Bug 1815133: osp UPI machineset OS image name

- images/installer/Dockerfile.upi.ci
Add the AWS CLI to the UPI image for use in the upi templates (which install the cli through pip) and the VSphere IPI template. These commands are the same as used by the OpenStack Dockerfile.
/test e2e-aws-upi
> Add AWS CLI to UPI image.

- images/baremetal/Dockerfile.ci
This a backport of PR #3301
We'll be using baremetal-installer as the container we setup packet
for metal IPI CI. We need to use SSH, but it's broken without having a
valid user in /etc/passwd.
This change is required for our CI infrastructure to use SSH correctly
until we have completely moved CI to 4.x infrastructure where
/etc/passwd becomes dynamic.
This was restored to the tests container[1], and is now also being added
to the baremetal/installer container.
[1] openshift/origin#24690
> Bug 1815551: images/baremetal: make /etc/passwd writeable and add SSH client

- pkg/asset/targets/targets.go
Now we generate terraform config and create resources for OpenStack first, and only then we create the metadata.json file.
In case the resources were not created because of an error, we get garbage in the system. And the installer cannot remove it because the metadata file has not been generated yet.
This commit creates the file before the generation of terraform config.
> Bug 1812950: generate metadata before tfvars

- pkg/asset/machines/openstack/machines.go
Now we create the server group in OpenStack Machines asset, but it is called twice: from Bootstrap Ignition Config and from Terraform Variables. It leads to the fact that we create two server groups
during installation.
This commit makes the server group creation idempotent.
> Bug 1816995: OpenStack: create server group only once

- docs/user/openstack/README.md
The documentation was not clear as to where the path for "cacert" was
relative to.
> openstack: Detail the clouds.yaml cacert option

- docs/dev/openstack/customization.md
- docs/user/openstack/customization.md
- pkg/tfvars/openstack/openstack.go
- pkg/types/openstack/platform.go
Now we support http(s) schemes only, but for disconnected installs it's very convenient to specify the local file path to the image file.
This commit adds "file" scheme support, so users can set the location as  "file:///path/to/image".
> OpenStack: support "file" scheme for custom os image urls

- data/data/manifests/bootkube/cvo-overrides.yaml.template
New OKD clusters should point updates to stable versions at https://origin-release.svc.ci.openshift.org/#4-stable
> [FCOS] cvo-overrides.yaml: point OKD releases to release-controller

- upi/vsphere/machine/ignition.tf
Internal connectivity tests expect nodes to be resolvable. On our CI
these are not, so we have to use IP addresses instead of generated
node names to make tests pass.
See test results in https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_installer/3367/pull-ci-openshift-installer-fcos-e2e-vsphere/600
> [fcos] vSphere UPI: use IPs as node names

- docs/user/openstack/install_upi.md
- docs/user/openstack/known-issues.md
Following objects are still present in the cluster, after deletion is
completed:
- Cinder volumes from PVs
- Swift container for image registry (bootstrap container is correctly
deleted)
/cc @mandre @MaysaMacedo
> Bug 1814651: os UPI known issues: stale resources

- docs/user/gcp/install_upi.md
This change adds direction in the GCP UPI install document about how to
install a cluster using a Shared VPC. Because the VPC, networks,
subnets, and dns zones are in a different project (the host project),
the installer has problems finding them while creating the Ignition
files. Furthermore, some changes are required to the cloud-provider in
order for the cluster to properly provision resources in the subnets. In
addition, it is assumed the service account in the service project will
likely not have sufficient permissions in the host project to perform
all of the required tasks.
Depends on: #2574, #3270, #3309
> GCP UPI: document how to install into a Shared VPC

- docs/user/gcp/install_upi.md
This change documents how to add custom tags to the bootstrap, master,
and worker nodes at install time. This will enable users with custom
firewall rules to use previously known tags to enable communications to
their cluster.
This PR depends on: #3309, #3278
> gcp upi: document how to tag the masters and workers

- pkg/destroy/aws/aws.go
…ror.
It appears in some situations, AWS may return a route53 hosted zone when
querying for tagged resources, despite the fact that the zone no longer
exists.
Update deprovision code to catch this error and skip route53 cleanup
when present.
> Bug 1817201: Fix intermittent deprovision loop on NoSuchHostedZone error

- pkg/types/baremetal/platform.go
- pkg/types/baremetal/validation/platform.go
- pkg/types/baremetal/validation/platform_test.go
This PR defines a new validation rule `urlexist` applied to the `BootstrapOSImage` and `ClusterOSImage` fields of `baremetal.Platform` structure, to ensure that the specified URL exists (without downloading the content).
The PR also contains the smallest refactoring step to allows a coherent validation approach for the mentioned fields.
Finally, the PR contains a proposal to improve the readability (and reduce the duplication and the chance of errors) of the related test code using the fluent builder pattern.
> baremetal: Validate os images exist

- upi/openstack/04_control-plane.yaml
Use the existing server group, if it exists with the target name.
Also convert the call from HTTP to openstackclient for consistency.
/cc @mandre @MaysaMacedo @adduarte
> Bug 1819320: os UPI Idempotent server group create

- docs/user/openstack/kuryr.md
Add information about the number of amphora VMs created, as
well as fixing the typo for CGO_ENABLED
Fix issue: https://github.com/openshift/installer/issues/2373
> Enhancements to Kuryr documentation

- docs/user/openstack/install_upi.md
* Normalise title hierarchy
* Incorporate Glance instructions into the flow
* TLS public certificates are not sensitive data
/cc @mandre @MaysaMacedo
> openstack UPI: Small documentation fixes

- cmd/openshift-install/create.go
- docs/user/troubleshooting.md
As of OpenShift 4.4.0, the `router-ca` configmap is deprecated, and the `default-ingress-cert` configmap should be used instead.
* `cmd/openshift-install/create.go` (`addRouterCAToClusterCA`): Replace use of `router-ca` with use of `default-ingress-cert`.  Return not-found errors to caller.
* `docs/user/troubleshooting.md`: Update references to "router-ca".
Thanks @stlaz for finding the issue!  https://github.com/openshift/cluster-ingress-operator/pull/377#issuecomment-606007260
> Use "default-ingress-cert", not "router-ca"

- pkg/tfvars/openstack/rhcos_image.go
Looks like image import is not configured well on our testing cloud, which leads to the uploading error.
We have to temporary disable image import in the installer until the cloud is fixed.
> OpenStack: Temporary disable image import

- data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
This allows someone installing OpenShift to slip in a ConfigMap that keeps cloud-credential-operator from ever starting up.
The process would look like:
openshift-install create manifests
create YAML for CCO Configmap for namespace/name: openshift-cloud-credential-operator/cloud-credential-operator-config
openshift-install create cluster
When the CCO render command sees the ConfigMap indicating that it should be disabled, it will not render the bootstrap Pod manifest, and the ConfigMap will make it into the cluster so the in-cluster CCO will also not attempt to run.
> pass the manifests-dir param to CCO render

- pkg/destroy/openstack/glance.go
Now if the function fails, we stop the installation immediately, but it's better to retry several times before finally stopping the installation.
> Bug 1816155: OpenStack: Add retries to DeleteGlanceImage

- data/data/gcp/main.tf
This opts us in to some of the features from
https://cloud.google.com/security/shielded-cloud/shielded-vm
Specifically with this, we get a vTPM device.
And what's nice about having a TPM device is that we can start
to optionally make use of TPM devices in OpenShift which
will then work on both bare metal *and* in GCP.
Closes: #2546
> gcp: Flag RHCOS with SECURE_BOOT and UEFI_COMPATIBLE

- upi/openstack/down-06_load-balancers.yaml
This commit fix an indentation on the UPI destroy playbook
for loadbalancers.
> Fix indentation on a UPI Playbook task

- pkg/destroy/aws/aws.go
This commit fixes the problem where S3 bucket deletion would fail if it had
versioned objects. deleteS3() now does a mass delete of any versioned objects
in the S3 bucket before deleting the bucket.
> bug 1815518: pkg/destroy/aws: delete versioned objects from s3 buckets

- pkg/destroy/openstack/openstack.go
When the cloud doesn't have support for trunk ports, we should not try
to delete them.
This is a manual backport of https://github.com/openshift/installer/pull/3319/ due to merge conflicts.
> Bug 1820153: OpenStack: Allow destroying cluster without trunk ports

- docs/user/openstack/install_upi.md
The Boostrap Ignition file needs to be edited before it's uploaded.
Before this change, the documentation described the "upload" step before
the "edit" step.
Manual cherry-pick of https://github.com/openshift/installer/pull/3370
/cc @mandre @Fedosin @adduarte @MaysaMacedo 
> Bug 1818608: os UPI fix step order

- pkg/tfvars/openstack/rhcos_image.go
Add link to the github issue tracking re-enabling of glance image
import:
https://github.com/openshift/installer/issues/3403
> OpenStack: Link to GH issue for glance image import

- pkg/types/baremetal/validation/platform.go
- pkg/types/baremetal/validation/platform_test.go
- pkg/types/validation/installconfig.go
- pkg/types/validation/installconfig_test.go
This PR adds a new Baremetal platform validation rule to verify that the configured hosts are equal or greater than the sum of the configured ControlPlane and Compute replicas.
In addition, it contains refactoring steps to:
- have a single generic function for defining and applying tags based validation 
- support future splitting of rules definition and their application by the use of a validation context
> baremetal: validate hosts number

- data/data/libvirt/bootstrap/main.tf
- data/data/libvirt/bootstrap/variables.tf
- data/data/libvirt/main.tf
- data/data/libvirt/variables-libvirt.tf
- pkg/asset/cluster/tfvars.go
- pkg/tfvars/libvirt/libvirt.go
On ppc64le there were OOM kills being observed during the bootstrap process
because of insufficient memory and bumping the memory seemed to solve the problem.
The libvirt defaults for the master and worker memory are 7G and 5G respectively,
so setting the boostrap default to 5G.
> Bug 1821788:libvirt: Bump bootstrap memory to 5G for ppc64le

- README.md
Fix documentation to no longer reflect needless requirement of cloning
the installer repository to a directory in $GOPATH/src.
[issue #3422]
* Tags: kind/documentation platform/none size/XS
> docs(README): README build steps don't require clone to GOPATH

- pkg/asset/installconfig/clustername.go
- pkg/types/validation/installconfig.go
This logic became a method in 1ab1cd3fb0 (#1169); so we can drop the validation-specific helper which was from bf3ee0353a (#1255).  Or maybe we never needed the validation-specific helper ;).
> pkg/types/validation: Drop internal ClusterDomain

- docs/user/openstack/install_upi.md
- upi/openstack/down-load-balancers.yaml
This commit ensures the lb ID is used instead of the name
when deleting a lb, as openstack allows multiple load balancers
with same name to coexist. Also, it ensures the deletion of lb
with status different than ERROR or ACTIVE to be skipped.
> Bug 1821653: Fix LB deletion for lbs with same or status pending

- cmd/openshift-install/create.go
- cmd/openshift-install/destroy.go
- cmd/openshift-install/waitfor.go
- go.sum
- pkg/asset/cluster/cluster.go
- pkg/metrics/timer/timer.go
- pkg/metrics/timer/timer_test.go
Adds a new feature which prints a summary of the time it took in
each stage of the installer after the stage has been completed.
Summary is currently supported for the create, wait-for and the
delete command. The summary is printed at the completion of the
command and will show the time elapsed for each of the stages
of the execution.
Create command has the following stages:-
. Infrastructure
. API
. Bootstrap Complete
. Destroy bootstrap complete.
. Cluster Operator Complete.
Destroy command has the following stages:- 
. Cluster
. Bootstrap
The wait-for command has the following stages:-
- Bootstrap-complete command
. Bootstrap
. API
- Install-complete command
. Cluster
. Console
> Print time for each step of installation

- data/data/openstack/bootstrap/main.tf
- data/data/openstack/bootstrap/variables.tf
- data/data/openstack/main.tf
- data/data/openstack/topology/private-network.tf
- docs/user/openstack/customization.md
- pkg/asset/cluster/tfvars.go
- pkg/asset/ignition/machine/node.go
- pkg/asset/manifests/infrastructure.go
- pkg/asset/tls/mcscertkey.go
- pkg/types/defaults/installconfig.go
- pkg/types/defaults/installconfig_test.go
- pkg/types/openstack/defaults/platform.go
- pkg/types/openstack/platform.go
- pkg/types/openstack/validation/platform.go
- pkg/types/openstack/validation/platform_test.go
Customers may want to plumb the networking that enables external access to the cluster in a number of ways. To make their job easier, this feature allows them to select fixed IP addresses that they can reach the API and apps ingress at in their OpenShift cluster. This allows them to use/reuse pre-existing routing and external access schemes more easily. This adds an additional optional set of values to the openstack platform section of the install config as follows:
```yaml
platform:
openstack:
cloud: ...
apiVIP: "10.0.0.35"
ingressVIP: "10.0.0.19"
```
Note that the default values have not changed. APIVIP still defaults to the `5` on the machineNetwork, and IngressVIP still defaults to the `7`.
> OpenStack: Custom API and Ingress vip addresses

- data/data/openstack/main.tf
- data/data/openstack/masters/main.tf
- data/data/openstack/masters/variables.tf
- data/data/openstack/variables-openstack.tf
- docs/user/openstack/customization.md
- go.mod
- go.sum
- pkg/asset/cluster/tfvars.go
- pkg/asset/machines/openstack/machines.go
- pkg/tfvars/openstack/openstack.go
- pkg/types/openstack/machinepool.go
- pkg/types/openstack/validation/machinepool.go
- pkg/types/openstack/validation/machinepool_test.go
- pkg/types/validation/installconfig_test.go
- vendor/modules.txt
- vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/apis/openstackproviderconfig/v1alpha1/types.go
In some cases we may need to provide access to additional networks and security groups. An example of this need would be to mount RWX volumes from OpenStack Manila, when shares are in another network (OSP default).
Since we plan to use Manila as the primary backend for the image registry, it is essential that we have this feature in IPI.
This PR adds two new parameters to OpenStack's MachinePool:
* `additionalNetworkIDs` (optional list of strings): IDs of additional networks for machines.
* `additionalSecurityGroupIDs` (optional list of strings): IDs of additional security groups for machines.
> OpenStack: allow to specify additional networks and security groups for masters and workers

- data/data/vsphere/main.tf
- pkg/terraform/exec/plugins/vsphereprivate/config.go
- pkg/terraform/exec/plugins/vsphereprivate/resource_vsphereprivate_import_ova.go
- Add rest client
- Add function `attachTag`. This function creates a TagManager
that will attach a tag to virtual machine managedobject
- Modify terraform resource schema
- Use provided Folder to place virtual machine (template) in.
- Update terraform to use `tag` for imported virtual machine
> Bug 1822858: vsphere ipi: tag virtual machine created when importing ova

- data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
When disabling CCO, the bootstrap-manifests dir will be empty which will error bootkube.sh when trying to copy the contents of the empty dir.
Detect the empty dir and avoid trying to copy the contents the empty dir in that situation.
> handle the posibility that CCO will have no pod definition

- pkg/destroy/ovirt/destroyer.go
Fixing some of the logging from 05177839ab (#1948) to avoid things like:
```console
$ openshift-install destroy cluster --dir one
INFO searching VMs by tag=one-6xlb7
INFO Found %!s(int=3) VMs
INFO Stopping VM one-6xlb7-master-1 : errors: %s%!(EXTRA <nil>)
...
```
because the final `err` had no `%s` in the template string to consume it.  This commit fixes the two cases which had an `errors: %s` using up the final template `%s`, but leaves a lot of other potential logging cleanup in this package alone.
> pkg/destroy/ovirt: Cleanup VM logging

- pkg/asset/installconfig/aws/permissions.go
recent changes to the installer for AWS now require these permissions to perform an install/uninstall.
ec2:GetEbsDefaultKmsKeyId
s3:GetBucketAcl
s3:ListBucketVersions
> update permissions list to cover new installer functionality

- docs/user/openstack/README.md
In order for the user to account for the needed resources, the
documentation should mention that while 2 floating IPs are needed for
running an OpenShift cluster, a third one will be used during
installation.
> Bug 1823659: os: Mention the bootstrap FIP

- upi/metal/main.tf
@sdodson - Please review these changes.
> Updates to fix DNS error for compact cluster worker nodes

- docs/user/openstack/install_upi.md
- docs/user/openstack/known-issues.md
- go.mod
- go.sum
- pkg/asset/installconfig/ovirt/config.go
- pkg/destroy/openstack/glance.go
- vendor/modules.txt
This also updates to latest MCO.
> [fcos] Cherrypick few 4.4 fixes

- pkg/destroy/azure/azure.go
When running an Azure uninstall for a cluster that has already been deleted, the uninstall fails due to an error deleting the resource group. This change accepts an already-deleted resource group as a successful uninstall of the resource group.
https://issues.redhat.com/browse/CO-863
> uninstall: allow for azure uninstall to succeed for missing rg

- docs/user/customization.md
The plural form was deprecated in 2e7ecd3ab3 (#1356).
> docs/user/customization: Fix 'clusterNetworks' -> 'clusterNetwork'

- hack/update-rhcos-bootimage.py
F-strings are [new in 3.6][1], and my old RHEL 7.5 CSB has the old Python 3.4.9 by default.  I'm probably just way behind the times, but it doesn't cost much to use the older `.format()` to make this compatible with all of Python 3 ;).
[1]: https://www.python.org/dev/peps/pep-0498/
> hack/update-rhcos-bootimage: Drop the f-string

- docs/user/metal/install_ipi.md
This commit adds a way to know beforehand which virtual router IDs a
baremetal IPI deployment will use in order to know, pre-deployment, if
those happen to conflict with already used virtual router IDs
pre-existent in the network.
> bug 1821667: baremetal IPI: Document Virtual Router IDs

- docs/user/openstack/known-issues.md
Some installations on slow OpenStack clouds might take longer than the
installer timeout.
> Bug 1819746: Add a note on slow installations

- data/data/baremetal/main.tf
- data/data/baremetal/masters/main.tf
- data/data/baremetal/masters/variables.tf
- data/data/baremetal/variables-baremetal.tf
- go.mod
- go.sum
- pkg/asset/cluster/tfvars.go
- pkg/tfvars/baremetal/baremetal.go
- vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/resource_ironic_deployment.go
- vendor/golang.org/x/lint/go.mod
- vendor/golang.org/x/lint/go.sum
- vendor/golang.org/x/lint/lint.go
- vendor/modules.txt
Today, the installer uses a stub ignition that simply points to the full rendered ignition hosted by the bootstrap. However, the full ignition may contain configuration to configure network interfaces with bonding, vlans, etc.
That means the full ignition would need to be sent to the masters instead of the stub, because the hosts may not have network connectivity until after ignition is run. This PR enables the baremetal platform to optionally send full ignition to masters.
Depends on:
https://github.com/openshift-metal3/terraform-provider-ironic/pull/38
~~https://github.com/metal3-io/baremetal-operator/pull/455~~
https://github.com/openshift/cluster-api-provider-baremetal/pull/65
> Baremetal: Support to send full ignition to masters

- pkg/asset/installconfig/gcp/gcp.go
- pkg/asset/installconfig/vsphere/vsphere.go
- pkg/types/installconfig.go
This pull request adds the interactive wizard for creating a vSphere install config. After querying credentials from the user, the options are populated from the vCenter API. In cases where only one option is available, it is automatically selected.
This is WIP, but is mostly done, so I am posting for general feedback as well as specific feedback regarding networks. There seem to be four types of vSphere networks. In our vcenter there are DistributedVirtualPortGroups and DistributedVirtualSwitches, and some of these have children. Are all of these valid selections or should I be filtering some of them? The network list is pulled here: https://github.com/openshift/installer/compare/master...patrickdillon:vsphere-tui-cors-1415?expand=1#diff-8366d626249d949112555caeac30a52cR262
Here is a …
> pkg/asset/installconfig: add vSphere TUI wizard

- data/data/openstack/topology/sg-master.tf
- data/data/openstack/topology/sg-worker.tf
Using `remote_group_id` in the security rules is very inefficient, triggering a lot of computation by ovs agent to generate the flows and possibly exceeding the time allocated for flow generation. In such cases, especially in environments already under stress, masters nodes may be unable to communicate with worker nodes, leading the deployment to fail.
We're seeing this behavior in MOC, the cloud we're using for our CI.
The workaround is to use the more efficient remote_ip_prefix rather than remote_group_id when creating security rules.
This was already done for openshift-ansible in the past: https://bugzilla.redhat.com/show_bug.cgi?id=1703947
> Bug 1824287: OpenStack: Replace remote_group_id with remote_ip_prefix

- docs/user/metal/install_ipi.md
This PR enhances the documentation for the baremetal configuration by describing the validations added in #3392, #3232 and #3358
> baremetal: add documentation for configuration validations

- data/data/openstack/main.tf
- data/data/openstack/topology/outputs.tf
- data/data/openstack/topology/private-network.tf
- data/data/openstack/topology/variables.tf
- data/data/openstack/variables-openstack.tf
- docs/user/openstack/customization.md
- pkg/asset/cluster/tfvars.go
- pkg/asset/installconfig/openstack/realvalidvaluesfetcher.go
- pkg/asset/machines/openstack/machines.go
- pkg/asset/mock/filefetcher_generated.go
- pkg/tfvars/openstack/openstack.go
- pkg/types/openstack/platform.go
- pkg/types/openstack/validation/mock/validvaluesfetcher_generated.go
- pkg/types/openstack/validation/platform.go
- pkg/types/openstack/validation/platform_test.go
- pkg/types/openstack/validation/validvaluesfetcher.go
Enable IPI support for users to pass the installer an already provisioned subnet in openstack to use as the nods subnet. The installer should take the subnet passed to the install config, if there is one, and should not create a network, or a subnet in openstack.
```yaml
apiVersion: v1
baseDomain: example.com
metadata: 
name: test-cluster
platform: 
openstack: 
nodesSubnet: abcd-4321
pullSecret: '{"auths": ...}'
sshKey: ssh-ed25519 AAAA...
```
> OpenStack: Custom subnets

- upi/openstack/security-groups.yaml
OpenStack with OVS has an issue where security groups using
remote_group_id can be very slow, leading to OVS dropping packets.
https://bugzilla.redhat.com/show_bug.cgi?id=1703947
Use remote_ip_prefix instead to work around the issue.
This is the UPI port of https://github.com/openshift/installer/pull/3461
/cc @mandre @iamemilio @Fedosin @adduarte
> Bug 1825286: OpenStack UPI: Replace remote_group_id with remote_ip_prefix

- data/data/openstack/topology/sg-master.tf
- data/data/openstack/topology/sg-worker.tf
If VRRP plugin is disabled in neutron, then Terraform fails to fetch the desired protocol number.
To prevent the issue this patch explicitly sets the protocol number to 112 for the sg rules.
For more information:
https://docs.openstack.org/api-ref/network/v2/index.html?expanded=create-security-group-rule-detail
> Bug 1822701: OpenStack: Set vrrp protocol number instead of name

- pkg/asset/manifests/vsphere/cloudproviderconfig.go
Cloud provider still uses cluster name for folder. Platform does include folder from install-config:
https://github.com/openshift/installer/blob/release-4.4/pkg/types/vsphere/platform.go#L22
But, the cloud provider still uses cluster name:
https://github.com/openshift/installer/blob/release-4.4/pkg/asset/manifests/vsphere/cloudproviderconfig.go#L30 (edited)
> update cloud provider to use folder from platform

- pkg/types/baremetal/validation/platform.go
- pkg/types/baremetal/validation/platform_test.go
Currently there's no explicit check for overlap between these two
networks, we only check if the default calculated VIPs exist in a
machine network. This is not reliable, and the error message is also not
very clear.
For example, if the machineCIDR is `192.168.111.192/26`, and the
provisioningNetworkCIDR is `192.168.111.0/24` the default VIP's will
not be in the machineCIDR range -- this will validate successfully, even
though it's not a valid configuration.
This adds explict checks and errors for this case.
> Bug 1813422: baremetal: validate no overlap between provisioning and machine nets

- pkg/asset/installconfig/vsphere/validation_test.go
- pkg/asset/manifests/infrastructure.go
- pkg/types/vsphere/platform.go
- pkg/types/vsphere/validation/platform.go
- pkg/types/vsphere/validation/platform_test.go
These changes remove the required field `NodeDNSIP` from openshift/api
and `DNSVIP` from the vsphere platform.
> vsphere ipi: align with baremetal and remove DNSVIP

- data/data/openstack/bootstrap/main.tf
- data/data/openstack/bootstrap/variables.tf
- data/data/openstack/main.tf
- docs/user/openstack/customization.md
Some OpenStack environments might enforce a policy where VMs can't boot
with ephemeral disks and need to boot from a cinder volume. In these
cases, it would be impossible to install OCP because even though we
configured the master and worker nodes to boot from volume using the
`rootVolume` setting, the bootstrap node would still boot from
ephemeral disk.
With this change, the bootstrap node follows the `rootVolume` settings
from controlPlane machine pool. This shouldn't be a surprising behavior
since the bootstrap node is already using the same flavor and security
groups as the control plane nodes.
> Bug 1820434: OpenStack: Allow Booting bootstrap node from volume

- pkg/asset/installconfig/ovirt/credentials.go
This is a follow-on to 3eccc348. After looking at this more closely, I
realized that the cert bundle is only prompted if the CA is trusted
locally. This means that if the CA isn't trusted, the communication with
the oVirt engine will be insecure. I added a warning to reflect that
reality.
> installconfig/ovirt: fix CA prompt and add warning

- data/data/openstack/topology/sg-master.tf
- data/data/openstack/topology/sg-worker.tf
OpenStack with OVS has an issue where security groups using
remote_group_id can be very slow, leading to OVS dropping packets.
https://bugzilla.redhat.com/show_bug.cgi?id=1703947
Use remote_ip_prefix instead to workaround the issue.
This is a cherry-pick of https://github.com/openshift/installer/pull/3461
> [release-4.4] Bug 1825460: OpenStack: Replace remote_group_id with remote_ip_prefix

- docs/user/power/install_upi.md
This is derived from https://github.com/openshift/installer/blob/master/docs/user/zvm/install_upi.md
> Add instructions for UPI install on Power

- images/installer/Dockerfile.upi.ci
This change combines the two yum install calls in Dockerfile.upi.ci and adds the binaries used by CI to install a UPI GCP cluster.
> Dockerfile.upi.ci: Add GCP UPI required binaries.

- data/data/manifests/openshift/community-operators.yaml
- data/data/manifests/openshift/upstream-community-operators.yaml
- pkg/asset/templates/content/openshift/community-operators.go
This adds a new "upstream-community-operators" operator source for OKD clusters, alongside with curated "community-operators"
Ref: https://github.com/openshift/okd/issues/99
> [fcos] add a new upstream community operator source

- upi/openstack/down-load-balancers.yaml
No functional changes.
An Ansible step mentions Server groups, while it gathers a token for
calls unrelated to server groups.
/cc @MaysaMacedo 
> Bug 1826739: openstack UPI: Fix step name

- cmd/openshift-install/gather.go
When gathering bootstrap logs, it's not clear where the log bundle is written.
This prints out the absolute path to the log bundle.
Without fix:
DEBUG Log bundle written to /var/home/core/log-bundle-20200421144316.tar.gz 
INFO Bootstrap gather logs captured here "log-bundle-20200421144316.tar.gz" 
With fix:
DEBUG Log bundle written to /var/home/core/log-bundle-20200421144316.tar.gz 
INFO Bootstrap gather logs captured here "/home/jhixson/Test-AWS-Fail/log-bundle-20200421144316.tar.gz"
> bug 1821932: cmd/openshift-install/gather: clarify location of log bundle

- images/openstack/Dockerfile.ci
Documentation change.
Add a comment explaining why we are installing the AWS command-line
client in the CI image for OpenStack.
ref https://github.com/openshift/installer/pull/3478#issuecomment-617907257
/assign @russellb 
/cc @mandre @iamemilio @adduarte
> Bug 1827070: openstack: Explain why awscli in the CI image

- data/data/openstack/topology/private-network.tf
- pkg/destroy/openstack/openstack.go
- pkg/tfvars/openstack/openstack.go
In the case of multiple added networks the tag `<infraID>-primaryClusterNetwork` should allow cluster-api-provider-openstack to define which IP address to set as the primary one for machines.
Now CAPO can't do this, because Neutron returns the list of networks in alphabetical order.
> Bug 1824426: tag primary OpenStack networks

- data/data/manifests/openshift/baremetal-provisioning-config.yaml.template
For the provisioning config, it's allowable for provisioningDHCPRange to
be empty. If it is, the current template produces this YAML:
```yaml
spec:
provisioningDHCPRange:
```
Unfortunately, in YAML-land the above is null not empty string, so when
you apply it, you get complaints:
```
Provisioning.metal3.io "provisioning-configuration" is invalid:
spec.provisioningDHCPRange: Invalid value: "null":
spec.provisioningDHCPRange in body must be of type string: "null"
```
This change ensures all string values are quoted, which will result in a
correct value for provisioningDHCPRange when empty.
> Bug 1823359: baremetal: update provisioning CR to quote strings

- data/data/openstack/topology/sg-master.tf
- data/data/openstack/topology/sg-worker.tf
OpenStack with OVS has an issue where security groups using
remote_group_id can be very slow, leading to OVS dropping packets.
https://bugzilla.redhat.com/show_bug.cgi?id=1703947
Use remote_ip_prefix instead to workaround the issue.
This is a cherry-pick of https://github.com/openshift/installer/pull/3477
/cc @mandre @iamemilio @adduarte @Fedosin 
> [release-4.3] Bug 1825973: OpenStack: Replace remote_group_id with remote_ip_prefix

- upi/openstack/common.yaml
The installer creates a server group as a side effect of the manifest
generation.
Prior to this patch, the UPI playbooks created yet another server group
and left the installer-created one unused.
With this patch, the UPI playbooks reuse the server group created by the
installer, rather than creating an additional one.
/cc @adduarte @MaysaMacedo @mandre 
> Bug 1827067: openstack UPI: Server group name to match IPI

- data/data/rhcos-amd64.json
- data/data/rhcos.json
Update to latest package sets. This includes an updated cri-o for https://bugzilla.redhat.com/show_bug.cgi?id=1826896
```
"diff": {
"conmon": {
"rhcos-4.4/44.81.202003110027-0": "conmon-2.0.11-1.rhaos4.4.el8.x86_64",
"rhcos-4.4/44.81.202004250133-0": "conmon-2.0.15-1.rhaos4.4.el8.x86_64"
},
"coreutils": {
"rhcos-4.4/44.81.202003110027-0": "coreutils-8.30-6.el8.x86_64",
"rhcos-4.4/44.81.202004250133-0": "coreutils-8.30-6.el8_1.1.x86_64"
},
"coreutils-common": {
"rhcos-4.4/44.81.202003110027-0": "coreutils-common-8.30-6.el8.x86_64",
"rhcos-4.4/44.81.202004250133-0": "coreutils-common-8.30-6.el8_1.1.x86_64"
},
"cri-o": {
"rhcos-4.4/44.81.202003110027-0": "cri-o-1.17.0-8.dev.rhaos4.4.git36920a5.el8.x86_64",
"rhcos-4.4/44.81.202004250133-0": "cri-o-1.17.4-6.dev.rhaos4.4.gitb5c490c.el8.x86_64" …
```
> Bug 1826896: rhcos: bump RHCOS boot image to 44.81.202004250133-0

- data/data/rhcos-amd64.json
- data/data/rhcos.json
Update to latest package sets. This includes an updated cri-o https://bugzilla.redhat.com/show_bug.cgi?id=1826895
```
"diff": {
"conmon": {
"rhcos-4.4/44.81.202003062006-0": "conmon-2.0.11-1.rhaos4.4.el8.x86_64",
"rhcos-4.4/44.81.202004250133-0": "conmon-2.0.15-1.rhaos4.4.el8.x86_64"
},
"coreutils": {
"rhcos-4.4/44.81.202003062006-0": "coreutils-8.30-6.el8.x86_64",
"rhcos-4.4/44.81.202004250133-0": "coreutils-8.30-6.el8_1.1.x86_64"
},
"coreutils-common": {
"rhcos-4.4/44.81.202003062006-0": "coreutils-common-8.30-6.el8.x86_64",
"rhcos-4.4/44.81.202004250133-0": "coreutils-common-8.30-6.el8_1.1.x86_64"
},
"cri-o": {
"rhcos-4.4/44.81.202003062006-0": "cri-o-1.17.0-4.dev.rhaos4.4.gitc3436cc.el8.x86_64",
"rhcos-4.4/44.81.202004250133-0": "cri-o-1.17.4-6.dev.rhaos4.4.gitb5c490c.el8.x86_64"
}, …
```
> Bug 1826895: rhcos: bump RHCOS boot image to 44.81.202004250133-0

- data/data/azure/main.tf
- data/data/azure/master/outputs.tf
- data/data/azure/master/variables.tf
- data/data/azure/vnet/internal-lb.tf
- data/data/azure/vnet/outputs.tf
- data/data/azure/vnet/public-lb.tf
Azure only allows a NIC to be in one load balancer, which prevents
service load balancers from working on masters (the NIC is part of
the kube-apiserver LB). This prevents compact Azure clusters and
any future service that wishes to run on the master.
Instead, rename the Azure LB and backend pool so that it matches
the names the Azure cloud controller will add service load balancer
rules to. Azure LBs allow multiple frontends against a single
backend and so both kube-apiserver (selecting just masters) can
co-exist with service load balancers.
The only downside is a pod on a node on port 6443 would be included
in the balancer - but since we intend to move kube-apiserver behind
a service load balancer in the future and nothing stops the router
from being impacted the same way (someone …
> Bug 1794839: Azure masters should correctly support service load balancers

- images/openstack/Dockerfile.ci
Using jq will simplify the CI scripts where we currently use `awk` to parse JSON.
> Bug 1827667: openstack: Add jq to the CI image

- docs/user/openstack/README.md
For a successful installation, it is required to be able to tag network
resources.
/cc mandre Fedosin iamemilio adduarte
> Bug 1826317: openstack docs: Add tagging as a requirement

- data/data/openstack/topology/sg-master.tf
- data/data/openstack/topology/sg-worker.tf
OpenStack with OVS has an issue where security groups using
remote_group_id can be very slow, leading to OVS dropping packets.
https://bugzilla.redhat.com/show_bug.cgi?id=1703947
Use remote_ip_prefix instead to workaround the issue.
> Bug 1827795: OpenStack: Replace remote_group_id with remote_ip_prefix

- images/baremetal/Dockerfile.ci
For the baremetal platform, we need to know where the images are in
order to mirror them.  Especially for IPv6 environments where we may not
have outbound internet access to download the images.
Typically, we download the rhcos.json from the sha reported by
`openshift-install version` but this doesn't work in CI, where PR's are
always rebased on master and the sha reported doesn't exist on GitHub.
This is a temporary workaround until the machine OS content is part of
the release image itself.
Backports #3330
> [release-4.4] images/baremetal: save rhcos.json in container image

- upi/metal/README.md
The link currently points to the repo (and hence README), which doesn't have the essential information and is not really a guide that we are claiming it to be, here. Let's link directly to the getting started guide.
> baremetal: Link directly to getting-started guide in the docs

- upi/metal/README.md
And it's not the guide we're talking about. I misunderstood and wasted a lot of time. :)
> baremetal: Clarify it's the matchbox instance that needs to be public reachable

- data/data/vsphere/main.tf
- data/data/vsphere/variables-vsphere.tf
- docs/user/vsphere/customization.md
- pkg/asset/cluster/tfvars.go
- pkg/asset/installconfig/vsphere/validation.go
- pkg/asset/machines/vsphere/machines.go
- pkg/asset/manifests/cloudproviderconfig.go
- pkg/asset/manifests/vsphere/cloudproviderconfig.go
- pkg/asset/manifests/vsphere/cloudproviderconfig_test.go
- pkg/destroy/vsphere/vsphere.go
- pkg/terraform/exec/plugins/vsphereprivate/resource_vsphereprivate_import_ova.go
- pkg/tfvars/vsphere/vsphere.go
- pkg/types/validation/installconfig_test.go
- pkg/types/vsphere/platform.go
- pkg/types/vsphere/validation/platform.go
Before this PR, we were always creating a folder with the cluster ID (incorrectly ignoring the folder specified in the install config). Now, if users specify a folder in the install config, terraform will expect there to be an existing folder and will use it for installation. If none is specified, a folder will be created with install config.
TODO:
**Folder Paths**
vSphere libraries seem to use a mixture of relative and absolute paths. Some of these issues only seem to arise when using nested folders; that is, a relative path is ok for a top-level folder but an absolute path is required for a nested folder. This is the case for the Machine API provider and terraform import_ova resource. The cloud config and terraform virtual machine resource need relative paths.
**Validation**
Adds static …
> Bug 1826100: vSphere allow users to specify existing folder

- pkg/terraform/exec/exec.go
also fixes bz https://bugzilla.redhat.com/show_bug.cgi?id=1830123
> bug 1807111: terraform/exec: suppress the warnings from error to debug

- pkg/asset/tls/tls.go
Based on https://tools.ietf.org/html/rfc3280#section-4.2.1.1 and https://tools.ietf.org/html/rfc3280#section-4.2.1.2 
We should not set SubjectKeyId to signing certificate value. We should set it to the current certificate value.
> Bug 1831760: Fix bootstrap certificate generation

- docs/user/openstack/README.md
Prior to this change, the documentation refers to working clusters with
two workers. As of 4.5, two workers of 2vCPUs are not enough for a
healthy cluster.
/cc @mandre @adduarte @Fedosin @iamemilio
> Bug 1814605: openstack: Require three workers

- docs/user/troubleshooting.md
- docs/user/troubleshootingbootstrap.md
This adds a document that provides,
1. structural information about various file in the bootstrap log bundle
2. some common failures that can be troubleshooted using the bootstrap log bundle
/cc @openshift/openshift-team-installer
> docs/user: add troubleshootingbootstrap to define the bootstrap log bundle

- data/data/openstack/bootstrap/main.tf
- data/data/openstack/bootstrap/variables.tf
- data/data/openstack/main.tf
- docs/user/openstack/customization.md
Some OpenStack environments might enforce a policy where VMs can't boot
with ephemeral disks and need to boot from a cinder volume. In these
cases, it would be impossible to install OCP because even though we
configured the master and worker nodes to boot from volume using the
`rootVolume` setting, the bootstrap node would still boot from
ephemeral disk.
With this change, the bootstrap node follows the `rootVolume` settings
from controlPlane machine pool. This shouldn't be a surprising behavior
since the bootstrap node is already using the same flavor and security
groups as the control plane nodes.
This is a cherry-pick of https://github.com/openshift/installer/pull/3434
> Bug 1828238: OpenStack: Allow Booting bootstrap node from volume

- data/data/azure/main.tf
- data/data/rhcos-amd64.json
- data/data/rhcos.json
- pkg/tfvars/azure/azure.go
Hi,
these commits fix a few issues:
- FCOS version typo
- FCOS image for Azure will be decompressed
- blob type now is 'page'
The installer built with this commits still uploads the decompressed (8GByte big) FCOS image to Azure. For that to work you should run the openshift-install tool in an Azure cloud shell.
Greetings,
Josef
> [FCOS] Azure fixes (correct FCOS version, decompress fcos image for Azure, page blob)

- data/data/azure/main.tf
- data/data/azure/vnet/nsg.tf
- data/data/azure/vnet/outputs.tf
- pkg/asset/manifests/cloudproviderconfig.go
The Kubernetes service load balancer programs a cluster specific
Azure NSG automatically to expose service load balancers. OpenShift
requires all nodes to be able to host service load balancer workloads
and so the simplest configuration is to have a single network security
group for the whole cluster. This does require exposing port 6443 on
all nodes, but in practice this does not reduce security because we
cannot rely on network security within the cluster to protect
workloads.
As a result of this change, a 3 node compact Azure cluster can be
grown to have a worker pool at runtime with no disruption to the
router or other components that depend on service load balancer.
> Bug 1794839: data/azure: Use a single network security group for Azure clusters

- pkg/asset/installconfig/azure/dns.go
- pkg/asset/installconfig/azure/validation.go
- pkg/asset/installconfig/platformprovisioncheck.go
This code checks to see if an existing DNS record exists for api.clusterName and fails if it exists. 
See https://bugzilla.redhat.com/show_bug.cgi?id=1732124
> Bug 1732124: Azure: don't allow installing with the same cluster name as an existing install

- docs/user/power/install_upi.md
Changes recommended from the original review comments in PR #3454 .
Change worker machine minimum to 2.
Reword air-gapped to restricted network install.
etc.
> docs/user/power/install_upi: 2 compute and copy-edits

- hack/verify-codegen.sh
- pkg/explain/cmd.go
- pkg/rhcos/ami_regions_generate.go
6f929ae i missed that commit in #3515 so i have included it here.
/assign @patrickdillon
> Bug 1833425: pkg/explain/cmd.go: fix help text

- docs/user/openstack/README.md
cf https://github.com/shiftstack/installer/blob/aa5df6782839bdfe4a98ed3413885853cd2cecba/cmd/openshift-install/create.go#L259-L260
Closes https://github.com/openshift/installer/issues/3585
/cc @iamemilio @adduarte
> Bug 1834748: os: Fix wait-for install-complete timeout in docs

- docs/user/azure/install_upi.md
- upi/azure/01_vnet.json
- upi/azure/04_bootstrap.json
- upi/azure/setup-manifests.py
This updates UPI to be in par with https://github.com/openshift/installer/pull/3561
> bug 1834177: upi/azure: Use a single network security group for Azure clusters

- data/data/vsphere/master/main.tf
- pkg/types/validation/machinepools.go
- pkg/types/vsphere/validation/machinepool.go
- pkg/types/vsphere/validation/machinepool_test.go
The disk size for masters in terraform was hardcoded to 120 GB. This removes the hardcoded value and uses the value from the machinepool, whether it is the default or user-provided. Also adds validation and tests for the machine pools.
/cc @rna-afk
> Bug 1828638: set vSphere node diskSize based on machine pool

- data/data/baremetal/main.tf
- data/data/baremetal/masters/main.tf
- data/data/baremetal/masters/variables.tf
- data/data/baremetal/variables-baremetal.tf
- pkg/asset/cluster/tfvars.go
- pkg/tfvars/baremetal/baremetal.go
This was merged in https://github.com/openshift/installer/pull/3276
but had the side-effect of breaking an interface some users were
already reliant on, where additional config is added to the
pointer ignition output via `create ignition-configs`
Downstream bz https://bugzilla.redhat.com/show_bug.cgi?id=1833483
reported this issue, and we've taken the decision to revert this
to resolve that interface regression, and look at other ways to
satisfy the requirements that led to #3276
This reverts commit f67d61a7142a95063e096857a6c477bef376a3e7.
> Bug 1833483: Revert "baremetal: send full ignition to masters"

- data/data/libvirt/volume/main.tf
- images/libvirt/Dockerfile.ci
2 fixes for OKD:
* set entrypoint in `images/libvirt/Dockerfile`. Not sure why it is unset (so that nested GCP can be tested)?
* resize FCOS image to 16GB when machines are created.
RHCOS image is 16GB, while FCOS is 8GB and single master installation needs a lot of space. This commit would resize bootstrap / master machines to 16GB
/cc @LorbusChris @praveenkumar
> [fcos] libvirt container entrypoint, resize image to 16GB

- pkg/asset/installconfig/vsphere/validation.go
vSphere validation checks whether a folder exists when creating manifests or ignition configs. Creating the folder after the manifests or ignition configs is a valid UPI workflow so this check should only be run when provisioning infrastructure.
@abhinavdahiya we [discussed this before](https://github.com/openshift/installer/pull/3498#discussion_r418114851), but it seems I answered your question incorrectly.
cc @jcpowermac did you see UPI documentation that needs to be changed to work with the new folder requirements? I am not seeing it in the repo. perhaps you were looking at official docs?
> Bug 1835438: move vSphere folder validation to provisioning

- pkg/destroy/openstack/swift.go
Now if the function fails, we stop the installation immediately, but it's better to retry several times before finally stopping the installation.
> Bug 1820591: Add retries to DeleteSwiftContainer

- data/data/baremetal/masters/main.tf
- data/data/bootstrap/baremetal/files/usr/local/bin/master-bmh-update.sh
- data/data/bootstrap/baremetal/systemd/units/master-bmh-update.service
- pkg/asset/ignition/bootstrap/bootstrap.go
Right now we don't get any introspection data about the masters
because they are provisioned by the bootstrap node and the information
is lost.  This patch adds a script to pull the introspection data
from ironic running on the bootstrap and places it in the BareMetalHost CRs
for the masters.  This is done via an annotation as we cannot directly
update the Status in BMH.  The annotation is picked up by the BMO
and added to the BMH CRs.
There are several bugs filed about this:
https://github.com/openshift-metal3/dev-scripts/issues/917
https://bugzilla.redhat.com/show_bug.cgi?id=1801238
> Baremetal: Bug 1801238: Pull data from ironic inspector and annotate BareMetalHost

- pkg/asset/installconfig/ovirt/validaton.go
Aggregating a nil instead of empty slice ([]) when the validation is
successful will cause the field.Errors.Aggregate function to panic.
apending an empty slice to a slice using the variadic syntax will leave
the slice untouched.
> Bug 1836368: ovirt: return slice and not nil in instanceTypeID validation

- README.md
Adding a pointer to existing doc from the installer tree.
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1816834
> ovirt: Add ovirt to supported platforms

- data/data/aws/vpc/vpc-private.tf
- data/data/aws/vpc/vpc-public.tf
For every availability zone, we need a subnet. `ceil(log2(num of AZs))` finds the smallest exponent of 2 that is greater than or equal to `num of AZs`
Using that to split the private/public machine_cidr range allows the installer to carve out network ranges for each AZ with minimum unused.
Previously the installer would create 8 ranges always even when only a few were required.
> Bug 1835867: data/data/aws/vpc: create subnet sizes based on az count

- pkg/asset/machines/master.go
- pkg/asset/machines/singlemaster.go
Along with https://github.com/openshift/machine-config-operator/pull/1708 this enabled single master installations.
If master pool has a single replica unsupported etcd configuration is injected. Ingress replica is scaled to 1
> [fcos] Inject etcd and ingress tweaks when a single master is used

- data/data/install.openshift.io_installconfigs.yaml
- docs/user/gcp/customization.md
- pkg/asset/machines/gcp/machines.go
- pkg/asset/machines/worker.go
- pkg/types/gcp/machinepools.go
- pkg/types/gcp/validation/machinepool.go
- pkg/types/gcp/validation/machinepool_test.go
- pkg/types/gcp/validation/platform.go
- pkg/types/gcp/validation/platform_test.go
- pkg/types/validation/machinepools.go
- pkg/types/validation/machinepools_test.go
Currently, the installer does not allow the users to customize the
type and size of the disks for the workers and control plane.
Added the option for the user to specify the type and the size of
the disks for both machines in GCP.
The user can specify two types of disks, pd-standard and pd-ssd disks
which are the options that GCP/Terraform provides. pd-standard is not
recommended for control planes and will not be allowed as a value in
the DefaultMachinePlatform and the master compute section.
> Bug 1836339: GCP: Enable disk type and size customization

- docs/user/vsphere/install_upi.md
To enable infrastructure provisioning in vSphere, the installer now
creates machine object and machineset manifests. This commit updates
UPI docs to remove those manifests, as the skew between the installer
produced manifests and user-provisioned control-plane causes errors.
cc @jcpowermac
> Bug 1834966: update vSphere UPI docs to remove machinesets

- docs/user/ovirt/install_ipi.md
docs: Update for oVirt installation and customization
revisit install_ipi.md
> Bug 1804230: Documentation Incorrect for OCP 4.4 RHV IPI Install

- pkg/diagnostics/error.go
- pkg/terraform/diagnose.go
- pkg/terraform/diagnose_test.go
- pkg/terraform/terraform.go
The terraform errors are tracked in a buffer. This buffers is then used to match against various
known conditions to understand the reasons for the errors.
This now allows the terraform apply to return specific errors in these cases instead of previous `failed to apply Terraform` constant
string message.
/cc @openshift/openshift-team-installer
> Bug 1837564: pkg/terraform: add diagnostics errors for terraform apply operations

- data/data/libvirt/bootstrap/main.tf
- data/data/libvirt/bootstrap/variables.tf
- data/data/libvirt/main.tf
- data/data/libvirt/variables-libvirt.tf
- pkg/asset/cluster/tfvars.go
- pkg/tfvars/libvirt/libvirt.go
On ppc64le there were OOM kills being observed during the bootstrap process
because of insufficient memory and bumping the memory seemed to solve the problem.
The libvirt defaults for the master and worker memory are 7G and 5G respectively,
so setting the boostrap default to 5G for ppc64le. ppc64le uses 64K pages rather than
the default 4K page size and thus requires more memory.
(cherry picked from commit c57c68097e2a8219267972c7c443eaf26e57bc6e)
> Bug 1820222: libvirt: Bump bootstrap memory to 5G for ppc64le

- pkg/asset/manifests/cloudproviderconfig.go
- pkg/asset/manifests/vsphere/cloudproviderconfig.go
- pkg/asset/manifests/vsphere/cloudproviderconfig_test.go
This is a partial revision of 814f64f4bce13a1c4472a104f72b7658b0e76abe,
where we update to use an absolute path rather than a relative path.
Using a relative path results in an error when trying to provision a PVC
and a subfolder was used for install.
> Bug 1836042: set folder absolute path in vSphere cloud provider

- data/data/rhcos-amd64.json
- data/data/rhcos.json
A lot of fixes here, for example time synchronization, see
https://bugzilla.redhat.com/show_bug.cgi?id=1828342
and entropy:
https://bugzilla.redhat.com/show_bug.cgi?id=1830280
In particular, we definitely need time sync on the bootstrap
node.
> Bug 1837039: rhcos: Bump to 45.81.202005181029-0

- data/data/gcp/bootstrap/main.tf
- data/data/gcp/master/main.tf
- pkg/asset/installconfig/clusterid.go
- pkg/asset/machines/gcp/machines.go
- pkg/asset/machines/gcp/machinesets.go
The infra id of the clusters on GCP was reduced to 12 in #2088 because we couldn't handle the hostname seen by rhcos machine to be greater than 64.
More details on this are available in https://bugzilla.redhat.com/show_bug.cgi?id=1809345
now since BZ 1809345 is fixed by openshift/machine-config-operator#1711 and openshift/cluster-api-provider-gcp#88 the installer can relax the restriction on the infra-id to match the other platforms.
Why is it important?
On GCP all resources are prefixed with infra-id, which currently is 12 chars with 6 chars used by random bit, leaving only 6 chars from cluster name. This causes trouble associating the cluster to jobs in CI as most of the identifyable characters are dropped from the resource names in CI due to this restriction.
Also because of the …
> Bug 1837642: installconfig: relax GCP cluster id restriction

- data/data/ovirt/template/main.tf
On [1] we sent a patch to add the rchos os type,
the string we gave was wrong which caused the tepmplate to be created with the wrong OS type
This patch fixes the problem
> Bug 1821151: oVirt, fix rhcos os_type name

- OWNERS_ALIASES
blunderbuss uses the nearest OWNERS file to calculate the reviewers for PR. Since there are only
platform approvers, all the PRs end up assigned to installer-reviewers.
From now on we should,
- ensure there are at least 2 revierwers when we define a OWNERS file
- duplicates in approvers and reviewers is acceptable, mimicing the approvers as reviewers should be the fine for now.
/cc @openshift/openshift-team-installer
> OWNER_ALIASES: ensure there are atleast 2 reviewers for each platform

- OWNERS_ALIASES
This is one way we'll help them stay in the loop with architectural changes.
> Adding a few people to the ARO team to our list of reviewers

- cmd/openshift-install/gather.go
- data/data/baremetal/main.tf
- data/data/baremetal/masters/main.tf
- data/data/bootstrap/files/usr/local/bin/installer-gather.sh
- go.mod
- go.sum
- pkg/terraform/gather/baremetal/OWNERS
- pkg/terraform/gather/baremetal/ip.go
- vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/provider.go
- vendor/modules.txt
This enables bootstrap log gathering for baremetal. We fetch the IP's
for the control plane hosts using ironic introspection data, and use
the provisioning IP for the bootstrap.
fixes #2009
> Bug 1798498: gather: enable bootstrap log gathering for baremetal

- data/data/install.openshift.io_installconfigs.yaml
- docs/user/gcp/customization.md
- pkg/types/gcp/machinepools.go
- pkg/types/gcp/validation/machinepool.go
- pkg/types/gcp/validation/machinepool_test.go
Current disk size restrictions for GCP is set to be above 0.
The current size of the image is 16GB and hence the disk sizes
must at least be 16GB. Also, the maximum disk size limit on GCP
is 65536GB so users must not be allowed to create disks above that
limit. Added the validations to the install config input for GCP.
> Bug 1838631: Set validations for GCP disk sizes.

- data/data/ovirt/template/main.tf
- pkg/asset/installconfig/ovirt/validaton_test.go
On RHV 4.3.9 we have change the ignition handling and API, to recognize an ignition is passed to the VM we need to specify the os_type as RHCOS.
During the installation the installer creates a ovirt templates to be used by the nodes, so we need to create the template with os_type = "rchos_x64".
Signed-off-by: Gal Zaidman <gzaidman@redhat.com>
> Bug 1821638: oVirt, add os_type to ovirt templates

- docs/user/metal/install_ipi.md
- pkg/asset/manifests/infrastructure.go
- pkg/types/baremetal/platform.go
- pkg/types/baremetal/validation/platform.go
- pkg/types/baremetal/validation/platform_test.go
- pkg/types/validation/installconfig_test.go
Use of this setting is being removed in [0]. Once that goes in we
can remove it from the installer as well.
0: https://github.com/openshift/machine-config-operator/pull/1569
> Bug 1840496: [baremetal] Remove DNS VIP

- pkg/asset/machines/libvirt/machines.go
From 4.4 onward, on libvirt installations, it is seen that with 7G of memory
as the default for the worker machines, the kube-storage-version-migrator pod does
not get provisioned successfully because the node does not meet its memory requirements.
Bumping to 8G fixes the issue.
> Bug 1840710: libvirt: Bump machine memory from 7G to 8G

- data/data/bootstrap/files/usr/local/bin/crio-configure.sh.template
- data/data/bootstrap/systemd/units/bootkube.service
Hi,
as default crio configures a pause image *k8s.gcr.io/pause:3.1* which is pulled from the internet at the first start of crio. This creates problems if OKD is installed in an offline scenario without access to the internet.
This was initially fixed by patching this image name last year but the fix was overwritten here:
https://github.com/openshift/installer/commit/112ac42637836367e829a3653e7470e68054aea6#diff-bf9773415bdef6d66a4de7fa216472c4
To make it work again I had to revert this change to bootkube.service and added a check for the directory */etc/crio* before the pause images name will be patched.
I tested that with a local vSphere installation. The pause image is not pulled from the internet, the cluster installation finished without problems (also in an offline environment from …
> [fcos] Prevent crio from pulling the pause image. The crio-configure.service should test if crio already is installed before patching its config.

- data/data/gcp/bootstrap/main.tf
- data/data/gcp/master/main.tf
- pkg/asset/installconfig/clusterid.go
- pkg/asset/machines/gcp/machines.go
- pkg/asset/machines/gcp/machinesets.go
- pkg/destroy/gcp/policybinding.go
- pkg/destroy/gcp/serviceaccount.go
(clean cherry-pick from https://github.com/openshift/installer/pull/3643)
The infra id of the clusters on GCP was reduced to 12 in #2088 because we couldn't handle the hostname seen by rhcos machine to be greater than 64.
More details on this are available in https://bugzilla.redhat.com/show_bug.cgi?id=1809345
now since BZ 1809345 is fixed by openshift/machine-config-operator#1711 and openshift/cluster-api-provider-gcp#88 the installer can relax the restriction on the infra-id to match the other platforms.
Why is it important?
On GCP all resources are prefixed with infra-id, which currently is 12 chars with 6 chars used by random bit, leaving only 6 chars from cluster name. This causes trouble associating the cluster to jobs in CI as most of the identifyable characters are dropped from …
> [release-4.4] Bug 1838885: installconfig: relax GCP cluster id restriction

- images/libvirt/Dockerfile.ci
For s390x/ppc64le we do some amount of yaml manipulation, for example: https://github.com/openshift/release/pull/9362
and we plan to add a volume size which will have increased disk space for certain tests. yq will be especially useful and easier to use than sed for these manipulations.
> Bug 1841913: images: libvirt: add yq to libvirt CI image

- upi/openstack/down-security-groups.yaml
As OpenStack allows resources to have the same name, it's
possible that we end up with multiple security groups with
same name, and the deletion of those resources for UPI fails
as currently we're relying on sg Name. This commit fixes the
issue by ensuring the resoruce ID is used instead.
> Bug 1841072: [UPI] Rely on security group ID when deleting it

- docs/dev/libvirt/README.md
The libvirt installer documentation is recommending a highly insecure configuration of libvirtd, with no auth or encryption, listening on all IP addresses, which gives clients prives equiv to a root shell. It does give some sense of this being an insecure config, but doesn't spell out the full implications to users following the doc. So this adds a much more explicit warning about the risks to fully inform users.
A few other minor improvements were made too.
> Warn about security risks of the recommended libvirt install configuration

- docs/user/openstack/README.md
Before this documentation change, there was no clear indication of the
expected disk latency in the OpenStack requirements.
The threshold value (10ms) is taken from a post[1] on the IBM Cloud blog,
which the official ETCD documentation points to.
[1]: https://www.ibm.com/cloud/blog/using-fio-to-tell-whether-your-storage-is-fast-enough-for-etcd
> openstack: Add numbers to disk requirements

- README.md
I missed this in #3672.
Updates vSphere link to point to IPI and adds link for UPI.
> Bug 1842607: update README with vSphere IPI docs

- cmd/openshift-install/gather.go
- pkg/gather/ssh/agent.go
- pkg/gather/ssh/ssh.go
Before this commit, bootstrap machines that failed to come up would
look like [1]:
```
level=info msg="Waiting up to 30m0s for the Kubernetes API at https://api.ci-op-6266tp8r-77109.origin-ci-int-aws.dev.rhcloud.com:6443..."
level=error msg="Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get https://api.ci-op-6266tp8r-77109.origin-ci-int-aws.dev.rhcloud.com:6443/apis/config.openshift.io/v1/clusteroperators: dial tcp 3.221.214.197:6443: connect: connection refused"
level=info msg="Pulling debug logs from the bootstrap machine"
level=error msg="Attempted to gather debug logs after installation failure: failed to create SSH client, ensure the proper ssh key is in your keyring or specify with --key: dial tcp 3.84.188.207:22: connect: …
```
> cmd/openshift-install/gather: Recognize "connection refused"

- data/data/aws/bootstrap/main.tf
- data/data/aws/bootstrap/variables.tf
- data/data/aws/main.tf
- data/data/aws/variables-aws.tf
- pkg/asset/cluster/tfvars.go
- pkg/asset/installconfig/aws/presign.go
- pkg/tfvars/aws/aws.go
Update the S3 bucket that stores the ignition config to use a presigned URL.
This allows the S3 bucket to be accesseed via HTTP(s) similar to Azure and GCP
thus allowing the installer to pick the correct endpoint based on region/user
specification.
https://issues.redhat.com/browse/CORS-1322
> aws: update the bootstrap ignition fetching to use custom region endpoints

- data/data/bootstrap/systemd/units/crio-configure.service.template
If this service fails, we shouldn't go on and still try to
have crio start which might then use the upstream pause
image.
Came out of looking at https://github.com/openshift/installer/pull/3652
> bootstrap: Make crio-configure.service RequiredBy=crio.service

- cmd/openshift-install/create.go
- cmd/openshift-install/waitfor.go
Looks like I forgot to clean these up when pivoting from destroyBootstrap to waitForBootstrapComplete and removing the only directory consumer in bfc40f87fb (#1393).
> cmd/openshift-install: Drop unused 'directory' arguments

- cmd/openshift-install/create.go
We made improvements in the etcd operator to bring the bootstrap timeout back to 30 minutes.
/hold
holding for proof
> bootstrap: restore 30 minute bootstrap timeout

- upi/aws/cloudformation/02_cluster_infra.yaml
Probes for internal and external endpoints should use "/readyz"
> Bug 1836018: upi/aws/cloudformation: Define healthcheck probes for LBs

- upi/vsphere/README.md
Clarify that a DHCP server is still required at the beginning of the installation to download the ignition files.
The current wording implies that a DHCP server is not required if you set the IPs in the tfvars. This is not the case, and the install will fail because the CoreOS nodes will never pull down the ignition file, because it never gets assigned an IP.
In response to #2552
> upi: update upi/vsphere/README.md

- pkg/types/validation/installconfig.go
If you set `OPENSHIFT_INSTALL_AZURE_EMULATE_SINGLESTACK_IPV6=true` but accidentally pass an IPv4 config, the install will fail with:
```
ERROR                                              
ERROR Error: Insufficient record blocks            
ERROR                                              
ERROR   on  line 0:                                
ERROR   (source code not available)                
ERROR                                              
ERROR At least 1 "record" blocks are required.     
ERROR                                              
ERROR Failed to read tfstate: open /tmp/openshift-install-151306092/terraform.tfstate:
no such file or directory 
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create
cluster: failed to apply using Terraform 
```
If …
> Give a proper error when misusing OPENSHIFT_INSTALL_AZURE_EMULATE_SINGLESTACK_IPV6

- data/data/gcp/main.tf
- data/data/gcp/variables-gcp.tf
- docs/user/gcp/customization.md
- pkg/asset/cluster/tfvars.go
- pkg/tfvars/gcp/gcp.go
- pkg/types/gcp/platform.go
- pkg/types/gcp/validation/platform.go
This is based on the a patch from @cgwalters. I just applied his patch and tweaked a bit the terraform variables file to avoid some errors.
I am not familiar with the project, so I cannot judge whether this implementation is acceptable or not. I can only testify that it does work.
So, this PR should be understood as me volunteering to rework this patch based on the feedback I receive.
Fixes #2649
> Add nested support for GCP

- data/data/azure/vnet/internal-lb.tf
- data/data/azure/vnet/public-lb.tf
- pkg/asset/tls/tls.go
(clean cherry-pick from https://github.com/openshift/installer/pull/3600)
(clean cherry-pick from https://github.com/openshift/installer/pull/3551)
Based on https://tools.ietf.org/html/rfc3280#section-4.2.1.1 and https://tools.ietf.org/html/rfc3280#section-4.2.1.2
We should not set SubjectKeyId to signing certificate value. We should set it to the current certificate value.
replaces https://github.com/openshift/installer/pull/3658 and https://github.com/openshift/installer/pull/3659
/assign e-tienne
> [release-4.3] Bug 1840230: data/azure/vnet: switch to HTTPS probes for lbs

- cmd/openshift-install/create.go
- pkg/asset/store.go
- pkg/asset/store/store.go
- pkg/asset/store/store_test.go
If the cluster is created and the wait-for install-complete command
is called to check the status, the installer checks if the install
config exists to get the platform information to set the timeout for
baremetal clusters a little higher. Since the install config is
consumed during the cluster creation, the installer will then start
to re-generate the install config and ask the user to provide the
information again.
Modified the platform information gathering to only pick the information
up only if the information is available and if it does not exist, set the
timeout value to the maximum value required as default (60 seconds 
as the baremetal machines take long time to boot). This will now 
avoid re-generation of the install config.
> Fix re-generation of install config on wait-for install-complete command

- data/data/openstack/bootstrap/main.tf
- data/data/openstack/bootstrap/variables.tf
- data/data/openstack/main.tf
- data/data/openstack/topology/private-network.tf
- data/data/openstack/topology/variables.tf
- data/data/openstack/variables-openstack.tf
- pkg/asset/cluster/tfvars.go
- pkg/asset/manifests/infrastructure.go
- pkg/tfvars/openstack/openstack.go
- pkg/types/openstack/defaults/platform.go
Depends on https://github.com/openshift/machine-config-operator/pull/1666
> Bug 1841066: OpenStack: Remove DNS VIP

- pkg/types/validation/installconfig_test.go
on go 1.14, the error from url Parse seems to be now quoted compared to previous versions, and therefore the test fails to compare.
```
$ go version
go version go1.14.1 linux/amd64
$ go test ./pkg/types/validation/... -run "^TestValidateInstallConfig/invalid_HTTP"
--- FAIL: TestValidateInstallConfig (0.00s)
--- FAIL: TestValidateInstallConfig/invalid_HTTPProxy (0.00s)
installconfig_test.go:953:
Error Trace:    installconfig_test.go:953
Error:          Expect "HTTPProxy: Invalid value: "http://bad%20uri": parse "http://bad%20uri": invalid URL escape "%20"" to match "^\QHTTPProxy: Invalid value: "http://bad%20uri": parse http://bad%20uri: invalid URL escape "%20"\E$"
Test:           TestValidateInstallConfig/invalid_HTTPProxy
--- FAIL: TestValidateInstallConfig/invalid_HTTPSProxy (0.00s) …
```
> validation/installconfig: fix the test to work with go 1.14

- docs/user/openstack/customization.md
This beefs up the openstack docs for installing with a custom subnet. 
/cc @pierreprinetti @maxwelldb @morenod 
> Bug 1838032: Better docs for using custom subnets

- pkg/asset/installconfig/vsphere/vsphere.go
The vSphere wizard only allows users to select networks of certain types. This commit adds the ability to select OpaqueNetworks.
OpaqueNetwork is what is used in VMC.
So now we allow:
- DistributedVirtualPortgroup
- Network
- OpaqueNetwork
@jcpowermac do you think there might be any other network types we are missing? Also should we continue this process of filtering networks by type?
> Bug 1844103: allow OpaqueNetwork type in vSphere wizard

- data/data/bootstrap/files/usr/local/bin/kubelet-pause-image.sh.template
- data/data/bootstrap/systemd/units/kubelet.service.template
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1823967
Override the --pod-infra-container-image flag to point to the pause
image from the release payload. By default, this flag is set to k8s.gcr.io/pause:3.1
and the kubelet asks the runtime for the image status of this image every few minutes,
which is why we were seeing the warning logs in cri-o saying that this image was not
found. This is avoided by making the pod-infra-container-image flag point to the actual
pause image being used from the release payload.
The MCO PR is https://github.com/openshift/machine-config-operator/pull/1776
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>
> Bug 1823967: Add the --pod-infra-container-image flag to the kubelet service

- data/data/azure/bootstrap/main.tf
- data/data/azure/bootstrap/variables.tf
- data/data/azure/main.tf
- data/data/azure/master/master.tf
- data/data/azure/master/variables.tf
- data/data/azure/variables-azure.tf
- data/data/azure/vnet/outputs.tf
- data/data/azure/vnet/public-lb.tf
- data/data/azure/vnet/variables.tf
- data/data/install.openshift.io_installconfigs.yaml
- docs/user/azure/customization.md
- pkg/asset/cluster/tfvars.go
- pkg/asset/machines/azure/machines.go
- pkg/asset/manifests/openshift.go
- pkg/explain/printer_test.go
- pkg/tfvars/azure/azure.go
- pkg/types/azure/defaults/platform.go
- pkg/types/azure/defaults/platform_test.go
- pkg/types/azure/platform.go
- pkg/types/azure/validation/platform.go
- pkg/types/azure/validation/platform_test.go
enhancement: https://github.com/openshift/enhancements/pull/338
xref: https://issues.redhat.com/browse/CORS-1365
Similar to [AKS outbound type][3]
OutboundType is a strategy for how egress from cluster is achieved
Currently 2 strategies are:
- loadbalancer (default)
this uses the standard load balancer pointing to the control plane and compute nodes to provide egress based on [Azure Outbound for private machines behind standard LB][1]
for internal cluster, this means an public lb will be used to provide egress, i.e. even though all the endpoints of the cluster are internal and only accessible to the virtual network, there exists a public lb with public ip that provides the egress for the cluster
- user defined routing
this allows the user to configure the routing of the virtual network on …
> azure: add OutboundType for controlling egress

- upi/azure/03_infra.json
This changes the load balancer probes ARM template health check from a TCP port to a standardized endpoint using https.
> Bug 1836016: use https for lb probes in Azure UPI

- data/data/baremetal/main.tf
terraform-provider-ironic [recently changed the approach it uses for
timeouts](https://github.com/openshift-metal3/terraform-provider-ironic/pull/41) from an estimate based on number of attempts, to using a
go routine in a context. The logic it used to estimate was off by more
than a factor of two. That means the current 1500 second timeout was
actually more than 3000.
This commit restores the previously unintended behavior as now
explicitly set. The latest RHCOS images are around 800 MB in size. At
256kB/s, this would be 3,125 seconds to download. We also have to allow
time for the bootstrap VM itself to boot, which we could alot 5 minutes
for, totaling 3,425 seconds. I round it up to 3600 just for the even
number.
This timeout is unfortunate but I think is required for users who …
> Bug 1843314: baremetal: bump ironic timeout to 3600 seconds

- data/data/openstack/topology/private-network.tf
The api_fip should have an explicit dependency on the
nodes_router_interface otherwise it may fail with:
Error: Error associating openstack_networking_floatingip_associate_v2 floating_ip xxx with port xxx: Resource not found
> Bug 1734460: OpenStack: Wait for router interface to create FIP

- .github/ISSUE_TEMPLATE.md
As nearly all supported platforms now document some UPI process, we want
the issue reporter to clearly state what platform UPI is being deployed
onto.
> ISSUE_TEMPLATE.md: Specify the platform for UPI

- pkg/asset/installconfig/ovirt/credentials.go
Avoid error of:
"must pass a pointer as the target of a Write operation"
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1846366
> Bug 1846366: ovirt: use pointer instead of struct for user/pass

- pkg/destroy/gcp/cloudcontroller.go
- pkg/destroy/gcp/gcp.go
- pkg/destroy/gcp/instance.go
- pkg/destroy/gcp/instancegroup.go
The uninstaller currently hard codes the base path as the GCP
API base path has changed.
Change 1:
For the getZoneName function, the InstanceGroupAggregatedList,
InstanceAggregatedList and the disk list functions that calls
this to get the proper url all have a shortened URL as the key
in the list.Items map. Example of a shortened URL is
zones/us-central1-a.
Reusing the key value instead of hard coding the base path
and TrimLeft operation.
Change 2:
For the getInstanceGroupURL function, the call to the underlying
InstanceGroupAggregatedList to get the InstanceGroups already have
the URL to hit called the SelfLink which is now set to the returning
object and used for the URL, thus not requiring the call.
Change 3:
For the getInstanceNameAndZone, since the underlying object has only
the URL …
> GCP: Fix uninstaller to not use hardcoded base path.

- docs/user/gcp/install_upi.md
- upi/gcp/05_control_plane.py
This mirrors changes to GCP IPI in #3544
The infra id of the clusters on GCP was reduced to 12 in #2088 because
we couldn't handle the hostname seen by rhcos machine to be greater than
64.
More details on this are available in
https://bugzilla.redhat.com/show_bug.cgi?id=1809345
now since BZ 1809345 is fixed by openshift/machine-config-operator#1711
and openshift/cluster-api-provider-gcp#88 the installer can relax the
restriction on the infra-id to match the other platforms.
Why is it important?
On GCP all resources are prefixed with infra-id, which currently is 12
chars with 6 chars used by random bit, leaving only 6 chars from cluster
name. This causes trouble associating the cluster to jobs in CI as most
of the identifyable characters are dropped from the resource names in CI
due to …
> GCP UPI: relax cluster name

- docs/user/vsphere/install_upi.md
vSphere UPI docs should take into account that the cloud-provider-config
manifest specifies the folder with the name of cluster id.
> vSphere docs: update UPI docs for folder name

- docs/dev/libvirt/README.md
* Update libvirt setup instructions to clearly separate the systemd activated version from the classic one.
* Update firewalld setup to take into account recent libvirt integration.
* Also include some minor Markdown styling fixes.
> docs/dev/libvirt: update libvirt/firewalld setup instructions

- docs/user/openstack/install_upi.md
- upi/openstack/common.yaml
- upi/openstack/down-containers.yaml
Add a `down-` playbook to the OpenStack UPI documentation to delete any
remaining Swift container named after the cluster.
> Bug 1846296: openstack UPI: prune containers

- pkg/destroy/gcp/cloudcontroller.go
- pkg/destroy/gcp/instancegroup.go
Fixed the GCP uninstaller to get the instance group self links which
would be used to destroy them. Currently, the self links are used but
are not requested from GCP as a field when the instance groups are listed.
Therefore, the uninstaller does not get the appropriate link to target
for deletion. This fix is for the internal clusters uninstallation.
> gcp: Fix uninstaller for internal clusters on GCP.

- pkg/destroy/aws/aws.go
The `RunWithContext` method was added to the AWS uninstaller. This provides a way for the user to supply a context that can be used to stop the uninstall.
This will be used by Hive to backoff uninstall attempts.
https://issues.redhat.com/browse/CO-973
> destroy: provide way to stop aws uninstall using context

- pkg/asset/cluster/tfvars.go
- pkg/asset/installconfig/azure/azure.go
- pkg/asset/installconfig/azure/client.go
- pkg/asset/installconfig/azure/dns.go
- pkg/asset/installconfig/azure/metadata.go
- pkg/asset/installconfig/azure/validation.go
- pkg/asset/installconfig/basedomain.go
- pkg/asset/installconfig/installconfig.go
- pkg/asset/installconfig/platformcredscheck.go
- pkg/asset/installconfig/platformprovisioncheck.go
- pkg/asset/machines/azure/zones.go
- pkg/asset/machines/master.go
- pkg/asset/machines/worker.go
- pkg/asset/manifests/cloudproviderconfig.go
- pkg/asset/manifests/dns.go
- pkg/asset/manifests/openshift.go
This commit creates an Azure metadata struct in the installconfig asset
(similar to AWS) and stores an Azure session and clients for interacting
with the Azure API. This commit also refactors existing code to use
this functionality rather than plumbing the install config values repeatedly.
> pkg/asset/installconfig/azure: create reusable session

- data/data/azure/vnet/public-lb.tf
Using a dummy inbound rule can easily be replaced with an outbound rule that serves the exact purpose of egress traffic.
this also solves the issue where the installer and k8s are trying to create lb_rule for the same port.
```
2020-06-17T01:48:36.741071573Z E0617 01:48:36.741045       1 azure_loadbalancer.go:159] reconcileLoadBalancer(openshift-config-managed/outbound-provider) failed: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: {
2020-06-17T01:48:36.741071573Z   "error": {
2020-06-17T01:48:36.741071573Z     "code": "RulesUseSameBackendPortProtocolAndPool",
2020-06-17T01:48:36.741071573Z     "message": "Load balancing rules /subscriptions/53b8f551-f0fc-4bea-8cba-6d1fefd54c8a/resourceGroups/esstest03-2hn2 …
```
> Bug 1848106: data/azure: use outbound_rule instead of dummy inbound lb_rule

- data/data/rhcos-amd64.json
- data/data/rhcos.json
There's a whole lot going on in 4.6, among the changes are the
Live ISO, RHEL 8.2 (so far), new static networking handling etc.
Among all that, also we are currently pivoting from 4.5 w/RHEL 8.1
which causes
https://bugzilla.redhat.com/show_bug.cgi?id=1847705
> Bug 1847705: rhcos: Bump to 46.82.202006162207-0

- data/data/rhcos-amd64.json
- data/data/rhcos.json
Promoted here:
https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/logs/promote-release-openshift-machine-os-content-e2e-aws-4.5/1273982585365598208
This gets the bootimage to RHEL 8.2, among other things.
> Bug 1849150: rhcos/amd64: Bump to 45.82.202006191325-0

- data/data/openstack/masters/main.tf
- upi/vsphere/lb/main.tf
- upi/vsphere/vm/ignition.tf
openstack masters are using Ignition provider to generate Ignition file, so it needs to be ported to Ignition spec 3.
Fixes https://github.com/openshift/okd/issues/127
> [FCOS] Use Ignition spec 3 in openstack terraform

- data/data/rhcos-amd64.json
- data/data/rhcos.json
The `machine-os-content` has been promoted. This pulls in a few packages which were not present in the plashets previously.
cc @dustymabe @sohankunkerkar @sdodson @miabbott @imcleod 
```
"diff": {
"coreos-installer": {
"rhcos-4.5/45.82.202006191325-0": "coreos-installer-0-2.rhaos4.4.gite5aa5dc.el8.noarch",
"rhcos-4.5/45.82.202006230709-0": "coreos-installer-0-3.rhaos4.5.gite5aa5dc.el8.noarch"
},
"coreos-installer-dracut": {
"rhcos-4.5/45.82.202006191325-0": "coreos-installer-dracut-0-2.rhaos4.4.gite5aa5dc.el8.noarch",
"rhcos-4.5/45.82.202006230709-0": "coreos-installer-dracut-0-3.rhaos4.5.gite5aa5dc.el8.noarch"
},
"cri-o": {
"rhcos-4.5/45.82.202006191325-0": "cri-o-1.18.1-13.dev.rhaos4.5.git6d00f64.el8.x86_64",
"rhcos-4.5/45.82.202006230709-0": …
```
> rhcos/amd64: Bump to 45.82.202006230709-0

- data/data/libvirt/main.tf
- data/data/libvirt/variables-libvirt.tf
- pkg/tfvars/libvirt/libvirt.go
With this patch user can specify the volume size of master node using the machine config.
```
$ openshift-install create manifests --dir mydir
$ yq write --inplace mydir/openshift/99_openshift-cluster-api_master-machines-0.yaml spec.providerSpec.value.volume[volumeSize] 32212254720
$ openshift-install create cluster --dir mydir
```
> Libvirt: Make master disk size configurable

- data/data/openstack/topology/private-network.tf
This is a cherry-pick of https://github.com/openshift/installer/pull/3780
The api_fip should have an explicit dependency on the
nodes_router_interface otherwise it may fail with:
Error: Error associating openstack_networking_floatingip_associate_v2
floating_ip xxx with port xxx: Resource not found
/assign mandre
> Bug 1850940: OpenStack: Wait for router to create FIP

- data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
coreos-downloader usually takes longer, starting it sooner should
allow it to start doing its thing while the ipa-downloader image
is being retrieved.
> baremetal: Start coreos-downloader before ipa-downloader

- docs/design/openstack/networking-infrastructure.md
We're removed the DNS VIP from the picture [1][2], however we forgot to
update the docs.
[1] https://github.com/openshift/machine-config-operator/pull/1666
[2] https://github.com/openshift/installer/pull/3492
> Docs: DNS VIP no longer exists

- pkg/destroy/gcp/address.go
- pkg/destroy/gcp/backendservice.go
- pkg/destroy/gcp/bucket.go
- pkg/destroy/gcp/disk.go
- pkg/destroy/gcp/errortracker.go
- pkg/destroy/gcp/firewall.go
- pkg/destroy/gcp/forwardingrule.go
- pkg/destroy/gcp/gcp.go
- pkg/destroy/gcp/healthcheck.go
- pkg/destroy/gcp/httphealthcheck.go
- pkg/destroy/gcp/image.go
- pkg/destroy/gcp/instance.go
- pkg/destroy/gcp/instancegroup.go
- pkg/destroy/gcp/network.go
- pkg/destroy/gcp/policybinding.go
- pkg/destroy/gcp/route.go
- pkg/destroy/gcp/router.go
- pkg/destroy/gcp/serviceaccount.go
- pkg/destroy/gcp/subnetwork.go
- pkg/destroy/gcp/targetpool.go
This change will allow errors to become visible to users using log-level
of warn or higher. It continues to log errors encountered while deleting
cloud resources as DEBUG while escalating the errors to WARN once every
5 minutes.
> destroy/gcp: bubble up errors after 5 minutes

- upi/azure/05_masters.json
Adjust Azure UPI to use a 1024 GB disk size by default, which is currently the default in IPI and the recommended size for better IOPS performance.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1850714
> Bug 1850714: adjust Azure UPI disk size to the same used in IPI

- data/data/rhcos-ppc64le.json
- data/data/rhcos-s390x.json
Keep in sync with x86_64 to pull in the new machine-os-content and other changes
> Bug 1851069: rhcos/ppc64le, s390x: Bump to 45.82.202006240558-0 and 45.82.202006240257-0

- cmd/openshift-install/create.go
- pkg/asset/logging/filelogging.go
- pkg/asset/logging/filelogging_test.go
Added a feature where the directories of the assets that were
used during any target of the create command is invoked, are
displayed on the screen. Examples of the display that will show
up are
'''
INFO install-config created in the test directory
INFO manifests created in the test/manifests and test/openshift directories
INFO ignition-configs created in the test and test/auth directories
'''
> create cmd: Display command asset directories.

- go.mod
- go.sum
- vendor/github.com/ovirt/go-ovirt/connection.go
- vendor/github.com/ovirt/go-ovirt/reader.go
- vendor/modules.txt
Solve an issue related to RHV network parsing
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1838559
> Bug 1838559: Bump go-ovirt

- upi/vsphere/ipam/cidr_to_ip.sh
> upi/vsphere: Make cidr_to_ip.sh more verbose

- data/data/manifests/bootkube/cvo-overrides.yaml.template
OKD doesn't use "stable-4.x" schema for channels, so it should be
`stable-4` on fresh installs
> [FCOS] cvo-overrides.yaml: update default channel

- pkg/asset/installconfig/gcp/client.go
- pkg/asset/installconfig/gcp/mock/gcpclient_generated.go
- pkg/asset/installconfig/gcp/validation.go
- pkg/asset/installconfig/gcp/validation_test.go
- pkg/asset/installconfig/platformpermscheck.go
xref: https://issues.redhat.com/browse/CORS-1254
1. To verify the list of services that are enabled before a cluster is installed we are making a call to 
https://serviceusage.googleapis.com/v1/{parent=*/*}/services via the gcp client.go. 
The link to the documentaion is [here](https://cloud.google.com/service-usage/docs/reference/rest/v1/services/list)
2. In platformpermscheck.go we get the list of services and check if all the required services are enabled , else it returns an error.
3. The gcp validation.go checks for the list of services code.
> gcp: verify project services are enabled before install

- docs/user/metal/install_ipi.md
- pkg/tfvars/baremetal/baremetal.go
- pkg/types/baremetal/platform.go
- vendor/github.com/metal3-io/baremetal-operator/pkg/provisioner/ironic/devicehints/devicehints.go
- vendor/modules.txt
Hardware profiles don't allow for all of the use cases
required in some baremetal environments, allow the
boot hints associated with them to be overridden.
e.g. to specifiy a device by serial number
```
- name: openshift-master-0
rootDeviceHints:
serialNumber: 1111
```
> baremetal: Allow rootDeviceHints to override Host profiles

- data/data/manifests/bootkube/cvo-overrides.yaml.template
Update CVO upstream setting from OCP Cincinnati to OKD's release-controller.
Fixes https://github.com/openshift/okd/issues/241
> [fcos] cvo-overrides.yaml: update upstream URL

- data/data/install.openshift.io_installconfigs.yaml
- docs/dev/dependencies.md
- go.mod
- hack/build.sh
- hack/go-fmt.sh
- hack/go-lint.sh
- hack/go-sec.sh
- hack/go-test.sh
- hack/go-vet.sh
- hack/verify-codegen.sh
- hack/verify-vendor.sh
- images/baremetal/Dockerfile.ci
- images/installer-artifacts/Dockerfile.rhel
- images/installer/Dockerfile.ci
- images/installer/Dockerfile.ci.rhel7
- images/installer/Dockerfile.upi.ci
- images/libvirt/Dockerfile.ci
- images/mock/Dockerfile
- images/openstack/Dockerfile.ci
- vendor/modules.txt
With Go 1.14 the handling of modules has improved in the sense that all the subcommands `go {test, generate}` now use the vendor when available by default. This makes it easier for us to run generate using the vendored tools like controller-tools etc. as it now uses the checked in vendor.
> bump the minimum version for building installer to go 1.14

- data/data/manifests/bootkube/cvo-overrides.yaml.template
Like 9cd119dfa9 (#3287), but for 4.6 (now that release-4.5 is no longer being fast-forwarded to track master).
> Bug 1850417: data/manifests/bootkube/cvo-overrides: Bump default to stable-4.6

- data/data/rhcos-amd64.json
- data/data/rhcos.json
```
"diff": {
"cri-o": {
"rhcos-4.5/45.82.202006230709-0": "cri-o-1.18.2-15.dev.rhaos4.5.git7c4494f.el8.x86_64",
"rhcos-4.5/45.82.202007062333-0": "cri-o-1.18.2-18.rhaos4.5.git754d46b.el8.x86_64"
},
"kernel": {
"rhcos-4.5/45.82.202006230709-0": "kernel-4.18.0-193.9.1.el8_2.x86_64",
"rhcos-4.5/45.82.202007062333-0": "kernel-4.18.0-193.12.1.el8_2.x86_64"
},
"kernel-core": {
"rhcos-4.5/45.82.202006230709-0": "kernel-core-4.18.0-193.9.1.el8_2.x86_64",
"rhcos-4.5/45.82.202007062333-0": "kernel-core-4.18.0-193.12.1.el8_2.x86_64"
},
"kernel-devel": {
"rhcos-4.5/45.82.202006230709-0": "kernel-devel-4.18.0-193.9.1.el8_2.x86_64",
"rhcos-4.5/45.82.202007062333-0": "kernel-devel-4.18.0-193.12.1.el8_2.x86_64"
},
"kernel-headers": {
"rhcos-4.5/45.82.202006230709-0": …
```
> Bug 1854222: rhcos/amd64: Bump to 45.82.202007062333-0

- pkg/asset/installconfig/ovirt/credentials.go
Commit 235492ffb7 missed to populate ca
bundle in ovirt-config.yaml which can make installation
not complete.
> ovirt: populate again ovirt ca bundle in yaml

- data/data/rhcos-amd64.json
- data/data/rhcos.json
This brings in at least https://github.com/coreos/fedora-coreos-config/pull/499
for the Live ISO, and we want those fixes for all of the work
happening on top of the Live ISO like the assisted installer, etc.
> rhcos: Bump to 46.82.202007051540-0

- platformtests/README.md
The guts were removed by 805a108ba7 (#3277), citing d45e881abe (#3051).  No need to keep the useless directory around now that it holds no code.
> platformtests: Drop no-longer-used directory

- docs/user/aws/limits.md
- pkg/asset/machines/master_test.go
- pkg/asset/machines/worker_test.go
- pkg/types/aws/defaults/platform.go
- upi/aws/cloudformation/05_cluster_master_nodes.yaml
- upi/aws/cloudformation/06_cluster_worker_node.yaml
Changes default AWS instance type from m4 to m5.
Fixes #2919.
> Bug 1710981: Default AWS instance type to 'm5'

- data/data/bootstrap/files/usr/local/bin/release-image-download.sh.template
- data/data/bootstrap/gcp/files/opt/libexec/openshift-gcp-routes.sh
- data/data/bootstrap/systemd/units/openshift-gcp-routes.service
Temporary solution for OKD installer 4.5 - include gcp-routes.sh script and service in installer, so that the bootstrap node would be a part of api/api-int lbs.
In 4.6 we'll push for Afterburn / NM to set these up on all nodes.
Verified that this change to installer allows deploying OKD clusters on GCP
> [FCOS] data/data/bootstrap/gcp: install openshift-gcp-routes on bootstrap node

- docs/user/metal/install_ipi.md
> Remove metal todo for install gather support

- go.mod
- go.sum
- vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/access.go
- vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/ibmc.go
- vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/idrac.go
- vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/ipmi.go
- vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/irmc.go
- vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/redfish.go
- vendor/modules.txt
This commit updates baremetal-operator to include support for using
`redfish-virtualmedia+http` baseboard management controllers URI's.
Previously, baremetal operator didn't recognize that format of BMC
despite being a valid construction.
> vendor: update baremetal-operator for virtual media support

- data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
There is a new --release-image flag in MCO bootstrap
which is used to get the release-image being used from
the installer. This will help in validating the list of
blocked registries with day 1 support for Image CR and
registries.conf.
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>
> Pass down release-image to the MCO on bootstrap

- pkg/asset/installconfig/vsphere/vsphere.go
- pkg/types/vsphere/validation/platform.go
- pkg/types/vsphere/validation/platform_test.go
With the current setup, it is possible for the user to enter the
same IP address for the ingress and the API for vsphere. Creating
a cluster with these settings results in Bootstrap and one of the
masters being assigned the same IP address during installation.
Added a validation to check if the given input for the Ingress is
not the same as API whose input would have been specified first
and throw an error if they are the same, prompting the user to
re-enter the IP address again.
> Bug 1853859: Add validations for IP inputs

- docs/user/metal/customization_ipi.md
- pkg/types/baremetal/defaults/platform.go
- pkg/types/baremetal/defaults/platform_test.go
The default only allowed for 90 hosts, increasing it removes the
likelihood large deploys will hit deploy errors.
> Bug 1841135: baremetal: increase default provisioning dhcp range

- data/data/install.openshift.io_installconfigs.yaml
- data/data/openstack/topology/variables.tf
- data/data/openstack/variables-openstack.tf
- docs/user/openstack/customization.md
- docs/user/openstack/kuryr.md
- pkg/asset/cluster/tfvars.go
- pkg/asset/installconfig/openstack/openstack.go
- pkg/asset/installconfig/openstack/realvalidvaluesfetcher.go
- pkg/asset/machines/openstack/machines.go
- pkg/asset/machines/openstack/machinesets.go
- pkg/tfvars/openstack/openstack.go
- pkg/types/openstack/platform.go
- pkg/types/openstack/validation/mock/validvaluesfetcher_generated.go
- pkg/types/openstack/validation/platform.go
- pkg/types/openstack/validation/platform_test.go
- pkg/types/openstack/validation/validvaluesfetcher.go
- pkg/types/validation/installconfig_test.go
Despite the fact these two values can be set by the user, they are overwritten by the installer every time in two places.
First time during config validation:
https://github.com/openshift/installer/blob/release-4.4/pkg/types/openstack/validation/platform.go#L35-L52
And the second time in the installconfig asset:
https://github.com/openshift/installer/blob/release-4.4/pkg/asset/installconfig/openstack/openstack.go#L128-L151
Every time all possible errors are ignored, which leads to an unpredictable behavior, when depending on the quality of the network connection, we may get different results.
Then these values are passed to terraform.
This PR deprecates these parameters in the install config, since users can't define them anyway.
Also, from now the values will be fetched from `tvfars` …
> OpenStack: Deprecate TrunkSupport and OctaviaSupport in the config 

- pkg/asset/installconfig/baremetal/OWNERS
- pkg/asset/installconfig/baremetal/validation.go
- pkg/asset/installconfig/platformprovisioncheck.go
- pkg/types/baremetal/validation/libvirt.go
- pkg/types/baremetal/validation/platform.go
- pkg/types/baremetal/validation/platform_test.go
This PR re-arranges all provisioning network validations until the `create` target. This enables end users to run other targets such as `ignition-configs`, `manifests` without specifying any config related to the provisioning network.
This is an implementation of [openshift/enhancements#388](https://github.com/openshift/enhancements/pull/388).
Co-Authored-By: @andfasano
> Baremetal: Re-arrange validations for provisioning network at cluster creation time

- data/data/openstack/variables-openstack.tf
Now if there is no support for octavia or trunks we don't pass `false` values to terraform. It leads to the fact that the terraform variables remain undefined.
To prevent this we should set default values to `false` for the variables.
> [OpenStack] Set default values for octavia and trunk support tf vars

- pkg/asset/installconfig/openstack/realvalidvaluesfetcher.go
Now we use modified cloud loaders from the credentials checker in realValidValuesFetcher. But they are useless there, because the only one difference from the standard ones is that they print clouds.yaml location to the log.
This commit starts using the default loaders from gophercloud utils.
> OpenStack: stop using custom cloud loaders for realValidValuesFetcher

- pkg/types/openstack/validation/platform.go
Due to a high number of if statements, it is fairly difficult to trace what is happening in the platform validations. This change aims to make the high level workflow very clear by grouping checks for the same component or feature together into helper functions.
/cc @Fedosin @mandre
> clean up the validations to improve readability and high level flow

- data/data/rhcos-amd64.json
- data/data/rhcos.json
This contains the fixed RHEL 8.2 kernel that allows RHCOS to boot when
Secure Boot is enabled.
Used:
`$ hack/update-rhcos-bootimage.py https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.5/45.82.202007141718-0/x86_64/meta.json amd64`
> Bug 1856820: update boot images for RHCOS Secure Boot issue

- OWNERS_ALIASES
We have more developers working day by day to make OCP on oVirt
a great product. This patch update the list of approvers with
people that have at least some contributions related to both
projects.
> ovirt: update approvers list

- data/data/ovirt/bootstrap/main.tf
- data/data/ovirt/bootstrap/variables.tf
- data/data/ovirt/main.tf
- data/data/ovirt/template/outputs.tf
- data/data/ovirt/template/variables.tf
- data/data/ovirt/variables-ovirt.tf
- pkg/destroy/ovirt/destroyer.go
Currently, tmp/bootstrap VMs are not removed when destroy
command is called. This patch creates a ${tagname}-bootstrap
for tmp/bootstrap VMs.
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1806471
> ovirt: tag and remove tmp/bootstrap machines

- data/data/azure/main.tf
- pkg/tfvars/azure/azure.go
FCOS image is not yet available in the marketplace, so it needs to be downloaded by the installer
Cherry-pick of #3563 on `fcos` branch after it was wiped by the rebase.
/cc @LorbusChris 
@jomeier once you got a minute could you check that is the only change we need to restore Azure support?
> [FCOS] Download Azure image in the installer

- pkg/destroy/ovirt/destroyer.go
The destroy cluster command do not remove the template created during the OCP 
deploy due incorrect search criteria. It keeps consuming resource from oVirt.
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1855501
> ovirt: remove template from the deploy

- pkg/destroy/openstack/openstack.go
During deletion of containers we get a list of available containers first, and then we iterate through them to find the ones we need,
based on their metadata.
Since this is not an atomic operation, it may happen that the containers can be removed at runtime. We should ignore these cases and continue to iterate through the remaining ones.
> Bug 1857188: OpenStack: skip container deletion if it was removed

- docs/user/gcp/install_upi.md
The consuming script has not been changed since it landed in cbe6f1549d (#2117).
The associated Markdown landed with a 'region' in the docs and YAML in cbe6f1549d.  It was removed from the YAML in 998a518a17 (#2574), but not the surrounding Markdown (until this commit).
Parallel openshift-docs fix in flight with openshift/openshift-docs#23500.
> docs/user/gcp/install_upi: Drop unused 'region' from compute

- pkg/asset/machines/vsphere/machines.go
In vsphere IPI installations, the VCenter can have multiple data centers and clusters. 
When a new cluster is created, the machine-api operator fails to find a default resource
pool because there are multiple resource pools.
This will specify the exact path to reference the resources which will
remove this ambiguity and will not cause failure in the installation
process.
> Bug 1852545: Add ResourcePoolPath to machines in vsphere

- data/data/openstack/bootstrap/main.tf
- data/data/openstack/masters/main.tf
- pkg/asset/machines/openstack/machines.go
- pkg/destroy/openstack/openstack.go
Now to delete servers we first get a list of all available servers from Nova, and then we iterate through them to find those with required metadata. In the case of a large number of servers, this can take a very long time.
Fortunately gophercloud introduced filtering by tags, so we can start using this feature to get only servers with the required tag.
https://github.com/gophercloud/gophercloud/pull/1759
> OpenStack: Deleting servers using tag-based filtering

- pkg/types/gcp/validation/platform.go
This change adds the following regions to GCP:
- asia-northeast3
- asia-southeast2
- us-west3
- us-west4
> Bug 1847549: gcp - add new regions in us-west, asia-northeast, and asia-southeast

- data/data/ovirt/template/outputs.tf
PR https://github.com/openshift/installer/pull/3868 added the tmp vm as an output variable. This causes the installer to fail when that resource is not created i.e when we don't let the installer create the template, as we do on CI.
This caused all 4.6 and master PR to be red and fail before starting the installation.
We need to fix and add a condition to set the var only when the resource is created
> Bug 1857651: oVirt, add condition for non existing tmp-vm

- data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
If startironic.sh is run multiple times we need to remove the
DHCP chain before creating it again.
Also rename it to DHCP_IRONIC to reduce the chances of removing
a legitimate iptables rule.
> baremetal: Remove any references to the DHCP chain

- pkg/asset/cluster/ovirt/ovirt.go
We want to remove the cluster template and the VM associated with it
when the overriding variable is not set, meaning when the installer
creates the cluster template.
If the override env variable is set then an existing template is used
on the installation and we don't want to remove it
> Bug 1857650: oVirt, fix incorrect template removal condition

- pkg/asset/installconfig/ovirt/credentials.go
After changing the template for the ovirt user password question,
we need to reset the template to avoid survey to use it for other
password questions like (Pull-secret)
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1857762
> Need to reset PasswordQuestionTemplate

- pkg/asset/installconfig/ovirt/credentials.go
Before ask users questions like: user/pass we should
validate that host AND PKI URL from engine are both
reachable.
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1848885
> Bug 1848885: check if 404 returned before ask users questions

- pkg/asset/machines/baremetal/machines.go
Currently, we're not setting Kind or APIVersion in the baremetal
provider config, which is causing problems when recent code added to the
installer tries to unmarshal these resources.
Fixes https://github.com/openshift/installer/issues/3906
> baremetal: populate TypeMeta for baremetal provider config

- pkg/types/validation/installconfig.go
- pkg/types/validation/installconfig_test.go
While tracking down a 4.4 IPv6 bug we realized that OVN only supports dynamic address assignment on /64 networks on IPv6. (Standard IPv6 automatic address assignment also requires this, and DHCPv6 mostly does as well, so it's not a strange requirement.)
We'll need to propagate this requirement to a few other places, and decide if it should be ovn-kubernetes-specific or apply to all IPv6-supporting network plugins. But for now, OCP only supports IPv6 with HostPrefix=64, so enforce that in the installer.
/cc @smarterclayton @russellb
> validation: OVN requires a HostPrefix of 64 for IPv6 networks

- images/baremetal/Dockerfile.ci
- images/installer/Dockerfile.ci
- images/openstack/Dockerfile.ci
This enables us to simplify CI configuration, so that it would import less images
> [fcos] images: use 4.5 as a base

- pkg/asset/installconfig/openstack/validation/validation.go
The recent validations refactoring [1] caused the installer to panic with
nil pointer deference when running with an install-config.yaml where the
`controlPlane.platform.openstack` struct was unset.
This wasn't caught in CI since we do set the struct.
[1] https://github.com/openshift/installer/pull/3864
> OpenStack: fix runtime error with machine pool validation

- data/data/install.openshift.io_installconfigs.yaml
- data/data/openstack/main.tf
- data/data/openstack/topology/private-network.tf
- data/data/openstack/topology/variables.tf
- data/data/openstack/variables-openstack.tf
- pkg/asset/cluster/tfvars.go
- pkg/tfvars/openstack/openstack.go
- pkg/types/openstack/platform.go
Customers have requested a more consistent experience for floating IPs in the installer, with a preference for how the loadbalancer FIP is implemented. To support this, we created an option for passing a floating ip for the ingress port that is identical in usage to the loadbalancer/api port implementation.
> Option to pass floating IP to ingress port

- pkg/asset/installconfig/ovirt/ovirt.go
If users press ctrl c in the middle of questionary
process or an error happens it will save whatever users
have provided in the ovirt-config.yaml which can be incomplete and
prevent users to trigger a new installation asking a fresh
round of questions about their env.
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1857924
Signed-off-by: Douglas Schilling Landgraf <dougsland@gmail.com>
> Bug 1857924: ovirt: remove defer ovirtConfig.Save()

- pkg/asset/machines/worker.go
Otherwise when loading the worker machinesets we get error like
```
unmarshal worker 0: no kind "VSphereMachineProviderSpec" is registered for version "vsphereprovider.openshift.io/v1beta1" in scheme
```
/cc @patrickdillon 
/assign @patrickdillon
> Bug 1858705: assets/machines/worker.go: add vsphere provider scheme to load machinsets

- data/data/install.openshift.io_installconfigs.yaml
- data/data/openstack/bootstrap/main.tf
- data/data/openstack/bootstrap/variables.tf
- data/data/openstack/topology/private-network.tf
- docs/user/openstack/customization.md
- pkg/asset/installconfig/openstack/openstack.go
- pkg/asset/installconfig/openstack/validation/cloudinfo.go
- pkg/terraform/gather/openstack/ip.go
- pkg/types/openstack/platform.go
Removes floating ip binding from bootstrap server
if external network is not used
> OpenStack: Make externalnetwork and lbfloating ip optional

- pkg/asset/installconfig/ovirt/credentials.go
Today if the installer cannot download the CA from Engine
it will continue without enabling TLS verify (connection Insecure).
Instead of warning only, let's make sure users agree with that.
Bug-URL: https://bugzilla.redhat.com/show_bug.cgi?id=1857945
> Bug 1857945: ovirt: if TLS verify is disable raise a question to users

- upi/ovirt/OWNERS
- upi/ovirt/README.md
This PR is setting the initial README file and the ownership of the oVirt upi folder
> oVirt UPI: initial setup

- data/data/openstack/topology/sg-master.tf
- data/data/openstack/topology/sg-worker.tf
Terraform-provider-openstack suffered from a race condition that would
lead to conflicts in neutron and forced us to create security group
sequentially (via an explicit dependency on the previous rule) to
prevent failures. This is no longer the case in
terraform-provider-openstack v1.28.0 where this issue was fixed with
[1].
With the recent bump of terraform-provider-openstack to v1.28.0, we can
now remove the workaround.
This reverts commit 228aadf9ebde1b60490bff19511de49d6350008f.
[1] https://github.com/terraform-providers/terraform-provider-openstack/pull/994
> OpenStack: Create SG rules in parallel

- data/data/bootstrap/files/usr/local/bin/release-image-download.sh.template
MCD since release-4.6 doesn't reboot automatically, so during bootstrap
pivot it needs to happen manually.
See https://github.com/openshift/machine-config-operator/pull/1809
> [FCOS] bootstrap: reboot manually after pivot

- pkg/asset/machines/baremetal/hosts.go
This PR ensures that BMC secret is referenced in the hosts asset only when BMC credentials are specified. If not, the secret is not referenced.
> baremetal: Only set BMC secret reference in Hosts when BMC details are specified

- data/data/bootstrap/files/usr/local/bin/installer-gather.sh
- data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh
Signed-off-by: Andrew Beekhof <andrew@beekhof.net>
> Masters-gather: Include the full logs of failed units

- upi/ovirt/README.md
- upi/ovirt/bootstrap.yml
- upi/ovirt/common-auth.yml
- upi/ovirt/create-templates-and-vms.yml
- upi/ovirt/inventory.yml
- upi/ovirt/masters.yml
- upi/ovirt/retire-bootstrap.yml
- upi/ovirt/retire-masters.yml
- upi/ovirt/retire-workers.yml
- upi/ovirt/workers.yml
Basic set of Ansible playbooks to reach the minimum cluster installation on ovirt/RHV
Depends on: #3771 
https://issues.redhat.com/browse/OCPRHV-279
Enhancement: https://github.com/openshift/enhancements/pull/326
> Ovirt upi basic installation

- data/data/install.openshift.io_installconfigs.yaml
- pkg/asset/installconfig/platformpermscheck.go
- pkg/explain/printer_test.go
- pkg/types/installconfig.go
- pkg/types/validation/installconfig.go
- pkg/types/validation/installconfig_test.go
Add the cloudCredentialsMode field to InstallConfig. When set, the installer will not perform any permissions checks on the cloud
credentials. The cloud-credential-operator render command will look at the installconfig to render the manifests appropriately.
See https://github.com/openshift/enhancements/blob/master/enhancements/installer/aws-permissions-check-bypass.md
https://issues.redhat.com/browse/CO-1057
> types: add field to InstallConfig to force credentials mode

- data/data/bootstrap/baremetal/files/usr/local/bin/master-bmh-update.sh
- pkg/asset/machines/baremetal/hosts.go
We add HardwareDetails to a BareMetalHost resource by including them in
initial Status data that is attached to the Host as an annotation. This
annotation must be present before the BareMetalHost is first reconciled
(thus creating the Status subresource), otherwise it will be ignored.
It is not possible to add the annotation at the time the BareMetalHost
is created. Therefore, we were previously relying on it being added
before the baremetal-operator is up and running. In practice this works
because the baremetal-operator takes a long time to start up, but in
fact this is a race.
Prevent the race by setting the baremetalhost.metal3.io/paused
annotation on the CR at the time it is created, and removing it again
when the status annotation is added. This annotation prevents the
operator from …
> baremetal: Prevent race condition when adding HardwareDetails

- pkg/asset/machines/baremetal/machines.go
- pkg/asset/machines/baremetal/machinesets.go
The installer takes the cluster name given by the user and appends a
random string. MachineSets and Machines create within the cluster need
to be linked to that cluster in order to be recognized by some of the
controllers in the machine API. This is especially important, for
example, when scaling a MachineSet to ensure that the new Machines
created by the machine-set-controller are linked to the MachineSet
properly. See https://bugzilla.redhat.com/show_bug.cgi?id=1857175 for
more details.
This change drops the use of cluster name in the MachineSet and
Machine resoures created for a baremetal cluster and uses the
clusterID instead. The baremetal platform was the only one using name
instead of ID in this way.
> baremetal: create machines and machineset linked to cluster

- data/data/azure/main.tf
- pkg/asset/installconfig/azure/client.go
- pkg/asset/installconfig/azure/dns.go
- pkg/asset/installconfig/azure/session.go
- pkg/asset/machines/azure/zones.go
- pkg/destroy/azure/azure.go
- pkg/migrate/azure/privatedns.go
When support for other Azure cloud environments was added [1], there were some necessary changes that were omitted.
* Azure clients that are created need to use the base URI appropriate for the cloud environment.
* Azure authorizers need to use the ActiveDirectory endpoint appropriate for the cloud environment.
* The environment needs to be specified for the terraform azureprivatedns provider.
[1] https://github.com/openshift/installer/pull/3634
> use correct base URI for other azure cloud environments

- data/data/gcp/main.tf
- data/data/gcp/variables-gcp.tf
- pkg/asset/cluster/tfvars.go
- pkg/asset/machines/gcp/machines.go
- pkg/rhcos/builds.go
- pkg/rhcos/gcp.go
- pkg/tfvars/gcp/gcp.go
The rhcos.json contains the GCP image project name and resource name.
Based on instance.insert api https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert the source image
for instance can use of the form `projects/debian-cloud/global/images/debian-9-stretch-vYYYYMMDD` where the image is in `debian-cloud`
project.
So this updates the rhcos.GCP to return the sourceImage in the form of `projects/<project name>/global/images/<image name>`
Since we still need to create GCP images in cases like where licenses are provided, we still need to link to GCS bucket with raw image.
So this adds a rhcos.GCPRaw function to return that URL.
The machines will use the osImage as is for re-using the RHCOS published images. But for
cases where the licenses are set for platform, the installer …
> gcp: use GCP Image published by RHCOS instead of creating per cluster

- pkg/asset/installconfig/ovirt/credentials.go
This patch show to users the PEM loaded automatic and ask
to confirm. If users decide to not use the auto downloaded
PEM from Engine they can use their own PEM.
Bug-URL: https://bugzilla.redhat.com/show_bug.cgi?id=1855345
> Bug 1855345: ovirt: show more info about PEM file loaded

- docs/user/vsphere/install_upi.md
This simplifies the instructions surrounding folder names and corrects terminology from cluster ID to infrastructure ID.
complements openshift/openshift-docs#24161
cc @abhinavdahiya @kalexand-rh
> vSphere UPI docs: clarify folder naming

- data/data/baremetal/bootstrap/main.tf
- data/data/baremetal/bootstrap/variables.tf
- docs/user/metal/install_ipi.md
- pkg/destroy/baremetal/baremetal.go
This PR creates a default storage pool for Baremetal platform's bootstrap image instead of relying on the OS to create the default libvirt storage pool. The default storage location will be stored under /var/lib/libvirt/openshift-images.
> Baremetal: Add default storage pool at /var/lib/libvirt/openshift-images

- pkg/destroy/gcp/gcp.go
Add a `GetAllPendingItems` function to the GCP destroyer that the user can use to get all of the resources that were not able to be destroyed.
This will be used by Hive to expose to the user the resources that cannot be deleted so that the user can take action on those resources.
https://issues.redhat.com/browse/CO-974
> destroy: means to obtain gcp blocked resources

- data/data/azure/main.tf
- data/data/azure/variables-azure.tf
- data/data/install.openshift.io_installconfigs.yaml
- pkg/asset/cluster/azure/azure.go
- pkg/asset/cluster/cluster.go
- pkg/asset/cluster/tfvars.go
- pkg/asset/installconfig/azure/client.go
- pkg/asset/installconfig/azure/mock/azureclient_generated.go
- pkg/asset/installconfig/azure/validation.go
- pkg/asset/installconfig/azure/validation_test.go
- pkg/asset/installconfig/platformprovisioncheck.go
- pkg/asset/machines/azure/machines.go
- pkg/asset/manifests/azure/cloudproviderconfig.go
- pkg/asset/manifests/azure/cloudproviderconfig_test.go
- pkg/asset/manifests/cloudproviderconfig.go
- pkg/asset/manifests/dns.go
- pkg/asset/manifests/infrastructure.go
- pkg/asset/manifests/openshift.go
- pkg/destroy/azure/azure.go
- pkg/explain/printer_test.go
- pkg/tfvars/azure/azure.go
- pkg/types/azure/metadata.go
- pkg/types/azure/platform.go
Add a field to azure platform to specific the name for an existing resource group
where the cluster should be installed.
- This resource group should only be used for this specific cluster and the cluster components will assume assume
ownership of all resources in the resource group.
- Destroying the cluster using installer will delete this resource group.
- This resource group must be empty with no other resources when trying to use it for creating a cluster.
If not set the installer will continue to create a new resource group using the Infra identifier.
Update the machines, cloudproviderconfig and infrastructure objects to use the
user provided resource group name when provided and fall back to generated name `<infraID>-rg` when
not set.
Update the TF templates to accept a name for the …
> Azure: Allow use to provide an empty resource group for cluster

- pkg/asset/quota/quota.go
- pkg/quota/aws/limits.go
The service quota APIs are only supported in certain regions [1] and therefore we must skip
checking quotas unless the region are from that list.
[1]: https://docs.aws.amazon.com/general/latest/gr/servicequotas.html
> Bug 1861088: aws: skip quota checking for not supported regions

- go.mod
- pkg/metrics/pushclient/pushclient.go
- pkg/metrics/pushclient/pushclient_test.go
- vendor/github.com/prometheus/client_golang/prometheus/push/push.go
- vendor/modules.txt
Creates a push client that will be used to push metrics to
Prometheus Aggregation Gateway. The client can be used for 
any type of Gateway and it takes in the URL and the HTTP Client
that would have all the necessary information(authentication) 
required to push to the gateway.
Configured to take in Prometheus Objects for pushing to gateway.
https://github.com/prometheus/client_golang/tree/master/prometheus
> Metrics: Add push client to push metrics to endpoint

- pkg/asset/installconfig/baremetal/baremetal.go
- pkg/asset/installconfig/baremetal/host.go
- pkg/asset/installconfig/platform.go
- pkg/types/installconfig_baremetal.go
baremetal: Enable installer survey for baremetal platform
This PR enables installer survey for the baremetal platform where the user is asked a minimal set of questions, which combined with sane defaults to construct an installer-config file. The config file can either directly used to create a cluster or can be customized by editing it manually before creating the cluster.
> Baremetal: Enable installer survey for baremetal platform

- pkg/destroy/vsphere/vsphere.go
when destroying a cluster, the tag associated is being deleted at the end of the process.
> Bug 1846125: deleting vsphere cluster tag after deleting the attached resources

- pkg/tfvars/ovirt/ovirt.go
:s/stoarageDomainID/storageDomainID/g
> ovirt: fix typo in tfvars ovirt

- pkg/asset/installconfig/openstack/validate.go
- pkg/asset/installconfig/openstack/validation/cloudinfo.go
- pkg/asset/installconfig/openstack/validation/machinepool.go
- pkg/asset/installconfig/openstack/validation/machinepool_test.go
- pkg/asset/installconfig/openstack/validation/platform.go
- pkg/asset/installconfig/openstack/validation/platform_test.go
Check that a minimum set of requirements are met for flavors to ensure
that installation failures due to insufficient resources don't occur.
Stacked on top of my AZ pull request because this builds on top of the testing groundwork laid in that patch.
/cc @pierreprinetti @Fedosin @mandre @adduarte  for review
> Flavor validations

- upi/ovirt/masters.yml
- upi/ovirt/workers.yml
Add the async to the ansible tasks starting vms,
to have all vms starting in parallel
> Ovirt UPI: Start vms with async

- data/data/install.openshift.io_installconfigs.yaml
- docs/user/metal/install_ipi.md
- go.mod
- go.sum
- pkg/asset/machines/baremetal/hosts.go
- pkg/tfvars/baremetal/baremetal.go
- pkg/types/baremetal/platform.go
- pkg/types/baremetal/validation/platform.go
- pkg/types/baremetal/validation/platform_test.go
- vendor/github.com/metal3-io/baremetal-operator/pkg/apis/metal3/v1alpha1/baremetalhost_types.go
- vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/redfish.go
- vendor/modules.txt
* Use the instance_info/deploy_boot_mode instead of the capabilities based on feedback from the Ironic team.
* Use the host setting from the install-config, if there is any.
* Copy the boot mode from the install-config to the new host resource, if it is set.
* update baremetal-operator to include the boot mode field
> baremetal: set the boot mode for hosts based on the input

- data/data/bootstrap/baremetal/files/usr/local/bin/master-bmh-update.sh
- data/data/bootstrap/baremetal/systemd/units/master-bmh-update.service
We missed some review items in #3591 and also I noticed we're ignoring errors currently without any way to retry.
This led to some confusion when debugging issues on 4.4 because the script silently failed even though the baremetal-operator image was missing the necessary entrypoint - hopefully these changes make things a little more robust.
> baremetal: Make master-bmh-update script more robust

- data/data/install.openshift.io_installconfigs.yaml
- pkg/explain/printer_test.go
- pkg/types/installconfig.go
- pkg/types/validation/installconfig_test.go
By convention, API constants should be capitalized.
> types: capitalize CredentialsMode values

- pkg/types/validation/installconfig.go
- pkg/types/validation/installconfig_test.go
- pkg/validate/validate.go
- pkg/validate/validate_test.go
The networking team has made an argument that not allowing docker default network bridge for machine, service and cluster networks is
an invalid validation see https://bugzilla.redhat.com/show_bug.cgi?id=1858342#c2 . So we are dropping that validation.
But on libvirt platform overlap with docker bridge has known to cause problems therefore we are keeping the validation for this platform.
Also when this network range is in use, warning is shown to the user so that in case users keep weird errors we can quickly traige to networking team.
/cc @dcbw @sdodson
> Bug 1858342: types: allow docker bridge network range except on libvirt

- data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
The cluster-etcd-operator render command now handles bootstrap certificate
generation[1]. This patch deletes the now unused client/server bootstrap etcd
cert generation logic.
[1] openshift/cluster-etcd-operator#412
> Remove unused bootstrap etcd cert generation mechanism 

- data/data/install.openshift.io_installconfigs.yaml
- docs/user/customization.md
- pkg/types/installconfig.go
- pkg/types/validation/installconfig.go
- pkg/types/validation/installconfig_test.go
For plugins like Calico which don't use the hostPrefix for anything,
it does not make sense to validate this field and force customers
to set specific values just to pass validation. These plugins should
be able to unset the hostPrefix completely and not have to worry about
it. This patch ensures that we perform the validation only for
OpenShiftSDN and OVNKubernetes. In the case of other plugins, we
check if the hostPrefix is unset(0) and if so, we skip the validation.
Signed-off-by: Surya Seetharaman <suryaseetharaman.9@gmail.com>
> Bug 1852112: Ignore hostPrefix validation for non-(sdn/ovn) plugins

- data/data/install.openshift.io_installconfigs.yaml
- data/data/openstack/bootstrap/variables.tf
- data/data/openstack/main.tf
- data/data/openstack/masters/main.tf
- data/data/openstack/masters/variables.tf
- data/data/openstack/variables-openstack.tf
- docs/user/openstack/customization.md
- pkg/asset/cluster/tfvars.go
- pkg/asset/installconfig/openstack/validation/cloudinfo.go
- pkg/asset/installconfig/openstack/validation/machinepool.go
- pkg/asset/installconfig/openstack/validation/machinepool_test.go
- pkg/asset/machines/openstack/machines.go
- pkg/asset/machines/openstack/machinesets.go
- pkg/tfvars/openstack/openstack.go
- pkg/types/openstack/machinepool.go
Following suit with AWS, OpenStack is adding support for custom AZs
for installer machine pools. Users can pass a list of zones to use
and the nodes in that machine pool will be spread across them. When
no custom zones are passed, the installer will discover and use all
zones.
Issue: #2391
> OpenStack Availibility Zones

- pkg/asset/installconfig/azure/validation.go
Previously the validation message would hide the error from the API making the error message a little difficult
to act on.
/cc @fabianofranz @jhixson74
> Bug 1840705: pkg/asset/installconfig/azure/validation.go: do not hide error from API

- pkg/asset/installconfig/aws/session.go
For global APIs the signing region is different from the cluster region, therefore when the
service overrides are set use the default resolver to get the signing region and use that when it's
non empty.
Since we only using the result when the output is non-empty we do not care about the error as we default to cluster region already.
Example:
```
apiVersion: v1
baseDomain: devcluster.openshift.com
controlPlane:
name: master
replicas: 3
compute:
- name: worker
replicas: 3
metadata:
name: adahiya-1
platform:
aws:
region: af-south-1
serviceEndpoints:
- name: ec2
url: https://ec2.af-south-1.amazonaws.com
- name: elasticloadbalancing
url: https://elasticloadbalancing.af-south-1.amazonaws.com
- name: s3
url: https://s3.af-south-1.amazonaws.com
- name: iam
url: …
```
> Bug 1862065: aws: use default resolver for signing_region of global APIs

- pkg/asset/machines/master.go
- pkg/asset/machines/worker.go
~~Completely WIP right now and won't even pass tests. I need this PR to further testing, launching clusters with https://github.com/openshift/machine-config-operator/pull/1792~~
This turned out to be working with openshift/machine-config-operator#1792 - I'm now doing further testing and creating the enhancement to get the MCO PR in first and then this one
We need to change the name of the Secret so the MCO can recompute it with the very same name we're using. We need the naming change because when we upgrade, we want to leave the old `worker|master-user-data` around for old MachineSets to still use the old ignition types. 
We need the installer to start using https://github.com/openshift/machine-config-operator/pull/1792/files#diff-5926e0cec606d949b66f823310790298R136 so we manage that …
> Have the MCO manage the ignition stub config

- pkg/asset/machines/worker.go
- pkg/types/openstack/machinepool.go
Currently If mpool is empty, we don't set default AZs and the installer can't generate machinesets.
This commit moves setting the default to the right place.
> Bug 1864280: set AZs default for machine pool in the right place

- data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
This updates bootkube.sh to have the cluster-config-operator to generate a configmap from an infrastructure and cloud config file. 
https://issues.redhat.com/browse/CORS-1458
> Bug 1864677: bootkube.sh: update cluster-config-operator to generate bootstrap configmap

- data/data/ovirt/template/main.tf
- pkg/destroy/bootstrap/bootstrap.go
This patch breaks the dependency between terraform resources:
releaseimage_template and tmp_import_vm
On ovirt before the bootstrap, masters and workers start they need to be created from a template.
The installer creates this template with the terraform template module.
As part of the process for creating the template, we create an oVirt tmp VM which should be sealed into a template for the bootstrap, masters and workers machines and then removed.
Until this PR the tmp VM will just stay in the oVirt cluster until cluster destroy is called, this is not good because it is just garbage in the oVirt cluster that the user will probably remove on its own once the installation is complete.
This PR makes bootstrap destroy command to destroy the tmp VM as well, which makes sense because it is …
> oVirt: remove tmp template VM on bootstrap destroy phase

- data/data/rhcos-amd64.json
- data/data/rhcos.json
The mitigation path for OCP customers is to reprovision nodes, so we
should bump the boot images on the installer as well.
> Bug 1862111: bump RHCOS images for CVE-2020-10713

- pkg/asset/cluster/tfvars.go
- pkg/tfvars/openstack/openstack.go
Now we use cloud name not from the install config, which is set by the user, but from master specs, where it is hardcoded to 'openstack'.
This patch starts using the value from the install config.
> Bug 1866328: use correct cloud name for tfvars

- docs/user/metal/install_upi.md
- upi/metal/config.tf
- upi/metal/main.tf
- upi/metal/terraform.tfvars.example
Requires https://github.com/openshift/release/pull/9960
> upi/metal: Add pxe_kernel_args, stop using pxe_os_image_url

- go.mod
- go.sum
- vendor/github.com/ovirt/go-ovirt/connection.go
- vendor/github.com/ovirt/go-ovirt/reader.go
- vendor/modules.txt
Solve an issue related to RHV network parsing
Backport of #3823 
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1852722
> Bug 1852722: Bump go-ovirt

- data/data/rhcos-amd64.json
- data/data/rhcos.json
The mitigation path for OCP customers is to reprovision nodes, so we
should bump the boot images on the installer as well.
> Bug 1862112: bump RHCOS images for CVE-2020-10713

- data/data/rhcos-amd64.json
- data/data/rhcos.json
The mitigation path for OCP customers is to reprovision nodes, so we
should bump the boot images on the installer as well.
> Bug 1862113: bump RHCOS images for CVE-2020-10713

- data/data/install.openshift.io_installconfigs.yaml
- pkg/asset/installconfig/openstack/validation/cloudinfo.go
- pkg/asset/installconfig/openstack/validation/machinepool.go
- pkg/asset/installconfig/openstack/validation/machinepool_test.go
- pkg/asset/machines/openstack/machinesets.go
- pkg/types/openstack/machinepool.go
Fixes a number of issues in the AZ patch:
- corrects number of replicas in machineset
- fixes bad programming conventions
- fixes handling of empty list of available zones on cloud provider
> Bug 1864120: Clean Up OpenStack IPI AZ patch 

- pkg/types/aws/validation/platform.go
- pkg/types/aws/validation/platform_test.go
Allowing these values as user defined tags causes problems defined in https://bugzilla.redhat.com/show_bug.cgi?id=1862209
> Bug 1862209: types/aws: validate Name and kubernetes.io/clustername/* keys are not allowed

- docs/user/openstack/README.md
Respecting the 301 redirects currently in place:
```console
$ curl -sLi https://try.openshift.com | grep -i '^http\|^location'
HTTP/1.1 301 Moved Permanently
location: https://www.openshift.com/try/
HTTP/1.1 301 Moved Permanently
Location: https://www.openshift.com/try
HTTP/1.1 200 OK
```
From [the spec][1] for 301 redirects:
> The 301 (Moved Permanently) status code indicates that the target resource has been assigned a new permanent URI and any future references to this resource ought to use one of the enclosed URIs.
So we should no longer be using the outdated URI.
[1]: https://tools.ietf.org/html/rfc7231#section-6.4.2
> docs/user/openstack: Replace try.openshift.com with www.openshift.com/try

- data/data/rhcos-amd64.json
- data/data/rhcos.json
The mitigation path for OCP customers is to reprovision nodes, so we
should bump the boot images on the installer as well.
> Bug 1862114: bump RHCOS images for CVE-2020-10713

- data/data/rhcos-amd64.json
- data/data/rhcos.json
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1867747
Also, addresses CI failure for https://github.com/openshift/release/pull/10121
/cc @sdodson
> Bug 1867747: bump RHCOS images to fix the booting issue from PXE

- data/data/baremetal/bootstrap/main.tf
- data/data/baremetal/bootstrap/variables.tf
- data/data/baremetal/main.tf
- data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
- data/data/install.openshift.io_installconfigs.yaml
- data/data/manifests/openshift/baremetal-provisioning-config.yaml.template
- docs/user/metal/install_ipi.md
- pkg/asset/ignition/bootstrap/baremetal/template.go
- pkg/asset/ignition/bootstrap/baremetal/template_test.go
- pkg/asset/ignition/bootstrap/bootstrap.go
- pkg/asset/installconfig/baremetal/baremetal.go
- pkg/tfvars/baremetal/baremetal.go
- pkg/types/baremetal/defaults/platform.go
- pkg/types/baremetal/defaults/platform_test.go
- pkg/types/baremetal/platform.go
- pkg/types/baremetal/validation/libvirt.go
- pkg/types/baremetal/validation/platform.go
- pkg/types/baremetal/validation/platform_test.go
- pkg/types/conversion/installconfig.go
- pkg/types/validation/installconfig_test.go
This implements [the enhancement request that makes the provisioning
network optional](https://github.com/openshift/enhancements/pull/386). It introduces a new platform configuration called
"provisioningNetwork" that takes 3 possible values: managed, unmanaged,
and disabled. The "unmanaged" option replaces the external DHCP flag
that was previously used.
When the network is set to "disabled," it is expected that users use
virtualmedia configuration. We will deploy no DHCP/TFTP provisioning
services for a user to use.
> baremetal: make provisioning network optional

- pkg/asset/installconfig/baremetal/baremetal.go
This PR fixes a bug in the baremetal survey where the host role is not currently
set. We also change the phrase for control plane back to 'master' temporarily until
the whole ecosystem moves away from the 'master/slave' terminology.
> Bug 1865707: [baremetal] Add host roles to hosts in baremetal survey

- docs/user/openstack/README.md
Add an example MachineSet with the OpenStack platform-specific
properties.
CC: @maxwelldb
> OpenStack: Document the MachineSet resource

- upi/metal/main.tf
A follow-up to https://github.com/openshift/installer/pull/3865 address few comments
xref: https://github.com/openshift/installer/pull/3865/files#r461057804
> upi/metal: remove deprecated coreos-installer kernel arguments

- data/data/openstack/topology/private-network.tf
- pkg/asset/installconfig/openstack/validation/platform.go
- pkg/asset/installconfig/openstack/validation/platform_test.go
- pkg/types/openstack/platform.go
Despite the fact `externalNetwork` is considered as an optional parameter, installations fails if it's not specified.
https://github.com/openshift/installer/pull/3822
This commit makes this and related parameters truly optional.
> Bug 1867519: make externalNetwork optional

- data/data/rhcos-ppc64le.json
The rhcos image for ppc64le was old and this was causing issues with the bootstrap node to come up because it was using the old
ignition version. Since ignition has been bumped to v3, update bootimage.
> Bump rhcos images for ppc64le

- pkg/destroy/aws/aws.go
Similar to https://github.com/openshift/installer/commit/2ef70a98679f62dc6fe9965ac7ca79b1c7dd09c6 resourcetaggingapi needs to be congifured with
additional region that would allow listing the Route53 resources for the partition. For GovCloud that region is `us-west-gov-1`
> Bug 1867972: destroy/aws: setup the resourcetagging api with correct region for gov cloud

- data/data/openstack/bootstrap/main.tf
- data/data/openstack/masters/main.tf
- pkg/asset/machines/openstack/machines.go
- pkg/destroy/openstack/openstack.go
In https://github.com/openshift/installer/pull/3818 we introduced tag-based server delition. Unfortunately it turned out we can destroy servers, created by previous versions, as no tags were set there.
To fix this situation we come back to the previous solution - deleting servers by metadata.
This reverts commit e7bf767b96f71ae7c3be210d536b64dda28e4e37
> Bug 1862044: deleting servers using metadata-based filtering

- data/data/aws/main.tf
- data/data/aws/route53/base.tf
- data/data/aws/route53/variables.tf
Based on the documentation https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/govcloud-r53.html
```
You can create private hosted zones in the AWS GovCloud (US). In general, the functionality is the same as for private hosted zones in the global version of Route 53. However, you can create alias records only when the alias target is another record in the same hosted zone. To route traffic to another AWS resource, such as an ELB load balancer or an S3 bucket, you can use a CNAME record instead of an alias record unless you're creating a record at the zone apex.
```
We cannot create ALIAS records to the NLBs in gov clouds partition, which includes `us-gov-west-1` and `us-gov-east-1`. So we switch to using CNAME for our api records in those regions and continue to use ALIAS for other …
> Bug 1866949: data/data/aws/route53: use CNAME for gov cloud partition

- data/data/azure/bootstrap/main.tf
- data/data/azure/main.tf
Set blob type for ignition file for Bootstrap VM to 'Block' instead of 'Page'.
Change source_uri to source because on OKD we download the FCOS image locally before uploading it to Azure.
> [FCOS] Fix Terraform for Azure

- docs/user/openstack/install_upi.md
Make the script modifying masters' Ignition more resilient by accounting
for a missing 'storage' property.
> Bug 1868439: openstack upi: fix Ignition key error

- docs/user/openstack/deploy_baremetal_workers.md
A couple of improvements to the openstack BM workers doc:
- Capitalize acronyms
- Fixed links
- Fixed typos
- Point to supported documentation for customizing OS image
> OpenStack: Fixups to BM workers documentation

- data/data/openstack/bootstrap/main.tf
Provision bootstrap instance in given availability zone similar to masters. Currently bootstrap is created in default zone.
Signed-off-by: Yussuf Shaikh <yussuf@us.ibm.com>
> Bug 1869329: OpenStack: Place Bootstrap in one of the master AZs

- go.mod
- go.sum
- vendor/github.com/terraform-providers/terraform-provider-vsphere/vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
- vendor/modules.txt
Updated openshift fork which contains the patch for DiskPostCloneOperation
https://github.com/openshift/terraform-provider-vsphere/pull/3
> Bug 1862290: vendor/terraform-provider-vsphere: DiskPostCloneOperation patch carry

- data/data/install.openshift.io_installconfigs.yaml
- pkg/asset/installconfig/platformpermscheck.go
- pkg/explain/printer_test.go
- pkg/types/installconfig.go
- pkg/types/validation/installconfig.go
- pkg/types/validation/installconfig_test.go
Limited backport to 4.5 that will not be documented, but was requested for Service Delivery.
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1868350 but fix spans 3 repos.
> Bug 1868350: Backport new feature to bypass problems with AWS Accounts using SCP

- docs/user/customization.md
We don't want to encourage users to install kernel-devel
as an extension in BaseOS. Preferred way is to install
it in a development build container.
> Bug 1866693: docs: drop kernel-devel from supported extensions 

- README.md
As of OCP 4.5, OpenStack UPI is fully supported.
> Readme.md: Remove experimental tag for OpenStack UPI

- pkg/asset/installconfig/ovirt/credentials.go
- pkg/asset/installconfig/ovirt/validaton.go
- pkg/asset/installconfig/ovirt/validaton_test.go
Add a basic URL validator to avoid adding urls with no
scheme or scheme different from https.
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1859874
> Bug 1859874: Add basic engine URL validation

- docs/user/openstack/README.md
Implements OSASINFRA-1940
cf. https://github.com/openshift/openshift-docs/pull/24834
> Bug 1870592: openstack: Document MachineSet availabilityZone

- data/data/rhcos-amd64.json
- data/data/rhcos.json
This fixes a race condition during early boot where FIPS mode doesn't
always get turned on.
```
$ ./differ.py --first-endpoint art --first-version 46.82.202008111140-0 --second-endpoint art --second-version 46.82.202008181646-0
{
"sources": {
"46.82.202008111140-0": "https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.6/46.82.202008111140-0/x86_64/commitmeta.json",
"46.82.202008181646-0": "https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.6/46.82.202008181646-0/x86_64/commitmeta.json"
},
"diff": {
"container-selinux": {
"46.82.202008111140-0": "container-selinux-2.135.0-1.module+el8.2.1+6849+893e4f4a.noarch",
"46.82.202008181646-0": "container-selinux-2.144.0-1.rhaos4.6.el8.noarch"
},
"cri-o": {
"46.82.202008111140-0": …
```
> Bug 1862957: bump RHCOS images for FIPS fix

- pkg/types/aws/validation/platform.go
- pkg/types/aws/validation/platform_test.go
The validation was checking for kubernetes.io/clustername/ prefix in tag keys when it should have been kubernetes.io/cluster/ prefix
> Bug 1862209: aws: fix validation for user tags

- data/data/libvirt/variables-libvirt.tf
- pkg/tfvars/libvirt/libvirt.go
Noticed on 4.6 libvirt installs that processes on the bootstrap node were getting OOM killed. This was mainly due to
large memory consumption on by the kube-apiserver (https://bugzilla.redhat.com/show_bug.cgi?id=1868773) although
this looks to be normal as other platforms have a bigger memory limit for the bootstrap node.
> Bug 1868773: Libvirt: Bump bootstrap memory to 4G

- data/data/openstack/topology/private-network.tf
By dynamically calculating the end of DHCP allocation pool, this allows
deploying OpenShift with machine CIDR smaller than `/18`.
> Bug 1871048: OpenStack: dynamically set end of DHCP allocation pool

- docs/user/azure/install_upi.md
Update Azure UPI documentation to base64 encode without newlines.
> bug 1863026: docs/user/azure: remove newlines from base64 encoding in UPI install doc

- data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
There was a time prior to 4.4 where cluster-etcd-operator was built as experimental operator and it was enabled by a flag to consider it unmanaged. Since cluster-etcd-operator has been mainstay since OCP 4.4, this flag is unused and should be removed.
This is an attempt to get https://github.com/openshift/installer/pull/4024 split into smaller PRs to understand the build errors.
> Bug 1813012: Remove legacy code for unmanaged cluster-etcd-operator

- pkg/asset/machines/openstack/machinesets.go
Fixes #4069
Signed-off-by: Yussuf Shaikh <yussuf@us.ibm.com>
> Bug 1870082: Use index in MachineSet names for Openstack IPI 

- data/data/gcp/bootstrap/main.tf
- data/data/gcp/bootstrap/variables.tf
- data/data/gcp/main.tf
Specify region for all terraform resources. This prevents the default of "US" from being used.
> bug 1871030: data/data/gcp: be pedantic about setting the region

- go.mod
- go.sum
- vendor/github.com/terraform-providers/terraform-provider-vsphere/vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
- vendor/modules.txt
Updated openshift fork which contains the patch for
DiskPostCloneOperation
(https://github.com/openshift/terraform-provider-vsphere/pull/3)
manual cherry-pick #4060
> Bug 1873537: vendor/terraform-provider-vsphere: DiskPostCloneOperation patch carry

- images/installer/Dockerfile.upi.ci
Before this change the container that was being used to
grab the `oc` command was v4.1. This is too old for
CSR requests and causes vSphere UPI CI to fail.
Updates to v4.6.
> Bug 1872861: Update cli container image for UPI

- upi/openstack/compute-nodes.yaml
Wrong tagging of compute node parent ports make kuryr not able
to find the precreated ports, thus breaking the kuryr ports pool
functionality
> Bug 1873448: Ensure proper tagging of compute nodes ports

- README.md
Adding the documentation links, that have been available for a while.
> Bug 1842071: Add ppc64le and s390x documentation links

- data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
The images for kube-client-agent and setup-etcd-env are no longer needed for either MCO or CEO.
> Bug 1813012: Remove unused flags previously needed for etcd static pod

- hack/update-rhcos-bootimage.py
Automatically convert RHT-internal `meta.json` URL (from the RHCOS ART build browser) to the external openshift.org URL, so the caller doesn't have to do it manually.
cc @cgwalters
> hack/update-rhcos-bootimage: update usage example

- pkg/destroy/bootstrap/bootstrap.go
When calling terraform destroy the tmpVM disk is not removed from the engine. This is because the tmp VM unlike any other VM is not created from an oVirt template, and we create a separate disk for it with ovirt_image_transfer.
This PR removes the disk resource when calling destroy
> BUG 1872646: oVirt, remove tmp VM disk on destroy

- pkg/types/aws/validation/machinepool.go
- pkg/types/aws/validation/machinepool_test.go
- pkg/types/validation/machinepools.go
US Govcloud and China partitions do not allow copying AMI from commercial region us-east-1. Therefore the users
need to provide the AMI for control plane and compute.
/assign @jstuever
> Bug 1867975: aws: ensure users set ami id for us-gov and cn regions

- data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
This will increase install speed and reduce retries by creating namespace annotations
required for SCC.
part 2 of 3.  requires https://github.com/openshift/cluster-kube-controller-manager-operator/pull/443
> bug 1861917: bootkube: add image for cluster-policy-controller

- data/data/rhcos-ppc64le.json
- data/data/rhcos-s390x.json
Just like #4095 but for multi-arch
> Bug 1874656: Bump RHCOS for s390x/ppc64le to fix SSH authentication

- docs/user/openstack/install_upi.md
Trailing commas are not allowed in JSON.
> Bug 1868439: openstack UPI: Fix JSON syntax

- pkg/asset/machines/baremetal/hosts.go
- pkg/types/baremetal/rootdevice.go
- pkg/types/baremetal/rootdevice_test.go
Pass the root device hints given by the user in the install-config to
the BareMetalHost resources created in the cluster.
> Bug 1871653: baremetal: set root device hints on host resources

- docs/user/ovirt/install_upi.md
In RHEL8 we need to use explicitly python3 command
> Bug 1876783: oVirt UPI fix python cmd

- pkg/asset/installconfig/openstack/openstack.go
Now, during install config generation, we cannot set lbFloatingIP value because there is a variable redeclaration in the code.
This patch removes the nested variable declaration, which allows the installer to assign the value to the right variable.
> Bug 1876825: generate lbFloatingIP in OpenStack config

- pkg/asset/manifests/openshift.go
- pkg/asset/manifests/operators.go
Fetching only yaml, yml, and json file types from manifests and openshift directory to avoid unwanted file types
> Bug 1856928: Fix Non yaml files in manifests/ or openshift/ directories preventing bootstrap from completing

- pkg/tfvars/openstack/bootstrap_ignition.go
In some environments Glance cannot return bootstrap ignition config in time (10 seconds), and users see timeout errors. To prevent it this commit increases the timeout to two minutes.
> Bug 1875855: increase timeout for bootstrap ignition downloading

- upi/vsphere/lb/haproxy.service
This change allows the haproxy.service to restart cleanly by removing
the haproxy pod on ExecStop.
> Bug 1870038: vmware upi: haproxy.service to rm haproxy pod on ExecStop

- docs/user/openstack/install_upi.md
Commit e7c35dfd9 introduced invalid python syntax in the OpenStack UPI scripts. This series of commit fixes the errors and also cleans up the scripts a bit by removing extra semicolons at the end of lines.
> Bug 1873125: Fix python syntax for OpenStack UPI scripts

- data/data/bootstrap/gcp/files/opt/libexec/openshift-gcp-routes.sh
- pkg/asset/machines/machineconfig/okdextensions.go
MC is invalid without Ignition version set:
```
"99_openshift-machineconfig_99-worker-okd-extensions.yaml": failed to create machineconfigs.v1.machineconfiguration.openshift.io/99-worker-okd-extensions -n : MachineConfig.machineconfiguration.openshift.io "99-worker-okd-extensions" is invalid: spec.config: Invalid value: "null": spec.config in body must be of type object: "null"
```
This also syncs gcp-routes with latest code in MCO
> [FCOS] okdextensions: ensure minimal ignition config is set

- upi/ovirt/create-templates-and-vms.yml
Fix the templates exists check flattening the templates list,
add check for already downloaded compressed image to avoid the default
get_url check.
> Bug 1877862: oVirt UPI - Fix templates check and optimize image check

- docs/user/openstack/README.md
Since https://github.com/openshift/installer/pull/3855, the installer is
able to attach the `ingressFloatingIP` specified in the
`install-config.yaml` to the ingress-port. Update the documentation to
reflect the change.
> Bug 1877676: OpenStack: Refresh documentation about ingress FIP

- upi/ovirt/inventory.yml
According to the UPI documentation recent changes the assets_dir var
value in the inventory.yml should be set looking at the env variable
ASSETS_DIR
> Bug 1877440: oVirt UPI Assets_dir set according to env var

- images/openstack/Dockerfile.ci
Before this patch, the CI was using the `oc` OpenShift client `v4.2.0-alpha.0-110-g1337b29`
> Bug 1878243: openstack: Upgrade the CI build image

- data/data/ovirt/template/main.tf
- go.mod
- go.sum
- vendor/github.com/ovirt/terraform-provider-ovirt/ovirt/resource_ovirt_vm.go
- vendor/modules.txt
- bump terraform provider with the `auto_start` param
- add `auto_start=false` param to the installer not to start the VM when creating template.
this PR depends on https://github.com/oVirt/terraform-provider-ovirt/pull/227
> Bug 1874747: ovirt: dont start the temp VM before template creation

- docs/user/openstack/install_upi.md
- upi/openstack/bootstrap.yaml
- upi/openstack/inventory.yaml
- upi/openstack/network.yaml
Add the option to disable the use of floating IPs
/assign adduarte iamemilio
> Bug 1878758: openstack UPI: Optional floating IPs

- cmd/openshift-install/create.go
We're seeing a significant uptick in install failures.  Many appear to actually finish successfully before
artifact collection.  We have good signal in sippy about successful install ratios.  We can increase
this timeout by 10 minutes to see if we get an improved install percentage and then continue from there.
> install: increase timeout to 40 minutes

- pkg/destroy/gcp/policybinding.go
- pkg/destroy/gcp/policybinding_test.go
/test e2e-gcp
/cc @abhinavdahiya
> Bug 1880132: destroy/gcp: correct extract service account email from IAM policy binding member

- pkg/asset/manifests/proxy.go
- pkg/types/validation/installconfig.go
- pkg/types/validation/installconfig_test.go
"*" is considered to be a valid value for noProxy according to [1]
So the installer allows setting "*" for noProxy and matches the network operator for configuring .status.noProxy when such a value is set based on [2] i.e. as-is set the noProxy to "*"
without adding any default noProxy values.
[1]: https://docs.openshift.com/container-platform/4.5/installing/installing_bare_metal/installing-restricted-networks-bare-metal.html#installation-configure-proxy_installing-restricted-networks-bare-metal
[2]: https://github.com/openshift/cluster-network-operator/blob/210e2dea2a60c18c277a7249d04085472a6b9a8c/pkg/controller/proxyconfig/status.go#L21-L28
> Bug 1877486: proxy: allow * for noProxy

- pkg/asset/quota/gcp/client.go
- pkg/asset/quota/gcp/gcp.go
- pkg/asset/quota/gcp/gcp_test.go
- pkg/asset/quota/quota.go
Previously we were using the machine type name to figure out the CPU count and metric name. But it seems like using the GCP API
will be more future proof compared to string matching.
So now the constraint calculator will fetch the CPU count from GCP api and only on failure guess the count using string matching.
Fallback to the string matching allows us to guess the CPU count when API access to not available or other failures. The guess always drops the count to 0 when it cannot guess with high confidence.
Also adds unit tests for the machine type -> guess cpu function and use GCP api and fallback to guess function.
/cc @jstuever @gregsheremeta 
/assign @jstuever
> Bug 1878108: asset/quota/gcp: use GCP api to find CPU count for constraint and guess only on failure

- pkg/asset/installconfig/openstack/openstack.go
We should unset OS_CLOUD env variable during interactive install-config generation, because the real cloud name is defined by user in the interactive session. OS_CLOUD has more priority, so the user-defined value will be ignored if OS_CLOUD contains something.
> Bug 1876815: unset OS_CLOUD during config generator

- pkg/destroy/openstack/openstack.go
In case the machines Subnet is not connected to a Router
there is not a need to clean-up the interfaces from the
custom Router as no additional interfaces would have
been created on it. Also, when using Kuryr if a Service
of LoadBalancer type was created, a floating ip would get
created for the load balancer and the removal of the service
subnet from the router would be blocked.
This commit fixes both issues by ignoring the custom Router
clean-up when no Router is found and moving the custom
Router clean-up to after the load balancers removal.
> Bug 1879891: Fix cluster destroy when fip less installation happened

- docs/user/openstack/install_upi.md
Similar to 0bf09af3bc45e6724e210fce7a0743c9a3cab8bf that fixed the same
issue for IPI, we need to trim EOLs from the ca-cert bundle in the UPI
scripts otherwise ignition might not accept it as valid.
> Bug 1880393: OpenStack UPI: Trim EOLs from the cacert trustbundle

- docs/user/openstack/install_upi.md
By passing the certificate through openssl, we ensure it is valid. This
has the added benefit of trimming EOLs from otherwise valid certs.
> Bug 1880393: OpenStack UPI: Explain how to encode cert to base64

- upi/ovirt/create-templates-and-vms.yml
Removing some not mandatory attributes according to the
ovirt.image-template docs and the ovirt/RHV UPI docs that
explains mandatory parameters to set in the inventory.yml
> Bug 1879649: oVirt UPI - Simplify create templates

- upi/openstack/bootstrap.yaml
- upi/openstack/common.yaml
- upi/openstack/network.yaml
- Flag primary cluster subnet.
- Attaches bootstrap floating ip to correct subnet.
> Bug 1877854: OpenStack: Support multiple subnets

- docs/user/ovirt/install_upi.md
Certificates inside ignition config files expire in 24 hours. Add a Note section to describe that
> Bug 1878789: Add note about ignition certificates expiration

- pkg/types/conversion/installconfig.go
- pkg/types/conversion/installconfig_test.go
- pkg/types/defaults/installconfig.go
- pkg/types/validation/installconfig.go
I forget exactly what happened, but way back in the beginning there was a disconnect between the installer and the cluster-network-operator about what the correct spelling of "OpenShiftSDN" was, and it was decided that CNO was going to have to accept both "OpenShiftSDN" and "OpenshiftSDN" for backward compatibility.
However, there are other components that look at the network config sometimes (in particular, MCO now needs to look at it before CNO even runs), so it doesn't make sense for the canonicalization to happen in CNO; we should just not generate the incorrect version of the network config in the first place.
> Bug 1877984: Fix "OpenShiftSDN" to proper case when generating network config

- pkg/types/installconfig.go
Users might provide the base domain in its canonical form, with the
trailing dot. With this change, the baseDomain trailing dot is ignored
both in the interactive prompt, and when loading an install-config file
from the filesystem.
> Bug 1853418: Ignore trailing dots in baseDomain

- pkg/asset/tls/mcscertkey.go
go1.15 clients do not like server certs with common name set to a valid hostname. casuing failures like
```
x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
```
So, looking at the go 1.15 release notes
https://golang.org/doc/go1.15
```
X.509 CommonName deprecation ¶
The deprecated, legacy behavior of treating the CommonName field on X.509 certificates as a host name when no Subject Alternative Names are present is now disabled by default.
It can be temporarily re-enabled by adding the value x509ignoreCN=0 to the GODEBUG environment variable.Note that if the CommonName is an invalid host name, it's always ignored, regardless of GODEBUG settings.
Invalid names include those with any characters other than …
```
> Bug 1881757: tls: set mcs cert common name to not-valid-hostname

- data/data/rhcos-ppc64le.json
- data/data/rhcos-s390x.json
To align with the x86 images in #4206, bump bootimages for the other arches
> Bug 1882805: Bump bootimages for ppc64le and s390x to 46.82.202009240941-0 and 46.82.202009241338-0

- pkg/asset/installconfig/openstack/openstack.go
- pkg/asset/installconfig/openstack/validvaluesfetcher.go
Non-external networks are not accepted and would make the Installer
error.
> Bug 1881532: openstack: Only list external networks in prompt

- pkg/asset/installconfig/openstack/validation/cloudinfo.go
- pkg/asset/installconfig/openstack/validation/machinepool.go
- pkg/asset/installconfig/openstack/validation/machinepool_test.go
- pkg/asset/installconfig/openstack/validation/platform.go
- pkg/asset/installconfig/openstack/validation/platform_test.go
Baremetal flavor metadata in Glance often contains placeholder
information. With this change, pre-flight validation is no longer
performed for flavors itentified as baremetal.
> Bug 1878900: openstack: Skip validation for baremetal flavors

- docs/user/openstack/deploy_baremetal_workers.md
OpenShift 4.6 does not support adding a MachineSet on a separate subnet.
Removing the corresponding use case from the baremetal-workers
documentation.
Also adding a use case for installing a cluster on bare metal machines
exclusively.
> Bug 1882752: openstack BM: Remove MachineSet on separate subnet

- pkg/asset/machines/master.go
- pkg/asset/machines/worker.go
This reverts commit 8d278d258f9eb16788cc8c4bda842018e28625d7 following findings in https://docs.google.com/document/d/1TnnfPgFim-e895MD0msOGN9tyPBk3CM8cmSewFmgzDQ/edit# and https://bugzilla.redhat.com/show_bug.cgi?id=1881703
> Bug 1881703: Revert "Have the MCO manage the ignition stub config"

- docs/user/openstack/install_upi.md
Indicate what privileges are needed to generate the Glance token to be
included in the bootstrap Igntion shim.
> Bug 1876844: openstack UPI: Ignition token needs Glance access

- docs/user/openstack/install_upi.md
- upi/openstack/bootstrap.yaml
- upi/openstack/down-bootstrap.yaml
- upi/openstack/inventory.yaml
If the external network is not provided, the router will not be created
and external connectivity will be a respopnsibility of the operator.
Floating IPs will be set if available, on an individual basis. The
external network is a requirement for FIPs; if not provided, the
playbooks will error.
The bootstrap FIP is now required to be created manually like the other
FIPs.
This is a follow-up to #3755.
/cc luis5tb adduarte iamemilio mandre
> Bug 1878758: openstack UPI: Allow for no FIP or router

- pkg/asset/manifests/openshift.go
When we generate an OpenShift cred secret with clouds.yaml, we keep the local cacert path there. In other words, path to cacert on the user's machine.
This is wrong, because this value is useless after the installation. To avoid this we need to use the predefined const value, like we do with cloud config:  https://github.com/openshift/installer/blob/4aac205a59a9102ddf1ae329b3c4c6f0dff7e330/pkg/asset/manifests/openstack/cloudproviderconfig.go#L21
> Bug 1884558: do not use local cacert path in generated clouds.yaml

- pkg/asset/installconfig/openstack/session.go
- pkg/asset/installconfig/openstack/validation/cloudinfo.go
- pkg/destroy/openstack/openstack.go
We should unset OS_CLOUD env variable during cloudinfo and session generation, and cluster destruction. We have to do it because the real cloud name is defined by user in the install-config. OS_CLOUD has more priority, so the user-defined value will be ignored if OS_CLOUD contains something.
> Bug 1876815: OpenStack: unset OS_CLOUD

- docs/user/openstack/troubleshooting.md
The issue was long fixed and the recommended solution isn't needed
anymore.
> Docs: OpenStack: Remove mention of cluster failing to destroy

- data/data/rhcos-amd64.json
- data/data/rhcos.json
This fixes early boot issues in environments with low entropy.
```
$ ./differ.py \
--first-endpoint art --first-version 46.82.202009222340-0 \
--second-endpoint art --second-version 46.82.202010011740-0
{
"sources": {
"46.82.202009222340-0": "https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.6/46.82.202009222340-0/x86_64/commitmeta.json",
"46.82.202010011740-0": "https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.6/46.82.202010011740-0/x86_64/commitmeta.json"
},
"diff": {
"conmon": {
"46.82.202009222340-0": "conmon-2.0.20-1.rhaos4.6.el8.x86_64",
"46.82.202010011740-0": "conmon-2.0.21-2.rhaos4.6.el8.x86_64"
},
"console-login-helper-messages": {
"46.82.202009222340-0": …
```
> Bump RHCOS images for Ignition entropy fix

- pkg/asset/cluster/metadata.go
Prior to this change, the Metadata asset was only regenerated when the
install-config or install-config.infraID was determined to have changed.
However, in the case that the install-config was updated, the installer
was invoked with `create manifests`, and then the installer was invoked
a second time with `create ignition-configs`, the second invokation had
no way of knowing the install-config had changed. As a result, the
Metadata would not be regenerated. This caused the clusterID in the
metadata.json to not match that of the cluster.
This change solves this specific case by making the Metadata asset
dependent on the bootstrap ignition asset. It in turn is dependent on
the manifests asset. As a result, when the manifests are regenerated
in the first invocation, and the bootstrap …
> Bug 1777224: pkg/asset: metadata to depend on ignition

- data/data/bootstrap/vsphere/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender.template
Randomly the resolver will not be configured with 127.0.0.1 causing
bootstrap failure, adding status `down` to see if it improves.
> Bug 1884435: vsphere - add delay if resolv.conf is not available; wait for dhcp

- data/data/rhcos-amd64.json
- data/data/rhcos.json
This fixes early boot issues in environments with low entropy.
```
$ ./differ.py \
--first-endpoint art --first-version 46.82.202009222340-0 \
--second-endpoint art --second-version 46.82.202010011740-0
{
"sources": {
"46.82.202009222340-0": "https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.6/46.82.202009222340-0/x86_64/commitmeta.json",
"46.82.202010011740-0": "https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.6/46.82.202010011740-0/x86_64/commitmeta.json"
},
"diff": {
"conmon": {
"46.82.202009222340-0": "conmon-2.0.20-1.rhaos4.6.el8.x86_64",
"46.82.202010011740-0": "conmon-2.0.21-2.rhaos4.6.el8.x86_64"
},
"console-login-helper-messages": {
"46.82.202009222340-0": …
```
> Bug 1882515: bump RHCOS images for Ignition entropy fix

- data/data/bootstrap/files/etc/systemd/system.conf.d/10-default-env-godebug.conf.template
Go 1.15 no longer falls back to the common name for hostname validation
requiring that a DNS SAN exist. We need more time to deprecate this so
revert back to previous behavior for the time being.
> Bug 1882191: Add GODEBUG=x509ignoreCN=0 to systemd DefaultEnvironment

- data/data/install.openshift.io_installconfigs.yaml
- data/data/openstack/main.tf
- data/data/openstack/topology/private-network.tf
- data/data/openstack/topology/variables.tf
- data/data/openstack/variables-openstack.tf
- docs/user/openstack/README.md
- docs/user/openstack/customization.md
- pkg/asset/cluster/tfvars.go
- pkg/asset/installconfig/openstack/openstack.go
- pkg/asset/installconfig/openstack/validation/cloudinfo.go
- pkg/asset/installconfig/openstack/validation/platform.go
- pkg/asset/installconfig/openstack/validation/platform_test.go
- pkg/tfvars/openstack/openstack.go
- pkg/types/conversion/installconfig.go
- pkg/types/conversion/installconfig_test.go
- pkg/types/openstack/platform.go
> OpenStack: Rename lbFloatingIP to apiFloatingIP

- docs/user/openstack/README.md
- docs/user/openstack/privileges.md
Document the bare minimum permissions needed to install a cluster on openstack.
> openstack privileges documented

- images/installer-artifacts/Dockerfile.rhel
Updating ose-installer-artifacts builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-installer-artifacts.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/installer/pull/4250 . Allow it to merge and then run `/test all` on this PR.
> Updating ose-installer-artifacts builder & base images to be consistent with ART

- images/installer/Dockerfile.ci
Updating ose-installer builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-installer.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
> Updating ose-installer builder & base images to be consistent with ART

- pkg/types/vsphere/validation/platform.go
- pkg/types/vsphere/validation/platform_test.go
the vCenter hostname must be all lower case because otherwise the cluster components cannot accurately connect with vCenter.
> Bug 1874248: types/vsphere/validation: ensure vcenter is all lower case

- docs/user/openstack/install_upi.md
- images/openstack/Dockerfile.ci
[OSASINFRA-2127](https://issues.redhat.com/browse/OSASINFRA-2127)
> openstack: Bump Ansible to 2.9 in UPI

- data/data/bootstrap/baremetal/systemd/units/master-bmh-update.service
- data/data/bootstrap/files/usr/local/bin/installer-gather.sh
Allow users to debug failures in the master-bmh-update script.
We are not done with the bootstrap host until the `master-bmh-update.sh`
script has successfully completed, adding the IP address data needed by
the master nodes, and enabling reconciliation on the master Host
objects. To ensure the bootstrap cannot go away before this is done,
delay signalling that bootstrapping is complete until it is finished.
Correct the name of the unit in the log gathering script, so that users
can see the output without logging in to the bootstrap host.
> Bug 1887525: baremetal: Wait for master-bmh-update script to succeed

- pkg/asset/installconfig/openstack/validation/cloudinfo.go
- pkg/asset/installconfig/openstack/validation/platform.go
- pkg/asset/installconfig/openstack/validation/platform_test.go
- vendor/github.com/gophercloud/utils/openstack/imageservice/v2/images/utils.go
- vendor/modules.txt
This commit adds validations that custom Glance image specified by `clusterOSImage` config parameter exists and has Active status.
> OpenStack: add clusterOSImage validations

- cmd/openshift-install/create.go
- cmd/openshift-install/waitfor.go
This change provides a link to the documentation when operators are
reporting failures during install-complete. It also gives instructions
to reinvoke with wait-for install-complete once all issues have been
resolved.
> install-complete: provide troubleshooting info when operators fail

- pkg/destroy/aws/aws.go
The RunWithContext method has been modified to return a slice of ARNs that could not be destroyed. Only the ARNs of the first-level resources will be returned. For example, when deleting a VPC, the uninstaller will first delete other resources that use the VPC. Any of those resources that are blocked from being deleted but are not tagged for the cluster will not show up in the list of blocked resources. However, the first-level VPC will show up as blocked in this case.
This will be used by Hive to expose to the user the resources that cannot be deleted so that the user can take action on those resources.
https://issues.redhat.com/browse/CO-973
> destroy: return aws resources that could not be deleted

- upi/openstack/bootstrap.yaml
- upi/openstack/compute-nodes.yaml
- upi/openstack/control-plane.yaml
- upi/openstack/inventory.yaml
- upi/openstack/network.yaml
This feature allows the customer to select fixed IP addresses
that they can reach the API and apps ingress at in their OpenShift cluster.
Note that the default values have not changed. APIVIP still defaults
to the 5 on the machineNetwork, and IngressVIP still defaults to the 7.
> OpenStack UPI: Custom API and Ingress vip addresses

- pkg/asset/installconfig/openstack/validation/cloudinfo.go
- pkg/asset/installconfig/openstack/validation/machinepool.go
- pkg/asset/installconfig/openstack/validation/machinepool_test.go
- pkg/asset/installconfig/openstack/validation/platform.go
- pkg/asset/installconfig/openstack/validation/platform_test.go
Flavor validation was reporting issues with wrong `install-config.yaml`
property names.
> Bug 1878900: openstack: Fix error messages in flavor validation

- images/installer/Dockerfile.upi.ci
This vSphere environment is being decommissioned and VMC
uses valid certificates for vCenter so this is no longer required.
This is required for UPI CI testing to continue to function
(and whatever else tests that use `upi-installer`)
> vSphere: Update dockerfile removing certificate

- pkg/tfvars/openstack/rhcos_image.go
Now we always use "qcow2" disk format for Glance images. This is not correct if a user wants to upload a raw format image (with "raw" file extension).
This commit checks the extension and allows to set disk format accordingly.
> Bug 1882649: Determine Glance disk format based on file extension

- cmd/openshift-install/create.go
- cmd/openshift-install/log.go
- cmd/openshift-install/main.go
Currently the logrus hook runs formatter once for each entry, which causes newlines to be escaped see sirupsen/logrus#608
Because of this multiline messages end up looking like
```go
logrus.Info(`some message
same mesage multiline 1`)
logrus.Info("next meesage")
```
```
LEVEL some message
same message multiline 1
LEVEL next messsage
```
With this change the hook will format each entry's message split on newlines so that,
```go
logrus.Info(`some message
same mesage multiline 1`)
logrus.Info("next meesage")
```
```
LEVEL some message
LEVEL same message multiline 1
LEVEL next messsage
```
This will help 2 cases,
- af9b49c like informational messages that are require multiple lines to be more user-friendly.
- meesages from cluster operators on install-complete failure see #4242
/cc @deads2k …
> cmd: split newlines in logrus stderr output to new entry

- data/data/gcp/network/network.tf
Our worker nodes NAT instances are configured on GCP to allow for 512 ports per VM instance.
Master nodes have the same setting set to 7168 ports. However worker nodes usually run the load
(i.e pods) which instantiate a huge amount of open connections, we thus need to increase this
value to avoid NAT packet drops on GCP when running high load. This has been a big cause of
connection timeout problems on GCP clusters.
Slack channel for incident which took 2 weeks to solve: https://coreos.slack.com/archives/C01BQ9UR5J9
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1886553
Signed-off-by: Alexander Constantinescu <aconstan@redhat.com>
> Bug 1886553: GCP - Increase worker NAT min ports

- data/data/rhcos-amd64.json
- data/data/rhcos.json
- pkg/rhcos/ami_regions.go
There are RFEs requesting support for additional AWS regions:
ap-east-1, af-south-1, and eu-south-1
https://issues.redhat.com/browse/RFE-903
https://issues.redhat.com/browse/RFE-1267
This also bumps the boot image to a *real* RHCOS 4.7 image.
> Bug 1889852: add new AWS regions

- upi/vsphere/lb/haproxy.tmpl
Current hapropy setting for the vsphere upi is to check the
6443 port to see if the api server is up in tcp mode. TCP breaks
graceful termination and /readyz provides error information before
the api server crashes which would give some time for the load
balancer to react.
Adding a check in the HAProxy server to check for the /readyz
port for 200 status.
> Bug 1836017: Configure haproxy to check /readyz

- pkg/asset/installconfig/aws/instancetypes.go
- pkg/asset/installconfig/aws/metadata.go
- pkg/asset/installconfig/aws/validation.go
- pkg/asset/installconfig/aws/validation_test.go
Ensure the user provided instance type meets minimum resource requirements.
Example error:
```
FATAL failed to fetch Metadata: failed to load asset "Install Config": [controlPlane.platform.aws.type: Invalid value: "m5.large": Instance type m5.large does not meet minimum controlPlane resource requirements of 4 vCPUs, controlPlane.platform.aws.type: Invalid value: "m5.large": Instance type m5.large does not meet minimum controlPlane resource requirements of 16384 MiB Memory]
```
> pkg/asset/installconfig/aws: Validate install-config instance type

- pkg/asset/machines/openstack/machines.go
- pkg/asset/machines/openstack/machinesets.go
- pkg/asset/machines/worker.go
Hive calls into the installer's functions for converting MachinePools to MachineSets.
As Hive can be reconciling multiple cluster states simultaneously, we cannot rely on setting shared `OS_*` environment variables.
Extend the installer's functions for OpenStack to allow providing custom versions of reading in the OpenStack credentials.
> Bug 1880443: allow providing client options when generating OpenStack MachineSets

- data/data/ovirt/template/main.tf
We noticed that sometime the installation fails on template creation or release image upload just because of the 10m timeout.
We increase the time out to 20m allowing resources to finish
> Bug 1889267: oVirt, increase terraform template and release image timeout to 20m

- OWNERS_ALIASES
This PR changes the ovirt approvers and reviewers
- remove gekorob that is not working at red hat any more
- remove dougsland approver
- add eslutsky as approver and reviewer
> oVirt: change owners

- pkg/destroy/azure/azure.go
Azure clubs all resources for a cluster within a resource group. The
pattern for delete is to first delete all the resources and then delete
the resource group.
However, when attempting delete, we should first check if the
resource group exists and then try to delete the resources. This is to
ensure delete exits gracefully when resource group wasn't created and/or
deleted before attempting delete.
> Bug 1888378: [Azure][Destroy] Check if resource group exists

- pkg/asset/ignition/bootstrap/bootstrap.go
https://bugzilla.redhat.com/show_bug.cgi?id=1891702
> bug 1891702: pkg/asset/ignition/bootstrap: exit loop if pem.Decode() fails

- pkg/types/aws/validation/machinepool.go
As with US Govcloud and China partitions, C2S partitions do not allow copying AMI from commercial region us-east-1. Therefore the users need to provide the AMI for control plane and compute.
https://issues.redhat.com/browse/CORS-1582
> aws: ensure users set ami id for c2s regions

- pkg/destroy/aws/aws.go
The C2S partition does not have resourcetaggingapi. Consequently, the aws destroyer is not able to find resources to clean up when the cluster is installed in that partition. Rather than making the user wait through numerous timeouts and backoffs, fail the destroy command early when the region used for the cluster is the C2S region.
https://issues.redhat.com/browse/CORS-1581
> aws: block cluster destroy in c2s region

- data/data/install.openshift.io_installconfigs.yaml
- pkg/types/gcp/machinepools.go
This adds the API fields to enable GCP customer managed encryption keys from the MachinePool configuration at installation.
I wasn't sure whether at this stage we wanted to document this in `docs/user/gcp/customization.md` or wait until the implementation is done so I've left it out for now, I can add it if you'd rather we keep that in this PR with the API changes.
This API should match the Machine API changes introduced in https://github.com/openshift/cluster-api-provider-gcp/pull/132
CC @katherinedube, you mentioned about adding just to the MachinePool on the call yesterday to match what was done in AWS, I believe I've done it that way but would appreciate a double check
> [CORS-1577] Add Encryption Key reference to GCP MachinePool API

- pkg/destroy/azure/azure.go
Reverts openshift/installer#4320
I concur with the sentiment expressed by @abhinavdahiya [here](https://github.com/openshift/installer/pull/4320#issuecomment-718153041)
> Revert "[Azure][Destroy] Check if resource group exists"

- data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
The cluster-etcd-operator render command now handles bootstrap certificate
generation. This patch deletes the now unused client/server bootstrap etcd
cert generation logic.
Depends on https://github.com/openshift/cluster-etcd-operator/pull/438
Backport of https://github.com/openshift/installer/pull/3995
> Bug 1877374: Remove unused bootstrap etcd cert generation mechanism

- pkg/destroy/azure/azure.go
This appends Azure auth errors to the error list, so destroy is properly terminated and an error shown to the user. Without this, the metadata.json is deleted (along with other artifacts) and no error is shown to the user.
With this change, users (with incorrect credentials) will see:
```
$ ./openshift-install destroy cluster --dir azure-delete/cluster/
INFO Credentials loaded from file "/home/padillon/.azure/osServicePrincipal.json" 
FATAL Failed to destroy cluster: [unable to authenticate when deleting public DNS records: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to [...]
```
Without this change, users (at standard log level)  see only:
```
$ ./openshift-install destroy cluster --dir azure-delete/cluster/
INFO Credentials loaded from file …
```
> Bug 1866925: display Azure destroy auth error

- pkg/types/ovirt/validation/machinepool.go
To align with other platforms and our own validation, we added a validation on the memoryMB field to make sure it is a positive valuei
> Bug 1841381: oVirt, add memoryMB validation

- pkg/asset/installconfig/openstack/validation/cloudinfo.go
- pkg/asset/installconfig/openstack/validation/machinepool.go
- pkg/asset/installconfig/openstack/validation/machinepool_test.go
- pkg/asset/installconfig/openstack/validation/platform.go
- pkg/asset/installconfig/openstack/validation/platform_test.go
Fixes an issue where we expected cloudInfo to not have a
key for the flavorName if it was not found. In the code and the unit tests, cloudInfo's flavor map now has a pointer value
instead of a struct. This allows us to set it to nil when the flavor is not found in openstack.
> Bug 1887863: Patch Flavor Not Found validation for OpenStack Install Config

- pkg/destroy/azure/azure.go
In Azure, while trying to delete public and private DNS zones,
ignore error if resource group was already deleted. This will
ensure that if the resource group wasn't created, or if it was
deleted before attempting destroy of cluster, it doesn't get
stuck in a loop.
> Bug 1888378: Ignore error if resource group already deleted 

- cmd/openshift-install/create.go
- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/route/routeapihelpers/routeapihelpers.go
- vendor/modules.txt
Using the helper from openshift/library-go#911, so we:
* No longer hard-code `https://`.  It's calculated based on the route's TLS config.
* No longer assume that the available ingress host will match the route's `spec.host`.
* No longer assume that the route is admitted.  Now we check the ingress conditions to confirm `Admitted=True`.
```console
$ emacs cmd/openshift-install/create.go # everything in the diff
$ go get github.com/openshift/library-go@f360b9835cc8815eccc26cb52dafe05d3cbb3e93
go: github.com/openshift/library-go f360b9835cc8815eccc26cb52dafe05d3cbb3e93 => v0.0.0-20201006230840-f360b9835cc8
go: downloading github.com/openshift/library-go v0.0.0-20201006230840-f360b9835cc8
$ go mod tidy
...
github.com/openshift/installer/cmd/openshift-install imports …
```
> cmd/openshift-install/create: Use library-go's IngressURI helper

- images/baremetal/Dockerfile.ci
The latest version of RHEL ships with libvirt 6.x, which are now in
yum repositories used to build the CI containers. However, when running
an installer built that's linked against it on an older RHEL host, the
installer fails:
```
$ ocp/ostest/openshift-baremetal-install --dir ocp/ostest --log-level=debug create manifests
ocp/ostest/openshift-baremetal-install: /lib64/libvirt.so.0: version
```LIBVIRT_5.2.0' not found (required by
ocp/ostest/openshift-baremetal-install)
[...snip...]
```
According to the [RHEL 8 ABI Guarantees](access.redhat.com/articles/rhel8-abi-compatibility),
"an application is only guaranteed to run correctly if it executes in an
environment that is as new as the environment it was built in or newer."
Therefore, we must build openshift baremetal installer against the …
```
> Bug 1894144: baremetal: pin libvirt to 4.5.0

- pkg/asset/installconfig/gcp/gcp.go
Corrects oversight where GCP survey was not handling CTRL+C.
> Bug 1855351: Handle CTRL+C in GCP survey

- pkg/asset/installconfig/platformcredscheck.go
This commit wraps an error after creds validation to comply with the other platforms.
> Wrap errors after OpenStack creds validation

- docs/user/openstack/README.md
- docs/user/openstack/customization.md
- pkg/asset/installconfig/openstack/validation/machinepool.go
- pkg/asset/installconfig/openstack/validation/machinepool_test.go
- pkg/asset/installconfig/openstack/validation/platform.go
It is possible to boot a server without using ephemeral storage, with
boot from volume:
https://docs.openstack.org/cinder/latest/admin/blockstorage-boot-from-volume.html
This patch will disable flavor storage check if rootVolume is used in
the Machine Pool and checks that the volume is at least 25Gb sized.
https://bugzilla.redhat.com/show_bug.cgi?id=1891543
> Bug 1891543: openstack: consider volumes for storage requirements checks

- data/data/manifests/bootkube/cvo-overrides.yaml.template
- docs/user/troubleshooting.md
Not bug-worthy, but floating now for 4.7 to centralize discussion.
The cluster-version operator has been falling back to a default URI when the ClusterVersion upstream is empty since [way][1] [back][2], and this behavior is [enshrined in the API][3].  Drop the installer-side
opinion, so:
* There is a single location where we version-control the default upstream (the CVO).
* Folks consuming in-cluster ClusterVersion objects have one less property to distract them (unless they want to override the default, in which case it's not distracting).
Related to openshift/openshift-docs#22252.
CC @vrutkovs , since I'm not sure how this will square with FCOS and a71f4245a.  FCOS options:
1. Continue to override the CVO default with explicit ClusterVersion.  No change from today, but breaks [nominal …
> data/manifests/bootkube/cvo-overrides: Drop the explicit upstream

- OWNERS_ALIASES
This adds @dhellmann as an approver/reviewer for baremetal IPI.
Currently, there's only two approvers which can create issues when one
of us in unavailable and the other has an open PR.
> owners: add dhellmann to baremetal-approvers/reviewers

- data/data/rhcos-amd64.json
- data/data/rhcos.json
- pkg/rhcos/ami_regions.go
There are RFEs requesting support for additional AWS regions:
ap-east-1, af-south-1, and eu-south-1
https://issues.redhat.com/browse/RFE-903
https://issues.redhat.com/browse/RFE-1267
The existing 4.6 RHCOS AMI was manually copied to these regions by the
ART team.
> Bug 1889855: additional AWS regions for RHCOS AMIs

- data/data/manifests/bootkube/cvo-overrides.yaml.template
Like f8a0f7b069 (#3848), but for 4.7 (now that release-4.6 is no longer being fast-forwarded to track master).
> data/manifests/bootkube/cvo-overrides: Bump default to stable-4.7

- data/data/bootstrap/files/usr/local/bin/installer-gather.sh
Using [`exec`][1] and [Bash's process substitution][2] to redirect both stdout and stderr into [`tee`][3].  `tee` will copy them to the original stdout, and will also write them to a file in the artifacts directory.   The artifacts directory is subsequently tarred up, and the tarball will contain the tee-written copy of the script's logs.
[1]: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#exec
[2]: https://www.gnu.org/software/bash/manual/html_node/Process-Substitution.html#Process-Substitution
[3]: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/tee.html
> data/bootstrap/files/usr/local/bin/installer-gather: Tee logs into tarball

- docs/user/openstack/install_upi.md
- Update package names for Fedora, now python3
- Replace the usage of swiftclient by openstackclient
for container/object creates (which uses clouds.yaml)
- Fix logs alignment
> doc/openstack/UPI: improvements

- pkg/asset/cluster/aws/aws.go
ResourceTagging API is not available for C2S use case. This switches from tagging shared subnets with ResourceTagging API to EC2 API.
[CORS-1580](https://issues.redhat.com/browse/CORS-1580)
> pkg/asset/cluster/aws: switch to ec2 tagging API

- pkg/asset/installconfig/azure/mock/azureclient_generated.go
- pkg/asset/installconfig/gcp/client.go
- pkg/asset/installconfig/gcp/mock/gcpclient_generated.go
- pkg/asset/installconfig/gcp/validation.go
- pkg/asset/installconfig/gcp/validation_test.go
Ensure the user provided instance types meets minimum resource
requirements.
> asset/installconfig/gcp: Validate install-config instance types

- docs/user/azure/install_upi.md
Fix `az group deployment` deprecated command replacing it with `az deployment group`, in line with OCP 4.6 product docs.
> Bug 1886435: Fix azure UPI az group deployment deprecation

- data/data/aws/route53/base.tf
We cannot create ALIAS records to the NLBs in C2S cloud partition, which includes `us-iso-east-1`. So we switch to using CNAME for our api records in that region.
> data/data/aws/route53: use CNAME for us-iso-east-1 region

- data/data/baremetal/bootstrap/main.tf
- data/data/libvirt/bootstrap/main.tf
The FCOS/RHCOS difference of 8GB vs 16GB is something
I'd eventually like to fix by making RHCOS 8GB too for
consistency.
The installer can easily resize.
> libvirt: Bump bootstrap size (primarily for OKD)

- cmd/openshift-install/create.go
I noticed this while reading CI logs.
> Fix 'troubleshooting' typo

- docs/user/openstack/kuryr.md
Update the Neutron quotas now required when Kuryr is used at the
networking plugin for an OCP cluster.
The numbers were taken from:
https://docs.openshift.com/container-platform/4.6/installing/installing_openstack/installing-openstack-user-kuryr.html#installation-osp-default-kuryr-deployment_installing-openstack-user-kuryr
and confirmed with the Kuryr team.
It updates the table and the command that updates the quotas so the
reader won't be confused nor set the wrong quotas, which lead to a
failed deployment of that type: http://paste.openstack.org/show/799839/
> doc/openstack: update quota reqs for kuryr

- upi/aws/cloudformation/02_cluster_infra.yaml
Docs for UPI installations are now auto-updated from the reference implementation in this repo. So add the health checks which are called out in the [release notes](https://docs.openshift.com/container-platform/4.5/release_notes/ocp-4-5-release-notes.html#ocp-4-5-notable-technical-changes).
This backports #3709 and #3757 
/cc @mtnbikenc @codyhoag
> Bug 1876581: upi/aws Define load balancer health checks

- data/data/bootstrap/files/usr/local/bin/installer-gather.sh
In installer log-gathers, we see this error:
```
rm: cannot remove '/tmp/artifacts-20201104213542/rendered-assets/openshift/etcd-bootstrap/bootstrap-manifests/secrets': Is a directory
```
The secrets directory is attempted to be removed by simple `rm` command which cannot remove directories without the recursive flag.
> Remove the secrets directory recursively

- pkg/asset/installconfig/aws/permissions.go
- pkg/asset/installconfig/platformpermscheck.go
Create a new permissions group for destroying a shared-network cluster. These clusters require permissions to untag the shared networks. This check is skipped in the case of C2S, because delete is not supported.
The solution will need to be slightly different for pre 4.7 as Tags are needed for cluster create and obviously there is no C2S support.
> Bug 1888464: add tag:UnTagResource perm for aws shared networks

- data/data/install.openshift.io_installconfigs.yaml
- pkg/types/conversion/installconfig.go
- pkg/types/installconfig.go
Now some functions in "conversion" module are public but they are used only inside the module, so it is reasonable to make them
private.
Also this commit fixes typos in deprecated properties descriptions.
> Cleanup: make conversion functions private

- pkg/tfvars/baremetal/baremetal.go
This setting is no longer required as the linked ironic issue that
required specifying a root disk size when using whole disk images
has been fixed.
> baremetal: remove root_gb from tfvars

- pkg/asset/installconfig/openstack/validation/platform.go
- pkg/asset/installconfig/openstack/validation/platform_test.go
Flavors are validated in machine pools already, therefore it is
redundant to also check computeFlavor at the platform level.
This patch removes the computeFlavor validation at the platform
level, since this flavor would already be checked during machine
pool validation.
The installer generates machine pools for both masters and workers.
If the flavor isn't found at the machine pool level, it'll take
platform.computeFlavor, so we don't loose validation coverage.
https://bugzilla.redhat.com/show_bug.cgi?id=1891543
Related: #4323
> Bug 1891543: openstack: remove platform flavor validation

- data/data/bootstrap/baremetal/README.md
Fixed the typo under data/data/bootstrap/baremetal/README.md 
To have a better reader experience  fixed this typo.
> Correcting normal typos

- docs/user/openstack/install_upi.md
- images/openstack/Dockerfile.ci
Document the use of ansible-galaxy as a dependency manager for the
Ansible playbooks in UPI.
Implements [OSASINFRA-2169](https://issues.redhat.com/browse/OSASINFRA-2169)
> openstack UPI: Use ansible-galaxy

- pkg/destroy/vsphere/vsphere.go
- pkg/terraform/exec/plugins/vsphereprivate/resource_vsphereprivate_import_ova.go
Adjusts vSphere destroy code to handle cases when cluster create was  terminated early, particularly if interrupted before OVA is completely downloaded. This commit moves the tagging of the OVA template before the data upload, because the template was not getting tagged if the upload did not commit. See details below.
Also, prior to this change, destroy would stop if no VMs or folders were found, but this updates the flow to allow best effort to destroy all resources.
Finally, updates caps to be consistent with other standard logger output.
Import OVA & Destroy Details:
If one hard terminates the installer during a template import, the import continues in the vCenter for some period of time afterward (I would estimate at five minutes).
This will block the deletion of the template, but in …
> Bug 1889779: vSphere destroy: handle failed clusters

- pkg/asset/installconfig/openstack/validation/platform.go
This structure contains default values that will be inserted in machine sets for masters and workers if some values there are
omitted. Since we validate these machine sets anyway, we can stop doing it for DefaultMachinePlatform, so as not to do the
work twice.
> Stop validating DefaultMachinePlatform

- data/data/install.openshift.io_installconfigs.yaml
- pkg/types/baremetal/platform.go
- pkg/types/baremetal/validation/platform_test.go
- pkg/validate/validate.go
- pkg/validate/validate_test.go
When users specify a custom MAC address for the provisioning and
baremetal bridges of the libvirt bootstrap host, libvirt complains
if the user does not give a unicast MAC address:
`
020-11-13 10:52:18 level=debug msg=2020/11/13 10:52:18 [ERROR]
module.bootstrap: eval: *terraform.EvalApplyPost, err: Error defining
libvirt domain: virError(Code=27, Domain=20, Message='XML error:
expected unicast mac address, found multicast '7D:CE:E3:29:35:6F'')
')
`
This adds a function that validates whether a MAC address is unicast. A
multicast MAC address is one where the most significant byte has a least
significant bit of `1`.
Example 1: Multicast MAC
------------------------
7D:CE:E3:29:35:6F
^--> most significant byte
0x7D is 0b11111101
^--> this is a multicast MAC
Example 2: Unicast MAC …
> baremetal: validate that macs are EUI-48 and unicast

- data/data/ovirt/template/main.tf
This PR adds a timeout of 20m to the tmp_import_vm resource
> Bug 1894432: oVirt, add timeout to tmp_import_vm

- data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
- pkg/asset/ignition/bootstrap/bootstrap.go
- pkg/asset/manifests/infrastructure.go
- pkg/asset/manifests/utils.go
etcd has not been using DNS entries since 4.4 and EtcdDiscoveryDomain has been a redundant flag. This PR attempts to get rid of the unused flag.
This is an attempt to get https://github.com/openshift/installer/pull/4024 split into smaller PRs to understand the build errors.
> Bug 1813012: Remove unused etcd discovery domain

- docs/user/openstack/add_worker_nodes_by_hand.md
When adding worker nodes via ansible playbooks
there re certain settings that  need to be configure on the node.
> Bug 1848945: OpenStack - Documentation for adding worker nodes using ansible

- pkg/asset/installconfig/openstack/validation/platform.go
- pkg/asset/installconfig/openstack/validation/platform_test.go
Patches  [OSASINFRA-2178](https://issues.redhat.com/browse/OSASINFRA-2178) where the user is able to pass the same floating IP to the API and Ingress FIP in the install config.
> Bug 1898238: Validate the the API and Ingress FIPs are not the same

- data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
- pkg/asset/cluster/tfvars.go
- pkg/asset/ignition/bootstrap/baremetal/template.go
- pkg/types/baremetal/defaults/platform_test.go
- pkg/types/baremetal/validation/platform.go
- pkg/types/baremetal/validation/platform_test.go
This is needed by the assisted installer, so that it does not have to create static ips.
/cc @zaneb @hardys
> baremetal: when networking is disabled make the bootstrap provisioning ip optional

- pkg/asset/installconfig/gcp/client.go
- pkg/asset/installconfig/gcp/mock/gcpclient_generated.go
- pkg/asset/installconfig/gcp/validation.go
- pkg/asset/installconfig/gcp/validation_test.go
Prior to this change, the validation on gcp instance types would return
an error that the type did not exist. This change adds the logic to
properly handle custom machine types while validating their CPU and
Memeory values.
> Bug 1898194: installconfig/gcp/validation: handle custom machine types

- pkg/asset/installconfig/ovirt/config.go
- pkg/asset/installconfig/ovirt/ovirt.go
This PR fixes an issue when running the installer on ovirt with an already existing, but invalid `ovirt-config.yaml`. Previously, the installer did not allow the user to re-enter the credentials in this case. This patch fixes that.
```
? Platform ovirt
FATAL failed to fetch Install Config: failed to fetch dependency of "Install Config": failed to fetch dependency of "Base Domain": failed to generate asset "Platform": The Password must not be empty
```
```
? Platform ovirt
{{WARNING found invalid existing ovirt configuration (Error during SSO authentication access_denied : Cannot authenticate user 'admin@N/A': No valid profile found in credentials..) }}
? Engine FQDN[:PORT] [? for help]
```
> pkg: validation for previously existing ovirt configuration

- pkg/asset/machines/baremetal/machines.go
- pkg/tfvars/baremetal/baremetal.go
The image filename suffix is different for OKD so we need to
handle both gz and xz here
> baremetal: Handle xz filenames for OKD

- data/data/openstack/main.tf
- data/data/openstack/topology/private-network.tf
- data/data/openstack/topology/variables.tf
Assign the user-defined additional security groups to the Control Plane
port.
Fixes [Bug 1899853](https://bugzilla.redhat.com/show_bug.cgi?id=1899853)
> Bug 1899853: openstack: CP nodes port to use addtional SGs

- pkg/asset/installconfig/ovirt/client.go
- pkg/asset/installconfig/ovirt/config.go
- pkg/asset/installconfig/ovirt/validation.go
This pull request changes the oVirt/RVH installer to use the certificate downloaded from the oVirt engine and verified by the user. It eliminates the need for the user to add the certificate to the trust root on their system.
This PR is based on #4354 and fixes [Bugzilla#1895874](https://bugzilla.redhat.com/show_bug.cgi?id=1895874).
> $ openshift-install create install-config
> ? Platform ovirt
> ? Engine FQDN[:PORT] engine.example.com
> INFO Loaded the following PEM file:
> INFO    Version: 3
> INFO    Signature Algorithm: SHA256-RSA
> INFO    Serial Number: 4096
> INFO    Issuer: CN=engine.example.com.39197,O=example.com,C=US
> INFO    Validity:
> INFO            Not Before: 2020-08-11 13:50:26 +0000 UTC
> INFO            Not After: 2030-08-10 13:50:26 +0000 UTC
> INFO    Subject: …
> Bug 1895874: Use oVirt Engine certificate verified by the user for installation

- pkg/asset/machines/baremetal/machines.go
> baremetal: correct the cacheImageURL when we don't have a provisioningIP

- data/data/rhcos-amd64.json
- data/data/rhcos-ppc64le.json
- data/data/rhcos-s390x.json
- data/data/rhcos.json
This includes fixes for the following bugs:
- https://bugzilla.redhat.com/show_bug.cgi?id=1899289
- https://bugzilla.redhat.com/show_bug.cgi?id=1899361
- https://bugzilla.redhat.com/show_bug.cgi?id=1899286
- https://bugzilla.redhat.com/show_bug.cgi?id=1901021
```
$ ./differ.py --first-endpoint art --first-release [rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0 \
--second-endpoint art --second-release [rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0
{
"sources": {
"[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.6/46.82.202010011740-0/x86_64/commitmeta.json",
"[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.2020112 …
```
> Bug 1899176: Bump RHCOS bootimages to 46.82.202011260640-0

- docs/user/openstack/README.md
The underlying network architecture has changed a lot since these docs
were initially written. We want to make sure that these docs are accurate
and up to date so that users with complex networking use cases like workers
on a custom subnet and baremetal workers are able to manage their ingress/egress
traffic as needed. More up to date examples and reference information has been added.
We have chosen to omit sections outlining how to replace the internal lb and dns
services since they were inaccurate. We are targeting an upcoming release to handle
these features better given the complexity of our current networking architecture.
> OSASINFRA-902: Update OpenStack Custom External LB and DNS Docs

- docs/user/vsphere/privileges.md
This updates vSphere docs to provide more information about permissions. We can see in a lot of cases (https://bugzilla.redhat.com/show_bug.cgi?id=1869035) that when admins are not granting Global Permissions they are neglecting
to assign minimum priveleges to the vSphere itself.
cc @jcpowermac @gnufied @bobfuru 
related to openshift/openshift-docs#27328
> vSphere Docs: Update to include Permissions

- pkg/types/baremetal/validation/platform.go
- pkg/types/baremetal/validation/platform_test.go
This makes the cluster provisioning IP optional when the provisioning
network is disabled. If no provisioning IP is provided, then we use
the host IP of the node we're running on.
This is dependent on the work in https://github.com/openshift/cluster-baremetal-operator/pull/73
and https://github.com/openshift/cluster-baremetal-operator/pull/76
> baremetal: make cluster provisioning IP optional

- pkg/asset/releaseimage/default.go
Align the default release image with the current development version.
> Set default release image to 4.7

- pkg/destroy/aws/aws.go
Even though the destroyer cannot directly delete the default security group, the destroyer still needs to remove the ingress and egress rules from the default security group. There could be rules on the default security group that source another security group, which would block the destroyer from deleting that other security group.
https://bugzilla.redhat.com/show_bug.cgi?id=1903277
> Bug 1903277: destroy/aws: remove rules from default security group

- pkg/asset/installconfig/openstack/validation/platform.go
- pkg/asset/installconfig/openstack/validation/platform_test.go
Flavors are validated in machine pools already, therefore it is
redundant to also check computeFlavor at the platform level.
This patch removes the computeFlavor validation at the platform
level, since this flavor would already be checked during machine
pool validation.
The installer generates machine pools for both masters and workers.
If the flavor isn't found at the machine pool level, it'll take
platform.computeFlavor, so we don't loose validation coverage.
Reference: #4383
JIRA: [OSASINFRA-2146](https://issues.redhat.com/browse/OSASINFRA-2146)
[BZ#1899161](https://bugzilla.redhat.com/show_bug.cgi?id=1899161)
> Bug 1899161: Cherry-Pick: openstack: remove platform flavor validation

- data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
- data/data/bootstrap/baremetal/files/usr/local/bin/stopironic.sh
- docs/user/metal/install_ipi.md
A new entrypoint has been added to the ironic containers
that watches for deploy ramdisk logs in the shared volume
and exposes them via the regular podman logs output.
https://github.com/openshift/ironic-inspector-image/pull/47/
https://github.com/openshift/ironic-image/pull/121/
This should make it easier for users debugging as they no longer
need to exec into the containers and have knowledge of the
internal logfile location.
> baremetal: Add ironic logwatch containers

- docs/design/openstack/networking-infrastructure.md
Removed a lot of template duplication in the mco repo, so we need to reflect those changes here
Referring to the following commits:
- https://github.com/openshift/machine-config-operator/commit/eb9ee782506204b78cf82c7ea9405b26c07f8315
- https://github.com/openshift/machine-config-operator/commit/1236612f5b22bb478f464f414532c57e97e74939
> [DOC] Update MCO doc references

- pkg/asset/installconfig/azure/client.go
- pkg/asset/installconfig/azure/mock/azureclient_generated.go
- pkg/asset/installconfig/azure/validation.go
- pkg/asset/installconfig/azure/validation_test.go
Ensure the user provided instance types meets minimum resource
requirements.
> asset/installconfig/Azure: Validate install-config instance types

- data/data/baremetal/main.tf
- data/data/baremetal/masters/main.tf
- data/data/baremetal/masters/variables.tf
- data/data/baremetal/variables-baremetal.tf
- go.mod
- go.sum
- pkg/asset/cluster/tfvars.go
- pkg/tfvars/baremetal/baremetal.go
- vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/resource_ironic_deployment.go
- vendor/modules.txt
This restores the work which was previously done via #3276 but then reverted via #3589 due to breaking users who customized the pointer ignition config in IPI deployments.
A solution to that has been proposed via https://github.com/openshift/installer/pull/4413 which this PR depends on, so when that lands this work can safely be restored, see openshift/enhancements#540 for more details.
Note that some additional changes beyond the initial implementation were required due to the MCO now supporting multiple
ignition versions, thus this PR depends on https://github.com/openshift-metal3/terraform-provider-ironic/pull/46 which will need to land and be vendored here before the PR merges.
This replaces https://github.com/openshift/installer/pull/4359
> baremetal: send full ignition to masters

- pkg/destroy/vsphere/vsphere.go
Prints Info message when tag and tag categories are successfully destroyed.
/test e2e-vsphere
> vSphere Destroy: add log messages for tag destruction

- data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
- pkg/asset/ignition/bootstrap/bootstrap.go
This PR adds the ability to pass CLUSTER_PROFILE as env var to the installer which will be propagated as env var to the CVO rendering.
Following the enhancements:
https://github.com/openshift/enhancements/pull/200
https://github.com/openshift/enhancements/pull/543
Signed-off-by: Ravid Brown <ravid@redhat.com>
> Pass CLUSTER_PROFILE env var to CVO render

- pkg/asset/manifests/cloudproviderconfig.go
- pkg/asset/manifests/openstack/cloudproviderconfig.go
- pkg/asset/manifests/openstack/cloudproviderconfig_test.go
Move OpenStack platform-specific code in the platform package to
increase ownership and leave a clean API footprint on the orchestrating
logic.
Implements [OSASINFRA-2195](https://issues.redhat.com/browse/OSASINFRA-2195)
> cloudproviderconfig: Refactor openstack

- data/data/install.openshift.io_installconfigs.yaml
- docs/user/metal/customization_ipi.md
- pkg/types/baremetal/platform.go
- pkg/types/baremetal/validation/platform.go
- pkg/types/conversion/installconfig.go
- pkg/types/conversion/installconfig_test.go
The ClusterProvisioningIP field in the baremetal platform had an
incorrect JSON annotation for serialization/deserialization, using
"provisioningHostIP" instead of "clusterProvisioningIP." This name is
incorrect and doesn't adequately reflect it's purpose. This field is
the IP used in the cluster for provisioning.
This commit deprecates the old JSON field, and uses the correct JSON
annotation for ClusterProvisioningIP.
> Bug 1868748: baremetal: rename JSON field for ClusterProvisioningIP

- data/data/baremetal/bootstrap/main.tf
Currently in the 'baremetal' platform, we use a customized TF-created storage volume with the following naming convention: `<clustername>.<id>.bootstrap` and this volume is used to store the bootstrap VM images. Since the libvirt_ignition resources was introduced, it has been defaulting to the `default` libvirt storage pool.
This PR ensures that the libvirt_ignition TF resource uses the above mentioned customized libvirt storage pool.
> Bug 1904125: Ensure the bootstrap ignition libvirt pool defaults to <clustername>.<id>.bootstrap rather than 'default'

- data/data/install.openshift.io_installconfigs.yaml
- docs/user/openstack/customization.md
- pkg/asset/cluster/tfvars.go
- pkg/tfvars/openstack/openstack.go
- pkg/tfvars/openstack/rhcos_image.go
- pkg/types/openstack/platform.go
ClusterOSImageProperty is a list of properties to be added to the cluster OS glance image metadata. 
example usage
platform:
openstack:
clusterOSImageProperties:
hw_qemu_guest_agent: yes
hw_scsi_model: virtio-scsi
implementes [OSASINFRA-1980](https://issues.redhat.com/browse/OSASINFRA-1980)
> OpenStack: Adds clusterOSImageProperties to install-config.yaml

- docs/user/openstack/README.md
- pkg/asset/installconfig/openstack/validation/cloudinfo.go
- pkg/asset/quota/openstack/OWNERS
- pkg/asset/quota/openstack/openstack.go
- pkg/asset/quota/quota.go
- pkg/quota/quota.go
Note: openshift-installer already check quotas for AWS and GCP.
1) Calculate the quota constraints based on the InstallConfig.
For both ControlPlane and workers, get the flavors and
create a list of quota resources that will be needed to
successfully deploy the cluster.
Note: for now, only instances, CPUs and RAM are supported.
In the future, we'll add networking and storage resources.
2) Fetch project quotas by using OpenStack API (via gophercloud)
and create the constraints (for instances, CPUs and RAM only
for now).
The Quota constraints will be stored in the CloudInfo struct,
for caching so we avoid multiple calls to the OpenStack APIs
to get quotas.
3) The logging is improved when there is no region name for
a cloud provider.
Fixes: …
> openstack: check quotas before creating cluster

- OWNERS_ALIASES
- data/data/bootstrap/files/etc/systemd/system.conf.d/10-default-env-godebug.conf.template
- data/data/bootstrap/vsphere/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender.template
- data/data/fcos-amd64.json
- data/data/fcos.json
- data/data/rhcos-amd64.json
- data/data/rhcos-ppc64le.json
- data/data/rhcos-s390x.json
- data/data/rhcos.json
- docs/user/openstack/install_upi.md
- images/baremetal/Dockerfile.ci
- pkg/asset/installconfig/openstack/validation/platform.go
- pkg/asset/installconfig/openstack/validation/platform_test.go
- pkg/asset/machines/master.go
- pkg/asset/machines/worker.go
- pkg/asset/manifests/openshift.go
- pkg/rhcos/ami_regions.go
- upi/openstack/bootstrap.yaml
- upi/openstack/down-bootstrap.yaml
- upi/openstack/inventory.yaml
Created with
```
TARGET_COMMIT=$(git describe --tags fcos | sed 's/.*-g//')
git checkout -b fcos-rebase-dec5 origin/release-4.6
git rebase --onto fcos $TARGET_COMMIT
```
This also updates FCOS images to latest stable (32.20201104.3.0)
> [FCOS] Rebase `fcos` on release-4.6

- docs/user/ovirt/install_ipi.md
- pkg/asset/installconfig/ovirt/credentials.go
[This change](https://bugzilla.redhat.com/show_bug.cgi?id=1900138) removes support for the insecure mode from the oVirt installer. Previously, when no certificate could be obtained from the oVirt engine the installer would proceed without certificate verification. This PR is based on #4387 and **depends on [OCPRHV-426](https://issues.redhat.com/browse/OCPRHV-426)**.
Due to recent improvements this is no longer a valid use case and is being deprecated. The user is instead presented with a message explaining the situation and linking to the to-be-written documentation. If the user wants to use insecure mode they have to create a file named `~/.ovirt/ovirt-config.yaml` with the following contents before running the installer:
```yaml
ovirt_url: https://ovirt.example.com/ovirt-engine/api …
```
> Bug 1900138: Removed support for insecure mode for oVirt/RHV installation

- pkg/asset/installconfig/openstack/validate.go
Skip pre-flight validations when the development-only variable
`OS_SKIP_PREFLIGHT_VALIDATIONS=1` is found in the environment.
Skipping pre-flight validations is essential to testing manifest
generation when the exotic settings under test are not available in the
CI infrastructure.
Implements [OSASINFRA-2194](https://issues.redhat.com/browse/OSASINFRA-2194)
> openstack: Allow to skip pre-flight validations

- hack/openstack/OWNERS
- hack/openstack/test-manifests.sh
- images/openstack/Dockerfile.ci
- scripts/openstack/OWNERS
- scripts/openstack/manifest-tests/additional-security-group/install-config.yaml
- scripts/openstack/manifest-tests/additional-security-group/test_masters.sh
- scripts/openstack/manifest-tests/additional-security-group/test_workers.sh
Add a script for testing OpenStack manifest generation.
Co-Authored-By: Matthew Booth <mbooth@redhat.com>
> openstack: Test manifest creation

- data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
- data/data/rhcos-amd64.json
- data/data/rhcos-ppc64le.json
- data/data/rhcos-s390x.json
- data/data/rhcos.json
amd64:   47.83.202012030221-0
s390x:   47.83.202012030410-0
ppc64le: 47.83.202012030110-0
> Bug 1899175: data/rhcos.json: Update boot images for RHEL 8.3

- data/data/gcp/bootstrap/main.tf
- data/data/gcp/bootstrap/variables.tf
- data/data/gcp/main.tf
- data/data/gcp/master/main.tf
- data/data/gcp/master/variables.tf
- data/data/gcp/variables-gcp.tf
- pkg/asset/machines/gcp/machines.go
- pkg/tfvars/gcp/gcp.go
This commit ensures encryption values are properly
populated into terraform and machines/machinesets.
> GCP: populate encryption values into tf and machines

- hack/verify-vendor.sh
Prior to this patch, errors in vendoring or verification were ignored.
With this patch, `verify-vendor` fails if the dependency files are
corrupted.
> hack/verify-vendor.sh: Fail early if error

- pkg/asset/manifests/openshift.go
When `credentialsMode` is set to `Manual` the user is responsible for providing the credentials into the cluster. Do not create the cloud Secret when the install-config indicates `Manual`.
For installing on AWS with temporary credentials, this means we no longer install a Secret with creds that will expire and never be updated.
Ref: https://issues.redhat.com/browse/CO-1249
> do not generate the cloud cred secret when credentialsMode is Manual

- pkg/asset/ignition/machine/master_ignition_customizations.go
- pkg/asset/ignition/machine/master_ignition_customizations_test.go
- pkg/asset/ignition/machine/worker_ignition_customizations.go
- pkg/asset/ignition/machine/worker_ignition_customizations_test.go
An issue was spotted after #4413 landed, the config comparison
always evaluates to true, so we're generating empty machineconfig
objects even when no customization has happened.
Update to compare a json representation of the configs, and add
a test to confirm all works as expected.
> Bug 1904663: Fix comparison in pointer ignition customization asset

- docs/user/openstack/install_upi.md
implements [OSASINFRA-2191](https://issues.redhat.com/browse/OSASINFRA-2191)
> Openstack: describes how to enable qemu agent for UPI.

- pkg/asset/installconfig/openstack/validation/cloudinfo.go
- pkg/quota/quota.go
In OpenStack, if a quota resource is limited to "-1", it means that it's
unlimited. It's the case of a lot of OpenStack clouds, were quotas
aren't defined for all projects and by default "-1" is used.
This patch will ignore a quota record if its limit is set to "-1".
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1906459
Signed-off-by: Emilien Macchi <emilien@redhat.com>
> Bug 1906459: openstack: fix quota checks when they're unlimited

- pkg/destroy/aws/aws.go
HostedZone may already be removed and causes destroy to get stuck.
> Bug 1890228: pkg/destroy/aws: Pass destroy if HostedZone does not exist

- pkg/asset/installconfig/aws/permissions.go
- pkg/asset/installconfig/platformpermscheck.go
This is a small rewrite of #4371 for release-4.6 
Create a new permissions group for creating & destroying a shared-network cluster.
These clusters require permissions to tag and untag the shared networks.
This could be cherry picked to previous branches.
> Bug 1898172: add tagging perms for aws shared networks

- docs/user/openstack/known-issues.md
This commit documents the correct value that should be set to enable ignore-volume-az option in the cloud provider.
> Bug 1908280: update docs for Cinder AZs

- pkg/asset/installconfig/openstack/validation/cloudinfo.go
Some clouds may return a generic 404 error instead of an
`ErrResourceNotFound` error, causing the installer to fail with:
FATAL failed to fetch Install Config: failed to generate asset "Install Config": failed to generate OpenStack cloud info: failed to fetch machine subnet info: Resource not found
We need to not gather subnet information unless a machine subnet was
provided.
> Bug 1906517: OpenStack: Skip collecting info for empty subnet IDs

- docs/user/openstack/README.md
- docs/user/openstack/customization.md
Due to the addition of the PrimarySubnets variable in the providerSpec
we wanted to ensure that users knew it existed and of its pitfalls.
Fixes: [OSASINFRA-2088](https://issues.redhat.com/browse/OSASINFRA-2088)
/cc @maxwelldb
> Bug 1907628: OpenStack Documentation for MachineSets with Multiple Networks

- data/data/gcp/bootstrap/main.tf
- data/data/gcp/master/main.tf
Similar to previous bug (see below) but in this case for custom machine types. In the previous bz, the config generated by Terraform did not match the resource that was ultimately created. So when apply is run a second time for bootstrap destroy, an error occurs when TF tries to switch the resource back to match the config.
Similar: fdefcca25cb12fc241198b0688f421411c9a580a
The error message states:
```
"Error: Changing the machine_type, min_cpu_platform, service_account, or enable display on a started instance requires stopping it.
```
We could potentially add `service_account` and `enable display` (however that is handled in TF) to prevent this error from happening in those cases, but I chose to opt for the minimal change and wait and see if those become a problem.
> Bug 1908171: fix Terraform issue with GCP custom machine types

- pkg/asset/installconfig/openstack/validation/cloudinfo.go
- pkg/asset/installconfig/openstack/validation/machinepool.go
- pkg/asset/installconfig/openstack/validation/machinepool_test.go
Flavors are always added to the Flavors map, however if they are not found
the flavor pointer is nil. Corrected the code logic to account for this.
Bug 1894678
Backports https://github.com/openshift/installer/pull/4289
> Bug 1894678: Patch Flavor Not Found validation for OpenStack Install Config

- data/data/aws/vpc/sg-master.tf
- data/data/aws/vpc/sg-worker.tf
- data/data/gcp/network/firewall.tf
- data/data/openstack/topology/sg-master.tf
- data/data/openstack/topology/sg-worker.tf
Enable ESP and IKE traffic across all installer targets between
worker and master nodes.
This is required to resolve https://bugzilla.redhat.com/show_bug.cgi?id=1908782 which is required to enable key feature for OCP 4.7 (OVN Kubernetes IPsec)
Signed-off-by: Mark Gray <mark.d.gray@redhat.com>
> Bug 1908782: terraform: Add rules to allow internal IPsec traffic

- docs/user/openstack/install_upi.md
- images/openstack/Dockerfile.ci
This reverts commit 0388ceaa95616c2411727867630da879316d6593 (https://github.com/openshift/installer/pull/4379).
Fixes Bug 1910049
/cc EmilienM maxwelldb mandre mdbooth
> Bug 1910049: Revert "openstack UPI: Use ansible-galaxy"

- go.mod
- go.sum
- vendor/github.com/gophercloud/utils/internal/util.go
- vendor/modules.txt
This patch introduces recent optimizations for tls config generation.
1. Now the library ignores the fact the CA certificate can be broken
(if it can't parse it for some reason, it just leaves an empty string
without a notice). From now we raise an error in this case.
2. It tries to prevent some obvious formatting errors in the certificate
like leading and trailing spaces, additional new lines etc.
> Bug 1786314: bump gophercloud/utils

- docs/user/kubevirt/role.yaml
When this verb is missing, although the cluster is created successfully,
the cluster behavior after the installation is wrong
(machine-controllers use the infra cluster credentials provided by the user)
> Bug 1913151: KubeVirt user docs: change role example - add "update" verb to VM

- data/data/openstack/masters/main.tf
This patch addresses the OpenStack issue where the Compute module won't
honour the soft-anti-affinity policy when servers are created
concurrently.
> Bug 1909587: openstack: Create Control plane nodes sequentially

- docs/user/openstack/install_upi.md
SRIOV docs had a typo in the port create example command. This command excluded the necessary statement "create".
> Bug 1914439: OpenStack Port Create Typo in SRIOV Docs

- data/data/openstack/bootstrap/main.tf
- data/data/openstack/bootstrap/variables.tf
- data/data/openstack/main.tf
The bootstrap node was only being attached to the private network created by the installer,
causing deployments with more advanced networking topologies that made use of the additional
networking feature to fail. The bootstrap needs to be attached to the same networks as the
control plane nodes in order to guarantee the install will succeed.
Fixes Bug 1908583
> Bug 1908583: Set same additional networks on Bootstrap as Control Plane

- pkg/asset/installconfig/azure/validation.go
This change fixes an issue where the memory values for azure instances were assumed to be integer while some of them were actually floating point values.
> Bug 1908468: azure/validation: some memory values are float and not int

- pkg/asset/installconfig/openstack/openstack.go
- pkg/asset/installconfig/openstack/session.go
- pkg/asset/installconfig/openstack/validation/cloudinfo.go
- pkg/asset/installconfig/openstack/validvaluesfetcher.go
- pkg/asset/machines/openstack/machines.go
- pkg/asset/machines/openstack/machinesets.go
- pkg/asset/machines/worker.go
- pkg/destroy/openstack/glance.go
- pkg/destroy/openstack/openstack.go
- pkg/tfvars/openstack/bootstrap_ignition.go
- pkg/tfvars/openstack/openstack.go
- pkg/tfvars/openstack/rhcos_image.go
- pkg/types/openstack/defaults/clientopts.go
This commit explicitly disables reading auth data from env variables by setting an invalid EnvPrefix. By doing this, we make sure that the data from clouds.yaml is enough to authenticate.
After this change we don't have to unset OS_CLOUD env variable explicitly anymore.
> Bug 1813949: ignore local env variables when we create a service client

- pkg/asset/machines/master.go
- pkg/asset/machines/singlemaster.go
In 4.6+ `authentication` operator needs additional setting to allow single kube-apiserver instance.
Fixes https://github.com/openshift/okd/issues/465
> [FCOS] pkg/asset/machines: include authentication setting for single master

- docs/user/openstack/README.md
- docs/user/openstack/customization.md
- pkg/asset/installconfig/openstack/validation/machinepool.go
- pkg/asset/installconfig/openstack/validation/machinepool_test.go
It is possible to boot a server without using ephemeral storage, with
boot from volume:
https://docs.openstack.org/cinder/latest/admin/blockstorage-boot-from-volume.html
This patch will disable flavor storage check if rootVolume is used in
the Machine Pool and checks that the volume is at least 25Gb sized.
https://bugzilla.redhat.com/show_bug.cgi?id=1899161
Signed-off-by: Emilien Macchi <emilien@redhat.com>
(cherry picked from commit 1b400b48f8face099ff9eeed92266ee32edf106e)
> Bug 1899161: openstack: consider volumes for storage requirements checks

- docs/user/openstack/known-issues.md
Add a note on the limitations of the soft-anti-affinity server group
that the installer creates.
> Bug 1916271: openstack known issues: ControlPlane anti-affinity

- data/data/openstack/bootstrap/main.tf
- data/data/openstack/bootstrap/variables.tf
- data/data/openstack/main.tf
- docs/user/openstack/customization.md
The bootstrap node in the installer does not have any way to set additional
networks and security groups. The installer currently adds additional control
plane networks to the bootrap node, and should do the same for security groups.
Since the bootstrap is an ephemeral node that has the same networking requirements
as the master nodes, this logically makes sense and makes the user experience more
consistent.
Fixes: Bug 1915998
> Bug 1915998: Set Additional Control Plane Security Groups on Bootstrap Node

- pkg/asset/manifests/proxy.go
since 4.4 etcd no longer has a dep on DNS. This PR removes code that populates noproxy with etcd records.
depends on: https://github.com/openshift/machine-config-operator/pull/2315
> Bug 1909502: pkg/asset/manifests: remove etcd records from proxy config

- pkg/asset/installconfig/clustername.go
- pkg/types/validation/installconfig.go
- pkg/validate/validate.go
Similar to OpenStack platform, we require to
validate cluster name size to avoid DNS resolution
issues in the deploy.
See also: https://github.com/openshift/installer/pull/2270/commits
> Bug 1915460: ovirt: validate cluster name during install

- pkg/asset/machines/singlemaster.go
Somehow this manifest avoided validation and created an invalid CR that got openshift-authentication-operator stuck permanently.
```
- lastTransitionTime: "2021-01-21T15:26:42Z"
message: |-
ManagementStateDegraded: Unsupported management state "" for authentication operator
OAuthAPIServerConfigObservationDegraded: error writing updated observed config: Authentication.operator.openshift.io "cluster" is invalid: spec.managementState: Invalid value: "": spec.managementState in body should match '^(Managed|Unmanaged|Force|Removed)$'
OAuthServerConfigObservationDegraded: error writing updated observed config: Authentication.operator.openshift.io "cluster" is invalid: spec.managementState: Invalid value: "": spec.managementState in body should match '^(Managed|Unmanaged|Force|Removed)$'
reason: …
```
> Fix Authentication manifest for SNO

- pkg/types/conversion/installconfig.go
- pkg/types/conversion/installconfig_test.go
In 4.7 LbFloatingIP was deprecated and renamed to APIFloatingIP.
But if we regenerate a config from 4.6 version, it doesn't unset the deprecated LbFloatingIP and both values are present in the new config, which leads to an error.
This commit allows to set both parameters in the config, but only if their values are equal.
> Bug 1916938: tolerate equal APIFloatingIP and LbFloatingIP

- docs/user/ovirt/install_upi.md
RHCOS image is not a requirement for Network.
> Bug 1917101: UPI ovirt - remove RHCOS image from Network req

- cmd/openshift-install/gather.go
- pkg/terraform/gather/ovirt/ip.go
during gather-bootstrap logs need to be gathered from the bootstrap node using ssh,
oVirt engine collects  node  IP information using the qemu-agent,
we are using oVirt SDK to retrieve this information and choose the correct IP which allows ssh connection.
> Bug 1810438: oVirt: Add missing piece for gathering bootstrap IP info

- scripts/maintenance/virsh-cleanup.sh
This will clean up all volumes under all non-default pools. The
openshift CI creates a pool for each cluster.
> maintenance: remove pools and volumes

- pkg/destroy/gcp/gcp.go
- pkg/destroy/gcp/policybinding.go
This updates GCP destroy code to remove IAM roles before deleting service accounts.
Service accounts are deleted one at a time but IAM roles are deleted by rewriting the entire policy. We are seeing conflicts (with two clusters in the same project) when one cluster is rewriting the IAM policy as another cluster deletes its service accounts. There is a conflict because the state of service accounts in the newly written policy is out-of-date.  By deleting the role bindings first, we decouple the service accounts from the IAM policy and avoid the conflicts.
> Bug 1896218: remove GCP role bindings before service accounts

- docs/user/openstack/known-issues.md
Now if we just set "ignore-volume-az = yes" in the config, users can't create PVs with the standard storage class. To workaround this issue users have to create another storage class with the `availability` parameter.
This commit documents how to do it.
> Bug 1909978: update documentation for ignore-volume-az usage

- pkg/asset/installconfig/openstack/validate.go
- pkg/asset/installconfig/openstack/validate_test.go
- pkg/asset/installconfig/platformprovisioncheck.go
This is a follow up to b6e3088d, which hard codes the size of the
control plane to three nodes. We have a broad policy within OpenShift to
only support three-node control planes, but that's there's nothing
technically preventing a user from using a different size. In the case
of IPI on OpenStack, however, there is a technical restriction, so this
explicitly validates that.
> Bug 1919407: openstack/validation: enforce control plane size

- pkg/destroy/openstack/openstack.go
If the user destroyed a cluster without removing all the associated
service LBs, the `destroy` command would fail to remove the network
and loop until it hits the timeout.
The destroy command now looks if there are any leftover LBs where its
`VipNetworkID` matches the network ID and deprovisions it.  We filter on
services LBs created by the openstack cloud provider, matching the
`Kubernetes external service` string in the description [1], to ensure
we're not destroying a user-created resource by mistake.
[1] https://github.com/openshift/kubernetes/blob/442a69c/staging/src/k8s.io/legacy-cloud-providers/openstack/openstack_loadbalancer.go#L446
> Bug 1916692: OpenStack: Delete leftover LBs when destroying cluster

- docs/user/openstack/known-issues.md
Now in the documentation we assume that the Cinder AZ is always called "nova". This commit replaces the hardcoded "nova" string with "<Cinder_AZ>", which then will be changed by users to the real Cinder AZ name.
> Bug 1909978: update ignore-volume-az documentation

- data/data/rhcos-amd64.json
- data/data/rhcos-ppc64le.json
- data/data/rhcos-s390x.json
- data/data/rhcos.json
- amd64:   47.83.202102090044-0
- s390x:   47.83.202102090311-0
- ppc64le: 47.83.202102091015-0
(cherry picked from commit e653cfd1315e0d293864292fdef4d5af0c055745)
See: https://github.com/openshift/installer/pull/4633
(sdodson) Attempting to write down testing expectations, need at least installation to complete on all of our major platforms, either ipi or upi for each, doesn't matter:
> Bug 1922292: [release-4.7] data/rhcos.json: Update boot images

- data/data/rhcos-amd64.json
- data/data/rhcos-ppc64le.json
- data/data/rhcos-s390x.json
- data/data/rhcos.json
- amd64:   47.83.202102090044-0
- s390x:   47.83.202102090311-0
- ppc64le: 47.83.202102091015-0
4.8: https://github.com/openshift/installer/pull/4634
4.7: https://github.com/openshift/installer/pull/4635
> data/rhcos.json: Update boot images

- hack/openstack/OWNERS
Now OWNERS is a symbolic link and looks like github doesn't accept it. This commit makes OWNERS a regular text file.
> Fix OWNERS for openstack

- OWNERS_ALIASES
- pkg/destroy/vsphere/OWNERS
Adds missing owners file for vsphere destroy package. e.g. I should be able to `/approve` #4579 
Updates reviewers/approvers to add @jstuever
> vSphere: add missing destroy OWNERS & update OWNERS_ALIASES

- pkg/asset/machines/openstack/machines.go
- pkg/asset/machines/openstack/machinesets.go
- pkg/asset/machines/worker.go
In 05453ef0d the MachineSets function was updated to remove the option
to specify external clientOpts. This clientOpts is used by hive to generate
the machinesets and ensuring the correct client authentication is used.
using the default client opts as forced in 05453ef0d only allows configuring the
openstack client using the default location on the host, which doesn't sit well
with something like hive which needs to manage the machinesets for many different
clients from single location.
Reverting the change in 05453ef0d to allow machinesets to accept external clientOpts
and use the default opts when it is nil.
xref: https://issues.redhat.com/browse/HIVE-1372
/assign @Fedosin
> machines/openstack: re-enable external clientOpts

- pkg/asset/installconfig/openstack/validate.go
- pkg/asset/installconfig/openstack/validate_test.go
- pkg/asset/installconfig/platformprovisioncheck.go
This is a cherry-pick of commit fb94d1cd4d713ee79efa672af71b52a067cb2e36
This is a follow up to b6e3088d, which hard codes the size of the
control plane to three nodes. We have a broad policy within OpenShift to
only support three-node control planes, but that's there's nothing
technically preventing a user from using a different size. In the case
of IPI on OpenStack, however, there is a technical restriction, so this
explicitly validates that.
> Bug 1924670: openstack/validation: enforce control plane size

- hack/openstack/test-manifests.sh
- pkg/asset/installconfig/openstack/validate.go
It should be called OPENSHIFT_INSTALL_SKIP_PREFLIGHT_VALIDATIONS.
> Bug 1924140: fix a typo in an env variable name

- data/data/rhcos-ppc64le.json
- data/data/rhcos-s390x.json
Refer to https://bugzilla.redhat.com/show_bug.cgi?id=1926558. After https://github.com/openshift/installer/pull/4604 landed in 4.4, the multi-arch CI runs started failing because the hyperkube package was old. This was not an issue for x86 as the rhcos images were bumped for a CVE (https://github.com/openshift/installer/pull/3985), resulting in a newer hyperkube package which did not have this issue with the kubelet erroring out on `anonymous-auth=false`
Logs of error:
```
Feb 08 22:02:17 psundara-ocp-ptj44-bootstrap hyperkube[2888]: I0208 22:02:17.946044    2888 server.go:540] No cloud provider specified: "" from the config file: ""
Feb 08 22:02:17 psundara-ocp-ptj44-bootstrap hyperkube[2888]: W0208 22:02:17.946082    2888 server.go:563] standalone mode, no API client
Feb 08 22:02:17 …
```
> Bug 1926558: [release-4.4]: rhcos.json: Update bootimages for ppc64le/s390x to fix kubelet error

- upi/openstack/bootstrap.yaml
- upi/openstack/compute-nodes.yaml
- upi/openstack/control-plane.yaml
- upi/openstack/network.yaml
Without the openshiftClusterID tag, the `destroy` command can't properly identify the resources and that might cause the destroy to loop over resource deletion until it reaches the timeout.
> Bug 1916593: OpenStack UPI: Tag all resources with clusterID

- pkg/asset/installconfig/aws/session.go
- pkg/asset/manifests/openshift.go
Currently the installer only supports `static credentials` from
AWS config/credentials file or environment for authenticating with AWS.
For the default credential modes (mint/passthrough) this restriction makes
sense because the installer transfers those credentials to the cluster to mint/
passthrough creds to all the components.
For manual mode this restriction can be removed as the credentials are used only
by the installer and installer's internal components(terraform). This is especially
important for allowing users to use STS Webhook identity work, where the users want the
installer to assume a certain role using specific token specified by env variables or,
the aws config file.
The new credentials loading,
- loads the previously used env and static credentials provider first,
- when …
> aws: support more auth options in manual mode

- OWNERS_ALIASES
Neither of us are on the ARO team anymore.
> OWNERS: Remove ehashman and asalkeld from azure reviewers

- hack/build.sh
There is a bug with the golang internal linker for the linux/arm64 target
that has yet to be fixed:
https://github.com/golang/go/issues/40492
> Workaround golang linux/arm64 link error

- pkg/asset/manifests/proxy.go
- pkg/types/validation/installconfig.go
- pkg/types/validation/installconfig_test.go
The installer currently trims the spaces for the noProxy URLs
provided by the user but the Cluster Network Operator does not which
causes the machine config operator to fail with invalid proxy urls.
Adding a validation check to reject the input from the user if there
are spaces in the noProxy input.
Also added validation checks for the HTTPProxy and the HTTPSProxy
similar to the cluster network operator for the same.
> Bug 1873649: Validate noProxy input and add prefix for proxy urls

- pkg/asset/installconfig/aws/session.go
AWS SDK session uses another const for loading credentials from the ennvironment
see [1]. This is same as the env provider and should be treated like one.
[1]: https://github.com/aws/aws-sdk-go/blob/v1.37.10/aws/session/env_config.go#L16
/assign @staebler 
> aws/session.go: include another internal provider name for static creds

- data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
- `--manifest-cluster-etcd-operator-image` has been deprecated and is unused
- `--cluster-config-file` has been replaced by `--network-config-file`
/cc @hexfusion
> Cleanup argument usage in bootkube.sh for ceo

- docs/user/openstack/README.md
With 9314e6dc5823690a08109acd26583c517912f55d, the Installer reads the
`clouds.yaml` `cacert` file to connect to the OpenStack API. It is
therefore no longer necessary to add the certificate to the system
trust.
> Bug 1786314: openstack: cacert does not require system trust

- pkg/asset/installconfig/openstack/validation/cloudinfo.go
- vendor/github.com/gophercloud/utils/openstack/compute/v2/availabilityzones/utils.go
- vendor/modules.txt
A new helper was added into gophercloud/utils to list the available
availability zones.
Switch the getZones() function in cloudinfo to use it, so we don't
have the carry that logic in the installer anymore.
Related bug: https://issues.redhat.com/browse/OSASINFRA-1848
Signed-off-by: Emilien Macchi <emilien@redhat.com>
> openstack: refactor getZones() to use gophercloud/utils

- pkg/terraform/exec/plugins/vsphereprivate/resource_vsphereprivate_import_ova.go
From internal forums it was suggested that marking
the imported RHCOS virtual machines as a template
would be better than leaving it as a virtual machine.
This PR adds to the end of the `resourceVSpherePrivateImportOvaCreate`
fuction:
- From `info.Entity` get the VirtualMachine
- If the VirtualMachine exists, mark as a template
> vSphere: mark imported virtual machines as template

- pkg/tfvars/internal/cache/cache.go
cache: Create an internal "urlWithIntegrity" API, use better filename
Prep for openshift/os#477
Clarify internally that this sha256 is uncompressed; the stream
will also have the compressed sha256 which we should support
verifying too (as well as the size).
Since we're now parsing the URL better, use the uncompressed
filename as the target name.  This makes it much *much* more
obvious to users how to manually clean up old images in
the cache.  We can do this because for both FCOS/RHCOS
the filenames contain versions and are immutable - we will
never go back and change an image.
> Stream metadata prep

- data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
This will allow the change introducing the new secret structure to merge to ceo, after which the compatibility for the legacy structure can be removed.
CEO change requiring this PR: https://github.com/openshift/cluster-etcd-operator/pull/544
/cc @hexfusion
> bootstrap: Ensure temp compat for old and new ceo secret structure

- data/data/bootstrap/bootstrap-in-place/files/usr/local/bin/bootstrap-in-place.sh
A recent [PR](https://github.com/openshift/installer/pull/4653) bumped the ignition generated by the installer to v3.2.
This PR aligns the master ignition that bootstrap in place is getting from the machine config server to the same version.
This is mainly relevant for assisted-installer that might want to merge user custom Ignition (that should match the ignition version generated by the installer) with this ignition config.
> Bump bootstrap in place MCS master ignition to v3_2

- images/installer/Dockerfile.ci.rhel7
- images/installer/Dockerfile.upi.ci
- images/libvirt/Dockerfile.ci
- images/mock/Dockerfile
- images/openstack/Dockerfile.ci
- pkg/asset/releaseimage/default.go
* Replace uses of registry.svc.ci.openshift.org with registry.ci.openshift.org.
* Update references to golang-1.14 images to golang-1.15.
* Update references to OpenShift images to 4.8.
> update ci image references

- data/data/openstack/masters/main.tf
- pkg/asset/installconfig/openstack/validate.go
- pkg/asset/installconfig/openstack/validate_test.go
Modify the terraform for IPI OpenStack so that it only creates at most the number of control planes requested by the user. In other words, if the user requests only one control plane node, then the terraform will only create master-0 and not master-1 nor master-2.
Relax the provsioning validation that enforces that the number of control plane replicas must be exactly 3 to allow for the control plane replicas to be at most 3.
> openstack: allow for fewer than 3 masters

- images/installer/Dockerfile.upi.ci
With the current code, yum install pyopenssl is used to install
the openssl package that gcloud sdk needs to signurl which has
stopped working because gcloud is not able to pick up the package.
Added a code to install pip of a version less than 21 (pip support
for python 2 ends with pip version 21) and installed pyopenssl
which is the recommended way to install openssl for gcloud.
> Bug 1917931: Fix GCP openssl not found error

- data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
- pkg/asset/ignition/bootstrap/common.go
Use the ssh key from install-config to allow ssh to
running IPA instance on master nodes.
Makes use of the recently added IRONIC_RAMDISK_SSH_KEY parameter
https://github.com/openshift/ironic-image/pull/151
> baremetal:  pass an sshKey to ironic

- pkg/asset/ignition/bootstrap/baremetal/template.go
- pkg/asset/ignition/bootstrap/baremetal/template_test.go
While deploying with IPv6 provision network with subnet other than /64
control plane hosts fail to PXE boot - this is due to DNSmasq defaulting
to /64. This updates the installer's bootstrap dnsmasq config to specify
the netmask.
> Bug 1925291: baremetal: include netmask in DNSMasq dhcp range

- pkg/metrics/builder/builder_test.go
This fixes two dropped error variables in `pkg/metrics/builder`.
> pkg/metrics/builder: fix test errors

- pkg/asset/machines/master.go
- pkg/asset/machines/master_test.go
- pkg/asset/machines/worker_test.go
- pkg/tfvars/openstack/openstack.go
Now, during generation of machines, we modify machine pools in the install config. It's not correct because by contract all assets are immutable after generation.
To prevent this, this commit creates copies of existing machine pools and all changes are made to it, leaving the original values intact.
> Make copies of machine pools in machines asset

- docs/user/aws/iam.md
Documentation improvement:
There are a few difference of AWS account root user and AWS IAM user, so my suggestions are:
- improve the initial description based on official documentation
- remove the "secondary" as **AWS account root user** is not AWS IAM user.
> docs/aws-iam: improving the concepts for Account root user and IAM user

- go.sum
- hack/go-genmock.sh
- images/mock/Dockerfile
- pkg/asset/installconfig/azure/mock/azureclient_generated.go
- pkg/asset/installconfig/gcp/mock/gcpclient_generated.go
- tools.go
- vendor/github.com/golang/mock/mockgen/mockgen.go
- vendor/github.com/golang/mock/mockgen/model/model.go
- vendor/github.com/golang/mock/mockgen/parse.go
- vendor/github.com/golang/mock/mockgen/reflect.go
- vendor/github.com/golang/mock/mockgen/version.1.11.go
- vendor/github.com/golang/mock/mockgen/version.1.12.go
- vendor/modules.txt
Rather than building an image to run mockgen and having that image always get the latest verion of mockgen, use the mockgen from the vendor directory. This has a couple benefits.
1) We do not get changes to the client mocks that pop up in random PRs when a new version of mockgen is released.
2) Contributors that do not have access to the CI registry can generate the mock clients.
> use vendored mockgen for generating mock clients

- data/data/install.openshift.io_installconfigs.yaml
- docs/user/metal/install_ipi.md
- pkg/tfvars/baremetal/baremetal.go
- pkg/types/baremetal/platform.go
- pkg/types/baremetal/validation/platform.go
- pkg/types/baremetal/validation/platform_test.go
Uses the new baremetal-operator BootMode value UEFISecureBoot to request
Ironic to automatically configure secure boot during the instance start.
Metal3 design: https://github.com/metal3-io/metal3-docs/pull/161
> baremetal: automatic UEFI secure boot configuration

- data/data/openstack/masters/main.tf
This syntax was deprecated in terraform 0.11. Let's use the new syntax
to prevent a deprecation warning:
Warning: Interpolation-only expressions are deprecated
> OpenStack: Stop using deprecated interpolation syntax

- data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
The cluster-etcd-operator is intended to take over responsibility for rendering all of its tls assets and owning where its boostrap assets are copied to. This change ensures compatibility with the current strategy and the new one to allow the operator changes to be tested before merge.
/cc @staebler @hexfusion
> Enable bootkube compatibility for ceo rendering improvements

- data/data/openstack/topology/sg-master.tf
- data/data/openstack/topology/sg-worker.tf
- upi/openstack/security-groups.yaml
TL;DR: SSH shouldn't be exposed to the public by default and if an
operator explicitly wants it, they should do it by modifying the
security group on day 2.
Reasons to not open SSH to all networks:
* SSH to an OCP cluster should be done only by advanced operators and
shouldn't be encouraged, therefore not open by default that easily. Instead, an experienced operator should make configuration changes via `machineconfig` objects.
* Operators who know what they do should reach the nodes from a secure
network (e.g. provider network or tenant network, ie internal). Not
from a public network (e.g. Internet or any public faced network).
* Other cloud providers don't allow SSH from 0.0.0.0/0, we shouldn't be
the one doing it.
* Running `oc debug` doesn't require SSH to be open from the client.
> Bug 1873079: openstack: restrict SSH to machineNetwork CIDR
