pkg/types/validation/installconfig.go, pkg/types/validation/installconfig_test.go
When the port number is specified, the validation that whether
the given proxy value overlaps with the cluster or service
networks is not done due to the port number not being a valid
value for the parseIP function used for converting string to
a valid IP.
Adding a fix to make sure that the port number part of the code
is removed from the given input proxy value before it is converted
to a vaild IP.
=> Bug 1932789: Fix proxy validation when specified with port.

pkg/terraform/exec/plugins/vsphereprivate/resource_vsphereprivate_import_ova.go
Prior to this change, the vsphereprivate Terraform plugin would fatally
error if the specified network was not found on any hosts when importing
the ova. Because the error was a common pointer reference error, it was
difficult to determine what caused the error. This change adds a more
clear error when this situation happens.
=> Bug 1868755: vsphereprivate: tf plugin to no longer error if no network found.

data/data/baremetal/main.tf, data/data/baremetal/variables-baremetal.tf, pkg/asset/cluster/tfvars.go, pkg/tfvars/baremetal/baremetal.go
The installer's terraform provider needs to talk to Ironic running on
the bootstrap VM. That communication path always used the provisioning
network, which means when using Hive from a remote cluster, the
provisioning network must be routable.
Since 4.7, with the disabled provisioning network feature, the installer
uses the API VIP for installer communication and image cache. It makes
sense to remove the dependency that the installer talks to the
provisioning network at all.  This PR makes the installer always use the
API VIP to talk to Ironic, but maintains the provisioning network for
bare metal host <-> image cache communications when it's enabled.
=> Bug 1932799: baremetal: always use API VIP for installer communication

pkg/asset/installconfig/openstack/validation/cloudinfo.go
Now Installer loads cloud info for OpenStack platform twice: for base validations and for quota checking. This is not reasonable, because we just double the number of requests to OpenStack cloud.
This commit caches cloud info, which allows to reuse what we get from the first time.
=> Bug 1923038: OpenStack: cache cloud info

data/data/bootstrap/bootstrap-in-place/files/opt/openshift/bootstrap-in-place/master-update.fcc
Due to recent ceo rendering improvements the etc-bootstrap directory structure changed.
This caused bootstrap in place to fail since some of the files that it adds to the master Ignition moved
=> Adjust master-update.fcc to the new ceo render secret structure

pkg/terraform/diagnose.go, pkg/terraform/diagnose_test.go
A customer encountered a timeout when the installer was trying to reach
the baremetal provisioning services due to incorrect proxy settings in
the environment from which the installer was run. This updates the
diagnosis helper for this API timeout to include a suggestion to check
network and proxy settings.
=> Bug 1926364: baremetal: update terraform diagnosis for API timeout

pkg/asset/installconfig/vsphere/validation_test.go, pkg/asset/installconfig/vsphere/vsphere.go, pkg/types/vsphere/validation/platform.go, pkg/types/vsphere/validation/platform_test.go, pkg/validate/validate.go, pkg/validate/validate_test.go
Vcenter input must always only be the hostname yet it is possible
for the user to provide other types of input like URLs. URLs would
cause an error to occur only during the time of cluster creation
as connection to the vcenter would succeed.
Adding a validation check for the user input for the vcenter value
so that it conforms to the RFC-1035 standard and forces the user
to re-enter the value rather than throw an error during cluster
creation.
=> vsphere: Validate vcenter user input to match RFC standards

pkg/asset/machines/ovirt/machinesets.go
Machineset: Removed '0' from the name 
worker nodes created by the installer have number '0' suffixed
Fixes [bz-1817954](https://bugzilla.redhat.com/show_bug.cgi?id=1817954)
=> [ovirt]: Removed '0' from machineset name

cmd/openshift-install/gather.go
This fixes a dropped error variable in `cmd/openshift-install`.
=> cmd/openshift-install: fix dropped error

pkg/asset/installconfig/openstack/validation/cloudinfo.go, pkg/asset/quota/openstack/openstack.go, pkg/asset/quota/quota.go
We now check the quotas for:
* Ports, with a base number + growing for each machine and its number of
attached networks.
* Routers
* Subnets
* Networks
* Security Groups
* Security Group Rules
We make the difference between requirements when Kuryr is the networking
backend or not, since the quotas aren't the same.
Note: this PR also includes vendoring for both gophercloud and
terraform-openstack, which is required to get quota details for networking
resources.
JIRA: [OSASINFRA-2006](https://issues.redhat.com/browse/OSASINFRA-2006)
=> openstack: add networking quota checks

data/data/bootstrap/baremetal/files/opt/metal3/auth/clouds.yaml.template, data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template, pkg/asset/ignition/bootstrap/baremetal/template.go
The clouds.yaml baremetal_endpoint_override and
baremetal_introspection_endpoint_override fields were missing an IP
address when provisioning network was disabled. This adds some bash
that grabs the PROVISIONING_NIC IP address in startironic.sh.template
and inserts it into those fields.
=> Bug 1930240: baremetal: Set missing IP in clouds.yaml

data/data/baremetal/main.tf, data/data/baremetal/masters/main.tf, data/data/baremetal/masters/variables.tf, data/data/baremetal/variables-baremetal.tf, pkg/tfvars/baremetal/baremetal.go
This doesn't work for IPI baremetal deployments driven via hive,
because there are firewall rules that prevent access to the
bootstrap MCS from the pod running the installer.
This was implemented in:
https://github.com/openshift/installer/pull/4427
But we ran into problems making the same approach work for
worker machines ref:
https://github.com/openshift/installer/pull/4456
We're now looking at other approaches to resolve the
network-config requirements driving that work, so
switching back to the pointer config for masters seems
reasonable, particularly given this issue discovered for
hive deployments.
Conflicts:
pkg/tfvars/baremetal/baremetal.go
This reverts commit 98dc38170a66d3ede7513fc01e3ccce4ff8dd93d.
=> Bug 1936443: Revert "baremetal: send full ignition to masters"

docs/user/openstack/known-issues.md
Installations with Kuryr can timeout because of
recent changes on the way the nodes' subnet is retrieved.
This commit adds a section to the know issues describing
why the issue occour and how to avoid it.
=> Add docs about issues on UPI with Kuryr

pkg/asset/installconfig/openstack/validate.go, pkg/asset/installconfig/openstack/validation/machinepool.go, pkg/asset/installconfig/openstack/validation/machinepool_test.go, pkg/asset/installconfig/openstack/validation/platform.go
Now we validate just the user input, but in fact we additionally set default values there if they are not provided directly. It leads
to incorrect validation of the install config.
This commit sets the default values to machine pools before validation to make them just like what we use to build a cluster.
=> Bug 1903055: Set default values to machine pools before validation

pkg/asset/cluster/aws/aws.go
This fixes a dropped error in `pkg/asset/cluster/aws`.
=> pkg/asset/cluster/aws: fix dropped error

go.mod, go.sum, vendor/github.com/gophercloud/gophercloud/CHANGELOG.md, vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/nodes/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/nodes/results.go, vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/quotasets/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/quotasets/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/quotasets/results.go, vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/volumeactions/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/volumeactions/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/volumeactions/results.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/quotas/results.go, vendor/modules.txt
We found a workaround in gophercloud to unmarschal json if "reserved" is
a string, we deal with it in the gophercloud library until this is
solved in OpenStack Neutron:
https://review.opendev.org/c/openstack/neutron/+/779878
BZ#1937460
Signed-off-by: Emilien Macchi <emilien@redhat.com>
=> Bug 1937460: Update gophercloud module from master

data/data/gcp/bootstrap/main.tf
As requested from this RFE:
https://issues.redhat.com/browse/RFE-1516
`uniform_bucket_level_access` is unavailable in the currently vendored
terraform-provider-google. Using `bucket_policy_only` instead.
=> [gcp] Change bootstrap ignition storage bucket access

pkg/tfvars/openstack/openstack.go
Now we ignore region when we generate the glance url with ignition config. This commit updates it by considering the region name.
=> Bug 1934123: generate glance url considering the region

data/data/rhcos-amd64.json, data/data/rhcos-ppc64le.json, data/data/rhcos-s390x.json, data/data/rhcos.json
This bumps the RHCOS boot image address the LUKS problem described in RHBZ#1934174
=> Bug 1934557: bump RHCOS image for LUKS fix

data/data/openstack/topology/private-network.tf
Before this patch, [Terraform][1] and [cluster-api-provider-openstack][2]
created Neutron ports for the master machines with a slightly different
pattern:
`<infra-id>-master-port-<n>`
versus
`<infra-id>-master-<n>`
This resulted in an inconsistency in live clusters: the machines created
at install-time had ports named one way, while machines created
day-2 the other way.
In particular, this different behaviour hits logic like Kuryr that has
on occasion to depend on OpenStack resource names.
This patch does not aim at fixing the Kuryr bug specifically, as a
change in the Installer code can't affect upgrades. Rather, it
introduces some more consistency.
---
The variable name is chosen to reflect CAPO's, given that [the upstream
code][3] is also using the same pattern.
[1]: …
=> Bug 1933414: openstack: Consistent port names

docs/user/aws/customization.md
Fix a disconnect about the slug to use for the reference link from 17030b3bdb (#3293).
=> docs/user/aws/customization: Fix KMS-key link format

docs/user/metal/customization_ipi.md, docs/user/metal/external_loadbalancer_ipi.md
Customers who are not satisfied with the self-hosted LB architecture limitations ( traffic goes through a single node, node failover may cause traffic hit) may want to use their own LB.
This PR describes how to shift (post-deployment) external api/ingress traffic from the default self-hosted
load balancer to load balancer provides by the customer.
=> IPI-BAREMETAL: document how to use external LB for api/ingress traffic

data/data/gcp/main.tf, docs/user/gcp/install_upi.md
Instead of dividing the IPv4 machine CIDR into 8 networks and only using 2 of those 8, divide into only 2 networks.
https://issues.redhat.com/browse/CORS-1660
=> gcp: divide machine CIDR into 2 networks for subnets

data/data/bootstrap/bootstrap-in-place/files/usr/local/bin/bootstrap-in-place.sh, data/data/bootstrap/bootstrap-in-place/files/usr/local/bin/install-to-disk.sh.template, data/data/bootstrap/files/usr/local/bin/approve-csr.sh, data/data/bootstrap/files/usr/local/bin/bootkube.sh.template, data/data/bootstrap/files/usr/local/bin/bootstrap-service-record.sh, data/data/bootstrap/files/usr/local/bin/crio-configure.sh.template, data/data/bootstrap/files/usr/local/bin/installer-gather.sh, data/data/bootstrap/files/usr/local/bin/kubelet-pause-image.sh.template, data/data/bootstrap/files/usr/local/bin/kubelet.sh, data/data/bootstrap/files/usr/local/bin/release-image-download.sh.template, data/data/bootstrap/files/usr/local/bin/report-progress.sh, data/data/bootstrap/systemd/units/chown-gatewayd-key.service, data/data/bootstrap/systemd/units/kubelet.service.template, docs/dev/bootstrap_services.md
Each OpenShift service running on the bootstrap machine will now create a json file in /var/log/openshift/ that contains an array of entries detailing the progress that the service has made.
The entries included in the json file are the following.
* Service start
* Service end, with result and error details
* Service stage start
* Service stage end, with result and error details
The json files in /var/log/openshift will be collected by the bootstrap gather in /bootstrap/services/ for evaluation by the
installer for improved failure reporting to the user. The evaluation is left for follow-on work.
https://issues.redhat.com/browse/CORS-1542
https://issues.redhat.com/browse/CORS-1543
=> bootstrap: record progress of services

data/data/gcp/main.tf
Add kubernetes-io-cluster-$CLUSTER_ID=owned label to master and bootstrap machines when installing in GCP. This label is already added to worker machines created by the machine-api-operator.
The limit for label keys in GCP is 63 characters. The maximum length of a cluster ID is 27 characters, so the maximum length of the kubernetes owned label key will be 49 characters, which will fit within the GCP limits.
https://issues.redhat.com/browse/CORS-1641
Sample labels added to machines.
```
$ gcloud compute instances list --filter 'name: mstaeble-*' --format json | jq '.[] | {"name":.name, "labels":.labels}'
{
"name": "mstaeble-team-mpbw5-bootstrap",
"labels": {
"kubernetes-io-cluster-mstaeble-team-mpbw5": "owned"
}
}
{
"name": "mstaeble-team-mpbw5-master-0",
"labels": { …
```
=> gcp: add kubernetes owned label to master machines

data/data/manifests/openshift/baremetal-provisioning-config.yaml.template
A new value has been added to the baremetal provisioning CRD that allows
it to watch more namespaces to support deploying remote single node
OpenShift instances.  This patch explicitly sets this value to false.
We do not want to expose this in the installer at this time.  This is
a day 2 option.
=> Baremetal: Explicitly set watchAllNamespaces

pkg/asset/tls/certkey_test.go
In Go 1.15 treating the CommonName field on X.509 certificates as a host name when no Subject Alternative Names are present is now disabled by default (see [release notes](https://golang.org/doc/go1.15#commonname)).
This leads to the following error in the "simple ca" test case when running with Go >=1.15:
```
x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
```
I think it is safe to amend this test csae. I didn't manage to find any instances where certs without SAN values (`DNSNames`) are being verified against `x509.VerifyOptions` with hostnames. I'm however not 100% sure that I found everytinhg and would like to hear feedback from someone with more experience in this area.
=> asset/tls: fixes certkey unit test for Go >= 1.15

pkg/asset/installconfig/vsphere/validation.go, pkg/types/validation/installconfig.go, pkg/types/vsphere/validation/platform.go, pkg/types/vsphere/validation/platform_test.go
If the machineCIDR is specified by the user, the VIP IPs provided
must overlap with the CIDRs provided and the installation fails
if they do not.
Adding a validation check to see if the CIDR is provided and if so,
checks to see if the IPs are within any of the machine CIDRs provided.
=> Bug 1918469: Check if VIP IPs overlap with machine CIDR provided during vsphere installation

data/data/kubevirt/datavolume/main.tf
This change is done in order to support CDI behavior change and
prevent from having "WaitForFirstConsumer" phase on the dv - source PVC
=> Bug 1939513: KubeVirt platform: Add the immediate request annotation to the source PVC

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
This change is the first step in migrating responsibility for token keypair generation from the installer to operator render. This will ensure parity with ckao which already renders the bound token keypair.
/cc @staebler @soltysh
=> Enable forward compatibility with kcmo rendering of signing keypair

pkg/destroy/gcp/disk.go, pkg/destroy/gcp/gcp.go
With the introduction of CSI volumes in GCE it is no longer possible to find GCE PDs belonging to a particular cluster by their name. Therefore the CSI provisioned disks are to be labelled and the installer can find the disks to destroy also by the label.
Related patches:
Extra label support in the GCE CSI driver: https://github.com/openshift/gcp-pd-csi-driver/pull/11
GCP CSI operator: https://github.com/openshift/gcp-pd-csi-driver-operator/pull/16
=> Add resource filter that matches Label or ClusterID

images/installer/Dockerfile.upi.ci
We shouldn't need this anymore, see
https://cloud.google.com/sdk/crypto
We have a larger conflict here because the gcloud sdk wants
python2, azure wants python3.
Something changed in the pip CDN that broke our use of the
older pip.
(hopefully)
Closes: #4783
=>  Dockerfile.upi.ci: Drop pip+pyopenssl installs

pkg/asset/installconfig/vsphere/validation.go, pkg/types/validation/installconfig.go, pkg/types/vsphere/validation/platform.go, pkg/types/vsphere/validation/platform_test.go
Reverts openshift/installer#4754
When using the survey flow, the machine CIDR is not populated. This causes the installation to fail, unless the VIPs happen to be within the default machine CIDR.
=> Revert "Check if VIP IPs overlap with machine CIDR provided during vsphere installation"

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template, data/data/bootstrap/files/usr/local/bin/bootstrap-cluster-gather.sh, data/data/bootstrap/files/usr/local/bin/installer-gather.sh
The bootkube tries to keep the bootstrap control-plane on for
30 minutes before it shuts down due to a timeout. In which case,
the bootkube tries to re-run the control-plane to gather the logs.
The re-run is not guaranteed by the api team and hence there is
a possibility the logs for the control-plane will not be gathered.
Adding a check to trap the error message from the run bootstrap
command in the bootkube to run installer-gather script to gather
the logs in case of any error before the resources get deleted.
The logs will be stored in a folder with a default name temporarily.
Then the size of the openapi.json.gz file will be checked to see
if there was any extra information was logged from the control-
plane and if there was not a change, the tar file and the folder
will be removed as …
=> gather-bootstrap: Gather logs before bootstrap shuts down

images/installer/Dockerfile.upi.ci.rhel8
Fork the current rhel7 Dockerfile and port it to rhel8.  This
makes it easier to use both python2 and python3 at the same time,
which we need for gcloud (python2) and azure (python3).
We need to land this, then try changing CI to actually use
it in a rehearsal job in openshift/release.
=> images: Add Dockerfile.upi.ci.rhel8

data/data/rhcos-amd64.json, data/data/rhcos-ppc64le.json, data/data/rhcos-s390x.json, data/data/rhcos.json, pkg/rhcos/ami_regions.go
This boot image bump brings in fixes for the following BZs on the
RHCOS side:
BZ#1934174 - rootfs too small when enabling NBDE
BZ#1940704 - prjquota is dropped from rootflags if rootfs is reprovisioned
It also brings in support for the new ap-northeast-3 region in AWS.
BZ#1939661 - support new AWS region ap-northeast-3
=>     Bug 1934557: RHCOS boot image bump for LUKS fixes

pkg/asset/installconfig/azure/validation.go, pkg/asset/installconfig/azure/validation_test.go, pkg/asset/machines/worker.go, pkg/types/azure/machinepool.go
If the Azure disktype is Premium_LRS, a check must be made to see
if the given InstanceType has the PremiumIO capabilities which when
not present causes creation of clusters to fail. Adding the check
which iterates through all the capabilities of the given instance
type disk to find the PremiumIO, check if it is set to True and
return error otherwise.
=> Bug 1931115: Azure: Check Azure disk Instance Type for PremiumIO Capabilities

pkg/asset/cluster/tfvars.go
This fixes a dropped `err` variable in `pkg/asset/cluster`.
=> pkg/asset/cluster: fix dropped error

hack/build-coreos-manifest.go, images/installer/Dockerfile.ci
Split out from #4582
This copies the bits from https://github.com/cgwalters/rhel-coreos-bootimages
which builds a ConfigMap out of the stream metadata and injects
it into the cluster.
We have an `installer` image in the release image today; this adds
the "is an operator" label, even though it's not really an
operator.  We just want the CVO to inject the manifest.
Among other important semantics, this will ensure that in-place
cluster upgrades that have new pinned CoreOS stream data will
have this configmap updated.
=>   Inject CoreOS stream metadata as configmap via CVO manifest

go.mod, go.sum, vendor/github.com/gophercloud/utils/openstack/clientconfig/requests.go, vendor/modules.txt
Bump gophercloud/utils to include
https://github.com/gophercloud/utils/pull/149
This commit ensures gophercloud keeps working fine when using a custom
CA cert and Proxy at the same time.
=> Bug 1925216: Bump gophercloud utils

pkg/asset/installconfig/azure/session.go
This fixes a dropped error variable in `installer/pkg/asset/installconfig/azure`.
=> installer/pkg/asset/installconfig/azure: fix dropped error

data/data/bootstrap/files/usr/local/bin/release-image-download.sh.template
This is a simple sanity check to see if release image architecture matches the bootstrap node's architecture. This is useful in cases of user error where an incorrect release image is specified and we error right away rather than downloading the associated images and failing in say crio when downloading the incorrect pause image.
=> data/bootstrap: Check if release image architecture matches host architecture

cmd/openshift-install/create.go, cmd/openshift-install/waitfor.go
Refines the error messages that are provided during cluster installation
if the API or the bootstrap fails to come up within the given time
to provide more info to the user about what would have likely
caused the error. This would provide a suggestion to the user
about where to go look for the specific log file for the error.
=> installer-create: Provide user friendly error messages during failures

data/data/azure/bootstrap/variables.tf, data/data/azure/dns/dns.tf, data/data/azure/dns/variables.tf, data/data/azure/main.tf, data/data/azure/master/variables.tf, data/data/azure/variables-azure.tf, data/data/azure/vnet/internal-lb.tf, data/data/azure/vnet/outputs.tf, data/data/azure/vnet/variables.tf, pkg/tfvars/azure/azure.go, pkg/types/validation/installconfig.go
The installer considers Azure to be a supported platform for IPv6 and dual-stack because of our early plans for testing, but single-stack IPv6 on Azure never worked, and dual-stack on Azure has never been tested and is not supported in 4.8.
=> Fix ipv6/dual-stack validation with Azure

pkg/asset/machines/baremetal/machines.go, pkg/tfvars/baremetal/baremetal.go
Change the way we handle the image filename so that we aren't requiring
that '-openstack' be in the image name.  This allows the use of any
filename that meets the rest of the validations.
This can be merged now that this is in:
https://github.com/openshift/ironic-rhcos-downloader/pull/26
=> Baremetal: Remove the -openstack rename in the os image.

hack/build-coreos-manifest.go
Marshal the coreos-bootimages ConfigMap included in the installer manifests as yaml instead of json. This allows `oc` to replace
the `0.0.1-snapshot` value of the `releaseVersion`. The quotes around the value when marshalled as json were preventing the value from matching the regular expression that `oc` uses.
/fixes https://github.com/openshift/installer/issues/4797
=> hack: use yaml for coreos manifest

pkg/asset/cluster/aws/aws.go, pkg/asset/cluster/tfvars.go
If the IAM role is set in the default AWS machine platform but not in the machine platform for a specific machine pool, then the IAM role from the default AWS machine platform should be used for that machine pool.
These changes also fix a bug where if the AWS machine platform were omitted from a particular machine pool, the installer would panic when trying to find IAM roles to tag.
https://bugzilla.redhat.com/show_bug.cgi?id=1946119
=> Bug 1946119: aws: support setting IAM role in the default AWS machine platform

cmd/openshift-install/analyze.go, cmd/openshift-install/create.go, cmd/openshift-install/gather.go, cmd/openshift-install/main.go, pkg/gather/service/analyze.go, pkg/gather/service/analyze_test.go, pkg/gather/service/doc.go, pkg/gather/service/entry.go, vendor/github.com/sirupsen/logrus/hooks/test/test.go, vendor/modules.txt
When an installation fails during bootstrapping, analyze the bootstrap gather bundle for problems with downloading the release image. This analysis uses data from the new service entries files.
https://issues.redhat.com/browse/CORS-1533
Sample output when pull secret is not valid.
```
$ ./bin/openshift-install gather bootstrap
INFO Pulling debug logs from the bootstrap machine
INFO Bootstrap gather logs captured here "log-bundle-20210313180900.tar.gz"
ERROR The bootstrap machine failed to download the release image
INFO Error: unable to pull registry.ci.openshift.org/ocp/release:4.8.0-0.nightly-2021-03-12-142603: Error initializing source docker://registry.ci.openshift.org/ocp/release:4.8.0-0.nightly-2021-03-12-142603: Error reading manifest 4.8.0-0.nightly-2021-03-12-142603 in …
```
=> cmd: diagnose problems downloading release image

images/installer/Dockerfile.upi.ci
Google recommends to use disable repository GPG key
checking in the yum repo configuration by setting
repo_gpgcheck=0. Yum repositories do not usually
use GPG keys for repository validation.
Instead, the https endpoint is trusted.
=> Bug 1946307: gcp: install google cloud sdk with yum the recommended way

pkg/asset/cluster/tfvars.go, pkg/tfvars/openstack/bootstrap_ignition.go, pkg/tfvars/openstack/openstack.go
Add Proxy config to the bootstrap ignition, so in the case of
a disconnected install using a local proxy, ignition will be able to go
through the proxy.
=> Bug 1945236: add proxy params to bootstrap ignition

data/data/install.openshift.io_installconfigs.yaml, data/data/openstack/bootstrap/main.tf, data/data/openstack/bootstrap/variables.tf, data/data/openstack/main.tf, data/data/openstack/masters/main.tf, data/data/openstack/masters/variables.tf, data/data/openstack/variables-openstack.tf, docs/user/openstack/customization.md, go.mod, go.sum, pkg/asset/cluster/tfvars.go, pkg/asset/machines/openstack/machines.go, pkg/asset/machines/openstack/machinesets.go, pkg/tfvars/openstack/openstack.go, pkg/types/openstack/defaults/machinepool.go, pkg/types/openstack/machinepool.go, scripts/openstack/manifest-tests/cinder-availability-zones/install-config.yaml, scripts/openstack/manifest-tests/cinder-availability-zones/test_machines.py, scripts/openstack/manifest-tests/cinder-availability-zones/test_machinesets.py, vendor/modules.txt, vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/apis/openstackproviderconfig/v1alpha1/types.go
This PR allows users to specify custom availability zones for their root volumes.
Implements: https://issues.redhat.com/browse/OSASINFRA-2226
Enhancement proposal: https://github.com/openshift/enhancements/pull/691
=> OpenStack: Availability zones for root volumes

data/data/manifests/openshift/cloud-creds-secret.yaml.template, docs/user/ovirt/install_ipi.md, pkg/asset/manifests/openshift.go, pkg/asset/manifests/template.go
When the user tried to use an ovirt.config with a ca_file the ca_file path is written to the secret but this will not be the path of the file in the created machines.
This problem will cause connection errors in the machine object that tries to find the file that doesn't exist.
Instead, we should read the file content and write it as the ovirt_ca_bundle in case the ovirt_ca_bundle is not set on the ovirt.config file.
=> Bug 1945659: remove ovirt_cafile from ovirt-credentials secret

images/installer/Dockerfile.upi.ci
This reverts commit 9aeadb0ccef278538bf007afd0c0b405722c7ce9.
- pyopenssl is still required to use signurl with gcloud
- we still end up using python2 with the image used by prow
- the ssl certificate for files.pythonhosted.org appears to work now
=> Revert "Dockerfile.upi.ci: Drop pip+pyopenssl installs"

pkg/destroy/gcp/gcp.go
This fixes a dropped error in `pkg/destroy/gcp`.
=> pkg/destroy/gcp: fix dropped error

data/data/rhcos-amd64.json, data/data/rhcos-ppc64le.json, data/data/rhcos-s390x.json, data/data/rhcos.json, pkg/rhcos/ami_regions.go
This bumps the boot image to to include fixes for the following:
BZ#1922417 - Issue configuring nodes with VLAN and teaming
BZ#1940966 - [4.7.z] prjquota is dropped from rootflags if rootfs is reprovisioned
BZ#1941760 - [4.7.z] rootfs too small when enabling NBDE (redo)
BZ#1942706 - [4.7.z] support new AWS region ap-northeast-3
=> Bug 1935174: RHCOS bump for LUKS, prjquota, etc

data/data/aws/main.tf, data/data/aws/route53/base.tf, data/data/aws/route53/variables.tf, data/data/aws/variables-aws.tf, data/data/install.openshift.io_installconfigs.yaml, pkg/asset/cluster/aws/aws.go, pkg/asset/cluster/tfvars.go, pkg/asset/installconfig/aws/validation.go, pkg/asset/installconfig/platformprovisioncheck.go, pkg/asset/manifests/dns.go, pkg/destroy/aws/aws.go, pkg/destroy/aws/shared.go, pkg/explain/printer_test.go, pkg/tfvars/aws/aws.go, pkg/types/aws/metadata.go, pkg/types/aws/platform.go, pkg/types/aws/validation/platform.go, pkg/types/aws/validation/platform_test.go
Add the `.aws.hostedZone` field to the install config to support the user supplying an existing hosted zone for the internal private hosted zone for the cluster. This can only be used when the user is also supplying their own VPC. The hosted zone must already be associated with the user-provided VPC.
Add validation in the "Platform Provisioning Check" asset for the user-provided internal hosted zone. The validation checks that
(1) the hosted zone is associated with the user-provided VPC and that (2) the hosted zone does not contain any record sets for subdomains of the cluster's domain.
The latter of these checks is meant to provide a modicum of protection against the user accidentally trying to install again a cluster that they have already installed. When it comes time to destroy the …
=> aws: support for bring-your-own hosted zone

pkg/asset/installconfig/openstack/validate.go, pkg/asset/installconfig/openstack/validation/cloudinfo.go, pkg/asset/quota/quota.go
It is possible that under some circumstance we fail to gather the
necessary information to validate the underlying cloud meets the
requirements. Recently, this was a neutron bug [1] that caused it to
return an unexpected variable type.
Our inability to perform pre-flight validation shouldn't prevent the
installer from running.
This commit makes the installer more tolerant to failures to run
validations, for OpenStack platform only. Legitimate validation
failures still block the installation.
[1] https://bugs.launchpad.net/neutron/+bug/1918565
=> Bug 1941759: Make failure to fetch cloud info non-fatal

images/installer/Dockerfile.upi.ci
easy_install is still failing. Let's make sure to use the
documented way to install an older pip version.
https://pip.pypa.io/en/stable/installing/
=> Bug 1950007: UPI image: use get-pip instead of easy_install

pkg/asset/installconfig/ovirt/credentials.go, pkg/asset/installconfig/ovirt/validation.go
This is to fix the typos in ovirt OCP installer in sentences such as:
'connect to Engine API' -> 'connect to the Engine API'
=> Bug 1936223: [ovirt] Fix typo in connect to Engine

data/data/bootstrap/files/usr/local/bin/kubelet.sh.template, pkg/asset/ignition/bootstrap/common.go
Kubelet can end up choosing IPv4 addresses as its hostIP, which after:
https://github.com/openshift/cluster-kube-apiserver-operator/pull/1042/files
mean that the kubernetes API service ends up with an endpoint being an
IPv4 address.  This breaks the kubernetes API loadbalancer in the
service network and prevent the deployment from succeeding.
=> Bug 1931974: Prefer IPv6 hostIP on bootstrap IPv6 deployments

images/baremetal/Dockerfile.ci
Is there any reason to keep this pinned for 4.8? [we'd like to move to RHEL 8.4 beta to match RHCOS](https://github.com/openshift/ocp-build-data/pull/885), but the beta repos don't have version 4.5.0.
=> Bug 1951174: Dockerfile: repin libvirt

pkg/asset/installconfig/aws/validation.go, pkg/asset/installconfig/aws/validation_test.go
Improve the validation around whether a custom AMI has been provided by the user in the regions where one is required.
The install config is valid if any of the following are satisifed.
* The RHCOS stream metadata has an AMI for the region.
* The region is in the standard AWS partition. In this caes, the AMI can be copied from us-east-1.
* The custom AMI has been specified at the platform level.
* The custom AMI has been specified in the default machine platform.
* A custom AMI has been specified for each machine pool that has replicas.
=> Bug 1948923: aws: improve ami validation

pkg/asset/installconfig/aws/permissions.go, pkg/asset/installconfig/platformpermscheck.go
Add checks to the Platform Permissions Check asset to verify that the user has the necessary permissions to remove the shared tag from the IAM roles that the user is supplying.
=> Bug 1948359: aws: add permissions for untagging shared byo instance roles

data/data/manifests/bootkube/cvo-overrides.yaml.template
Like bd146989d3 (#4347), but for 4.8 (now that release-4.7 is no longer being fast-forwarded to track master).
=> Bug 1952632: data/manifests/bootkube/cvo-overrides: Bump default to stable-4.8

hack/build.sh
Recent versions of Go have had issues statically linking some ppc64le
binaries:
https://github.com/golang/go/issues/45564
/cc @joepvd
=> Bug 1953551: Link ppc64le binary dynamically

pkg/asset/installconfig/aws/permissions.go, pkg/destroy/aws/aws.go, pkg/destroy/aws/shared.go
Remove the kubernetes.io/cluster/xxx=shared tag from user-supplied AWS IAM roles.
=> Bug 1948359: destroy: remove shared tag from byo aws iam role

data/data/azure/bootstrap/main.tf
Removes ssh from source ANY to destination ANY on azure
private clusters. The private cluster design should not
include SSH access to the bootstrap unless you're on the
same local network.
https://bugzilla.redhat.com/show_bug.cgi?id=1943219
=> Bug 1943219: azure: remove bootstrap ssh rule on private clusters

images/installer/Dockerfile.ci.rhel7, images/installer/Dockerfile.upi.ci, images/libvirt/Dockerfile.ci, images/mock/Dockerfile, images/openstack/Dockerfile.ci, pkg/asset/releaseimage/default.go
registry.svc.ci.openshift.org has been moved to registry.ci.openshift.org.  The old
one was on a 3.x cluster and the new one is on a 4.x cluser.
=> Bug 1951571: registry.svc.ci.openshift.org is no longer valid

pkg/asset/installconfig/aws/validation.go
This change moves the AWS end point validation to happen before
other validations. This will ensure the endpoints are validated before
being used by other validations, where they may cause undesired long
timeouts.
https://issues.redhat.com/browse/CORS-1546
=> Bug 1878655: aws installconfig: endpoint validation should be before others

data/data/aws/main.tf, data/data/aws/route53/base.tf, data/data/aws/route53/variables.tf, data/data/aws/variables-aws.tf, data/data/install.openshift.io_installconfigs.yaml, pkg/asset/cluster/aws/aws.go, pkg/asset/cluster/tfvars.go, pkg/asset/installconfig/aws/validation.go, pkg/asset/installconfig/platformprovisioncheck.go, pkg/asset/manifests/dns.go, pkg/destroy/aws/aws.go, pkg/destroy/aws/shared.go, pkg/explain/printer_test.go, pkg/tfvars/aws/aws.go, pkg/types/aws/metadata.go, pkg/types/aws/platform.go, pkg/types/aws/validation/platform.go, pkg/types/aws/validation/platform_test.go
Add the .aws.hostedZone field to the install config to support the user supplying an existing hosted zone for the internal private hosted zone for the cluster. This can only be used when the user is also supplying their own VPC. The hosted zone must already be associated with the user-provided VPC.
Add validation in the "Platform Provisioning Check" asset for the user-provided internal hosted zone. The validation checks that
(1) the hosted zone is associated with the user-provided VPC and that (2) the hosted zone does not contain any record sets for subdomains of the cluster's domain.
The latter of these checks is meant to provide a modicum of protection against the user accidentally trying to install again a cluster that they have already installed. When it comes time to destroy the …
=> Bug 1954803: aws: support for bring-your-own hosted zone

pkg/asset/installconfig/aws/validation.go, pkg/asset/installconfig/aws/validation_test.go
Validate that the user-supplied private HostedZone has a domain that is the cluster domain or a parent of the cluster domain. This
is necessary so that records added to the HostedZone have the correct value.
=> Bug 1953803: aws: validate byo hostedzone is parent of cluster domain

data/data/bootstrap/files/usr/local/bin/installer-gather.sh, data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh
This collects some rudimentary networking information (ip a, ip r,
hostname, resolv.conf) on the bootstrap and masters in the log bundle.
For on-premise platforms, we've had a variety of reasons to want to look
at this information due to various networking problems.
=> Bug 1956079: gather: collect networking information in log bundle

pkg/asset/installconfig/openstack/validate.go
This commit applies default values for root volume AZs before validating control plane and compute machine pools.
=> Bug 1949923: apply defaults for root volume AZs if they aren't set

docs/user/openstack/README.md, docs/user/openstack/deploy_sriov_workers.md
Upgrading the upstream docs to match the feedback and changes that Aaron, Itzig, and Max are adding to the downstream 4.7 release version:
- explains the full end to end workflow
- example of how to create SRIOV workers in UPI
This patch will also be upgraded to include IPI instructions for installing a cluster with SR-IOV workers.
Fixes: [OSASINFRA-2281](https://issues.redhat.com/browse/OSASINFRA-2281)
=> Bug 1956496: Openstack SRIOV docs

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template, data/data/bootstrap/files/usr/local/bin/installer-gather.sh, data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh
This adds names for all bootkube podman containers, and then ensures
they are used in the logfile names.
This change adds the name to the filename too to make it easier to find
the log you want.  We already do this for the info gathered from crictl.
Before:
```
048ef60a5c98.inspect  19469a52f7ad.log      37295b9146d0.inspect  47a6928aec07.log      9f0336ed4472.inspect  adc089be665d.log      de3b81bae57f.inspect  e87f59adff94.log
048ef60a5c98.log      28df02fb561a.inspect  37295b9146d0.log      7cf3eb0e9c83.inspect  9f0336ed4472.log      afc6dbef0228.inspect  de3b81bae57f.log      efae86fe1adf.inspect
0eafc3264794.inspect  28df02fb561a.log      39c7564d80ee.inspect  7cf3eb0e9c83.log      a3dbad8cdd94.inspect  afc6dbef0228.log      e7154648c31d.inspect  efae86fe1adf.log
0eafc3264794.log …
```
=> Bug 1956978: install-gather: use names in pod logs too

data/data/bootstrap/files/usr/local/bin/crio-configure.sh.template
now, it's not guaranteed that crio will print out every field in the config
this is good, it allows us to iterate on default values quicker. However, this means we can't use simple tools like sed to update the config
luckily, `crio config` is now primed to create new drop-in files to configure itself. Use this behavior to set the override
Signed-off-by: Peter Hunt <pehunt@redhat.com>
=> bug 1956281: crio: fix bootstrap given new crio config behavior

data/data/libvirt/main.tf, data/data/libvirt/variables-libvirt.tf, pkg/asset/cluster/tfvars.go, pkg/tfvars/libvirt/libvirt.go
A corner case was discovered where if a sepcific option is specified multiple times(for example the
"address" option could be specified multiple times for different domains), only one of the options is
set. This is a bug and an oversight when adding the original code for the dnsmasq options. Fixed by using
a list instead of a map.
=> Bug 1958216: libvirt: Allow duplicate dnsmasq options

pkg/asset/installconfig/aws/session.go, pkg/asset/manifests/openshift.go
aws: support more auth options in manual mode
This is a manual cherry-pick of #4596 and its followup fix #4655
/assign @staebler
=> Bug 1958428: aws: support more auth options in manual mode

go.mod, go.sum, pkg/tfvars/baremetal/baremetal.go, vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/resource_ironic_deployment.go, vendor/modules.txt
This commit updates the ironic-terraform-provider to 0.2.6,
to handle instance_info/capabilities as strings in the format
`key1:value1,key2:value2`.
Change the capabilities from `map[string]string` to `string` in
`pkg/tfvars/baremetal/baremetal.go`.
=> Bug 1948563: Handle instance_info capabilities and update ironic-terraform

pkg/asset/installconfig/openstack/validation/cloudinfo.go, pkg/asset/installconfig/openstack/validation/machinepool.go, pkg/asset/installconfig/openstack/validation/machinepool_test.go, vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumetypes/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumetypes/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumetypes/results.go, vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumetypes/urls.go, vendor/modules.txt
When an user wants to deploy with rootVolume, they need to specify
a volume type.
We already checked that the volume type was set but we didn't check that
the type was actually existing.
With this patch, we now check that the type exists.
If the Volume Type doesn't exist, it'll show this error message:
```
FATAL failed to fetch Metadata: failed to load asset "Install Config": compute[0].platform.openstack.rootVolume.type.type: Invalid value: "wrong": Volume Type either does not exist in this cloud, or is not available
```
Note: this patch also adds test coverage when the type is an empty string, which wasn't done before.
=> Bug 1956208: openstack: add validation for volume types

pkg/asset/manifests/infrastructure.go, pkg/asset/manifests/infrastructure_test.go
The code that set an empty `AWSPlatformSpec` in the infrastructure resource was accidentally removed when adding support for [propagating user tags](https://github.com/openshift/installer/commit/2033421c8dcba057a643cdd35e040d7ddcd4c355). This causes the installer to panic when the install config included service endpoints.
=> Bug 1958420: aws: restore setting aws platform spec in infra resource

go.mod, go.sum, vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/baremetalhost_types.go, vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/ibmc.go, vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/idrac.go, vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/ilo4.go, vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/ipmi.go, vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/irmc.go, vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/redfish.go, vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/redfish_virtualmedia.go, vendor/modules.txt
This is to include https://github.com/metal3-io/baremetal-operator/pull/848
This is needed because we reference PowerInterface() in
pkg/tfvars/baremetal/baremetal.go, so Ironic power_interface
will be wrong for master deployment via terraform when irmc is
used.
See https://bugzilla.redhat.com/show_bug.cgi?id=1957869
=> Bug 1957869: vendor: update baremetal-operator to align irmc PowerInterface

pkg/asset/installconfig/openstack/validation/platform.go
If the user provides an UUID under platform.openstack.machinesSubnet
of a subnet which does not exist, the installer should not fail with a
backtrace.
Instead, the installer should exit gracefully and provide the correct error
to the user.
=> Bug 1957809: Validation of platform.openstack.machineSubnet

pkg/types/validation/installconfig.go, pkg/types/validation/installconfig_test.go
The publish: internal strategy is only available in cloud platforms,
GCP, Azure, AWS, Alibaba and IBM cloud, and should not be allowed as a
strategy for the other platforms.
Added a validation check to check if the strategy is internal and
the platform used is one of the valid cloud platforms. Check for IBM
and Alibaba is not yet added as they are not supported yet.
=> Bug 1953035: Disallow publish internal for non-cloud installations

pkg/destroy/baremetal/baremetal.go
While deleting any leftover bootstrap storage resources, just log a warning instead of exiting immediately, so that the installer can proceed with normal deletion.
=> Bug 1953019: Baremetal: While deleting cluster, warn instead of exiting 

pkg/asset/installconfig/ovirt/credentials.go, pkg/asset/tls/bootstrapsshkeypair.go, pkg/asset/tls/boundsasigningkey.go, pkg/asset/tls/cabundle.go, pkg/asset/tls/certkey.go, pkg/asset/tls/tls.go, pkg/asset/tls/utils.go, pkg/gather/ssh/ssh.go, pkg/terraform/exec/plugins/azureprivatedns/resource_private_dns_srv_record.go, pkg/terraform/exec/plugins/vsphereprivate/config.go, pkg/terraform/exec/plugins/vsphereprivate/resource_vsphereprivate_import_ova.go, pkg/types/kubevirt/validation/machinepool.go
This fixes a few small defects in the installer code as
mentioned here: http://download.eng.bos.redhat.com/rcm-guest/puddles/RHAOS/coverity/results/ose-installer/fe9e87fb04ae777d913e5787792756208392cf3a/stage_1/all_results.html
=> Bug 1960323: Address issues raised by coverity security scan

pkg/asset/installconfig/clustername.go, pkg/asset/installconfig/gcp/validation.go, pkg/asset/installconfig/gcp/validation_test.go, pkg/validate/validate.go
GCP does not allow certain resources to have names with words
similar to 'google'. Adding a regex check for known invalid
cluster names in GCP to inform the user before trying to create
the cluster.
Tested values:
Passed: test-googl, testgoogl-test, testgoogl, goo-test
Failed: goog-test, test-google, testgoogletest
=> Bug 1955336: Check cluster name for similarities with word 'google'

data/data/bootstrap/files/usr/local/bin/installer-gather.sh
When `openshift-install gather bootstrap` is passed the bootstrap node as
`--master`, the bootstrap node will attempt to run `installer-masters-gather.sh` on itself, via ssh.
Then when it tries to copy the resulting artifacts via `scp`, it does so
with a wildcard `scp` source parameter. Since it attempts to perform the
recursive copy with a wildcard source that is the same as the
destination (same because this is the bootstrap node actually copying from
itself to itself), `scp` starts behaving weirdly.
The weird scp behavior can be demonstrated by running the following 2 lines:
(warning, this will recursively create a nested directory until the file
system gives up. Seems to be harmless on my machine, but I can't
guarantee it won't break anything on yours)
```bash
mkdir -p scploop/loop …
```
=> Bug 1959703: Avoid scp wildcard recursion with installer-masters-gather.sh

pkg/tfvars/vsphere/vsphere.go
This change specifies the explicit path to the datacenter when passing
it to Terraform. Prior to this change, only the datacenter name was
passed, which caused a collision when the same name was used by
datacenters in different paths.
=> Bug 1955697: tfvars/vsphere: use explicit path for datacenter.

pkg/destroy/aws/shared.go
When destroying a cluster that has a bring-your-own private hosted zone, the search for the public hosted zone should be using the dotted domain (i.e., the domain that ends in a dot). Since the search was incorrectly using the un-dotted domain, the search was never able to find a match.
=> Bug 1957597: aws: using dotted domain when looking for public hosted zone

docs/user/openstack/customization.md
Documentation of this limitation under the externalDNS entry.
=> Bug 1954873: CoreOS only supports three dns namservers

pkg/types/ovirt/defaults/machinepools.go, pkg/types/ovirt/machinepool.go
- Handle empty affinity group names field
=> Bug 1959981: oVirt: fix empty AffinityGroupsNames handling

pkg/asset/installconfig/aws/permissions.go, pkg/destroy/aws/shared.go
UntagResorucesWithContext will retun without errors even when resources
cannot be untagged.  The untagging failures are retuned in the
FailedResourcesMap.  This commit will log the failure to untag the
resource and not incorrectly log the tag was removed.
=> Bug 1926547: pkg/destroy/aws: Log errors untagging shared resources

data/data/baremetal/masters/main.tf
While testing secure boot scenario where only 1 master is using,
we found that the instance_info capabilities for secure_boot was set
in a different master.
This was happening because in all allocations we were considering
all nodes, since we need to match 1-1 the information we don't need
to create allocations for each node.
=> bug 1959920: baremetal: Do not use ironic allocation

pkg/asset/installconfig/ovirt/validation.go, pkg/asset/installconfig/platformprovisioncheck.go
Currently, we validate existing affinity groups and cluster resources on the install-config creation.
This is a problem since the user may want to generate the install config using questions and then edit the affinity groups field.
Currently, if the user env does not have enough resources for the default affinity group settings then the install config generation will fail due to validations and the user will not get an install-config to edit.
This patch moves the validations to the ValidateForProvisioning to validate affinity group on cluster creation, meaning after the install config was generated and edited
=> Bug 1962274: oVirt move affinity groups validations to ValidateForProvisioning

docs/user/openstack/known-issues.md
This patch adds a documented known issue where we explain that we can't
edit a machine spec or it'll lead to problems like the servers being
removed.
We also give a tested resolution procedure.
More info: https://access.redhat.com/solutions/5998451
=> Bug 1951713: docs/openstack/known-issues: add section for machine spec edits

data/data/bootstrap/baremetal/README.md, data/data/bootstrap/files/usr/local/bin/bootkube.sh.template, data/data/openstack/topology/sg-master.tf, data/data/openstack/topology/sg-worker.tf, docs/design/baremetal/networking-infrastructure.md, docs/design/openstack/networking-infrastructure.md, docs/user/openstack/known-issues.md, upi/openstack/security-groups.yaml
Bootstrap no longer rely on mdns for name resolution. We can remove the `--mdns-publisher-image` flag for the bootstrap and remove the security group rules for mdns.
These rules where only defined for OpenStack plaform. This PR removes the rules for both UPI and IPI.
Also remove obsolete comment about coredns running with mdns plugin in documentation.
Depends on https://github.com/openshift/machine-config-operator/pull/2465, to remove dependency on the coredns's mdns plugin.
=> Bug 1946506: Bootstrap no longer relies on mdns

data/data/libvirt/variables-libvirt.tf
Fix for https://github.com/openshift/okd/issues/649
=> Bump default bootstrap memory.

go.mod, go.sum, vendor/github.com/ovirt/terraform-provider-ovirt/ovirt/resource_ovirt_vm.go, vendor/modules.txt
RHV changed the default behavior of creating High-Performance VMs.
In the past when creating a High-Performance VM it would be created with Existing auto pining policy, but now Existing is removed and shouldn't be used.
We need to update the terraform provider that is used within the Openshift installer to consume the changes.
=> Bug 1965921: [oVirt] High performance VMs shouldn't be created with Existing policy

data/data/bootstrap/baremetal/files/usr/local/bin/master-bmh-update.sh, data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template, data/data/bootstrap/baremetal/systemd/units/ironic.service
Currently keepalived monitors only the kubernetes API before determining
whether to failover to the control plane. However, we also use the API
VIP to host provisioning services since 22c32f8, so we need to include
Ironic in the health checks.  However, we need to stop Ironic when we're
done to trigger failover.
This change makes Ironic shutdown once all control plane hosts are
"active" (i.e. deployed), and the introspection data is synced. 
This is for use with https://github.com/openshift/baremetal-runtimecfg/pull/135.
=> Bug 1949859: baremetal: stop provisioning services once control plane is deployed

go.mod, go.sum, vendor/github.com/metal3-io/baremetal-operator/pkg/bmc/irmc.go, vendor/modules.txt
This is to include https://github.com/metal3-io/baremetal-operator/pull/880
Fix error: missing the following IPMI credentials in node's driver_info: ['ipmi_address'].
see https://bugzilla.redhat.com/show_bug.cgi?id=1965182
Signed-off-by: Zhou Hao <zhouhao@fujitsu.com>
=>  Bug 1965182: update baremetal-operator to fix miss IPMI credentials

pkg/asset/installconfig/ovirt/credentials.go
The installer project updated the version of the survey package which cause the hack of editing the PasswordQuestionTemplate to break due to misssing funtions such as: HelpIcon, QuestionIcon and HelpInputRune.
There is no reason to keep this hack just to edit the inital help message, instead we will move the ctrl+c note to the help message.
=> Bug 1967623: oVirt: Fix password input

docs/user/metal/external_loadbalancer_ipi.md
The HTTPS frontend should be listening on 443, not 80.
=> Bug 1952604: [baremetal] Fix port in external loadbalancer example config

pkg/tfvars/vsphere/vsphere.go
This reverts commit cbc778f7608f383174605f6299b3b0cd3060f7fa.
This change was insufficient to resolve the issue. Another solution will be needed, and this bit of code will not be used.
=> Bug 1955697: Revert "tfvars/vsphere: use explicit path for datacenter."

data/data/rhcos-amd64.json, data/data/rhcos-ppc64le.json, data/data/rhcos-s390x.json, data/data/rhcos.json
This brings in the following fixes:
BZ 1956489 - CVE-2021-3114 ignition: golang: crypto/elliptic: incorrect operations on the P-224 curve
BZ 1960748 - RHCOS PXE deployment script coreos-livepxe-rootfs randomly fails to download and verify the image with bonding LACP active-active
```
$ hack/update-rhcos-bootimage.py https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.7/47.83.202105220305-0/x86_64/meta.json amd64
$ hack/update-rhcos-bootimage.py https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.7-ppc64le/47.83.202105211710-0/ppc64le/meta.json ppc64le
$ hack/update-rhcos-bootimage.py https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.7-s390x/47.83.202105211211-0/s390x/meta.json s390x
```
=> Bug 1956483: Bump boot images for RHCOS fixes

data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
The downloader needs to modify some kernel arguments of the OS image based on the network stack.
cc @asalkeld @sadasu
=> Bug 1946079: baremetal: pass IP_OPTIONS to os downloader

docs/user/openstack/README.md
Add a note that if we deploy a cluster in an OpenStack AZ, it's
suggested to use Cinder backend if the service is available in this AZ,
since Cinder is topology aware.
Swift isn't deployed in AZs usually, so traffic would have to go
through the link between sites, which isn't optimal in real world.
=> doc/openstack: add a note about image registry in AZ

docs/user/aws/install.md, docs/user/azure/install.md, docs/user/gcp/install.md, docs/user/vsphere/install.md
This patch updates the "cloud-install" links in the documentation to
point to the current location.
=> docs/user/aws/install: Update cloud install links

data/data/rhcos-aarch64.json, data/data/rhcos-amd64.json, data/data/rhcos-ppc64le.json, data/data/rhcos-s390x.json, data/data/rhcos-stream.json, data/data/rhcos.json, docs/dev/pinned-coreos.md, hack/update-rhcos-bootimage.py
aarch64=48.84.202106091220-0
ppc64le=48.84.202106091427-0
s390x=48.84.202106091721-0
x86_64=48.84.202106091622-0
This bootimage bump contains fixes for the following RHBZs:
- https://bugzilla.redhat.com/show_bug.cgi?id=1944660
- https://bugzilla.redhat.com/show_bug.cgi?id=1954025
- https://bugzilla.redhat.com/show_bug.cgi?id=1958930
- https://bugzilla.redhat.com/show_bug.cgi?id=1969208
=> Bug 1962850: Bump RHCOS bootimages for various fixes

pkg/asset/installconfig/aws/validation.go, pkg/asset/installconfig/aws/validation_test.go
This is a manual cherry-pick of #4801.
Allow the user to specify a region that is not known to the instatller but does match the regex of a known partition without requiring the user to specify custom service endpoints. This is needed to support new regions that are added to known partitions.
Without this, it is not possible to use an unknown region is the standard partition. Terraform will not create the IAM roles correctly when specifying custom endpoints for a region in the standard partition because the request will try to create the role in the  cluster's region rather than in us-east-1.
This seems like the behavior that was desired when the check for whether custom service endpoints are needed was added in https://github.com/openshift/installer/commit/cf79a75308faf38e11f758457ca40748 …
=> Bug 1945467: aws: allow use of unknown regions in known partitions

pkg/asset/installconfig/kubevirt/client.go
This fixes a dropped error variable in `pkg/asset/installconfig/kubevirt`.
=> pkg/asset/installconfig/kubevirt: fix dropped error

data/data/azure/vnet/common.tf
Instead of dividing the IPv4 machine CIDR into 8 networks and only using 2 of those 8, divide into only 2 networks. Likewise,
for the IPv6 machine CIDR divide into only 2 networks instead of 2^16 networks.
https://issues.redhat.com/browse/CORS-1659
=> azure: divide machine CIDR into 2 networks for subnets

pkg/asset/installconfig/openstack/validation/platform.go, pkg/asset/installconfig/openstack/validation/platform_test.go
1. Add Unit Tests for validation of platform.openstack.machineSubnet.
2. Delete the duplicate logic in platform.openstack.machineSubnet
https://github.com/openshift/installer/blob/aba60410f3530cdf18cc73dfe290c2bd546ed357/pkg/asset/installconfig/openstack/validation/platform.go#L52-L54
=> OpenStack: Add Unit Tests for validation of platform.openstack.machineSubnet

pkg/destroy/openstack/openstack.go
Previously each destroy function would exit on the first conflict and
it was expected to retry on a next iteration, hoping that in the mean
time the conflict that prevented removal of the resource was fixed.
While this strategy works, it is also slower then necessary. A better
strategy is to try deleting all resources and ignore the ones that have
conflicts. On the next iteration there will be less conflicts.
This patch was tested on a openstack cluster with openshiftSDN, and
we observed a 37% faster cluster deletion. I expect the performance
boost to be significantly higher for clusters using kuryr.
=> Bug 1974598: OpenStack: Optimize cluster deletion

pkg/types/clustermetadata.go
While reviewing another PR noticed that `json` was
incorrect.
=> ibmcloud: fix struct field json

pkg/asset/machines/master.go, pkg/asset/machines/worker.go
Based on VMware vSphere performance best practices and
a resulting blog post from VMware in relation to vNUMA.
Cores should be used instead of sockets.
https://blogs.vmware.com/performance/2017/03/virtual-machine-vcpu-and-vnuma-rightsizing-rules-of-thumb.html
=> [SPLAT-211] vSphere: Switch from sockets to cores by default

.yamllint
data/data/manifests/openshift/cluster-networkconfig-crd.yaml is a
symlink to a vendored file. yamllint should ignored vendored files. I
don't see a generic way to ignore symlinks based on their targets, so
I'm adding this explicit path.
=> .yamllint: ignore cluster-networkconfig-crd.yaml

data/data/aws/bootstrap/main.tf
Give the bootstrap instance a dependency on the creation of the s3 bucket object holding the bootstrap's ignition config. The bootstrap instance requires the ignition config in order to complete its creation. It takes around 2 minutes to create the bucket object, and the instance creation has a 2-minute timeout. Consequently, there are times when the bootstrap fails to complete in time because the creation of the bucket object took too long.
=> Bug 1975475: aws: block creation of bootstrap instance until ignition config is uploaded

pkg/types/azure/validation/platform.go, pkg/types/azure/validation/platform_test.go
This prevents a validating failure when omitting `BaseDomainResourceGroupName` configurable which is never used in ARO.
=> azure: don't require BaseDomainResourceGroupName on ARO

pkg/asset/installconfig/azure/metadata.go, pkg/asset/installconfig/azure/session.go
Change in the function signatures allows a caller to provide credentials.
This is useful when we want to avoid a dependency on a file system or asking for manual input. This can happen in managed OpenShift services, where some packages from the installer are being used in the context of the webserver.
=> azure: changes the way we get credentials

OWNERS_ALIASES
Adding @rvanderp3  to approvers. Keeping out of reviewers to minimize number of review requests. 
/approve
@rvanderp3 you can put an lgtm on here if this looks good to you and you want to be added.
=> OWNERS: update vSphere-approvers

pkg/asset/cluster/tfvars.go
The TerraformVariables.Generate(), in case of baremetal, uses some configuration vars which require to be validated before their usage (for example, it tries to download the image file). This commit reuses the same validation rules already
defined in the Platform Provision Check asset.
Fixes #5040
=> baremetal: add PlatformProvisionCheck dependency for TerraformVariables asset

data/data/bootstrap/files/usr/local/bin/release-image-download.sh.template
If the wrong image is specified for a different architecture, then the following is observed:
```
systemd[1]: Starting Download the OpenShift Release Image...
release-image-download.sh[1392]: Pulling registry.ci.openshift.org/origin/release:4.8...
release-image-download.sh[1392]: d4d56de3fdd878f8c61032e6cb8fcc1fef03a28073b574ff7f1a6dbfb02f7359
release-image-download.sh[1392]: attempt to record the end of a stage without starting one
systemd[1]: release-image.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: release-image.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Download the OpenShift Release Image.
systemd[1]: Dependency failed for Bootstrap a Kubernetes cluster.
systemd[1]: bootkube.service: Job bootkube.service/start failed with result …
```
=> Fix sanity check image metadata arches match error

pkg/asset/machines/baremetal/machines.go
The metal3-image-cache daemonset is started unconditionally by the
cluster-baremetal-operator, serving on port 6181. However, we were only
pointing at this service in the MachineConfig if the provisioning
network was not present.
Given that the MachineConfig is fixed at install time while the
provisioning network can be added or removed by changing the
Provisioning resource, we should always use the cache.
This also means the cache will get exercised in CI, where previously it
was not.
=> baremetal: Always use image cache

pkg/asset/quota/openstack/openstack.go
Due to a missing capitalization we didn't run the kuryr-specific network
quota checks for OpenStack validation which could result in the
installation starting even though the user has not nearly enough quota
for a successful Kuryr deployment.
=> Bug 1978213: Run kuryr-specific quota checks for kuryr envs

pkg/asset/installconfig/aws/permissions.go
Elastic IPs are only created when the installer provisions VPCs and subnets. In the case where users install into an existing VPC, the installer does not need the permissions to create and associate EIPs. Therefore let's move these EIP permissions so that they are only checked when we create networking resources.
=> aws: move elastic ip permissions to create networking category

pkg/types/validation/installconfig.go
If a public key is configured in the install-config.yaml and fips is set to true,
validate that the ssh public key type is compatible with FIPS mode.
Only rsa and ecdsa types are valid at the moment.
https://bugzilla.redhat.com/show_bug.cgi?id=1962414
=> Bug 1962414: FIPS: validate ssh public key type compatibility

data/data/install.openshift.io_installconfigs.yaml, data/data/openstack/main.tf, data/data/openstack/masters/main.tf, data/data/openstack/masters/variables.tf, data/data/openstack/variables-openstack.tf, docs/user/openstack/customization.md, pkg/tfvars/openstack/openstack.go, pkg/types/openstack/machinepool.go, pkg/types/openstack/servergrouppolicy.go, pkg/types/openstack/validation/machinepool.go, pkg/types/openstack/validation/machinepool_test.go, pkg/types/openstack/validation/platform.go, pkg/types/validation/machinepools.go
Prior to this change, the Control plane nodes are created in a server
group with the hardcoded policy "soft-anti-affinity".
This change adds a new configuration knob in the OpenStack-specific
MachinePool configuration of `install-config.yaml`.
The new property `controlPlane.platform.openstack.serverGroupPolicy`
defines the policy that will be applied to the Control Plane server
group.
Acceptable values are:
* `affinity`
* `anti-affinity`
* `soft-affinity`
* `soft-anti-affinity`
Defaults to `soft-anti-affinity`, to match the previous hardcoded
behaviour.
Validation will fail if the property is set on the Compute MachinePool.
Implements [OSASINFRA-2507](https://issues.redhat.com/browse/OSASINFRA-2507)
/hold for gathering team consensus on the API.
=> openstack: Expose master server group policy

README.md, docs/user/metal/install_ipi.md
BM IPI is no longer experimental, and some of the content is no
longer accurate, this PR does a first-pass update of the content.
=> baremetal: Update IPI docs for latest version

pkg/asset/cluster/tfvars.go
We need to return a custom error.
We wrapped a nil error which causes errors.Wrapf to return nil and then the installer would move to the next phase and fail due to missing tfvars.json file
=> Bug 1972582: Installing with an oVirt network with 2 vnics on the same network causes the installer to not create tfvars and fail with terraform error

pkg/terraform/gather/ovirt/ip.go
`gather bootstrap` command will collect logs from the VMs only if the boostrap VM still exists.
this change adds the control planes VMs IP information, resulting the master logs
to be collected as well.
=> Bug 1979038: oVirt: include master IPs when running must gather

images/openstack/Dockerfile.ci
Openstacksdk 0.53 introduced an error with older version of Neutron,
where it fails with:
400: Client Error for url: <cloud>/v2.0/security-group-rules, Unrecognized attribute(s) 'remote_address_group_id'
This was fixed in openstacksdk 0.56 which we do not yet have in the
repositories. Until then, pin to the known working 0.36 version.
Upstream issue: https://storyboard.openstack.org/#!/story/2008577
=> Bug 1980029: Pin openstacksdk

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Kube-api operator need to render different params in sno and ha modes.
Installer should provide infrastructure file path for kube-api rendering process
=> bootstrap: add --infra-config-file to kube-api render

data/data/openstack/topology/sg-master.tf, data/data/openstack/topology/sg-worker.tf, upi/openstack/security-groups.yaml
For `LoadBalancer` `Services` OpenStack cloud provider creates an
Octavia loadbalancer and adds all the nodes as members pointing to the
NodePort on the hosts. Previously the SGs opening traffic on those ports
were constrained to CIDR of the nodes subnet. This works fine in case of
Octavia with Amphora driver, as HAProxy will change the source-IP of the
traffic to the IP of the LB:
```
traffic source-IP: (x.x.x.x)               (y.y.y.y)
caller (x.x.x.x)      ->     LB (y.y.y.y)     ->     member
```
The LBs are created in nodes subnet, so that worked. Things are
different in case of OVN Octavia driver:
```
traffic source-IP: (x.x.x.x)               (x.x.x.x)
caller (x.x.x.x)      ->     LB (y.y.y.y)     ->     member
```
OVN preserves the source-IP of the original caller, meaning that SG …
=> OpenStack: Open 0.0.0.0/0 on NodePorts

pkg/asset/manifests/openstack/cloudproviderconfig.go, pkg/asset/manifests/openstack/cloudproviderconfig_test.go
Kuryr already handles the service type Load Balancer and we need to
explicitly disable the use of octavia in the cloud provider
configuration otherwise we'll run into issues once the default for
`use-octavia` changes from false to true with the out-of-tree openstack
cloud provider.
Implements [OSASINFRA-2510](https://issues.redhat.com/browse/OSASINFRA-2510)
=> OpenStack: explicitly disable octavia when using kuryr

OWNERS_ALIASES
This PR updates my nick in the owners file because of my recent GitHub account change.
=> Updated owner aliases because of GitHub account change

data/data/vsphere/main.tf
Allow the tag that is created by the installer to be attached
to a datastore for storage policy based management.
=> vSphere: Add datastore and storagepod to category

data/data/rhcos-amd64.json, data/data/rhcos-ppc64le.json, data/data/rhcos-s390x.json, data/data/rhcos.json, pkg/rhcos/ami_regions.go
This boot image bump for RHCOS 4.6 fixes the following BZs:
1956491 - CVE-2021-3114 ignition: golang: crypto/elliptic: incorrect operations on the P-224 curve
1960750 - RHCOS PXE deployment script coreos-livepxe-rootfs randomly fails to download and verify the image with bonding LACP active-active
Additionally, this includes the AMI published to the ap-northeast-3
(Osaka) region.
46.82.202106161040-0 amd64
46.82.202106162140-0 ppc64le
46.82.202106161139-0 s390x
=> Bug 1956485: bump RHCOS 4.6 boot images

images/baremetal/Dockerfile.ci, images/installer-artifacts/Dockerfile.rhel, images/installer/Dockerfile.ci, images/installer/Dockerfile.ci.rhel7, images/installer/Dockerfile.upi.ci, images/libvirt/Dockerfile.ci, images/mock/Dockerfile, images/openstack/Dockerfile.ci, pkg/asset/releaseimage/default.go
registry.svc.ci.openshift.org has been moved to registry.ci.openshift.org. The old
one was on a 3.x cluster and the new one is on a 4.x cluser.
=> Bug 1951572: registry.svc.ci.openshift.org is no longer valid

hack/build.sh
GOFLAGS is a space-separated value; quoting it here results in errors.
/cc @sosiouxme
=> Fix build with multiple GOFLAGS

data/data/install.openshift.io_installconfigs.yaml, pkg/types/baremetal/defaults/platform.go, pkg/types/baremetal/defaults/platform_test.go, pkg/types/baremetal/platform.go
Implicitly, tfvars makes the default value for BootMode "UEFI." This
should instead be done by pkg/types/baremetal/defaults, and so that
`explain` shows an empty value as being allowed.
=> baremetal: set default boot mode explicitly

pkg/terraform/gather/ovirt/ip.go
fix panic caused by nil pointer dereference
=> oVirt: must gather fix nil pointer panic

docs/user/openstack/README.md, docs/user/openstack/customization.md
In 4.9 we introduce support for LoadBalancer services. This means that
user might need to tweak the cloud provider options to match their
OpenStack cluster configuration. This commit adds documentation on how
to do it before and after the installation.
=> Add documentation on setting cloud provider opts

pkg/destroy/vsphere/vsphere.go
=> Delete storage policy ids when cluser is deleted

data/data/rhcos-aarch64.json, data/data/rhcos-amd64.json, data/data/rhcos-ppc64le.json, data/data/rhcos-s390x.json, data/data/rhcos-stream.json, data/data/rhcos.json, docs/dev/pinned-coreos.md, hack/update-rhcos-bootimage.py
This brings in properly identified RHCOS 4.9 boot images for all
architectures.  In addition, the following BZs are addressed:
1959248 - CVE-2021-31525 ignition: golang: net/http: panic in ReadRequest and ReadResponse when reading a very large header
1960485 - Cannot use DASD at virtio block device when installing RHCOS on KVM
aarch64=49.84.202106302247-0
ppc64le=49.84.202107010047-0
s390x=49.84.202106302347-0
x86_64=49.84.202107010027-0
```
$ plume cosa2stream --target=data/data/rhcos-stream.json --distro=rhcos aarch64=49.84.202106302247-0 ppc64le=49.84.202107010047-0 s390x=49.84.202106302347-0 x86_64=49.84.202107010027-0
$ hack/update-rhcos-bootimage.py https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases/rhcos-4.9-aarch64/49.84.202106302247-0/aarch64/meta.jso …
```
=> Bug 1970179: update boot images for RHCOS 4.9

data/data/manifests/openshift/baremetal-provisioning-config.yaml.template
This was removed in #5015 but we should still include it if a user
provides a value - since it's now optional we'll pass an empty
string if no value is provided, which will trigger the new logic
that detects the interface name by MAC.
=> Bug 1984576: baremetal: reinstate provisioningInterface for provisioning CR

pkg/asset/machines/azure/machines.go, pkg/asset/manifests/azure/cloudproviderconfig.go, pkg/asset/manifests/azure/types.go, pkg/asset/manifests/cloudproviderconfig.go
These commits add specific cloud provider configuration for Azure Stack Hub. 
be4635c - Adds generic support, separating configuration that differs from public Azure. 
d210770 - Is a temporary commit to add credentials to the cloud provider config. Once bootstrap support for the cloud controller manager is added we should revert this commit and keep credentials in a secret, which is not presently supported as explained in the commit message.
Merging d210770 would allow us to make progress with fully automated IPI install and reverting later would be simple enough. I can create a revert PR now with a basic PoC of how to use the merge config based on ARO.
=> Azure Stack cloud provider config

pkg/destroy/aws/aws.go
Destroy AWS EFS volumes that have owner tag when destroying a cluster. Recursively destroy all access points and mount targets used by the volume, even when they are not tagged, otherwise EFS cannot be deleted. Not sure what's common practice for recursive deletion on `cluster destroy` - access points could be tagged (and thus we may require users to tag them), but mount targets do not have any tags.
AWS EFS CSI driver is an optional OCP component (installed via OLM). Right now, an EFS must be created manually by user. Since VPC and subnets cannot be deleted if they are used by an EFS volume, allow user to tag the EFS volume so cluster destruction deletes EFS, VPC + subnets (with two iterations to get the ordering right...)
KEP for whole AWS EFS support: …
=> Destroy AWS EFS volumes

pkg/asset/manifests/dns.go
Skip adding private DNS zones to the DNS manifest for Azure Stack so the ingress controller does not try to create DNS records in private zones, which don't exist in ASH.
Example manifest for Azure Stack:
```
$ cat ash-manifests/m/manifests/cluster-dns-02-config.yml 
apiVersion: config.openshift.io/v1
kind: DNS
metadata:
creationTimestamp: null
name: cluster
spec:
baseDomain: pddimg.ppe.azurestack.devcluster.openshift.com
publicZone:
id: /subscriptions/e90a4bc2-2f4e-4d36-874b-9011e4734d74/resourceGroups/openshiftInstallerRG/providers/Microsoft.Network/dnszones/ppe.azurestack.devcluster.openshift.com
status: {}
```
Example manifest for Azure:
```
$ cat azure-man/manifests/cluster-dns-02-config.yml 
apiVersion: config.openshift.io/v1
kind: DNS
metadata:
creationTimestamp: null
name: cluster …
```
=> pkg/asset/manifests/dns: don't create private zone in Azure Stack

cmd/openshift-install/destroy.go, pkg/asset/cluster/ibmcloud/ibmcloud.go, pkg/asset/cluster/metadata.go, pkg/destroy/ibmcloud/OWNERS, pkg/destroy/ibmcloud/cloudobjectstorage.go, pkg/destroy/ibmcloud/cloudresource.go, pkg/destroy/ibmcloud/dns.go, pkg/destroy/ibmcloud/doc.go, pkg/destroy/ibmcloud/errortracker.go, pkg/destroy/ibmcloud/floatingip.go, pkg/destroy/ibmcloud/iam.go, pkg/destroy/ibmcloud/ibmcloud.go, pkg/destroy/ibmcloud/image.go, pkg/destroy/ibmcloud/instance.go, pkg/destroy/ibmcloud/loadbalancer.go, pkg/destroy/ibmcloud/publicgateway.go, pkg/destroy/ibmcloud/register.go, pkg/destroy/ibmcloud/resourcegroup.go, pkg/destroy/ibmcloud/securitygroup.go, pkg/destroy/ibmcloud/subnet.go, pkg/destroy/ibmcloud/vpc.go, pkg/types/ibmcloud/metadata.go
Remove all IBM Cloud resources that are created with an OpenShift cluster.
=> ibmcloud: Destroy cluster

pkg/types/baremetal/validation/platform.go, pkg/types/baremetal/validation/platform_test.go
Due to a limitation in dnsmasq an IPv6 provisioning network cannot be
larger than a /64 network.
bug: https://bugzilla.redhat.com/show_bug.cgi?id=1947293
=> Bug: 1947293 Baremetal: Validate provisioning network size

data/data/azure/cluster/master/master.tf
Fix code consistency issue of missing dash in nic name.
```
> $ git grep '${var.cluster_id}-master-${count.index}' | wc -l
21
> $ git grep '${var.cluster_id}-master${count.index}' | wc -l 
1
```
=> Bug 1882490: data/azure/master: Add dash to nic name

data/data/gcp/post-bootstrap/variables.tf
The cluster_ip_address output variable is null in the cluster stage when the publishing strategy is internal. A null output variable results in no value actually being written to the tfvars. This results in an error when running with publish: internal: "No value for required variable."
=> Bug 1986420: GCP: make cluster_ip_address optional post-bootstrap

pkg/types/validation/installconfig.go, pkg/types/validation/installconfig_test.go, pkg/validate/validate.go
tl;dr: require dual-stack install-configs to be "IPv4-primary". To be backported to 4.8.
At some point in early 4.7 we noticed that "IPv6-primary" dual-stack configurations (eg, where the first value for clusterNetworks/serviceNetworks is IPv6 rather than IPv4) didn't work right due to cluster-etcd-operator issues. I think that specific bug was fixed, but other problems have popped up, and more importantly, we aren't testing IPv6-primary installation anywhere, and dev-scripts actually _can't_ bring up an IPv6-primary cluster currently. Someone just pointed out that a customer had tried this with a 4.8 fc release and was running into weird problems, so let's just block it.
(eg, see https://coreos.slack.com/archives/CQQ7P8UTT/p1623765189017300, …
=> Bug 1972776: improve dual-stack install-config validation

pkg/asset/manifests/azure/cloudproviderconfig.go, pkg/asset/manifests/azure/cloudproviderconfig_test.go
This updates the Azure cloud provider config to set excludeMastersFromStandardLB to false. The default value is true, which
has not been a problem because the functionality was broken. With the move to out-of-tree providers the functionality has been restored, in which case if a master node restarts the service controller will not add it back to the load balancer backend pool.
cc @JoelSpeed @lobziik
=> Bug 1987083: Azure: cloud provider config excludeMastersFromStandardLB -> false

pkg/destroy/aws/aws.go
AWS EFS CSI driver creates AccessPoint with the "owner" tag.
Delete these AccessPoints on cluster destruction.
The access points would be cascade-deleted during EFS volume destruction, however, before reaching the code, the destruction would fail with:
> WARNING unrecognized elastic file system resource type access-point
=> Bug 1987279: Delete AWS EFS AccessPoints with owner tags

pkg/asset/quota/openstack/openstack.go, pkg/asset/quota/quota.go
When deploying OCP with pre-provisioned networks, we do not need to have
available quotas for routers, networks and subnets for the machines
since they are created already.
This patch does the following:
* On Kuryr based deployment:
- Do not touch the quotas on networks / subnets, since we still need to
have a bunch of quotas to create what's needed for Kuryr.
- Relax the quota on Routers, since it wouldn't create one in BYON mode.
* For other network types:
Relax routers, subnets, networks to be 0 by default and if we don't
configure OCP in BYON mode, then we add the necessary quotas (1 router,
1 network and 1 subnet).
Allow to skip quota checks by re-using
`OPENSHIFT_INSTALL_SKIP_PREFLIGHT_VALIDATIONS` variable that has been used
for validations already.
=> Bug 1987845: openstack: relax quota checks in BYON

pkg/asset/installconfig/aws/validation.go, pkg/asset/installconfig/aws/validation_test.go
=> Bug 1981929:  aws: allow use of unknown regions in known partitions

pkg/asset/quota/openstack/openstack.go
We currently document that a tenant should have ports quota set to 15
(or 1500 with Kuryr), but we didn't take in account the ports that are
used for the machines:
3 masters + 3 workers = 6 ports.
With these new numbers, we can deploy clusters with the existing
documentation with enough resources used from available quotas.
=> Bug 1978213: openstack - relax value for minNetworkConstraint

pkg/types/gcp/validation/platform.go
Remove the "Northern" word from the description of us-east4
to make it similar to the description in GCP.
=> Bug 1963132: Fix us-east4 Ashburn description

data/data/manifests/bootkube/openshift-kubevirt-infra-namespace.yaml
Runlevel was required in installer version <4.6 due to significant
start times of components waiting for the apiserver but it is no
longer necessary. More info is in this bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1977129
=> Bug 1977129: Remove runlevel label from openshift-kubevirt-infra

pkg/asset/installconfig/ibmcloud/client.go
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1989604
=> Bug 1989604: ibmcloud: GetVSIProfiles error handling

pkg/asset/quota/openstack/openstack.go
We missed Kuryr when we relaxed networking quotas and decremented the
minimal constraints.
=> Bug 1987845: openstack: relax quotas with Kuryr

data/data/fcos-stream.json
Use latest FCOS images as of https://github.com/coreos/fedora-coreos-streams/commit/2e15ba504e8e8fe9cd22962146c9181241c1653d
Requires https://github.com/openshift/release/pull/14082 to add OKD tests
=> Bug 1990617: Update fedora-coreos stream to 34.20210725.2.0

pkg/asset/quota/openstack/openstack.go
OpenStack clouds deployed by Red Hat have a `default` security group
which contains 4 rules.
This patch will relax the number of security groups and rules so it
takes in account that a number of these resources could already be there
before installing OpenShift.
This is fine because the installer will create 2 security groups (one
for masters and one for workers, when using OpenShiftSDN, etc) and less
than 45 rules, so 56 rules is enough.
Same with Kuryr, new numbers will be enough as well.
This will allow our users following the documentation and the quotas, to
deploy on Red Hat OpenStack without modifying the quota numbers.
=> Bug 1989917: openstack: relax Security Group quotas

upi/aws/cloudformation/05_cluster_master_nodes.yaml, upi/aws/cloudformation/06_cluster_worker_node.yaml
On AWS, m5a.10xlarge is not a valid instance type anymore. Replaced with m5a.12xlarge
per https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstanceTypes.html
generated with `find . -type f -print0 | xargs -0 sed -i 's|m5a.10xlarge|m5a.12xlarge|'`
https://bugzilla.redhat.com/show_bug.cgi?id=1990206
=> Bug 1990206: Fix invalid UPI AWS instance type

pkg/asset/quota/openstack/openstack.go
When using a machine network, it's very likely that a port will already
be used by Neutron for OVN metadata, so we need to take that in account
when checking available resources.
=> Bug 1987845: openstack: relax port constrain by one

data/data/rhcos-aarch64.json, data/data/rhcos-amd64.json, data/data/rhcos-ppc64le.json, data/data/rhcos-s390x.json, data/data/rhcos-stream.json, data/data/rhcos.json
This brings in fixes for the following issues:
1970180 - Cannot use DASD at virtio block device when installing RHCOS on KVM [4.8.z]
1970183 - CVE-2021-31525 ignition: golang: net/http: panic in ReadRequest and ReadResponse when reading a very large header [openshift-4.8.z]
1974850 - [4.8] coreos-installer failing Execshield
```
$ hack/update-rhcos-bootimage.py https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases/rhcos-4.8-aarch64/48.84.202106171757-0/aarch64/meta.json aarch64
$ hack/update-rhcos-bootimage.py https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases/rhcos-4.8/48.84.202106301921-0/x86_64/meta.json amd64
$ hack/update-rhcos-bootimage.py https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases/rhcos-4. …
```
=> Bug 1969651: bump RHCOS 4.8 boot images

data/data/bootstrap/files/usr/local/bin/installer-gather.sh, data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh
OKD runs on FCOS, which requires services release-image-download on bootstrap and machine-config-master-firstboot on nodes. Gathering a log bundle should include them too.
Fixes https://github.com/openshift/okd/issues/651
=> Bug 1992876: gather: Add OKD specific journal logs

data/data/libvirt/variables-libvirt.tf
This commit bumps memory to 8gb for bootstrap vm and 16gb for masters, which seem minimal defaults for a successful install.
User can still override those values when building but this provide an alternative workflow when using public binaries (the openshift-baremetal one containing libvirt bindings)
=> Bug 1992463: libvirt: bump default memory and cpus

data/data/install.openshift.io_installconfigs.yaml, docs/user/azure/customization.md, pkg/explain/printer_test.go, pkg/types/azure/platform.go
Replace "assume assume" with "assume" in azure
byo resource group description and docs.
Generated with `find . -type f -print0 | xargs -0 sed -i 's|assume assume|assume|'`
Ran codegen for `install.openshift.io_installconfigs.yaml`
https://bugzilla.redhat.com/show_bug.cgi?id=1989973
=> Bug 1989973: Fix Azure typo

pkg/asset/quota/openstack/openstack.go
For Kuryr:
Reduce from 1493 to 1490:
* 6 ports taken by machines (and added later in the requirements)
* 2 for floating IPs
* 1 for router gateway
* 1 for bootstrap machine
= 10
1500 - 10 = 1490
So we have now 1490 as a new relaxed number which should satisfy the
documented quotas.
For non-Kuryr:
Reduce from 8 to 4:
* 1 taken by network gateway
* 2 taken by API & Ingress ports or FIPs
* 1 taken by bootstrap
-> this makes 4
Then the installer adds one port per machine, so 6 by default (3 masters
and 3 workers) which makes 10 total. The documented quota is 15 so have
some margin error.
=> Bug 1978213: openstack/quota: relax min ports

pkg/types/aws/validation/platform.go
AWS S3 bucket does not allow more than 10 user tags to be applied
to them. Since the installer adds two tags, the "Name" and the
"kubernetes.io" tags, the user specified tags should only be a maximum
of 8.
Adding this restriction to the validation of user tags to prevent
error from terraform during cluster creation.
=> Bug 1958154: Restrict number of AWS user tags

data/data/manifests/bootkube/cvo-overrides.yaml.template
```
NAME      VERSION                             AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.9.0-0.nightly-2021-08-18-144658   True        False         157m    Cluster version is 4.9.0-0.nightly-2021-08-18-144658
{
"channel": "stable-4.8",
"clusterID": "a26e6104-d182-488e-b261-d785e5caf424"
}
```
The default channel should be stable-4.9.
=> Bug 1995655: bump default channel to stable-4.9

pkg/asset/installconfig/aws/session.go
If the user specified the AWS_SHARED_CREDENTIALS_FILE which is
either invalid or empty file, the credentials are collected by
the installer and are written to a default location (~/.aws/credentials)
when it can be written to the location specified in the above location.
Adding a small fix to write to the location specified in the location
specified by AWS_SHARED_CREDENTIALS_FILE if the file is either empty
or is invalid.
=> Bug 1974640: Write user credentials to specified env location

pkg/destroy/azure/azure.go
If there are other resources in the resource group that are in use
by resources in other groups then the deletion will be blocked.
The error message displayed is not user friendly and hence adding
a check to see if the error code returned by azure autorest is
409, which is ResourceGroupDeletionBlocked, and display a proper
message to the user.
=> Bug 1976016: Display proper error message on failure to delete

cmd/openshift-install/version.go
This should make it easier to identify the release/payload architecture
which a particular installer binary will install, since that is often
not clear from the release image name.
=> Bug 1996124: version: display release architecture

pkg/destroy/aws/aws.go
For cluster destroy on AWS china regions, the cn-northwest-1
region is always searched for resources even if the cn-north-1
region is used for installation. This might be true for the
public regions where there are a few resources in the us-east-1
location but the china regions are separate partitions and are
not involved in the other region installation.
Removing the northwest region client from the destroy so it
will not be used to search if it is not used for installation.
=> Bug 1969371: Stop searching other China regions for resources

pkg/asset/installconfig/ibmcloud/client.go
Make sure the account ID context is set for a resource group look up. This option is required when using a ServiceID-based IBM Cloud API key.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1993207
=> Bug 1993207: fix(ibmcloud): Set account ID for resource group look up

.ci-operator.yaml, docs/dev/dependencies.md, go.mod, go.sum, hack/build.sh, hack/go-fmt.sh, hack/go-genmock.sh, hack/go-lint.sh, hack/go-sec.sh, hack/go-test.sh, hack/go-vet.sh, hack/verify-codegen.sh, hack/verify-vendor.sh, images/installer/Dockerfile.ci.rhel7, images/installer/Dockerfile.upi.ci, images/installer/Dockerfile.upi.ci.rhel8, images/libvirt/Dockerfile.ci, images/openstack/Dockerfile.ci
We need the support of the new features in the component.
=> Bug 1999119: bump to golang-1.16 

pkg/destroy/ibmcloud/ibmcloud.go, pkg/destroy/ibmcloud/resourcegroup.go
Make sure the account ID context is set for a resource group look up on destroy operations. This option is required when using a ServiceID-based IBM Cloud API key.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1993207
=> Bug 1993207: fix(ibmcloud): Set account ID for rg on destroy

data/data/rhcos-aarch64.json, data/data/rhcos-amd64.json, data/data/rhcos-ppc64le.json, data/data/rhcos-s390x.json, data/data/rhcos-stream.json, data/data/rhcos.json
`e2e-metal-ipi-ovn-ipv6` and `e2e-metal-ipi-ovn-dualstack` jobs are failing in bootstrap stage. Service network endpoint can not be up and pods are crashlooping.
This PR reverts https://github.com/openshift/installer/pull/5168
=> Bug 1998643: Revert "bump RHCOS boot images for 4.9"

data/data/fcos-amd64.json, data/data/fcos-stream.json
Reverting FCOS back to 0626 as newer versions seem to break oVirt/vSphere networking. See https://github.com/openshift/okd/issues/783
=> Bug 1999421: Fedora CoreOS: revert to 34.20210626.3.1

go.mod, pkg/terraform/exec/plugins/vsphereprivate/resource_vsphereprivate_import_ova.go, vendor/modules.txt
The out-of-tree csi requires hardware 15, vSphere 6.7U3 and greater
Hardware 15 is only supported on 6.7 U2 and greater.
This PR checks for each ESXi host version, if less than 6.7 U3
sets the hardware version to 13. If greater than or equal to 6.7U3
the hardware version is set to 15.
=> Bug 2000352: [CORS-1716] vsphere: set the imported ova hardware version

data/data/install.openshift.io_installconfigs.yaml, data/data/kubevirt/bootstrap/main.tf, data/data/kubevirt/bootstrap/variables.tf, data/data/kubevirt/datavolume/variables.tf, data/data/kubevirt/main.tf, data/data/kubevirt/masters/main.tf, data/data/kubevirt/masters/variables.tf, data/data/kubevirt/variables-kubevirt.tf, docs/user/kubevirt/install-config.yaml, docs/user/kubevirt/install_ipi.md, go.mod, go.sum, pkg/asset/cluster/tfvars.go, pkg/asset/installconfig/ibmcloud/mock/ibmcloudclient_generated.go, pkg/asset/installconfig/kubevirt/client.go, pkg/asset/installconfig/kubevirt/mock/client_generated.go, pkg/asset/installconfig/kubevirt/validation.go, pkg/asset/installconfig/kubevirt/validation_test.go, pkg/asset/machines/kubevirt/machines.go, pkg/asset/machines/kubevirt/machinesets.go, pkg/tfvars/kubevirt/kubevirt.go, pkg/types/kubevirt/platform.go, pkg/types/kubevirt/validation/platform.go, vendor/github.com/openshift/cluster-api-provider-kubevirt/pkg/apis/kubevirtprovider/v1alpha1/types.go, vendor/modules.txt
Currently, the kubevirt VirtualMachines that are created during the cluster provisioning, are hard-coded with Bridge interface binding, despite the actual type of the network that was configured in `install-config.yaml`.
This PR adds an optional new field to install-config.yaml, specifying the interface binding method to be used when creating the kubevirt VirtualMachines.
Example:
```
platform:
kubevirt:
apiVIP: <api_vip>
ingressVIP: <ingress_vip>
namespace: kubevirt-nested-cluster
networkName: <NAD name>
InterfaceBindingMethod: SRIOV          # <------- New Field
storageClass: <storage class used>
```
This PR is strictly related to PR in openshift/cluster-api-provider-kubevirt - https://github.com/openshift/cluster-api-provider-kubevirt/pull/38, as it's changing the API for …
=> Add SRIOV Support for Kubevirt Provider

docs/dev/operators.md
The link moved from the cluster-version-operator to the enhancements repo.
Unsubscribing because the bot seems to have gone a bit crazy. Please tag me if you want me to be notified. :)
Signed-off-by: Rohan CJ <rohantmp@gmail.com>
=> docs: fix broken link to CVO/operators.md in operators.md

images/installer/Dockerfile.upi.ci
Adding yq for ASH CI to pick up information from yaml file to
login to the ASH environment which is needed for cluster
installation.
=> UPI: Add yq to images for ASH CI

docs/user/gcp/install_upi.md
This change makes clear the ROUTER_IP variable needs to be set prior to usage in the GCP UPI documentation.
=> gcp upi: clarify ROUTER_IP needs to be set

data/data/azure/variables-azure.tf
It is confusing that the example is different than the value,
which is the case since the default value changed: 120a9a35af715385c75ad9e246a4df9b103e12e6
=> bring example in line with the default value

pkg/destroy/openstack/openstack.go
When using byon with Kuryr the Router would be identified based
on the Primary Network used by the Servers, which would be filtered
by the device-owner compute:nova. However, when using azs the
device-owner name can change. This commit fixes the issue by
identifying the router by looking for any tagged networks that
has a subnet connected to the router. The gorouting for this
approach can't be run before other clean ups because the CNO
would always attempt to re-connect the service subnet to the
router.
Co-Authored-By: Maysa Macedo <maysa.macedo95@gmail.com>
Co-Authored-By: Emilien Macchi <emilien@redhat.com>
=> Bug 1993364: openstack/destroy: fix Kuryr/BYON

pkg/destroy/openstack/openstack.go
When performing a cluster destroy we should
look for all cluster tagged Networks that might be
connected to the router, regardless if it was created
by CAPO. This commit updates the filtering for the
look up of Networks and ensure to skip the Subnet
when no Gateway is set.
=> Bug 1993364: Consider all Networks on Router clean up

pkg/asset/manifests/cloudproviderconfig.go, pkg/asset/manifests/ibmcloud/cloudproviderconfig.go, pkg/asset/manifests/ibmcloud/cloudproviderconfig_test.go
Add required cloud config fields for IBM Cloud CCM.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1994142
=> Bug 1994142: fix(ibmcloud): Add more cloud config fields

pkg/types/validation/installconfig.go, pkg/types/validation/installconfig_test.go, pkg/validate/validate.go
backport of #5005
(needed a manual backport just because of a conflict in the `import` changes)
/assign @patrickdillon 
since you approved the original
=> Bug 1973421: [4.8] improve dual-stack install-config validation

data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
Since https://github.com/openshift/ironic-image/pull/190 the inspector components and entrypoint moved to the ironic-image, so we need to update the image and entrypoint to match, also aligning with https://github.com/openshift/cluster-baremetal-operator/pull/132
=> baremetal: Specify entrypoint when starting inspector

docs/user/openstack/deploy_sriov_workers.md
The syntax for reference links in markdown was incorrect and generated
broken links.
=> Bug 2002567: OpenStack: Fix links in SR-IOV workers doc

pkg/destroy/ibmcloud/cloudobjectstorage.go
Delete COS instances recursively to delete any associated resource keys that will be created by image-registry operator. Without this option set, destroy is blocked by failure to delete these COS instances.
```
time="2021-08-18T17:19:12Z" level=debug msg="Failed to delete COS instance ipi-ci-test-12-glldh-image-registry: Cannot delete instance or alias, resource keys must first be deleted."
time="2021-08-18T17:19:12Z" level=debug msg="Cloud Object Storage Instances: 1 items pending"
```
=> fix(ibmcloud): Delete COS in recursive mode

data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
The runlogwatch.sh script is now intended to watch
both directories, so we only need one instance of
this container.
Side Note: gathering the inspection logs is also currently broken due to a bug,
this is fixed upstream metal3-io/ironic-image#289
=> Bug 2004600: Remove duplicate ramdisk log container

data/data/openstack/bootstrap/main.tf, data/data/openstack/bootstrap/variables.tf, data/data/openstack/main.tf, data/data/openstack/masters/main.tf, data/data/openstack/variables-openstack.tf
Since commit 63f7a03d8967d754a9e2110ccd6a1d5cf321515d the
extra_tags seem to go unused
=> terraform/openstack: remove unused extra_tags

data/data/rhcos-aarch64.json, data/data/rhcos-amd64.json, data/data/rhcos-ppc64le.json, data/data/rhcos-s390x.json, data/data/rhcos-stream.json, data/data/rhcos.json
This updates the RHCOS boot image metadata in the installer with the
most recent version of RHCOS 4.9 artifacts.
This includes fixes for the following BZs:
1967483 - coreos-installer fails to download Ignition (DNS error, failed to lookup address)
1974411 - Installation with multipath parameters in parmfile fails (DNS resolution missing)
1980679 - On a Azure IPI installation MCO fails to create new nodes
1999577 - RHCOS live ISO can fail to boot in UEFI mode; drops to grub shell
2002374 - Inexplicably slow kubelet on bootstrap makes installation fail
2004605 - RHCOS-4.9 failed to boot in FIPS mode on s390x
2004676 - Boot option recovery menu prevents image boot
Changes generated with the following:
```
$ plume cosa2stream --target data/data/rhcos-stream.json --distro rhcos --url …
```
=> Bug 1981999: bump RHCOS boot images for 4.9

images/installer/Dockerfile.upi.ci
CI is failing with jq not found error. Installing it from pip
modules instead.
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/22060/rehearse-22060-pull-ci-openshift-installer-master-e2e-azure-upi/1440695554429423616
=> images: Fix jq not found error

docs/user/openstack/README.md
Documentation to describe the steps to enable octavia as a day 2
operation in a cluster. 
/hold
/cc @dulek
=> Bug 2004236: Document how to enable Octavia Day 2

data/data/bootstrap/systemd/units/kubelet.service.template, pkg/asset/ignition/bootstrap/bootstrap.go
Prefer IPv6 hostIP on bootstrap IPv6 deployments 
Kubelet can end up choosing IPv4 addresses as its hostIP, which after:
https://github.com/openshift/cluster-kube-apiserver-operator/pull/1042/files
mean that the kubernetes API service ends up with an endpoint being an
IPv4 address.  This breaks the kubernetes API loadbalancer in the
service network and prevent the deployment from succeeding.
Backport of https://github.com/openshift/installer/pull/4756
=> Bug 1980866: [4.7] Prefer IPv6 hostIP on bootstrap IPv6 deployments

data/data/rhcos-amd64.json, data/data/rhcos-stream.json, data/data/rhcos.json
This bumps the RHCOS boot image in the metadata for the x86_64
platform only.  This is to address the following BZ:
2007089 - [4.9] Intermittent failure mounting /run/media/iso when booting live ISO from USB stick
Changes were generated with:
```
$ plume cosa2stream --target data/data/rhcos-stream.json --distro rhcos --url https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases x86_64=49.84.202109241334-0
$ hack/update-rhcos-bootimage.py https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases/rhcos-4.9/49.84.202109241334-0/x86_64/meta.json amd64
```
=> Bug 2007086: bump RHCOS boot images for x86_64 only

docs/dev/libvirt/README.md
s/resovectl/resolvectl
Signed-off-by: Julian Wiedmann <jwi@linux.ibm.com>
=> docs: libvirt: fix typo

docs/user/azure/install_upi_azurestack.md, upi/azurestack/03_infra.json, upi/azurestack/04_bootstrap.json, upi/azurestack/05_masters.json
In the current solution, ASH only has one public load balancer. Both api DNS records point to the public IP address. This creates an
internal load balancer and updates the docs to point the api-int record to the internal LB.
I have a test in progress. So far it has been successful with masters pulling the ignition from api-int, which points to the private ip address.
=> Bug 2008599: Azure Stack: Add Internal Load Balancer

data/data/aws/cluster/vpc/sg-master.tf, data/data/gcp/cluster/network/firewall.tf, data/data/ibmcloud/network/vpc/security-groups.tf, data/data/openstack/topology/sg-master.tf, upi/aws/cloudformation/03_cluster_security.yaml, upi/gcp/03_firewall.py, upi/openstack/security-groups.yaml
This opens ports for gathering cluster-policy-controller metrics. The container itself is running on the same pod as kube-controller-manager.
I updated the configs in similar manner as kube-controller-manager. Please let me know if there are other steps needed.
=> open cluster-policy-controller ports for metrics

data/data/rhcos-amd64.json, data/data/rhcos-ppc64le.json, data/data/rhcos-s390x.json, data/data/rhcos.json
This updates the "legacy" RHCOS boot image metadata to match what is
contained in the stream metadata in `data/data/rhcos-stream.json`.
Note: this does not touch `data/data/rhcos-aarch64.json` as it already
matches the stream metadata and was not updated as part of #5227
=> Bug 2009019: update legacy RHCOS boot image metadata

pkg/asset/manifests/cloudproviderconfig.go, pkg/asset/manifests/ibmcloud/cloudproviderconfig.go, pkg/asset/manifests/ibmcloud/cloudproviderconfig_test.go
Add the set of subnet names created for the VPC into the IBM Cloud
provider configuration.
=> Inject subnet names into IBM Cloud provider config

pkg/asset/installconfig/openstack/validation/machinepool.go, pkg/asset/installconfig/openstack/validation/machinepool_test.go
OpenStack flavors report RAM in MB and not GB. This unit error caused
the installer to accept flavors with insufficient RAM to install
OpenShift.
=> Bug 2009699: Fix RAM validation for openstack flavors

data/data/rhcos-amd64.json, data/data/rhcos-ppc64le.json, data/data/rhcos-s390x.json, data/data/rhcos.json, hack/update-rhcos-bootimage.py
```
./hack/update-rhcos-bootimage.py https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases/rhcos-4.7-ppc64le/47.84.202109242011-0/ppc64le/meta.json ppc64le
./hack/update-rhcos-bootimage.py https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases/rhcos-4.7-s390x/47.84.202109242305-0/s390x/meta.json s390x
./hack/update-rhcos-bootimage.py https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases/rhcos-4.7/47.84.202109241831-0/x86_64/meta.json amd64
```
=> Bug 1964753: Bump RHCOS 4.7 boot image

pkg/asset/cluster/tfvars.go, pkg/tfvars/openstack/openstack.go
This refactoring moves code from the shared `tfvars` asset directory to
the OpenStack-specific package.
The behaviour is left completely unchanged.
Implements [OSASINFRA-2695](https://issues.redhat.com/browse/OSASINFRA-2695)
=> openstack: Move TFVars logic to own package

data/data/rhcos-amd64.json, data/data/rhcos-ppc64le.json, data/data/rhcos-s390x.json, data/data/rhcos.json, hack/update-rhcos-bootimage.py
```
python update-rhcos-bootimage.py https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases/rhcos-4.6-ppc64le/46.82.202109161439-0/ppc64le/meta.json ppc64le
python update-rhcos-bootimage.py https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases/rhcos-4.6-s390x/46.82.202109171905-0/s390x/meta.json s390x
python update-rhcos-bootimage.py https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases/rhcos-4.6/46.82.202109171856-0/x86_64/meta.json amd64
```
Signed-off-by: Renata Ravanelli <rravanel@redhat.com>
=> Bug 1964751: Bump boot images for RHCOS fixes

data/data/config.tf, data/data/openstack/main.tf, data/data/openstack/topology/sg-master.tf, data/data/openstack/topology/variables.tf, pkg/asset/cluster/tfvars.go, pkg/asset/manifests/scheduler.go, pkg/tfvars/tfvars.go
In the case of compact clusters, where master nodes are schedulable, we
need to open ports for ingress, same as for workers.
=> Bug 1955544: Add ingress rules to master SG for compact clusters

data/data/openstack/main.tf, data/data/openstack/variables-openstack.tf, data/data/openstack/workers/main.tf, data/data/openstack/workers/variables.tf, docs/user/openstack/README.md, docs/user/openstack/customization.md, pkg/asset/machines/openstack/machines.go, pkg/tfvars/openstack/openstack.go, pkg/types/openstack/servergrouppolicy.go, pkg/types/openstack/validation/machinepool.go, pkg/types/openstack/validation/machinepool_test.go, pkg/types/openstack/validation/platform.go, scripts/openstack/manifest-tests/server-groups/install-config.yaml, scripts/openstack/manifest-tests/server-groups/test_machines.py, scripts/openstack/manifest-tests/server-groups/test_machinesets.py
With this change, Compute nodes within each MachineSet are automatically
created in a Server group, with a default policy of
"soft-anti-affinity".
With this change, a "serverGroupPolicy" can be set in install-config, on
the worker MachinePool and/or in the platform default.
Implements [OSASINFRA-2570](https://issues.redhat.com/browse/OSASINFRA-2570)
Co-Authored-By: Matthew Booth <mbooth@redhat.com>
=> openstack: Expose worker server group policy

upi/gcp/04_bootstrap.py
Updating ignition version from 3.1.0 to 3.2.0 for GCP UPI
templates.
=> Bug 1949672: Update UPI ignition version to 3.2.0

data/data/bootstrap/files/usr/local/bin/installer-gather.sh, data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh
During log-bundle analysis it should be trivial to find out which FCOS/RHCOS os image was used during installation.  
Fixes https://github.com/openshift/okd/issues/652
=> Record rpm-ostree status and history in log-bundle

data/data/rhcos-aarch64.json, data/data/rhcos-amd64.json, data/data/rhcos-ppc64le.json, data/data/rhcos-s390x.json, data/data/rhcos-stream.json, data/data/rhcos.json
This bumps the RHCOS 4.9 boot image metadata to the latest available
versions for each architecture. As part of this change, we are
including fixes for the following issues as part of the boot images:
2009652 - [4.9] Multipath day1 not working on s390
2011958 - [4.9] [tracker] Kubelet rejects pods that use resources that should be freed by completed pods
2011961 - [4.9] [tracker] Storage operator is not available after reboot cluster instances
Changes generated with the following:
```
$ plume cosa2stream --target data/data/rhcos-stream.json --distro rhcos --url https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases aarch64=49.84.202110080947-0 ppc64le=49.84.202110081256-0 s390x=49.84.202110081202-0 x86_64=49.84.202110081407-0
$ ./hack/update-rhcos-bootimage.py …
```
=> Bug 2009653: bump RHCOS 4.9 boot images

OWNERS_ALIASES
I am not part of the oVirt Installer team anymore.
Signed-off-by: Douglas Schilling Landgraf <dlandgra@redhat.com>
=> ovirt: remove dougsland from OWNERS_ALIASES

pkg/asset/cluster/aws/aws.go, pkg/asset/installconfig/platformpermscheck.go
The installer tags the IAM roles that are specified by the user
and deletes it during cluster destroy which is not ideal since
the installer should not be deleting the user created resources.
Removing the code that tags the IAM roes provided by the user and
also removing the permission required to delete the IAM role if
the user provided it.
=> aws: Remove shared tags from user specified IAM roles

upi/ovirt/create-templates-and-vms.yml, upi/ovirt/inventory.yml
guaranteed memory added, ovirt.ovirt collection role updated and check for template added)
=> ovirt: update of upi playbook files

docs/dev/pinned-coreos.md
Since we don't ship detached signatures, we're currently populating the artifact signature fields with dead links.
cc @miabbott @cgwalters @jlebon
=> docs/dev/pinned-coreos: pass `--no-signatures` to `plume cosa2stream`

pkg/types/baremetal/validation/platform.go, pkg/types/baremetal/validation/platform_test.go
If ProvisioningNetworkCIDR is provided to "cidr.Host"
with host bits set e.g. 172.22.0.1/24 vs 172.22.0.0/24,
then the same host bits are set in the
BootstrapProvisioningIP and ClusterProvisioningIP.
This happens because "cidr.Host" is expecting a network address
as returned by net.ParseCIDR but ipnet.MustParseCIDR returns
a host CIDR.
=> Bug 2006291: baremetal: Prevent ProvisioningNetworkCIDR with host bits set

pkg/destroy/openstack/openstack.go
Cherry-pick of the following commits:
-  Bug 1993364: openstack/destroy: fix Kuryr/BYON: 1d87b0858bd2be90f126a9cd18990b5192a32aad
- Consider all Networks on Router clean up: 37df7484fa27de1e10e303658db2071e704425ce
=> Bug 2004569:Fix router clean up upon cluster destroy

pkg/tfvars/aws/aws.go
This commit sets the boostrap node to use the same instance type as the control-plane nodes
in order to avoid failures that we have seen when the hard-coded instance type of m5 is unavailable in the zone.
=> Bug 2017985: Set AWS Bootstrap Type == Master

pkg/tfvars/aws/aws.go
This commit sets the boostrap node to use the same instance type as the control-plane nodes in order to avoid failures that we have seen when the hard-coded instance type of m5 is unavailable in the zone.
=> Bug 2017986: Set AWS Bootstrap Type == Master

data/data/azure/bootstrap/main.tf
Instead of creating a temp file and then uploading that to an azure
storage blob, we can upload the ignition file created by the go code to
azure.
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2004313
=> Bug 2004313: azure: Skip making azure bootstrap ignition temp file

pkg/destroy/azure/azure.go
Azure Stack Hub destroyer checks for the environment name before
deleting the A records but it checks the environment name after
the Azure SDK returns an environment and the sdk right now is
returning "HybridEnvironment" instead of "AzureStackCloud" that
the destroyer is expecting.
Adding a fix to pick our cloud name instead on the one returned
by the Azure sdk.
=> azurestack: Fix destroyer to delete A records

scripts/openstack/manifest-tests/additional-security-group/install-config.yaml, scripts/openstack/manifest-tests/cinder-availability-zones/install-config.yaml, scripts/openstack/manifest-tests/nova-availability-zones/install-config.yaml, scripts/openstack/manifest-tests/server-groups/install-config.yaml
The openstack manifests tests use an install config with the
clusterID field that is no longer supported by the installer.
Changes to the installer to enforce strict unmarshalling of the
install config is in place but is being hindered by the openstack
manifests tests in this PR.
https://github.com/openshift/installer/pull/5307
=> openstack: Fix install config for openstack manifests

data/data/vsphere/bootstrap/outputs.tf, data/data/vsphere/master/outputs.tf, data/data/vsphere/pre-bootstrap/main.tf, data/data/vsphere/pre-bootstrap/outputs.tf, pkg/terraform/gather/vsphere/ip.go, pkg/terraform/stages/split.go, pkg/terraform/stages/vsphere/stages.go
Customize ExtractHostAddresses per platform (optional).
In this first case, we use a custom ExtractHostAddresses for vSphere.
https://issues.redhat.com/browse/CORS-1754
=> Implement WithCustomExtractHostAddresses to gather bootstrap in stages

pkg/asset/installconfig/installconfig.go, pkg/asset/installconfig/installconfig_test.go
In order to stop the user from adding unrecognized properties
in the install config, a validation check is added to force the
user to remove them. This is done by enforcing a strict
unmarshalling of the install config yaml file that will raise an
error when an unknown property is added.
This will force the installer to return an error for the first
occurence of an unknown property since the current library
returns only the first unknown field.
=> validation: Enforce strict unmarshalling of config

pkg/asset/installconfig/vsphere/validation.go
Adding a check to see if vsphere network is set before validating
it for UPI installations where network is optional.
=> Bug 1956776: Fix network validation for UPI

pkg/asset/installconfig/aws/permissions.go
s3:GetBucketReplication is not a valid IAM action. The correct action is s3:GetReplicationConfiguration which is also included.
https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazons3.html
Since the installer attempts to verify that it has all of the permissions that it thinks it needs, it fails when it checks for this permission and aborts the install. This means that we must include the invalid permission in our IAM policy and ignore the warnings that this generates in order to run the cluster install.
=> Bug 2021364: aws: remove invalid s3 permission

data/data/install.openshift.io_installconfigs.yaml, data/data/vsphere/pre-bootstrap/main.tf, data/data/vsphere/variables-vsphere.tf, docs/user/vsphere/customization.md, pkg/asset/cluster/tfvars.go, pkg/terraform/exec/plugins/vsphereprivate/resource_vsphereprivate_import_ova.go, pkg/tfvars/vsphere/vsphere.go, pkg/types/vsphere/platform.go
This PR enables thin provisioning via the importing process
of the RHCOS ova. Terraform will then clone the virtual machine
based on the existing template disk type.
This adds an additional option in the vsphere platform struct `Thin`.
=> vSphere IPI: Enable thin provisioning via the OVA import

data/data/baremetal/main.tf, data/data/baremetal/masters/main.tf, data/data/baremetal/masters/variables.tf, data/data/baremetal/variables-baremetal.tf, pkg/asset/cluster/tfvars.go, pkg/asset/ignition/bootstrap/baremetal/template.go, pkg/asset/machines/baremetal/hosts.go, pkg/asset/machines/baremetal/hosts_test.go, pkg/tfvars/baremetal/baremetal.go, pkg/tfvars/baremetal/baremetal_test.go, pkg/types/baremetal/defaults/platform.go, pkg/types/baremetal/defaults/platform_test.go, pkg/types/baremetal/platform.go, pkg/types/baremetal/validation/platform.go, pkg/types/baremetal/validation/platform_test.go, pkg/types/validation/installconfig_test.go
The current patch provides a fix for the issue BZ 2003113.
The logic for generating baremetal manifests and Terraform variables now takes into account the host `role` tag properly, if defined.
To remain backward compatible, if an host doesn not have any role defined (or supported value), it's considered eligible for the ControlPlane or Compute respectively, based on the configured requirements.
For that, the validation rule has been enhanced to verify that the correct number of hosts have been configured.
=> Bug 2003113: Improve host role management during assets creation

pkg/destroy/aws/shared.go
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1965969
=> Bug 1965969: aws: Output public zone id correctly when deleting hosted dns records

docs/user/metal/install_upi.md, upi/metal/README.md
This is a documentation update for the Equinix Metal UPI (based on the Packet terraform provider). This PR only updates the text and links in the relevant README.md and install_upi.md.
=> update Packet UPI for Equinix Metal rename

pkg/validate/validate.go, pkg/validate/validate_test.go
The vsphere vcenter validation in the installer right now is
to check if the first character starts with a lowercase alphabet
but we should allow digits as well so removing the first
character check in validation.
=> Bug 2021607: Relax vcenter hostname check

pkg/asset/releaseimage/default.go
This PR updates the registry.ci.openshift.org/origin image to 4.9.
The quick start guide for libvirt installation relies on source compiled binary. When the installer is built from the master branch it fails to install as the image that is pulled is of v4.8 and some of the command args are not supported anymore.
For example, this is one of the error seen on the bootstrap node, 
```
bootkube.service
Error: unknown flag: --infra-config-file
Usage: Sep 23 12:24:08 ocp-xxxxxxxxxxxx bootkube.sh[2271]: cluster-kube-apiserver-operator render [flags]
```
I could not find an image for version 4.10/master, if there is one I will update the commit to use that.
=> Update registry.ci.openshift.org/origin image to 4.9

cmd/openshift-install/create.go
This is to improve the user experience of someone watching the console for the installer by telling the user when the timer started, using the local timestamp.
=> Add timestamps to Waiting messages when creating clusters

data/data/install.openshift.io_installconfigs.yaml, data/data/vsphere/pre-bootstrap/main.tf, data/data/vsphere/pre-bootstrap/outputs.tf, data/data/vsphere/variables-vsphere.tf, docs/user/vsphere/customization.md, docs/user/vsphere/privileges.md, pkg/asset/installconfig/vsphere/client.go, pkg/asset/installconfig/vsphere/mock/vsphereclient_mock.go, pkg/asset/installconfig/vsphere/validation.go, pkg/asset/machines/vsphere/machines.go, pkg/asset/manifests/vsphere/cloudproviderconfig.go, pkg/terraform/exec/plugins/vsphereprivate/resource_vsphereprivate_import_ova.go, pkg/tfvars/vsphere/vsphere.go, pkg/types/validation/installconfig_test.go, pkg/types/vsphere/platform.go, pkg/types/vsphere/validation/platform.go
Adds support for installing a cluster into an existing resource pool when using IPI on VMware. This allows users to take advantage of IPI on VMware with fewer cluster-wide permissions. Resolves #3921.
Heavily borrows from PR #3498. Tested manually against 4.7.0-0.okd-2021-07-03-190901 on vSphere 6.7 with (new functionality) and without (existing functionality) a resource pool. This was done by cherry-picking these commits on top of  vrutkovs/installer:release-4.7-okd.
TODO:
=> IPI for vSphere w/ existing resource pool

pkg/types/validation/installconfig.go, pkg/types/validation/installconfig_test.go
Relax the imageContentSource validation to allow for mirroring root registry.
This is a follow up to a previous attempt: #5297 which didn't quite fix the issue. The use of url.Parse does not work as expected. This PR utilized validate.Host function to check for a valid host name/IP when the canonical check fails.
=> bug 1960378: Relax the imageContentSource validation

data/data/vsphere/variables-vsphere.tf, pkg/terraform/exec/plugins/vsphereprivate/resource_vsphereprivate_import_ova.go
In #4664 I incorrectly commented to use `eagerZeroedThick`.
The correct disktype to keep the vSphere install the same
as previous versions is `thick`. eagerZeroed as named
will write zeros when creating the vmdk which significantly
extends the time to import and clone virtual machines.
=> vSphere: Set default disktype to thick not eager

data/data/alibabacloud/cluster/dns/privatezone.tf
The ingress record is created by the ingress-operator is no longer required to be created by the installer.
=> Alibaba Cloud Provider: remove the ingress record.

upi/aws/cloudformation/04_cluster_bootstrap.yaml
this is needed to spin up ARM UPI clusters. given the fact that the release payloads are not manifest listed yet, the bootstrap instance type has to correspond to the specific architecture of the release payload.
=> upi/aws/cloudformation: make bootstrap instance type configurable

data/data/config.tf, data/data/openstack/main.tf, data/data/openstack/topology/sg-master.tf, data/data/openstack/topology/variables.tf, pkg/asset/cluster/tfvars.go, pkg/asset/manifests/scheduler.go, pkg/tfvars/tfvars.go
In the case of compact clusters, where master nodes are schedulable, we
need to open ports for ingress, same as for workers.
Manual cherry-pick of https://github.com/openshift/installer/pull/5320 onto release-4.8.
=> [release-4.8] Bug 2023363: Add ingress rules to master SG for compact clusters

pkg/terraform/exec/plugins/openstack.go
In terraform-provider-openstack, the OS_CLOUD environment variable takes
precedence over what's passed directly.
=> Bug 2015837: openstack: unset OS_CLOUD for running Terraform

data/data/alibabacloud/bootstrap/main.tf, data/data/alibabacloud/bootstrap/variables.tf, data/data/alibabacloud/cluster/main.tf, data/data/alibabacloud/cluster/outputs.tf, data/data/alibabacloud/cluster/resourcegroup/main.tf, data/data/alibabacloud/cluster/resourcegroup/outputs.tf, data/data/alibabacloud/cluster/resourcegroup/variables.tf, data/data/alibabacloud/cluster/vpc/sg-master.tf, data/data/alibabacloud/cluster/vpc/sg-worker.tf, data/data/install.openshift.io_installconfigs.yaml, pkg/asset/installconfig/alibabacloud/alibabacloud.go, pkg/asset/installconfig/alibabacloud/validation.go, pkg/types/alibabacloud/metadata.go, pkg/types/alibabacloud/platform.go
Support the creation of a new resource group to manage the resources in the cluster.
Users do not need to manually create a resource group before creating a cluster. The `resourceGroupID` parameter is no longer a required parameter
=> Alibaba: support to create a resource group

data/data/alibabacloud/cluster/vpc/slb.tf
- Remove listeners 80 and 443 for public and private SLB[1]
- Fix Health check protocol to HTTP port 6080 (kube-apiserver sidecar for "insecure" health checks): SLB does
not support health check protocol HTTPS[2][3]
- when `health_check_type`  is not defined, the default will be set which is `TCP`[4]. Keeping explicitly the value of each listener.
- Change the port of machine-config-server health check, listener port 22623, to HTTP that binds on port 22624
- More details on the [internal thread](https://coreos.slack.com/archives/C01PES793LL/p1637846770449300)
References:
1. Other Cloud implementation ([AWS](https://github.com/openshift/installer/blob/master/data/data/aws/cluster/vpc/master-elb.tf#L124-L157) and [Azure](https://github.com/openshift/installer/blob/master/data/data/azure/vnet …
=> fix/alibaba-slb: remove unused listeners, and set kube-apiserver to HTTP/6080

data/data/install.openshift.io_installconfigs.yaml, pkg/types/alibabacloud/platform.go
In fact, it has no effect if it is not empty. we do not query and destroy resources through resource group. So this description is incorrect
=> Alibaba: fix: update comment on ResourceGroupID

pkg/types/openstack/validation/machinepool.go, pkg/types/openstack/validation/machinepool_test.go
If the user has explicitly provided `controlPlane` and `compute` configuration, then there won't be a default to consider.
This was hit in CI once `platform.openstack.computeFlavor` was no longer defined in a generated `install-config.yaml` file. This had been masking the bug since setting that attribute resulted in us initializing `config.Platform.OpenStack.DefaultMachinePlatform` with an `openstack.MachinePool` instance and populating the `FlavorName` attribute of this struct (see `pkg/types/conversion/installconfig.go` for more info).
=> Bug 2027329: Handle unset default machine pool

data/data/install.openshift.io_installconfigs.yaml, docs/user/metal/install_ipi.md, pkg/types/baremetal/platform.go, pkg/types/baremetal/validation/platform.go, pkg/types/baremetal/validation/platform_test.go
This PR adds a new `install-config` field to store network configuration data (with validation) as described in the enhancement https://github.com/openshift/enhancements/pull/817
=> baremetal: add NetworkConfig field

pkg/asset/installconfig/alibabacloud/client.go
The `LIKE` is default search mode on DescribeDomains api, In this mode,
if you search `openshift.com`, can match `xx.openshift.com` and
`openshift.com.xx`, but using `EXACT` mode, only return `openshift.com`.
=> Alibaba: fix: use EXACT search mode

OWNERS_ALIASES
Please add Kiran Thyagaraja (kirankt) and Caleb Boylan (squidboylan) into the Installer reviewers list.
=> Add Kiran and Caleb into Installer reviewers

upi/azure/04_bootstrap.json, upi/azure/05_masters.json, upi/azure/06_workers.json
This updates the azure UPI arm templates to not add the ssh keys.
The azure API does not support using ed25519 ssh keys which
caused the deployment to fail when using ed25519 keys, we are already
providing ssh keys in the ignition so we can bypass this limitation.
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1968364
=> Bug 1968364: azure: fix upi bug preventing using ed25519 keys

data/data/alibabacloud/cluster/dns/privatezone.tf, data/data/alibabacloud/cluster/dns/variables.tf, data/data/alibabacloud/cluster/main.tf, data/data/alibabacloud/cluster/master/outputs.tf, data/data/alibabacloud/cluster/outputs.tf
The `<master><n>.<cluster name>.<base domain>` records is not needed on
base domain
=> Alibaba: fix: remove the master node records

data/data/ibmcloud/network/image/main.tf
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2027387
Remove the usage of the `etag` TF variable with `filemd()`. This variable is intended for TF to compute the diff of a file to perform an update of an existing object. The installer is not designed to run update operations, so we can just remove.
The `filemd()` TF function is causing high memory consumption according to https://github.com/hashicorp/terraform/issues/23890.
=> Bug 2027387: fix(ibmcloud): Do not compute image file checksum

go.mod, go.sum, vendor/github.com/terraform-providers/terraform-provider-google/google/common_operation.go, vendor/github.com/terraform-providers/terraform-provider-google/google/error_retry_predicates.go, vendor/modules.txt
In CI, we're hitting errors like this:
```
level=error msg=Error: Error when reading or editing Target Pool
"ci-op-x5j99sbj-82914-2f74l-api": googleapi: Error 403: Quota exceeded
for quota group 'ReadGroup' and limit 'Read requests per 100 seconds' of
service 'compute.googleapis.com' for consumer
'project_number:711936183532'., rateLimitExceeded
```
This was fixed in v3.62.0, however v3.62.0 uses v2 of the terraform sdk. This
changes the installer to use the openshift fork which contains the
existing version in the repo (3.27.0), with these two fixes
applied.[1][2]
[1] hashicorp/terraform-provider-google#8746
[2] hashicorp/terraform-provider-google#8997
=> vendor: update terraform-provider-google for rate limit fix

docs/dev/libvirt/load_balancer.md
The installer for the development libvirt target does not launch a load balancer by default.
A default configuration of a basic HAProxy config is given here as a guideline for developers.
Signed-off-by: Tim Hansen <tihansen@redhat.com>
=> libvirt: add doc on a default load balancer configuration for libvirt

data/data/alibabacloud/cluster/dns/variables.tf, data/data/alibabacloud/cluster/master/variables.tf, data/data/alibabacloud/cluster/ram/variables.tf, data/data/alibabacloud/cluster/vpc/variables.tf, data/data/alibabacloud/variables-alibabacloud.tf, pkg/tfvars/alibabacloud/alibabacloud.go
Remove the default value in terraform variables, because the root module
and tfvars file should always be  explicitly supplying a value.
=> Alibaba: fix: remove the default value

go.mod, go.sum, vendor/github.com/terraform-providers/terraform-provider-google/google/common_operation.go, vendor/github.com/terraform-providers/terraform-provider-google/google/error_retry_predicates.go, vendor/modules.txt
In CI, we're hitting errors like this:
```
level=error msg=Error: Error when reading or editing Target Pool
"ci-op-x5j99sbj-82914-2f74l-api": googleapi: Error 403: Quota exceeded
for quota group 'ReadGroup' and limit 'Read requests per 100 seconds' of
service 'compute.googleapis.com' for consumer
'project_number:711936183532'., rateLimitExceeded
```
This was fixed in v3.62.0, however v3.62.0 uses v2 of the terraform sdk. This
changes the installer to use the openshift fork which contains the
existing version in the repo (3.27.0), with these two fixes
applied.[1][2]
[1] hashicorp/terraform-provider-google#8746
[2] hashicorp/terraform-provider-google#8997
=> Bug 2028611: vendor: update terraform-provider-google for rate limit fix

pkg/types/alibabacloud/machinepool.go
DiskCategory validation had string type instead of enum.
On master without this change:
```
$ go generate ./pkg/types/installconfig.go
github.com/openshift/installer/pkg/types:-: conflicting types in allOf branches in schema: string vs DiskCategory
github.com/openshift/installer/pkg/types:-: conflicting types in allOf branches in schema: string vs DiskCategory
github.com/openshift/installer/pkg/types:-: conflicting types in allOf branches in schema: string vs DiskCategory
Error: not all generators ran successfully
run `controller-gen crd:crdVersions=v1 paths=. output:dir=../../data/data/ -w` to see all available markers, or `controller-gen crd:crdVersions=v1 paths=. output:dir=../../data/data/ -h` for usage
exit status 1
pkg/types/installconfig.go:67: running "go": exit status 1
```
=> Alibaba: fix kubebuilder validation

images/installer-artifacts/Dockerfile.rhel
This will require a simultaneous commit to ocp-build-data, so this should not be merged until both are ready.
=> installer-artifacts: add darwin/arm64 binary

data/data/azurestack/cluster/master/outputs.tf
The terraform stages needs just a list of control plane ips to
gather bootstrap logs but the azurestack terraform output is
a list of lists causing the gather command to fail. Fixing the
output of the terraform stage to flatten the ips to a single
list. This will enable azurestack gather command.
=> azurestack: Fix gather bootstrap for azurestack

docs/user/aws/install.md, docs/user/azure/install.md, docs/user/gcp/install.md, docs/user/ovirt/install_upi.md, docs/user/vsphere/install.md, pkg/asset/installconfig/pullsecret.go
The console applications currently in cloud.redhat.com have been moved to
to a new URL at console.redhat.com.
https://cloud.redhat.com/blog/check-out-our-new-look
Signed-off-by: Mikel Olasagasti Uranga <mikel@olasagasti.info>
=> Update URL from cloud.redhat.com to console.redhat.com

pkg/asset/machines/worker.go
I was looking at this issue:
https://github.com/openshift/openshift-docs/issues/35793
Which then led me to wonder exactly what the defaults are per
platform for disk sizes.
And then I stumbled into this 120 vs 128 thing that as best
I can tell from the git history is mostly an accident.  If someone
happens to know differently (e.g. can/should we unify on 120 or 128?)
then that'd be good.
In the meantime, an additional benefit here is that if one does
e.g. `git grep -i volume.*size` these constants will turn up.
It took me a little while to figure out how to backtrack from
the Terraform code to this.  (The lines here only contained
`Size` which is too generic to grep)
=> machines: Extract root disk sizes to constants

data/data/ibmcloud/network/vpc/security-groups.tf
Condense the SecurityGroup names for IBM Cloud to make sure those
names can meet the IBM Cloud restricitions (character limits).
Related: https://bugzilla.redhat.com/show_bug.cgi?id=2027498
=> Condense IBM Cloud SG names

pkg/asset/installconfig/openstack/validation/platform.go
This is a combined backport of 2 commits:
- Bug 1957809: Validation of platform.openstack.machineSubnet
- Update pkg/asset/installconfig/openstack/validation/platform.go
This will help to fix user experience when a subnet doesn't exist, the error will be shown as the following:
```
FATAL failed to fetch Metadata: failed to load asset "Install Config": platform.openstack.machinesSubnet: Not found: "27178ac7-a4d8-41c3-938a-0605707657e9"
```
Instead of a huge Go trace.
=> Bug 1928761: Validation of platform.openstack.machineSubnet

pkg/asset/installconfig/aws/availabilityzones.go
Certain resources cannot be created in local zones such as load
balancers, this causes an openshift installation to fail, because of
this we need to filter out local zones when generating a default list of
zones to use
https://bugzilla.redhat.com/show_bug.cgi?id=1997059
=> Bug 1997059: aws: Filter out local zones when generating a default list of zones

data/data/aws/cluster/vpc/sg-master.tf, data/data/gcp/cluster/network/firewall.tf, data/data/ibmcloud/network/vpc/security-groups.tf, data/data/openstack/topology/sg-master.tf, upi/aws/cloudformation/03_cluster_security.yaml, upi/gcp/03_firewall.py, upi/openstack/security-groups.yaml
This reverts commit 2636aef6cdf0f897f98446e29c969d61b6b009a7 (https://github.com/openshift/installer/pull/5105).
Opening port 10357 has to be reverted due to the problems with opening ports during cluster upgrades and moving to a different solution.
=> Revert "open cluster-policy-controller ports for metrics"

data/data/install.openshift.io_installconfigs.yaml, pkg/types/installconfig.go
The `machineCIDR` config option wasn't replaced by `machineCIDRs` - it was replaced by `machineNetwork[*].cidr`. Similarly, `serviceNetwork` isn't a like-for-like replacement for `serviceCIDR`: the latter took a single value while the former takes a list. Update docs to reflect this, fixing an unrelated bug in the process.
=> pkg/types: Correct docs for deprecated options

docs/user/azure/install_upi.md
remove --public-access blob,use sas token in BOOTSTRAP_URL
https://bugzilla.redhat.com/show_bug.cgi?id=2020216#c7
=> Bug 2020216: replace public-access with sas token in bootstrap deployment

docs/dev/pinned-coreos.md
The file data/data/rhcos-stream.json was deleted in https://github.com/openshift/installer/commit/d773ee557311fda59565bb82e947d7d55001252b
and the corresponding data now lives in data/data/coreos/rhcos.json. 
Let's update the documentation to reflect this change.
=> docs/dev/pinned-coreos.md: update rhcos-stream.json example

data/data/alibabacloud/bootstrap/outputs.tf
Rename the variable name of the output bootstrap node's IP to `bootstrap_ip `
=> Alibaba: fix: rename the bootstrap output variable

data/data/bootstrap/files/etc/systemd/system.conf.d/10-default-env-godebug.conf.template
This removes the deprecated support for certs which lack a SAN.
See https://github.com/openshift/installer/pull/4248
=> bootstrap: remove support for certs lacking SAN

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.10 bootimage metadata in the installer.
This change includes fixes for the following BZs:
Bug 1990506 - Missing udev rules in initramfs for /dev/disk/by-id/scsi-* symlinks
This change will also introduce artifacts for for Aliyun, AWS GovCloud regions, and Nutanix.
```
$ cosa shell
[coreos-assembler]$ plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --no-signatures \
--url https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases aarch64=410.84.202112060851-0 \
ppc64le=410.84.202112041603-0 s390x=410.84.202112040202-0  x86_64=410.84.202112040202-0
```
Verification Steps:
1. Install a new 4.10 cluster
2. `oc debug node/<node name> -- chroot /host rpm-ostree status`
3. Verify that the …
=> Bug 2027501: bump RHCOS 4.10 bootimage metadata

data/data/azure/cluster/master/outputs.tf
Fixing an output produced by the cluster stage of create command
in Azure where the stage provided a list of lists as output for
the IP addresses. This could be made as simple as a list hence
making the change to pick only the first IP address of each
control plane node.
=> azure: Fix terraform cluster IP output

hack/verify-codegen.sh
if the `go codegen` commands failed, the the `hack/verify-codegen.sh` script continued and the CI check passed. see https://github.com/openshift/installer/pull/5406 for an example. the script was not set to fail on a non-zero return code. this pr adds the bash `e` option to the `set` builtin to catch errors and exit on failure.
=> close a verify-codegen ci failure loophole

data/data/install.openshift.io_installconfigs.yaml, data/data/vsphere/variables-vsphere.tf, docs/user/vsphere/customization.md, pkg/terraform/exec/plugins/vsphereprivate/resource_vsphereprivate_import_ova.go, pkg/types/vsphere/platform.go
Resolved the following bug by removing the default values for the disk provisioning type of Vsphere.
https://bugzilla.redhat.com/show_bug.cgi?id=2025093
=> Bug 2025093: Remove The Default Value For The Disk Provisioning Type of Vsphere 

pkg/asset/installconfig/alibabacloud/validation.go
The `ic.ClusterName` is empty in the `validateClusterName`, and the
`ic.ObjectMeta.Name` is correct, not `ic.ClusterName`.
=> Alibaba: fix: replace the ic.ClusterName in the validateClusterName

pkg/destroy/alibabacloud/alibabacloud.go
Filter the resolution records of the base domain through `api.<cluster name>`,
otherwise it will cause all records to be released.
=> Alibaba: fix: destroy the records of the current cluster

data/data/aws/cluster/master/outputs.tf
The tf code for aws outputs only the IP address of the first control plane instance rather than the IPs of all of the control plane instances. The issue is that all of the IPs for all of the instances are collected into a single list and only then the first IP is taken from the list. Instead, we want to take the first IP from each instance and then collect those IPs into a list.
=> Bug 2025464: aws: get ips for all control plane instances for bootstrap gather

pkg/asset/cluster/cluster.go, pkg/destroy/bootstrap/bootstrap.go, pkg/terraform/stages/azure/stages.go, pkg/terraform/stages/platform/stages.go, pkg/types/azure/doc.go
There was a bug where the wrong platform name was being set for Azure Stack Hub bootstrap destroy.
=> Azure Stack Bootstrap Destroy Bug

pkg/asset/machines/ibmcloud/machines.go
Cleanup references to the condensed SecurityGroup names for IBM
Cloud in machine references. They were missed initially.
=> Cleanup machine references to ibmcloud SG

pkg/asset/installconfig/alibabacloud/validation.go
Should add an error when the zone in zones do not exist in `zonesWithStock`
=> Alibaba: fix the validation of instance type

pkg/asset/cluster/azure/azure.go, pkg/destroy/azure/azure.go, pkg/types/azure/metadata.go
The azurestack A record destroy was checking for cluster tag
with the cluster name and not the Infra ID which is the actual
name used for cluster tag population. Changing the name from
clusterName to InfraID to pick the right A records to destroy.
=> azurestack: Fix cluster tag check for A record destroy

docs/user/gcp/install_upi.md, upi/gcp/02_lb_int.py, upi/gcp/04_bootstrap.py
GCP has a size restriction of 63 for the instance group name which
is mostly taken up by the suffix -instance-group that is being added
to make sure the resources have unique name. Reducing the size
of the suffix from -instance-group to -ig would help in restricting
the size of the name and would also help in keeping the names
unique.
=> Bug 1921627: Shorten instance group suffix to ig

pkg/asset/installconfig/aws/availabilityzones.go
We have updated our aws-sdk-go dependency to a version that exposes the
ZoneType field on AvailabilityZone objects, we can use this field to
filter out local zones instead of our temporary fix that used the format
of the zone name.
=> aws: Update our local zone filtering code

images/libvirt/Dockerfile.ci
Proposed fix based on the changes to CRC https://github.com/code-ready/crc/commit/b85050b66be6b0923e73db5d7de1c3fabe1f4633
Currently, google-cloud-sdk is broken and issuing the following error when launching and running jobs.  
err
```gcloud crashed (SystemError): ffi_prep_closure(): bad user_data (it seems that the version of the libffi library seen at runtime is different from the 'ffi.h' file seen at compile-time```
Providing a specific version should allow jobs to no longer fail
=> images/libvirt: provide specific version of google cloud sdk

data/data/alibabacloud/cluster/dns/outputs.tf, data/data/alibabacloud/cluster/dns/privatezone.tf, data/data/alibabacloud/cluster/dns/variables.tf, data/data/alibabacloud/cluster/main.tf, data/data/alibabacloud/cluster/master/main.tf, data/data/alibabacloud/cluster/master/variables.tf, data/data/alibabacloud/cluster/vpc/nat_gateway.tf, data/data/alibabacloud/cluster/vpc/outputs.tf, data/data/alibabacloud/cluster/vpc/sg-master.tf, data/data/alibabacloud/cluster/vpc/sg-worker.tf, data/data/alibabacloud/cluster/vpc/slb.tf, data/data/alibabacloud/cluster/vpc/variables.tf, data/data/alibabacloud/cluster/vpc/vpc.tf, data/data/alibabacloud/variables-alibabacloud.tf, data/data/install.openshift.io_installconfigs.yaml, pkg/asset/cluster/tfvars.go, pkg/asset/installconfig/alibabacloud/client.go, pkg/asset/installconfig/alibabacloud/metadata.go, pkg/asset/installconfig/alibabacloud/validation.go, pkg/asset/installconfig/installconfig.go, pkg/asset/machines/alibabacloud/machines.go, pkg/asset/machines/alibabacloud/machinesets.go, pkg/asset/machines/master.go, pkg/asset/machines/worker.go, pkg/tfvars/alibabacloud/alibabacloud.go, pkg/types/alibabacloud/platform.go, pkg/types/alibabacloud/validation/platform.go, pkg/types/alibabacloud/validation/platform_test.go
This PR is based on #5378
If the user wants the Installer to install the cluster in an existing network, it is now supported.
=> Alibaba: support existing VPC, VSwitchs and PrivateZone

pkg/terraform/stages/platform/stages.go
The resolution from the platform name to the tf stages to use for openstack and ovirt were accidentally removed in a poor rebase.
=> tf/stages: add resolution to stages for openstack and ovirt

OWNERS_ALIASES
This adds @andfasano, @ardaguclu and @sadasu fro baremetal IPI, and removes @dhellman, @kirankt and @stbenjam to properly reflect and support the new metal team organization.
cc @tomassedovic
=> owners: refresh baremetal-approvers/reviewers

data/data/aws/cluster/route53/base.tf, pkg/asset/installconfig/aws/validation.go
Verify no DNS records exist in the public DNS zone. This helps to prevent
installing into an existing cluster. The goal here is to not leak public DNS
records. This should help make the race condition less likely.
https://issues.redhat.com/browse/CORS-1195
=> pkg/asset/installconfig/aws: public DNS validation

data/data/azure/variables-azure.tf, data/data/azurestack/bootstrap/main.tf, pkg/asset/cluster/tfvars.go, pkg/tfvars/azure/azure.go
On Azure Stack, this adds CAs from the additionalTrustBundle to the ignition stub. Azure Stack uses shared-access signatures (SAS) to manage access to the ignition storage account. [Creating a SAS requires an existing storage account](https://pkg.go.dev/github.com/Azure/azure-storage-blob-go/azblob?utm_source=godoc#BlobSASSignatureValues), so we cannot use a similar approach to AWS, which creates a pre-signed URL and passes it through the tfvars.
Instead, this approach manipulates the ignition stub in the Terraform config to append the SAS to the storage account URL.
=> Azure Stack: add CA support in bootstrap ign stub

pkg/asset/cluster/tfvars.go, pkg/destroy/bootstrap/bootstrap.go
Since we are not installing multiple platforms at once, there is no need to include the platform name in the tfvars file containing the platform-specific variables. Removing the platform name from the file makes the code cleaner for Azure Stack.
See https://github.com/openshift/installer/pull/5443#discussion_r766337074.
=> asset/tfvars: use generic name for platform tfvars file

pkg/asset/machines/machineconfig/hyperthreading.go, pkg/asset/machines/master_test.go, pkg/asset/machines/worker_test.go
The MC KernelArguments field is the recommended way to set kernel args,
and should be used in new installs as opposed to writing kernel args to
the `/etc/pivot/kernel-args` file, which should be considered
deprecated.
This should be considered a stop-gap solution until in-Ignition kargs support has landed in the MCO.
/cc @sinnykumari @yuqi-zhang @craychee @cgwalters 
/hold
for testing
=> [MCO-8] machineconfig: Use KernelArguments field instead of kernel-args file

docs/user/azure/install_upi_azurestack.md
To avoid changing the COMPRESSED_VHD_URL with the release version, get COMPRESSED_VHD_URL with "openshift-install coreos print-stream-json"
=> azurestack upi : get VHD_URL with openshift-install coreos print-stream-json

data/data/alibabacloud/bootstrap/versions.tf, data/data/alibabacloud/cluster/dns/versions.tf, data/data/alibabacloud/cluster/master/versions.tf, data/data/alibabacloud/cluster/ram/versions.tf, data/data/alibabacloud/cluster/resourcegroup/versions.tf, data/data/alibabacloud/cluster/versions.tf, data/data/alibabacloud/cluster/vpc/versions.tf
The name of the alibaba tf provider is terraform-provider-alicloud, so the name of the embedded provider should be openshift/local/alicloud. We had been using openshift/local/alibabacloud.
=> tf/alibaba: fix name of alibaba tf provider

pkg/tfvars/aws/aws.go, pkg/types/aws/defaults/platform.go
After switching the bootstrap to use the same instance type as masters, the defaults.InstanceClass is no longer used so this
commit removes it.
/hold
Depends on #5334
=> AWS: Remove unused Instance Class Function

data/data/alibabacloud/cluster/main.tf, data/data/alibabacloud/cluster/vpc/variables.tf, data/data/alibabacloud/variables-alibabacloud.tf, pkg/tfvars/alibabacloud/alibabacloud.go
The `ali_zone_ids` needs to contain the availability zone of the workers,
and create the VSwitches
=> Alibaba: fix: add the availability zone of worker

data/data/azurestack/vnet/versions.tf
Bookkeeping in vnet module for Terraform upgrade. Versions file
was missing random provider and correct terraform version.
=> Azure Stack: fix versions for Terraform Upgrade

pkg/terraform/terraform.go
TRACE-level debugging was hardcoded. Unset this and allow users to configure as needed through environment variables.
=> Terraform: Unset TRACE-level debugging

data/data/install.openshift.io_installconfigs.yaml, pkg/asset/installconfig/azure/client.go, pkg/asset/installconfig/azure/mock/azureclient_generated.go, pkg/asset/installconfig/azure/validation.go, pkg/asset/installconfig/azure/validation_test.go, pkg/asset/installconfig/gcp/mock/gcpclient_generated.go, pkg/asset/rhcos/image.go, pkg/explain/printer_test.go, pkg/types/azure/platform.go, pkg/types/azure/validation/platform.go
Add a new field to the install config so users can specify an RHCOS image
to use in their ASH environment. This field is required for ASH, and not
allowed to be used for azure.
=> azurestack: Add a custom rhcos image field for ASH

data/data/azurestack/bootstrap/versions.tf
Specify local provider to fix this failure:
```
ERROR Could not retrieve the list of available versions for provider
ERROR hashicorp/local: provider registry.terraform.io/hashicorp/local was not found
ERROR in any of the search locations
```
=> Bug 2033749: Azure Stack: Terraform Local Provider

pkg/terraform/terraform.go
The symlinks created for the terraform providers are hard-coded to
use "linux" as the OS for the provider. Instead, it should be using
the OS from the runtime.
=> Bug 2034245: terraform: use the correct os for terraform providers

pkg/destroy/aws/aws.go
The installer has been ignoring the bootstrap profiles during
cluster destroy and needs to be cleaned up along with the
cluster. Added bootstrap-profiles to the list of profiles to
check during destroy.
=> Bug 2028695: Delete bootstrap profiles during cluster destroy

pkg/asset/installconfig/aws/validation.go, pkg/asset/installconfig/aws/validation_test.go
When an invalid region is passed to the installer, the binary
spends 60 minutes trying to find the region and fails. Adding
a check to see if the region provided is present in the list of
supported regions in the AWS SDK.
=> Bug 2019977: Validate region provided in install config

pkg/asset/installconfig/azure/validation.go, pkg/asset/installconfig/azure/validation_test.go
The installer must also check the vCPUsAvailable for the given
instance type to see if the value is greater than the minimum
required to create a cluster. Adding an extra check for this
requirement.
=> Bug 2025788: Check vCPUsAvailable for given instance type

pkg/types/azure/defaults/machines.go
The control plane default instance type was accidentally changed to
a VM with smaller capabilities. This corrects the type.
Similarly, the Azure Stack Hub default compute instance type was
accidentally oversized.
=> Bug 2038384: Azure: Update Default Instance Types

data/data/alibabacloud/cluster/vpc/nat_gateway.tf
Pay-by-specification NAT is no longer supported. Newly purchased pay-as-you-go NAT gateways only support the pay-by-CU metering method.
The wrong information is as follows:
=> Bug 2039689: Alibaba: fix payment method for NAT gateway

data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
The installed CoreOS that is written to disk needs IP options set such that it can contact the MCO over the external network to obtain the Ignition file for the Machine.
These options may be different from the ones needed for pre-provisioning, when IPA has to contact ironic, usually over the provisioning network.
Pass the option to the image-customization-controller, so it can build it into the IPA ignition (in openshift/image-customization-controller#31)
=> Bug 2034527: Pass different IP options to installed CoreOS image and IPA

data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template, pkg/asset/ignition/bootstrap/baremetal/template.go, pkg/asset/ignition/bootstrap/baremetal/template_test.go, pkg/asset/ignition/bootstrap/common.go
Use a podman secret to inject the pull secret into the image-customization container, instead of a plain env var. Related template code also removed.
Requires https://github.com/openshift/image-customization-controller/pull/30
=> Bug 2039241: [baremetal] use podman secret for image-customization server

pkg/destroy/azure/azure.go
This is a follow up PR to https://github.com/openshift/installer/pull/5314 which didn't correctly check whether the resourcegroups were already deleted before attempting deletion.
This PR fixes the bug and has been locally tested by attempting to delete a missing resourcegroup.
=> Bug 2035705: Azure: Only attempt to destroy resourcegroups if present

docs/user/openstack/invalid-https-certificates.md, docs/user/openstack/known-issues.md
Provide a script to validate the OpenStack endpoints, to be run before
installing or upgrading to OpenShift v4.10.
/cc sdodson mandre s-urbaniak maxwelldb
=> Bug 2038166: openstack: Document legacy HTTPS cert validation

pkg/asset/manifests/cloudproviderconfig.go
Remove the CA bundle from the clooud provider config, because the MCO does not expect it. This leads to a discrepency between the bootstrap generated and cluster generated master configs.
Considering there is a discrepency, we could add support in the MCO for the trust bundle in the Azure cloud provider config. But we have decided that the long-term plan should be a unified approach to internal CAs. Until then, operators on Azure Stack should use the CA from the proxy object.
So there is no need for the CA bundle in the Azure configmap so let's just remove it.
=> Bug 2041598: Azure Stack remove CA bundle from CPC

pkg/destroy/alibabacloud/alibabacloud.go
Since there is no automatic paging function, the resource group may not
be queried and not deleted.
Search the resource group created by the installer by the resource group name.
=> Bug 2033271: [Alibaba] fix deletion of resource group

images/openstack/Dockerfile.ci
These rpms would be helpful for some of our CI jobs that we run for
OpenStack; where we'll need to use `envsubst` and `make` commands.
=> Bug 2042438: openstack/Dockerfile: add make and gettext

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template, pkg/asset/ignition/bootstrap/common.go
Setting up `--tear-down-delay` flag to `cluster-bootstrap` to wait `10m` until it tear down, to give time to wait for two kube-apiserver pods is available to finish the bootstrap in AlibabaCloud (only). The default value will be set to `0`.
This is caused due to a premature ending of bootkube of `cluster-bootstrap`/`kube-apiserver`  when scheduled the kube-apiserver to only one master, and the "SLB limitation where cannot be accessed by backend servers"[1]. 
[1] https://www.alibabacloud.com/help/en/doc-detail/55206.htm
This is an investigation of the bug https://bugzilla.redhat.com/show_bug.cgi?id=2035757
=> Bug 2035757: cluster-bootstrap/alibaba: set tear-down-delay to wait kube-apiserver rolls out on AlibabaCloud

data/data/alibabacloud/cluster/vpc/eip.tf
In some regions, 'PayByBandwidth' is not supported, and it is changed to 'PayByTraffic'.
=> Bug 2040160: [Alibaba] fix EIP metering method

data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template, pkg/asset/ignition/bootstrap/baremetal/template.go
If ProvisioningNetwork is Disabled the PROVISIONING_IP_OPTIONS should be
based on the IP version on the external network.
=> Bug 2042315: Fallback to External IP_OPTIONS when ProvisioningNetwork is Disabled

data/data/install.openshift.io_installconfigs.yaml, docs/user/metal/install_ipi.md, pkg/asset/machines/baremetal/hosts.go, pkg/asset/machines/baremetal/hosts_test.go, pkg/asset/machines/master_test.go, pkg/types/baremetal/platform.go, pkg/types/baremetal/validation/platform.go, pkg/types/baremetal/validation/platform_test.go
The current patch allows the user to specify the content of the install-config networkConfig field directly as a yaml object. Content validation (for a generic yaml) is now carried on by the install config asset
/label platform/baremetal
=> Bug 2037813: [baremetal] networkConfig field now accepts yaml instead of string value

data/data/ibmcloud/bootstrap/outputs.tf, data/data/ibmcloud/master/outputs.tf
Add the IP addresses for IBM bootstrap and master nodes to allow
collecting of logs from those nodes.
=> Bug 2043731: Add IP outputs for IBM terraform instances

data/data/alibabacloud/cluster/dns/privatezone.tf
If the user chooses a base domain for which there is no zone, creating the A record in the zone is simply skipped rather than raising an error.
=> Bug 2041926: [Alibaba] fix creating public record being skipped

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template, pkg/asset/ignition/bootstrap/common.go
This reverts commit 6e2d76b61c98ce6b3289a2bbee2c25778a1a1d4a.
With https://github.com/openshift/machine-config-operator/pull/2919, it is no longer necessary to delay the teardown
of the bootstrap control plane. The cluster will no longer get into an unusable state when there is only a single
kube-apiserver pod running.
/hold for https://github.com/openshift/machine-config-operator/pull/2919
=> Bug 2042655: revert delay of bootstrap control plane teardown for alibaba

data/data/alibabacloud/bootstrap/main.tf
Remove hard coding, support users can specify cloud_efficiency in regions that do not support cloud_essd disk category
=> Bug 2041694: [Alibaba] fix system disk category of bootstrap

data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
Avoid the issue that ironic agent image cannot be downloaded due to network proxy.
See #5552 for details.
Signed-off-by: Zhou Hao <zhouhao@fujitsu.com>
=> Bug 2045927: Add proxy for ironic-agent.service

pkg/types/aws/validation/machinepool.go, pkg/types/aws/validation/machinepool_test.go
AMIs for GovCloud regions have been added to the RHCOS stream. Remove
validation requiring users to provide an AMI.
=> Bug 2047258: Read GovCloud from RHCOS stream

data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
Run the httpd container after the coreos-downloader completes to ensure that the kernel parameters can be added correctly.
Fixes: #5504 
Signed-off-by: Zhou Hao <zhouhao@fujitsu.com>
=> Bug 2041765: Adjust the startup order of httpd container

pkg/asset/installconfig/azure/validation.go, pkg/asset/installconfig/azure/validation_test.go
If an instance type that does not support HyperVGeneration version 1
then terraform returns an error mentioning there's support only for
V1. Adding a check during install config to check for the versions
supported by the instance type provided.
=> Bug 2025868: Check HyperVGenerations for instance type

data/data/alibabacloud/bootstrap/main.tf, data/data/alibabacloud/bootstrap/outputs.tf, data/data/alibabacloud/cluster/dns/privatezone.tf, data/data/alibabacloud/cluster/dns/variables.tf, data/data/alibabacloud/cluster/main.tf, data/data/alibabacloud/cluster/master/main.tf, data/data/alibabacloud/cluster/master/variables.tf, data/data/alibabacloud/cluster/vpc/outputs.tf, data/data/alibabacloud/cluster/vpc/slb.tf, data/data/alibabacloud/cluster/vpc/variables.tf, data/data/alibabacloud/cluster/vpc/vpc.tf, data/data/alibabacloud/variables-alibabacloud.tf, pkg/tfvars/alibabacloud/alibabacloud.go, pkg/types/validation/installconfig.go
Support internal publish strategy for platform Alibaba Cloud
=> Bug 2035720: [Alibaba] support internal publish strategy

data/data/alibabacloud/cluster/vpc/eip.tf, data/data/alibabacloud/cluster/vpc/nat_gateway.tf, data/data/alibabacloud/cluster/vpc/outputs.tf, data/data/alibabacloud/cluster/vpc/vpc.tf
When users use an existing network, no longer create Nat gateways and EIPs
=> Bug 2042770: [Alibaba] fix resource creation for existing network

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.10 bootimage metadata in the installer.
This change includes fixes for the following BZs:
Bug 2008521 - gcp-hostname service should correct invalid search entries in resolv.conf
Bug 2043296 - Ignition fails when reusing existing statically-keyed LUKS volume
Bug 2043721 - Installer bootstrap hosts using outdated kubelet containing bugs
Bug 2043316 - RHCOS VM fails to boot on Nutanix AOS
This change will also introduce artifacts for for Aliyun, AWS GovCloud regions, and Nutanix.
```
$ cosa shell
[coreos-assembler]$ plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --no-signatures \
--url https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases aarch64=410.84.202201251203-0 \ …
```
=> Bug 2043297: bump RHCOS 4.10 bootimage metadata

data/data/ibmcloud/variables-ibmcloud.tf, pkg/asset/machines/worker.go
Move off the dedicated storage machine profile, as it has shown to
be less reliable for provisioning on IBM Cloud.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2045916
=> Bug 2045916: IBMCloud: Stop defaulting to dedicated storage profile

pkg/asset/cluster/alibabacloud/alibabacloud.go, pkg/destroy/alibabacloud/alibabacloud.go, pkg/types/alibabacloud/metadata.go
Should not destroy pre-configured alicloud DNS private zone
=> Bug 2046025: [Alibaba] fix destory exist private zone

data/data/ibmcloud/network/image/main.tf
Changing custom image os type to `fedora-coreos-stable-amd64` (a better choice that `centos-8-amd64`).
A correct `rchos` os type will be set once support is added. The support being the ability to set os type to `rhcos` on a custom image. That support should be coming soon (likely in time for 4.11).
Note: the actual image being used IS a RHCOS image. This is an os type labelling issue due to having to import it as a custom image for usage on IBM Cloud VPC.
=> Bug 2047455: Update custom image os type

pkg/destroy/aws/aws.go
As a part of the effort to introduce AWS EFA into openshift, we need to also include placement groups (https://github.com/openshift/enhancements/pull/995). 
As part of this, Machine API will create placement groups for users if they do not exist. During cluster teardown, these currently block the destroy operation as the installer does not know how to handle the placement groups.
This PR teaches the destroy logic how to handle placement groups, with an implementation based on other resources.
I have manually tested this by creating a cluster, adding two placement groups (created by MAPI) and then destroying the cluster. It no longer blocks indefinitely and successfully removes the placement groups and completes the cluster destroy operation.
=> [OCPCLOUD-1385] Ensure removal of placement-groups during cluster destroy on AWS

docs/user/azure/install_upi_azurestack.md
Many Azure Stack environments use internal CAs. In these cases
special steps are needed for a UPI install.
=> Azure Stack: Add UPI Instructions for internal CA

pkg/asset/installconfig/aws/regions.go
When creating the install-config, the installer displays regions
of all partitions of AWS. Certain regions also need extra information
for the validation to work and should not be taken as input since we
only ask for the bare minimum amount of information to create the
install config.
The best approach here would be to only display all the public regions
of AWS and allow for other regions after the install-config is created
to allow for the user to add the extra information.
=> Bug 2048222: Remove non-public AWS regions from list of regions

pkg/asset/installconfig/openstack/validation/cloudinfo.go
This results in an incorrect failure to validate network capabilities
because network extensions weren't loaded.
=> Bug 2050146: Don't shortcut OpenStack scraping if quota is unavailable

go.mod, pkg/asset/installconfig/aws/validation.go
Using proxy dial instead of the current net dial for validating
service endpoints in AWS since there could be a proxy setup
when an IPI restricted installation occurs that might make the
the endpoints unreachable without using them.
=> Bug 2048451: Use proxy dial to validate endpoints

pkg/asset/installconfig/vsphere/validation.go, pkg/asset/installconfig/vsphere/validation_test.go
Do not check for the existince of the vSphere network until the pre-provision checks. For UPI installs, the network may be created as part of provisioning the infrastructure, and so it may not exist when the manifests are created.
=> Bug 2050767: vsphere: check that network exist in provisioning validation

pkg/asset/installconfig/platformpermscheck.go, pkg/asset/manifests/cloudproviderconfig.go, pkg/asset/tls/cloudprovidercabundle.go, pkg/destroy/aws/aws.go, pkg/types/aws/platform.go
When C2S support was added, there was only the one region, us-iso-east-1, in the C2S partition. The us-iso-west-1 region is being added. The installer should be able to support new regions in the partition without requiring code changes going forward, just like it does for the public partition.
Additionally, the installer should be able to support the SC2S partition, as it has all of the same conditional behavior as the C2S partition does.
=> aws: support the entirety of the secret partitions

data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template, data/data/bootstrap/baremetal/systemd/units/ironic.service
It crashes if the provided network configuration is invalid. In this
case inspection currently fails with a generic message.
=> Bug 2046181: baremetal: wait for image-customization to come up

pkg/asset/manifests/cloudproviderconfig.go
resolve BZ 1926975
I have tested this fix in C2S and it resolves the issue. The newline looks strange but is needed to generate properly formatted yaml. It is similar to the newlines here: pkg/asset/manifests/openstack/cloudproviderconfig.go
=> Bug 1926975: Add cloudProviderConfigDataKey to cloud-provider-config map in AWS C2S

cmd/openshift-install/create.go, cmd/openshift-install/gather.go
Adding a conditional that we overlooked in fdb04a76e50d (#4751).  This will avoid distractions [like][1]:
```
level=error msg=Attempted to gather debug logs after installation failure: bootstrap host address and at least one control plane host address must be provided
...
level=error msg=Attempted to analyze the debug logs after installation failure: could not open the gather bundle: open : no such file or directory
```
where the first line usefully explains that we failed to gather the log bundle, while the second line uselessly adds that without a log bundle, there can be no log bundle analysis.
In a separate commit, I'm shifting #4800's:
```go
logrus.Error("Bootstrap failed to complete: ", err.Unwrap())
logrus.Error(err.Error())
```
to move them out from between the gather and …
=> cmd/openshift-install/create: Do not attempt analysis when we fail to gather logs

docs/user/openstack/README.md
Before this patch, the migration would sometimes fail with the following
error:
```
cannot delete Pods not managed by ReplicationController, ReplicaSet,
Job, DaemonSet or StatefulSet (use --force to override)
```
=> Bug 2047257: openstack: Migration script should --force drain

OWNERS_ALIASES
This PR updates the ovirt-reviewers and ovirt-approvers groups to match the current OCP on RHV team structure.
=> Updated owners to current OCP on RHV members

data/data/manifests/bootkube/cvo-overrides.yaml.template
Like d1bf677d62 (#5312) and earlier, now that 4.10 has forked off from the development branch.
=> data/manifests/bootkube/cvo-overrides: Default to stable-4.11

OWNERS_ALIASES
I've been outside the installer for long enough now, that even when I'm pretty confident about a change, I don't think I'd approve anything without someone who's still on the team weighing in.  Dropping myself from the approver set makes that machine-readable ;).
=> OWNERS_ALIASES: Drop wking from approvers

pkg/asset/installconfig/aws/permissions.go
This is a follow up to #5528 so that we ensure that the credentials provided to the installer have permission to delete the placement groups before we attempt to delete them.
This was highlighted as required by @staebler during a review of the enhancement
=> Check for DeletePlacementGroup permission before destroying cluster

data/data/baremetal/bootstrap/main.tf
There is no point in waiting 1 hours for Ironic API to start: even given
the bootstrap VM start-up, it takes much less. Currently, users have to
wait 1 hour to learn that API failed to start for some reason (e.g.
because the network config has an error).
=> Bug 2046181: baremetal: reduce API timeout to 15 minutes

OWNERS_ALIASES, data/data/install.openshift.io_installconfigs.yaml, pkg/explain/printer_test.go, pkg/types/clustermetadata.go, pkg/types/defaults/installconfig.go, pkg/types/installconfig.go, pkg/types/machinepools.go, pkg/types/powervs/OWNERS, pkg/types/powervs/defaults/platform.go, pkg/types/powervs/doc.go, pkg/types/powervs/machinepools.go, pkg/types/powervs/metadata.go, pkg/types/powervs/platform.go, pkg/types/powervs/powervs_regions.go, pkg/types/powervs/validation/machinepool.go, pkg/types/powervs/validation/machinepool_test.go, pkg/types/powervs/validation/platform.go, pkg/types/powervs/validation/platform_test.go, pkg/types/validation/installconfig.go, pkg/types/validation/installconfig_test.go, pkg/types/validation/machinepools.go
For more background on IPI on Power VS, refer to the enhancement
proposal here: openshift/enhancements#736
Older discussions on some of the code here can be found in
https://github.com/openshift/installer/pull/5224.
An older unreviewed version of this PR can be found here:
https://github.com/openshift/installer/pull/5292
=> Add IBM Power VS: types

pkg/types/vsphere/validation/machinepool.go, pkg/types/vsphere/validation/machinepool_test.go
An error occurs if the vcpus specified is not a multiple of the
number of cores specified. A validation check is added to check
if it is indeed a multiple. The check also accounts for default
values of both the vcpus and number of cores (4 by default) in
case only one of the two is set.
=> Bug 2034147: Validate num cores with vcpus

data/data/azure/bootstrap/main.tf, data/data/azure/variables-azure.tf, data/data/azurestack/bootstrap/main.tf, pkg/tfvars/azure/azure.go, pkg/types/azure/defaults/machines.go
The bootstrap VM type is set to the default value for the given
region but must be instead set to the value given for the master
VM type. Making the changes to use the master VM type.
=> Bug 2026356: Fix bootstrap disk instance type

pkg/quota/gcp/gcp.go
Trying to install OCP on GCP without permission to check quotas resulted in
this error:
```
DEBUG   Generating Platform Quota Check...
FATAL failed to fetch Cluster: failed to fetch dependency of "Cluster": failed to generate asset "Platform Quota Check": failed to load Quota for services: projects/assisted-installer/services/compute.googleapis.com, projects/assisted-installer/services/iam.googleapis.com: failed to load quota limits: googleapi: Error 403: Permission denied to get quota on service [compute.googleapis.com]
FATAL Help Token: <REDACTED>
FATAL Details:
FATAL [
FATAL   {
FATAL     "@type": "type.googleapis.com/google.rpc.PreconditionFailure",
FATAL     "violations": [
FATAL       {
FATAL         "subject": "110002",
FATAL         "type": "googleapis.com"
FATAL       }
FATAL …
```
=> GCP may also return Forbidden status when trying to check quotas

data/data/coreos/fcos.json
This updates latest FCOS used for OKD to FCOS [35.20220213.3.0](https://github.com/coreos/fedora-coreos-streams/commit/029876068963da7579c10fa5afbdcabca81bd01b)
=> Bug 2060970: data/data/coreos/fcos.json: update initial FCOS to 35.20220213.3.0

data/data/azurestack/bootstrap/main.tf, data/data/azurestack/cluster/main.tf, data/data/azurestack/cluster/master/master.tf, data/data/azurestack/cluster/master/variables.tf
Azure Stack supports disks types other than Standard_LRS. The installer should not overriding the disk type choice made by the user and silently restricting the disk type for the control plane to Standard_LRS.
=> Bug 2061544: azurestack: stop pinning to Standard_LRS for disk type

pkg/asset/manifests/infrastructure.go
The ProviderType was missing from the PlatformStatus block for the
infrastructure asset on IBM Cloud. Added the missing value for
any configuration usage by other components/operators.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=2061527
=> Bug 2061527: IBMCloud: Missing infra providertype

pkg/asset/installconfig/azure/validation.go, pkg/asset/installconfig/azure/validation_test.go
As of release 4.9, the `Cluster` target now inherits the `PlatformProvisionCheck` dependency by way of [this commit for baremetal](https://github.com/openshift/installer/commit/e6ea0c6364837204428a08abfc9a2cdae2076960).
In the context of [Azure Red Hat OpenShift (ARO)](https://azure.microsoft.com/en-us/services/openshift/), all provisioning checks are passing except for one, which we need to disable.  Since the [ARO Resource Provider](https://github.com/Azure/ARO-RP) provisions Azure resources _before_ resolving the installer asset graph, it's normal for the Azure resource group to be populated.
cc: @m1kola
=> azure/validation: Skip "resource group empty" check for ARO

data/data/azurestack/bootstrap/main.tf, data/data/azurestack/bootstrap/variables.tf, data/data/azurestack/cluster/master/master.tf
When using internal publishing, the backend address pools of the load balancers incorrectly used a null list for the external load balancer's ID. Terraform requires that the list supplied to the concat function be an empty list rather than a null list.
Also, the elb_backend_pool_v4_id variable used as input to the bootstrap stage did not have a default. For internal publishing, the elb_backend_pool_v4_id output from the vnet stage is null, which is omitted from the outputs rather than explicitly set to null. Consequently, terraform would complain that the required elb_backend_pool_v4_id value was not set.
=> Bug 2060508: azurestack: fix backend address pools for internal publishing

pkg/types/powervs/powervs_regions.go
This function will be used to create a CloudProvider config for
Power VS among other potential uses.
=> Add VPCRegionForPowerVSRegion function

pkg/types/baremetal/validation/platform.go, pkg/types/baremetal/validation/platform_test.go
This PR adds returning error if bmc driver requires provisioning network
and does not disabled support provisioning network cases.
=> Validate BMC driver supported and requires provisioning network

pkg/asset/manifests/cloudproviderconfig.go, pkg/asset/manifests/dns.go, pkg/asset/manifests/infrastructure.go, pkg/asset/manifests/powervs/cloudproviderconfig.go
For more background on IPI on Power VS, refer to the enhancement
proposal here: openshift/enhancements#736
Older discussions on some of the code here can be found in
https://github.com/openshift/installer/pull/5224
=> Add IBM Power VS: manifest assets

pkg/destroy/ibmcloud/dns.go
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2060617
Update regex for IBM Cloud DNS destroy to explicitly match the cluster subdomain.
=> Bug 2060617: fix(ibmcloud): Properly match regex for DNS destroy

hack/verify-vendor.sh
Update the go version used for verifying vendoring from 1.16 to 1.17. The CI job uses its own image and does not use the image specified in the script. Therefore, the go version in the script must match the go version in the CI job, particularly when there are breaking changes between go versions (as there are between 1.16 and 1.17 when it comes to modules).
=> hack: update go version used in hack/verify-vendor.sh

data/data/install.openshift.io_installconfigs.yaml, pkg/explain/printer_test.go, pkg/types/clustermetadata.go, pkg/types/defaults/installconfig.go, pkg/types/installconfig.go, pkg/types/machinepools.go, pkg/types/nutanix/OWNERS, pkg/types/nutanix/defaults/platform.go, pkg/types/nutanix/defaults/platform_test.go, pkg/types/nutanix/doc.go, pkg/types/nutanix/machinepool.go, pkg/types/nutanix/metadata.go, pkg/types/nutanix/platform.go, pkg/types/nutanix/validation/machinepool.go, pkg/types/nutanix/validation/machinepool_test.go, pkg/types/nutanix/validation/platform.go, pkg/types/nutanix/validation/platform_test.go, pkg/types/validation/installconfig.go, pkg/types/validation/installconfig_test.go
Add types, defaults, and validations to support Nutanix platform on the Openshift installer.
=> Add Nutanix-specific platform types

data/data/install.openshift.io_installconfigs.yaml, pkg/explain/printer_test.go, pkg/types/installconfig.go, pkg/types/validation/installconfig.go
This PR is just https://github.com/openshift/installer/pull/5496 with merge conflicts resolved.
=> stop considering Mint mode as supported on Azure

cmd/openshift-install/gather.go
When debugging a failed installation, its important to understand the constraints in which the installer failed to connect to the bootstrap node. Currently when `connection timed out` occurs, its accompanied by a logging message that indicates the ssh client failed. 
```
time="2022-03-04T00:05:49Z" level=fatal msg="failed to create SSH client: dial tcp 172.16.19.161:22: connect: connection timed out"
```
In this situation the SSH client was successful and some kind of networking condition or service ACL is causing the connection timed out, thus it should follow https://github.com/openshift/installer/blob/master/cmd/openshift-install/gather.go#L149.  This small peice of information assists SREs in hypothesising the conditions in which the installation and/or boostrap logs collection has …
=> include conn timed out err for bootstrap collection

OWNERS_ALIASES
Refresh the baremetal owners list to reflect latest organizational changes
=> baremetal: refresh owners list

data/data/azurestack/cluster/dns/dns.tf
When using internal publishing on Azure Stack Hub, the DNS record for the api should be created and point to the internal load balancer.
=> Bug 2061549: azurestack: create the api DNS record when publishing internally

pkg/asset/installconfig/basedomain.go, pkg/asset/installconfig/powervs/dns.go
The powervs code uses a new version of the power-go-client which requires
not reusing the Authenticator structure as input.  We are using our own
code instead of ibmcloud's code since ibmcloud may diverge in the future.
Also, their timetables on fixes and testing are different than ours.
=> Use powervs NewClient in GetDNSZone

data/data/alibabacloud/bootstrap/main.tf, data/data/alibabacloud/bootstrap/outputs.tf, data/data/alibabacloud/cluster/master/main.tf, data/data/alibabacloud/cluster/outputs.tf, data/data/alibabacloud/slb_attach_controlplane/main.tf, data/data/alibabacloud/slb_attach_controlplane/variables.tf, data/data/alibabacloud/variables-alibabacloud.tf, pkg/terraform/stages/alibabacloud/stages.go
AlibabaCloud provider has an issue with the recent terraform provider updates. When the bootstrap is torn down the SLB server backends are removed. This seems to be an issue in the terraform provider.
This code removes the teardown of the SLB for the bootstrap. This adds an additional stage to add all of the control plane nodes including the bootstrap. When the bootstrap is torn down the instance is removed automatically from the SLB (service load balancer).
=> AlibabaCloud: fix for bootstrap teardown removing slb backends

terraform/Makefile
The amount of time that it takes to compress the terraform binaries is burdensome on development and is causing the brew builds to fail due to timeouts. Changing the compression speed from 9 to 1 increases the resultant size of the installer binary by roughly 10% but reduces the time spent compressing to roughly 20% of the original time.
On my local machine, building and compressing the aws provider is reduced from about 22 seconds to about 4 seconds. The size of the aws provider zip is increased from 99M to 108M. The size of the installer binary is increased from 413M to 450M.
=> terraform: compress provider binaries faster

data/data/aws/bootstrap/main.tf, data/data/aws/cluster/main.tf, data/data/aws/variables-aws.tf, pkg/asset/installconfig/aws/platform.go, pkg/asset/installconfig/aws/regions.go, pkg/asset/rhcos/image.go, pkg/tfvars/aws/aws.go
When determining whether an AMI is available in a region, we should use the coreos stream directly. The installer function for determining known regions has been changed to only list public regions.
=> Bug 2062998: Update region check for coreos AMIs

pkg/asset/cluster/tfvars.go, pkg/asset/installconfig/ibmcloud/client.go, pkg/asset/installconfig/ibmcloud/metadata.go, pkg/asset/manifests/openshift.go, pkg/destroy/ibmcloud/ibmcloud.go
After IBM go-sdk's were updated, re-using a single IAMAuthenticator
for multiple services is no longer valid. For each service use we
should have a unique IAMAuthenticator created.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=2066463
=> Bug 2066463: IBMCloud: Patch IBM client auth

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.11 bootimage metadata in the installer.
This change includes fixes for the following BZs:
Bug 2032717: Unable to download ignition after coreos-installer install --copy-network
This change will also introduce artifacts for for Aliyun, AWS GovCloud regions,
and Nutanix.
```
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos  x86_64=411.85.202203181601-0 s390x=411.85.202203181515-0 ppc64le=411.85.202203181612-0 --url https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases --no-signatures
```
=> Bug 2047935: bump RHCOS 4.11 bootimage metadata

data/data/manifests/openshift/cloud-creds-secret.yaml.template, data/data/manifests/openshift/role-cloud-creds-secret-reader.yaml.template, pkg/asset/manifests/cloudproviderconfig.go, pkg/asset/manifests/dns.go, pkg/asset/manifests/infrastructure.go, pkg/asset/manifests/openshift.go, pkg/asset/manifests/template.go
- Update templates in data/data/manifests
- Add nutanix platform customizations in pkg/asset/manifests
=> Add Nutanix-specific customizations to manifests

pkg/types/ibmcloud/validation/platform.go
Add the br-sao region to the list of supported regions for IBM
Cloud. We will keep this static list for now and look into generating
the supported regions dynamically in a future patch.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=2061891
=> Bug 2061891: IBMCloud: Add br-sao region to static list

data/data/manifests/bootkube/cvo-overrides.yaml.template
OpenShift 4.6 EUS is unique in that it doesn't pick up the lifecycle changes
which made EUS available to all subscribers, nor do we continue adding all
4.6.z to stable-4.6 channel. Therefore, so that new installs don't get abandoned
we'll set the default channel to eus-4.6.
=> Bug 2070666: Update the default channel for new 4.6 installs to eus-4.6

OWNERS_ALIASES
Updating OWNERS_ALIASES to get team up to date.
By being listed here, this means you will be in the review request rotation.
/cc @AnnaZivkovic  @barbacbd  @r4f4 @sadasu 
@staebler you weren't listed in reviewers. I think you get plenty of review requests already based on how the algorithm factors previous contributions. Adding you here, may be a bit of a novelty. Any issues I don't foresee?
=> OWNERS_ALIASES: Update current installer team

pkg/asset/installconfig/azure/validation.go, pkg/asset/installconfig/azure/validation_test.go
Confirm an instance type is compatible with UltraSSD enabled or fail
early, before provisioning infrastructure, if type is incompatible.
=> Azure: validate UltraSSD instance types

data/data/bootstrap/files/usr/local/bin/bootstrap-cluster-gather.sh
While debugging https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.11-e2e-vsphere/1511046135223947264, we lacked the summarization of the machines present.  Somehow a list of master IPs was retrieved, so machines exist at some level, try gathering them.
=> collect machine state in bootstrap gather

data/data/bootstrap/files/usr/local/bin/installer-gather.sh, data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh
This adds sssd to the list of services we collect logs from. Currently,
vsphere and metal are failing to bootstrap and there's some evidence
collected from manual runs that we're hitting an issue in sssd[1].
Note, this also alphabetizes the list of services we collect logs from.
[1] https://github.com/SSSD/sssd/issues/5753
=> gather: collect sssd journal logs

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template, data/data/nutanix/OWNERS, data/data/nutanix/bootstrap/main.tf, data/data/nutanix/bootstrap/outputs.tf, data/data/nutanix/bootstrap/variables.tf, data/data/nutanix/cluster/main.tf, data/data/nutanix/cluster/outputs.tf, data/data/nutanix/variables-nutanix.tf, pkg/terraform/stages/nutanix/OWNERS, pkg/terraform/stages/nutanix/stages.go, pkg/terraform/stages/platform/stages.go
- Update bootkube template to copy static resources for nutanix under data/data/bootstrap/files
- Add terraform files for Nutanix platform under data/data/nutanix
- Add terraform stages for Nutanix platform under pkg/terraform/stages/nutanix
=> Update declarative assets for Nutanix

data/data/ibmcloud/network/vpc/security-groups.tf
OVN-IPsec requires UDP ports 500 and 4500 for IKE
Because of the limitation of 5 remote rules per SG we have to
create a new SG
=> Bug 2038774: [IBM] add IPsec IKE UDP ports 500, 4500 to security group

data/data/install.openshift.io_installconfigs.yaml, pkg/asset/installconfig/nutanix/nutanix.go, pkg/types/nutanix/platform.go, pkg/types/nutanix/validation/platform.go, pkg/types/nutanix/validation/platform_test.go, pkg/types/validation/installconfig_test.go
Remove defaultStorageContainer from the platform, installconfig, and survey.
This was added earlier with the intention to provide a default storage class
for the cluster. However, with the Nutanix CSI driver provisioning being a day-2
operation for Nutanix, a defaultStorageContainer is no longer required.
=> Remove defaultStorageContainer from nutanix platform installconfig

pkg/asset/targets/targets.go
This is an implementation of the second other part of the single node + workers
enhancement:
https://github.com/openshift/enhancements/blob/master/enhancements/single-node/single-node-openshift-with-workers.md
The first part is implemented in this PR: https://github.com/openshift/installer/pull/5746
________________________________
Today, performing bootstrap-in-place installation of a "none"-platform
single control-plane node cluster using the OpenShift Installer does not
provide the user with a worker node ignition file. As a result, the user
is not able to manually add worker nodes to the resulting cluster. This
was historically done intentionally to prevent users from adding worker
nodes to a single-node cluster, which would be an unsupported operation.
All current official OCP …
=> Bootstrap-in-place ignition creation should also create a `worker.ign` file

cmd/openshift-install/create.go, cmd/openshift-install/waitfor.go, pkg/asset/asset.go, pkg/asset/cluster/cluster.go, pkg/asset/installconfig/installconfig.go
Attempt to add some additional exit codes to differentiate errors from infrastructure, boothstrap and cluster phases. 
- Exit code for infrastructure phase only applies to "create cluster" command. 
- Exit code for bootstrap catches the result from bootstrap watch phase. 
- Exit code for install catches the final result from cluster installation. Right now the code keeps checking until context is done, or clusterversion is Available. It does not exit because any other reasons. So exitCodeIntallFailed pretty much means the cluster installation did not complete within the specified timeframe.
=> Add exit code for infra, bootstrip and install failures

pkg/asset/manifests/operators.go, pkg/asset/manifests/utils.go
The ConfigMap is install-time archival, and may no longer express the current cluster state.  Having it in-cluster was intended to be a temporary hack until we got Infrastructure and such, and we just failed to remove the ConfigMap quickly enough, and now removing it would be a breaking change.  But with this commit, we get a warning about this into the cluster, so folks looking at the resource are more likely to understand its limitations.
The kubernetes.io/description annotation has been documented since kubernetes/website#31621.
=> pkg/asset/manifests/operators: Set kubernetes.io/description for cluster-config-v1

pkg/types/powervs/validation/machinepool.go, pkg/types/powervs/validation/machinepool_test.go
Follow up PR from the below discussion:
https://github.com/openshift/installer/pull/5609#discussion_r812213205
Added testcases to validate unique and duplicate volumeIDs
=> Add VolumeID testscases for Power VS machinepool

data/data/vsphere/bootstrap/variables.tf, data/data/vsphere/master/variables.tf
This change add missing variables to each vsphere terraform stage in order
to remove the terraform warnings regarding undeclared variables. These
warnings were the result of output variables from some stages not being
declared in the later stages.
=> Bug 2033482: vsphere: ensure terraform variables are defined

images/installer/Dockerfile.upi.ci
Updating terraform version and the matchbox provider version to
latest to help the baremetal UPI CI PR.
=> images: Update terraform version in UPI image

pkg/asset/quota/quota.go
This permission is optional and only used by the installer to do
pr-flight quota checks. Logging it missing as a warning tends to
distract SREs and customers from other more serious problems in the log.
=> Lower severity of ListAWSDefaultServiceQuotas warning msg

docs/user/azure/customization.md
tested on 4.10.9 
platform.azure.osDisk will caused the following error
FATAL failed to fetch Metadata: failed to load asset "Install Config": failed to unmarshal install-config.yaml: failed to parse first occurence of unknown field: error unmarshaling JSON: while decoding JSON: json: unknown field "osDisk"
=> remove platform.azure.osDisk

docs/dev/terraform.md, terraform/providers/alicloud/go.mod, terraform/providers/aws/go.mod, terraform/providers/azureprivatedns/go.mod, terraform/providers/azurerm/go.mod, terraform/providers/azurestack/go.mod, terraform/providers/google/go.mod, terraform/providers/ibm/go.mod, terraform/providers/ignition/go.mod, terraform/providers/ironic/go.mod, terraform/providers/libvirt/go.mod, terraform/providers/local/go.mod, terraform/providers/openstack/go.mod, terraform/providers/ovirt/go.mod, terraform/providers/random/go.mod, terraform/providers/vsphere/go.mod, terraform/providers/vsphereprivate/go.mod
The module names used for the terraform providers should have the module as a sub-module of the installer's main module.
```sh
find ./terraform/providers/ -name go.mod -exec sed -E -i 's|^module github.com/openshift/installer/terraform/([^/]+)$|module github.com/openshift/installer/terraform/providers/\1|' {} \;
find ./terraform/providers/ -name go.mod -exec sed -E -i 's|^module ([^/]+)$|module github.com/openshift/installer/terraform/providers/\1|' {} \;
```
https://issues.redhat.com/browse/CORS-1978
=> terraform: fix module name of terraform providers

pkg/destroy/aws/aws.go
Log when iterating over paginated resources.
Most of our destroy logic is linked to tags, so we can iterate over resources tagged as owned by the cluster.  But IAM resources are not returned by the tag APIs.  And `deleteElasticLoadBalancerClassicByVPC` and `deleteElasticLoadBalancerV2ByVPC` are expressly intended for deleting untagged load balancers.  This commit adds once-per-page logging for each of these functions, so folks looking at installer logs will see "oh, my, that's a lot of page log lines, I wonder if I have an IAM role leak?" without having to look [at][1]:
```
time="2022-03-22T16:02:52Z" level=debug msg="search for IAM roles"
time="2022-03-22T16:12:51Z" level=debug msg="search for IAM users"
```
and think "10 minutes searching for IAM roles, I wonder if I have an IAM role …
=> pkg/destroy/aws: Log unfiltered pagination

data/data/azure/variables-azure.tf, data/data/azure/vnet/main.tf, data/data/azure/vnet/outputs.tf, pkg/asset/cluster/tfvars.go, pkg/asset/installconfig/azure/client.go, pkg/asset/installconfig/azure/mock/azureclient_generated.go, pkg/asset/installconfig/azure/validation.go, pkg/asset/installconfig/azure/validation_test.go, pkg/asset/machines/azure/machines.go, pkg/asset/machines/azure/machinesets.go, pkg/asset/machines/master.go, pkg/asset/machines/worker.go, pkg/tfvars/azure/azure.go
Currently, azure disks do not support HyperVGeneration version 2
so adding a field in the install config and set it to either V1
or the preferred V2 if the instance type supports it.
This includes adding another OS image for version 2 and picking
the right image depending on the HyperVGeneration version set and
passing the version to terraform to output the right image name
used.
=> azure: Enable HyperVGeneration setting for Azure disks

cmd/openshift-install/create.go, pkg/asset/cluster/cluster.go, pkg/destroy/bootstrap/bootstrap.go, pkg/terraform/init.go, pkg/terraform/stage.go, pkg/terraform/stages/alibabacloud/stages.go, pkg/terraform/stages/gcp/stages.go, pkg/terraform/stages/split.go, pkg/terraform/state.go, pkg/terraform/terraform.go
Currently, the installer unpacks the terraform and terraform providers binaries to the same temporary directory under /tmp that is used for the plan files for a stage. Some users, however, are not able to execute files under /tmp.
A workaround for this would be for the user to set the TMPDIR environment variable to a directory where they do have the ability to execute files. That is not a great experience for a user when there is already a command-line argument that the user can use to specify the install directory.
So, let's use the install directory as the location under which to unpack the terraform binaries instead. At the same time, let's unpack once for all of the stages rather than unpacking once per stage.
One downside of this approach is that either (1) it makes the Cluster asset …
=> cluster: unpack terraform binaries into install directory

data/data/powervs/cluster/bootstrap/main.tf, data/data/powervs/cluster/bootstrap/outputs.tf, data/data/powervs/cluster/bootstrap/templates/bootstrap.ign, data/data/powervs/cluster/bootstrap/variables.tf, data/data/powervs/cluster/bootstrap/versions.tf, data/data/powervs/cluster/dns/dns.tf, data/data/powervs/cluster/dns/variables.tf, data/data/powervs/cluster/dns/versions.tf, data/data/powervs/cluster/loadbalancer/alb.tf, data/data/powervs/cluster/loadbalancer/outputs.tf, data/data/powervs/cluster/loadbalancer/sg.tf, data/data/powervs/cluster/loadbalancer/variables.tf, data/data/powervs/cluster/loadbalancer/versions.tf, data/data/powervs/cluster/main.tf, data/data/powervs/cluster/master/main.tf, data/data/powervs/cluster/master/outputs.tf, data/data/powervs/cluster/master/variables.tf, data/data/powervs/cluster/master/versions.tf, data/data/powervs/cluster/outputs.tf, data/data/powervs/cluster/versions.tf, data/data/powervs/iaas/power-iaas.tf, data/data/powervs/iaas/variables.tf, data/data/powervs/post-install/main.tf, data/data/powervs/post-install/versions.tf, data/data/powervs/variables-powervs.tf
For more background on IPI on Power VS, refer to the enhancement
proposal here: openshift/enhancements#736
Older discussions on some of the code here can be found in #5224
=> Add IBM Power VS: tf data

images/baremetal/Dockerfile.ci
Also use a shared ARG to keep it consistent between stages
This should fix the downstream build pipeline
=> Repin libvirt-version

cmd/openshift-install/create.go, pkg/asset/cluster/cluster.go, pkg/destroy/bootstrap/bootstrap.go, pkg/terraform/init.go, pkg/terraform/stage.go, pkg/terraform/stages/alibabacloud/stages.go, pkg/terraform/stages/gcp/stages.go, pkg/terraform/stages/split.go, pkg/terraform/state.go, pkg/terraform/terraform.go
Reverting cluster: unpack terraform binaries into install directory #5715 
I think this may have broken baremetal-ipi like:
"bootstrap" stage: failed to create cluster: failed doing terraform init: fork/exec ocp/ostest/terraform/bin/terraform: no such file or directory
This reverts commit fc75b79aaafb2addb689ae332ae731d6b8c08e82.
=> Revert "cluster: unpack terraform binaries into install directory"

pkg/asset/manifests/dns.go
Zones are checked and used by `ingress` operator, at: https://github.com/openshift/cluster-ingress-operator/blob/3fdb8608f385a94a2c75e129edbac1dcd8760c32/pkg/operator/controller/dns/controller.go#L463
This proposed change adds just that for PowerVS, as can be seen in `oc describe dns/cluster` below;
=> Adding public&private zones to DNS config on PowerVS

pkg/asset/cluster/tfvars.go, pkg/asset/installconfig/vsphere/client.go, pkg/asset/installconfig/vsphere/validation.go, pkg/asset/installconfig/vsphere/vsphere.go, pkg/destroy/vsphere/vsphere.go, pkg/terraform/stages/vsphere/stages.go
This PR adds logouts for each location a vSphere client is created (excluding inside `terraform-provider-vsphere`). 
A new `Cleanup` method was added to `Destroyer` interface (this method name is open to suggestions) with the first implementation being for vSphere where logouts occur. 
Terraform provider for vSphere is not addressed in this PR due to https://github.com/hashicorp/terraform-provider-vsphere/issues/618
Relates to [SPLAT-471](https://issues.redhat.com//browse/SPLAT-471)
=> vSphere session cleanup

docs/user/customization.md
Add in-repo documentation for user-selectable capabilities
=> Add in-repo documentation for user-selectable capabilities

pkg/asset/manifests/cloudproviderconfig.go, pkg/asset/manifests/powervs/cloudproviderconfig.go
adding new fields to align with changes in cloud-provider-powervs
=> Add Power VS-specific fields to cloud-provider config

pkg/asset/ignition/machine/node.go
This is to make sure the user does not have to manually set A records
for api-int.
=> Ensure ignition host is set to API VIP for Nutanix platform

data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh
Fixes #5706. 
This should now fetch the machine-config-daemon-firstboot logs from the control plane nodes if OpenShift 4 installation fails.
=> Changing the machine-config service name

data/data/coreos/fcos.json
This updates latest FCOS used for OKD to FCOS 35.20220213.3.0, latest stable
=> Bug 2075873: data/data/coreos/fcos.json: update initial FCOS to 35.20220327.3.0

images/libvirt/google-cloud-sdk.repo
The following error has been observed on the CI jobs using the
`libvirt-installer` image:
`ERROR: gcloud crashed (SystemError): ffi_prep_closure(): bad user_data (it seems that the version of the libffi library seen at runtime is different from the 'ffi.h' file seen at compile-time)`
See an example failed job - https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_installer/5452/pull-ci-openshift-installer-master-e2e-crc/1468627926126694400
This seems to coincide with version 366.0 of the Google Cloud SDK
which was released on Dec 7.
https://cloud.google.com/sdk/docs/release-notes#36600_2021-12-07
This changes the use of the el7 version of the SDK repo to use the el8
version.
I'm kind of surprised that things have been working as long as they
have because the …
=> libvirt: use el8 repo for Google Cloud SDK

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
[Avoid][1]:
```
Error: error creating container storage: the container name "mco-render" is already in use by "877829c1add4c25f797255405478c4b8f75da308bc5cb3037e171487eec0ff37". You have to remove that container to be able to reuse that name.: that name is already in use
```
and similar for other containers by removing inconsistent `--rm` options and baking that in at the `bootkube_podman_run` level.
Also add an `etcd-bootstrap` `rm` call, to clear out any cruft from a previous bootkube round before calling Podman for a fresh etcd render.
Spun out of #5800 as a hopefully straightforward, small robustness improvement.
[1]: https://github.com/openshift/installer/pull/5800#issuecomment-1097141511
=> data/bootstrap/files/usr/local/bin/bootkube: --rm all Podman containers

pkg/asset/tls/mcscertkey.go
Without the API VIP populated in the SAN for the MCS Cert, the
nodes created by the installer will fail to ignite due to a x509
verification error.
=> Ensure Nutanix API VIP is populated in the SAN for the MCS Cert

data/data/bootstrap/vsphere/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender.template, data/data/vsphere/bootstrap/main.tf
for vsphere ipi add cluster domain to the uploaded vm configs so that 30-local-dns-prepender can use it
Due to changes in FCOS 35 /etc/nsswitch.conf, we need to move the name resolution of api-int.<domain> to
systemd-resolved.  The way we do this is by adding a Domain attribute to /etc/systemd/resolved.conf.d/60-kni.conf.
Since we are using a slightly different prepender than the masters and workers the domain is not being
discovered automatically.  To address this we are adding the domain in data/data/vsphere/bootstrap/main.tf
which gets uploaded to the bootstrap instance on creation.
30-local-dns-prepender then downloads this information and adds it to /etc/systemd/resolved.conf.d/60-kni.conf
Note that we check for a non-empty domain before writing …
=> Bug 2076880: for vsphere ipi add cluster domain to the uploaded vm configs so that 30-local-dns-prepender can use it

pkg/asset/installconfig/aws/validation.go
The zoneName and zonePath were always empty variables. The variables were initialized
outside of the if/else and then reinitialized using := in the if/else causing their
values to go out of scope before the function call to validateZoneRecords.
Fixes: 43224
=> Bug 2074659:Fix empty string usage in ValidateForProvisioning

images/installer/Dockerfile.upi.ci, images/installer/Dockerfile.upi.ci.rhel8
The terraform-provider-matchbox binary was not being correctly extracted into the /bin directory. This PR ensures that the binary is moved to /bin correctly.
This PR also ensures the changes made in this PR and #5762 are reconciled between the two UPI images.
Fixes issues see here: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/27383/rehearse-27383-pull-ci-openshift-installer-master-e2e-metal-upi/1516093307896205312/build-log.txt
=> Ensure that the /bin/terraform-provider-matchbox binary is present

data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template, pkg/asset/ignition/bootstrap/baremetal/template.go, pkg/types/baremetal/defaults/platform.go, pkg/types/baremetal/defaults/platform_test.go
Hey @hardys 
I dug into why arm/x86 were creating nic names:
By default libvirt the bootstrap x86 vm that gets created uses pci:  
```        
<controller type='pci' index='0' model='pci-root'>
<interface type='bridge'>
<address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
</interface>
<interface type='bridge'>
<address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x0'/>
</interface>
```
By default libvirt the bootstrap arm64 vm that gets created uses pcie:
```     
<controller type='pci' index='0' model='pcie-root'>
<interface type='bridge'>
<address type='pci' domain='0x0000' bus='0x01' slot='0x00' function='0x0'/>
</interface>
<interface type='bridge'>
<address type='pci' domain='0x0000' bus='0x02' slot='0x00' function='0x0'/>
</interface>
```
This …
=> Determine Nic name in Bootstrap VM for ARM and x86

data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
During the bootstrap, proxy related variables should be already injected in the service by https://github.com/openshift/installer/blob/master/data/data/bootstrap/files/etc/systemd/system.conf.d/10-default-env.conf.template.
In addition, proxy environment variable should be already passed to the container by podman
=> baremetal: remove redundant proxy setting

pkg/asset/installconfig/vsphere/vsphere.go
Removes leftover namer interface. The implementation using the interface was removed in e7dfefa7d51d5d4fbee1a37412ef6f8ab7c16d38 but the interface was left behind. We have no need for the interface so clean it
up.
=> vsphere: remove unused namer interface

data/data/bootstrap/vsphere/files/etc/NetworkManager/conf.d/99-vsphere.conf, data/data/bootstrap/vsphere/files/etc/NetworkManager/conf.d/99-vsphere.conf.template
Using rc-manager=unmanaged
for vsphere upi breaks the bootstrap
process since the RHCOS instance has
no `/etc/resolv.conf`
=> vsphere upi: missing etc resolv

pkg/types/ovirt/validation/machinepool.go
This change fixes a bug where the 'format' parameter on the oVirt platform would be validated incorrectly and only accept empty, raw, or format. Instead, it should accept empty, raw, or cow.
=> Bug 2078895: ovirt: fixing incorrect 'format' value validation

data/data/vsphere/bootstrap/main.tf
The vsphere terraform provider has a long standing
bug if a disk parameter is changed underneath
terraform by vSphere the apply will fail.
This resolves reported issue:
https://github.com/openshift/installer/issues/5830
=> vSphere: ignore bootstrap eagerly scrub changes

OWNERS_ALIASES, cmd/openshift-install/agent.go, cmd/openshift-install/agent/OWNERS, cmd/openshift-install/agent/create.go, cmd/openshift-install/agent/waitfor.go, cmd/openshift-install/main.go, data/data/agent/OWNERS, pkg/agent/OWNERS, pkg/agent/build_image.go, pkg/agent/create_manifests.go, pkg/agent/wait_for.go, pkg/asset/agent/OWNERS
This patch adds the initial project setup for the agent installer, as described in the OpenShift enhancement https://github.com/openshift/enhancements/pull/1067, to be managed by the agent team.
Initially, the developments will be kept in a separate branch, currently named `master-agent-installer`.
=> agent: create skeleton commands and folders structure for agent-based installer

pkg/asset/installconfig/aws/validation.go
This fixes a bug in the AWS Platform Provisioning Check where it
identifies a record that merely matches the DNS suffix domain without
checking for a "." in the record.
For example, if cluster name is "abcd" with baseDomain "example.com"
then a record "foo-abcd.example.com" is misidentified as part of the
domain of the cluster ("abcd.example.com").
=> Bug 2077662: Fix AWS Platform Provisioning Check

data/data/ibmcloud/network/image/main.tf
A custom image is used for VSI provisioning. We were unable to to set the operating system name correctly until additional support was added to VPC IaaS.
That support has been added and is available in all supported regions.
This PR will set the os name value to: `red-coreos-stable-amd64` (previously set to: `fedora-coreos-stable-amd64"`).
=> [ibmcloud] Update os name to correct value 

pkg/asset/machines/master.go, pkg/asset/machines/worker.go
Adjust the default machine pool configuration for Nutanix machines
- Reduce the number of cores per socket:
- Control plane nodes: From 4 cores per socket to 1
- Worker nodes: From 2 cores per socket to 1
- Increase the number of CPUs:
- Control plane nodes: From 4 CPUs to 8
- Worker nodes: From 2 CPUs to 4
- Increased the RAM to 16GB.
Note: The AHV scheduler treats socket and core allocation exactly the same.
=> Change the default machine pool config for Nutanix

data/data/nutanix/cluster/main.tf, data/data/nutanix/variables-nutanix.tf, pkg/asset/cluster/tfvars.go, pkg/tfvars/nutanix/nutanix.go
Instead of uploading the rhcos image from the installer machine
to Prism Central, ask Prism Central to download the image through
a URL. This is a lot less error prone.
=> Pull the OS Image for Nutanix via URL

images/installer-artifacts/Dockerfile.rhel
For OKD builds TAGS are not propagated to all three builds.  Adding
'ARG TAGS=""' to each build stanza fixes this
Command:
`podman build --build-arg TAGS=okd -f images/installer-artifacts/Dockerfile.rhel -t installer-artifacts:4.11-jef .`
**Without fix** (Not all three build as shown as I ran out of disk space)
```
[johnf@johnf-dev installer]$ grep -e "go build" -e TAGS build-installer-artifacts-no-okd.log
[1/4] STEP 2/5: ARG TAGS=""
+ TAGS=okd
+ TAGS='okd release'
+ go build -mod=vendor -ldflags ' -X github.com/openshift/installer/pkg/version.Raw=unreleased-master-5311-gcd69a4bda52fe5e4cf4d250717529ba9e8811ba4-dirty -X github.com/openshift/installer/pkg/version.Commit=cd69a4bda52fe5e4cf4d250717529ba9e8811ba4 -X github.com/openshift/installer/pkg/version.defaultArch=amd64 -s -w' -tags …
```
=> Bug 2080054: Add 'ARG TAGS=""' line for each build step

docs/user/openstack/deploy_sriov_workers.md, docs/user/openstack/ovs-dpdk.md
In 4.11, we did the following:
* Remove the dependency on config-drive and support OpenStack Metadata
URL fetching.
* Automate the configuration of VFIO NO IOMMU
* Add support for vhostuser interfaces for DPDK
This patch adds more content for DPDK, with an example of a pod using
hugepages, dedicated CPUs and the DPDK port.
It also add more content for SR-IOV, like how to create a policy & a
pod.
Later, we'll add content for SR-IOV with HW offload.
=> Update SR-IOV & DPDK doc for OpenStack

data/data/bootstrap/bootstrap-in-place/files/usr/local/bin/install-to-disk.sh.template
If a customer creates a custom RHCOS ISO to install Single Node OpenShift and also embeds the Networking Config via Network Manager Keyfile the installer will not copy over the install environment's network configuration.
Adding the `-n` option to the install-to-disk.sh.template file ensures that the embedded network configuration is copied.
If the Customer does not embed a Network Manager keyfile the DHCP configuration is still used without an issue.
=> Add -n argument to copy network config from install environment to install-to-disk.sh.template

pkg/asset/manifests/powervs/cloudproviderconfig.go
The PowerVS cloud provider needs additional parameters.	 These were added previously
but not	added to the template.
=> Update template for CloudProviderConfig

data/data/ibmcloud/network/image/main.tf
This reverts commit 9f339a3a6f34c0498bb137693f4941669945b7e9.
=> Bug 2082604: Revert "image: set os name to red-coreos-stable-amd64"

pkg/destroy/openstack/openstack.go
Currently, we are trying to remove ports, which are tagged, but
sometimes it happens, that port is created but tagging has failed, or we
didn't get response from Neutron API, resulting with untagged port.
Having network already tagged we can use its id to select all the port
within such network, so that all the ports, not only tagged would be
deleted.
=> Bug 2078875: Delete all the ports from tagged Neutron networks. 

docs/user/openstack/deploy_sriov_workers.md
While refreshing the SR-IOV documentation in #5712 we forgot to update the Table of Contents at the top of the document. This PR fixes it.
=> OpenStack: fix SR-IOV documentation TOC

pkg/asset/installconfig/azure/client.go, pkg/asset/installconfig/azure/mock/azureclient_generated.go, pkg/asset/installconfig/azure/validation.go, pkg/asset/installconfig/azure/validation_test.go, pkg/asset/machines/azure/capabilities.go, pkg/asset/machines/azure/machines.go, pkg/asset/machines/azure/machinesets.go, pkg/asset/machines/master.go, pkg/asset/machines/worker.go
Summary:
With the recent changes introduced to vmNetworkingType #5309, the default setting for was set to true (enable accelerated networking). This has broken a QE test for instance type  `Standard_B4ms`.
The idea behind this PR is to fetch the vm capabilities and then set the default to `vmNetworkingType` to whether or not the VM has the capability. This introduces a new azure client call `GetVMCapabilities`.
=> Azure Provider: fix vmNetworkType defaults by checking vm capabilities

pkg/asset/machines/master.go, pkg/asset/machines/worker.go
Setting all compute nodes to use the instance types that provide
4 VPUs and 16 GB RAM for AWS, GCP and VSphere platforms.
=> machines: Set defaults for machine instance types

images/installer-artifacts/Dockerfile.rhel
For OKD builds TAGS are not propagated to all three builds.  Adding
'ARG TAGS=""' to each build stanza fixes this
Cherry-pick of https://github.com/openshift/installer/pull/5794 on release-4.10
=> Bug 2083327: [release-4.10] Add 'ARG TAGS=""' line for each build step

data/data/agent/files/usr/local/bin/start-cluster-installation.sh.template, data/data/agent/systemd/units/start-cluster-installation.service
Add dependencies to start-cluster-installation service so it starts after assisted-service, and also to ensure it will be rerun if assisted service fails (see https://github.com/openshift/installer/commit/0dbbef3667ab64753819c483fffcaeea0e6a4fde).
Fix script to ensure that the infra_env_id can be retrieved before it is used.
=> AGENT-194: Fixes to start cluster installation script and service

pkg/destroy/openstack/openstack.go
This includes two backports that are required for `cluster destroy` with bring your own network mode to work. One backport comes from this BZ [1] and is related to FIPs and second one [2] makes sure all subnets are removed from the created router, not only tagged ones.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1924701
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1940159
=> Bug 2080219: OpenStack+Kuryr: Fix `cluster destroy` with BYON

pkg/asset/machines/worker.go
GCP has separate quotas for N2 CPUs: https://cloud.google.com/compute/quotas#cpu_quota
We should revert this change until we're not breaking CI.
These changes were introduced in: https://github.com/openshift/installer/pull/5841/commits/16f2827aafa325d9ca5c7e525d5c1abb400d5dd9
=> GCP: Revert Instance Type from N2 to N1

pkg/asset/tls/adminkubeconfig.go, pkg/asset/tls/apiserver.go, pkg/asset/tls/certkey.go
Ensure that we can use an admin kubeconfig pre-generated by the agent
installer. This requires adding the ability to read all of the
certificates that it depends on:
Certs and keys will be read from disk only if they exist and the environment variable `OPENSHIFT_INSTALL_LOAD_CLUSTER_CERTS` is set to `true`.
=> AGENT-40: allow reading cert keys

data/data/agent/files/usr/local/bin/start-cluster-installation.sh.template
This fixes the failure of `start-cluster-installation.service`
```
[core@master-0 ~]$ sudo journalctl -f -u start-cluster-installation.service 
-- Logs begin at Fri 2022-05-13 14:53:57 UTC. --
May 13 14:55:48 master-0.ostest.test.metalkube.org systemd[1]: Starting Service that starts cluster installation...
May 13 14:55:48 master-0.ostest.test.metalkube.org start-cluster-installation.sh[2961]: Waiting for assisted-service to be ready
May 13 14:55:55 master-0.ostest.test.metalkube.org start-cluster-installation.sh[2961]: ./usr/local/bin/start-cluster-installation.sh: line 22: unexpected EOF while looking for matching ``'
```
=> Typo: Fixed redundant `

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.11 bootimage metadata in the installer.
This change includes fixes for the following BZs:
Bug 2050452 - Update osType and hardware version used by RHCOS OVA to indicate it is a RHEL 8 guest*
Bug 2074483 - coreos-installer doesnt work on Dell machines*
Bug 2079944 - Publish RHEL CoreOS AMIs in AWS ap-southeast-3 region*
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos x86_64=411.85.202205101201-0 s390x=411.86.202205030351-0 ppc64le=411.85.202203250810-0 aarch64=411.85.202205040359-0 --url https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases --no-signatures
* May not be fixed in this commit for ppc64le, s390x, and aarch64
=> Bug 2065893: bump RHCOS 4.11 bootimage metadata

data/data/agent/files/etc/issue, pkg/agent/imagebuilder/embed_ignition.go
`fleeting` was the temp name for agent-installer.
=> Rename "fleeting" to "agent-installer"

pkg/asset/machines/worker.go
Virtual machines running on
vSphere should be configured for cores
over sockets for NUMA. The change
in #5841 missed that.
Changing vSphere back to using a single
socket and multiple cores.
=> Bug 2086936: vSphere: change socket back to cores

data/data/agent/systemd/units/start-cluster-installation.service
The create-cluster-and-infra-env service was renamed in
d87d402510aaa96553f46a415483a67d023b3dc2, but the dependencies on it
were not.
=> AGENT-194: Fix service name in dependencies

data/data/agent/files/usr/local/bin/start-cluster-installation.sh.template
Fix the unwanted API call to set API_VIP in case of SNO cluster in start-cluster-installation.service. 
`{"code":"400","href":"","id":400,"kind":"Error","reason":"API VIP cannot be set with User Managed Networking"}`
Although this HTTP 400 error doesn't impact starting cluster installation in the case of SNO, there is no need to check the API_VIP in the first place.
Ref: https://issues.redhat.com/browse/AGENT-193
=> AGENT-193: Do not set api_vip for SNO cluster

pkg/terraform/init.go, pkg/terraform/terraform.go
Sets the TF_DATA_DIR env variable so that .terraform folder and
extracted provider binaries are written to a directory that has
the same level of permissions as the Terraform binary.
=> Bug 2078431: Set TF_DATA_DIR to the Terraform Dir.

pkg/asset/installconfig/azure/validation.go
By checking both "PremiumIO" presence and diskType being "Premium_LRS"
in the same line, we were incorrectly reporting absence of "PremiumIO"
for the instance type in cases when diskType != "Premium_LRS". This
change separates these checks, so the failure message properly conveys
what the problem is.
=> Bug 2084441: azure: proper premiumIO validation message

docs/user/openstack/image_registry_with_custom_pvc_backends.md
The created pvc needs to use a volumeMode of 'Filesystem', not 'Block'. Using the latter will result in the image-registry pod failing to mount the volume because it can't handle raw block devices without a filesystem [1].
[1] https://docs.openshift.com/container-platform/4.10/virt/virtual_machines/virtual_disks/virt-creating-data-volumes.html
=> Bug 1969794: Correct typo

data/data/baremetal/main.tf, data/data/baremetal/masters/main.tf, data/data/baremetal/masters/variables.tf, data/data/baremetal/variables-baremetal.tf, pkg/asset/cluster/tfvars.go, pkg/asset/ignition/bootstrap/baremetal/template.go, pkg/asset/machines/baremetal/hosts.go, pkg/asset/machines/baremetal/hosts_test.go, pkg/tfvars/baremetal/baremetal.go, pkg/tfvars/baremetal/baremetal_test.go, pkg/types/baremetal/defaults/platform.go, pkg/types/baremetal/defaults/platform_test.go, pkg/types/baremetal/platform.go, pkg/types/baremetal/validation/platform.go, pkg/types/baremetal/validation/platform_test.go, pkg/types/validation/installconfig_test.go
This patch ports back in 4.9 branch the fix implemented in PR #5205
=> Bug 2025862: Improve host role management during assets creation

data/data/agent/files/usr/local/bin/start-cluster-installation.sh.template
While reading the output from a single API call, we were sleeping for
30s between each non-ready host. This resulted in an unnecessary delay of up
to 2 minutes on installation.
Instead, sleep only once per API call. Also, reduce the sleep time to
10s.
=> Fix unnecessary delays in start-cluster-installation

data/data/install.openshift.io_installconfigs.yaml, docs/user/customization.md, pkg/types/defaults/installconfig.go, pkg/types/installconfig.go, pkg/types/validation/installconfig.go
Change the default SNO networking from OpenShiftSDN to OVNKubernetes, which has the features (in particular, IPv6) required for a majority of the deployments.
In addition, also change the default networkType just for SNO deployments to OVNKubernetes.
Details in: https://issues.redhat.com/browse/CORS-2008
=> Bug 2090487: SNO network type update

pkg/agent/imagebuilder/content.go, pkg/agent/imagebuilder/releaseimage.go, pkg/agent/imagebuilder/releaseimage_test.go
While specifying the image works locally, we haven't yet figured out the
magic incantation for CI images, so go back to hard-coding the release
image for now.
=> Hard-code agent release image to fix CI

data/data/agent/systemd/units/create-cluster-and-infraenv.service.template, pkg/agent/imagebuilder/content.go, pkg/agent/imagebuilder/releaseimage.go, pkg/agent/imagebuilder/releaseimage_test.go
This is a one-shot service, so we want the pod to run synchronously and
return its error code. When we allowed podman to detach, the service was
treated as successful as soon as the container started.
=> Don't run create-cluster-and-infraenv in the background

pkg/asset/ignition/bootstrap/bootstrap_in_place.go, pkg/asset/ignition/bootstrap/common.go
These methods have been exported as functions so that they can be
used by code outside of bootstrap package that are also building
Ignition configs.
The functions have been modified to take in the Ignition config
that is being modified as its first parameter.
=> AGENT-133: Export addStorageFiles and addSystemdUnits as functions

pkg/asset/installconfig/clustername.go, pkg/types/validation/installconfig.go, pkg/validate/validate.go, pkg/validate/validate_test.go
On prem clusters with a dot in the cluster name causes issues
in keepalived and should be validated to prevent this. Adding
an extra check to make sure there are no dots in the cluster
name.
=> Bug 2084580: Add check to validate cluster name for dots

pkg/asset/installconfig/gcp/validation.go, pkg/asset/installconfig/gcp/validation_test.go
There are a few services that are not required for the installer
to run but are now causing the installer to fail if the permission
is not provided. Adding an optional set of permissions and warn
the user if these permissions are not provided.
List of required services:
compute - used for creating VMs
cloudresourcemanager - used for updating metadata for resources
iam, iamcredentials - used for creating iam accounts
dns - used for dns creation
=> Bug 2084280: Remove optional services from permissions check

data/data/aws/cluster/master/main.tf, data/data/install.openshift.io_installconfigs.yaml, pkg/types/aws/machinepool.go, pkg/types/aws/validation/machinepool.go, pkg/types/aws/validation/machinepool_test.go, pkg/types/aws/validation/platform_test.go, pkg/types/validation/machinepools_test.go
aws: IOPS was not being set even when manually configured
** Removed the terraform parameter that was constantly set to 0 unless this
was an io1 instance.
** Left the bootstrap terraform value remain as it isn't causing any issues, but
we should be aware if we want to change the boostrap aws instance to anything
other than gp3 then we will change that too.
** Added static value tests for the volume type, volume size and iops
for AWS.
=> BUG 2075459: IOPS was not being set even when manually configured

pkg/agent/imagebuilder/content.go, pkg/agent/imagebuilder/releaseimage.go, pkg/agent/imagebuilder/releaseimage_test.go
Since currently we don't have a way to extract the openshift version when the pullspec it's a digest, let's default the version to some hard-coded values. The current approach will not work properly in the general case but it will support the CI environment, where the pullspec it's referencing the current ephemeral release payload
=> agent: default openshift version when pullspec it's a digest

upi/metal/bootstrap/outputs.tf
With the move to equinix/metal terraform provider , resource names
have to be migrated to metal_device.
Is a remnant from the work done in https://github.com/openshift/installer/pull/5941
=> Bug 2057582: Remove all occurances of packet_device from upi/metal

cmd/openshift-install/agent.go, data/data/agent/files/usr/local/share/assisted-service/assisted-service.env.template, data/data/agent/systemd/units/assisted-service.service, pkg/asset/agent/image/ignition.go, pkg/asset/kubeconfig/agent.go
Generate a kubeconfig at the same time as the agent ISO. Pass the certificates used to generate this config into the ISO and to assisted-service to allow it to pass them to the installer, as described in https://github.com/openshift/assisted-service/pull/3836
Note that while this should be safe to merge on its own, the generated kubeconfig will not work until both:
1. https://github.com/openshift/assisted-service/pull/3836 has landed; and
2. we are no longer hard-coding the release image (i.e. openshift/installer#5954 has been reverted), but are instead using a (post-Feature Freeze) 4.11 image.
=> AGENT-40: Generate kubeconfig alongside ISO

cmd/openshift-install/create.go, pkg/asset/agent/image/agentimage.go, pkg/asset/agent/image/cache.go, pkg/asset/agent/manifests/agent.go, pkg/asset/agent/manifests/agentpullsecret_test.go, pkg/asset/agent/manifests/infraenv_test.go, pkg/asset/agent/manifests/nmstateconfig.go, pkg/asset/agent/manifests/nmstateconfig_test.go
* ZTP manifests go in `cluster-manifests`
* Output ISO goes in work directory directly (i.e. same dir as install-config.yaml)
* Suppress debug logs by default
=> Improve user interface of agent installer

docs/user/azure/tested_instance_types.md
Azure: add tested VM family
<BLANK LINE>
add the VM family tested on 4.11 for [CORS-1916 Enable HyperVGeneration version 2 for Azure disks](https://issues.redhat.com/browse/CORS-1916)
[Bug 2085336 [IPI-Azure] Fail to create the worker node which HyperVGenerations is V2 or V1 and vmNetworkingType is Accelerated](https://bugzilla.redhat.com/show_bug.cgi?id=2085336) 
<BLANK LINE>
<footer>
=> Bug 2085336: based on 4.11 CORS-1916 add the vm family

hack/build.sh, images/installer-artifacts/Dockerfile.rhel, terraform/Makefile
- Always run go generate natively
- Add GOOS_GOARCH to all terraform build paths
=> Bug 2094902: Simplify cross-compiling

data/data/rhcos-aarch64.json, data/data/rhcos-amd64.json, data/data/rhcos-ppc64le.json, data/data/rhcos-s390x.json, data/data/rhcos-stream.json, data/data/rhcos.json
This bumps the RHCOS 4.9 boot image metadata to the latest available
versions for each architecture. As part of this change, we are
including fixes for the following issues as part of the boot images:
- BZ 2043299 Ignition fails when reusing existing statically-keyed LUKS volume
- BZ 2055260 randomizing the rootfs UUID is racing with mounting the rootfs
- BZ 2079999Publish RHEL CoreOS AMIs in AWS ap-southeast-3 region
Changes generated with the following
```
$ plume cosa2stream --target data/data/rhcos-stream.json --distro rhcos --url https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases x86_64=49.84.202205311501-0 aarch64=49.84.202205312214-0 ppc64le=49.84.202206022045-0 s390x=49.84.202205311520-0
$ ./hack/update-rhcos-bootimage.py …
```
=> Bug 2043298: bump RHCOS 4.9 boot images

data/data/agent/embed.go
The code in from the fleeting prototype relied on the embed module to
embed the data in data/data/agent. Since that code has now been removed,
and replaced with native installer code, in #5945 the agent data is now
accessed through data.Assets. This second copy of it is no longer
needed.
=> AGENT-133: Remove double embedding of agent data

docs/user/aws/install_upi.md
For disconnected clusters, OpenShift can be configured not to manage
DNS, and the cluster administrator can configure DNS manually.
Otherwise, the Ingress operator will try to contact sts directly
"sts.amazonaws.com" as opposed to the configured VPC endpoint for the
cluster.
=> Bug 2068180: update doc for DNS and disconnected clusters

data/data/bootstrap/baremetal/files/etc/NetworkManager/system-connections/nmconnection.template, data/data/install.openshift.io_installconfigs.yaml, pkg/asset/ignition/bootstrap/baremetal/template.go, pkg/asset/installconfig/baremetal/validation.go, pkg/asset/installconfig/platformprovisioncheck.go, pkg/types/baremetal/platform.go
Add new configuration fields to `install-config.yaml` that will enable the cluster operator to set up static networking for the bootstrap node
This is the implementation of the [Bootstrap external IP OpenShift enhancement](https://github.com/openshift/enhancements/blob/master/enhancements/baremetal/bootstrap-external-ip.md).
=> baremetal: static IP for bootstrap node

data/data/bootstrap/files/usr/local/bin/installer-gather.sh, data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh
On multiple occasions, it has been helpful to collect the systemd journal in it's entirety for deep debugging.  We needed this back in April, and again this week for https://bugzilla.redhat.com/show_bug.cgi?id=2096226.
The netstat data turned out to not be as helpful, but I figured it can't hurt.
=> Bug 2096352: Collect whole journal and netstat data

data/data/aws/bootstrap/main.tf
When terraform tries to find
aws_iam_instance_profile.bootstrap.name it is already available to it
locally from the config that we provide and it need not wait for the
whole resource to actually appear before if tries to spawn ec2 with that
profile name. This can result in the following error:
level=error msg="Error: Error launching source instance: InvalidParameterValue: Value ($cluster_id-bootstrap-profile) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name"
level=error msg="\tstatus code: 400"
This can be avoided if we explicitly use a computed value of aws_iam_instance_profile.bootstrap like arn. That way terraform needs to fetch it before it can use it and it will only be available to terraform once creation is complete.
=> Bug 1859153: IAM instance profile race condition

data/data/install.openshift.io_installconfigs.yaml, pkg/asset/machines/nutanix/machines.go, pkg/asset/machines/worker.go, pkg/types/nutanix/machinepool.go, pkg/types/nutanix/validation/machinepool.go, pkg/types/nutanix/validation/machinepool_test.go
Use GiB instead of MiB for the osDisk size format to make it more readable and convenient for users.
=> Bug 2095917: Nutanix set osDisk with diskSizeGB rather than diskSizeMiB

cmd/openshift-install/create.go
This fixes a previous change where we mistakenly increased the
Kubernetes API timeout instead of the bootstrap timeout.
=> Bug 2090816: Increase bootstrap timeout, not k8s API timeout

data/data/install.openshift.io_installconfigs.yaml, pkg/asset/installconfig/powervs/validation_test.go, pkg/types/defaults/installconfig.go, pkg/types/installconfig.go, pkg/types/powervs/defaults/platform.go
1.Changed PowerVS MachineCIDR from `10.x.x.x/16 to192.168.0.0/16`
2.Added changes to set Default credentialMode for Powervs to `ManualCredentialsMode`
=> [release-4.11.0] Bug 2092296: Changed DefaultMachineCIDR of PowerVS to 192.168.0.0/16

pkg/asset/installconfig/powervs/session.go
Issue: openshift-install create manifests failed for Power VS platform
What happened?
Openshift manifest creation failed with UAAEnpoint not found for few powervs region
```
FATAL failed to fetch Master Machines: failed to fetch dependency of "Master Machines":
failed to generate asset "Platform Credentials Check": ServiceEndpointDoesnotExist: 
UAA endpoint doesn't exist for region: "jp-osa"
```
Expected:
Successfull creation of Openshift Manifests
Changes to fix the ServiceEndpointDoesnotExist
=> Bug 2097260: Fixes openshift-install create manifest failure of Power VS Platform

data/data/aws/cluster/master/main.tf
Right now, the control-plane nodes and their network interfaces
are being created in parallel and sometimes the control plane nodes
try to find their network interface before it's created, causing
an error in the creation of the nodes. Adding a depends on block
to instruct terraform to create the network interfaces before
trying to create the control plane nodes.
=> Bug 2049108: Fix network interface not found error

data/data/rhcos-amd64.json, data/data/rhcos-ppc64le.json, data/data/rhcos-s390x.json, data/data/rhcos-stream.json, data/data/rhcos.json
This brings in fixes for the following issues:
BZ 1983773 - coreos-installer fails to download Ignition (DNS error, failed to lookup address)
BZ 1984086 - Installation with multipath parameters in parmfile fails (DNS resolution missing)
BZ 2078000 - Publish RHEL CoreOS AMIs in AWS ap-southeast-3 region
These changes were generated with:
```
$ hack/update-rhcos-bootimage.py https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases/rhcos-4.8/48.84.202206091823-0/x86_64/meta.json amd64
$ hack/update-rhcos-bootimage.py https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases/rhcos-4.8-ppc64le/48.84.202206072116-0/ppc64le/meta.json ppc64le
$ hack/update-rhcos-bootimage.py https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/relea …
```
=> Bug 2006965: bump RHCOS 4.8 boot images

data/data/rhcos-amd64.json, data/data/rhcos-ppc64le.json, data/data/rhcos-s390x.json, data/data/rhcos.json, pkg/rhcos/ami_regions.go
This brings in fixes for the following issues:
BZ 2078001 - Publish RHEL CoreOS AMIs in AWS ap-southeast-3 region
These changes were generated with:
```
$ hack/update-rhcos-bootimage.py https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases/rhcos-4.7/47.84.202206131038-0/x86_64/meta.json amd64
$ hack/update-rhcos-bootimage.py https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases/rhcos-4.7-ppc64le/47.84.202206131039-0/ppc64le/meta.json ppc64le
$ hack/update-rhcos-bootimage.py https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases/rhcos-4.7-s390x/47.84.202206131037-0/s390x/meta.json s390x
```
=> Bug 2007087: bump RHCOS 4.7 boot images

pkg/asset/installconfig/platform.go
This solves a bug where platform errors out, and subsequently have issues later in the install.
=> Bug 2098243: Adding error handling to powervs platform

pkg/asset/installconfig/clustername.go, pkg/types/validation/installconfig.go
Ensure Nutanix is subject to the same cluster name validation as
other on prem platforms.
=> Bug 2094694: Nutanix cluster name validation

pkg/destroy/powervs/powervs.go
The VPCRegion is optional in the install-config.yaml file.  Therefore we
need to derive it from other data present when we destroy a cluster.
=> Bug 2097940: PowerVS: Handle optional VPCRegion

data/data/agent/files/etc/multipath.conf, pkg/asset/agent/image/ignition.go
Enable the multipathd service with a default config file in the agent
ISO. This is equivalent to specifying the `rd.multipath=default` flag on
the kernel command line, but without the need to mess with the kernel
command line. Since the ISO itself will be attached as virtual or actual
media, there is no need for anything to run during the initramfs.
This allows us the agent to discover multipath Fibre Channel volumes if
they exist.
=> AGENT-230: Enable multipathd in agent ISO

pkg/asset/cluster/cluster.go, pkg/asset/cluster/openstack/openstack.go
We recently switched from using Terraform as a library to using it as a binary. As part of this switch, we have changed the definition of `$PWD` for the providers - it is now a temporary working directory we create rather than the user's current working directory. This breaks the ability to use a `clouds.yaml` file in the local directory when provisioning on OpenStack clouds.
Restore this by checking for the presence of such a file early in the provisioning process and setting an environment variable to point to this file if found. This isn't the nicest solution - it would probably be better to load the file as an asset and copy it to the Terraform working directory - but it should be effective.
=> Bug 2064693: Restore ability to use local clouds.yaml

docs/user/openstack/known-issues.md
By default, the cloud provider does not support creation of FIPs
using pre-defined addresses due to a policy that allows this operation
only for admins. This commit updates the documentation with possible
solutions for this issue.
=> Bug 1997704: [OpenStack] Document in-tree limitation for external LBs

data/data/agent/systemd/units/apply-host-config.service.template, data/data/agent/systemd/units/create-cluster-and-infraenv.service.template, data/data/agent/systemd/units/start-cluster-installation.service, pkg/asset/agent/agentconfig/agent_config.go, pkg/asset/agent/agentconfig/agent_config_test.go, pkg/asset/agent/image/ignition.go
Pass the root device hints into the ISO, and create a service to apply them to the cluster once host inventory is available, but before installation starts.
=> AGENT-227: Use root device hints from agent-config.yaml

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.11 boot image metadata in the
BZ 2059212 Backport https://github.com/util-linux/util-linux/commit/eab90ef8d4f66394285e0cff1dfc0a27242c05aa
BZ 2059304 HPE Synergy 480 Gen10 Plus servers fail to boot control plane nodes with kernel panic
BZ 2092966 [azure] /etc/udev/rules.d/66-azure-storage.rules missing from initramfs
BZ 2093127 CVE-2022-1706 ignition: configs are accessible from unprivileged containers in VMs running on VMware products [openshift-4]
BZ 2094055 Bump coreos-installer for s390x Secure Execution
`plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --url https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases …
=> Bug 2093126: bump RHCOS 4.11 boot image metadata

data/data/agent/systemd/units/apply-host-config.service.template, data/data/agent/systemd/units/create-cluster-and-infraenv.service.template
Since we now know the InfraEnv ID in advance, there's no need to record
it in create-cluster-and-infra-env and then pass it to
apply-host-config from the resulting environment file.
=> AGENT-144: Pass pre-generated InfraEnv ID to apply-host-config

pkg/destroy/gcp/disk.go
** The Length of the disks can be less than the 22 char max. In the case that the
cluster name is very small and a minimal name for disks is generated an error
was thrown, this will fix that error.
** Altered comment for uses to destroying from creating.
=> BUG 2102632: destroy/gcp: Use min length for destroying disks

pkg/asset/installconfig/gcp/gcp.go
If we query GCP for projects without a proper service principal,
the list returned is an empty one and survey errors out with
a non-explanatory message. Adding an error check to see if the
project list is not empty.
=> Bug 2103236: Provide proper error message for empty projects list

pkg/asset/installconfig/openstack/validation/platform.go, pkg/asset/installconfig/openstack/validation/platform_test.go
Before this patch, apiVIP and ingressVIP are checked to be different
based on a comparison of their string representation.
However, the same IP can have different string representation; this is
especially true with IPv6.
With this patch, IP comparison is delegated to the Go standard library.
=> Bug 2103144: openstack: validate apiVIP and ingressVIP to be semantically different

data/data/agent/systemd/units/node-zero.service
In some circumnstances the assisted-service-pod.service may fail to start since the node0 is not yet available.  This patch ensures that the `set-node-zero.sh` completes before systemd will activate follow up services.
=> Bug 2101879: Use systemd path unit to monitor the node0 file

pkg/asset/installconfig/gcp/validation.go
If an unknown region is provided, installer queries GCP for zones
which returns empty. The installer assumes if there are no errors,
the array is populated and uses the first entry that does not
get populated. Adding another safe check to see if the zone length
is not zero and then proceed.
=> Bug 2102324: Fix panic when unknown region is provided.

data/data/agent/files/usr/local/bin/set-hostname.sh, data/data/agent/systemd/units/agent.service.template, data/data/agent/systemd/units/set-hostname.service, pkg/asset/agent/image/ignition.go
[AGENT-228](https://issues.redhat.com//browse/AGENT-228): Systemd service to set hostname defined in agent-config
Users may specify a hostname for a host by defining the hostname
and the host's macAddress in agent-config.yaml.
The agent Ignition then writes each macAddress to hostname mapping
to a file at /etc/assisted/hostnames/.
The file names in that path are MAC addresses. The desired hostname
is the file's content.
A new set-hostname.service runs during boot and reads the macAddress
to hostname mappings and if it finds one of the host's macAddress
is in the mapping, it then updates the host's hostname using the
mapped value.
~~Depends on: #6022~~
=> AGENT-228: Systemd service to set hostname defined in agent-config

pkg/asset/cluster/tfvars.go, pkg/asset/ignition/bootstrap/bootstrap_ignition.go, pkg/tfvars/alibabacloud/alibabacloud.go, pkg/tfvars/aws/aws.go
BZ-2090836 states:
Given An AWS Openshift Install
When I Configured HTTP Proxy for Openshift installer
Then bootstrap Ignition should grab assets in S3 through the configured HTTP proxy
And Not expect direct internet access to the assets
Unless VPC endpoints are added to the noProxy configuration to bypass those endpoints
This PR passes proxy configuration to the ignition by using `GenerateIgnitionShimWithCertBundleAndProxy`
=> Bug 2090836: Fixes CFE-489 - AWS installer should go through proxy for s3 bootstrap ignition call

data/data/openstack/masters/sg-master.tf
The master_ingress_cluster_policy_controller security group rule was
initially introduced with 2636aef but later reverted with a7040d4. It
was then re-introduced by mistake with 40febcf.
=> Bug 2104578: Remove unnecessary SG rule

pkg/destroy/aws/aws.go
This is needed because Hypershift creates those and after being deleted,
they are still visible in the tags api, making it impossible to delete a
Hypershift cluster through the installer.
=> AWS Destroy: Clean up endpoint services

pkg/asset/installconfig/installconfig.go, pkg/asset/installconfig/installconfig_test.go
The hive team uses a lot of fields in the install config that might
not exist due to older versions of the installer missing a few fields
that may have been added in the newer versions, which causes the
installer to reject them all but is needed for proper functioning.
Changing the code a little to now provide a warning message to the
user in case of any unknown fields and then try to unmarshal it
normally instead of strict.
=> Bug 2098299: Switch to perform normal marshalling with unknown fields

data/data/agent/files/usr/local/bin/start-agent.sh.template, data/data/agent/systemd/units/agent.service.template
PR#6045 removed the wait. The wait needs to be put back in
because host registration will fail if the InfraEnv has not been
registered with assisted-service.
=> NO-ISSUE: Wait for InfraEnv to be created before running agent

cmd/openshift-install/gather.go
Errors [like][1]:
level=error msg=Cluster operator monitoring Degraded is True with UpdatingPrometheusK8SFailed: Failed to rollout the stack. Error: updating prometheus-k8s: waiting for Prometheus object changes failed: waiting for Prometheus openshift-monitoring/k8s: expected 2 replicas, got 0 updated replicas
level=info msg=Cluster operator monitoring Available is False with MultipleTasksFailed: Rollout of the monitoring stack failed and is degraded. Please investigate the degraded status error.
should give equal level=error weight to `Available=False` and `Degraded=True`.  The logic I'm improving hasn't been touched since de5a26aa42 (#2450).
[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/kubevirt_kubevirt-tekton-tasks/149/pull-ci-kubevirt-kubevirt-tekton-tasks-ma …
=> cmd/openshift-install/gather: Errorf for Available=False

pkg/asset/agent/image/baseiso.go, pkg/asset/agent/installconfig.go, pkg/asset/agent/manifests/agentclusterinstall.go, pkg/asset/agent/manifests/agentclusterinstall_test.go, pkg/asset/agent/manifests/agentpullsecret.go, pkg/asset/agent/manifests/agentpullsecret_test.go, pkg/asset/agent/manifests/clusterdeployment.go, pkg/asset/agent/manifests/clusterimageset.go, pkg/asset/agent/manifests/infraenv.go, pkg/asset/agent/manifests/infraenv_test.go, pkg/asset/agent/mirror/cabundle.go, pkg/asset/agent/mirror/registriesconf.go
With agent-based installation, we allow users to start directly from ZTP
CRs in cluster-manifests without first generating them from an
install-config. However, the latter will be an option, so resources will
need to depend on the InstallConfig without causing the survey to run if
it is not present.
=> AGENT-136: Add optional install-config asset for agent installation

pkg/destroy/ibmcloud/dns.go, pkg/destroy/ibmcloud/ibmcloud.go
During uninstall/destroy, if no CIS CRN is available, the installer
errors trying to collect DNS Records for deletion. If no CIS CRN
is supplied in metadata, skip attempting to delete the DNS Records.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=2061947
=> Bug 2061947: IBMCloud: Skip DNS Record delete

data/data/agent/files/usr/local/bin/extract-agent.sh.template, data/data/agent/files/usr/local/bin/get-container-images.sh.template, data/data/agent/files/usr/local/bin/start-agent.sh.template, data/data/agent/systemd/units/agent.service.template, data/data/agent/systemd/units/apply-host-config.service.template, data/data/agent/systemd/units/assisted-service-db.service, data/data/agent/systemd/units/assisted-service-pod.service, data/data/agent/systemd/units/assisted-service.service.template, data/data/agent/systemd/units/create-cluster-and-infraenv.service.template, pkg/asset/agent/image/ignition.go, pkg/asset/agent/image/ignition_test.go
Get the images used to start all services from the release payload. 
This works in a connected environment, however in order to fully complete a disconnected install, an assisted-service change to use an icsp file when running 'oc adm release extract' is required as described in https://issues.redhat.com/browse/MGMT-10209.
The disconnected environment can be tested in dev-scripts with https://github.com/openshift-metal3/dev-scripts/pull/1424 using
export MIRROR_IMAGES=true
=> AGENT-263: Get images from release payload

upi/openstack/inventory.yaml, upi/openstack/network.yaml
Akin to `install-config.yaml`'s `platform.openstack.externalDNS`, add a
new `os_external_dns` property of the UPI inventory to allow setting up
external DNS resolvers to the machines' subnet.
=> Bug 2106667: OpenStack UPI: Allow setting external DNS

pkg/asset/agent/agentconfig/agent_config.go, pkg/asset/agent/image/ignition.go
If MAC addresses are provided with uppercase hex digits in the
agent-config, convert them to lowercase before storing in the image. The
client program that searches for hosts just does a direct
(case-sensitive) comparison with the values obtained from inventory.
=> Bug 2106820: Convert all MAC addresses to lowercase

pkg/asset/installconfig/vsphere/mock/vsphere_sim.go, pkg/asset/installconfig/vsphere/validation.go, pkg/asset/installconfig/vsphere/validation_test.go
If a vspehre datacenter is created within a folder, the full invetory
path must be used when retrieving the cluster for network validation
This also extends tests for including the case where the datacenter
is created in a folder.
Fixes #5999
=> Bug 2097691: vsphere installconfig: use full dc path in network validation

pkg/asset/agent/agentconfig/agent_config.go, pkg/asset/agent/agentconfig/agent_config_test.go, pkg/asset/agent/image/ignition_test.go
Validate role value can either be "master" or "worker"
More complex validations will require install-config manifest to
be available.
=> AGENT-267: Add host role to /etc/assisted/hostconfig

data/data/install.openshift.io_installconfigs.yaml, pkg/asset/cluster/ibmcloud/ibmcloud.go, pkg/asset/cluster/tfvars.go, pkg/asset/installconfig/ibmcloud/client.go, pkg/asset/installconfig/ibmcloud/mock/ibmcloudclient_generated.go, pkg/asset/installconfig/ibmcloud/validation.go, pkg/asset/installconfig/ibmcloud/validation_test.go, pkg/destroy/ibmcloud/instance.go, pkg/tfvars/ibmcloud/ibmcloud.go, pkg/types/ibmcloud/platform.go, pkg/types/ibmcloud/platform_test.go, pkg/types/ibmcloud/validation/platform.go, pkg/types/ibmcloud/validation/platform_test.go
Setup enablement for Bring Your Own Network support on IBM Cloud
using IPI. This portion focuses on adding support for the
required values in the InstallConfig, and performing simple
validation of those resources provided.
=> IBMCloud: BYON Enablement - InstallConfig

data/unpack_test.go, pkg/asset/asset_test.go, pkg/asset/store/assetcreate_test.go, pkg/asset/store/filefetcher_test.go, pkg/asset/store/store_test.go
A small testing enhancement.
We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
Reference: https://pkg.go.dev/testing#T.TempDir
=> test: use `T.TempDir` to create temporary test directory

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.12 boot image metadata in the
BZ 2106055 vSphere defaults to SecureBoot on; breaks installation of out-of-tree drivers
```
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --url https://rhcos.mirror.openshift.com/art/storage/releases --no-signatures x86_64=412.86.202207142104-0 aarch64=412.86.202207141642-0 s390x=412.86.202207142236-0 ppc64le=412.86.202207151711-0
```
=> Bug 2106061: bump RHCOS 4.12 bootimage metadata

cmd/openshift-install/create.go, pkg/asset/agent/image/agentimage.go, pkg/asset/filewriter.go
Inspired by the initial work developed by @patrickdillon in PR #5990, also this patch offers the possibility for a writable asset to customize the way its content is persisted into the currently configured assets folder.
This approach it's a tentative to limit the refactoring impact required on the existing codebase by adopting a traits-like pattern, in conjuction with the an adapter to wrap the current default behavior.
In addition, an example of how it could be used to persist the current agent ISO image is provided.
=> AGENT-265: Agent asset interface with traits

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.11 boot image metadata in the
BZ 2106058 vSphere defaults to SecureBoot on; breaks installation of out-of-tree drivers
```
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --no-signatures --url https://rhcos.mirror.openshift.com/art/storage/releases x86_64=411.86.202207150124-0 aarch64=411.86.202207130959-0 s390x=411.86.202207151039-0 ppc64le=411.86.202207150037-0
```
=> Bug 2106062: bump RHCOS 4.11 bootimage metadata

data/data/agent/files/etc/containers/containers.conf
The 'podman create pod' requires a pause container which is fetched from registry.access.redhat.com/ubi8/pause:latest. This won't work in a disconnected environment. This change overwrite the default infra image defined in /usr/share/containers/containers.conf:
`infra_image = "registry.access.redhat.com/ubi8/pause"`
By supplying this field in /etc/containers/containers.conf set to an empty string. 
When this image is not defined, podman will build the image by default and not attempt to retrieve it.  The image which is build and used is:
localhost/podman-pause
=> AGENT-286: Use default image built by podman for pause container

data/data/openstack/masters/private-network.tf, data/data/openstack/masters/sg-master.tf, data/data/openstack/masters/sg-worker.tf
Previously, only the first CIDR was taken into account when creating
the security group rules. This commit now create security group rules
for each one of them, allowing traffic from every possible
MachineNetwork.
=> Bug 2095323: Create security group rules for each MachineNetwork CIDR

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.10 boot image metadata in the
BZ 2059305 [tracker] HPE Synergy 480 Gen10 Plus servers fail to boot control plane nodes with kernel panic
```
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --url https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases --no-signatures x86_64=410.84.202207061638-0 aarch64=410.84.202207051516-0 s390x=410.84.202207060728-0 ppc64le=410.84.202207061403-0
```
=> Bug 2095319: bump RHCOS 4.10 bootimage metadata

pkg/asset/installconfig/gcp/validation.go
Fixed an issue where the error message returned in case there are
no zones retrieved from the APIs.
=> Bug 2102324: Fix validation errors for instance type

data/data/ibmcloud/network/image/main.tf
Update the image tag for the VSI's in IBM Cloud to be RHCOS rather
than Fedora CoreOS, now that IBM Cloud provides proper support for
the RHCOS image tag.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=2082604
Related: https://github.com/openshift/installer/pull/5869
Related: https://github.com/openshift/installer/pull/5860
=> IBMCloud: Update RHCOS image for VSI

pkg/asset/installconfig/aws/permissions.go
** Added the s3::GetBucketPolicy. This is require the user to have permissions to
return the policy of the specified bucket.
=> BUG 2109388: Add AWS S3 Bucket Permissions

pkg/asset/ignition/bootstrap/common.go
If the file /etc/containers/containers.conf is not world-readable,
starting the podman API service fails. If nothing else, this leaves a
lot of misleading junk in the journal logs.
In practice, only the agent installation method is populating this file,
but in principle this is the right mode wherever it is used. We are
creating the file to work around a podman configuration bug, so it is
entirely possible that other installation methods will also use it in
the future. Therefore the fix is in the bootstrap ignition population
method.
=> AGENT-299: Set mode 0644 on containers.conf

cmd/openshift-install/gather.go
** Removed the requirement for control plane nodes during boostrap gather process
** Removed hard/strict failure during bootstrap process while iterating through
stages. If we can find a successful stage the installer will use it instead
of failing immediately when finding a bad stage.
=> BUG 2105341: Remove required check for control planes in boostrap gather

pkg/destroy/ibmcloud/securitygroup.go
Setup enablement for Bring Your Own Network support on IBM Cloud
using IPI. This portion focuses on handling cleanup of IPI created
SecurityGroups, and their SecurityGroupRules, which must be
deleted first due to cross-SG reference. Otherwise, SG's and their
SGRules get deleted with the VPC.
=> IBMCloud: BYON Enablement - SG Rule Cleanup

terraform/providers/ovirt/go.mod, terraform/providers/ovirt/go.sum, terraform/providers/ovirt/vendor/github.com/hashicorp/terraform-plugin-log/internal/logging/filtering.go, terraform/providers/ovirt/vendor/github.com/hashicorp/terraform-plugin-log/internal/logging/options.go, terraform/providers/ovirt/vendor/github.com/hashicorp/terraform-plugin-log/tflog/provider.go, terraform/providers/ovirt/vendor/github.com/hashicorp/terraform-plugin-log/tflog/subsystem.go, terraform/providers/ovirt/vendor/github.com/hashicorp/terraform-plugin-log/tfsdklog/sdk.go, terraform/providers/ovirt/vendor/github.com/hashicorp/terraform-plugin-log/tfsdklog/subsystem.go, terraform/providers/ovirt/vendor/github.com/ovirt/go-ovirt-client/v2/vm.go, terraform/providers/ovirt/vendor/modules.txt
This PR is a continuation of https://github.com/openshift/installer/pull/6148. It updates the `terraform-provider-ovirt` with the necessary fix in `go-ovirt-client` so that a missing soundcard enabled field on the VM struct does not result in an error.
=> updated terraform-provider-ovirt

data/data/coreos/rhcos.json, pkg/asset/cluster/tfvars.go, pkg/asset/ignition/bootstrap/bootstrap_ignition.go, pkg/destroy/gcp/disk.go, pkg/tfvars/alibabacloud/alibabacloud.go, pkg/tfvars/aws/aws.go
This mainly has the effect of updating the CoreOS metadata to the version used in the latest 4.11 RCs.
=> Merge RC release-4.11 into agent-installer branch

data/data/install.openshift.io_installconfigs.yaml, docs/user/customization.md, docs/user/openstack/README.md, docs/user/openstack/install_upi.md, docs/user/troubleshooting.md, pkg/asset/installconfig/installconfig_test.go, pkg/types/alibabacloud/validation/platform_test.go, pkg/types/conversion/installconfig.go, pkg/types/defaults/installconfig.go, pkg/types/installconfig.go, pkg/types/openstack/validation/platform_test.go, pkg/types/validation/installconfig_test.go, scripts/openstack/manifest-tests/additional-security-group/install-config.yaml, scripts/openstack/manifest-tests/cinder-availability-zones/install-config.yaml, scripts/openstack/manifest-tests/nova-availability-zones/install-config.yaml, scripts/openstack/manifest-tests/server-groups/install-config.yaml
Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>
=> Change defaultNetworkType to ovn-kubernetes

data/data/rhcos-aarch64.json, data/data/rhcos-amd64.json, data/data/rhcos-ppc64le.json, data/data/rhcos-s390x.json, data/data/rhcos-stream.json, data/data/rhcos.json, hack/update-rhcos-bootimage.py
This bumps the RHCOS 4.9 boot image metadata to the latest available
versions for each architecture. As part of this change, we are
including fixes for the following BZs:
BZ 2095320 [tracker] HPE Synergy 480 Gen10 Plus servers fail to boot control plane nodes with kernel panic
Changes generated with the following:
```
$ plume cosa2stream --target data/data/rhcos-stream.json --distro rhcos --url https://rhcos.mirror.openshift.com/art/storage/releases/ x86_64=49.84.202207192205-0 aarch64=49.84.202207192128-0 s390x=49.84.202207192141-0 ppc64le=49.84.202207212012-0
$ ./hack/update-rhcos-bootimage.py https://rhcos.mirror.openshift.com/art/storage/releases/rhcos-4.9-aarch64/49.84.202207192128-0/aarch64/meta.json aarch64
$ ./hack/update-rhcos-bootimage.py …
```
=> Bug 2095320: bump RHCOS 4.9 bootimage metadata

pkg/asset/machines/worker.go
This reverts commit e6bbf3e1dab9928c0caf35036fe1451adc8168fb.
This reintroduces using N2 as the default instance type for GCP. CI
quota has been bumped. This should allow installs in regions that
don't have N1 instances.
=> Revert "GCP: Revert Instance Type from N2 to N1"

pkg/asset/tls/utils.go
Otherwise we'll see the red herring message
time="2022-08-02T14:15:46-04:00" level=debug msg="Failed to marshal PKIX public key: %!s(<nil>)"
=> tls: only report error if one happened

data/data/agent/files/usr/local/bin/set-node-zero.sh.template
Add a delay of up to 30 seconds (checking every 5 seconds) to allow the Node0 IP to be set.
=> Bug 2112906: Add a delay when checking Node0 IP address

pkg/asset/agent/installconfig.go, pkg/asset/agent/installconfig_test.go
To be able to validate the install-config.yaml as per agent installer requirements, 
the install-config is first loaded early in the agent installer OptionalInstallConfig.
Then, the following validations are performed if the loaded file is valid YAML.
- Only Baremetal, VSphere, and None platforms are supported
e.g. `invalid install-config configuration: Platform: Unsupported value: "aws": supported values: "baremetal", "vsphere", "none"`
- API and Ingress VIPs must be set when using Baremetal and VSphere platform
e.g. 
1. `invalid install-config configuration: Platform.Baremetal.ApiVip: Required value: ApiVip must be set for baremetal platform`
2. `invalid install-config configuration: Platform.VSphere.IngressVip: Required value: IngressVip must be set for vsphere platform`
- If using …
=> AGENT-161: install-config validations for agent installer

pkg/asset/agent/manifests/nmstateconfig.go, pkg/asset/agent/manifests/nmstateconfig_test.go
The NMStateConfig.Generate was not populating the staticNetworkConfig
when the asset was being generated from the AgentConfig.
Because the staticNetworkConfig is missing, the Ignition asset does
does not add the /usr/local/bin/pre-network-manager-config.sh script
to the ignition config.
This causes the pre-network-manager-config.service to fail on
node0.
=> Bug 2114977: Populate staticNetworkConfig in NMStateConfig.Generate

data/data/rhcos-aarch64.json, data/data/rhcos-amd64.json, data/data/rhcos-ppc64le.json, data/data/rhcos-s390x.json, data/data/rhcos-stream.json, data/data/rhcos.json, docs/dev/pinned-coreos.md, hack/update-rhcos-bootimage.py
Similar to https://github.com/openshift/installer/pull/6109.
rhcos.mirror.openshift.com is the new formal location to download
RHCOS boot images. It is backed by CloudFront CDN, which should be
more reliable and faster than the rhcos-redirector.
=> Bug 2108581: [release-4.8] RHCOS: move to rhcos.mirror.openshift.com

pkg/types/powervs/powervs_regions.go
Montreal was excluded initilally because it lacked an associated IBM Cloud region. We can instead map it to Toronto.
=> Power VS: Add Montreal as a supported region

data/data/rhcos-amd64.json, data/data/rhcos-ppc64le.json, data/data/rhcos-s390x.json, data/data/rhcos-stream.json, data/data/rhcos.json
These changes will update the RHCOS 4.8 boot image metadata in the installer which includes fixing the following BZ:
BZ 2059307 [tracker] HPE Synergy 480 Gen10 Plus servers fail to boot control plane nodes with kernel panic
```
$ plume cosa2stream --target=data/data/rhcos-stream.json --distro=rhcos x86_64=48.84.202208021106-0 s390x=48.84.202208020845-0 ppc64le=48.84.202207281745-0
$ hack/update-rhcos-bootimage.py https://rhcos.mirror.openshift.com/art/storage/releases/rhcos-4.8/48.84.202208021106-0/x86_64/meta.json amd64
$ hack/update-rhcos-bootimage.py https://rhcos.mirror.openshift.com/art/storage/releases/rhcos-4.8-ppc64le/48.84.202207281745-0/ppc64le/meta.json ppc64le
$ hack/update-rhcos-bootimage.py https://rhcos.mirror.openshift.com/art/storage/releases/rhcos- …
```
=> Bug 2098252: bump RHCOS 4.8 bootimage metadata

pkg/asset/installconfig/alibabacloud/alibabacloud.go
The list of regions obtained through the API may include new regions that are not supported, so explicitly define a list of supported regions
=> Alibaba: Use a static region list

pkg/asset/manifests/openstack/cloudproviderconfig.go, pkg/asset/manifests/openstack/cloudproviderconfig_test.go
Since the cluster-cloud-controller-manager-operator is
enforcing all the required configurations, there is no
need to specify those anymore in the installer. This
commit removes all the uneeded configurations.
=> Remove LoadBalancer settings from cloud provider config

images/installer/Dockerfile.upi.ci, images/installer/Dockerfile.upi.ci.rhel8
[TRT-319](https://issues.redhat.com//browse/TRT-319)
Various CI steps use the upi-installer container for it's access to the
aws cli tools among other things.  However, most of those steps also
curl `yq` directly from GitHub.  We can save ourselves some headaches
when GitHub is down by just embedding the binary in the image already.
=> Download `yq` in upi installer containers

data/data/install.openshift.io_installconfigs.yaml, pkg/asset/installconfig/gcp/validation.go, pkg/asset/installconfig/gcp/validation_test.go, pkg/types/gcp/platform.go
This change adds the networkProjecID parameter to the GCP platform in
the install-config. When set, it also validates the project exists and
that the network and subnetworks belong to this project.
https://issues.redhat.com/browse/CORS-2036
=> GCP: Add networkProjectID parameter to install-config.

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.12 boot image metadata in the
BZ 2115528 This will bump bootimage to include latest rpm-ostree
```
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --url https://rhcos.mirror.openshift.com/art/storage/releases --no-signatures x86_64=412.86.202208101039-0 aarch64=412.86.202208101040-0 s390x=412.86.202208090843-0 ppc64le=412.86.202208090152-0
```
=> Bug 2115790: bump RHCOS 4.12 bootimage metadata

docs/user/azure/install_upi_azurestack.md
Updates the instructions to have users remove any credential requests for feature-gated resources. Creating such credentials will cause installs to fail as the bootstrap node continuously fails to create a resource in a namespace that does not exist.
cc @mjpytlak
=> Azure Stack UPI Docs: Remove Feature Gate CRs

pkg/asset/agent/image/ignition.go
Although this service is no longer started or a dependency it should be removed from this list.
=> Remove assisted-ui service from list of agentEnabledServices

data/data/gcp/cluster/main.tf, data/data/gcp/cluster/master/main.tf, data/data/gcp/cluster/master/variables.tf, data/data/gcp/variables-gcp.tf, pkg/tfvars/gcp/gcp.go
This is the second step to enabling an IPI cluster using Shared VPC where the service account does not have sufficient permissions to create firewall rules in the Host Project while maintaining cluster-specific firewall rules.
=> GCP: Added user specified tags on control plane instances

data/data/baremetal/main.tf, data/data/baremetal/masters/main.tf, data/data/baremetal/masters/variables.tf, data/data/baremetal/variables-baremetal.tf, pkg/asset/cluster/tfvars.go, pkg/asset/ignition/bootstrap/baremetal/template.go, pkg/asset/machines/baremetal/hosts.go, pkg/asset/machines/baremetal/hosts_test.go, pkg/tfvars/baremetal/baremetal.go, pkg/tfvars/baremetal/baremetal_test.go, pkg/types/baremetal/defaults/platform.go, pkg/types/baremetal/defaults/platform_test.go, pkg/types/baremetal/platform.go, pkg/types/baremetal/validation/platform.go, pkg/types/baremetal/validation/platform_test.go, pkg/types/validation/installconfig_test.go
This patch ports back in 4.8 branch the fix implemented in PR #5205
=> Bug 2025901: Improve host role management during assets creation

images/installer/Dockerfile.upi.ci, images/installer/Dockerfile.upi.ci.rhel8
Backport https://github.com/openshift/installer/pull/6008 to 4.11
=> Bug 2118514: [4.11] Download yq in upi installer containers

pkg/asset/agent/installconfig.go, pkg/asset/agent/installconfig_test.go
When controlPlane.replicas = 1 and compute.replicas is missing from install-config.yaml,  validation warns users that compute.replicas needs to be set to 0 when controlPlane.replicas = 1 for SNO cluster on none platform.
validation error: `invalid install-config configuration: Compute.Replicas: Required value: Installing a Single Node Openshift requires explicitly setting compute replicas to zero`
https://bugzilla.redhat.com/show_bug.cgi?id=2117687
=> Bug 2117687: compute.replicas must be 0 for SNO

pkg/asset/cluster/ibmcloud/ibmcloud.go, pkg/asset/installconfig/ibmcloud/client.go, pkg/asset/installconfig/ibmcloud/metadata.go, pkg/asset/installconfig/ibmcloud/subnet.go, pkg/asset/installconfig/ibmcloud/validation_test.go, pkg/asset/installconfig/installconfig.go, pkg/asset/machines/ibmcloud/machines.go, pkg/asset/machines/ibmcloud/machinesets.go, pkg/asset/machines/master.go, pkg/asset/machines/worker.go, pkg/asset/manifests/cloudproviderconfig.go, pkg/asset/manifests/ibmcloud/cloudproviderconfig.go, pkg/asset/manifests/ibmcloud/cloudproviderconfig_test.go
Setup enablement for Bring Your Own Network support on IBM Cloud
using IPI.
=> IBMCloud: BYON Enablement

pkg/asset/agent/image/ignition.go, pkg/asset/agent/image/ignition_test.go, pkg/asset/agent/manifests/nmstateconfig.go, pkg/asset/agent/manifests/nmstateconfig_test.go
Numerous places assume that there will be at least one NMStateConfig:
* https://bugzilla.redhat.com/show_bug.cgi?id=2116489
* https://bugzilla.redhat.com/show_bug.cgi?id=2115770
* https://bugzilla.redhat.com/show_bug.cgi?id=2115798
* https://bugzilla.redhat.com/show_bug.cgi?id=2115803
* https://bugzilla.redhat.com/show_bug.cgi?id=2117302
Since these are not easily discoverable by users, temporarily reinstate
the requirement that at least one NMState configuration be provided
(even if the RendezvousIP is specified). This will provide users with an
upfront error rather than a difficult-to-debug mystery.
=> AGENT-246: Temporarily require at least one NMStateConfig to be specified

data/data/ibmcloud/network/vpc/security-groups.tf
Allow metrics traffic to flow through the cluster, including the
worker nodes, to resolve issues where the KCM and KS metrics are
not accessible.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2109800
=> Bug 2109800: IBMCloud: Allow metrics traffic

pkg/agent/rest.go, pkg/asset/agent/image/ignition.go, pkg/asset/agent/image/ignition_test.go
Digging around I found this function already implemented so I decided to use it.
=> Bug 2115770: Check for RendezvousIP in Agent config if NMStateConfig is not provided

pkg/asset/agent/agentconfig/agent_config.go, pkg/asset/agent/agentconfig/agent_config_test.go, pkg/asset/agent/image/ignition.go, pkg/asset/agent/image/ignition_test.go, pkg/asset/agent/manifests/nmstateconfig.go, pkg/asset/agent/manifests/util_test.go, pkg/types/agent/OWNERS, pkg/types/agent/agent_config_type.go, pkg/types/agent/conversion/agentconfig.go, pkg/types/agent/conversion/agentconfig_test.go
The InstallConfig schema does not have a Spec subresource, so
configuration items are added directly at the top level of the file. It
is desirable that the AgentConfig should behave the same. There is no
Status subresource for an AgentConfig either, and in fact not even any
plans to ever install AgentConfig into clusters as a CRD, so there is no
need for a Spec.
Set the initial version of AgentConfig to v1alpha1, since we are not yet
committing to not changing it. This will now be required.
This is a breaking change that will require users to change their
existing agent-config.yaml files, so better that it happen now.
=> Collapse AgentConfig spec and add versioning

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
The MCO needs access to `image-references` during bootstrap so it can reference additional images. 
I'm open to more elegant ways to do this if you have concerns.  
As for why...
- As part of [OCP CoreOS Laysering](https://github.com/openshift/enhancements/pull/1150), there are "new format" images that are actually bootable container images rather than just "wrappers" around an ostree commit
- We have built and added these as new ART images `rhel-coreos-8` and `rhel-coreos-8-extensions`. ( https://issues.redhat.com/browse/ART-3883, https://github.com/openshift/release/pull/31118) 
- The MCO eventually wants to use them in lieu of `machine-os-content`
- There will be more images for additional CoreOS versions (e.g. `rhel-coreos-9`, `rhel-coreos-9-extensions`) and potentially other things, …
=> Extract the image-references file from the release, pass it to `machine-config-operator`

images/installer/Dockerfile.upi.ci
Removing the downloading of `govc` to
workaround rate limit errors
=> OCPBUGS-262: UPI image download govc rate limit failure

pkg/asset/installconfig/ibmcloud/metadata.go
A shared mutex for all ibmcloud.metadata functions, including the
public Client method, deadlocks calls. Since the Client is a public
method, we should still use a mutex, but it should be a unique
mutex to prevent deadlocking.
=> IBMCloud: Use unique mutex for Client retrieval

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.11 boot image metadata in the
BZ 2118311 bump boot images to pick up signed RPMS
```
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --no-signatures --url https://rhcos.mirror.openshift.com/art/storage/releases x86_64=411.86.202208112011-0 aarch64=411.86.202208111758-0 s390x=411.86.202208111740-0 ppc64le=411.86.202208112105-0
```
=> Bug 2117279: bump RHCOS 4.11 bootimage metadata

pkg/destroy/ibmcloud/ibmcloud.go
Handle cases when there is no ResourceGroupName provided
during destroy, or the ResourceGroup doesn't exist, or cannot
be found.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=2061947
=> Bug 2061947: IBMCloud: Handle missing RG

terraform/providers/vsphereprivate/resource_vsphereprivate_import_ova.go
During the terraform decoupling work [1], a fix for the default value
for the disk provisioning type [2] ended up being lost.
This commit bring those changes back, fixing a regression where the
default disk type would be set to "thick" instead of the default storage
policy of vsphere.
[1] https://github.com/openshift/installer/commit/9c77d6a437bcbf7289dc5affb8809bf3d17e018d
[2] https://github.com/openshift/installer/commit/f3c9bfade850662ab74ae4cc62a226d75da43819
=> Bug 2098072: vsphere: fix default disk type when not speficied

pkg/types/gcp/validation/platform.go, pkg/types/gcp/validation/platform_test.go, pkg/types/validation/installconfig.go
** Added checks in types to ensure that network, computeSubnet, and controlPlaneSubnet
are set when NetworkProjectID exists.
** Added checks in installconfig to ensure that CredentialsMode is set to either Passthrough or
Manual when NetworkProjectID exists.
[CORS-2048](https://issues.redhat.com//browse/CORS-2048)
Requires #6166
=> gcp: Add validation for Network Project Data

data/data/vsphere/master/main.tf, upi/vsphere/vm/main.tf
This PR enables steal time accounting on
control plane virtual machines.
From the linux commit:
Steal time is the amount of CPU time needed by a guest virtual machine
that is not provided by the host. Steal time occurs when the host
allocates this CPU time elsewhere, for example, to another guest.
Steal time can be enabled by adding the VM configuration option
stealclock.enable = "TRUE". It is supported by VMs that run hardware
version 13 or newer.
=> OCPBUGS-268: vSphere - enable steal time accounting

cmd/openshift-install/create.go
The console may become optional (openshift/enhancements#922), so teach the installer to handle its absence gracefully.
We've waited on the console since way back in ff53523b11 (#806).  Back then, install-complete timing was much less organized, and since e17ba3c571 (#1132) we've blocked on ClusterVersion going `Available=True`.  So the current dependency chain is:
1. Console route admission blocks console operator from going `Available=True` in its ClusterOperator.
2. Console ClusterOperator blocks cluster-version operator from going `Available=True` in ClusterVersion.
3. ClusterVersion blocks installer's `waitForInitializedCluster`.
So we no longer need to wait for the route to show up, and can fail fast if we get a clear `IsNotFound`.  I'm keeping a bit of polling so we don't fail an …
=> cmd/openshift-install/create: One shot console access

pkg/asset/manifests/cloudproviderconfig.go, pkg/asset/manifests/gcp/cloudproviderconfig.go, pkg/asset/manifests/gcp/cloudproviderconfig_test.go
** Pull the NetworkProjectID out of the installconfig and pass it to the cloud provider manifests
** Added tests for the new manifest information
** Added the network project ID to match that of
https://github.com/openshift/origin/blob/57b52e0a9528027448422d678c4ef682dfc0b885/vendor/k8s.io/legacy-cloud-providers/gce/gce.go#L136
[CORS-2037](https://issues.redhat.com//browse/CORS-2037)
=> manifests: Pass the NetworkProjectID to manifests

data/data/gcp/bootstrap/main.tf, data/data/gcp/cluster/main.tf, data/data/gcp/cluster/network/firewall.tf, data/data/gcp/cluster/network/variables.tf, data/data/gcp/variables-gcp.tf, pkg/asset/cluster/tfvars.go, pkg/tfvars/gcp/gcp.go
** Added the Network Project ID data to gcp terraform vars
** Added checks to GCP terraform to set count to 0 for firewall rules when
the Network Project ID is available.
CORS 2039
Requires #6166
=> GCP: Remove firewall rules when providing network project id

data/data/powervs/bootstrap/vm/outputs.tf, data/data/powervs/cluster/bootstrap/lb/ouputs.tf, data/data/powervs/cluster/bootstrap/outputs.tf, data/data/powervs/cluster/dns/dns.tf, data/data/powervs/cluster/dns/variables.tf, data/data/powervs/cluster/main.tf, data/data/powervs/cluster/master/lb/variables.tf, data/data/powervs/variables-powervs.tf, pkg/asset/cluster/tfvars.go, pkg/destroy/powervs/cloud-instance.go, pkg/destroy/powervs/cloud-sshkey.go, pkg/destroy/powervs/cloudconnection.go, pkg/destroy/powervs/power-instance.go, pkg/destroy/powervs/power-sshkey.go, pkg/destroy/powervs/powervs.go, pkg/destroy/powervs/publicgateway.go, pkg/tfvars/powervs/powervs.go, pkg/types/validation/installconfig.go
This adds support for a private DNS server to PowerVS by
conditionally creating resources based on:
publish: Internal
in the install-config.yaml
=> Add support for private DNS server to PowerVS

docs/user/openstack/README.md, docs/user/openstack/deploy_sriov_workers.md, pkg/asset/installconfig/openstack/validation/machinepool.go, pkg/asset/installconfig/openstack/validation/machinepool_test.go
Other platforms require at least 100 GB of disk size and we've updated
openshift-docs to reflect that in OpenStack too. Seems like we forgot to
update flavor validation code and docs in the installer. This commit
fixes this.
=> Bug OCPBUGS-164: OpenStack: Set minimum disk of a flavor to 100 GB

pkg/asset/installconfig/ibmcloud/client.go, pkg/asset/installconfig/ibmcloud/dns.go, pkg/asset/installconfig/ibmcloud/metadata.go, pkg/asset/installconfig/ibmcloud/mock/ibmcloudclient_generated.go, pkg/asset/installconfig/ibmcloud/validation.go, pkg/asset/installconfig/ibmcloud/validation_test.go, pkg/asset/installconfig/platformprovisioncheck.go, pkg/asset/manifests/dns.go, pkg/asset/manifests/infrastructure.go, pkg/types/validation/installconfig.go, vendor/github.com/IBM/networking-go-sdk/dnszonesv1/dns_zones_v1.go, vendor/modules.txt
Add support for DNS Service on IBM Cloud in IPI. This allows lookup
of resources based on PublishStrategy, CIS (External) vs. DNS
(Internal). Handles service and zone lookup, and configuring DNS
and Infrastructure.
=> CORS-2271: IBMCloud: Add DNS Service support - installconfig

pkg/asset/agent/image/ignition.go, pkg/asset/agent/image/ignition_test.go
Based on https://github.com/openshift/installer/pull/6272, this fixes the mirror generation to handle release images that include the sha256 checksum, e.g:
`quay.io/openshift-release-dev/ocp- release@sha256:300bce8246cf880e792e106607925de0a404484637627edf5f517375517d54a4`
=> AGENT-326: Fix releaseImage mirror handling with unit test

pkg/asset/machines/azure/machines.go
If there's no internal load balancer specified on the Machine provider spec, then, when we replace the Machine, users must manually add the new Machine to the backend pool for the internal load balancer.
This will become more important when users start using controlplanemachinesets to replace machines, but we should make sure users have this data as soon as possible IMO.
I reviewed the terraform for creating the internal load balancer and, as far as I can tell, nothing there was conditional and we should always have an internal load balancer, so I think this is safe to do.
=> Bug 2117439: Azure masters should publish on an internal load balancer

data/data/gcp/cluster/network/common.tf
This change modifies the GCP Terraform data resources for the
pre-existing networks and subnets to specify the project as defined
in the network_project_id variable. This variable is derived from the
install config networkProjectID parameter. When defined, this causes
Terraform to look in the specified project for these resources. When
undefined, the default, this variable will be an empty string at which
point Terraform will look in the default project.
https://issues.redhat.com/browse/CORS-2038
=> gcp: specify network_project_id for network and subnets

pkg/destroy/powervs/powervs.go
We were asked to delete the existing Cloud Connection before
deleting the VPC.
=> Switch delete ordering of CloudConnect and VPCs

data/data/coreos/fcos.json
Update FCOS to 36.20220806.3.0. This is required for layering fixes to land in 4.12
=> Bump FCOS to latest stable

pkg/asset/machines/gcp/machines.go
This change adds the networkProjectID to the network configuration for
the compute and control plane machine manifests. It will be skipped
(omitempty) when the parameter is not specified in the install config.
https://issues.redhat.com/browse/CORS-2069
=> gcp: machines to use networkProjectID when defined

OWNERS_ALIASES
Signed-off-by: Clement Verna <cverna@tutanota.com>
=> OWNER_ALIASES: remove Saqib Ali from the coreos approvers and reviewers

pkg/asset/machines/aws/machines.go, pkg/asset/machines/master.go
Creating an extra CRD asset for the ControlPlaneMachineSet which
is required for the machine api operator for more control over
the control-plane nodes that come up on AWS.
=> AWS: Create ControlPlaneMachineSet CRDs

data/data/powervs/cluster/power_network/pi_network.tf
Because the VPC will not always be in the same DC as the Power VS service instance, we want to enable global routing to allow for this. Additionally we want to specify the DNS server as it's required until private cluster support lands.
=> Power VS: Enable global routing for cloud connection and specify dns

pkg/types/baremetal/validation/platform.go, pkg/types/baremetal/validation/platform_test.go
Capital letters in install-config.yaml .platform.baremetal.hosts[].name caused bootkube to loop forever with errors.
The install gets stuck on openshift-master-host creation.
See: https://bugzilla.redhat.com/show_bug.cgi?id=2084471
This patch uses the same validation function and makes the install fail early with a clear message.
=> Bug 2084471: validate baremetal hosts names are lowercase RFC 1123

pkg/asset/installconfig/vsphere/validation.go
The following nil pointer was found while installing into a multi-zone vsphere. 
```
sh-4.4$ ./openshift-install-zonal create cluster --dir cluster/
INFO Consuming Install Config from target directory 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c8 pc=0x2fd69aa]
goroutine 1 [running]:
github.com/vmware/govmomi/object.NewSearchIndex(...)
/var/home/rbost/go/src/github.com/openshift/installer/vendor/github.com/vmware/govmomi/object/search_index.go:33
github.com/vmware/govmomi/find.NewFinder(0x0, {0x0?, 0x0, 0x1d?})
/var/home/rbost/go/src/github.com/openshift/installer/vendor/github.com/vmware/govmomi/find/finder.go:51 +0x6a
github.com/openshift/installer/pkg/asset/installconfig/vsphere.getVCenterClient({{0xc0 …
```
=> vsphere: error checking while creating vsphere clients

data/data/ibmcloud/bootstrap/main.tf, data/data/ibmcloud/network/cis/main.tf, data/data/ibmcloud/network/dns/common.tf, data/data/ibmcloud/network/dns/main.tf, data/data/ibmcloud/network/dns/variables.tf, data/data/ibmcloud/network/main.tf, data/data/ibmcloud/network/vpc/common.tf, data/data/ibmcloud/network/vpc/outputs.tf, data/data/ibmcloud/variables-ibmcloud.tf, pkg/asset/cluster/ibmcloud/ibmcloud.go, pkg/asset/cluster/tfvars.go, pkg/tfvars/ibmcloud/ibmcloud.go, pkg/types/ibmcloud/metadata.go
Add support for creating, configuring, and destroying Terraform
resources for private (Internal) IPI clusters on IBM Cloud, using
DNS Services, rather than CIS (public/External).
Partial: https://issues.redhat.com/browse/CORS-2255
=> CORS-2280: IBMCloud: Add TF support for private DNS

data/data/manifests/bootkube/cvo-overrides.yaml.template
```
╰─ oc get clusterversion
NAME      VERSION                              AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.12.0-0.nightly-2022-09-02-154321   True        False         84m     Cluster version is 4.12.0-0.nightly-2022-09-02-154321
╰─ oc get clusterversion/version -ojson | jq .spec
{
"channel": "stable-4.11",
"clusterID": "f96fff8e-4905-4f9a-92e0-96a659fe8cc6"
}
```
=> OCPBUGS-889: bump default channel to stable-4.12

images/installer/Dockerfile.upi.ci, images/installer/Dockerfile.upi.ci.rhel8
The alibabacloud client "aliyun" would be used when pre-configuring some resources (e.g. VPC, bastion host, etc.) before launching an OCP cluster with customization.
=> download 'aliyun'

images/installer/Dockerfile.upi.ci, images/installer/Dockerfile.upi.ci.rhel8
In latest 4.12 upi-installer image, we found it's missing `dig` command that's required for https://github.com/openshift/release/blob/master/ci-operator/step-registry/azure/provision/bastionhost/azure-provision-bastionhost-commands.sh#L17
=> Add bind-utils in upi installer image

pkg/terraform/stages/platform/stages.go
If "none" is specified as platform, we should skip the terraform stages
extraction since terraform is not used in that case. Otherwise we'll get
the following panic:
```
panic: unsupported platform "none"
goroutine 1 [running]:
github.com/openshift/installer/pkg/terraform/stages/platform.StagesForPlatform({0x146f2d0a, 0x1619aa08})
/go/src/github.com/openshift/installer/pkg/terraform/stages/platform/stages.go:55 +0x2ff
main.runGatherBootstrapCmd({0x14d8e028, 0x1})
/go/src/github.com/openshift/installer/cmd/openshift-install/gather.go:115 +0x2d6
main.newGatherBootstrapCmd.func1(0xc001364500, {0xc0005a0b40, 0x2, 0x2})
/go/src/github.com/openshift/installer/cmd/openshift-install/gather.go:65 +0x59
github.com/spf13/cobra.(*Command).execute(0xc001364500, {0xc0005a0b20, 0x2, 0x2}) …
```
=> OCPBUGS-302: bootstrap gather: fix panic when platform is "none"

pkg/asset/machines/aws/machines.go, pkg/asset/machines/master.go
Reverts openshift/installer#6172 ; tracked by OCPBUGS-1056
TRT are reverting this breaking change.  This change has broken single-node openshift.
Errors from single-node:
```
Sep 08 07:39:14 ip-10-0-54-229 bootkube.sh[5263]: "99_openshift-machine-api_master-control-plane-machine-set.yaml": failed to create controlplanemachinesets.v1.machine.openshift.io/cluster -n openshift-machine-api: ControlPlaneMachineSet.machine.openshift.io "cluster" is invalid: spec.replicas: Unsupported value: 1: supported values: "3", "5"
```
To unrevert this revert, revert this PR, and layer an additional separate commit on top that addresses the problem.   Please verify the unrevert works correctly on single-node by  invoking appropriate `/test` commands (such as `/test e2e-aws-single-node`).
CC: @rna-afk, …
=> Revert "AWS: Create ControlPlaneMachineSet CRDs"

data/data/azure/cluster/dns/dns.tf
** Added depends for the azurerm_private_dns_zone_virtual_network_link.network to depend on "".private. This should enforce the dependencies.
=> OCPBUGS-927: Add depends to enforce order for azure terraform dependencies

data/data/azure/cluster/dns/dns.tf
Reverts openshift/installer#6333 which broke Azure installs but those jobs weren't blocking.
=> Revert "[release-4.11] OCPBUGS-1157: Add depends to enforce order for azure terraform dependencies"

data/data/gcp/bootstrap/main.tf, data/data/gcp/cluster/main.tf, data/data/gcp/cluster/network/firewall.tf, data/data/gcp/cluster/network/variables.tf, data/data/gcp/variables-gcp.tf, data/data/install.openshift.io_installconfigs.yaml, pkg/asset/cluster/tfvars.go, pkg/tfvars/gcp/gcp.go, pkg/types/gcp/platform.go, pkg/types/gcp/validation/platform.go, pkg/types/gcp/validation/platform_test.go
The createFirewallRules parameter in the install config can be used to toggle the creation of the firewall rules. This enables users to provide their own rules in advance of the installer and skip the installer from attempting to create them.
https://issues.redhat.com/browse/CORS-2288
=> GCP: Add createFirewallRules parameter to installconfig.

pkg/asset/machines/aws/machines.go, pkg/asset/machines/master.go
Single node clusters do not need the CPMS manifests and hence adding
a check to stop the creation of CPMS when the Replicas is set to
anything below 1.
Ideally, the replicas are set to 0 when the installer needs to create
single node clusters.
=> OCPBUGS-1247: Restrict CPMS from being created with single node clusters

data/data/install.openshift.io_installconfigs.yaml, docs/user/customization.md, pkg/asset/agent/installconfig_test.go, pkg/asset/installconfig/installconfig_test.go, pkg/asset/manifests/proxy.go, pkg/explain/printer_test.go, pkg/types/defaults/installconfig.go, pkg/types/defaults/installconfig_test.go, pkg/types/installconfig.go, pkg/types/validation/installconfig.go
A new field _additionalTrustBundlePolicy_ is added to support transparent proxy scenario. 
_additionalTrustBundlePolicy_ defines conditional policy to add AdditionalTrustBundle to the nodes' trusted certificate store. Following are the valid values :
_default_ : use AdditionalTrustBundle if there is http/https proxy configured
_always_ : ignore all conditions and use AdditionalTrustBundle
=> [CFE-465] Add additionalTrustBundlePolicy field to allow CA bundle propagation

pkg/asset/ignition/bootstrap/cvoignore.go
[`docs/design/resource_dep.svg`][1] shows the complicated hierarchy of installer assets, and it is likely that not all users are familiar with all the manifests that the installer generates.  It's also possible that there is a complicated hierarchy on the caller's side, and not just a single actor, creating additional manifests to feed into a create-manifests flow.  With all of these inputs, it seems possible that folks occasionally call the installer with directory contents that result in multiple manifests for a single resource, as determined by the (group, kind, namespace, name) tuples.  This commit adds a check at the slightly-before-Ignition-serialization overrides asset, which was already in the business of iterating over the content and building ClusterVersion spec.overrides. …
=> pkg/asset/ignition/bootstrap/cvoignore: Add group/kind/name(space) collision detection

docs/user/azure/limits.md, pkg/asset/installconfig/azure/validation.go, pkg/asset/installconfig/azure/validation_test.go, pkg/asset/machines/master.go, pkg/asset/machines/worker.go, pkg/types/azure/defaults/machines.go
As part of the overall effort to add IPI support for Azure on ARM
instances (https://issues.redhat.com/browse/ARMOCP-16), this PR enables
the creation of arm64 machines when the arm64 architecture is specified
in the install config. Also added validation and tests.
=> azure: add support for arm64 instances (Dps_v5 instances)

pkg/asset/agent/image/ignition.go, pkg/asset/agent/manifests/nmstateconfig.go, pkg/asset/agent/manifests/nmstateconfig_test.go, pkg/asset/agent/manifests/util_test.go
When creating DHCP only cluster with agent config ( i.e. only RendezvousIP), do not require any networkConfig to be provided.
=> OCPBUGSM-47740: No networkconfig needed with DHCP agent config

pkg/destroy/ibmcloud/dns.go, pkg/destroy/ibmcloud/ibmcloud.go, vendor/github.com/IBM/networking-go-sdk/dnssvcsv1/dns_svcs_v1.go, vendor/modules.txt
Add support for destroying DNS Service on IBM Cloud in IPI, as
part of Private (Internal) clusters, which use IBM Cloud DNS
Services instead of CIS (External clusters).
- [CORS-2280](https://issues.redhat.com//browse/CORS-2280): IBMCloud: Add DNS Service destroy
- IBMCloud: Add DNS Service support - vendor
Partial: https://issues.redhat.com/browse/CORS-2280
=> CORS-2280: IBMCloud: Add DNS Service destroy

data/data/ibmcloud/network/dns/main.tf, data/data/ibmcloud/network/dns/variables.tf, data/data/ibmcloud/network/main.tf, data/data/ibmcloud/variables-ibmcloud.tf, pkg/asset/cluster/tfvars.go, pkg/asset/installconfig/ibmcloud/client.go, pkg/asset/installconfig/ibmcloud/metadata.go, pkg/asset/installconfig/ibmcloud/mock/ibmcloudclient_generated.go, pkg/tfvars/ibmcloud/ibmcloud.go, vendor/github.com/IBM/networking-go-sdk/dnssvcsv1/dns_svcs_v1.go, vendor/modules.txt
Determine whether a VPC is already a permitted network
for Private/DNS (Internal) clusters for the DNS Service.
This can occur when using BYON and Private clusters.
Partial: https://issues.redhat.com/browse/CORS-2280
=> CORS-2280: IBMCloud: Add DNS Service permitted VPC

data/data/install.openshift.io_installconfigs.yaml, data/data/vspherezoning/bootstrap/main.tf, data/data/vspherezoning/bootstrap/variables.tf, data/data/vspherezoning/master/main.tf, data/data/vspherezoning/master/variables.tf, data/data/vspherezoning/pre-bootstrap/main.tf, data/data/vspherezoning/variables-vspherezoning.tf, pkg/asset/cluster/cluster.go, pkg/asset/cluster/tfvars.go, pkg/asset/cluster/vsphere/vsphere.go, pkg/asset/installconfig/vsphere/validation.go, pkg/asset/installconfig/vsphere/validation_test.go, pkg/asset/machines/vsphere/machines.go, pkg/asset/machines/vsphere/machines_test.go, pkg/asset/machines/vsphere/machinesets.go, pkg/asset/machines/vsphere/machinesets_test.go, pkg/asset/manifests/cloudproviderconfig.go, pkg/asset/manifests/vsphere/cloudproviderconfig.go, pkg/asset/manifests/vsphere/cloudproviderconfig_test.go, pkg/tfvars/vsphere/vsphere.go, pkg/types/vsphere/defaults/platform.go, pkg/types/vsphere/platform.go, pkg/types/vsphere/validation/machinepool.go, pkg/types/vsphere/validation/machinepool_test.go, pkg/types/vsphere/validation/platform.go, pkg/types/vsphere/validation/platform_test.go
This PR contains the changes from @rvanderp3 and I that updates the platform spec to conform to the changes in openshift/api#1278. The changes greatly reduce the complexity of the zonal platform spec.
=> vsphere zonal: platform spec and terraform updates

data/data/powervs/cluster/power_network/pi_network.tf
this will make the destroy logic more robust, as currently we have no way of knowing which networks belonged to which clusters when destroy errors occurred. the current logic is to look at the nw attached to a cluster vm and delete it, but if the cluster vms had been destroyed already, there would be an unused nw left behind.
=> Power VS: use the new name field for the dhcp nw

data/data/aws/bootstrap/main.tf, pkg/types/aws/validation/platform.go
Extend user tag limit to 40 based on AWS limits. 10 tags are reserved for OpenShift use. Previously, there has been a confusion on the tag limit for S3 bucket vs S3 bucket object tag limit. S3 bucket object tag limit is 10 while the requirement is for S3 bucket which has limit of 50 tags.
Reference : https://docs.aws.amazon.com/AmazonS3/latest/userguide/CostAllocTagging.html
=> OCPBUGS-1234 : [CFE-580] Extend user tags limit to 40 based on AWS limits

pkg/types/openstack/validation/platform.go, pkg/types/openstack/validation/platform_test.go, pkg/types/validation/installconfig.go
The validation is no longer necessary now that we stopped using mDNS. Instead, rely on cluster name validation common to all platforms for length check and the on-prem cluster name validation for names containing dots.
This aligns with other on-prem platforms.
=> OCPBUGS-963: OpenStack: Lift validation for 14 chars cluster names

upi/aws/cloudformation/02_cluster_infra.yaml
** Upgrade Python3.7 to 3.8 for AWS UPI jobs. Currently the dependent packages
do not support 3.8+.
=> OCPBUGS-717: Upgrade python3.7 to 3.8 for AWS UPI

docs/user/aws/install_upi.md
64665ebccf2ec699ce034ff2f2b996b245a77579 added a control plane machineset manifest. This updates corresponding UPI docs to remove this manifest when the cluster is runnning without MAO.
/cc @JoelSpeed 
/cc @rna-afk
=> AWS UPI docs: remove control plane machineset

docs/user/agent/OWNERS, docs/user/agent/mce-integration.md
This patch adds some brief documentation explaining how to install an hub cluster via MCE through the agent based installer
=> AGENT-328: Add documentation for agent mce integration

pkg/asset/machines/powervs/machines.go
This fixes the following error:
error getting network ID: failed to find an network ID with RegEx ^DHCPSERVER[0-9a-z]{32}_Private$ The DHCP service has changed the name it created to include the cluster infraID.
=> Fix generating Machine objects for PowerVS

data/data/azure/cluster/dns/dns.tf, data/data/azure/cluster/dns/versions.tf, pkg/terraform/stages/azure/stages.go
We started seeing errors from Azure about network links not being able to find a previously created private zone.  The order in terraform seems to be correct[1]:
```
time="2022-09-14T16:33:55Z" level=debug msg="module.dns.azurerm_private_dns_zone.private: Creating..."
time="2022-09-14T16:34:27Z" level=debug msg="module.dns.azurerm_private_dns_zone.private: Creation complete after 33s [id=/subscriptions/d38f1e38-4bed-438e-b227-833f997adf6a/resourceGroups/ci-op-r0j51ij5-0e6bb-22jzf-rg/providers/Microsoft.Network/privateDnsZones/ci-op-r0j51ij5-0e6bb.ci.azure.devcluster.openshift.com]"
time="2022-09-14T16:34:27Z" level=debug msg="module.dns.azurerm_private_dns_zone_virtual_network_link.network: Creating..."
time="2022-09-14T16:54:51Z" level=error msg="Error: creating/updating Virtual Network …
```
=> OCPBUGS-927: azure: add sleep between zone and link creation

pkg/types/aws/validation/platform.go, pkg/types/aws/validation/platform_test.go
openshift/api defines a limit for user tags, and this sets our validation to be equal to that. It would be nice if we could vendor the limit, but the limit is set within kubebuilder markers, which are not easily digestable in the installer. Therefore, let's just set a constant value with a reference.
Also cleans up the validation code and adds a test.
/cc @rna-afk @TrilokGeer
=> aws user tags: set limit == openshift/api

pkg/agent/waitfor.go
It appears that installs of 4.12 are taking consistently longer to bootstrap than for 4.11 - a local test run recorded 28 minutes, vs. 17-20 minutes in previous 4.11 testing. In CI testing, we are exceeding the 30 minute timeout.
Until such time as we are able to determine and address the reason for the slower bootstrapping, increase the timeout.
=> Agent: Increase bootstrap-complete timeout

data/data/aws/bootstrap/main.tf, pkg/types/aws/validation/platform.go
Extend user tag limit to 15 based on AWS limits. 10 tags are reserved for OpenShift use. Previously, there has been a confusion on the tag limit for S3 bucket vs S3 bucket object tag limit. S3 bucket object tag limit is 10 while the requirement is for S3 bucket which has limit of 50 tags.
Reference : https://docs.aws.amazon.com/AmazonS3/latest/userguide/CostAllocTagging.html
As agreed with customer scenario, 4.11 limit with 15 user tags works. 4.12 will have the limitation extended to support 40 user tags.
=> OCPBUGS-759: Extend user tags limit to 25 based on AWS limits for 4.11 release

data/data/ibmcloud/network/dns/main.tf
Add a DNS Services DNS Record for Private clusters to allow traffic to the public server URL to be directed to the private LB.
=> CORS-2280: IBMCloud: Add DNS Record for internal public traffic

pkg/asset/installconfig/azure/validation_test.go
Instead, use the capabilities map to generate Azure types. It's much
easier to add capabilities to a simple string map and then have that
automatically converted to Azure API types. We also make sure that both
vmCapabilities and instanceTypeSku are always in sync.
=> azure: validation: avoid specifying capabilities twice
