openshift/installer

pkg/destroy/powervs/dhcp.go, pkg/destroy/powervs/power-instance.go, pkg/destroy/powervs/powervs.go
Delete named DHCP service for PowerVS
The DHCP service went from:
DHCPSERVER2dc32880758344f08c8ff6933e87d27a_Private to:
DHCPSERVERrdr-maocp-lon06-hszgr_Private
in order to support multiple clusters in a zone.  Therefore, we need to delete only a specific DHCP service.
=> powervs-delete-named-dhcp

data/data/aws/bootstrap/main.tf
This fixes the following warning message
DEBUG Warning: Argument is deprecated
DEBUG
DEBUG   with aws_s3_bucket_object.ignition,
DEBUG   on main.tf line 68, in resource "aws_s3_bucket_object" "ignition":
DEBUG   68:   bucket = aws_s3_bucket.ignition.id
DEBUG
DEBUG Use the aws_s3_object resource instead
by using `aws_s3_object` instead of `aws_s3_bucket_object`.
=> aws: replace deprecated object in terraform config

pkg/types/gcp/validation/platform.go
Add me-west1 GCP region that was not previously listed as base regions for the installer to use.
The installer was able to create the cluster and tear it down when this region was selected and QE did the validation for the region
[https://issues.redhat.com/browse/CORS-2294](https://issues.redhat.com/browse/CORS-2294)
=> GCP: Add me-west1 region

pkg/asset/installconfig/aws/subnet.go, pkg/destroy/aws/aws.go
When looking at the subnet code I noticed the comment `// FIXME: port to DescribeSubnetsPagesWithContext once we bump our vendored AWS package past v1.19.30`. So I did it.
=> AWS: resolve subnet-related FIXMEs

pkg/destroy/vsphere/vsphere.go
With the addition of vsphere zonal there
can and will be more than one folder in `folderMoList`. Adding a loop to delete all the folders.
=> OCPBUGS-1489: [vsphere] Loop over all folders for destroy

docs/user/agent/network-type-cni-plugin-selection.md, pkg/asset/agent/manifests/agentclusterinstall.go, pkg/asset/agent/manifests/agentclusterinstall_test.go, pkg/asset/agent/manifests/util_test.go
The IgnitionConfig NetworkType value should be transferred to
the AgentClusterInstall. This will allow the installed cluster
to have the correct network type installed. Currently, the
installed cluster defaults to OpenShiftSDN even if the
NetworkType is set to OVNKubernetes.
If the NetworkType is unspecified, the value is defaulted to
the IgnitionConfig's default value: OpenShiftSDN. A message
is logged to the console indicating that the value was unspecified
and defaulted to OpenShiftSDN.
=> AGENT-325 Set NetworkType in AgentClusterInstall

hack/go-lint.sh
go-lint.sh outputs the following errors:
```
$ hack/go-lint.sh $(go list -f '{{ .ImportPath }}' ./...)
./hack/go-lint.sh: 5: golint: not found
```
AFAIK, golint does not exist in docker.io/golang-1.15 or later. So, the script uses the image of origin-release before commit 2c09bc5.
=> hack: Use golang-1.16 image of origin-release

pkg/asset/agent/image/ignition.go
This depends on the AdminKubeConfigSignerCertKey, which we also pass, with the result that AdminKubeConfigClientCertKey always gets regenerated by the installer when assisted-service runs it. Since this has no effect other than generating a spurious warning, just stop passing it.
=> Agent: Don't pass AdminKubeConfigClientCertKey

data/data/agent/files/usr/local/bin/set-node-zero.sh.template
motd and issue indicate whether the host is the rendezvous host.
The rendezvous host's IP address is displayed.
Signed-off-by: Richard Su <rwsu@redhat.com>
=> AGENT-309 Display the rendezvous IP in motd and issue

pkg/asset/agent/image/ignition.go
The rendezvous host IP (node0 IP) can be specified in the agent-config.yaml or automatically chosen from the NMStateConfigs.
The IP address is logged at INFO level to help users know which host has been chosen as the rendezvous host.
Signed-off-by: Richard Su <rwsu@redhat.com>
=> AGENT-288 Log rendezvous host IP when creating agent ISO

pkg/asset/installconfig/platformprovisioncheck.go
`ValidateMultiZoneForProvisioning` is calling `ValidateForProvisioning` [here](https://github.com/openshift/installer/blob/2d0389c782601cd76e9b6454aee657c1c274a26b/pkg/asset/installconfig/vsphere/validation.go#L66-L72) already so it can be skipped in `platformprovisioncheck.go`
=> vsphere: prevent duplicate validation check in multi-zone

pkg/asset/agent/image/ignition.go, pkg/asset/agent/image/ignition_test.go, pkg/asset/agent/manifests/agent.go, pkg/asset/agent/manifests/nmstateconfig_test.go
when there are no nmstateconfigs defined.
When DHCP is used, agent-config.yaml may have no networkConfigs defined, and therefore no nmstateconfigs will be generated. When nmstateconfigs are absent, the pre-network-manager-config systemd service should not be enabled.
=> OCPBUGSM-47737: Do not enable pre-network-manager-config.service

images/libvirt/Dockerfile.ci
Found recent failure in CI with incorrectly downloaded yq 
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-multiarch-master-nightly-4.12-ocp-e2e-sdn-remote-libvirt-ppc64le/1567624076510367744#1:build-log.txt%3A34-40 
cc @r4f4
=> Verifying yq is installed properly in libvirt installer containers

pkg/asset/installconfig/azure/client.go, pkg/asset/installconfig/azure/mock/azureclient_generated.go, pkg/asset/installconfig/azure/validation.go, pkg/asset/installconfig/azure/validation_test.go
Validate that the the VM family is not standardDDv5Family. This family of
confidential machines will be supported in a future release.
https://bugzilla.redhat.com/show_bug.cgi?id=2055247
=> bug 2055247: pkg/asset/installconfig/azure: standardDDv5Family is not currently supported

data/data/agent/files/usr/local/share/assisted-service/assisted-service.env.template
Ensure that in telemetry data we can distinguish between the ephemeral agent-based installer and the hosted assisted installer.
=> AGENT-365: Set install invoker to "agent-installer"

pkg/asset/agent/image/baseiso.go, pkg/asset/agent/image/cache.go, pkg/asset/agent/image/oc.go
For the base ISO that is cached, it needs to be verified that it matches the one in the release payload. This change first checks the sha256 hash in the rhcos.json file embedded in the installer. If that doesn't match the cached file it extracts the coreos-x86-64.iso.sha256 file from the release payload and compares that.  If neither match then a new iso will be retrieved from the release payload or downloaded.
=> OCPBUGS-816: Check that cached base ISP matches hash in release payload

pkg/types/agent/agent_config_type.go, pkg/types/agent/conversion/agentconfig.go, pkg/types/agent/conversion/agentconfig_test.go
We expect to add more fields to the agent-config file in the future (thus it is not time for v1 yet), but it will now appear in the 4.12 release and thus must be kept stable. Change the version to v1beta1.
Existing configs with version v1alpha1 will continue to work.
=> AGENT-319: Set agent-config version to v1beta1

pkg/asset/agent/installconfig.go, pkg/asset/agent/installconfig_test.go
Validate `Networking.NetworkType` is set as `OVNKubernetes` for SNO clusters in install-config.yaml
=> AGENT-364: Validate  network type for SNO clusters

data/data/agent/files/etc/motd, data/data/agent/files/usr/local/bin/agent-gather
This script aims to allow the user to gather useful troubleshooting data in those cases in which things went wrong even before the API services are available.
=> AGENT-354: script for gathering install data

pkg/asset/agent/installconfig.go, pkg/asset/agent/manifests/common.go, pkg/asset/agent/manifests/infraenv.go, pkg/asset/agent/manifests/infraenv_test.go, pkg/asset/agent/manifests/nmstateconfig.go, pkg/asset/agent/manifests/nmstateconfig_test.go
We don't want to require that the user provided the same (or, indeed,
any) name for the AgentConfig as for InstallConfig. So if NMStateConfig
is generated from the AgentConfig, use the cluster name from the
InstallConfig to do it.
Ideally if the user provided ZTP manifests *and* an AgentConfig, we
could generate just the NMStateConfig asset from the AgentConfig and
have the name match the one that appears in the InfraEnv. However, that
is not possible because it would entail a dependency between two
resources (NMStateConfig and InfraEnv) generated by the same command
(agent create cluster-manifests).
If no InstallConfig is provided, we will fall back to the default
cluster name "agent-cluster".
=> Bug 2116904: Base generated NMStateConfig on InstallConfig name

data/data/gcp/cluster/dns/base.tf, data/data/gcp/cluster/dns/variables.tf, data/data/gcp/cluster/main.tf, data/data/gcp/variables-gcp.tf, data/data/install.openshift.io_installconfigs.yaml, pkg/asset/cluster/tfvars.go, pkg/asset/installconfig/gcp/client.go, pkg/asset/installconfig/gcp/mock/gcpclient_generated.go, pkg/asset/installconfig/gcp/validation.go, pkg/asset/installconfig/gcp/validation_test.go, pkg/asset/manifests/dns.go, pkg/tfvars/gcp/gcp.go, pkg/types/gcp/platform.go
**Install config added the public and private managed zones under platform/gcp
**Install config validate the public and private managed zones (if provided) - when
empty or "None" the validation does not occur.
** Added tests for install config
https://issues.redhat.com/browse/CORS-2040
=> CORS 2040: [gcp] Adding Public and Private Managed zones

pkg/asset/agent/agentconfig/agent_config.go
The YAML emitted by `openshift-install agent create agent-config-template` is invalid, this fixes it as follows:
- indent rootDeviceHints.deviceName
- mark comment correctly
=> fix agent-config-template emitted by `agent create`

data/data/install.openshift.io_installconfigs.yaml, pkg/asset/installconfig/powervs/validation_test.go, pkg/types/installconfig.go, pkg/types/powervs/defaults/platform.go
The default CIDR for PowerVS has always been 192.168.0.0/24. However, this was only recently enforced by PowerVS.
=> Change PowerVS default machine CIDR

pkg/destroy/powervs/dhcp.go
The \n adds an extra blank line in the debug output.  It would be nice if this was removed.
=> Remove extra blank line in DHCP debugging

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.12 boot image metadata in the installer which includes the fixes for the following BZs:
OCPBUGS-1429 get updated rpm-ostree in 4.12 bootimages
```
$ plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --url https://rhcos.mirror.openshift.com/art/storage/releases --no-signatures x86_64=412.86.202209220614-0 aarch64=412.86.202209220538-0 s390x=412.86.202209220613-0 ppc64le=412.86.202209220618-0
```
=> OCPBUGS-561: bump RHCOS 4.12 bootimage metadata

pkg/asset/agent/agentconfig/agent_config.go, pkg/asset/agent/agentconfig/agent_config_test.go
This patch adds two new validations for the agent-config file to ensure that the configured mac addresses are not duplicated.
Additionaly, tests have been refactored to improve (hopefully) the readability and to make it easier adding new cases.
=> AGENT-264: validate agent-config macs

pkg/asset/manifests/network.go, pkg/asset/manifests/ovnkubeconfig.go
we rely on an explicitly-configured host route, and the default OVNKube routing ignores this. as a result, packets aren't routed to the right internal gateway.
=> powervs: introduce manifest for OVNKubernetes configuration

pkg/asset/machines/master.go, pkg/asset/machines/worker.go
Fix the issue when there are no zones
set in the machinepool for control plane
and workers.
This should also handle if there are
more replicas required than FailureDomains.
=> OCPBUGS-1490: [vsphere-zones] Handle no set zones

images/installer/Dockerfile.upi.ci.rhel8
Changes based on the latest instructions from
https://cloud.google.com/sdk/docs/install#rpm and
https://cloud.google.com/sdk/crypto
=> images: UPI: update gcloud install on rhel8 container

data/data/aws/cluster/vpc/vpc-public.tf
Hopefully by making the dependency between them explicit, we might alleviate the following error in CI
Error: error creating EC2 NAT Gateway: InvalidElasticIpID.NotFound: The elasticIp ID 'eipalloc-094ec9d0482d5b9f2' does not exist
=> OCPBUGS-891: aws: add explicit EIP dependency for nat gw

data/data/agent/systemd/units/assisted-service-db.service, data/data/agent/systemd/units/assisted-service-pod.service, data/data/agent/systemd/units/assisted-service.service.template
Testing in a real lab shows that it takes 333s for assisted-service-pod and 293s for assisted-service and assisted-service-db to start up (this is due to the time taken to pull the images). Set the timeouts so that this generally should not happen.
=> Increase start timeouts for assisted services

pkg/agent/validations.go, pkg/agent/validations_test.go
Moving these to the debug level because a validation can resolve on its own. Leaving it at the error level confuses the customer, this is more of a debugging feature for the customer.
[AGENT-321](https://issues.redhat.com//browse/AGENT-321)
=> AGENT-321: Move validation failures to debug log level

data/data/agent/files/usr/local/bin/agent-gather
Any host-config failures are written to the file
/var/run/agent-installer/host-config-failures and we will want to see this output in the event that we need to debug an installation.
=> Add host-config status to agent-gather

pkg/asset/agent/installconfig.go, pkg/asset/agent/installconfig_test.go
Platform should be set to none
if the ControlPlane.Replicas is 1
and total number of Compute.Replicas is 0
=> AGENT-369: SNO validation

pkg/asset/agent/image/agentimage.go
Currently whenever the `agent create image` command fails for any reason (usually a configuration error), a pretty technical and not very user-friendly message is reported.
This patch aims to provide a better message for the end user. The output will look like the following:
```
...
ERROR failed to write asset (Agent Installer ISO) to disk: cannot generate ISO image due some configuration errors 
...
=> OCPBUGS-527: Improve error message in case of failure during the agent image generation

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.10 boot image metadata in the installer which includes the fixes for the following:
OCPBUGS-1938 Booting live ISO: /dev/sr0 already mounted or mount point busy
```
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --no-signatures --url https://rhcos.mirror.openshift.com/art/storage/releases x86_64=410.84.202210040010-0 aarch64=410.84.202210040011-0 s390x=410.84.202210040017-0 ppc64le=410.84.202210040023-0
```
=> OCPBUGS-1936: bump RHCOS 4.10 bootimage metadata

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.11 boot image metadata in the installer which includes the fixes for the following:
OCPBUGS-1937 Booting live ISO: /dev/sr0 already mounted or mount point busy
OCPBUGS-565 Unable to install RHCOS 4.11.0-rc2-ppc64le on Bare-metal Power system
```
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --no-signatures --url https://rhcos.mirror.openshift.com/art/storage/releases x86_64=411.86.202210041459-0 aarch64=411.86.202210032347-0 s390x=411.86.202210032129-0 ppc64le=411.86.202210032141-0
```
=> OCPBUGS-562: bump RHCOS 4.11 bootimage metadata

pkg/asset/manifests/proxy.go
** Add 168.63.129.16 IP to noProxy in Azure Stack Hub 
** Add ArmEndpoint (from install config) when performing azure installation
https://issues.redhat.com/browse/OCPBUGSM-46450
=> Bug 2104997: Add additional fields to proxy manifest

pkg/asset/releaseimage/pullspec.go
This code-branch should be very rare, probably mostly internal testing.  A chattier line in those situations isn't a big user-experience concern, and including the pullspec makes it easier for folks who are trying to understand internal-test results to figure out which pullspec was being used.
The log line is originally from 456a373aed (#1910), and it was tweaked in cd0b70f992 (#2361), and neither of those make explicit arguments for why they didn't include the pullspec.
=> pkg/asset/releaseimage/pullspec: Include override pullspec in log message

data/data/azure/variables-azure.tf, data/data/azure/vnet/main.tf, data/data/azure/vnet/outputs.tf, pkg/asset/cluster/tfvars.go, pkg/asset/machines/azure/machines.go, pkg/asset/machines/azure/machinesets.go, pkg/asset/machines/master.go, pkg/asset/machines/master_test.go, pkg/asset/machines/worker.go, pkg/asset/machines/worker_test.go, pkg/asset/rhcos/release.go, pkg/tfvars/azure/azure.go
In order to support provisioning of arm64 bootimages, these need to be
created using the image gallery resource as they are not supported
through managed images. For this purpose, it would be good to unify the
implementation of x86 and arm64 to use image galleries as Microsoft have
said that it will be the supported way of creating bootimages going forward
for new instance types of new architectures.
This implementation would create one image gallery with two images: a
gen1 and a gen2 image which we would then pick appropriately based on
the VM generation.
xref: https://issues.redhat.com/browse/ARMOCP-16
=> azure: create bootimages using image gallery

pkg/asset/agent/installconfig.go, pkg/asset/agent/installconfig_test.go
With this PR we now first validate the install config via the installer's default validations and later do the additional validations for the agent installer.
=> OCPBUGS-1913: Agent Installer: Do not fail on deprecated apiVip and ingressVip values

pkg/asset/agent/image/ignition.go
Allow the 'core' user to log in to the agent ISO via the host console using the kubeadmin password for the cluster.
sshd in CoreOS is configured not to allow password authentication, so this doesn't allow the user to login via ssh without supplying their public key when building the image.
The password hash is not persisted to disk, so this does not allow users to log in to the installed OpenShift node after rebooting.
=> AGENT-349: Allow console login to Agent ISO

pkg/asset/agent/manifests/agentclusterinstall.go, pkg/asset/agent/manifests/agentclusterinstall_test.go, pkg/asset/agent/manifests/util_test.go
When install-config is configured to install a FIPS compliant OpenShift cluster, we need to generate the AgentClusterInstall object with a fips install-config overrides annotation.
=> AGENT-375: generate FIPS annotation for ACI

pkg/asset/agent/manifests/common.go, pkg/asset/agent/manifests/infraenv.go, pkg/asset/agent/manifests/infraenv_test.go, pkg/asset/agent/manifests/util_test.go
In order for the proxy config to make it to the installed cluster, it must make it into the infraenv that we then register in the assisted service API. This commit sees to it that if installConfig has the proxy section provided, it makes into the infraenv.
=> OCPBUGS-2029: Fix agent installation InstallConfig proxy processing

pkg/asset/installconfig/gcp/validation.go, pkg/asset/installconfig/gcp/validation_test.go, pkg/asset/installconfig/platformcredscheck.go
** The install config would fail immediately when the credentials were nil. There was no chance to set the Credentials Mode to Manual. Now the install config can be generated then the user can manually set the credentials mode to manual. ** More tests were generated for this functionality
=> OCPBUGS-1896: Validate Credentials Mode After Install Config step

pkg/types/vsphere/platform.go, pkg/types/vsphere/validation/platform.go, pkg/types/vsphere/validation/platform_test.go
add validation to require 'networks' be populated for multi-zone installs
=> OCPBUGS-1698: multi-zone network slice validation

data/data/bootstrap/bootstrap-in-place/files/opt/openshift/bootstrap-in-place/bootstrap-in-place-post-reboot.sh
Use `[*]` and not `[0]` in the BIP post-reboot `approve_csr` jsonpath
when counting ready nodes while approving CSRs, because the node
resource may not have been created yet.
This prevents the following harmless error message:
```
Sep 30 09:01:17 test.metalkube.org bootstrap-in-place-post-reboot.sh[2409]: Approving csrs ...
Sep 30 09:01:17 test.metalkube.org bootstrap-in-place-post-reboot.sh[3045]: error: error executing jsonpath "{.items[0].status.conditions[?(@.type==\"Ready\")].status}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
Sep 30 09:01:17 test.metalkube.org bootstrap-in-place-post-reboot.sh[3045]:         template was:
Sep 30 09:01:17 test.metalkube.org bootstrap-in-place-post-reboot.sh[3045]: …
```
=> OCPBUGS-1900: Avoid SNO bootstrap jsonpath error

docs/user/azure/install_upi_azurestack.md
This was added in https://github.com/openshift/cluster-version-operator/pull/821 to allow more featuresets and allow for a future migration to include actual gates. Because usage of this manifest would prevent upgrades, there are not upgrade concerns for this change.
=> update to release.openshift.io/feature-set to match OCP 4.12

data/data/powervs/cluster/power_network/pi_network.tf, pkg/types/powervs/powervs_regions.go
The 4.11 branch of the installer needs to support the zone mon01 in PowerVS for the CI
=> OCPBUGS-1242: Add PowerVS zone mon01 support

data/data/ibmcloud/network/vpc/security-groups.tf
Allow traffic from any source to the kube-api-lb apiserver for IBM Cloud. Private cluster traffic should already be restricted to be from within the VPC, via DNS Services, so removing the restriction it must also be from within the cluster's network as well.
Related: https://issues.redhat.com/browse/OCPBUGS-1856
=> OCPBUGS-1856: IBMCloud: Allow traffic to kube-api-lb

OWNERS_ALIASES
Removing jstuever from the OWNERS files so that pull requests continue to get assigned to two active reviewers.
=> Removing jstuever from OWNERS

pkg/types/openstack/validation/platform.go, pkg/types/openstack/validation/platform_test.go
The validation is no longer necessary now that we stopped using mDNS.
This aligns with other on-prem platforms.
Manual cherry-pick of https://github.com/openshift/installer/pull/6355/.
=> OCPBUGS-1737: OpenStack: Lift validation for 14 chars cluster names

docs/user/openstack/known-issues.md
Before this documentation patch, the known issue about soft-anti-affinity had several issues:
* it was in the UPI section, when it is not a UPI-specific issue
* it mentioned Control plane scale-out, when OCP only supports exactly 3 masters
* it is now possible to set strict anti-affinity from the install-config.yaml, and that should be the recommended solution when VM distribution across hosts is required.
=> OCPBUGS-2259: Fix soft-anti-affinity known issue

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template, data/data/bootstrap/files/usr/local/bin/bootstrap-verify-api-server-urls.sh, pkg/asset/ignition/bootstrap/common.go, pkg/gather/service/analyze.go, pkg/gather/service/analyze_test.go
During cluster bring up, when nodes are unable to resolve api-int, the cluster fails to come up and the messages in the logs, several times do not hint at any connectivity issues making it difficult to detect and resolve any infrastructure setup issues.
These changes contain:
1. Checks for the API and API-INT URLs to see if they are resolvable from the bootstrap node and logging helpful messages.
2. Records the state of the api-url and api-int-url services
3. Addition of validation of the API and API-INT URLs to the analyze output
=> Bug 2072202: Check for api and api-int resolution during cluster install

data/data/coreos/rhcos.json
OCPBUGS-1505 Booting live ISO: /dev/sr0 already mounted or mount point busy
```
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --no-signatures --url https://rhcos.mirror.openshift.com/art/storage/releases x86_64=412.86.202209302317-0 aarch64=412.86.202210031918-0 s390x=412.86.202209302317-0 ppc64le=412.86.202209302326-0
```
=> OCPBUGS-1941: bump RHCOS 4.12 bootimage metadata

data/data/install.openshift.io_installconfigs.yaml, pkg/types/gcp/platform.go
** Update the comments/explain docs for the public and private DNS zone in the install config.
=> OCPBUGS-2262: Update gcp explain for DNS zones

pkg/asset/machines/alibabacloud/machinesets.go
Not all zone IDs are connected using "-", such as the availability zone ID `ap-southeast-6a` mentioned above, and the `ap-southeast-6` is region ID.
=> Bug 2059491: [Alibaba] fix the format of Name

pkg/asset/cluster/gcp/gcp.go, pkg/destroy/gcp/cloudresource.go, pkg/destroy/gcp/firewall.go, pkg/destroy/gcp/gcp.go, pkg/types/gcp/metadata.go
** Adding NetworkProjectID to the Metadata so that it can be used to find resources on destroy. ** Added project name to the cloud resources so that the project where the resource was discovered is tracked ** Use the cloud resource project field to find all firewall rules when a network project ID was specified.
=> OCPBUGS-2301: Search Network Project For resources

cmd/openshift-install/create.go
Reverts openshift/installer#6124
Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.
This has been affecting almost every CI and nightly payload since last night:
1. [4.12.0-0.ci-2022-10-20-074427](https://amd64.ocp.releases.ci.openshift.org/releasestream/4.12.0-0.ci/release/4.12.0-0.ci-2022-10-20-074427)
2. [4.12.0-0.nightly-2022-10-20-015716](https://amd64.ocp.releases.ci.openshift.org/releasestream/4.12.0-0.nightly/release/4.12.0-0.nightly-2022-10-20-015716)
3. [4.12.0-0.nightly-2022-10-19-205630](https://amd64.ocp.releases.ci.openshift.org/releasestream/4.12.0-0.nightly/release/4.12.0-0.nightly-2022-10-19-205630)
The …
=> Revert "create: add check for cluster operator stability"

pkg/asset/installconfig/gcp/validation.go
Without this, the installation wil lfail without any worker machines launched.
=> OCPBUGS-1704: Service Usage API is required, not optional

data/data/agent/systemd/units/create-cluster-and-infraenv.service.template
The create-cluster-and-infraenv.service "Requires" assisted-service.service, this will make it be deactived when assisted-service.service fail to start. When assisted-service.service restarts, sinece create-cluster-and-infraenv.service was deactived, it will not restart automatically. Therefore, it is better to use "Wants=", it is a weaker version of Requires, and the dependency failure will not affect the dependent. https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Requires=
=> OCPBUGS-1824: enhance agent systemd service dependency

pkg/asset/agent/installconfig_test.go, pkg/types/baremetal/defaults/platform.go
If we fail to look up the API VIP in DNS, there is nowhere to return the
error. Previously we were setting the error message as
the default value, which resulted in a pretty horrible-looking error:
[platform.baremetal.apiVIPs: Invalid value: []string{"DNS lookup failure: lookup api.test-cluster.test-domain on 10.0.80.11:53: no such host"}: ip <nil> is invalid, platform.baremetal.apiVIPs: Invalid value: "DNS lookup failure: lookup api.test-cluster.test-domain on 10.0.80.11:53: no such host": "DNS lookup failure: lookup api.test-cluster.test-domain on 10.0.80.11:53: no such host" is not a valid IP, platform.baremetal.apiVIPs: Invalid value: "DNS lookup failure: lookup api.test-cluster.test-domain on 10.0.80.11:53: no such host": IP expected to be in one of the machine networks: …
=> OCPBUGS-2338: Don't use error messages as default values

pkg/asset/agent/agentconfig/agent_config.go, pkg/asset/agent/agentconfig/agent_config_test.go, pkg/asset/agent/manifests/infraenv.go, pkg/asset/agent/manifests/infraenv_test.go, pkg/asset/agent/manifests/util_test.go, pkg/types/agent/agent_config_type.go
In Agent based installation ZTP input, one can provide AdditionalNTPSources in InfraEnv. The sources configured there are merged by assisted-service with those that are provided by DHCP option 42 (According to RFC 2132) and provided to the openshift-install that assisted-service runs as MachineConfigs for the different roles defined for the cluster nodes.
This commit closes the gap we had when installing from install-config + agent-config.
=> OCPBUGS-2627: agent-config: Generate missing AdditionalNTPSources in InfraEnv

pkg/agent/cluster.go, pkg/agent/kube.go, pkg/agent/validations.go, pkg/agent/validations_test.go, pkg/agent/waitfor.go
This rework is to change the output for the cluster and host validations.
After querying the API, for each validation ID check the message against the most recent message received for that ID:
- If the message is unchanged, do nothing
- If the new message is a failure, log it at warning level
- If the new message is a success but there has previously been a failure, log it at info level
- If the new message is a success and this is the first report for that validation, log it at debug level
We won't log anything at error level because no validation in assisted prior to the install starting is ever final. The only error comes when we hit our timeout. 
To help with review [the struct coming from the Assisted API](https://github.com/openshift/assisted-service/blob/master/api/common/common_typ …
=> Agent-321: Cluster and Host validations rework

pkg/asset/agent/installconfig.go, pkg/asset/agent/installconfig_test.go
Log warnings for the irrelevant config data provided in install-config.yaml for the agent-based installer.
To Test, run 
`/usr/local/go/bin/go test -timeout 30s -run ^TestInstallConfigLoad/valid_configuration_for_baremetal_platform_for_HA_cluster_-_deprecated_and_unused_fields$ github.com/openshift/installer/pkg/asset/agent -v`
The test will print the warnings and the config data ignored.
=> AGENT-348: Warn when information in install-config is ignored

pkg/types/azure/validation/disk.go, pkg/types/azure/validation/disk_test.go
Current validation excludes upper-case letters. I expanded the test suite to cover some of the ugliest (legitimate) names possible.
=> OCPBUGS-2895: Azure: Fix DiskEncryptionSet regex validation

data/data/azure/vnet/main.tf
Although the gen v1 image will never be used for arm64 VMs (they are all gen2), set the appropriate architecture, so the appropriate architecture image is created.
=> OCPBUGS-2144: Azure: Set appropriate architecture for gen v1 image

pkg/agent/rest.go
The result returned from the List function should be used after checking err.
=> OCPBUGS-3018: Use result from List function after checking error

pkg/asset/agent/image/ignition.go, pkg/asset/agent/image/ignition_test.go, pkg/asset/agent/manifests/nmstateconfig.go, pkg/asset/agent/manifests/nmstateconfig_test.go
This patch allows to specify multiple documents in the same yaml file when when used as an extra manifest for the agent installer.
=> OCPBUGS-1033: support multiple documents in the same extra manifest file

images/installer-artifacts/Dockerfile.rhel
There are now ARM workstations available, and possibly more commonly, RHEL9/Fedora/etc. ARM VMs can run on ARM Macs, and these may be used to create and manage x86 clusters.
=> Add linux/arm64 binary to installer-artifacts

data/data/powervs/cluster/dns/dns.tf, data/data/powervs/cluster/dns/templates/cloud-init.yaml.tpl, data/data/powervs/cluster/dns/variables.tf, data/data/powervs/cluster/main.tf, data/data/powervs/cluster/vpc/variables.tf, data/data/powervs/cluster/vpc/vpc.tf, data/data/powervs/variables-powervs.tf, pkg/asset/cluster/tfvars.go, pkg/asset/installconfig/powervs/client.go, pkg/asset/installconfig/powervs/metadata.go, pkg/asset/installconfig/powervs/mock/powervsclient_generated.go, pkg/asset/installconfig/powervs/session.go, pkg/destroy/powervs/publicgateway.go, pkg/tfvars/powervs/powervs.go
In the private and disconnected scenarios, if you deploy with either an existing public gateway or the VPC already in the permitted networks of the DNS service, terraform will fail. This PR adds logic to create these resources only when needed. Much of the client code is lifted from IBM Cloud's client.go and adapted to work with our minor differences.
=> OCPBUGS-2290: Power VS Check for existing DNS permitted network and public gateway

data/data/install.openshift.io_installconfigs.yaml, pkg/types/gcp/platform.go, pkg/types/validation/installconfig.go, pkg/types/validation/installconfig_test.go
** Require the Tech preview feature to be set in the install config when the platform.gcp.createFirewallRules is set to any value other than the default ("Enabled").
Linked to #6522
=> OCPBUGS-2966: Add GCP CreateFirewallRules to tech preview

go.mod, go.sum, vendor/github.com/gophercloud/gophercloud/.zuul.yaml, vendor/github.com/gophercloud/gophercloud/CHANGELOG.md, vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/nodes/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/nodes/results.go, vendor/github.com/gophercloud/gophercloud/openstack/baremetal/v1/nodes/urls.go, vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/results.go, vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/rules/results.go, vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/results.go, vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/orchestration/v1/stacks/requests.go, vendor/github.com/gophercloud/gophercloud/provider_client.go, vendor/modules.txt
Update the pin to gophercloud v0.18.0 so that we get a fix that came
with https://github.com/gophercloud/gophercloud/pull/2160.
Also use a replacement for tencentcloud-sdk-go as they removed their
tags and broke all downstream projects in the process
(https://github.com/hashicorp/terraform#29021). This is needed in
order to run `go mod vendor`.
=> OCPBUGS-2795: Bump gophercloud

pkg/asset/manifests/vsphere/infrastructure.go
Testing of https://github.com/openshift/cluster-config-operator/pull/269 revealed an issue with validation of the datastore path as provided by the installer in the infrastructure manifest.
=> OCPBUGS-2758: Provide datastore as full path

pkg/asset/cluster/tfvars.go, pkg/asset/machines/gcp/machines.go, pkg/types/validation/installconfig.go, pkg/types/validation/installconfig_test.go
3bac80b688cfc9cca4f10cca612235cc5bbe24d9: adds feature gate protection to install config fields for projects for DNS zones
39c8e9f6a4498cb5070ceec82e4ebdfdb6a62f77: we should only passthrough service accounts when doing an XPN install
=> OCPBUGS-2847: GCP XPN Featuregates

pkg/asset/installconfig/platformcredscheck.go
Fixing a typo in the CredentialsMode check.
=> OCPBUGS-3110: azure: Fix client certs authentication

pkg/asset/installconfig/gcp/validation.go
** Private DNS Zone needs to use project during validation lookup after it is found instead of using the Platform Project ID.
=> OCPBUGS-2911: Use project after creation

hack/build.sh
While the installer binary is statically linked, the terraform binaries shipped with it are dynamically linked.
This could give issues when running the installer on Linux and depending on the GLIBC version the specific Linux distribution has installed. It becomes a risk when switching the base image of the builders from ubi8 to ubi9 and trying to run the installer in cs8 or rhel8.
For example, building the installer on cs9 and trying to run it in a cs8 distribution leads to:
```
time="2022-10-31T14:31:47+01:00" level=debug msg="[INFO] running Terraform command: /root/test/terraform/bin/terraform version -json"
time="2022-10-31T14:31:47+01:00" level=error msg="/root/test/terraform/bin/terraform: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by …
```
=> OCPBUGS-3096: Static linking the terraform and providers binaries

pkg/asset/agent/manifests/agentclusterinstall.go, pkg/asset/agent/manifests/agentclusterinstall_test.go, pkg/asset/agent/manifests/common.go, pkg/asset/agent/manifests/util_test.go
Dual stack VIPs were ignored, taking only the first in the list whichever address family the second addresses were. This PR makes the 4.12 dual stack VIPs functionality work with agent based installer by
leveraging the installconfig overrides escape hatch.
=> OCPBUGS-3287: agent ased installation fix for dual stack vips

pkg/asset/installconfig/gcp/validation.go, pkg/asset/installconfig/gcp/validation_test.go
We were only printing a warning in case Service Usage was missing and proceeding with the installation. However, that service is required by the CCO and the deployment would end up failing later on.
Instead, let's fail during install-config validation time so users can enabled the service before proceeding.
=> OCPBUGS-1704: gcp: fail during validation if service usage is not enabled

data/data/install.openshift.io_installconfigs.yaml, data/data/vspherezoning/bootstrap/main.tf, data/data/vspherezoning/master/main.tf, pkg/tfvars/vsphere/vsphere.go, pkg/types/vsphere/platform.go, pkg/types/vsphere/validation/platform.go, pkg/types/vsphere/validation/platform_test.go, terraform/providers/vsphereprivate/resource_vsphereprivate_import_ova.go
- Adds length check for folderPath split
- Only create a folder when folder name is empty
- Add additional validation for resource pools and folders
- In the vsphereprivate terraform provider support
the ability to use folders as full paths
- In terraform trimprefix of the folder path based on
`/<datacenter>/vm`
=> OCPBUGS-1627: [vsphere-zones] Fix user folders

pkg/asset/agent/installconfig.go, pkg/asset/agent/installconfig_test.go, pkg/types/validation/installconfig.go
With this fix, the agent installer's image creation command will fail if some other arch except amd64 is configured.
For example, when control plane and compute architecture in `install-config.yaml`
is set to `arm64`, the command `openshift-install agent create image` will fail with
```
FATAL failed to fetch Agent Installer ISO: failed to load asset "Install Config":
invalid install-config configuration: 
[ControlPlane.Architecture: 
Unsupported value: "arm64": 
supported values: "amd64", 
Compute[0].Architecture: 
Unsupported value: "arm64": 
supported values: "amd64"]
```
=> OCPBUGS-2841: (AGENT) only support amd64 archs

pkg/asset/agent/image/ignition.go
The ICSP may contain multiple mirrors for the release image. In some cases this may even be necessary: if the environment in which the Agent ISO is generated is disconnected, such that the CoreOS ISO must be extracted from a particular mirror, and the cluster is to be installed in a _different_ disconnected environment with a different mirror, then two mirror options must be specified to allow both the ISO generation and the eventual installation to work.
However, assisted-service accepts only a single mirror in its config. It uses this single mirror to extract the installer binary and get other information, such as the release version. This must be the mirror that is accessible in the cluster environment.
Previously we used the last matching mirror for this. It seems easier to document …
=> OCPBUGS-3304: Always use first matching mirror in assisted-service

data/data/agent/files/usr/local/bin/start-cluster-installation.sh.template, pkg/agent/cluster.go
In https://github.com/openshift/installer/pull/6470 we detected a failure when the cluster state moves back to Ready after an installation has been initiated. This adds an automatic retry when that condition occurs. It will help resolve issues like https://issues.redhat.com/browse/OCPBUGS-3280 and, in general, any problems that cause a cluster prepare failure.
=> OCPBUGS-3280: Automatically retry install

pkg/asset/installconfig/gcp/validation.go, pkg/asset/installconfig/gcp/validation_test.go
There are a few services that are not required for the installer to run but are now causing the installer to fail if the permission is not provided. Adding an optional set of permissions and warn the user if these permissions are not provided.
List of required services:
compute - used for creating VMs
cloudresourcemanager - used for updating metadata for resources iam, iamcredentials - used for creating iam accounts serviceusage - used for listing and managing APIs
=> Bug 2099604: Remove optional services from permissions check

pkg/asset/agent/manifests/agentclusterinstall.go, pkg/asset/agent/manifests/agentclusterinstall_test.go
To create cluster wide proxy, proxy entries must be made in the agent-cluster-install.yaml. This commit will ensure that if the installConfig has the proxy section provided, it must be present into the agent-cluster-install.yaml.
=> OCPBUGS-3382: Fix cluster wide proxy

pkg/asset/installconfig/ibmcloud/validation.go, pkg/asset/installconfig/ibmcloud/validation_test.go
Confirm the specified Availability Zones, if any, properly map to the specified BYON Subnets, if any, on IBM Cloud. This confirms the specified values match and can be properly used during Control Plane and/or Compute deployments.
Related: https://issues.redhat.com/browse/OCPBUGS-3186
=> OCPBUGS-3186: IBMCloud: Confirm Zones and BYON Subnets

docs/user/customization.md
Signed-off-by: Eran Cohen <eranco@redhat.com>
=> docs: fix broken link to default kubelet.service taint

hack/build.sh
Debugging the following error on ppc64le: 
```
+ go build -mod=vendor -ldflags ' -X github.com/openshift/installer/pkg/version.Raw=v4.10.0 -X github.com/openshift/installer/pkg/version.Commit=f3c53b382264bdebfc31235adcfbfa1718f4a305 -X github.com/openshift/installer/pkg/version.defaultArch=ppc64le -s -w' -tags ' release' -o bin/openshift-install ./cmd/openshift-install
github.com/aliyun/alibaba-cloud-sdk-go/services/cms.(*Client).DescribeMonitoringAgentHostsWithChan.func1: direct call too far: runtime.duffzero+1f0-tramp0 -2000068
Error: error building at STEP "RUN DEFAULT_ARCH="$(go env GOHOSTARCH)" hack/build.sh": error while running runtime: exit status 2
```
=> OCPBUGS-3743: build: change ppc64le linking mode

images/installer/Dockerfile.upi.ci, images/installer/Dockerfile.upi.ci.rhel8
add ibmcloud cli to image , it would be used when pre-configuring some resources (e.g. VPC, bastion host, etc.) before launching an OCP cluster with customization.
=> add ibmcloud cli to image

pkg/destroy/openstack/openstack.go
Some OpenStack object storages respond with `204 No Content` to list requests when there are no containers or objects to list. In these cases, when responding to requests with an `Accept: text/plain` or no `Accept` header, some object storages omit the `content-type` header in their status-204 responses.
Now, Gophercloud throws an error when the response does not contain a `content-type` header.
With this change, we work around the issue by forcing Gophercloud to request a JSON response from the object storage when listing containers. When passed an `Accept: application/json` header, the server responds with `200 Ok` and a `content-type` header in our tests.
This solution gives us a fix that is easily backportable because it doesn't require any dependency bump.
Note that in my local …
=> OCPBUGS-3933: OpenStack: Force JSON content-type in Swift

data/data/agent/systemd/units/create-cluster-and-infraenv.service.template
As described in https://issues.redhat.com/browse/OCPBUGS-3277, there have been occasional failures in the create-cluster-and-infraenv service due to the agentbasedinstaller being unable to retrieve the release image. This changes to the service to allow a retry on failure.
=> OCPBUGS-3277: Restart create-cluster-and-infraenv.service if it fails

pkg/asset/agent/installconfig.go, pkg/types/baremetal/validation/platform.go
For the agent-based installer, do not require the host data in the platform bare metal section in installconfig as it is unused by the agent installer. If still provided, a warning is issued to the user that the data is ignored.
=> OCPBUGS-3278: (Agent) Do not require host data in platform baremetal section in installconfig

images/installer/Dockerfile.upi.ci, images/installer/Dockerfile.upi.ci.rhel8
1. ibmcloud installed in /usr/local/bin, the env PATH just has /bin, need mv it. 
2. echo "-4" > ./.curlrc help resolving the download ibmcloud cli error
> Error: Get "https://download.clis.cloud.ibm.com/ibm-cloud-cli-plugin/cloud-internet-services/1.14.9/cloud-internet-services-linux-amd64-1.14.9": dial tcp [2600:1408:c400:21::17d4:fb48]:443: connect: network is unreachable
3.HOME=/output before ibmcloud download to resolve the issue of  no  ibmcloud plugin in release test.
=> mv ibmcloud to /bin folder

pkg/asset/machines/azure/machines.go
In 4.12 we switched Azure to use compute image galleries. ASH is still using managed images, but we forgot to account for that in the machine sets. This updates ASH to continue to use managed images in the machineset.
Still testing this locally, but want to post it to see some CI.
=> OCPBUGS-2931: Azure Stack: use managed images for compute nodes

data/data/agent/files/usr/local/bin/agent-gather, data/data/agent/systemd/units/agent.service.template, pkg/asset/agent/image/ignition.go, pkg/asset/agent/image/ignition_test.go, pkg/asset/agent/manifests/agentpullsecret.go, pkg/asset/agent/manifests/agentpullsecret_test.go, pkg/asset/agent/manifests/infraenv_test.go, pkg/asset/agent/manifests/util_test.go
The agent-gather output should not contain the user's pull secret. Redact it from `/etc/assisted/manifests/pull-secret.yaml`.
=> OCPBUGS-3405: Redact pull secret from agent-gather

data/data/azure/vnet/main.tf
In the transition from v2 to v3 of the azurerm terraform provider, not only was an option renamed from `allow_blob_public_access` to `allow_nested_items_to_be_public` but its default value was also changed from `false` to `true` [1].
So to restore the previous access setting for the RHCOS Storage Account, we need to explicitly set the new option to `false`.
Thanks Jinyun Ma for pointing this out.
[1] https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md#300-march-24-2022
=> OCPBUGS-3524: data: azurerm: restore RHCOS SA access configuration

images/installer/Dockerfile.upi.ci, images/installer/Dockerfile.upi.ci.rhel8
in release test ibmcloud fail to use. 
$ibmcloud
FAILED
Configuration error: mkdir /output/.bluemix/plugins: permission denied
=> [ibmcloud] ibmcloud plugin "permission denied"

pkg/asset/agent/image/oc.go
The execute() function was not returning an error properly, which allowed failures of the 'oc' command, such was when using an older version of 'oc' that did not support the --icsp-file param.
=> OCPBUGS-4355: Fix return value from execute()

data/data/bootstrap/systemd/units/release-image-pivot.service.template
This solves a race between release-image-pivot and bootkube on firstboot. While manifests are being generated pivot may reboot a machine, which may cause corrupted manifests. Instead in OKD bootkube should wait for pivot to be completed.
This service doesn't run on OCP and has no effect in OCP installs
=> OCPBUGS-3164: hold bootkube service until bootstrap has pivoted

pkg/asset/installconfig/gcp/validation.go, pkg/asset/installconfig/gcp/validation_test.go
We were only printing a warning in case Service Usage was missing and proceeding with the installation. However, that service is required by the CCO and the deployment would end up failing later on.
Instead, let's fail during install-config validation time so users can enable the service before proceeding.
=> [release-4.11] OCPBUGS-4325: gcp: fail during validation if service usage is not enabled

data/data/bootstrap/bootstrap-in-place/files/opt/openshift/bootstrap-in-place/bootstrap-in-place-post-reboot.sh, data/data/bootstrap/bootstrap-in-place/files/opt/openshift/bootstrap-in-place/master-update.fcc, pkg/asset/ignition/bootstrap/bootstrap.go, pkg/asset/ignition/bootstrap/common.go
#5258 introduced a mechanism to tell CVO to not manage some cluster resources,
as that management was creating races between bootkube and CVO.
In #5271, this mechanism was removed from bootstrap-in-place
installations.
The reason for the removal was because attempting to apply
`original_cvo_overrides.patch` after the cluster-bootstrap podman
container was done wasn't working, as in BIP by the time that that
container is down, there's no longer a running kube-apiserver apply the
patch on (unlike regular installations with a bootstrap node where the
API server keeps running on the actual nodes). The justification for
simply disabling the mechanism instead of finding a solution was based
on an incorrect assumption that "CVO doesn't even run in BIP pre-pivot
so there's no need to perform …
=> OCPBUGS-4125: Enable CVO unmanage overrides in bootstrap-in-place installations

pkg/asset/installconfig/platformprovisioncheck.go
Some switch branches were relying on the outer error variable but shadowing it with a local one whereas other branches were just returning right away in case of errors. Let's make them all consistent by returning the error and using `nil` explicitly at the end of the function to make it clear all validations passed at that point.
=> platformprovisioncheck: fix shadowing of `err` variable

data/data/powervs/bootstrap/vm/main.tf, data/data/powervs/cluster/master/vm/main.tf
At the moment, it is not possible to verify the target VM has fully booted up in the current setup. Therefore, we just need to find the optimal wait time before assuming it's up and proceeding further in the install automation.
=> Wait longer for VM to obtain IP from DHCP in PowerVS

terraform/providers/vsphereprivate/resource_vsphereprivate_import_ova.go
Zonal uses the full absolute path for cluster
in the OVA import. In the existing terraform
the relative path is used.
If `cluster` is a path use that string
otherwise generate it from the datacenter and cluster name (which was the existing method)
=> OCPBUGS-2130: import ova resource cluster path fix

data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template, pkg/asset/ignition/bootstrap/common.go
We were previously only seting this for workers but its also needed on the master nodes to ensure both networks are ready before ovnkube-node starts.
=> OCPBUGS-3196: Set ip=dhcp,dhcp6 for master nodes on dualstack

data/data/vspherezoning/pre-bootstrap/main.tf
Since the folder resource might not be ran because there could be
user defined folder per failure domain if a folder is created
the import resource is not waiting. Adding
this depends_on so the import happens after creating
folder(s).
=> OCPBUGS-1560: vsphere zonal, terraform depends on ova import

pkg/asset/installconfig/vsphere/permission_test.go, pkg/asset/installconfig/vsphere/permissions.go, pkg/asset/installconfig/vsphere/validation.go, pkg/asset/installconfig/vsphere/validation_test.go
The problem:
If a vCenter is configured with a default domain and the domain is not provided to the installer, the vCenter API is unable to validate privileges.
The fix:
Use the UserSession from session manager to determine fully qualified username
=> OCPBUGS-3668: fully qualified username must be provided

pkg/asset/agent/image/baseiso.go, pkg/asset/agent/image/oc.go, pkg/asset/agent/manifests/nmstateconfig.go
A new logger is currently created for the baseISO and oc commands. Since the default log level is not debug, this results in the messages not being output. It is cleaner to use the global logger which prints the debug log messages by default.
In addition, a log message was added for a failure running the oc command due to the --icspFile option as this indicates that an older oc binary is being used which doesn't support this option.
=> OCPBUGS-4367: Fix missing debug messages when getting baseISO

docs/dev/azure/azure_client_certs_auth.md
Added documentation for Azure client certificate authentication.
=> CORS-2147: Add documentation for the client certs authentication

data/data/bootstrap/bootstrap-in-place/files/opt/openshift/bootstrap-in-place/bootstrap-in-place-post-reboot.sh, data/data/bootstrap/bootstrap-in-place/files/opt/openshift/bootstrap-in-place/master-update.fcc, pkg/asset/ignition/bootstrap/bootstrap.go, pkg/asset/ignition/bootstrap/common.go
This is a manual cherry-pick of #6664
=> [release-4.11] OCPBUGS-4530: Enable CVO unmanage overrides in bootstrap-in-place installations

data/data/aws/bootstrap/main.tf
PR #5239 switched the default EBS volume type from gp2 to gp3. But in doing so, this breaks support for AWS regions which do not have gp3 (e.g. us-iso-east-1, us-isob-east-1). While it's possible to set the EBS volume type in the install-config for control plane and compute nodes, the bootstrap instance is hardcoded in the terraform.
Since the bootstrap instance is a short lived instance, doesn't require large amounts of iops, and will be destroyed after cluster bootstrapping, switch it back to gp2.
=> Switch back to gp2 ebs volume type for bootstrap instance

pkg/asset/machines/azure/machines.go, pkg/asset/machines/azure/machinesets.go, pkg/asset/machines/master.go
Hive vendors the installer and uses the asset package to generate machinesets for scaleup. Because Hive is using the latest code version but installing multiple previous versions, the machinesets--particularly the values--need to be backward compatible.
In this particular case, the installer switched from using Azure managed images to image galleries in 4.12. In 4.12+ Azure machinesets expect an image referencing an image gallery, while prior to this change the machinesets looked for a managed image.
This commit updates the machineset code to allow a toggle which will allow Hive to generate Azure machinesets utilizing managed images, which should be done with 4.11 and earlier clusters.
This change also future proofs the 4.12+ by switching the machinesets to use the latest version, rather …
=> OCPBUGS-4809: Azure: toggle image in machinesets

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.13 boot image metadata in the installer which includes the fixes for the following:
OCPBUGS-2926 - Unable to gather OpenStack console logs since kernel cmd line has no console args
OCPBUGS-3361 - RHCOS VM fails to boot on IBM Power (ppc64le) - 4.13
```
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --no-signatures --url https://rhcos.mirror.openshift.com/art/storage/releases x86_64=412.86.202209302317-0 aarch64=412.86.202210031918-0 s390x=412.86.202209302317-0 ppc64le=412.86.202209302326-0
```
=> OCPBUGS-2996: bump RHCOS 4.13 bootimage metadata

pkg/destroy/powervs/cloud-instance.go, pkg/destroy/powervs/cloud-sshkey.go, pkg/destroy/powervs/cloudconnection.go, pkg/destroy/powervs/cloudobjectstorage.go, pkg/destroy/powervs/dhcp.go, pkg/destroy/powervs/dns-dns.go, pkg/destroy/powervs/dns-resource.go, pkg/destroy/powervs/image.go, pkg/destroy/powervs/job.go, pkg/destroy/powervs/loadbalancer.go, pkg/destroy/powervs/power-instance.go, pkg/destroy/powervs/power-sshkey.go, pkg/destroy/powervs/powervs.go, pkg/destroy/powervs/publicgateway.go, pkg/destroy/powervs/securitygroup.go, pkg/destroy/powervs/subnet.go, pkg/destroy/powervs/vpc.go
Every place where this occurs:
ctx, _ := o.contextWithTimeout()
Change to:
ctx, cancel := o.contextWithTimeout()
defer cancel()
NOTE:
For the functions instance.NewIBMPI.*Client(, we now use context.Background() because o.contextWithTimeout() and then cancel() will cause future calls to these functions to error out with "context canceled."
=> PowerVS: Defer cancel when calling contextWithTimeout

pkg/destroy/openstack/openstack.go
Some OpenStack object storages respond with `204 No Content` to list requests when there are no containers or objects to list. In these cases, when responding to requests with an `Accept: text/plain` or no `Accept` header, some object storages omit the `content-type` header in their status-204 responses.
Now, Gophercloud throws an error when the response does not contain a `content-type` header.
With this change, we work around the issue by forcing Gophercloud to request a JSON response from the object storage when listing objects. When passed an `Accept: application/json` header, the server responds with `200 Ok` and a `content-type` header in our tests.
This solution gives us a fix that is easily backportable because it doesn't require any dependency bump.
Follows up on …
=> OCPBUGS-4941: OpenStack: Force JSON content-type in Swift object listing

data/data/install.openshift.io_installconfigs.yaml, pkg/asset/cluster/tfvars.go, pkg/asset/installconfig/gcp/client.go, pkg/asset/installconfig/gcp/mock/gcpclient_generated.go, pkg/asset/installconfig/vsphere/mock/authmanager_generated.go, pkg/types/gcp/platform.go, pkg/types/gcp/validation/platform.go, pkg/types/gcp/validation/platform_test.go, pkg/types/validation/installconfig.go, pkg/types/validation/installconfig_test.go
** Create Firewall permissions option is removed from the install config. The terraform vars checks the user permissions in the project to determine if the user can create firewall rules. If the user does not have permissions to create firewall rules then the firewall rules are skipped.
=> GCP: Tfvars will determine the user has create firewall permissions

upi/azure/02_storage.json
Since HyperV support has been added to the installer, it now prefers the HyperV gen2 whenever the VM type selected supports it. This means that we need to upload both gen1 and gen2 RHCOS images to the storage account when doing UPI with MAO to avoid errors like:
```
5h2m Warning FailedCreate machine/$cluster_id-worker-northeurope1-f6kc4 InvalidConfiguration: failed to reconcile machine "$cluster_id-worker-northeurope1-f6kc4": failed to create vm $cluster_id-worker-northeurope1-f6kc4: failure sending request for machine $cluster_id-worker-northeurope1-f6kc4: cannot create vm: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=404 - Original Error: Code="NotFound" Message="The Image '/subscriptions/$sub_id/resourceGroups/$rgroup-rg/providers/Microsoft.Compute/i …
```
=> [release-4.11] OCPBUGS-4405: UPI: Azure: create HyperV2 rhcos image

pkg/asset/cluster/openstack/openstack.go, pkg/asset/installconfig/openstack/openstack.go, pkg/asset/installconfig/openstack/session.go, pkg/asset/installconfig/openstack/validation/cloudinfo.go, pkg/asset/installconfig/openstack/validvaluesfetcher.go, pkg/destroy/openstack/glance.go, pkg/destroy/openstack/openstack.go
The package github.com/pkg/errors has been archived and its functionality integrated in Go's standard library.
=> openstack: Rely on Go's stdlib for errors

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.11 boot image metadata in the installer which includes the fixes for the following:
OCPBUGS-2321 RHCOS VM fails to boot on IBM Power (ppc64le) - 4.11
These changes were generated with the following command
```
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --no-signatures --url https://rhcos.mirror.openshift.com/art/storage/prod/streams x86_64=411.86.202212072103-0 aarch64=411.86.202212072103-0 s390x=411.86.202212072103-0 ppc64le=411.86.202212072103-0
```
=> OCPBUGS-3362: bump RHCOS 4.11 bootimage metadata

data/data/agent/files/usr/local/bin/install-status.sh, data/data/agent/files/usr/local/bin/issue_status.sh, data/data/agent/files/usr/local/bin/set-node-zero.sh.template, data/data/agent/files/usr/local/bin/start-cluster-installation.sh.template, data/data/agent/systemd/units/install-status.service, data/data/bootstrap/files/usr/local/bin/release-image-download.sh.template, pkg/asset/agent/image/ignition_test.go
When updating the console debug messages, don't wait for the next refresh. Issue a reload, which will cause the console to be redisplayed unless the user has already started logging in.
Improve reporting of status so that the user can see what is happening when there are host-specific configurations that cannot be applied, and so that an installation that needs user intervention will report when it has recovered.
=> OCPBUGS-3032: Report status on the console immediately

data/data/powervs/cluster/main.tf, data/data/powervs/variables-powervs.tf, pkg/asset/cluster/tfvars.go, pkg/asset/installconfig/platformprovisioncheck.go, pkg/asset/installconfig/powervs/client.go, pkg/asset/installconfig/powervs/metadata.go, pkg/asset/installconfig/powervs/mock/powervsclient_generated.go, pkg/asset/installconfig/powervs/validation.go, pkg/asset/installconfig/powervs/validation_test.go, pkg/asset/manifests/cloudproviderconfig.go, pkg/tfvars/powervs/powervs.go, pkg/types/powervs/powervs_regions.go
This change would allow users to specify which region to create a new or locate an existing VPC instance and its subnet. With this, users would no longer be tied to the installer-picked region for VPC resources that is hardcoded to be close to the PowerVS region, essentially allowing reuse of an existing VPC infrastructure the user always has, regardless of where the PowerVS instance is located.
The relevant params for VPC resources in question are; 1) `vpcRegion`, 2) `vpcName`, and 3) `vpcSubnets`.
Whether `publish: External` (default) or `publish: Internal`, when `vpcRegion` is specified, the VPC instance the installer works with will be in that region. If `vpcName` is specified additionally, a VPC instance with that name has to be found in that region. If not, one will be created in …
=> Better logic to derive vpcRegion/Zone from vpcName/Subnets

cmd/openshift-install/agent/waitfor.go, pkg/agent/waitfor.go
When running the `agent wait-for install-complete` command, we first check that bootstrapping is complete (by running the equivalent of `agent wait-for bootstrap-complete`. However, if this failed because the bootstrapping timed out, we would report it as an install failure along with the corresponding debug messages (stating that the problem is with the cluster operators, and inevitably failing to fetch data about which).
If the failure occurs during bootstrapping, report it as a bootstrap error the same as you would get from `agent wait-for bootstrap-complete`. If the failure occurs later, don't print the assisted-installer event list. If the command failed because of a timeout, log that.
=> OCPBUGS-3706: Improve error reporting from agent wait-for install-complete

pkg/asset/cluster/cluster.go, pkg/asset/cluster/openstack/openstack.go, pkg/destroy/bootstrap/bootstrap.go
The installer bootstrap destroy command does not locate the clouds.yaml file containing the credentials when it's present in the current directory. This commit fixes the issue by ensuring that prior to destroying the resources, the installer attempts to look for the OS_CLIENT_CONFIG_FILE env var and if unset looks for any clouds.yaml file in the current directory.
=> Bug OCPBUGS-3921: OpenStack: fix bootstrap destroy cmd

pkg/destroy/gcp/dns.go
** Search the host and service projects for the DNS records that were created during the install (when using the a networkProjectID).
=> OCPBUGS-2881: Destroy the service and host project dns records

pkg/asset/machines/gcp/machines.go, pkg/asset/machines/master.go
Creating CPMS manifests for GCP. This will help the operators monitor the control-plane nodes.
=> CORS-2449: Create CPMS manifest

pkg/types/baremetal/validation/platform.go
In order to remove the dependency on providing baremetal hosts, the "agent" string is checked in the CLI command. This fixes the requirement that it always be after the "create".
(Note that this solution is an improvement, but not perfect, as it can result in a false positive if "agent" is used elsewhere in the command line. A more complete solution will come in a later release).
=> OCPBUGS-4874: Remove order dependency for agent CLI string

upi/vsphere/main.tf, upi/vsphere/terraform.tfvars.example, upi/vsphere/variables.tf, upi/vsphere/vm/main.tf, upi/vsphere/vm/variables.tf
Introduces failure domains to the vSphere UPI terraform.  The changes in this PR should not impact configured in terraform.tfvars for non-zonal/failure domain installations.
=> SPLAT-900: provision VMs in to failure domains

pkg/asset/agent/agentconfig/agent_config.go, pkg/asset/agent/agentconfig/agent_config_test.go
Add validation that the rendezvousIP is assigned to a host with role "master".
This hasn't been tested beyond unit tests. Please test and review!
=> OCPBUGS-2088: Validate that the rendevousIP is assigned to a master

pkg/asset/machines/azure/machinesets.go, pkg/asset/machines/worker.go
As a followup to #6694, Hive needs to be able to select whether to use the image gallery setting or not.  This change just forwards the `useImageGallery` further up the chain, and also removes the unused `rhcosVersion` parameter.
=> Expose Azure useImageGallery parameter in the MachineSets() call

data/data/install.openshift.io_installconfigs.yaml, pkg/types/gcp/platform.go, pkg/types/validation/installconfig.go, pkg/types/validation/installconfig_test.go
GCP XPN, with DNS zones in the service projects, is intended to GA in the next release. Let's remove the feature gate requirement, especially because enabling the feature gate enables the CCM; so cluster behavior is different than what we would be seeing in actual deployments.
=> GCP XPN: remove tech preview feature gate

data/data/aws/bootstrap/main.tf, data/data/aws/cluster/main.tf
This is a potential fix for OCPBUGS-2743. I'm not 100% certain this is what we want to do, but I think it is good to put it up for discussion. 
When specifying an STS endpoint in the install config, the terraform provider assumes we are also using sts credentials, and the check fails validation:
level=error msg=Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: SignatureDoesNotMatch: Credential should be scoped to a valid region.
This skips the validation check, to allow us to use non-STS credentials.
The only downside I can see for this is if this would make failures for invalid STS creds less user-friendly. Considering that we don't document how to use STS creds for the installer, this seems like a small issue. …
=> OCPBUGS-2743: skip sts credentials check in terraform

pkg/destroy/aws/iamhelpers.go
In the AWS cluster destroy/uninstall path, the Installer tries to find all the IAM Roles in the cluster and then attempts to delete the resources with the tag `kubernetes.io/cluster/<cluster-name>`. In the case of STS clusters, all IAM Roles are cleared outside the cluster (not by the Installer) and even trying to find them in the cluster results in errors because the Installer does not have the privileges to do that, let alone deleting them.
The goal of the fix is not attempt to delete these IAM Roles that Installer does not have access to.
=> OCPBUGS-1769: Check for AWS STS installation before trying to get all IAM Roles

upi/vsphere/variables.tf
With the addition of failure_domains, some variables are deprecated and still may be used.  Since these variables may validly be left empty when failure_domains is used, defaults are now being provided for those variables.
cc: @jcpowermac
=> SPLAT-901: set default for variables that are deprecated by failure_domains

pkg/asset/installconfig/nutanix/nutanix.go, pkg/asset/installconfig/ovirt/network.go, pkg/asset/installconfig/vsphere/vsphere.go, pkg/types/defaults/installconfig.go, pkg/types/defaults/installconfig_test.go, pkg/types/validation/installconfig.go
validate VIPs are in machineNetwork in survey.  validation was added for vsphere, ovirt, and nutanix.
=> OCPBUGS-881: fail to create install-config.yaml as apiVIP and ingress VIP are not in machine networks

data/data/gcp/cluster/network/firewall.tf
** There is no need to add the public load balancer IP addresses to firewall rules when the cluster is internal. ** The internal load balancer ip addresses will be present for internal and external cluster.
https://issues.redhat.com/browse/OCPBUGSM-47223
=> BUG 2110982: GCP skip public loadbalancer ip addresses

data/data/coreos/fcos.json
OKD's machine-os-content has switched to F37, so installer should use F37 from next version to make bootstrap pass in allotted time.
This also fixes `containers.conf` permission issue introduced in #6171
=> OCPBUGS-1695: Update FCOS to latest 37.20221127.3.0 stable

pkg/asset/manifests/proxy.go
It was previously only added for StackCloud but it's also needed for all national clouds.
=> OCPBUGS-5734: make VIP 168.63.129.16 noProxy in all clouds except Public

pkg/asset/machines/azure/machines.go, pkg/asset/machines/master.go
Creating an extra CRD asset for the ControlPlaneMachineSet which is required for the machine api operator for more control over the control-plane nodes that come up on Azure.
=> CORS-2405: Create ControlPlaneMachineSet CRDs

pkg/types/vsphere/defaults/platform.go, pkg/types/vsphere/validation/platform.go, pkg/types/vsphere/validation/platform_test.go
Moved code for setting default values and adjusted how `resourcePool` is defaulted in the event there's no `resourcePool` defined in higher level vsphere platform config.
=> OCPBUGS-1612: vsphere: set default resource pool when missing failure domain topology

pkg/asset/machines/gcp/machines.go, pkg/asset/machines/gcp/machines_test.go, pkg/asset/machines/master.go
Setting the pre-created state to active in the CPMS manifest.
=> CORS-2449: gcp: Set pre-created CPMS to Active state

pkg/asset/installconfig/azure/validation.go
From azure doc
https://learn.microsoft.com/en-us/azure/virtual-machines/nvv4-series, looks like the NVv4 series only supports Windows.
=> OCPBUGS-5184: azure: validate Windows-only VM types

docs/user/azure/install_upi.md, upi/azure/02_storage.json, upi/azure/04_bootstrap.json, upi/azure/05_masters.json, upi/azure/06_workers.json
When we moved to using Image Galleries in Azure/IPI, we also changed the
location that MAO uses for the rhcos bootimages. These changes update
our ARM templates so that the bootimages are picked from the right
location. It fixes the following error when scaling compute nodes:
```
Error Message: failed to reconcile machine "maxu-upi2-gc7n8-worker-eastus3-68gdx": failed to create vm maxu-upi2-gc7n8-worker-eastus3-68gdx: failure sending request for machine maxu-upi2-gc7n8-worker-eastus3-68gdx: cannot create vm: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="GalleryImageNotFound" Message=""The gallery image /subscriptions/$sub_id/resourceGroups/$resource_group/providers/Microsoft.Compute/galleries/$gallery_name/images/maxu-upi2-gc …
```
=> OCPBUGS-4654: azure: upi: use Image Gallery in ARM templates

cmd/openshift-install/create.go
There is a separate command for the agent wait-for (bootstrap and install). If using the non-agent command but the AgentConfig asset is detected, log a warning.
=> OCPBUGS-3253: Warn if agent assets detected when using non-agent waitfor

pkg/types/validation/installconfig.go, pkg/types/validation/installconfig_test.go
Update the validation on NO_PROXY to allow IP addresses to be include.
=> OCPBUGS-5461: Allow NO_PROXY to contain IPs

pkg/asset/installconfig/azure/validation.go
Deploying IPI cluster on azure cloud in the 'westeurope' region with VM size as EC96iads_v5 or EC96ias_v5, installation fails with below error:
12-15 11:47:03.429  level=error msg=Error: creating Linux Virtual Machine: (Name "$infraID-bootstrap" / Resource Group "$infraID-rg"): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="The VM size 'Standard_EC96iads_v5' is not supported for creation of VMs and Virtual Machine Scale Set with '<NULL>' security type."
From azure portal, we can see that the type of both VM sizes EC96iads_v5 and EC96ias_v5 is confidential compute.
=> OCPBUGS-5182: validate additional confidential VM types

pkg/asset/agent/image/baseiso.go, pkg/asset/agent/image/cache.go, pkg/asset/agent/image/oc.go
This is a preliminary patch that refactors the `oc.go` code to introduce a new `ExtractFile` method in the `Release` interface.
This method will be required to extract the agent-tui binary from the release payload
=> AGENT-504: Agent extract binary

docs/user/azure/install_upi.md, docs/user/azure/install_upi_azurestack.md, docs/user/gcp/install_upi.md
Documenting the extra step of removing the control plane machine set files created for Azure and GCP which need to be removed for UPI installation.
=> CORS-2469: upi: Document removal of CPMS for UPI installation

pkg/destroy/openstack/openstack.go
This is a combined backport of https://github.com/openshift/installer/pull/6628 and https://github.com/openshift/installer/pull/6726
---
Some OpenStack object storages respond with `204 No Content` to list requests when there are no containers or objects to list. In these cases, when responding to requests with an `Accept: text/plain` or no `Accept` header, some object storages omit the `content-type` header in their status-204 responses.
Now, Gophercloud throws an error when the response does not contain a `content-type` header.
With this change, we work around the issue by forcing Gophercloud to request a JSON response from the object storage when listing containers. When passed an `Accept: application/json` header, the server responds with `220 OK` and a `content-type` header in our …
=> OCPBUGS-6086: OpenStack: Force JSON content-type in Swift

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.13 boot image metadata in the installer which includes the fixes for the following:
OCPBUGS-5957 - Update bootimage with new ignition build (to support FIPS mode in s390x)
```
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --no-signatures --url https://rhcos.mirror.openshift.com/art/storage/prod/streams x86_64=413.86.202301191042-0 aarch64=413.86.202301191042-0 s390x=413.86.202301191042-0 ppc64le=413.86.202301191042-0
```
=> OCPBUGS-5959: bump RHCOS 4.13 bootimage metadata

data/data/agent/files/usr/local/bin/agent-interactive-console.sh, data/data/agent/systemd/units/agent-interactive-console.service, data/data/agent/systemd/units/agent-tui.path, pkg/asset/agent/image/ignition.go, pkg/asset/agent/image/ignition_test.go
Users would like the ability to change their network configuration at the console if network connectivity problems are detected.
To achieve this goal, this patch adds a new service called agent-interactive-console.service to block the login prompt and the agent services that pulls an image from the registry.
The service will execute the agent TUI to allow users to update their network configuration. The TUI will check there is connectivity to the registry and to the rendezvous host. If the connectivity checks pass, the TUI exits, which also lead the interactive console service to exit, and this unblocks the login prompt and agent services waiting for pull from the registry, allowing the agent-based installer to proceed.
The agent TUI will be added in a future patch.
For now, the service …
=> AGENT-453: Create interactive console service for agent installer

data/data/bootstrap/files/usr/local/bin/bootstrap-pivot.sh.template
This should fix OKD SCOS, which pivots the bootstrap node and requires the file to be world-readable so that rpm-ostree could read it and fetch machine-os-content image
=> CORS-2479: bootstrap: set 0644 mode for registries.conf

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template, data/data/bootstrap/files/usr/local/bin/bootstrap-verify-api-server-urls.sh
The check to resolve the API and Internal API server URLs were performed together within the bootkube service right after MCO was started. This resulted in false negatives because the API Server became periodically unavailable during the bootstrap process. 
To make these checks better, this PR splits the check into 2 parts:
1. URLs resolvable - This can be checked early and hence this is the only check that happens before MCO is started.
2. URLs reachable - This check was causing the false -ives and hence has been moved to the end of bootkube service when we expect the API Server to be stable.
This split has resulted in these checks happening in 2 stages "resolve-api(-int)-url" and "check-api(-int)-url" so the success and failure of these stages can be reported individually. Also, …
=> Bug 2072202: Check for reachability of API and API-Int URLs later in bootkube

data/data/install.openshift.io_installconfigs.yaml, pkg/asset/installconfig/powervs/session.go, pkg/destroy/powervs/powervs.go, pkg/types/powervs/platform.go, pkg/types/powervs/powervs_regions.go, pkg/types/powervs/validation/platform.go, pkg/types/powervs/validation/platform_test.go, pkg/types/validation/installconfig_test.go
For the power-go-client, Region (and the endpoint name) is now derived from the Zone. Also, the install-config.yaml should handle not specifying the region.
https://issues.redhat.com/browse/MULTIARCH-2418WIP
=> PowerVS: Remove region requirement

cmd/openshift-install/agent_internal_integration_test.go, cmd/openshift-install/testdata/agent/image/assets/default_assets.txt, pkg/asset/agent/image/agentimage.go, pkg/asset/agent/image/cpio.go
This patches modifies the current ISO generation to insert also the agent-tui binary.
How it works:
* The rhcos base ISO is unpacked in a temp folder
* A new compressed cpio archive `ignition.img` is created, containing:
* The `config.ign` file generated by the agent installer
* The `agent-tui` binary
* The new `ignition.img` is saved in the temp folder, overwriting the older one
* A new ISO is created with the content of the temp folder
For manual testing: 
```
$ iso-read --image agent.x86_64.iso --extract /images/ignition.img --output-file ignition.img
$ zcat ignition.img | cpio -idmv
```
=> AGENT-505: Embed agent-tui binary in the agent ISO

pkg/destroy/azure/azure.go
It seems the SDK can return `nil` as a response even if no errors occurred. If we don't check for that, we get the following error on Gov cloud:
```
12-19 13:21:52.860  level=debug msg=deleting application registrations
12-19 13:21:52.860  E1219 05:21:48.969224     743 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
12-19 13:21:52.860  goroutine 1 [running]:
12-19 13:21:52.860  k8s.io/apimachinery/pkg/util/runtime.logPanic({0x6132160?, 0x22371b20})
12-19 13:21:52.860  	/go/src/github.com/openshift/installer/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
12-19 13:21:52.860  k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
12-19 13:21:52.860 …
```
=> OCPBUGS-4549: destroy: azure: handle `nil` responses from msgraph sdk

data/data/agent/files/etc/assisted/agent-installer.env.template, data/data/agent/files/usr/local/bin/agent-interactive-console.sh, data/data/agent/files/usr/local/bin/common.sh, data/data/agent/files/usr/local/bin/set-node-zero.sh, data/data/agent/systemd/units/agent-interactive-console.service, data/data/agent/systemd/units/agent-tui.path, pkg/asset/agent/image/ignition.go, pkg/asset/agent/image/ignition_test.go
Update the interactive console service to have it check the current
host can access the release image and rendezvous host. Display
this connectivity information to the user before prompting to run
the network configuration tui.
If there is connectivity, then the prompt times out after 60s and
the automation flow is allowed to continue.
If there is a connectivity issue, then the network configuration
tui will be executed to allow users to update. The tui, however,
has not been  integrated with the interactive console service, so
in the meantime, there is a 60s sleep in place of executing the tui.
This will be changed in a future patch.
Depends on: https://github.com/openshift/installer/pull/6756
=> AGENT-455: Check registry and rendezvous host access at startup

pkg/asset/agent/installconfig.go
Spurious warning are being generated for platform baremetal values. Compare the values to default in order to detect the values were set in install-config.
Since the default values for MAC addresses are generated a valid comparison can't be done, so these checks have been removed.
=> OCPBUGS-6663: Check platform baremetal settings against default values

data/data/coreos/rhcos.json
Having two artifacts under qemu was causing a failure in s390x CI.
It was not possible to keep the original RHCOS version because the
pipeline already produced a release.json with the qemu-secex nested
under qemu.
Also resolves the following bug for 4.13 (see comments):
OCPBUGS-6509 - Agent service fails to start since cannot pull assisted-installer-agent image
```
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --no-signatures --url https://rhcos.mirror.openshift.com/art/storage/prod/streams x86_64=413.86.202301302144-0 aarch64=413.86.202301302144-0 s390x=413.86.202301302144-0 ppc64le=413.86.202301302144-0
=> OCPBUGS-6722: bootimage: move secure execution artifact to separate artifact

cmd/openshift-install/testdata/agent/image/configurations/vsphere_compact.txt, pkg/asset/agent/installconfig.go, pkg/types/baremetal/validation/platform.go, pkg/types/vsphere/validation/platform.go, pkg/validate/method.go
Copy the same fix as for the baremetal platform (OCPBUGS-3278) to
vSphere to prevent validation of the presence of fields in the
install-config that are, in fact, ignored by the agent installer.
=> OCPBUGS-6270: Don't require vSphere details for agent installer

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.12 boot image metadata in the
installer which includes the fixes for the following:
OCPBUGS-5958 - Update bootimage with new ignition build (to support FIPS mode in s390x)
OCPBUGS-6722 - bootimage: move secure execution artifact to separate
OCPBUGS-6509 - Agent service fails to start since cannot pull assisted-installer-agent image
```
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --no-signatures --url https://rhcos.mirror.openshift.com/art/storage/prod/streams x86_64=412.86.202301272018-0 aarch64=412.86.202301272018-0 s390x=412.86.202301272018-0 ppc64le=412.86.202301272018-0
=> OCPBUGS-5960: bump RHCOS 4.12 bootimage metadata

pkg/asset/installconfig/azure/session.go
When the authorizer fails, the installer prints a generic message and continues with the collection of the service principal info. A clear error message as to why the authorizer fails would be helpful.
=> azure: Add error message when authorizer fails.

pkg/types/vsphere/validation/machinepool.go, pkg/types/vsphere/validation/machinepool_test.go
I think the original intention behind the validation was to check that, in case `CoresPerSocket` was not set by the user, it would be checked against a default value (currently set to 4). However, that's not what is happening in practice, and both the check against the user-inputed value and the default were being performed.
That means that using CPUS=2 and CoresPerSocket=2 as exemplified in the official docs [1] would result in a validation error:
```
failed to create install config: invalid "install-config.yaml" file: controlPlane.platform.vsphere.cpus:
Invalid value: 2: numCPUs specified should be a multiple of cores per socket which is by default 4]
```
even though it's a valid configuration (albeit a pretty tiny compute node).
I'm changing the code a bit to make it more clear what …
=> OCPBUGS-6919: vsphere: fix validation of CPUS and CoresPerSocket

data/data/agent/files/etc/systemd/system.conf.d/10-default-env.conf.template, data/data/agent/systemd/units/agent.service.template, pkg/asset/agent/image/ignition.go, pkg/asset/agent/image/ignition_test.go
When the registry is only reachable via a proxy, the settings configured in install-config.yaml need to be used for podman. Save the proxy settings in systemd config.
=> OCPBUGS-4997: Set the configured proxy settings for agent installer

pkg/asset/machines/openstack/machines.go
On 32-bit systems, Go `int` values are 32-bit integers. Given that we accept an explicit int64 number of replicas in the machine-pool, the index we use to distribute zones could end up negative when casting to int on 32-bit systems.
As a consequence, using availability zones when the replica number is greater than 2^31-1 on 32-bit systems makes the Installer panic.
With this change, we coerce the wrapping to be positive by casting to an unsigned integer. The automatic casting to int only happens after a modulo operation that is guaranteed to result in a number within int range.
While this fix may look risible, hitting this bug is just marginally less likely than encountering clusters of two billion workers, occurrence that the existing code goes out of its way to cover.
=> OpenStack: Fix distribution of zones on 32-bit systems

pkg/asset/installconfig/azure/session.go, pkg/destroy/azure/azure.go
When doing API calls to the new MSGraph API, we need to override the URL used to connect to Microsoft Graph national cloud deployments.
This fixes the following error when trying to destroy a Gov cloud cluster:
```
02-07 14:39:50.162  level=debug msg=deleting application registrations
02-07 14:40:36.775  level=debug msg=failed to gather list of Service Principals by tag: Get "https://graph.microsoft.com/v1.0/servicePrincipals?$filter=startswith%28displayName%2C%20%27$INFRA_ID%27%29%20and%20tags%2Fany%28s%3As%20eq%20%27kubernetes.io_cluster.$INFRA_ID%3Downed%27%29": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
Notice the usage of `https://graph.microsoft.com/` (global service) instead of `https://graph.microsoft.us/` (US Gov cloud). …
=> OCPBUGS-4549: azure: fix MS Graph calls on Gov cloud

pkg/asset/agent/agentconfig/agent_config.go, pkg/asset/agent/agentconfig/agent_config_test.go
Due to it being a string, it had become out of date in a way that it impacted users. This commit syncs its content back to what is in pkg/types
=> OCPBUGS-7261: Update AgentConfig template

hack/build.sh, terraform/Makefile
Using `MODE=dev ./hack/build.sh`with this PR will allow the use
of Delve (and rr). It disables:
- compiler optimizations
- inlining
- DWARF stripping
`MODE=release` remains unchanged.
=> installer dev build settings to enable delve

cmd/openshift-install/testdata/agent/image/assets/default_assets.txt, pkg/asset/agent/image/agentimage.go, pkg/asset/agent/image/cpio.go
This patch is a follow up of #6786, and it introduces a new approach for embedding files which is compatible also with the PXE booting.
The required files are added in a compressed cpio archive, which is appended to the `initrd.img` extracted from the base coreos ISO during the execution of the `agent create image` command. The newly added agent archive contains also a dracut hook script to copy the files before switching root.
=> AGENT-505: Embed agent files in initrd

pkg/asset/machines/master.go
When generating the openshift manifests, it tries to load the dependency control plane asset that creates files in the openshift directory. It then checks to see if the openshift manifest is actually already generated before this by checking the openshift directory for files that are not generated by the machine asset.
The newly created CPMS file was missing from the check, hence the asset loader always thought the asset was generated since there are files that exist other than the machine files and exits but it actually had to be newly generated with 4 files that were crucial to installation.
Adding the CPMS files to the list of machine asset files.
=> OCPBUGS-6777: Fix file check for loading openshift manifests

data/data/manifests/bootkube/cvo-overrides.yaml.template
Following up on 4.12's 35023b3804 (#6302), 4.11's f995341c32 (#5621), and similar.
=> OCPBUGS-7356: data/manifests/bootkube/cvo-overrides: Default to stable-4.13

data/data/azure/bootstrap/main.tf, data/data/azure/cluster/dns/dns.tf, data/data/azure/cluster/dns/variables.tf, data/data/azure/cluster/main.tf, data/data/azure/cluster/master/master.tf, data/data/azure/cluster/master/variables.tf, data/data/azure/vnet/internal-lb.tf, data/data/azure/vnet/main.tf, data/data/azure/vnet/nsg.tf, data/data/azure/vnet/public-lb.tf, data/data/azure/vnet/vnet.tf, pkg/asset/cluster/tfvars.go, pkg/asset/machines/azure/machines.go, pkg/asset/machines/azure/machinesets.go, pkg/asset/machines/master.go, pkg/asset/machines/worker.go, pkg/tfvars/azure/azure.go
PR is for applying OCP default tag (`"kubernetes.io_cluster.{cluster_id}" = "owned"`) and user defined tags to all azure resources created.
=> CFE-586 : Apply user defined tags on created azure resources

pkg/asset/cluster/tfvars.go, pkg/asset/installconfig/ibmcloud/client.go, pkg/asset/installconfig/ibmcloud/metadata.go, pkg/asset/installconfig/ibmcloud/metadata_test.go, pkg/asset/installconfig/ibmcloud/mock/ibmcloudclient_generated.go, pkg/asset/installconfig/ibmcloud/responses/responses.go, pkg/asset/installconfig/ibmcloud/subnet.go, pkg/asset/installconfig/ibmcloud/validation_test.go, pkg/asset/manifests/openshift.go
Add tests to improve coverage of the IBM Cloud installconfig metadata package. This includes removing public access for metadata values (used for test purposes), refactoring test package, and moving response structs to unique package to prevent cyclic dependencies.
=> IBMCloud: Add tests for installconfig metadata

data/data/install.openshift.io_installconfigs.yaml, pkg/explain/printer_test.go, pkg/types/azure/platform.go, pkg/types/azure/validation/platform.go, pkg/types/azure/validation/platform_test.go, pkg/types/validation/installconfig.go
- Public DNS records and Private Zone does not have user-defined tags where tag name contains @, +, = special characters.
- Missing validation for TechPreview feature
=> CFE-757 : Fix issues reported by QE

pkg/destroy/ibmcloud/cloudobjectstorage.go, pkg/destroy/ibmcloud/ibmcloud.go
Attempt to remove generation reclamations for COS Instances created by the installer for the cluster during the destroy process. These reclamations can cause the destroy process to fail, as the cluster's ResourceGroup cannot be deleted when these reclamations exist, which occurrs occassionally. Also, restructured destroy stages to handle deletion order properly.
Related: https://issues.redhat.com/browse/OCPBUGS-4954
=> OCPBUGS-4954: IBMCloud: Handle COS reclamations

go.mod, go.sum, vendor/github.com/Masterminds/goutils/cryptorandomstringutils.go, vendor/github.com/Masterminds/goutils/randomstringutils.go, vendor/github.com/Masterminds/goutils/stringutils.go, vendor/modules.txt
A flaw was found in goutils where randomly generated alphanumeric strings contain significantly less entropy than expected. Both the RandomAlphaNumeric and CryptoRandomAlphaNumeric functions always return strings containing at least one digit from 0 to 9. This issue significantly reduces the amount of entropy generated in short strings by these functions.
=> OCPBUGS-5663: CVE-2021-4238: goutils: update for randomness fix

.golangci.yaml, hack/go-lint.sh
CI now has golangci-lint 1.48 which supports Golang 1.19. Let's make sure our hack/ tool uses the same version.
=> linter: bump version to sync with CI

cmd/openshift-install/testdata/agent/image/configurations/compact.txt, cmd/openshift-install/testdata/agent/image/validations/compact_not_enough_hosts.txt
This data is no longer required since the fix for OCPBUGS-4874, so don't add it to the install-config in the integration tests. This will allow us to pick up any regression.
=> integration: Don't pass host data in the install-config

cmd/openshift-install/testdata/agent/image/manifests/default_manifests.txt, pkg/asset/agent/common.go, pkg/asset/agent/installconfig.go, pkg/asset/agent/manifests/agentclusterinstall.go, pkg/asset/agent/manifests/agentclusterinstall_test.go, pkg/asset/agent/manifests/util_test.go
The platform types in AgentClusterInstall are in mixed case. Previously we were just casting the lowercase platform name to set the PlatformType field. This resulted in the platform type being silently ignored when creating the Cluster in the assisted API. Clusters were getting the default type for their topology (None for SNO, otherwise BareMetal), but there was no way to set VSphere as the platform.
=> OCPBUGS-7495: Convert platform type for AgentClusterInstall

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.13 boot image metadata in the installer which includes the fixes for the following:
OCPBUGS-7523 - Add new AWS regions for ROSA
```
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --no-signatures --url https://rhcos.mirror.openshift.com/art/storage/prod/streams x86_64=413.86.202302150245-0 aarch64=413.86.202302150245-0 s390x=413.86.202302150245-0 ppc64le=413.86.202302150245-0
```
=> OCPBUGS-7180: update RHCOS 4.13 bootimage metadata

pkg/asset/agent/agentconfig/agent_config.go, pkg/asset/agent/agentconfig/agent_config_test.go
Due to it being a string, it had become out of date in a way that it impacted users. This commit syncs its content back to what is in pkg/types
(cherry picked from commit 1c665168e0b2776eac03e9c2154a22d4539b651e)
=> OCPBUGS-7521: Update AgentConfig template

images/baremetal/Dockerfile.ci
This workaround was introduced because it broke Metal IPI CI. However, the Metal team is now using `nss_wrapper`, so it should not be needed anymore.
=> Bug 1904573: baremetal container modify /etc/passwd group writable

data/data/coreos/rhcos.json
OCPBUGS-7525 - [4.12] Add new AWS regions for ROSA
```
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --no-signatures --url https://rhcos.mirror.openshift.com/art/storage/prod/streams x86_64=412.86.202301311551-0 aarch64=412.86.202301311551-0 s390x=412.86.202301311551-0 ppc64le=412.86.202301311551-0
```
=> OCPBUGS-7529: bump RHCOS 4.12 bootimage metadata

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.11 boot image metadata in the installer which includes the fixes for the following:
OCPBUGS-7526 [4.11] Add new regions for ROSA
These changes were generated with the following command
```
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --no-signatures --url https://rhcos.mirror.openshift.com/art/storage/prod/streams x86_64=411.86.202212072103-0 aarch64=411.86.202212072103-0 s390x=411.86.202212072103-0 ppc64le=411.86.202212072103-0
```
=> OCPBUGS-7530: bump RHCOS 4.11 bootimage metadata

pkg/asset/installconfig/azure/session.go
Fallout from https://github.com/openshift/installer/pull/6003
If we pass `nil` to `azidentity.ParseCertificates`, it assumes the private key isn't encrypted. Let's pipe the password through instead.
=> OCPBUGS-7579: azure: fix certificate-based auth with passpharse

.golangci.yaml, pkg/asset/agent/common.go, pkg/asset/agent/image/cpio.go, pkg/asset/manifests/nutanix/cloudproviderconfig.go, pkg/destroy/aws/iamhelpers.go, pkg/types/vsphere/conversion/installconfig.go, pkg/validate/method.go
This type of reporting is disabled by default in golangci-lint. However, we used to enforce it when using golang/lint and I think it's useful to have.
* Fix some recent cases that were only caught during backport.
=> linter: enable reporting about exported names lacking comments

pkg/asset/machines/master.go
For the machine asset to be generated, the CPMS asset is not required and for platforms outside of AWS, Azure and GCP, it is not necessary. This also affects UPI installation.
=> OCPBUGS-7622: Ignore CPMS file if not exist

hack/build-coreos-manifest.go
If TAGS env var contains "fcos" (its an alias to OKD) CoreOS manifest script should use
FCOS json. This is necessary for OKD clusters to be installable via
Hypershift
=> OCPBUGS-7993: hack/build-coreos-manifest: support OKD

data/data/install.openshift.io_installconfigs.yaml, data/data/nutanix/cluster/main.tf, data/data/nutanix/variables-nutanix.tf, pkg/asset/machines/master.go, pkg/asset/machines/nutanix/machines.go, pkg/asset/machines/worker.go, pkg/tfvars/nutanix/nutanix.go, pkg/types/nutanix/client.go, pkg/types/nutanix/machinepool.go
- Support the new fields of NutanixMachineProviderConfig added by the api PR https://github.com/openshift/api/pull/1390.
- The new fields include:
bootType: optionally indicates the boot type for the worker Machine VM.
project: optionally identifies a Prism project for the Machine's VM.
categories: optionally adds one or more prism categories for the Machine's VM.
=> Support the new fields in NutanixMachineProviderConfig

data/data/gcp/bootstrap/main.tf, data/data/gcp/variables-gcp.tf, pkg/asset/cluster/tfvars.go, pkg/tfvars/gcp/gcp.go
#6330, which introduced environmental auth, changed the default behavior of all installs to create a new service account for signing the ignition URL. Instead, we should only create that service account when using environmental auth (or for some other reason don't have a service account with a key).
=> GCP: conditionally create bootstrap service account

pkg/asset/agent/common.go, pkg/asset/agent/installconfig.go, pkg/asset/agent/manifests/agentclusterinstall.go, pkg/asset/agent/manifests/agentclusterinstall_test.go, pkg/asset/agent/manifests/util_test.go
The platform types in AgentClusterInstall are in mixed case. Previously we were just casting the lowercase platform name to set the PlatformType field. This resulted in the platform type being silently ignored when creating the Cluster in the assisted API. Clusters were getting the default type for their topology (None for SNO, otherwise BareMetal), but there was no way to set VSphere as the platform.
Backport of #6855
=> [release-4.12] OCPBUGS-7746: Convert platform type for AgentClusterInstall

cmd/openshift-install/testdata/agent/image/manifests/default_manifests.txt, data/data/agent/files/etc/assisted/agent-installer.env.template, data/data/agent/systemd/units/agent-interactive-console.service, data/data/agent/systemd/units/set-hostname.service, pkg/asset/agent/image/agentimage.go, pkg/asset/releaseimage/default.go
This patch finalizes the integration of the agent-tui binary within the agent ISO
This patch also bumps up the default release image to `registry.ci.openshift.org/origin/release:4.13`, as it's required by the integration tests (as pointed out by @zane in the comment, there's also a ticket for it https://issues.redhat.com/browse/CORS-2235)
=> AGENT-502: Enable agent tui

cmd/openshift-install/testdata/agent/image/manifests/default_manifests.txt, pkg/asset/agent/image/baseiso.go, pkg/asset/agent/image/baseiso_test.go, pkg/asset/agent/image/ignition.go, pkg/asset/agent/installconfig.go, pkg/asset/agent/installconfig_test.go, pkg/asset/agent/manifests/infraenv.go
Enable arm64 iso builds for agent installer based on the control plane architecture set in install-config.yaml.
=> ARMOCP-417: enable arm64 for agent installer

pkg/asset/agent/installconfig_test.go, pkg/types/validation/installconfig.go, pkg/types/validation/installconfig_test.go
a58ac55e8a07e442c73747ffcbdbbc3f584b276d introduced many network validations for on-prem platforms. We want to relax one of those, the check that Ingress & API VIPs are in the machinenetwork because the check prevents using the TUI survey to generate the install config and this (mismatched) configuration has been allowed in all of OpenShift 4 without issue.
Fixes OCPBUGS-7015
/cc creydr jcpowermac sadasu cybertron rvanderp3
=> OCPBUGS-7015: Relax MachineCIDR check for vSphere, Nutanix

data/data/azure/bootstrap/main.tf, data/data/azure/cluster/main.tf, data/data/azure/cluster/master/master.tf, data/data/azure/cluster/master/variables.tf, data/data/azure/cluster/variables.tf
Update installer-created VMs to use managed-storage accounts rather than custom storage accounts, created by the installer. We're doing this in order to have consistency with the control-plane machinesets and to decrease our dependence on the installer-created storage account, which we would like to remove at bootstrap destroy.
=> Azure: use managed storage account for boot logs

docs/user/aws/install_existing_vpc_local-zones.md, pkg/asset/installconfig/aws/availabilityzones.go, pkg/asset/installconfig/aws/metadata.go, pkg/asset/installconfig/aws/subnet.go, pkg/asset/installconfig/aws/validation.go, pkg/asset/installconfig/aws/validation_test.go, pkg/asset/installconfig/installconfig.go, pkg/asset/machines/aws/machines.go, pkg/asset/machines/aws/machinesets.go, pkg/asset/machines/master.go, pkg/asset/machines/worker.go, pkg/asset/machines/worker_test.go, pkg/asset/manifests/network.go, pkg/types/aws/availabilityzones.go, pkg/types/aws/defaults/platform.go, pkg/types/aws/defaults/platform_test.go, pkg/types/aws/platform.go, pkg/types/defaults/installconfig.go, pkg/types/defaults/installconfig_test.go, pkg/types/defaults/machinepools.go, pkg/types/defaults/machinepools_test.go, pkg/types/installconfig.go, pkg/types/machinepools.go, pkg/types/validation/installconfig.go, upi/aws/cloudformation/01.99_net_local-zone.yaml, upi/aws/cloudformation/01_vpc.yaml
The goal of this PR is to add support to [AWS Local Zones](https://aws.amazon.com/about-aws/global-infrastructure/localzones/) when installing a cluster in an existing VPC. It allows the creation of a compute pool named `edge`, alongside the `worker`, on `install-config.yaml`. The installer will generate MachineSet manifests with `NoSchedule` taint to deploy the instance on edge locations.
This implementation is Phase 1 of the [Enhancement Proposal #1232](https://github.com/openshift/enhancements/pull/1232), which describes in detail the change request.
Nodes are considered `edge` when the availability zone  [`zoneType`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AvailabilityZone.html) is `local-zone`. The `edge` compute pool is valid only for the AWS Platform.
It is not …
=> RFE-2782: Create edge compute pool to support AWS Local Zones

pkg/types/openstack/validation/platform.go, pkg/types/openstack/validation/platform_test.go, pkg/types/openstack/validation/techpreview.go, pkg/types/openstack/validation/techpreview_test.go, pkg/types/validation/installconfig.go, pkg/types/validation/installconfig_test.go
With this change, filling in TechPreview-only configuration flags in OpenStack throws similar errors as to what happens on other platforms.
Supersedes #6913
/cc mandre patrickdillon
=> openstack: consistent TechPreview-only feature validation

pkg/asset/agent/mirror/registriesconf.go
This was accidentally broken by
d3856aa7c6a9630dd7e401efe73e69d0591cd510, resulting in errors when writing the asset to disk (i.e. the 'agent create cluster-manifests' command would fail).
=> OCPBUGS-8258: Specify filename for default registries.conf

cmd/openshift-install/agent.go, cmd/openshift-install/testdata/agent/pxe/configurations/sno.txt
This feature has only partly landed, and is likely to be in a broken state. Disable the command that has landed, so that we can defer to a future release.
=> AGENT-356: Disable 'create pxe-files' command

pkg/asset/manifests/infrastructure.go
After https://github.com/openshift/api/commit/925f75a26305c13db2d89c0e993060ab60c267ce ResourceGroup is needed by the machine-config-operator.
=> OCPBUGS-8305: Power VS: Add resourceGroup to infrastructure manifest

data/data/install.openshift.io_installconfigs.yaml, data/data/openstack/masters/main.tf, data/data/openstack/masters/outputs.tf, data/data/openstack/masters/private-network.tf, data/data/openstack/variables-openstack.tf, pkg/asset/machines/openstack/machines.go, pkg/asset/machines/openstack/machinesets.go, pkg/tfvars/openstack/openstack.go, pkg/tfvars/openstack/ports.go, pkg/types/openstack/machinepool.go, pkg/types/openstack/validation/machinepool.go, pkg/types/openstack/validation/machinepool_test.go, pkg/types/openstack/validation/techpreview.go, scripts/openstack/manifest-tests/failure-domains/install-config.yaml, scripts/openstack/manifest-tests/failure-domains/test_machines.py
Distribute Control plane machines across user-defined failure domains.
This feature is being release under a TechPreviewNoUpgrade FeatureSet.
Failure domains can be defined in the `controlPlane` machine-pool of `install-config.yaml` as follows:
```yaml
controlPlane:
name: master
platform:
openstack:
type: ${CONTROL_PLANE_FLAVOR}
failureDomains:
- computeAvailabilityZone: 'nova-1'
storageAvailabilityZone: 'cinder-1'
portTargets:
- id: storage
network:
id: 8db6a48e-375b-4caa-b20b-5b9a7218bfe6
- computeAvailabilityZone: 'nova-2'
storageAvailabilityZone: 'cinder-2'
portTargets:
- id: storage
network:
id: 39a7b82a-a8a4-45a4-ba5a-288569a6edd1
- computeAvailabilityZone: 'nova-3'
storageAvailabilityZone: 'cinder-3'
portTargets:
- id: storage
network:
id: 8e4b4e0d-3865-4a9b-a769-559270271242
``` …
=> OpenStack Failure domains

cmd/openshift-install/agent.go, cmd/openshift-install/testdata/agent/pxe/configurations/sno.txt
This feature has only partly landed, and is likely to be in a broken state. Disable the command that has landed, so that we can defer to a future release.
=> OCPBUGS-8353: Disable 'create pxe-files' command

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.13 boot image metadata in the installer.
```
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --no-signatures --url https://rhcos.mirror.openshift.com/art/storage/prod/streams x86_64=413.92.202302171914-0 aarch64=413.92.202302171914-0 s390x=413.92.202302171914-0 ppc64le=413.92.202302171914-0
```
=> update RHCOS 4.13 bootimage metadata

data/data/openstack/bootstrap/main.tf, data/data/openstack/masters/private-network.tf, data/data/openstack/variables-openstack.tf, pkg/tfvars/openstack/openstack.go
This commit enables the usage of more than one API and ingress VIP, which is required by Dual-Stack clusters.
=> OpenStack: support multiple API and ingress VIPs

data/data/baremetal/bootstrap/main.tf, data/data/libvirt/bootstrap/main.tf
The storage volume of the bootstrap VM with a max size of 20GB seems to be too small for OKD 4.13 with SCOS and 3 redfish-virtualmedia boot isos. Let's increase it to 32GB.
Fixes #6891
=> data: libvirt: increase volume size to 32GB

terraform/providers/vsphereprivate/resource_vsphereprivate_import_ova.go
In the progression of execution when
the terraform private resource has been
reached we should have already validated the
paths completely.
This PR removes the regular expressions
that is causing the terraform import failure.
=> OCPBUGS-7063: vSphere - Remove regexs in terraform ova import

pkg/asset/cluster/tfvars.go, pkg/asset/machines/gcp/machines.go, pkg/types/validation/installconfig.go, pkg/types/validation/installconfig_test.go
Manual backport of #6522 
Looks like this didn't make it into 4.12 :/
=> OCPBUGS-7469: [release-4.12] GCP XPN Featuregates

data/data/bootstrap/bootstrap-in-place/files/opt/openshift/bootstrap-in-place/bootstrap-in-place-post-reboot.sh
When installing SNO with bootstrap in place it takes CVO 6 minutes to acquire the leader lease
This code delete the cvo lease that was created during bootstrapping, allowing cvo to start faster without waiting for the lease to end.
=> Shorten SNO installation duration by releasing CVO lease 

pkg/asset/machines/aws/machines.go
Installer inserts AWS userTags provided via install config into Machine and Machineset manifests that it generates. The userTags need to be ordered before adding to AWSMachineProviderConfig. This way when CPMS-operator compares its control plane & worker machines with the Installer generated manifests, it does not flag them as different.
=> OCPBUGS-10394: Sort userTags in Machine and Machineset manifests

pkg/asset/agent/image/baseiso.go, pkg/asset/agent/image/oc.go
The command `oc image extract --path <file>:<dir> ...` will not return an error even if the file is not extracted. Add a check to ensure that the file was extracted from the release image. If not, then fail the `create image` command.
=> OCPBUGS-9949: Verify output file exists when `oc image extract` is run

pkg/asset/installconfig/nutanix/nutanix.go, pkg/asset/installconfig/vsphere/vsphere.go
This commit removes validation to ensure the ingress and API vips are in the default machine network cidr. This validation was added to all on-prem platforms. Installs have worked without this validation since the release of openshift 4 and the new requirements seems to be causing user issues. So we are relaxing the validation to be consistent with previous releases and because there is not a clear need for the validation.
=> OCPBUGS-7015: vsphere, nutanix survey: relax vip in machine cidr

pkg/asset/agent/image/ignition.go, pkg/asset/agent/image/ignition_test.go, pkg/asset/agent/mirror/registriesconf.go
A warning message about missing entry in ImageContentSources is always generated when the releaseImage is a digest. Fix to handle all cases of the image format and reuse a common function for this, along with some minor code cleanup.
=> OCPBUGS-10207: Do not always output warning msg when releaseImage is digest

docs/user/aws/install_existing_vpc_local-zones.md
Persisting in the installer's doc the suggestion to adapt the product documentation:
- remove `jq` dependency
https://issues.redhat.com/browse/OSDOCS-5240
https://github.com/openshift/installer/pull/6931
https://github.com/openshift/installer/pull/6371
=> OSDOCS-5240: doc/fix-aws-localzones: replace jq to aws --query

pkg/asset/machines/openstack/machines.go, scripts/openstack/manifest-tests/failure-domains/install-config.yaml, scripts/openstack/manifest-tests/failure-domains/test_machines.py
When a "control-plane" portTarget is set, masters should not have the machinesSubnet in the "primarySubnet" field of their Machine ProviderSpec.
I don’t want to change any behaviour unrelated to failure domains in this PR, but in a follow-up we could and should stop setting primarySubnet in all cases.
=> OCPBUGS-10570: openstack: No master primarySubnet control-plane if portTarget is set

docs/user/openstack/README.md
Our indicated supported version was incorrect. Rather than having to remember to update it for each new OSP version, simply remove this snippet.
The LB FIP is now called the API FIP.
=> openstack: Remove version info, update lb FIP -> API FIP

pkg/asset/installconfig/powervs/session.go, pkg/asset/installconfig/powervs/validation_test.go, pkg/asset/quota/quota.go
Make sure before creating a cluster that we have enough capacity in the system pool.
@TODO I cannot currently find documentation which describes what
PowerVS uses internally for the "Shared" option.  Therefore, we
do not check for capacity if masters or workers use it.
https://issues.redhat.com/browse/MULTIARCH-2115
=> PowerVS: Add capacity checks before installation

data/data/bootstrap/files/usr/local/bin/bootstrap-pivot.sh.template
If bootstrap is running in a Live ISO of SCOS `rpm-ostree pivot` will fail as /usr is not writable. Live ISO is used in assisted-installer flow and it doesn't need to pivot machine-os-content during bootstrap (it would write SCOS image on disk and run pivot via machine-config-daemon-pivot service). 
This change unblocks OKD Stream isntall using assisted-installer
=> OCPBUGS-9982: bootstrap-pivot: skip pivot in SCOS Live ISO

data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template, pkg/tfvars/baremetal/baremetal.go
This port is too common, we have received objections from infosec teams
to open it on firewalls. Switch to 6180 which is already used by
cluster-baremetal-operator for the same purpose in day 2 operations.
=> OCPBUGS-8509: baremetal: do not use port 80 for httpd

pkg/destroy/ibmcloud/dns.go, pkg/destroy/ibmcloud/ibmcloud.go
Set the offset when going through the DNS Services Resource Records for deletion, during destroy, making sure we go through all records.
Related: https://issues.redhat.com/browse/OCPBUGS-7973
=> OCPBUGS-7973: IBMCloud set dnsrecords offset

data/data/coreos/rhcos.json
OCPBUGS-10609 - Request for NetworkManager fix in RHCOS for IPv6 hostname lookup failure
```
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --no-signatures --url https://rhcos.mirror.openshift.com/art/storage/prod/streams x86_64=412.86.202303211731-0 aarch64=412.86.202303211731-0 s390x=412.86.202303211731-0 ppc64le=412.86.202303211731-0
```
=> OCPBUGS-10740: bump RHCOS 4.12 bootimage metadata

data/data/ibmcloud/bootstrap/main.tf, data/data/ibmcloud/bootstrap/variables.tf, data/data/ibmcloud/network/outputs.tf, data/data/ibmcloud/network/vpc/outputs.tf, data/data/ibmcloud/network/vpc/security-groups.tf
Fix IBM Cloud SecurityGroupRule for the bootstrap node, to allow SSH access to the node from any node within the private network, across all VPC availability zone subnets (10.x), such as a bastion host running IPI.
Related: https://issues.redhat.com/browse/OCPBUGS-8035
=> OCPBUGS-8035: IBMCloud: Fix SSH Private bootstrap

pkg/destroy/openstack/openstack.go, pkg/destroy/openstack/semaphore.go
With this change:
* listing of container object is no longer limited to 50, but left to the default (which is 10000 on a standard Swift configuration);
* the object deletion calls are issued in concurrent goroutines rather than serially, giving Swift a chance to work them in parallel.
The goal of this change is to tackle waiting times on OCP destroy on clusters with massive amounts of data stored in OpenStack object storage.
=> OCPBUGS-9081: openstack/destroy: BulkDelete more objects at once

data/data/ibmcloud/bootstrap/main.tf
Use the direct COS endpoint when managing COS resources on IBM Cloud.
Related: https://issues.redhat.com/browse/OCPBUGS-2363
=> OCPGUS-2363: IBMCloud: Use direct COS endpoint

cmd/openshift-install/agent.go
This fixes the behavior when an unexpected string is passed to the `agent create` command and it generates an unexpected error message instead of help.
Current:
```
$ openshift-install agent create foo
FATA[0000] Error executing openshift-install: accepts 0 arg(s), received 1
```
Fix:
```
$ openshift-install agent create foo
Commands for generating agent installation artifacts
Usage:
openshift-install agent create [flags]
openshift-install agent create [command]
Available Commands:
agent-config-template Generates a template of the agent config manifest used by the agent installer
cluster-manifests     Generates the cluster definition manifests used by the agent installer
image                 Generates a bootable image containing all the information needed to deploy a cluster
<rest of …
```
=> OCPBUGS-10638: Properly handle invalid agent command

pkg/quota/gcp/usage.go
… to usages
timeseries returned by 
serviceruntime.googleapis.com/quota/allocation/usage can return other project_ids than intended.
With the filters added in the PR, only usages in the intended project will be used to match with limits of the same project.
Previously, it is possible to by chance have limits from intended project, and usage from an incorrect project accessible by the account that can lead to incorrect quota calculation (including potentially negative quota) that prevents an otherwise capable account from launching a cluster.
Negative quota can occurs if selected project has lower limits than other projects and the quota code happen to match it up with usage from a higher limit projects.
Example occurrence at breakpoint reference …
=> OCPBUGS-10728 add project filter to gcp usage api requests

pkg/asset/tls/kubelet.go
The certificate here is meant to represent the system node bootstrapper service account. When authenticated, the username in K8s comes from the common name, and the groups come from the organization.
This is important, because this certificate is used by all nodes during the bootstrap process to request bootstrap client credentials. When a CSR is requested, the Kube API server records the username and groups within the CSR object.
The cluster machine approver then verifies that the expected bootstrap service account created the request, before assessing whether it should approve the client CSR or not.
Service accounts normally have two groups, the generic all service accounts group, and the namespace scoped group. This was missing the all service accounts group.
Adding this in should mean …
=> OCPBUGS-8349: Kubelet Client Cert should include system:serviceaccounts group

pkg/asset/installconfig/vsphere/client.go, pkg/asset/installconfig/vsphere/validation.go, pkg/asset/installconfig/vsphere/validation_test.go
In previous releases we didn't use full paths for
cluster. Since we are now using full paths generating the path is incorrect. This PR removes that.
=> OCPBUGS-2130: vSphere - finding networks use full path cluster

docs/user/azure/tested_instance_types_x86_64.md
Docs update:
1. remove `standardDCSFamily` due to unable to verify it with insufficient quota
2. add two new families `standardDLDSv5Family` `standardDLSv5Family` which are tested passed on 4.13 nightly build.
=> [azure] update tested instance type on 4.13

data/data/bootstrap/files/usr/local/bin/kubelet.sh.template, docs/user/customization.md
removes the container-runtime=remote flag to correlate with:
```
CHANGELOG/CHANGELOG-1.27.md
478:- Kubelet: remove deprecated flag `--container-runtime` 
```
ref: https://github.com/kubernetes/kubernetes/pull/114017
=> OCPBUGS-11039: remove container-runtime flag from kubelet config

terraform/Makefile
If we build the terraform provider binaries, then change one of them so that it fails to build and try running `make -C terraform` without running `make -C clean` we might miss the build failure.
For example:
```
make: Entering directory '/home/rfonseca/prjs/upstream/openshift/installer/terraform'
cd providers/google; \
if [ -f main.go ]; then path="."; else path=./vendor/`grep _ tools.go|awk '{ print $2 }'|sed 's|"||g'`; fi; \
go build -gcflags "" -ldflags "-s -w" -o ../../bin/linux_amd64/terraform-provider-google "$path"; \
zip -1j ../../bin/linux_amd64/terraform-provider-google.zip ../../bin/linux_amd64/terraform-provider-google;
vendor/github.com/hashicorp/terraform-provider-google/google/resource_storage_bucket.go:1063:37: cannot convert condition.Age (variable of type *int64) to …
```
=> terraform: don't run zip if building provider binary failed

images/openstack/Dockerfile.ci
Note: these are rhel-8 images for 4.14.
cf https://github.com/openshift/installer/blob/master/images/installer/Dockerfile.ci
=> openstack: Bump CI base image to v4.14

docs/user/openstack/invalid-https-certificates.md
Before this change the validation steps, and the script, assumed that `internal` and `admin` OpenStack endpoints were always reachable. With this change, the manual steps and the script are amended to only check the validity of HTTPS certificates on the `public` endpoints of the OpenStack catalog.
In a separate commit, this PR fixes a syntax issue in the script that could cause it to crash when the OpenStack catalog contained an URL that is not HTTP and not HTTPS.
=> OCPBUGS-7954: openstack: Only check HTTPS certs on public endpoints

cmd/openshift-install/agent.go, cmd/openshift-install/graph.go, cmd/openshift-install/testdata/agent/graph/graph.txt
This patch adds the equivalent installer `graph`  command for the `agent` specific targets
=> AGENT-275: Add new agent graph command to output agent internal dependency graph

data/data/gcp/bootstrap/main.tf
This change adds the [confidential compute configuration options](https://github.com/openshift/installer/pull/6799) for the GCP bootstrap machine as well.
The confidential compute configuration options for the bootstrap instance are defined by the respective control-plane instance options.
The scheduling and confidential_instance_config options are defined as dynamic blocks and they will be applied when the user specifies the respective config options. This allows us to respect the cloud provider defaults, when the user does not provide any values. At the same time, it does not require code updates when the cloud provider defaults change.
Feature link: https://issues.redhat.com/browse/OCPBU-142
/cc @eranco74
=> gcp: add confidential compute support for boostrap TF

docs/user/gcp/install_upi.md
* Updated the link to the rhcos.json to point to the new location in the Installer repo (data/data/coreos/rhcos.json)
* Updated the json path to include the architecture and the images content.
* Changed the instruction to use the existing boot image in the rhcos-cloud project instead of copying it as a new image.
=> docs: gcp: upi: update obtaining RHCOS source image

pkg/asset/agent/image/agentimage.go, pkg/asset/agent/image/oc.go
The version of libnmstate in the release image changed from 1.x to 2.x. Use a wildcard match to handle the upgrade which can be used in a generic way with other libraries.
Tested with both libnmstate.so.1.3.3 (currently 4.14 until a CI release passes) and 2.2.9 (4.13)
$ ls -al /home/stack/.cache/agent/files_cache/
total 15592
drwxr-xr-x. 2 stack stack      73 Apr 10 13:40 .
drwxr-xr-x. 4 stack stack      44 Apr  6 09:05 ..
-r-xr-xr-x. 1 stack stack 9284768 Mar 30 16:29 agent-tui
lrwxrwxrwx. 1 stack stack      19 Aug 15  2022 libnmstate.so.1 -> libnmstate.so.1.3.3
-r-xr-xr-x. 1 stack stack 6678840 Aug 15  2022 libnmstate.so.1.3.3
$ ls -al /home/stack/.cache/agent/files_cache
total 16872
drwxr-xr-x. 2 stack stack      73 Apr 10 12:33 .
drwxr-xr-x. 4 stack stack      44 Apr  6 09:05 .. …
=> OCPBUGS-11479: Upgrade libnmstate version used

data/data/aws/bootstrap/main.tf
AWS has recently disabled ACL support by default. See https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/ for further information.
This commit removes our usage of ACLs. By default, S3 buckets will have public access blocked.
=> OCPBUGS-11662: AWS - Remove ACLs from s3 ign

data/data/aws/bootstrap/main.tf
AWS has recently disabled ACL support by default. See https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/ for further information.
This commit removes our usage of ACLs. By default, S3 buckets will have public access blocked.
=> OCPBUGS-11663: AWS - Remove ACLs from s3 ign

data/data/alibabacloud/cluster/vpc/eip.tf
=> OCPBUGS-10673: [Alibaba] update the bandwidth value of EIP

pkg/agent/cluster.go, pkg/agent/waitfor.go
When the cluster status is installing-pending-user-action the install won't complete. Most likely this is due to an invalid boot disk. In the `wait-for bootstrap-complete` also log the host's status_info for hosts that have this status.  In addition, don't continuously log the same errors in bootstrap such as occurs when this failure happens.
As an example, the `wait-for` output when an invalid boot disk is used is now:
```
level=info msg=Cluster has hosts requiring user input
level=debug msg=Host master-1 Expected the host to boot from disk, but it booted the installation image - please reboot and fix boot order to boot from disk QEMU_HARDDISK drive-scsi0-0-0-0 (sda, /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0)
level=debug msg=Host master-2 Expected the host to boot from disk, but it …
```
=> OCPBUGS-4998: Log additional info when status is pending-user-action

pkg/rhcos/ami_regions.go
Otherwise the log message looks like
```
time="2023-04-06T17:03:26Z" level=error msg="could not fetch the rhcos stream data: %wfailed to read embedded CoreOS stream metadata: open data/coreos/rhcos.json: no such file or directory"
```
=> pkg: rhcos: use Errorf instead of Error

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.13 bootimage metadata.
```
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --no-signatures --name 4.13-9.2 --url https://rhcos.mirror.openshift.com/art/storage/prod/streams x86_64=413.92.202304131328-0 aarch64=413.92.202304131328-0 s390x=413.92.202304131328-0 ppc64le=413.92.202304131328-0
```
=> OCPBUGS-11789: update RHCOS 4.13 bootimage metadata to 413.92.202304131328-0

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.14 boot image metadata.
```
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --no-signatures --name 4.14-9.2 --url https://rhcos.mirror.openshift.com/art/storage/prod/streams x86_64=414.92.202304131328-0 aarch64=414.92.202304131328-0 s390x=414.92.202304131328-0 ppc64le=414.92.202304131328-0
```
=> OCPBUGS-11788: update RHCOS 4.14 bootimage metadata to 414.92.202304131328-0

pkg/asset/installconfig/aws/metadata.go, pkg/asset/installconfig/aws/validation_test.go
This fix eliminates the need for mutexSubnets to update subnet
information within AWS metadata. It also updates populateSubnets
to take care of getting VPC and subnets once for the installation
eliminating duplicate code that could be prone to errors.
=> OCPBUGS-10767: Fix and improve locking session and AWS Metadata access

data/data/openstack/masters/sg-master.tf, data/data/openstack/masters/sg-worker.tf
Enable ingress traffic for api and ingress. Note that no internal communication over IPv6 is enabled because OpenStack has no support yet for IPv6 primary clusters, consequently IPv4 is always enforced.
=> OpenStack: enable ingress traffic for dual-stack installations

cmd/openshift-install/agent_internal_integration_test.go, cmd/openshift-install/testdata/agent/image/assets/default_assets.txt, pkg/asset/agent/image/agentimage.go, pkg/asset/agent/image/cpio.go, pkg/asset/agent/image/oc.go
This patch fixes the https://issues.redhat.com/browse/OCPBUGS-11801 bug by:
* removing the hard-coded version when extracting libnmstate
*  copying also the symlinks in the agent cpio archive
Due a recent bump in the repos, the agent-tui (currently shipped in the `agent-installer-node-agent` image) is now comprised of the following files:
```
agent-tui
libnmstate.so.2 -> libnmstate.so.2.2.9 (symlink)
libnmstate.so.2.2.9
```
=> OCPBUGS-11801: Fix agent-tui libnmstate dependency name

pkg/asset/manifests/topologies.go
Removing the feature check for tech preview when applying the cpu partitioning flag. This is no longer needed on the installer side.
=> OCPBUGS-11999: fix: remove feature flag for cpu partitioning no longer needed

data/data/manifests/bootkube/cvo-overrides.yaml.template
After 4.14 branching, bump CVO to the correct version.
=> OCPBUGS-12196: bump CVO to stable-4.14

cmd/openshift-install/agent_internal_integration_test.go, cmd/openshift-install/testdata/agent/image/assets/default_assets.txt, pkg/asset/agent/image/agentimage.go, pkg/asset/agent/image/cpio.go, pkg/asset/agent/image/oc.go
This is a manual cherry-pick of #7095
=> [release-4.13] OCPBUGS-12179: agent: copy also symbolic link when storing agent-tui related files into the agent ISO

data/data/alibabacloud/cluster/vpc/eip.tf
=> OCPBUGS-5140: [Alibaba] update the bandwidth value of EIP

images/installer/Dockerfile.upi.ci
We got "_ERROR: Python 2 is not compatible with the Google Cloud SDK. Please use Python version 3.5 and up_" (see [job](https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.14-amd64-nightly-gcp-ipi-proxy-private-p1-f4/1649243964022198272)) recently, so set the env `CLOUDSDK_PYTHON` as `/usr/bin/python3`.
=> OCPBUGS-12748: use python3 for cloud sdk

pkg/asset/agent/image/ignition_test.go, pkg/asset/agent/manifests/nmstateconfig_test.go
Due to a CI configuration issue (lack of nmstatectl in the image), the current CI [unit-test job](https://github.com/openshift/release/blob/a8a9d08406fc099a421b89b51a317c7ebfe92610/ci-operator/config/openshift/installer/openshift-installer-master.yaml#L205-L211) skips silently those unit tests requiring nmstatectl.
This patch thus:
1) Fixes the old test issues that have been silently ignored
2) Fixes a new test issue due the introduction of a newer nmstate version
*Note:* in the current PR these changes will continue to be skipped. Once merged, another PR https://github.com/openshift/release/pull/38290 will enable them
In addition, a test case has been temporarily disabled due a regression in nmstate 2.2.9
=> OCPBUGS-12869: fix nmstate related unit tests

pkg/asset/cluster/tfvars.go
** Do no look for a public zone if this is a private cluster. It would not be used anyway, but the look up would always fail if there was no public zone with the same DNS name.
=> OCPBUGS-12776: GCP XPN Private Cluster Fails with no Public Zone

images/openstack/Dockerfile.ci
ncat is needed for setting up load balancer and proxy environments in the CI.
=> OCPBUGS-12904: openstack: Add netcat to the Installer image

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template, pkg/asset/manifests/featuregate.go
For https://github.com/openshift/enhancements/pull/1373
I could probably live with this having to be vendored sometimes, but it would make me sad.
Part 5 of the three step plan to make individual featuregates observable via the API. This was previously avoided because when featuregates get promoted from TechPreview to Default, during an upgrade, an old operator may try to enable a TechPreview variant of a feature.
This builds on https://github.com/openshift/cluster-config-operator/pull/288 with a goal of making the development-time flow
1. update openshift/api with new featuregate
2. vendor into near zero-dep openshfit/cluster-config-operator (automated someday?)
3. done.
with a runtime flow of
1. installer builds the featuregate.yaml with spec completed
2. bootkube passes …
=> pass featuregate args to config-operator to get rendered featuregates

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.14 boot image metadata.
```
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --no-signatures --name 4.14-9.2 --url https://rhcos.mirror.openshift.com/art/storage/prod/streams x86_64=414.92.202304252144-0 aarch64=414.92.202304252144-0 s390x=414.92.202304252144-0 ppc64le=414.92.202304252144-0
```
=> OCPBUGS-11792: update RHCOS 4.14 bootimage metadata to 414.92.202304252144-0

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.13 bootimage metadata which include fixes for the following:
OCPBUGS-11791 - RHCOS missing udev rules for GCE PD NVMe disks in initrd
```
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --no-signatures --name 4.13-9.2 --url https://rhcos.mirror.openshift.com/art/storage/prod/streams x86_64=413.92.202305021736-0 aarch64=413.92.202305021736-0 s390x=413.92.202305021736-0 ppc64le=413.92.202305021736-0
```
=> OCPBUGS-11799: update RHCOS 4.13 bootimage metadata to 413.92.202305021736-0

data/data/aws/bootstrap/main.tf, data/data/aws/bootstrap/variables.tf, data/data/aws/variables-aws.tf, pkg/tfvars/aws/aws.go
OCPBUGS-12964: Bootstrap on aws should have same metadata service type as on other nodes
=> OCPBUGS-12964: Bootstrap on aws should have same metadata service type as on other nodes

data/data/alibabacloud/cluster/vpc/eip.tf
=> OCPBUGS-12749: [Alibaba] update the bandwidth value of EIP

pkg/asset/machines/gcp/machines.go
The installer service account was being passed through only in pass through mode, which meant manual mode installs would always fail.
=> OCPBUGS-11921: GCP XPN: Pass instance service acct in manual mode

pkg/destroy/openstack/openstack.go
down from 10. More than that killed RabbitMQ on a standalone OpenStack cloud.
Also add a smidge of logging information.
=> OCPBUGS-13107: openstack destroy: Limit Swift workers to 3

data/data/coreos/rhcos.json
OCPBUGS-12888 Request for RHCOS build to encompass fixes in Systemd and SELinux
OCPBUGS-8081 Agent based installer will always fail to install 3 node cluster with BareMetal ( HPE ProLiant BL460c Gen9) with SAN storage.
```
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --no-signatures --url https://rhcos.mirror.openshift.com/art/storage/prod/streams x86_64=412.86.202305030814-0 aarch64=412.86.202305030814-0 s390x=412.86.202305030814-0 ppc64le=412.86.202305030814-0
```
=> OCPBUGS-13052: bump RHCOS 4.12 bootimage metadata

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Passes the feature gate and featureset values used for rendering via the FeatureGate manifest contained in rendered manifests.  The dependencies in operators should now be complete.
=> pass payload version and manifests to kas and kcm

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.14 boot image metadata.
Notably this includes kubevirt artifacts for the first time which is part of JIRA issue COS-1232.
```
x86_64=414.92.202305090606-0                                      \
aarch64=414.92.202305090606-0                                     \
s390x=414.92.202305090606-0                                       \
ppc64le=414.92.202305090606-0
```
=> OCPBUGS-13253: update RHCOS 4.14 bootimage metadata to 414.92.202305090606-0

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
This completes the reset for rendering featureset sensitive manifests based on the FeatureGate manifest provided by the cluster-config-operator.
=> remove special cases for featureset in rendering

data/data/bootstrap/baremetal/files/etc/NetworkManager/system-connections/nmconnection.template, data/data/install.openshift.io_installconfigs.yaml, pkg/asset/ignition/bootstrap/baremetal/template.go, pkg/asset/installconfig/baremetal/validation.go, pkg/types/baremetal/platform.go
Add `bootstrapExternalStaticDNS` option in `install-config.yaml` file to avoid using `bootstrapExternalStaticGateway` as DNS in the bootstrap node.
https://github.com/openshift/installer/blob/0f99618f1c2b45f07d394a5f3e9ddf6a6436bc2e/data/data/bootstrap/baremetal/files/etc/NetworkManager/system-connections/nmconnection.template#L14
=> OCPBUGS-3542: Add bootstrapExternalStaticDNS

docs/user/openstack/README.md, pkg/asset/machines/openstack/machines.go, scripts/openstack/manifest-tests/server-groups/install-config.yaml
2.5 years ago we allowed to configure `serverGroupPolicy` in
install-config so a user could choose which Nova scheduling policy
to adopt for the machines.
However, if the masters were configured with AZ, Terraform would
create one ServerGroup in OpenStack (the one from master-0) but
configure the Machine providerSpec with different ServerGroups, one
per AZ. This was unwanted and now we want to use a single ServerGroup
for masters.
With compute AZ support, the users already have the possibility to
ensure that masters aren't on the same failure domain as others.
Also, even if there is less than 3 AZs (e.g. 2), the default
`soft-anti-affinity` server group policy would make Nova to
scheduling in best effort the machines on different hosts within a same
AZ.
Therefore, there is no need to …
=> OCPBUGS-13300: masters on a single compute server group

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Reverts openshift/installer#7158, tracked by OCPBUGS-13628
Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get  payloads flowing again.
Since this landed, all installs are failing.  See https://amd64.ocp.releases.ci.openshift.org/releasestream/4.14.0-0.nightly/release/4.14.0-0.nightly-2023-05-12-064129 for example jobs.
It looks like https://github.com/openshift/library-go/pull/1528 plus a revendor in cluster-config-operator is needed for this to work.  If possible please try the relevant PR's together perhaps using cluster-bot to prove this change doesn't break.
CC: @deads2k, @patrickdillon
=> OCPBUGS-13628: Revert "remove special cases for featureset in rendering"

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
In tandem with https://github.com/openshift/machine-config-operator/pull/3701 and working towards https://github.com/openshift/machine-config-operator/pull/3688, I am introducing a `--payload-version` requirement for the render command for MCO, so that it can read feature gates on bootstrap.
/hold 
I want to prove with cluster-bot that this works before merging
=> OCPBUGS-13547: Ensure --payload-version is set for MCO on bootstrap

data/data/vsphere/bootstrap/main.tf, data/data/vsphere/master/main.tf
This commit forces the `firmware` to only use
EFI.
=> OCPBUGS-9378: vSphere set bootstrap/master efi

pkg/asset/installconfig/azure/validation.go, pkg/asset/installconfig/azure/validation_test.go
"StandardSSD_LRS" is not a supported disk type and will result in the following failure:
```
level=error msg=Error: expected storage_os_disk.0.managed_disk_type to be one of [Premium_LRS Standard_LRS], got StandardSSD_LRS
level=error
level=error msg=  with azurestack_virtual_machine.bootstrap,
level=error msg=  on main.tf line 107, in resource "azurestack_virtual_machine" "bootstrap":
level=error msg= 107: resource "azurestack_virtual_machine" "bootstrap" {
level=error
```
Let's make sure that only Premium_LRS or Standard_LRS can be specified for AzureStack.
=> OCPBUGS-13718: ic: azure: validate diskTypes in AzureStack

pkg/asset/rhcos/image.go, pkg/tfvars/internal/cache/cache.go, terraform/providers/vsphereprivate/resource_vsphereprivate_import_ova.go
We have been experiencing issues with OVA
corruption for quite a while. In investigating
this issue it seems the provided sha256 for the OVA
was being left unused. This PR adds `sha256` query
so that upon download of the OVA the integrity
will be checked.
In addition the content length of the body GET
along with the io.Copy bytes written is outputted
when debugging is enabled.
Further debugging was added to the vsphereprivate
resource if and when parsing of the OVF descriptor
fails. It checks the SHA256 and provides the size of
the OVA for additional checking.
=> OCPBUGS-13552: vSphere Add ova sha query; additional debugging

pkg/asset/agent/installconfig_test.go, pkg/asset/installconfig/nutanix/nutanix.go, pkg/asset/installconfig/vsphere/vsphere.go, pkg/types/validation/installconfig.go, pkg/types/validation/installconfig_test.go
Manual backport of #6915 and #6967
=> OCPBUGS-12202: Relax vsphere, nutanix VIP validation

pkg/asset/machines/powervs/machinesets.go
Remove changing the image name for a MachineSet if ClusterOSImage is set
Terraform has already created an image bucket based on OPENSHIFT_INSTALL_OS_IMAGE_OVERRIDE
for us. So worker nodes should not use OPENSHIFT_INSTALL_OS_IMAGE_OVERRIDE directly and
instead use the image bucket.
=> OCPBUGS-14076: PowerVS: Remove ClusterOSImage

pkg/types/defaults/installconfig.go, pkg/types/powervs/defaults/platform.go
Use a random number for DefaultMachineCIDR: 192.168.%d.0/24 This should significantly reduce the chances for collisions.
=> OCPBUGS-14077: MULTIARCH-3492: Avoid conflicting subnets

pkg/asset/agent/agentconfig/agent_config.go, pkg/asset/agent/agentconfig/agent_config_test.go, pkg/types/baremetal/rootdevice.go, pkg/types/baremetal/validation/platform.go, pkg/types/baremetal/validation/platform_test.go
Update the installer/terraform implementation to match the Metal³ changes in [OCPBUGS-13080](https://issues.redhat.com/browse/OCPBUGS-13080) so that control plane and worker machines will have equivalent functionality.
This includes accepting /by-path/ paths and adding validation to ensure that invalid paths that can't ever match are rejected immediately. The code to construct the HardwareDetails for the status annotation of the control plane hosts runs in the baremetal-operator container so it always matches and no changes are needed here.
=> OCPBUGS-13764: Support /dev/disk/by-path root device hints

cmd/openshift-install/agent.go, cmd/openshift-install/testdata/agent/pxe/configurations/sno.txt
This reverts commit 93f78427bb73a7046b7f57dca6c8cf4f837ade4a from PR https://github.com/openshift/installer/pull/6927 and enables the `create pxe-files` command
=> AGENT-567: Re-enable 'create pxe-files' command

data/data/alibabacloud/cluster/vpc/eip.tf
=> OCPBUGS-12750: [Alibaba] update the bandwidth value of EIP

pkg/types/baremetal/rootdevice.go
In baremetal IPI, we should support /dev/disk/by-path root device hints in the install-config to match the implementation in Metal³.
=> [release-4.13] OCPBUGS-13765: Support /dev/disk/by-path root device hints

pkg/asset/agent/installconfig.go
Print a warning if `CPUPartitioning` is set to a non-default value.
=> OCPBUGS-13662: Ignore CPUPartitioning for ABI

pkg/agent/cluster.go, pkg/agent/waitfor.go
When the host fails to boot due to pending-user-action (this can occur when the disk boot order is set incorrectly) log the message at Warning level instead of Debug to make it obvious.
This also removes an additional spurious info message that was being logged.
=> OCPBUGS-13108: Log additional host info at warning level

images/installer/Dockerfile.upi.ci.rhel8
update upi-installer image on rhel8 container
1.  remove downloading 'govc' and replace with govc docker image, sync with change in `Dockerfile.upi.ci` https://github.com/openshift/installer/blob/master/images/installer/Dockerfile.upi.ci#L13
2.  fix ibmcli folder permission issue detected in https://github.com/openshift/release/pull/39991, should be https://github.com/openshift/installer/blob/master/images/installer/Dockerfile.upi.ci#L96 
```
[3/3] STEP 26/32: RUN chown 1000:1000 /output && chmod -R g=u "$HOME/.bluemix/"
chmod: cannot access '/root/.bluemix/': No such file or directory
error: build error: building at STEP "RUN chown 1000:1000 /output && chmod -R g=u "$HOME/.bluemix/"": while running runtime: exit status 1
```
=> OCPBUGS-14565: Replace with govc docker image and fix ibmcli folder permission issue

data/data/bootstrap/bootstrap-in-place/files/opt/openshift/bootstrap-in-place/bootstrap-in-place-post-reboot.sh
When installing Single Node OpenShift with bootstrap in place, it takes 6 minutes for the `cluster-policy-controller` to acquire the leader lease. This leads to some OpenShift namespaces not getting the `openshift.io/sa.scc.uid-range` annotation during that time, i.e. no pods can be scheduled in them.  Which in turn leads to delaying the installation completion.
This change deletes the cluster-policy-controller lease, which was created during bootstrapping. This allows the latter to start sooner, without waiting for the lease to expire.
/cc @eranco74 
/cc @tsorya
=> OCPBUGS-14416: Shorten SNO installation duration by releasing CPC lease

pkg/asset/agent/image/ignition.go, pkg/asset/agent/image/ignition_test.go
If the RendezvousIP is provided as a non-canonical (i.e. not compressed) IPv6 address then the IP comparison on the host will fail. Use ParseIp() address to convert this to canonical format. Note that this function will not affect the IPv4 address format.
=> OCPBUGS-14121: Convert Rendezvous IPv6 address to canonical format

data/data/agent/files/usr/local/bin/set-node-zero.sh
Block in the node-zero service for the rendezvous host configuration to
exist. In future this will allow the configuration to be added later,
either interactively or by introducing a config image.
=> AGENT-556: Wait for rendezvous host configuration

pkg/asset/installconfig/platform.go, pkg/types/installconfig.go, pkg/types/ovirt/validation/platform.go, pkg/types/ovirt/validation/platform_test.go, pkg/types/validation/installconfig_test.go
This PR disables oVirt as a supported platform by 
- removing it as an option from the interactive install
- and returning an validation error when using an `install-config.yaml`
=> OCPBUGS-14818: disable oVirt provider

images/installer/Dockerfile.upi.ci.rhel8
It was installed by default in RHEL-7 and is needed by some steps in CI.
=> OCPBUGS-14757: images: installer: add xz to the container

data/data/bootstrap/openstack/files/etc/NetworkManager/system-connections/nmconnection.template
This commit adds a template that configures IPv6 addresses in the ethernet interface of the bootstrap host when creating a dual-stack cluster for any type of IPv6 address stateful/slaac. Without it the bootstrap node wouldn't have the correct IPv6 address configured.
Partially Implements: https://github.com/openshift/enhancements/pull/1365
=> OpenStack: configure IPv6 address in the bootstrap node

data/data/openstack/masters/private-network.tf, pkg/destroy/openstack/openstack.go, pkg/tfvars/openstack/openstack.go, pkg/types/openstack/defaults/platform.go
When using dual-stack installations the user needs to pre-create the api and ingress port given OpenStack does not allow direct assignment of addresses when using slaac/stateless, consequently the installer can't create those. This commit adds support to tag those Ports, assign security groups to them, attach the Floating IP when needed and allow clean up of resources.
Partially implements: https://github.com/openshift/enhancements/pull/1365
=> OpenStack: support user provided dual-stack api and ingress Port

pkg/types/validation/installconfig.go
Previously we only supported primary-v6 dual-stack installations only on baremetal. As we are now extending full support of dual-stack to vSphere, we no longer need to enforce the order of networks on those clusters.
Closes: [OPNET-298](https://issues.redhat.com//browse/OPNET-298)
Contributes-to: [OPNET-230](https://issues.redhat.com//browse/OPNET-230)
=> OPNET-298: Allow primary-v6 dual-stack on vSphere

pkg/asset/machines/master.go, pkg/asset/machines/nutanix/machines.go
Set ControlPlaneMachineSet to Active. This generates a `ControlPlaneMachineSet` manifest in the openshift directory when running `create manifests` command.
**How was this tested?**
1. Create a CPMSO image with the changes in [cluster-control-plane-machine-set-operator#200](https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/200)
2. Create a new release image based on a [recent 4.14 release image](registry.ci.openshift.org/ocp/release:4.14.0-0.nightly-2023-04-19-125337) using `oc adm release new --from-release registry.ci.openshift.org/ocp/release:4.14.0-0.nightly-2023-04-19-125337 cluster-control-plane-machine-set-operator=image-registry:cluster-control-plane-machine-set-operator --to-image image-registry:release` and set the release image override environment …
=> [CORS-2666] Add ControlPlaneMachineSet for Nutanix

pkg/destroy/powervs/powervs.go, pkg/destroy/powervs/serviceinstance.go
New code has been added to create a new PowerVS service instance during create cluster.  Therefore, we need to clean it up during destroy cluster.
=> OCPBUGS-14917: PowerVS: Cleanup service instances for destroy cluster

cmd/openshift-install/testdata/agent/image/manifests/default_manifests.txt, pkg/asset/agent/image/agentimage.go, pkg/asset/releaseimage/default.go
Since `agent-installer-utils` image is now shipped within the release payload, it's then possible to start using it (instead of the temporary solution provided by `agent-installer-node-agent`) for extracting the agent-tui related artifacts
=> AGENT-596: use agent-installer-utils for agent-tui extraction

data/data/install.openshift.io_installconfigs.yaml, pkg/asset/installconfig/aws/ec2.go, pkg/asset/installconfig/aws/validation.go, pkg/asset/machines/aws/machines.go, pkg/asset/machines/aws/machinesets.go, pkg/types/aws/machinepool.go, pkg/types/aws/validation/machinepool.go, pkg/types/aws/validation/machinepool_test.go
Updates support [CORS-2631](https://issues.redhat.com//browse/CORS-2631) and [CORS-2632](https://issues.redhat.com//browse/CORS-2632)
=> CORS-2631: Add additional security group ids in AWS

data/data/install.openshift.io_installconfigs.yaml, pkg/explain/printer_test.go, pkg/types/azure/platform.go, pkg/types/validation/installconfig.go
Support for user defined tags for Azure resources was TechPreview only in openshift-4.13 which will be made GA in openshift-4.14. And the changes in this PR are for removing the indications on TechPreview and the featureSet check.
=> CFE-829: Remove Azure Tags TechPreview only indicators and checks

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.14 boot image metadata and includes fixes for:
OCPBUGS-8081 - Agent based installer will always fail to install 3 node cluster with BareMetal (HPE ProLiant BL460c Gen9) with SAN storage.
```
x86_64=414.92.202306141028-0                                      \
aarch64=414.92.202306141028-0                                     \
s390x=414.92.202306141028-0                                       \
ppc64le=414.92.202306141028-0
```
=> OCPBUGS-13960: update RHCOS 4.14 bootimage metadata to 414.92.202306141028-0

pkg/asset/machines/machineconfig/multipath.go, pkg/asset/machines/master.go, pkg/asset/machines/worker.go
Since IBM Power Virtual Servers environment supports multipath for disks including root, we need to enable multipath by default on this environment. Whenever anyone installs a cluster on PowerVS multipath becomes mandatory.
This will be used for running PowerVS CSI driver which again uses multipath.
JIRA: https://issues.redhat.com/browse/MULTIARCH-3664
=> MULTIARCH-3664: enable multipath for powervs

data/data/install.openshift.io_installconfigs.yaml, pkg/asset/manifests/featuregate.go, pkg/explain/printer_test.go, pkg/types/installconfig.go, pkg/types/validation/installconfig.go, pkg/types/validation/installconfig_test.go
To promote developers to use custom feature sets to develop their new features, we need the openshift installer to support custom features and custom feature sets. To do this, this PR adds a `customFeatures` field to the install config which accepts a list of `<name>=<bool>` feature names, that will then go into the generation of the feature gate manifest during the manifest generation stage.
=> Allow CustomNoUpgrade features via install-config

data/data/coreos/rhcos.json
The digest-ref was missing from the last set of boot image bumps.
=>     OCPBUGS-15095: Add kubevirt digest-ref in RHCOS boot images

data/data/agent/files/usr/local/bin/start-cluster-installation.sh, data/data/agent/files/usr/local/bin/start-cluster-installation.sh.template, data/data/agent/systemd/units/start-cluster-installation.service.template, pkg/asset/agent/image/ignition.go, pkg/asset/agent/image/ignition_test.go
Templating in shell scripts makes it impossible for us to run shellcheck
on them. Pass the data we need through environment variables and
template in the systemd unit.
=> Agent: run shellcheck on start-cluster-installation.sh

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
These command line arguments *should* be dead code since https://github.com/openshift/installer/commit/322d4fef843ec849ab839007d71e134ae31d6e72 landed; we just didn't drop them out of conservatism.
But it turns out that hyperkube has a duplicate of this code path; it's time to clean it up.  Add a cross reference to that code.
To rephrase and highlight: A key thing we've done here is entirely remove the need to change openshift/installer (*and* openshift/hyperkube) when adding a new image reference.
=> bootkube: Drop cruft in MCO bootstrap

docs/user/openstack/README.md, docs/user/openstack/external_load_balancer.md
First iteration to document external LB, when deploying OCP on OSP.
=> openstack: document external LB

pkg/destroy/gcp/address.go, pkg/destroy/gcp/backendservice.go, pkg/destroy/gcp/bucket.go, pkg/destroy/gcp/bucketobject.go, pkg/destroy/gcp/cloudcontroller.go, pkg/destroy/gcp/disk.go, pkg/destroy/gcp/dns.go, pkg/destroy/gcp/firewall.go, pkg/destroy/gcp/forwardingrule.go, pkg/destroy/gcp/gcp.go, pkg/destroy/gcp/healthcheck.go, pkg/destroy/gcp/httphealthcheck.go, pkg/destroy/gcp/image.go, pkg/destroy/gcp/instance.go, pkg/destroy/gcp/instancegroup.go, pkg/destroy/gcp/network.go, pkg/destroy/gcp/policybinding.go, pkg/destroy/gcp/route.go, pkg/destroy/gcp/router.go, pkg/destroy/gcp/serviceaccount.go, pkg/destroy/gcp/subnetwork.go, pkg/destroy/gcp/targetpool.go
** context structs should not be stored in another struct. Removed from GCP and altered the gcp destroy functionality to pass around the base context to all destroy functions and each will create a child off of the context.
=> CORS-2656: Remove context from cluster uninstaller struct

data/data/coreos/rhcos.json
OCPBUGS-13942 - RHCOS 4.12.3 and 4.12.10 on Z display the "swiotlb
buffer is full" message during KVM cluster Secure Execution (SE)
install boots for the bootstrap, master, worker nodes, elongating
boot durations
```
plume cosa2stream --target data/data/coreos/rhcos.json \
--distro rhcos --no-signatures \
x86_64=412.86.202306132230-0 \
aarch64=412.86.202306132230-0 \
s390x=412.86.202306132230-0 \
ppc64le=412.86.202306132230-0
```
=> OCPBUGS-13940: bump RHCOS 4.12 bootimage metadata to 412.86.202306132230-0

cmd/openshift-install/create.go
- Add timezone info - `until <time> <timezone>`
```
openshift-install wait-for install-complete --dir=install-dir
[...]
INFO Waiting up to 1h0m0s (until 4:52PM UTC) for the cluster at https://api.ocp.example.local:6443 to initialize...
[...]
```
```
TZ=Asia/Kolkata openshift-install wait-for install-complete --dir=install-dir
[...]
INFO Waiting up to 1h0m0s (until 5:55PM IST) for the cluster at https://api.ocp.example.local:6443 to initialize...
[...]
```
Fixes ocpbugs-14869
=> OCPBUGS-14869: Add timezone info in installer logs

pkg/asset/installconfig/alibabacloud/alibabacloud.go, pkg/types/alibabacloud/validation/platform.go
The Alibaba Cloud provider is soon going to be removed. This PR introduces a warning to users about the deprecation and a request for confirmation before to proceed with an installation in that provider. Doesn't affect the UX of other providers.
=> SPLAT-1094: warn users about deprecation of Alibaba Cloud

data/data/aws/cluster/route53/base.tf
Switching to use a CNAME instead of an ALIAS record is no longer needed on C2S regions. Both TC2S and SC2S support ALIAS records now.
=> OCPBUGS-9435: terraform: aws: secret regions now support ALIAS record

data/data/azure/vnet/nsg.tf
In an install where users bring their networks they also bring their own NSGs. However, the installer still creates NSG. In Azure environments using the rule [1] below, users are prohibited from installing cluster, as the apiserver_in rule has the rule set as 0.0.0.0. Having a rule in place where the users could define this before install would allow them to set this connectivity without having the inbound access.
[1] - Rule: Network Security Groups shall not allow rule with 0.0.0.0/Any Source/Destination IP Addresses - Custom Deny
=> OCPBUGS-11796: azure: skip NSG creation when BYO vnet

data/data/azure/bootstrap/main.tf, data/data/azure/cluster/main.tf, data/data/azure/variables-azure.tf, data/data/azure/vnet/main.tf, pkg/asset/cluster/tfvars.go, pkg/asset/installconfig/azure/session.go, pkg/asset/installconfig/platformcredscheck.go, pkg/tfvars/azure/azure.go
Use the managed identity from the installer host VM (running in Azure) so that a user can install a cluster without copying credentials to the installer host.
=> CORS-2372: Azure: auth Installer with Managed Identity from VM

pkg/types/aws/validation/machinepool.go
Add support for SC2S region (us-isob-east-1) and new TC2S region (us-iso-west-1).
=> OCPBUGS-13636: new Aws secret regions support

pkg/asset/agent/image/agentartifacts.go
Apparently the patch applied in PR [7185](https://github.com/openshift/installer/commit/9888256c5ce4a8b97061a136acd6a13d5a08b571#diff-4ba63e2557dcff8b6d8c998632f13630e766c5a4ccba4a77e41acc66ceaa692aL81) silently overwrote the image name (introduced in PR [7212](https://github.com/openshift/installer/commit/fa3a3141f18faf8970741e71de4f672e9606203d)).
It's currently working because the agent-tui related code has not yet been removed from `agent-installer-node-agent` (but it will be in the immediate future as part of the epic https://issues.redhat.com/browse/AGENT-508)
=> Use the correct image name for agent-tui extraction

pkg/asset/installconfig/vsphere/vsphere.go
On version 4.13 if only one dataStore is detected, it sets the configuration to the name instead to the path
Example:
```
% ./openshift-install create install-config --dir vmware-cluster-install                  
? SSH Public Key 
? Platform vsphere
? vCenter portal.vc.opentlc.com
? Username sandbox-mzfsr@vc.opentlc.com
? Password [? for help] ************
INFO Connecting to vCenter portal.vc.opentlc.com  
INFO Defaulting to only available datacenter: SDDC-Datacenter 
INFO Defaulting to only available cluster: /SDDC-Datacenter/host/Cluster-1 
INFO Defaulting to only available datastore: /SDDC-Datacenter/datastore/WorkloadDatastore 
INFO Defaulting to only available network: segment-sandbox-mzfsr 
? Virtual IP Address for API 192.168.13.201
? Virtual IP Address for Ingress 192.168.13.202
? …
```
=> Default dataStore is returned the name instead the inventoryPath

pkg/asset/installconfig/gcp/client.go, pkg/asset/installconfig/gcp/mock/gcpclient_generated.go, pkg/asset/installconfig/gcp/validation.go, pkg/asset/installconfig/gcp/validation_test.go
If we want to know if a project is valid, we can use the API to `Get` it directly, instead of `List`ing all projects and then filtering the one we want. Listing can be problematic for accounts with many associated projects.
=> OCPBUGS-15238: GCP: ic: improve project validation

pkg/asset/agent/image/agentpxefiles.go
Read the default  kernel args from the `coreos/kargs.json` file from the base iso 
such as `ignition.firstboot ignition.platform.id=metal` and add it to the iPXE script.
=> AGENT-498: Get iPXE script template kernel parameters from ISO

hack/go-test.sh
It was previously set to 1.18 and needed to be bumped to match move to golang 1.20.
=> Update hack/go-test.sh to golang 1.20

data/data/alibabacloud/cluster/vpc/eip.tf
=> OCPBUGS-12751: [Alibaba] update the bandwidth value of EIP

pkg/asset/agent/manifests/agentclusterinstall.go, pkg/asset/agent/manifests/agentclusterinstall_test.go
Allow override of the networkType. If the networkType is set to a value other then OpenshiftSDN or OVNKubernetes then the installConfigOverrides will be set to the configured value.
=> AGENT-624: Allow override of networkType

data/data/install.openshift.io_installconfigs.yaml, pkg/asset/installconfig/aws/permissions.go, pkg/asset/installconfig/platformpermscheck.go, pkg/destroy/aws/aws.go, pkg/destroy/aws/shared.go, pkg/explain/printer_test.go, pkg/types/aws/platform.go, pkg/types/aws/validation/platform.go, pkg/types/aws/validation/platform_test.go, pkg/types/validation/installconfig.go
Adds/refines validations for the cross-account private hosted zone use case:
- do not allow mint credential mode
- do not require unnecessary permissions when using an existing hosted zone
- require sts:AssumeRole permissions  
Also includes some refactoring that did not make it into the previous PR.
ccing previous reviewers:
/cc @barbacbd @r4f4 @mtulio @sadasu
=> CORS-2645: AWS Cross-Account Private Hosted Zone: Add Further Validations

images/installer/Dockerfile.upi.ci.rhel8
Due to [security vulnerability](https://github.com/Azure/azure-cli/security/advisories/GHSA-47xc-9rr2-q7p4) affecting Azure CLI versions previous to 2.40.0, it is recommended to update azure cli to higher version to avoid this issue.
Changes:
1. update azure cli yum repository to rhel8 based repository
=> OCPBUGS-14932: Update azure cli to 2.40.0+

images/installer/Dockerfile.upi.ci.rhel8
API version issue when using az 2.50.0 to install upi
```
Creating 'api' record in public zone for IP 52.152.61.10
ERROR: (NoRegisteredProviderFound) No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/A'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/A'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'. …
```
=> OCPBUGS-14932: specify azure cli version

docs/user/openstack/README.md, docs/user/openstack/connect_nodes_to_ipv6_network.md, docs/user/openstack/connect_nodes_to_manila_network.md, docs/user/openstack/customization.md, docs/user/openstack/image_registry_with_custom_pvc_backends.md, docs/user/openstack/install_upi.md, docs/user/openstack/kuryr.md, docs/user/openstack/provider_networks.md, docs/user/openstack/troubleshooting.md
Add a note suggesting users disable allowed address pairs when adding a manila network as a day 2 network.
While we're here, also address some other nits with the docs by adding missing entries to the "Reference doc" ToC in the main README, and fixing formatting for some admonitions.
Commits:
- `docs: Improve Manila document`
- `docs: Add missing refs to OpenStack README ToC`
- `docs: Use GHFM for OpenStack doc notes`
=> docs: Add note about not configuring allowed address pairs for day 2 manila configuration

data/data/azure/bootstrap/main.tf, data/data/azure/bootstrap/variables.tf, data/data/azure/cluster/main.tf, data/data/azure/cluster/master/master.tf, data/data/azure/cluster/master/variables.tf, data/data/azure/cluster/variables.tf, data/data/azure/variables-azure.tf, data/data/azure/vnet/outputs.tf, data/data/azure/vnet/public-lb.tf, data/data/azure/vnet/vnet.tf, data/data/install.openshift.io_installconfigs.yaml, pkg/explain/printer_test.go, pkg/tfvars/azure/azure.go, pkg/types/azure/platform.go, pkg/types/azure/validation/platform.go, pkg/types/azure/validation/platform_test.go
Provide the ability to the Installer to deploy clusters with a NAT Gateway for outbound traffic as the AKS installer already does. This will be useful for customers facing SNAT port exhaustion issues with the default LB outbound.
=> CORS-2572: azure: implement egress via NAT gateway

upi/azure/03_infra.json, upi/azure/04_bootstrap.json, upi/azure/05_masters.json
The CCM/KCM in OpenShift is configured to look for a load balancer name of `${CLUSTER_ID}`. In UPI we have been creating a load balancer called `${CLUSTER_ID}-public` to fill the same purpose.
When the KCM/CCM starts up, it notices the lack of the LB and creates a new load balancer, however, it doesn't move the master nodes across from the old LB, as it assumes they are supposed to be attached to the other LB. In this case, for UPI clusters, the master node membership is never reconciled and any service that uses a load balancer will never route through the master nodes.
```
I0704 12:31:39.379256       1 azure_standard.go:878] Node "jspeedtest3-xl52m-master-0" has already been added to LB "jspeedtest3-xl52m-public-lb", omit adding it to a new one
I0704 12:31:39.379304       1 …
```
=> OCPBUGS-14762: Use the same names for public LB in IPI and UPI Azure

cmd/openshift-install/create.go
Adds a check to see whether each cluster operator has stopped
progressing for at least 30 seconds. There is a five minute period
where operators can meet this threshold.
This check prevents against a class of errors where operators report
themselves as Available=true but continue to progress and are not
fully functional.
=> create: add check for cluster operator stability

data/data/agent/files/usr/local/bin/issue_status.sh
Signed-off-by: Zane Bitter <zbitter@redhat.com > and Pawan Pinjarkar <ppinjark@redhat.com>
=> OCPBUGS-14900: Use correct SELinux label. Make rename atomic.

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.14 boot image metadata. A notable change is the addition of a GCP aarch64 artifact.
```
x86_64=414.92.202307070025-0                                      \
aarch64=414.92.202307070025-0                                     \
s390x=414.92.202307070025-0                                       \
ppc64le=414.92.202307070025-0
```
=> OCPBUGS-15999: update RHCOS 4.14 bootimage metadata to 414.92.202307070025-0

pkg/destroy/aws/aws.go
Tagging APIs are now supported in the C2S isolated partitions (us-iso and us-isob). We have tested these changes on clusters installed with IPI in both partitions.
=> Allow destroy for C2S isolated (us-iso and us-isob) partitions.

cmd/openshift-install/testdata/agent/configimage/manifests/default_manifests.txt, cmd/openshift-install/testdata/agent/image/configurations/none_ha.txt, cmd/openshift-install/testdata/agent/image/manifests/default_manifests.txt, go.mod, pkg/asset/agent/installconfig.go, pkg/asset/agent/installconfig_test.go, pkg/asset/agent/manifests/agentclusterinstall.go
- For none platform with only one master and zero workers, only the network type `OVNKubernetes` is allowed.
- none platform can now have ControlPlane.Replicas>1 and workers>0
- Set UserManagedNetworking to true for none platform
- Remove redundant integration test when supporting non-SNO cluster topologies for none platform
=> AGENT-648: Remove validation check limiting None platform to SNO

pkg/asset/installconfig/gcp/client.go
We are probably being too optimistic with timeouts like 30s and 1min for API calls. If your account happens to have access to thousands of projects, the API calls can easily exceed that. Let's settle in 2min for now.
I also used the opportunity to fix a few instances where the context passed as parameter was being ignored.
=> OCPBUGS-15238: GCP: ic: client: use a higher context timeout

data/data/azure/vnet/public-lb.tf
When one creates an IPI Azure cluster with an `internal` publishing method, it creates a standard load balancer with an empty definition. This load balancer doesn't serve a purpose since the configuration is completely empty. Because it doesn't have a public IP address and backend pools it's not providing any outbound connectivity, and there are no frontend IP configurations for ingress connectivity to the cluster.
=> OCPBUGS-9404: azure: skip LB creation when not needed

data/data/agent/files/usr/local/bin/agent-config-image-wait.sh, data/data/agent/systemd/units/agent-check-config-image.service, pkg/asset/agent/image/ignition_test.go, pkg/asset/agent/image/unconfigured_ignition.go, pkg/asset/agent/image/unconfigured_ignition_test.go
The new service will only be added to the unconfigured ignition.
The purpose is to give customers some indication that in order for the hosts to proceed with cluster installation the config image need to be inserted or mounted.
=> AGENT-660 Display insert config image message to console

data/data/agent/files/usr/local/bin/install-status.sh
The commit 4daff6117fce1d73774b02caf605d9e1b836dd7c changed the value of $services_issue so that it will never find the correct file to remove. We should use the clear_issue function to correctly remove the issue file.
=> Agent: clear service status once all services started

pkg/types/validation/installconfig.go, pkg/types/validation/installconfig_test.go
AWS hostedZoneRole feature has been promoted in the API. Remove the installer validation for a tech preview feature gate.
API Promotion is in https://github.com/openshift/api/pull/1522
=> aws: drop hostedZoneRole Feature Gate

docs/user/openstack/customization.md, pkg/types/openstack/validation/machinepool.go, pkg/types/openstack/validation/machinepool_test.go
When a machine is created with a compute availability zone (defined via `mpool.zones`) and a storage root volume (defined as `mpool.rootVolume`) and that `rootVolume` has no specified `zones`, CAPO will use the compute AZ for the volume AZ.
This can be problematic if the AZ doesn't exist in Cinder.
Source:
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/9d183bd479fe9aed4f6e7ac3d5eee46681c518e7/pkg/cloud/services/compute/instance.go#L439-L442
```golang
func (s *Service) getOrCreateRootVolume(eventObject runtime.Object, instanceSpec *InstanceSpec, imageID string) (*volumes.Volume, error) {
(...)
availabilityZone := instanceSpec.FailureDomain
if rootVolume.AvailabilityZone != "" {
availabilityZone = rootVolume.AvailabilityZone
}
(...)
```
If a compute AZ is provided …
=> OCPBUGS-15997: openstack: add root volume AZ validation

pkg/asset/machines/master.go, pkg/asset/machines/powervs/machines.go
Add support for [CPMSO](https://github.com/openshift/cluster-control-plane-machine-set-operator) for Power VS platform, Initially it will be in Inactive state, Later based on the feedback we can by default make it active.
opesnhift/api changes PR: https://github.com/openshift/api/pull/1415
openshfit/machine-api-provider-powervs changes: https://github.com/openshift/machine-api-provider-powervs/pull/41
=> MULTIARCH-3667: Add support for CPMSO for Power VS

data/data/install.openshift.io_installconfigs.yaml, pkg/asset/installconfig/openstack/validation/cloudinfo.go, pkg/asset/installconfig/openstack/validation/machinepool.go, pkg/asset/installconfig/openstack/validation/platform.go, pkg/asset/installconfig/openstack/validation/platform_test.go, pkg/asset/machines/openstack/machines.go, pkg/asset/quota/openstack/openstack.go, pkg/tfvars/openstack/openstack.go, pkg/tfvars/openstack/ports.go, pkg/types/conversion/installconfig.go, pkg/types/openstack/machinepool.go, pkg/types/openstack/platform.go, pkg/types/openstack/validation/platform.go, pkg/types/openstack/validation/platform_test.go, pkg/types/openstack/validation/techpreview.go, pkg/types/openstack/validation/techpreview_test.go
This commit adds dual stack support with bring your own network
for OpenStack platform. The new `ControlPlanePort` field accepts IPv4/IPv6
subnets and the network in the install config, while the `machinesSubnet`
that only supports IPv4 Subnets is deprecated.
Partially implements: https://github.com/openshift/enhancements/pull/1365
=> OpenStack: Dual stack support with BYON

data/data/rhcos-amd64.json, data/data/rhcos-ppc64le.json, data/data/rhcos-s390x.json, data/data/rhcos.json, hack/update-rhcos-bootimage.py
rhcos.mirror.openshift.com is the new formal location to download RHCOS boot images. It is backed by CloudFront CDN, which should be more reliable and faster than the rhcos-redirector.
=> Bug 2108582 [4.7] RHCOS: move to rhcos.mirror.openshift.com

data/data/rhcos-amd64.json, data/data/rhcos-ppc64le.json, data/data/rhcos-s390x.json, data/data/rhcos.json, hack/update-rhcos-bootimage.py
rhcos.mirror.openshift.com is the new formal location to download RHCOS boot images. It is backed by CloudFront CDN, which should be more reliable and faster than the rhcos-redirector.
=> Bug 2108582 [4.6] RHCOS: move to rhcos.mirror.openshift.com

data/data/powervs/bootstrap/main.tf, data/data/powervs/bootstrap/variables.tf, data/data/powervs/bootstrap/vm/main.tf, data/data/powervs/bootstrap/vm/variables.tf, data/data/powervs/cluster/bootstrap/variables.tf, data/data/powervs/cluster/main.tf, data/data/powervs/cluster/master/main.tf, data/data/powervs/cluster/master/variables.tf, data/data/powervs/cluster/master/vm/main.tf, data/data/powervs/cluster/master/vm/variables.tf, data/data/powervs/cluster/outputs.tf
The output from ibm_pi_key resource, namely key_id has been deprecated and replaced by name attribute.
JIRA: https://issues.redhat.com/browse/MULTIARCH-3675
Reference: https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/pi_key#attribute-reference
=> PowerVS: Replace deprecated key_id attribute with name for ibm_pi_key resource

pkg/asset/installconfig/azure/validation.go, pkg/asset/installconfig/azure/validation_test.go
"StandardSSD_LRS" is not a supported disk type and will result in the following failure:
```
level=error msg=Error: expected storage_os_disk.0.managed_disk_type to be one of [Premium_LRS Standard_LRS], got StandardSSD_LRS
level=error
level=error msg=  with azurestack_virtual_machine.bootstrap,
level=error msg=  on main.tf line 107, in resource "azurestack_virtual_machine" "bootstrap":
level=error msg= 107: resource "azurestack_virtual_machine" "bootstrap" {
level=error
```
Let's make sure that only Premium_LRS or Standard_LRS can be specified for AzureStack.
=> [release-4.12] OCPBUGS-16151: ic: azure: validate diskTypes in AzureStack

pkg/asset/machines/master.go, pkg/asset/machines/worker.go
When arm64 is specified in the install config set the correct values in the MachinePool
This depends on https://github.com/openshift/installer/pull/7215
=> CORS-2445: GCP: Add default values for arm64

data/data/install.openshift.io_installconfigs.yaml, data/data/openstack/bootstrap/main.tf, data/data/openstack/masters/main.tf, data/data/openstack/variables-openstack.tf, docs/user/openstack/control-plane-machine-set.md, docs/user/openstack/customization.md, pkg/asset/installconfig/openstack/validation/machinepool.go, pkg/asset/installconfig/openstack/validation/machinepool_test.go, pkg/asset/machines/openstack/machines.go, pkg/asset/machines/openstack/machines_test.go, pkg/asset/machines/openstack/machinesets.go, pkg/tfvars/openstack/openstack.go, pkg/types/conversion/installconfig.go, pkg/types/conversion/installconfig_test.go, pkg/types/openstack/machinepool.go, pkg/types/openstack/validation/machinepool.go, pkg/types/openstack/validation/machinepool_test.go, scripts/openstack/manifest-tests/root-volume-types/install-config.yaml, scripts/openstack/manifest-tests/root-volume-types/test_cpms.py, scripts/openstack/manifest-tests/root-volume-types/test_machines.py
=> OSASINFRA-3181 - Volume Types for OpenStack CPMS

docs/user/openstack/install_upi.md
We don't want CCPMSO with UPI, the machines are managed by the user, not
OpenShift.
=> OCPBUGS-16395: openstack/upi: update doc for CCPMSO

data/data/install.openshift.io_installconfigs.yaml, pkg/asset/cluster/metadata.go, pkg/asset/cluster/tfvars.go, pkg/asset/installconfig/platform.go, pkg/asset/installconfig/platformcredscheck.go, pkg/asset/installconfig/platformpermscheck.go, pkg/asset/installconfig/platformprovisioncheck.go, pkg/asset/machines/master.go, pkg/asset/machines/worker.go, pkg/asset/manifests/cloudproviderconfig.go, pkg/asset/manifests/dns.go, pkg/asset/manifests/external/infrastructure.go, pkg/asset/manifests/infrastructure.go, pkg/asset/quota/quota.go, pkg/asset/rhcos/image.go, pkg/explain/printer_test.go, pkg/terraform/stages/platform/stages.go, pkg/types/external/defaults/platform.go, pkg/types/external/doc.go, pkg/types/external/platform.go, pkg/types/installconfig.go, pkg/types/validation/installconfig.go, pkg/types/validation/installconfig_test.go
The intent of this pull request is to allow the definition of the external platform type so that partners are able to more easily integrate with the installer and other components that recognize the external platform type.
cc: @elmiko
=> OCPCLOUD-2036: introduce External platform type

docs/user/openstack/customization.md
The option no longer exists in cloud-provider-openstack.
=> Remove mentions of use-octavia

data/data/agent/systemd/units/pre-network-manager-config.service
This fixes a timing issue between pre-network-manager-config.service and NetworkManager.service when defining static IPs in nmstateconfig. The problem is not apparent when using a few network interfaces, but when many interfaces (e.g. more than 8) are defined then the pre-network-manager-config.sh does not complete copying the files to /etc/NetworkManager/system-connections/ BEFORE NetworkManager.service starts running. The result is that the static IPs are not configured.
The fix is to add a dependency on NetworkManager.service to ensure that the pre-network-manager-config.service completes before NetworkManager.service is run.
=> OCPBUGS-16219: Fix timing issue between network services

data/data/openstack/variables-openstack.tf, docs/user/openstack/customization.md
Commit https://github.com/openshift/installer/commit/a1ea1c870e71509ccd9df968c63cfc61380778e7 changed how the
machinesets get generated. We no longer generate machineset when the
number of replicas is 0, meaning we need to provide a default value for
`openstack_worker_server_group_names` so that terraform does not blow
up.
Also document the `rootVolume.type` config as deprecated. We now need to use `rootVolume.types`.
=> Fix the deployment on OpenStack for worker pools with no replicas.

images/openstack/Dockerfile.ci, upi/openstack/inventory.yaml, upi/openstack/network.yaml
Ansible 2.9 is going EOL later this year, we need to use ansible-core
and until we get RPMs for openstack collections, we'll install them from
source.
TODO:
=> OSASINFRA-3193: Update openstack/Dockerfile.ci for ansible-core

data/data/aws/bootstrap/variables.tf, data/data/aws/cluster/main.tf, data/data/aws/cluster/outputs.tf, data/data/aws/cluster/vpc/common.tf, data/data/aws/cluster/vpc/outputs.tf, data/data/aws/cluster/vpc/variables.tf, data/data/aws/cluster/vpc/vpc-private.tf, data/data/aws/cluster/vpc/vpc-public.tf, data/data/aws/cluster/vpc/vpc.tf, data/data/aws/variables-aws.tf, docs/user/aws/install_local-zones.md, pkg/asset/cluster/tfvars.go, pkg/asset/installconfig/aws/availabilityzones.go, pkg/asset/installconfig/aws/metadata.go, pkg/asset/installconfig/aws/subnet.go, pkg/asset/installconfig/aws/validation.go, pkg/asset/installconfig/aws/validation_test.go, pkg/asset/installconfig/installconfig.go, pkg/asset/machines/aws/machinesets.go, pkg/asset/machines/master.go, pkg/asset/machines/worker.go, pkg/tfvars/aws/aws.go, pkg/types/aws/availabilityzones.go, pkg/types/defaults/machinepools.go, pkg/types/defaults/machinepools_test.go
This PR introduces the automation required to installer create subnets on AWS Local Zones when that zone names are set in the instal-config.yaml, Phase 2 of AWS Local Zones described on [EP 1232](https://github.com/openshift/enhancements/pull/1232)
Feature: [RFE-2782](https://issues.redhat.com/browse/RFE-2782) / [SPLAT-657](https://issues.redhat.com/browse/SPLAT-657)
Enhancement: https://github.com/openshift/enhancements/pull/1232
Workflow example:
- Create Install-config with support of Local Zones (Example region `us-east-1`)
```yaml
apiVersion: v1
publish: External
baseDomain: devcluster.openshift.com
metadata:
name: "cluster-name"
pullSecret: ...
sshKey: ...
platform:
aws:
region: us-east-1
compute:
- name: edge
platform:
aws:
zones:
- us-east-1-atl-1a
- us-east-1-bos-1a
- …
```
=> SPLAT-657: AWS Local Zones subnets automation for edge compute pool

docs/user/openstack/README.md, docs/user/openstack/customization.md, docs/user/openstack/deploy_baremetal_workers.md, docs/user/openstack/deploy_dual_stack_cluster.md, docs/user/openstack/external_load_balancer.md, docs/user/openstack/provider_networks.md
The `MachinesSubnet` field has been reshaped as `controlPlanePort`,
this commit updates the docs to ensure `controlPlanePort` is used.
Also, this commit adds dual-stack documentation.
Partially implements: https://github.com/openshift/enhancements/pull/1365
=> OpenStack: Add steps to enable dual-stack clusters

data/data/agent/systemd/units/create-cluster-and-infraenv.service.template
As done in assisted-service.service.template, added '-v /etc/containers:/etc/containers' when HaveMirrorConfig flag is true to the create-cluster-and-infraenv service. This should allow propagation of registries.conf, which is required on disconnected environments when using OPENSHIFT_INSTALL_RELEASE_IMAGE_MIRROR.
=> OCPBUGS-16380: Add /etc/containers volume on create-cluster-and-infraenv

cmd/openshift-install/testdata/agent/image/validations/compact_too_many_masters.txt, cmd/openshift-install/testdata/agent/image/validations/compact_too_many_workers.txt, pkg/asset/agent/manifests/nmstateconfig.go
A check was added in https://issues.redhat.com//browse/OCPBUGS-10342 to warn when the number of replicas exceeded the configured hosts, however this did not catch the case when the number of configured hosts exceeds the replicas, so it is added here. In addition if too many hosts are defined compared to the replicas it will result in an error instead of a warning, since this invalid configuration will cause installation failures.
=> OCPBUGS-14877: Validate that number hosts does not exceed replicas

pkg/asset/installconfig/gcp/client.go, pkg/asset/installconfig/gcp/mock/gcpclient_generated.go, pkg/asset/installconfig/gcp/validation.go, pkg/asset/installconfig/gcp/validation_test.go, pkg/asset/machines/gcp/zones.go, pkg/asset/machines/master.go, pkg/asset/machines/worker.go
In https://github.com/openshift/installer/pull/7096 we fixed the validation but the same logic needs to be done for the machine asset generation.
=> OCPBUGS-16515: gcp: use zones available for both instance and project

OWNERS_ALIASES
As part of the onboarding process, it is necessary to add the Github user to the OWNERS_ALIASES file.
=> OWNERS_ALIASES: Add new user to owners_aliases

data/data/install.openshift.io_installconfigs.yaml, pkg/asset/agent/image/unconfigured_ignition.go, pkg/destroy/gcp/gcp.go, pkg/destroy/gcp/gcp_test.go, pkg/types/gcp/machinepools.go, pkg/types/gcp/validation/machinepool.go, pkg/types/gcp/validation/machinepool_test.go
Adding support for `pd-balanced` disk types for the compute nodes by allowing users to provide it in the disk type field under compute in the install config.
=> CORS-1770: Support pd-balanced disk types for GCP deployments

data/data/azure/bootstrap/main.tf, data/data/azure/cluster/main.tf, data/data/azure/cluster/master/master.tf, data/data/azure/cluster/master/variables.tf, data/data/azure/variables-azure.tf, data/data/install.openshift.io_installconfigs.yaml, pkg/asset/installconfig/azure/capabilities.go, pkg/asset/installconfig/azure/validation.go, pkg/asset/installconfig/azure/validation_test.go, pkg/asset/machines/azure/machines.go, pkg/tfvars/azure/azure.go, pkg/types/azure/machinepool.go, pkg/types/azure/validation/machinepool.go, pkg/types/azure/validation/machinepool_test.go
This PR adds a new field `Plan` to the install-config, so the Installer can also use Marketplace images with no purchase plan. It was hard-coded to assume all images needed a purchase plan (therefore requiring its terms to be accepted).
It then extends the usage of Azure Marketplace images to nodes other than compute.
Some changes were made to the validation unit tests so the Marketplace image functionality can be tested independently from the more encompassing install-config validation test.
**Note**
I had to also fix a deprecated warning about `sets.String` usage so the linter would be happy
**Limitations**
To simplify things, the RHCOS image is still created and uploaded to the user's storage account. That way it can still be used for future scaleups. The Marketplace image, however, is …
=> CORS-2503: azure: use marketplace images for all nodes

data/data/install.openshift.io_installconfigs.yaml, pkg/asset/installconfig/gcp/client.go, pkg/asset/installconfig/gcp/mock/gcpclient_generated.go, pkg/asset/installconfig/gcp/validation.go, pkg/asset/installconfig/gcp/validation_test.go, pkg/asset/machines/gcp/machines.go, pkg/types/gcp/machinepools.go
Specify a RHCOS image coming from a custom source in the install config to override the installer's internal choice of bootimage. This is to enable the use of ARM64 images.
=> CORS-2445: GCP add bootimage override in install-config

pkg/types/conversion/installconfig.go, pkg/types/conversion/installconfig_test.go, scripts/openstack/manifest-tests/convert/install-config.yaml, scripts/openstack/manifest-tests/convert/test_convert.py
Passing an empty platform in machinepools caused the installer to exit with an ugly stack trace. This commit fixes the convertOpenStack() function to account for cases where the platform is not defined in the machine pools.
=> OCPBUGS-16692: OpenStack: fix crash with empty platform in machinepool

data/data/openstack/variables-openstack.tf
A follow-up to https://github.com/openshift/installer/pull/7356.
=> OpenStack: Fix default for openstack_worker_server_group_names

pkg/asset/machines/openstack/machinesets.go
... even if zero workers is requested from install-config (replicas ==
0).
This was a non backward compatible change introduced by https://github.com/openshift/installer/pull/7300
=> OCPBUGS-17064: always create a MachineSet

data/data/gcp/cluster/master/main.tf
** Removed the addition of the service account user permission for control plane nodes in terraform.
The service account user permission is passed to MAO as it is needed by that operator to access specific resources. It is not needed during the creation of master/control plane nodes.
=> CORS-2719: Remove service account user permission

data/data/azurestack/cluster/master/master.tf, pkg/asset/machines/master.go, pkg/types/azure/defaults/platform.go, pkg/types/azure/validation/machinepool.go, pkg/types/azure/validation/machinepool_test.go
The master disk size default is set to 1024 when the max size allowed in azurestack is 1024. Futhermore, the check in the tfvars sets the minimum value for disk size to 1023 which should not be done since the users can configure their own size. Changing these values.
=> OCPBUGS-6759: Fix discrepancy with disk size master

data/data/install.openshift.io_installconfigs.yaml, pkg/types/gcp/machinepools.go
Clarify the wording in the service account field in the gcp machine pool to indicate the field is only supported in the control plane machine set.
Because compute and control plane machine pools are the same type, openshift-install explain will display the service account field in the compute machine pool. Hopefully this will make it slightly less confusing.
=> OCPBUGS-16292: GCP XPN: clarify service account support

pkg/asset/installconfig/powervs/validation.go, pkg/asset/installconfig/powervs/validation_test.go
PowerVS supports machine pool CIDR of /24 for deployment.
=> PowerVS: Check whether Machine pool CIDR is /24

pkg/asset/machines/machineconfig/ipv6.go, pkg/asset/machines/master.go, pkg/asset/machines/worker.go, scripts/openstack/manifest-tests/dual-stack/install-config.yaml, scripts/openstack/manifest-tests/dual-stack/test_machine-config.py
On clusters configured with dual-stack network the
IPv4 and IPv6 addresses can be added to the main interface
at different time, which results in the openshift node addresses
not containing the IPv6 address. This commit fixes the issue
by including `ip=dhcp,dhcp6` to the kernel args of masters and works,
which sets `required-timeout` to an value that the IP configuration
will be tried before succeeds. This configuration is valid for day1
dual-stack clusters only.
Partially Implements: https://github.com/openshift/enhancements/pull/1365
=> Bug OCPBUGS-16249: Add ip=dhcp,dhcp6 option to Kernel args

data/data/agent/files/etc/NetworkManager/conf.d/clientid.conf, pkg/asset/agent/image/ignition_test.go, pkg/asset/agent/image/unconfigured_ignition.go
When using DHCPv6, ensure that the host sends a DHCP Solicitation with the Client ID containing the mac address, i.e. DUID-LL. See https://datatracker.ietf.org/doc/html/rfc3315#section-9.4 for more info.  This allows the DHCPv6 server to assign an IPv6 address that can be used as the rendezvousIP.
=> OCPBUGS-16912: Ensure DHCPv6 client sends Solicit with mac address

pkg/destroy/openstack/openstack.go
cloud-provider-openstack can be configured to create security groups for the NodePorts of the load balancers it is creating. These SGs are then attached to the nodes. On `cluster destroy` we're orphaning them. This commit makes sure that we're looking for them.
As they aren't tagged or have a proper cluster ID in the name, we will look at each of the ports, list its SGs and evaluate them comparing names with the pattern. If it matches, `destroy` will attempt to delete such SG.
=> OpenStack: Remove SGS created by CPO on destroy

data/data/agent/files/usr/local/bin/load-config-iso.sh, pkg/asset/agent/configimage/configiso.go
The core user password should be set to the one stored in kubeadmin-password.hash after loading the config-image.
=> OCPBUGS-15994: Update core password after loading config-image

pkg/asset/installconfig/alibabacloud/alibabacloud.go, pkg/types/alibabacloud/validation/platform.go
The deprecation of support for the Alibaba Cloud platform is being postponed by one release, so we need to revert [SPLAT-1094](https://issues.redhat.com/browse/SPLAT-1094). 
Fixes https://issues.redhat.com/browse/SPLAT-1123
=> SPLAT-1123: Revert Alibaba deprecation warning

data/data/bootstrap/files/usr/local/bin/installer-gather.sh, data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh
Before systemd was created, syslog was the dominant Unix logging system.
Later, systemd introduced the journal whose output intentionally exactly matched that of syslog for compatibility.
In systemd, the "unit" is the technical heart of things; yet the syslog output only includes the "syslog identifier" which might or might not look like the unit.
For many of our units that just run shell script, the syslog identifier is just "bash".
This makes it hard to distinguish what's going on.  With this patch the output will change from e.g.:
```
Jul 26 21:15:00 cvrzlbtm-bbcf1-t58lf-bootstrap release-image-download.sh[1995]: 2c5e0f38687f7acf45adf9de5e841a46bbbda574d121d71d92bfb929826dfa27
```
to
```
Jul 26 21:15:00 cvrzlbtm-bbcf1-t58lf-bootstrap release-image.service[1995]: …
```
=> gather: Use `journalctl -o with-unit`

docs/user/openstack/connect_nodes_to_ipv6_network.md
This commit fixes a typo on the kernal args and the URL of the openshift docs containing steps to configure a MachineConfig.
=> OpenStack: Fix user docs for additional network with IPv6

pkg/asset/machines/openstack/machinesets.go, scripts/openstack/manifest-tests/zero-workers/install-config.yaml, scripts/openstack/manifest-tests/zero-workers/test_cpms.py, scripts/openstack/manifest-tests/zero-workers/test_machines.py
Assert that:
* setting zero workers does not crash the Installer
* there always is at least one MachineSet
A follow-up to #7380
=> openstack: Test zero replicas in worker machine-pool

pkg/asset/machines/azure/machines.go
Azurestack does not create `-gen2` images so we should not set them in the machine manifests. Otherwise the following error occurs
```
$ oc describe machine jima411az-xvwvg-worker-mtcazs-4k6hs -n openshift-machine-api
...
Events:
Type     Reason        Age   From              Message
----     ------        ----  ----              -------
Warning  FailedCreate  3h4m  azure-controller  InvalidConfiguration: failed to reconcile machine "jima411az-xvwvg-worker-mtcazs-4k6hs": failed to create vm jima411az-xvwvg-worker-mtcazs-4k6hs: failure sending request for machine jima411az-xvwvg-worker-mtcazs-4k6hs: cannot create vm: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="NotFound" Message="The Image …
```
=> OCPBUGS-17246: azurestack: do not use gen2 images

pkg/asset/agent/agentconfig/agent_config.go
Fixed empty log message by adding the correct INFO log during 'agent-config-template' creation.
=> OCPBUGS-13408: $ openshift-install agent create agent-config-template --dir=./foo gives nothing in the INFO log-level

pkg/types/azure/validation/machinepool.go, pkg/types/azure/validation/machinepool_test.go
We cannot rely on any ordering from iterating over a Golang map. If we do, we might fail unit tests because the values we compare with are different:
```
--- FAIL: TestValidateMachinePool (0.00s)
--- FAIL: TestValidateMachinePool/securityType_set_to_ConfidentialVM_but_securityEncryptionType_is_invalid (0.00s)
machinepool_test.go:610:
Error Trace:	/go/src/github.com/openshift/installer/pkg/types/azure/validation/machinepool_test.go:610
Error:      	Expect "test-path.defaultMachinePlatform.osDisk.securityProfile.securityEncryptionType: Unsupported value: "invalidSecurityEncryptionType": supported values: "DiskWithVMGuestState", "VMGuestStateOnly"" to match "^test-path.defaultMachinePlatform.osDisk.securityProfile.securityEncryptionType: Unsupported value: "invalidSecurityEncryptionType": …
```
=> azure: validation: machinepool: sort slice before comparing

pkg/types/validation/installconfig.go, pkg/types/validation/installconfig_test.go
Based on https://github.com/openshift/api/pull/1537, this PR brings the same installer config validation to installer
=> Add baremetal capability validation

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.14 boot image metadata. Issues fixed in this bootimage are:
OCPBUGS-16157 - Service 'ignition-ostree-transposefs-autosave-xfs'
fails while booting the compute nodes with RHCOS image iso
OCPBUGS-16771 - ensure fixes land for large inodes [4.14]
```
x86_64=414.92.202308032115-0                                      \
aarch64=414.92.202308032115-0                                     \
s390x=414.92.202308032115-0                                       \
ppc64le=414.92.202308032115-0
```
=> OCPBUGS-16776: update RHCOS 4.14 bootimage metadata to 414.92.202308032115-0

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.13 boot image metadata. Issues resolved in this bootimage are:
OCPBUGS-16772 - [4.13] ensure fixes land for large inodes
```
--distro rhcos --no-signatures --name 4.13-9.2                    \
x86_64=413.92.202307260246-0                                      \
aarch64=413.92.202307260246-0                                     \
s390x=413.92.202307260246-0                                       \
ppc64le=413.92.202307260246-0
```
=> OCPBUGS-16777: update RHCOS 4.13 bootimage metadata to 413.92.202307260246-0

data/data/install.openshift.io_installconfigs.yaml, pkg/types/gcp/platform.go, pkg/types/gcp/validation/platform.go, pkg/types/gcp/validation/platform_test.go, pkg/types/validation/installconfig.go
PR is for adding new fields userLabels and userTags for gcp platform type, to add user defined labels and tags to all those gcp resources created by installer.
=> CFE-688: Update install-config CRD to support gcp labels and tags

data/data/install.openshift.io_installconfigs.yaml, pkg/explain/printer_test.go, pkg/types/installconfig.go
Update wording to remove techpreview verbiage from the installer description. Holding until we promote feature in the API.
https://github.com/openshift/api/pull/1443
/hold
=> OCPBUGS-11999: upkeep: updated description to remove techpreview

data/data/gcp/bootstrap/main.tf, data/data/gcp/cluster/dns/base.tf, data/data/gcp/cluster/dns/variables.tf, data/data/gcp/cluster/main.tf, data/data/gcp/cluster/master/main.tf, data/data/gcp/cluster/master/variables.tf, data/data/gcp/post-bootstrap/main.tf, pkg/asset/cluster/tfvars.go, pkg/asset/machines/gcp/machines.go, pkg/tfvars/gcp/gcp.go
PR is for applying OCP default label ("kubernetes-io-cluster-${cluster_id}" = "owned") and user defined labels to all gcp resources created.
=> CFE-687: Apply user defined labels on created gcp resources

pkg/asset/manifests/infrastructure.go
PR:
- Make GCP user tags and labels define din installconfig available in infrastructure CR created by installer for cluster operations.
=> CFE-686: Generate Infrastructure CR with the GCP user defined tags & labels

data/data/coreos/rhcos.json
OCPBUGS-13942 - RHCOS 4.12.3 and 4.12.10 on Z display the "swiotlb
buffer is full" message during KVM cluster Secure Execution (SE)
install boots for the bootstrap, master, worker nodes,
elongating boot durations
OCPBUGS-16773 - ensure fixes land for large inodes
```
plume cosa2stream --target data/data/coreos/rhcos.json \
--distro rhcos --no-signatures \
x86_64=412.86.202308081039-0 \
aarch64=412.86.202308081039-0 \
s390x=412.86.202308081039-0 \
ppc64le=412.86.202308081039-0
```
=> OCPBUGS-16778: bump RHCOS 4.12 bootimage metadata to 412.86.202308081039-0

images/installer/Dockerfile.upi.ci.rhel8
Due to [security vulnerability](https://github.com/Azure/azure-cli/security/advisories/GHSA-47xc-9rr2-q7p4) affecting Azure CLI versions previous to 2.40.0, it is recommended to update azure cli to higher version to avoid this issue.
=> OCPBUGS-16640: [release-4.13] Update azure cli version to 2.49.0

data/data/gcp/cluster/main.tf, data/data/gcp/variables-gcp.tf, data/data/install.openshift.io_installconfigs.yaml, pkg/asset/cluster/tfvars.go, pkg/asset/machines/gcp/machines.go, pkg/tfvars/gcp/gcp.go, pkg/types/gcp/platform.go, pkg/types/gcp/validation/platform.go
It has been at leas two years since the licence field has become obsolete due RHCOS GCP images already having nested virt licences by default. The licenses field is being kept for backwards compatibility
For a more detailed history reference https://github.com/openshift/installer/pull/4696
=> CORS-2660: GCP: deprecate the licenses field

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.11 boot image metadata in the installer which includes the fixes for the following:
OCPBUGS-16774: ensure fixes land for large inodes
These changes were generated with the following command
```
plume cosa2stream --target data/data/coreos/rhcos.json \
--distro rhcos --no-signatures \
x86_64=411.86.202308081056-0 aarch64=411.86.202308081056-0 \
s390x=411.86.202308081056-0 ppc64le=411.86.202308081056-0
```
=> OCPBUGS-16779: bump RHCOS 4.11 bootimage metadata to 411.86.202308081056-0

pkg/asset/installconfig/gcp/client.go, pkg/asset/machines/gcp/zones.go
Users can create their own instance types in GCloud. Those types are not returned when listing the machine types for a given project/region. This would cause those installs with custom types to fail with the error:
```
Internal error: failed to fetch instance type, this error usually occurs if the region or the instance type is not found
```
after the validations introduced by
https://github.com/openshift/installer/pull/7317 and https://github.com/openshift/installer/pull/7096.
To fix that, let's fallback to the previous way of fetching the specific machine type whenever the aggregated list returns 0 elements.
=> OCPBUGS-17227: gcp: fix validation of custom instance types

data/data/powervs/cluster/dns/templates/cloud-init.yaml.tpl
We were denying COS traffic, preventing the image-registry from properly deploying. This adds the endpoint to the allow list of the proxy server.
=> OCPBUGS-17940: Add COS endpoint to proxy server (Power VS)

data/data/openstack/masters/sg-master.tf, data/data/openstack/masters/sg-worker.tf, upi/openstack/security-groups.yaml
With openshift/cluster-cloud-controller-manager-operator#264 we should no longer need the SG rules opening whole NodePorts range by default. cloud-provider-openstack will manage this on its own now.
We still need to keep the rules opening the traffic inside the cluster to make sure traffic redirections and regular NodePort services work.
=> OCPBUGS-17860: OpenStack: Remove NodePorts range 0.0.0.0/0 rules

pkg/asset/installconfig/platformprovisioncheck.go
Adds a validation check to ensure that MachineAPI capability is included for IPI deployments.
=> OCPBUGS-15659: IPI pre-check for MachineAPI capability

images/installer/Dockerfile.upi.ci.rhel8
update govc version to v0.30.7 to support find.Network by cluster path
=> OCPBUGS-18046: update govc version to v0.30.7

data/data/aws/cluster/main.tf, data/data/aws/variables-aws.tf, pkg/asset/cluster/tfvars.go, pkg/tfvars/aws/aws.go
The security groups are being properly added to the controlPlane resource definition manifest but they are not being piped through to terraform to be attached to the instances.
This fixes the issue that, after installation, checking the Security Groups attached to master and worker, master doesn’t have the specified custom security groups attached while workers have.
For one of the masters:
```
[root@preserve-gpei-worker ~]# aws ec2 describe-instances --instance-ids i-0cd007cca57c86ee9 --region us-west-2 --query 'Reservations[*].Instances[*].SecurityGroups[*]' --output json
[
[
[
{
"GroupName": "terraform-20230713031140984600000002",
"GroupId": "sg-05495718555950f77"
}
]
]
]
```
=> OCPBUGS-16204: aws: attach additional security groups to controlPlane

cmd/openshift-install/testdata/agent/image/validations/compact_too_many_masters.txt, cmd/openshift-install/testdata/agent/image/validations/compact_too_many_workers.txt, pkg/asset/agent/installconfig.go, pkg/asset/agent/manifests/nmstateconfig.go
This is a backport of the 2 fixes for replica validations:
https://github.com/openshift/installer/pull/7059
https://github.com/openshift/installer/pull/7268
Also fixes https://issues.redhat.com/browse/OCPBUGS-17759
=> [release-4.13] OCPBUGS-14432: Replica validations

data/data/install.openshift.io_installconfigs.yaml, pkg/asset/installconfig/gcp/client.go, pkg/asset/installconfig/gcp/mock/gcpclient_generated.go, pkg/asset/installconfig/gcp/validation.go, pkg/asset/installconfig/gcp/validation_test.go, pkg/asset/machines/gcp/machines.go, pkg/types/gcp/machinepools.go
The initial stage towards enabling users to specify a boot images from Google Cloud Marketplace. This involves the introduction of a new field called oSImage. Within this field, users can indicate the project and name of the desired image.
Manual cherry-pick of https://github.com/openshift/installer/pull/7215
=> OCPBUGS-17823: CORS-2445: GCP: Add osImage to the install config

pkg/tfvars/azure/azure.go
https://github.com/openshift/installer/pull/7312 inadvertently removed the setting of `OutboundType` in the terraform variables, causing the outbound to always be the default `LoadBalancer` even if `NatGateway` is set in the install-config.
=> OCPBUGS-17869: azure: fix setting outboundType

pkg/asset/machines/master.go, pkg/asset/machines/worker.go
It seems the marketplace image publisher and the image plan's publisher can differ, even in character case. For example:
```
$ az vm image list --offer rh-ocp-worker --all -otable
Architecture    Offer          Publisher       Sku                 Urn                                                             Version
--------------  -------------  --------------  ------------------  --------------------------------------------------------------  --------------
x64             rh-ocp-worker  RedHat          rh-ocp-worker       RedHat:rh-ocp-worker:rh-ocp-worker:4.8.2021122100               4.8.2021122100
$ az vm image show --urn RedHat:rh-ocp-worker:rh-ocp-worker:4.8.2021122100 --query plan
{
"name": "rh-ocp-worker",
"product": "rh-ocp-worker",
"publisher": "redhat"
}
```
When checking for …
=> OCPBUGS-17770: azure: use marketplace image plan's publisher

cmd/openshift-install/testdata/agent/pxe/configurations/sno.txt, cmd/openshift-install/testdata/agent/pxe/configurations/sno_arm.txt
- Check the contents of the generated iPXE script using a regular expression and `grep` function.
- Rename the sno arm test case to match naming conventions
Signed-off-by: 
Andrea Fasano <afasano@redhat.com> @andfasano 
Pawan Pinjarkar <ppinjark@redhat.com> @pawanpinjarkar
=> OCPBUGS-18457: Fix PXE integration tests

data/data/install.openshift.io_installconfigs.yaml, pkg/asset/installconfig/gcp/client.go, pkg/asset/installconfig/gcp/mock/gcpclient_generated.go, pkg/asset/installconfig/gcp/validation.go, pkg/asset/installconfig/gcp/validation_test.go, pkg/asset/machines/gcp/machines.go, pkg/types/gcp/machinepools.go
The initial stage towards enabling users to specify a boot images from Google Cloud Marketplace. This involves the introduction of a new field called oSImage. Within this field, users can indicate the project and name of the desired image.
Manual cherry-pick of https://github.com/openshift/installer/pull/7215
=> OCPBUGS-18320: CORS-2445: GCP: Add osImage to the install config

cmd/openshift-install/agent_internal_integration_test.go
Display the actual value as a diff from the expected value, as unit tests with the assert library do, instead of the other way around.
=> integration tests: Swap order of diff arguments

pkg/asset/agent/manifests/agentclusterinstall.go
Set default value for `userManagedNetworking` in AgentClusterInstall ZTP manifest regardless of whether the user specified the platform type as `none` or `None`.
Also, return a validation error if the user explicitly specifies `false` when the value must be `true`, instead of overwriting it.
=> OCPBUGS-18365: Fix defaulting of userManagedNetworking value

pkg/asset/installconfig/aws/permissions.go
**Add the permission as a base check. This will error out when the user does not have the DescribeSecurityGroupRules permission.
=> OCPBUGS-18450: AWS permission missing for security group viewing.

pkg/asset/machines/master.go, pkg/asset/machines/worker.go
We have observed that when booting up the node, IPv4 and IPv6 stacks can come up at different times causing OpenShift networking services to start when IPv4 is ready but IPv6 is not. This is not desired for dual-stack setups where both stacks should be up before we proceed further.
With this PR we are adding `ip=dhcp,dhcp6` kernel param to master and worker nodes in vSphere scenario when cluster is deployed as dual-stack.
This PR handles only a scenario of initial cluster installation. Conversion from single-stack to dual-stack will be handled separately.
Fixes: OCPBUGS-18428
Contributes-to: [OPNET-230](https://issues.redhat.com//browse/OPNET-230)
=> OCPBUGS-18428: Add ip=dhcp,dhcp6 kernel param for vSphere dual-stack

data/data/bootstrap/files/usr/local/bin/bootstrap-pivot.sh.template, data/data/bootstrap/systemd/units/release-image-pivot.service.template
OKD/FCOS uses FCOS as its bootimage, i.e. when booting cluster nodes the first time during installation. FCOS does not provide tools such as OpenShift Client (`oc`) or hyperkube which are used during single-node cluster installation at first boot (e.g. `oc` in [bootkube.sh](https://github.com/openshift/installer/blob/master/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template)). RHCOS and SCOS include these tools, but FCOS has to [pivot the root fs](https://github.com/openshift/installer/blob/master/data/data/bootstrap/files/usr/local/bin/bootstrap-pivot.sh.template) to [okd-machine-os](https://github.com/openshift/okd-machine-os) first in order to make those tools available.
Pivoting uses `rpm-ostree rebase` but during SNO installation the node will be booted from a FCOS Live ISO …
=> Implement workaround to allow SNO installations for OKD/FCOS

data/data/bootstrap/baremetal/files/etc/containers/systemd/ironic-dnsmasq.container
the dnsmasq binary has these capabilites set in the ironic image and can't run on scos without them Added to the container.
=> OCPBUGS-19017: Add Net capabilities to dnsmasq container

data/data/agent/systemd/units/agent-interactive-console.service
If agent-tui fails to run, just carry on and don't block the console and ssh login.
=> OCPBUGS-19037: Handle agent tui failure gracefully

pkg/asset/cluster/tfvars.go
**GCP Xpn: The compute.firewalls.create rule is not required, but a warning should be provided when it is not found.
=> OCPBUGS-17218: Warn when firewall rull missing.

pkg/asset/installconfig/openstack/session.go, pkg/asset/manifests/openstack/cloudproviderconfig.go, pkg/asset/manifests/openstack/cloudproviderconfig_test.go
We allow users to specify an external network to create the floating IPs from on the install-config.yaml. We use that to create the API and Ingress FIPs and forget about it. We can however also use it to configure the cloud-provider-openstack to make sure it'll choose the correct network when creating FIPs for the `type=LoadBalancer` Services too. This commit implements it.
=> OpenStack: Set external network for cloud-provider

data/data/install.openshift.io_installconfigs.yaml, pkg/asset/manifests/external/infrastructure.go, pkg/asset/manifests/infrastructure.go, pkg/types/external/defaults/platform.go, pkg/types/external/platform.go
Introduces a new configuration to the platform external platform spec which allows an external cloud provider to be enabled.  By default, external cloud providers will be disabled.
=> SPLAT-1170: enable cloud controller manager type to be defined

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.15 boot image metadata. Issues fixed in this bootimage are:
OCPBUGS-15843 - No way to enable FIPS in RHCOS Live ISO
```
x86_64=415.92.202309142014-0                                      \
aarch64=415.92.202309142014-0                                     \
s390x=415.92.202309142014-0                                       \
ppc64le=415.92.202309142014-0
```
=> OCPBUGS-18945: update RHCOS 4.15 bootimage metadata to 415.92.202309161058-0

docs/user/openstack/deploy_dual_stack_cluster.md
Given we are using a provider network in the example, we should recommend adding the network in the router as external gateway instead.
=> OpenStack: fix IPv6 docs

pkg/asset/agent/manifests/agentclusterinstall.go, pkg/asset/agent/manifests/agentclusterinstall_test.go
If CPUPartitioning is set to install-config, set it in the install-config overrides in agentclusterinstall.yaml.
=> OCPBUGS-18876: Pass CPUPartitioning via install-config overrides if set

data/data/bootstrap/files/usr/local/bin/bootstrap-pivot.sh.template, data/data/bootstrap/systemd/units/release-image-pivot.service.template, pkg/asset/ignition/bootstrap/common.go
Some of the scripts generated by the `create ignition-configs` command for OKD may require to discriminate the cases where SNO is being managed or agent-based installer is currently used, thus adding the `OPENSHIFT_INSTALL_INVOKER` env var in the template inputs.
=> AGENT-710: Use invoker for bootstrap template generation

pkg/asset/manifests/cloudproviderconfig.go
AWS Service endpoints are injected into the cloud.conf cloud-provider config by the cluster-config operator running on bootstrap, as described in:
https://github.com/openshift/enhancements/blob/master/enhancements/installer/aws-custom-region-and-endpoints.md
OCPBUGS-12707 occurs because the installer does not, by the design in the enhancement,
write the service endpoints to the cloud config and there are no other uses of the config, so the installer does not populate the config at all. Accordingly, with no installer-generated config, the infrastructure object does not include a reference to the config.
The bug occurs because the MCO's bootstrap mode rendering of the cloud provider config depends on the infrastructure object containing the name of the cloud.conf, but because that is not …
=> OCPBUGS-12707: always write AWS cloud.conf

pkg/terraform/stages/aws/stages.go
Destroy AWS bootstrap will now use the terraform option -refresh=false.
https://developer.hashicorp.com/terraform/cloud-docs/run/modes-and-options#skipping-automatic-state-refresh Adding the option so that the terraform state is not refreshed. This should counter the requirement to bump the terraform aws provider for DescribeSecurityGroupRule changes that we have noticed since the bump to 5.4.0.
=> OCPBUGS-18830: AWS terraform bootstrap destroy will not refresh state

cmd/openshift-install/create.go
This is a temporary workaround until the ability to configure install timeouts becomes available.
=> OCPBUGS-18187: Increase bootstrap timeout for vSphere platform by 30 mins

pkg/asset/agent/installconfig.go
This warning is both incorrect - since it checks against "None" it generates a warning when not set, and no longer relevant now that https://issues.redhat.com//browse/OCPBUGS-18876 has been fixed.
=> OCPBUGS-19699: Remove warning about CPUPartitioning

pkg/asset/installconfig/powervs/metadata.go
This fixes a dropped `err` variable in `pkg/asset/installconfig/powervs`.
=> pkg/asset/installconfig/powervs: fix dropped error

pkg/asset/agent/installconfig.go, pkg/asset/agent/installconfig_test.go, pkg/asset/agent/manifests/infraenv.go
Enable openshift-install to be able to create agent based install ISO for Power, and it only supports platform none.
=> MULTIARCH-3701: Enable ppc64le for agent installer

data/data/gcp/variables-gcp.tf
** When authenticating with VM credentials the empty string was used in terraform, but null should be used.
=> OCPBUGS-19376: GCP default value for service account

data/data/aws/bootstrap/main.tf, data/data/aws/cluster/iam/main.tf, data/data/aws/cluster/master/main.tf, pkg/destroy/aws/aws.go
** Instance profiles are not always cleaned up correctly. Tags are available for these resources. Tag the resources and let the destroy functions find the resources by tag to be removed.
=> OCPBUGS-18986: Tag aws instance profiles.

data/data/agent/systemd/units/agent-interactive-console-serial@.service, data/data/agent/systemd/units/agent-interactive-console.service, pkg/asset/agent/image/ignition.go
Run agent-tui on the serial console when there is no graphical console available.
=> OCPBUGS-19093,OCPBUGS-19688: Allow agent-tui to use serial console

pkg/asset/agent/image/ignition.go, pkg/asset/ignition/bootstrap/common.go
We should not restrict the mode of this file beyond its defaults. It doesn't contain secret data (and anyways, user workloads are isolated form the host).
But specifically doing this breaks bootc/rpm-ostree's default privilege dropping when fetching container images.
=> CORS-2479: agent: Ensure registries.conf is world readable

data/data/gcp/cluster/dns/base.tf, data/data/gcp/cluster/dns/variables.tf, data/data/gcp/cluster/iam/main.tf, data/data/gcp/cluster/main.tf, data/data/install.openshift.io_installconfigs.yaml, pkg/asset/installconfig/gcp/client.go, pkg/asset/installconfig/gcp/mock/gcpclient_generated.go, pkg/asset/installconfig/gcp/validation.go, pkg/asset/installconfig/gcp/validation_test.go, pkg/asset/machines/gcp/machines.go, pkg/tfvars/gcp/gcp.go, pkg/types/gcp/machinepools.go, pkg/types/gcp/validation/machinepool.go, pkg/types/validation/machinepools.go, pkg/types/validation/machinepools_test.go
**Add service account field to the install config for control Planes
**Validation to ensure service account field added is only used for xpn installs **Add Validation to ensure that the service account is available in the host project
** Machine manifests will use the provided service account for control planes.
**Pass the service account data used for creating control plane nodes during a shared vpn install.
Manual back port of #7308
=> OCPBUGS-19670: [release-4.13] Allow different service account for xpn installs in gcp

pkg/asset/installconfig/azure/validation.go
NVMe-only controller type VM families are not yet supported by the azure terraform provider [1]. This commit adds a check during install validation so those VM families cannot be selected, which would cause the install to fail with
```
09-07 17:55:57.613  level=error msg=Error: creating Linux Virtual Machine: (Name "jima-test-wlgrr-bootstrap" / Resource Group "jima-test-wlgrr-rg"): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="The VM size 'Standard_E112ibs_v5' cannot boot with OS image or disk. Please check that disk controller types supported by the OS image or disk is one of the supported disk controller types for the VM size 'Standard_E112ibs_v5'. Please query sku api at …
```
=> OCPBUGS-18690: ic: azure: validate NVMe-only family types

cmd/openshift-install/testdata/agent/pxe/configurations/compact_external.txt, cmd/openshift-install/testdata/agent/pxe/configurations/sno.txt, pkg/asset/agent/image/kargs.go, pkg/asset/agent/manifests/agent.go
When creating an Agent ISO for OCI, add the kernel argument `console=ttyS0` to the ISO/PXE kargs.
CoreOS does not include a console arg by default when using metal as the platform because different hardware has different consoles and specifying one can cause booting to fail on some, but it [does](https://github.com/coreos/fedora-coreos-config/blob/stable/platforms.yaml) on many cloud platforms. Since we know when the user is definitely using OCI  and we know the correct settings for OCI, we should set them up automatically.
@pawanpinjarkar
=> OCPBUGS-19092: Enable serial console for external OCI platform

cmd/openshift-install/agent/waitfor.go, cmd/openshift-install/analyze.go, cmd/openshift-install/command/log.go, cmd/openshift-install/create.go, cmd/openshift-install/destroy.go, cmd/openshift-install/gather.go, cmd/openshift-install/main.go, cmd/openshift-install/waitfor.go, pkg/agent/cluster.go, pkg/agent/kube.go, pkg/agent/rest.go, pkg/agent/waitfor.go
Updated "agent wait-for" commands to also call
SetupFileHook(RootOpts.Dir) so that it logs to the common .openshift_install.log file.
Moved log.go and rootOpts to a command package so that it can be shared with agent wait-for.
=> OCPBUGS-5728: Log "agent wait-for" commands to .openshift_install.log

OWNERS_ALIASES
Spare people not working directly on the agent installer from all the email notifications.
=> OWNERS: Remove obsolete agent reviewers

images/openstack/Dockerfile.ci
Ansible-Core was only available as version 2.12.2 through yum (even with updates). The version was causing issues when  attempting to install the required collections. The ansible-core version is installed via pip to 2.15.x and all collections can be installed.
=> OCPBUGS-20058: Use updated ansible-core for Openstack image

cmd/openshift-install/testdata/agent/pxe/configurations/sno_arm.txt
Currently the integration tests are failing because `https://rhcos.mirror.openshift.com/art/storage/prod/streams/4.15-9.2/builds/415.92.202309142014-0/aarch64/rhcos-415.92.202309142014-0-live.aarch64.iso` cannot be download. It's not still clear if it's a network issue or something else, in any case this patch temporarily disable the affected 
test to avoid impacting (unrelated) PRs
=> Disable pxe sno arm integration test

images/openstack/Dockerfile.ci
** Ansible-Core was only available as version 2.12.2 through yum (even with updates). The version was causing issues when
attempting to install the required collections. The ansible-core version is installed via pip to 2.15.x and all collections can be installed.
=> OCPBUGS-20141: [release-4.13] Use updated ansible-core for Openstack image

images/openstack/Dockerfile.ci
** Ansible-Core was only available as version 2.12.2 through yum (even with updates). The version was causing issues when
attempting to install the required collections. The ansible-core version is installed via pip to 2.15.x and all collections can be installed.
=> OCPBUGS-20145: [release-4.12] Use updated ansible-core for Openstack image

pkg/asset/installconfig/powervs/client.go, pkg/asset/installconfig/powervs/dns.go, pkg/asset/installconfig/powervs/metadata.go, pkg/asset/installconfig/powervs/regions.go, pkg/asset/installconfig/powervs/session.go, pkg/asset/installconfig/powervs/validation_test.go, pkg/asset/machines/powervs/machines.go, pkg/asset/machines/powervs/machinesets.go, pkg/destroy/powervs/cloud-instance.go, pkg/destroy/powervs/cloud-sshkey.go, pkg/destroy/powervs/dhcp.go, pkg/destroy/powervs/dns-dns.go, pkg/destroy/powervs/dns-resource.go, pkg/destroy/powervs/image.go, pkg/destroy/powervs/job.go, pkg/destroy/powervs/loadbalancer.go, pkg/destroy/powervs/power-instance.go, pkg/destroy/powervs/power-sshkey.go, pkg/destroy/powervs/powervs.go, pkg/destroy/powervs/publicgateway.go, pkg/destroy/powervs/securitygroup.go, pkg/destroy/powervs/serviceinstance.go, pkg/destroy/powervs/subnet.go, pkg/destroy/powervs/vpc.go, pkg/terraform/stages/powervs/stages.go
Wrote a program [1] to remove all occurances of the go-lang errors package.
1) https://github.com/hamzy/powervs-hack/tree/main/remove-errors
=> PowerVS: Remove deprecated errors package

pkg/asset/installconfig/powervs/validation_test.go, pkg/types/powervs/powervs_regions.go, pkg/types/validation/installconfig_test.go
Currently the only zone that supports PER is dal10. Other than that, we'll keep mon01 and osa21 to keep CI running. Remove all zones except for dal10, mon01, and osa21.
https://issues.redhat.com/browse/MULTIARCH-3790
=> PowerVS: MULTIARCH-3790 Remove zones that only have CCs with exceptions

pkg/asset/installconfig/gcp/validation.go, pkg/asset/installconfig/gcp/validation_test.go, pkg/asset/installconfig/platformcredscheck.go, pkg/types/gcp/doc.go
**Altered GCP validation to check the type of credentials that are set (if they are set). The installer cannot
count on GCP credentials being nil or unset when authenticating using the gcloud cli. Now the installer checks for nil credentials and if the credentials exist then check the type.
=> OCPBUGS-17757: check credentials type to handle different gcp authentication methods

pkg/asset/installconfig/openstack/validation/cloudinfo.go, pkg/asset/installconfig/openstack/validvaluesfetcher.go, pkg/asset/machines/openstack/machines.go, pkg/asset/manifests/openstack/cloudproviderconfig.go, pkg/destroy/openstack/glance.go, pkg/destroy/openstack/openstack.go, pkg/tfvars/openstack/bootstrap_ignition.go, pkg/tfvars/openstack/openstack.go, pkg/tfvars/openstack/rhcos_image.go, pkg/types/openstack/defaults/client.go
gophercloud provides the ability to configure a User-Agent header for all API calls. This is a very helpful breadcrumb when debugging issues with the various OpenStack components. Configure it for all OpenStack API clients in the installer.
=> OSASINFRA-3199: Configure User-Agent for OpenStack API calls

data/data/openstack/masters/sg-master.tf, data/data/openstack/masters/sg-worker.tf, pkg/types/validation/installconfig.go
This commit removes the enforcement of the ordering IPv4 to api and ingress VIPs and adds IPv6 security group rules to allow ingress and egress traffic over IPv6.
=> OpenStack: enable IPv6 primary dual-stack cluster

cmd/openshift-install/testdata/agent/image/configurations/external_compact.txt, cmd/openshift-install/testdata/agent/image/configurations/external_with_bootArtifactsBaseURL_minimal_iso.txt, cmd/openshift-install/testdata/agent/image/configurations/external_without_bootArtifactsBaseURL_minimal_iso.txt, cmd/openshift-install/testdata/agent/image/configurations/sno_external_platform.txt, cmd/openshift-install/testdata/agent/pxe/configurations/compact_external.txt, pkg/asset/agent/installconfig.go, pkg/asset/agent/installconfig_test.go, pkg/asset/agent/manifests/agentclusterinstall.go, pkg/asset/agent/manifests/agentclusterinstall_test.go
- Adds a validation that cloudControllerManager field must be set to `External`
when using oci as the external platform.
- The default value for cloudControllerManager is an empty string. 
- Pass cloudControllerManager field value through to the install-config overrides 
so that assisted-service uses it in the install-config 
which ultimately generates the Infrastructure manifest
=> OCPBUGS-18455: Unable to disable external CCM for platform external

data/data/agent/systemd/units/agent-interactive-console.service
If there is only a serial console, do not start agent-tui since it will not be visible.
We assume that there will be a graphical console if there is a framebuffer device (/dev/fb0). On x86 an alternative would be to check for the existence of /sys/class/vtconsole/vtcon1. However, in the absence of a range of hardware to test, the former seems more likely to work on other platforms as well.
Backported from #7526
=> [release-4.14] OCPBUGS-19922: Do not start agent-tui if no graphical console available

pkg/asset/agent/manifests/staticnetworkconfig/generator.go
- Check if nmstatectl executable exists
- Print `install nmstate` 
Fixes OCPBUGS-19086
=> OCPBUGS-19086: Check if nmstatectl executable exists in the system

data/data/bootstrap/baremetal/files/etc/NetworkManager/dispatcher.d/30-local-dns-prepender.template, pkg/asset/ignition/bootstrap/common.go
OKD/FCOS uses FCOS without OKD/OCP code as bootimages for IPI, SNO and Agent-based Installer. FCOS uses systemd-resolved for handling DNS queries.
During installation, the bootstrap node or rendezvous host executes a bootkube.sh script which queries the cluster api.* and api-int.* endpoints to detect when the in-cluster control plane has come up. The DNS name resolution of these endpoints is supposed to be handled by CoreDNS which listens to 0.0.0.0:53 at the same node and is registered with 127.0.0.1 in /etc/resolv.conf.
Some tools such as curl which are called via [bootkube.sh](https://github.com/openshift/installer/blob/master/data/data/bootstrap/files/usr/local/bin/bootstrap-verify-api-server-urls.sh) do not query /etc/resolv.conf but use [Name Service Switch …
=> OCPBUGS-19552: Fixed DNS issues in OKD/FCOS due to split dns in systemd-resolved

data/data/install.openshift.io_installconfigs.yaml, data/data/powervs/cluster/main.tf, data/data/powervs/cluster/power_network/pi_network.tf, data/data/powervs/variables-powervs.tf, pkg/asset/cluster/tfvars.go, pkg/asset/quota/quota.go, pkg/tfvars/powervs/powervs.go, pkg/types/powervs/platform.go
One thing we can remove that will make removing cloud connections entirely later on easier is the ability to reuse a cloud connection.
This will require removing any vars in the installer that are specific to cloud connections and then removing the terraform specific to reusing a cloud connection.
This will leave us with an installer that can still be used in CI but is less entangled with cloud connections.
https://issues.redhat.com/browse/MULTIARCH-3791
=> PowerVS: MULTIARCH-3791 Remove cloud connection reuse functionality

data/data/openstack/masters/sg-master.tf
Since manage-security-groups is enabled by default, the cloud-provider-openstack opens the necessary SG rules for the Services. This commit updates the security group rules to only allow traffic inside the cluster.
=> OpenStack: Adapt nodePorts range 0.0.0.0/0 sg rules

cmd/openshift-install/testdata/agent/pxe/configurations/compact_external.txt, cmd/openshift-install/testdata/agent/pxe/configurations/sno.txt, pkg/asset/agent/image/kargs.go, pkg/asset/agent/manifests/agent.go
Manual cherrypick of https://github.com/openshift/installer/pull/7511
---
When creating an Agent ISO for OCI, add the kernel argument console=ttyS0 to the ISO/PXE kargs.
CoreOS does not include a console arg by default when using metal as the platform because different hardware has different consoles and specifying one can cause booting to fail on some, but it does on many cloud platforms.
Since we know when the user is definitely using OCI and we know the correct settings for OCI,
we should set them up automatically.
=> OCPBUGS-20345: Enable serial console for external OCI platform

pkg/asset/agent/manifests/agentclusterinstall.go
In the Load() method of AgentClusterInstall, we sometimes make changes to the input data to maintain backwards compatibility and such. However, these changes had no effect because we always used the original file read from disk as the generated output, even when it didn't match the actual config.
Regenerate the data to use in the Agent ISO at the conclusion of loading.
=> OCPBUGS-19444: Use changes to AgentClusterInstall during loading

hack/go-integration-test.sh
* By default `-p` is equal to `GOMAXPROCS`, forcing it to ensure that the integration tests are executed in parallel
* By default test timeout is 10m, in some cases is not enough, especially when downloading ISO images with a slower network, thus disabling it to avoid intermittent failures (`oc` command may remain hanging)
=> Enforcing the serial execution of the integration tests

pkg/types/gcp/validation/platform.go
Regex check used for validating GCP label key configured in install-config expects minimum two characters for the key, which is corrected to accept minimum 1 character and maximum of 63 characters.
=> OCPBUGS-21781: Rectify GCP label key validation check

cmd/openshift-install/testdata/agent/image/configurations/external_compact.txt, cmd/openshift-install/testdata/agent/image/configurations/external_with_bootArtifactsBaseURL_minimal_iso.txt, cmd/openshift-install/testdata/agent/image/configurations/external_without_bootArtifactsBaseURL_minimal_iso.txt, cmd/openshift-install/testdata/agent/image/configurations/sno_external_platform.txt, cmd/openshift-install/testdata/agent/pxe/configurations/compact_external.txt, pkg/asset/agent/installconfig.go, pkg/asset/agent/installconfig_test.go, pkg/asset/agent/manifests/agentclusterinstall.go, pkg/asset/agent/manifests/agentclusterinstall_test.go
Manual cherry-pick of https://github.com/openshift/installer/pull/7533
___
Adds a validation that cloudControllerManager field must be set to External when using oci as the external platform.
The default value for cloudControllerManager is an empty string. Pass cloudControllerManager field value through to the install-config overrides so that assisted-service uses it in the install-config which ultimately generates the Infrastructure manifest
=> [release-4.14] OCPBUGS-20396: Unable to disable external CCM for platform external

cmd/openshift-install/testdata/agent/image/validations/no-rendezvousip.txt, pkg/asset/agent/image/ignition.go, pkg/asset/agent/image/ignition_test.go, pkg/asset/agent/manifests/nmstateconfig.go, pkg/asset/agent/manifests/nmstateconfig_test.go
This patch enhances the rendezvousIP selection logic when it's not explicitly defined in the agent-config.yaml. In such case, it tries to look for an eligible IP within the non-worker hosts eventually configured in the agent-config.yaml first. If none is found (there couldn't be any host defined, or defined without nmstate config), it falls back to the previous behavior (by looking at the static configuration potentially loaded from the `nmstateconfig.yaml` file)
=> OCPBUGS-5471: Try to select rendezvousIP among non-worker hosts

pkg/asset/installconfig/aws/permissions.go, pkg/asset/installconfig/platformpermscheck.go
If users have specified the  KMS encryption keys in the install config, 
either in the master machine pool or the aws machine pool, 
then add the required permission group to the permission check.
=> OCPBUGS-13664: Add KMS encryption keys if provided

pkg/asset/cluster/tfvars.go
If no `additionalSecurityGroupIDs` is specified for controlPlane, make sure that `additionalSecurityGroupIDs` from  defaultMachinePlatform is used instead.
=> OCPBUGS-20525: aws: use security groups from defaultMachinePlatform

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.14 boot image metadata. Issues fixed in this bootimage are:
OCPBUGS-17154: 4.14/AWS: Machines using m4 instance types don't get network
```
x86_64=414.92.202310170514-0                                     \
aarch64=414.92.202310170514-0                                    \
s390x=414.92.202310170514-0                                      \
ppc64le=414.92.202310170514-0
```
=> OCPBUGS-20357: update RHCOS 4.14 bootimage metadata to 414.92.202310170514-0

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.15 boot image metadata. Issues fixed in this bootimage are:
OCPBUGS-20356: Machines using m4 instance types don't get network
```
x86_64=415.92.202310170229-0                                      \
aarch64=415.92.202310170229-0                                     \
s390x=415.92.202310170229-0                                       \
ppc64le=415.92.202310170229-0
```
=> OCPBUGS-20356: update RHCOS 4.15 bootimage metadata to 415.92.202310170229-0

cmd/openshift-install/gather.go, pkg/asset/cluster/cluster.go, pkg/destroy/bootstrap/bootstrap.go, pkg/infrastructure/platform/platform.go, pkg/infrastructure/provider.go, pkg/terraform/stage.go, pkg/terraform/stages/split.go, pkg/terraform/terraform.go
Due to Hashicorp's moving Terraform from an MPL to BSL license, the installer's usage of Terraform presents a risk that we would like to contain. This PR aims to:
1. **Contain Terraform**: moves all terraform dependencies to `pkg/terraform`
2. **Provide an alternative path**:  introduces a generic `infrastructure.Stages` interface (based on `terraform.Stages`) 
The existing code couples the Cluster Asset to terraform dependencies:
```mermaid
flowchart LR
a[Cluster Asset] --- b[Terraform] & c[Stages]
b --- c
```
This PR creates an interface to decouple the cluster asset from Terraform dependencies; and, potentially, allow other infrastructure providers.
```mermaid
flowchart LR
a[Cluster Asset] --- b[Stages Infrastructure Interface] --- c[Terraform] & d[Cloud SDKs] & e[CAPI]
``` …
=> CORS-2836: Refactor Stages, encapsulate terraform

pkg/asset/installconfig/aws/permissions.go, pkg/asset/installconfig/platformpermscheck.go
Reverts #7428 ; tracked by OCPBUGS-22231
Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.
This PR broke default install options for AWS.
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please ensure there's a test added which fails if the default install options cause a crash as requested by @soltysh .
CC: @pawanpinjarkar
<div align="right">
PR created by <a href="https://github.com/stbenjam/revertomatic">Revertomatic<sup>:tm:</sup></a>
</div>
=> Revert #7428 "OCPBUGS-13664: Add KMS encryption keys if provided"

cmd/openshift-install/testdata/agent/image/configurations/vsphere_no-credentials.txt, cmd/openshift-install/testdata/agent/image/configurations/vsphere_with-credentials.txt, cmd/openshift-install/testdata/agent/image/validations/vsphere_with-partial-credentials.txt, pkg/asset/agent/installconfig.go, pkg/asset/agent/installconfig_test.go, pkg/asset/agent/manifests/agentclusterinstall.go, pkg/types/vsphere/conversion/installconfig.go, pkg/types/vsphere/validation/platform.go
If vSphere credentials are present in install-config.yaml, they are passed through as a install-config override annotation in AgentClusterInstall.
If vSphere credentials are not present, then nothing is added to the install-config override.
Requires: https://github.com/openshift/installer/pull/7572
=> AGENT-718: Add vSphere credentials to install-config overrides

pkg/asset/ignition/bootstrap/common.go
Follow up to https://github.com/openshift/installer/pull/7580
/cc @vrutkovs @andfasano
=> OCPBUGS-4038: bootstrap: Skip gatewayd units only on OKD agent-installer

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
That variable isn't used anywhere. The last reference was removed as part of 33a74c7d19 ("bootkube: Drop cruft in MCO bootstrap") a while ago.
Part of trying to get rid of `machine-os-content`:
https://issues.redhat.com/browse/MCO-392
=> bootkube.sh: drop final mention of `machine-os-content`

pkg/destroy/gcp/disk.go
Regional disks are replicated in multiple zones but our logic was not taking them into account, only zonal disks. When trying to run `cluster destroy` in a cluster with regional disks, the following panic was observed:
```
time="2023-07-25T10:02:16Z" level=debug msg="Found disk: pvc-c8cf8f18-cd22-441e-b47a-565bed5573ee in zone europe-west2-a"
time="2023-07-25T10:02:16Z" level=debug msg="Found disk: pvc-3e703665-2271-4c16-8bf8-533b5e7be444 in zone "
E0725 10:02:16.633982       1 runtime.go:79] Observed a panic: runtime.boundsError{x:-1, y:0, signed:true, code:0x1} (runtime error: slice bounds out of range [:-1])
goroutine 1 [running]:
[k8s.io/apimachinery/pkg/util/runtime.logPanic(
{0x7b0e040|http://k8s.io/apimachinery/pkg/util/runtime.logPanic(%7B0x7b0e040]?, 0xc00007dde8}
) …
```
=> OCPBUGS-22489: destroy: gcp: fix destroying regional disks

pkg/asset/installconfig/azure/validation.go, pkg/asset/installconfig/azure/validation_test.go, pkg/types/azure/validation/machinepool.go, pkg/types/azure/validation/machinepool_test.go
This PR adds the following install config validations regarding [Azure Confidential VMs](https://learn.microsoft.com/en-us/azure/confidential-computing/confidential-vm-overview) and [Trusted Launch for VMs](https://learn.microsoft.com/en-us/azure/virtual-machines/trusted-launch):
- Confidential VM (specifically `AMD SEV-SNP`) support for the selected VM size
- Trusted Launch for VMs support for the selected VM size
- Trusted Launch is not supported on Confidential VMs
- when ConfidentialVM with `SecurityEncryptionType: DiskWithVMGuestState` and customer-managed key, the `DiskEncryptionSet.EncryptionType` should be `ConfidentialVMEncryptedWithCustomerKey`
- `Settings.SecurityType` (either `ConfidentialVM` or `TrustedLaunch`) is not currently supported on AzureStack
=> OCPBUGS-18387: Add Azure ConfidentialVM capability and DiskEncryptionSet validations

data/data/bootstrap/openstack/files/etc/NetworkManager/conf.d/02-ipv6.conf, data/data/bootstrap/openstack/files/etc/NetworkManager/system-connections/nmconnection.template
When using an additional network in the cluster,
we end up having two conections of ethernet type, the
main one for the control plane and the additional one.
This would result in Network Manager not happy with the current
Network Manager profile. To avoid this issue, the IPv6
configuration for bootstrap is updated to match the
configuration currently applied on masters and workers[1]. This
config named `addr-gen-mode` ensures nodes get the same IPv6 and mac
addresses that were configured in the OpenStack Ports
[1] https://github.com/openshift/machine-config-operator/blob/release-4.15/templates/common/openstack/files/ipv6-config.yaml
=> Bug OCPBUGS-22298: OpenStack: Fix IPv6 address configuration for bootstrap 

pkg/terraform/stages/powervs/stages.go
When we switched from using the errors package to using fmt.Errorf, we missed the fact that a nil error passed in would return nil.
=> OCPBUGS-22773: PowerVS: fix removeFromLoadBalancers

pkg/asset/installconfig/gcp/session.go
according to
https://cloud.google.com/docs/authentication/provide-credentials-adc#local-key the default for application credentials is to set
GOOGLE_APPLICATION_CREDENTIALS. currently this var is missing from the list of environment variables checked.
this should fix issue #6862
=> OCPBUGS-17866: check GOOGLE_APPLICATION_CREDENTIALS env var

docs/user/openstack/install_upi.md, upi/openstack/inventory.yaml, upi/openstack/security-groups.yaml
Compact clusters have been supported for a while in IPI. To also allow compact clusters on UPI, the security group rules for UPI should be adapted enabling the same ingress traffic that is enabled for workers.
=> OCPBUGS-20403: OpenStack: add SG rules for compact clusters on UPI

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.15 boot image metadata.
```
x86_64=415.92.202310310037-0                                      \
aarch64=415.92.202310310037-0                                     \
s390x=415.92.202310310037-0                                       \
ppc64le=415.92.202310310037-0
```
=> OCPBUGS-22757: update RHCOS 4.15 bootimage metadata to 415.92.202310310037-0

pkg/asset/manifests/openshift.go
[OCPBUGS-22113](https://issues.redhat.com/browse/OCPBUGS-22113):
Builds created with tags=aro result in azure-cloud-provider being generated with the service principal clientID used by the installer.
This results in kube-controller-manager crashlooping, unable to authenticate without the service principal's certificate.
azure-cloud-provider should not be generated in Manual mode.
=> OCPBUGS-22113: Do not generate azure-cloud-provider in manual mode for aro builds

images/installer/Dockerfile.upi.ci
google CLI deprecated` Python 3.5-3.7` from 448.0.0 causing release ci jobs failed with `ERROR: gcloud failed to load. You are running gcloud with Python 3.6, which is no longer supported by gcloud.` . specified version to 447.0.0
Related: https://issues.redhat.com/browse/OCPBUGS-22830
=> OCPBUGS-22830: fix google cli verson to 447.0.0

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.14 boot image metadata.
```
x86_64=414.92.202310210434-0                                     \
aarch64=414.92.202310210434-0                                    \
s390x=414.92.202310210434-0                                      \
ppc64le=414.92.202310210434-0
```
=> OCPBUGS-22758: update RHCOS 4.14 bootimage metadata to 414.92.202310210434-0

pkg/types/ibmcloud/validation/platform.go
Add support to use the Madrid region in IBM Cloud, eu-es.
Related: https://issues.redhat.com/browse/OCPBUGS-19398
=> OCPBUGS-19398: IBMCloud: Add eu-es region

pkg/terraform/terraform.go
Fixes a nil pointer dereference which occurs when there is an error during Terraform apply. A file needs to be written for the cluster asset, but there was a bug where no statefile was being returned upon an error in Terraform apply.
I tested this locally by manually breaking the Terraform configs in the Installer. The result is that the Terraform error is prettily returned:
```
ERROR Error: creating EC2 VPC Endpoint (com.amazonaws.us-east-2.s3): InvalidVpcId.Malformed: Invalid Id: 'my-crazy-vpc' (expecting 'vpc-...; the Id may only contain lowercase alphanumeric characters and a single dash') 
ERROR 	status code: 400, request id: 9178e750-a3a8-423b-be7f-70eb2b31f837 
ERROR                                              
ERROR   with module.vpc.aws_vpc_endpoint.s3[0],    
ERROR   on …
```
=> OCPBUGS-22772: return Terraform statefile on error

pkg/asset/manifests/featuregate.go, pkg/types/featuregates/featuregate.go, pkg/types/featuregates/featuregates.go, pkg/types/gcp/validation/featuregates.go, pkg/types/installconfig.go, pkg/types/validation/featuregate_test.go, pkg/types/validation/installconfig.go, pkg/types/vsphere/validation/featuregates.go
Adds the ability to validate install config fields using feature gates.
Fields can be gated based on any feature set: Default, TechPreviewNoUpgrade, or CustomNoUpgrade.
This means that features can be promoted without changing validation code by vendoring the updated API, where the feature has been promoted to the Default feature set.
Also enables more targeted testing for technical quality.
=> CORS-2877: Install Config Feature Gate Validation

cmd/openshift-install/gather.go, hack/build.sh, pkg/asset/cluster/cluster.go, pkg/destroy/bootstrap/bootstrap.go, pkg/infrastructure/platform/platform.go, pkg/infrastructure/platform/platform_altinfra.go
Build tags in the `pkg/infrastructure/platform.go` and `pkg/infrastructure/platform_altinfra.go` files selectively determine which file is included in the build. `platform.go` contains the normal Terraform dependencies for building infrastructure, while `platform_altinfra.go` will be where we land [non-Terraform implementors of the provider interface](https://github.com/openshift/installer/pull/7573/commits/266882741f4860da9f5fbbe6f1e0367d9b0bb91c#diff-34cd4c77afbf6c0c9931be6bd63b6540c7a0c392c340822dc6b06ec78fc50481). 
By using the `-v` flag with `go build` we can see that no Terraform dependencies are included when building. 
```shell
$ GOFLAGS='-mod=vendor -v' ./hack/build.sh &> normal-verbose-build.log
$ grep github.com/hashicorp/terraform/ normal-verbose-build.log | wc -l
72
$ go …
```
=> CORS-2835: use build tags to produce installer with alternate infrastructure providers

images/terraform-providers/Dockerfile
This Dockerfile will build the terraform provider binaries for all platforms/arches needed by the Installer images. Reusing this container in CI should stop the terraform provider binaries from being built every time there is a change to the Installer repo, since the providers are changed very sparingly.
=> CORS-2428: images: add Dockerfile for a terraform-providers image

images/installer/Dockerfile.upi.ci.rhel8
google CLI deprecated Python 3.5-3.7 from 448.0.0, specified version to 447.0.0
=> [release-4.14] OCPBUGS-22945: Update gcloud version to 447.0.0

pkg/asset/machines/openstack/machines.go, pkg/asset/machines/openstack/machinesets.go
When the network ID or Name is not specified in the `controlPlanePort` field, MAPO would create one Port per Subnet. In dual-stack clusters we must have one unique dual-stack Port. This commit fixes the issue by discovering the network ID from one of the subnets and adding it to the Machine Spec.
=> Bug OCPBUGS-19462: OpenStack: Fix dual-stack machines Spec to contain network

images/installer-altinfra/Dockerfile.ci
Creates the initial Dockerfile to create an image using the altinfra build tag. The Dockerfie is necessary to have the Terraform-free image built by ART.
The altinfra image is a temporary image to provide a Terraform-free image for all providers that have implemented alternate infrastructure providers. Once all providers have implemented non-Terraform solutions it will not be necessary.
=> CORS-2876: images/installer-altinfra: initial Dockerfile

pkg/types/vsphere/validation/machinepool.go, pkg/types/vsphere/validation/machinepool_test.go
I think the original intention behind the validation was to check that, in case `CoresPerSocket` was not set by the user, it would be checked against a default value (currently set to 4). However, that's not what is happening in practice, and both the check against the user-inputed value and the default were being performed.
That means that using CPUS=2 and CoresPerSocket=2 as exemplified in the official docs [1] would result in a validation error:
```
failed to create install config: invalid "install-config.yaml" file: controlPlane.platform.vsphere.cpus:
Invalid value: 2: numCPUs specified should be a multiple of cores per socket which is by default 4]
```
even though it's a valid configuration (albeit a pretty tiny compute node).
I'm changing the code a bit to make it more clear what …
=> OCPBUGS-22933: [release-4.12]: vsphere: fix validation of CPUS and CoresPerSocket

images/installer/Dockerfile.upi.ci, images/installer/Dockerfile.upi.ci.rhel8
google CLI deprecated Python 3.5-3.7 from 448.0.0, specified version to 447.0.0
=> OCPBUGS-23141: Specify google cloud CLI to version 447.0.0

cmd/openshift-install/testdata/agent/image/configurations/vsphere_no-credentials.txt, cmd/openshift-install/testdata/agent/image/configurations/vsphere_with-credentials.txt, pkg/asset/agent/manifests/agentclusterinstall.go, pkg/asset/agent/manifests/agentclusterinstall_test.go, pkg/asset/agent/manifests/util_test.go
The assisted-service is deprecating support for the singular APIVIP/IngressVIP in https://github.com/openshift/assisted-service/pull/5501. When that merges it will break the agent-installer since currently APIVIP is set when only one VIP is configured. This change sets both API/Ingress VIP and VIPs and will work before and after the assisted-service change merges. 
Note that as a follow-on, https://github.com/openshift/installer/pull/7574 will remove the multiple settings from install-config override which are not needed after the assisted-service change.
=> AGENT-337: Support both VIP and VIPs in AgentClusterInstall

pkg/asset/cluster/tfvars.go, pkg/asset/installconfig/vsphere/client.go
Instead of using a SplitAfter with the Resource Pool path
and the vCenter Cluster name this PR replaces it
with the Cluster's ManagedObjectReference
and finder.ObjectReference which will set the
InventoryPath.
=> OCPBUGS-23376: vSphere - when using RP network path is incorrect

docs/user/openstack/install_upi.md
This commit removes undefined variable from the script that adds the certificate to the bootstrap ignition shim.
=> OSASINFRA-3294: OpenStack: fix script to update bootstrap ignition shim

images/installer/Dockerfile.upi.ci
Per https://github.com/openshift/release/pull/45591, the 4.11 upi-installer need to install 256.0.0, but not 447.0.0, so we did not backport the [change](https://github.com/openshift/installer/pull/7731) here.
=> [release-4.11] OCPBUGS-23478: Specify google cloud CLI to version 256.0.0

pkg/asset/installconfig/openstack/validvaluesfetcher.go
The network client is currently used to retrieve the flavors available in the cloud, but the compute client should be used instead.
=> OSASINFRA-3295: OpenStack: fix client used to list flavors

pkg/destroy/azure/azure.go
Somehow I missed the `!` when translating `err != context.Canceled` to `!errors.Is(err, context.Canceled)`.
=> no-jira: destroy/azure: fix dropped negation from error comparison

data/data/install.openshift.io_installconfigs.yaml, pkg/asset/machines/machineconfig/powersmt.go, pkg/asset/machines/master.go, pkg/asset/machines/worker.go, pkg/types/powervs/machinepools.go, pkg/types/powervs/validation/machinepool.go
Through the installer, you can currently disable SMT. Power hardware allows levels of control that cannot currently be accessed through the installer (1-8). Until we can control SMT via kargs [0], and until igniton kargs support [1] is available in the MCO, we believe this is the best option for SMT control at install time.
[0] https://lore.kernel.org/all/20230705145143.40545-8-ldufour@linux.ibm.com/
[1] https://github.com/openshift/installer/pull/5439
=> MULTIARCH-3964: Power VS: Control SMT level with machineconfig

pkg/asset/installconfig/azure/validation.go, pkg/asset/installconfig/azure/validation_test.go
If you try to deploy a cluster with a marketplace image that requires a purchase plan to be accepted but set it to `NoPurchasePlan` in the install-config, the VM provisioning will fail with:
```
ERROR Error: waiting for creation of Linux Virtual Machine: (Name "jima02test-7jf8d-bootstrap" / Resource Group "jima02test-7jf8d-rg"): Code="VMMarketplaceInvalidInput" Message="Creating a virtual machine from Marketplace image or a custom image sourced from a Marketplace image requires Plan information in the request. VM: '/subscriptions/$ID/resourceGroups/jima02test-7jf8d-rg/providers/Microsoft.Compute/virtualMachines/jima02test-7jf8d-bootstrap'."
```
Let's check if the `Plan` field actually matches what's expected based on the image's plan properties.
=> OCPBUGS-22840: ic/azure: validate field Plan when for marketplace images

pkg/asset/machines/baremetal/hosts.go, pkg/asset/machines/baremetal/hosts_test.go
Currently, we do not populate any deployment fields when creating
BareMetalHosts, relying on the Machine API to do it instead.
However, not setting customDeploy makes the BMH controller think that
we're doing an image-based deployment and configure its resources
accordingly. If MAPI is slow enough, the hosts become provisioned
before customDeploy is set, and the controller enters a loop trying and
failing to switch away from the image-based deployment.
TL;DR just set customDeploy on creation.
=> OCPBUGS-21777: baremetal: populate customDeploy in advance

pkg/infrastructure/platform/platform.go, pkg/infrastructure/platform/platform_altinfra.go
The build tag was added to assist ARO when rebasing their fork. Including the tag was premature and this is now causing issues for QE.
See comments in: https://issues.redhat.com/browse/OCPBUGS-22113
=> CORS-2835: pkg/infrastructure: remove ARO build tag

go.mod, vendor/modules.txt
When https://github.com/openshift/installer/pull/5635 moved Nutanix under `terraform/providers` it missed removing the import from the root go.mod.
```
$ go mod why github.com/terraform-providers/terraform-provider-nutanix
(main module does not need package
github.com/terraform-providers/terraform-provider-nutanix)
```
=> no-jira: go.mod: remove unused terraform-providers-nutanix import

terraform/Makefile
Store the hash of the go.mod in the built binary which we can then use to determine if a provider needs to be rebuild. Useful when we import pre-built binaries from a container image.
=> CORS-2428: terraform: add build information to binaries

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Should merged with 
1. https://github.com/openshift/api/pull/1666
2. https://github.com/openshift/cluster-config-operator/pull/379
3. https://github.com/openshift/cluster-config-operator/pull/349
ideally these all land in a single unit.  If they don't, merges to openshift/api will get wedged on machine-configs not matching until they do.
=> Skip cluster config

data/data/agent/files/usr/local/bin/agent-gather
The hosts and clusters tables are queried for their status and validation_info information. This information can aid in triaging cluster installation failures when the validation information from wait-for bootstrap is missing or inadequate.
=> AGENT-670: Add assisted-db data to agent-gather

upi/openstack/common.yaml
Since Kuryr removal we don't need to generate the trunks name anymore. This commit removes it.
=> OSASINFRA-3303: OpenStack: remove generation of trunks name

data/data/azure/bootstrap/main.tf, data/data/azure/variables-azure.tf, data/data/azure/vnet/main.tf, data/data/install.openshift.io_installconfigs.yaml, pkg/asset/cluster/tfvars.go, pkg/explain/printer_test.go, pkg/tfvars/azure/azure.go, pkg/tfvars/tfvars.go, pkg/types/azure/platform.go, pkg/types/azure/validation/platform.go, pkg/types/azure/validation/platform_test.go
Added a field to accept the customer managed key vault id and
user assigned identity required for the encryption of storage
account.
=> CORS-2845: azure: Enable storage account encryption

cmd/openshift-install/gather.go, pkg/asset/cluster/cluster.go, pkg/asset/cluster/metadata.go, pkg/destroy/bootstrap/bootstrap.go, pkg/infrastructure/platform/platform.go, pkg/infrastructure/platform/platform_altinfra.go, pkg/types/clustermetadata.go
Plumbs feature gates through to the infrastructure provider package to enable exposing alternate infrastructure providers through feature gates. Particularly enables the AWS sdk infrastructure provider.
Also includes a fixup of the machine manifests due to the API bump. 
This PR plumbs the featuregate into the cluster metadata so that it can be used with the bootstrap destroy code. I know this can be problematic for hive (cc @2uasimojo) when we depend on updates to cluster metadata for destroy code, because cluster metadata is not always present. The functionality added here is only being used in bootstrap destroy code, so I don't think this will negatively affect hive. I think it would be a good idea to remove the feature gate field from the metadata once we have finished implementing …
=> CORS-2978: enable AWS SDK Installation through feature gates

cmd/openshift-install/testdata/agent/pxe/configurations/sno_arm.txt
Removing the sno_arm.txt because it is trying to extract arm64 pxe items from an x86 release payload.
Currently blocking https://github.com/openshift/installer/pull/7595
@aleskandro I'm pretty sure QE is already catching this on nightly's somewhere?
=> OCPBUGS-24008: Remove sno_arm.txt integration test

images/installer-artifacts/Dockerfile.rhel
The installer-artifacts image depends on the installer image, which means they cannot be built in parallel. The effect of this dependency is that the installer-artifacts image contains the linux amd64 builds in addition to the mac/linux amd64/arm64 builds present in the installer-artifacts image.
Breaking the dependency results in a more efficient build process because they can be built in parallel as well as no duplication of the linux amd64 binary in the release image (before this change the binary would be present in both images within the release image).
The risk, though, is that clients are inconsistently grabbing the linux amd64 binary from either image, rather than only the installer image, in which case we would break any client trying to get that binary from the …
=> CORS-2785: images: decouple installer and installer-artifacts

pkg/asset/agent/image/agentartifacts.go, pkg/asset/agent/image/oc.go
Enable the use of multi payload for the agent installer by adding the --filter-by-os flag when using oc
[Dockerfile.assisted-service.ocp](https://github.com/openshift/assisted-service/blob/c829a60a395054bdb9d77388e56d0d0420ef9670/Dockerfile.assisted-service.ocp#L24) is missing skopeo as a dependency. The PR to fix the problem is [here](https://github.com/openshift/assisted-service/pull/5558)
=> MIXEDARCH-310: Enable the use of the multi payload for agent installer

pkg/asset/machines/master.go, pkg/asset/machines/master_test.go
IsMachineManifest() should match all of the manifests generated by either the Master or Worker machines asset. Several new types of files have been added, particularly for baremetal, without updating this function. This resulted in the files being matched by the generic OpenShift Manifests asset as well as the one that actually created them.
As a result, there was a bogus warning every time we generated the manifests for a baremetal cluster:
```
WARNING Discarding the Openshift Manifests that was provided in the target directory because its dependencies are dirty and it needs to be regenerated
```
even when there is no pre-existing `openshift` directory with contents to discard.
=> OCPBUGS-23539: Keep Machine manifests out of OpenShift Manifests asset

pkg/asset/asset.go, pkg/asset/cluster/cluster.go, pkg/terraform/terraform.go
if provider.Provision() returns nil for files, it's appended to the filelist. When the asset store attempts to iterate of this, it joins a nil file to a directory thus segfaulting.
=> no-jira: pkg/asset: safety nets to keep installer from crashing

data/data/install.openshift.io_installconfigs.yaml, data/data/powervs/bootstrap/iaas/iaas.tf, data/data/powervs/bootstrap/iaas/variables.tf, data/data/powervs/bootstrap/main.tf, data/data/powervs/cluster/iaas/iaas.tf, data/data/powervs/cluster/iaas/outputs.tf, data/data/powervs/cluster/iaas/variables.tf, data/data/powervs/cluster/main.tf, data/data/powervs/variables-powervs.tf, pkg/asset/cluster/powervs/powervs.go, pkg/asset/cluster/tfvars.go, pkg/asset/installconfig/platformprovisioncheck.go, pkg/asset/installconfig/powervs/client.go, pkg/asset/installconfig/powervs/mock/powervsclient_generated.go, pkg/asset/installconfig/powervs/validation.go, pkg/asset/installconfig/powervs/validation_test.go, pkg/asset/machines/powervs/machines.go, pkg/asset/manifests/cloudproviderconfig.go, pkg/asset/manifests/powervs/cloudproviderconfig.go, pkg/destroy/powervs/powervs.go, pkg/tfvars/powervs/powervs.go, pkg/types/powervs/metadata.go, pkg/types/powervs/platform.go, pkg/types/powervs/validation/platform.go, pkg/types/powervs/validation/platform_test.go
We were made aware of a valid use of bring-your-own service instance recently. Therefore, reintroduce serviceInstanceGUID to install-config.yaml since there is a use case for it now.
https://issues.redhat.com/browse/MULTIARCH-4030
=> PowerVS: MULTIARCH-4030: Reintroduce serviceInstanceGUID install option

cmd/openshift-install/testdata/agent/image/configurations/vsphere_no-credentials.txt, cmd/openshift-install/testdata/agent/image/configurations/vsphere_with-credentials.txt, pkg/asset/agent/manifests/agentclusterinstall.go, pkg/asset/agent/manifests/agentclusterinstall_test.go, pkg/asset/agent/manifests/util_test.go
The agent installer has been using install-config override to set multiple VIPs since https://github.com/openshift/installer/pull/6530. The fields for multiple fields are avaiable in AgentClustInstall and should be used now that https://issues.redhat.com/browse/AGENT-692 is fixed.
=> AGENT-337: Set VIPs directly in api, instead of install-config override

data/data/azure/bootstrap/main.tf, data/data/azure/bootstrap/outputs.tf, data/data/azure/bootstrap/storage.tf, data/data/azure/bootstrap/variables.tf, data/data/azure/cluster/main.tf, data/data/azure/cluster/master/master.tf, data/data/azure/cluster/master/variables.tf, data/data/azure/cluster/variables.tf, data/data/azure/vnet/main.tf, data/data/azure/vnet/outputs.tf
Azure storage accounts are persisted for the life of an OpenShift cluster. The goal is to destroy the storage account along with other bootstrap resources during the bootstrap destroy process. Instead of creating the storage account in the vnet stage we move it to the bootstrap stage, so that it will be destroyed with the bootstrap resources. The storage account holds a temporary bootstrap image identical to the long lived cluster image.
=> CORS-2525: Azure: remove storage account with bootstrap destroy

docs/user/aws/install_edge-zones.md, pkg/asset/installconfig/aws/availabilityzones.go, pkg/asset/installconfig/aws/subnet.go, pkg/asset/installconfig/aws/validation.go, pkg/tfvars/aws/aws.go, pkg/types/aws/availabilityzones.go
This change introduces support for BYO VPC when installing a cluster in Wavelength Zones by:
- classifying subnets with zone type `wavelength-zone` as edge zone
This PR is created based on https://github.com/openshift/installer/pull/7369 , the following commits are related to this PR:
- [aws byovpc: classifying wavelength subnets as edge](https://github.com/openshift/installer/commit/cf9c3ac44d5286c781b3c9a1c1e3f77022b043d8)
- [aws/doc: updating edge zones Documentation with Wavelength Zone steps](https://github.com/openshift/installer/pull/7652/commits/77a07ffdd1d44bfaec3405d0df8ab75104488e65)
The following CloudFormation Templates have been introduced in https://github.com/openshift/installer/pull/7722:
- Create Carrier Gateway: provisions carrier gateway and route table for Wavelength …
=> SPLAT-1218: AWS BYO VPC support for Wavelength Zones

pkg/asset/agent/image/agentpxefiles.go, pkg/asset/agent/installconfig.go, pkg/asset/agent/installconfig_test.go, pkg/asset/agent/manifests/infraenv.go
Added s390x as a supported architecture.
Update PXE files generation to generate kernel.img for s390x as there is no vmlinuz present for it.
=> MULTIARCH-2678: Patch for Agent Based Installer to support s390x as supported architecture.

docs/user/openstack/install_upi.md, upi/openstack/bootstrap.yaml, upi/openstack/common.yaml, upi/openstack/compute-nodes.yaml, upi/openstack/control-plane.yaml, upi/openstack/inventory.yaml, upi/openstack/network.yaml, upi/openstack/security-groups.yaml, upi/openstack/update-network-resources.yaml
This PR includes steps to enable a dualstack cluster. Note that  users need to provide the addresses of API and Ingress VIPs, that were already allocated by Neutron, to the `install-config.yaml` . To achieve that the network resources are now created prior to populating the `install-config` file and later on are tagged with the clusterID tag.
=> OSASINFRA-3261: OpenStack: support dualstack in UPI

data/data/aws/bootstrap/main.tf
If S3 versioning is enabled, destroy may fail with:
BucketNotEmpty: The bucket you tried to delete is
not empty. You must delete all versions in the bucket.
Adding the[ force_destroy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#force_destroy) attribute should destroy the bucket, even with versioning enabled.
=> OCPBUGS-23458: force destroy bootstrap ign

hack/build.sh
Parallel builds can be achieved by setting the MAKEFLAGS env var. Hardcoding the value is causing some container builds to fail in CI with
```
{  error occurred handling build openstack-installer-amd64: build not successful after 5 attempts: [the build openstack-installer-amd64 failed after 7m36s with reason BuildPodEvicted: The node was low on resource: memory. Threshold quantity: 100Mi, available: 65128Ki. Container docker-build was using 10522940Ki, request is 5Gi, has larger consumption of memory. , the build openstack-installer-amd64 failed after 6m31s with reason BuildPodEvicted: The node was low on resource: memory. Threshold quantity: 100Mi, available: 53452Ki. Container docker-build was using 10936476Ki, request is 5Gi, has larger consumption of memory.
```
=> no-jira: hack: drop hardcoded -j8 in make invocations.

images/infrastructure-providers/Dockerfile
We don't need a builder image to just copy the binaries built in previous layers. Use `base` instead for the final container image.
=> no-jira: image: infra-providers: use base image instead of builder

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.15 boot image metadata. Notable
fixes in the boot image for:
OCPBUGS-18833 - Failed to mount gcp volume with "failed to find and re-link disk"
OCPBUGS-22259 - kubevirt platform not supported by afterburn-hostname.service
In addition eu-es region was added for PowerVS.
```
x86_64=415.92.202311241643-0                                      \
aarch64=415.92.202311241643-0                                     \
s390x=415.92.202311241643-0                                       \
ppc64le=415.92.202311241643-0
```
=> OCPBUGS-23473: update RHCOS 4.15 bootimage metadata to 415.92.202311241643-0

data/data/powervs/cluster/main.tf, data/data/powervs/cluster/transit_gateway/transit_gateway.tf, data/data/powervs/cluster/transit_gateway/variables.tf, data/data/powervs/variables-powervs.tf, pkg/asset/cluster/tfvars.go, pkg/asset/installconfig/powervs/client.go, pkg/asset/installconfig/powervs/mock/powervsclient_generated.go, pkg/tfvars/powervs/powervs.go
We pivoted from the original approach. Skip the part that's been stricken out.
~Presence of Transit Gateway in the target Workspace in PowerVS suggests there is an existing cluster (or other arbitrary workload), and sharing it with the new cluster that the current installer run would create could be a problem. Therefore, we decided to block install from proceeding if we detect such a condition.~
~So, we first get all the TGs in the account, loop through them checking all associated connections of each TG, until finding a match to the target Workspace, or reaching the end.~
With late discovery of limitation as of how many Transit Gateway you can have in an account (default: 10), we decided to allow reuse of existing TGs if one happens to be attached to the target workspace that the …
=> MULTIARCH-4042: Reuse existing Transit Gateway in target Workspace, or create anew

cmd/openshift-install/testdata/agent/image/configurations/baremetal_host_bmc_config.txt, pkg/asset/agent/agentconfig/agenthosts.go, pkg/asset/agent/installconfig.go, pkg/asset/agent/installconfig_test.go, pkg/asset/agent/manifests/agentclusterinstall.go, pkg/asset/agent/manifests/agentclusterinstall_test.go, pkg/asset/agent/manifests/util_test.go, pkg/types/agent/agent_config_type.go, pkg/types/baremetal/validation/platform.go
Add the baremetal host BMC fields to the AgentHosts asset. Detect changes to these fields when generating agent-cluster-install and include the BMC fields and the provisioning network configuration in the install-config override.
Note that changes are needed to assisted-service to add these fields to the installconfig override. Changes are also needed to dev-scripts for testing.
These are the additional patches needed for testing:
assisted-service - https://github.com/openshift/assisted-service/pull/5675 (merged)
dev-scripts - https://github.com/openshift-metal3/dev-scripts/pull/1601
=> AGENT-739: Support for install-config baremetal host BMC fields

pkg/types/validation/installconfig.go, pkg/types/validation/installconfig_test.go
Currently for cluster-managed load balancer we have a set of validations ensuring that API and Ingress VIP are placed in a correct subnet as well as they do not overlap.
For user-managed load balancer those validations are too strong as customers may have external load balancers placed outside of networks where cluster nodes live. Similarly, they may reuse the same IP for API and Ingress VIP, and distribute traffic via other means (e.g. using the port for the connection).
With this PR we are softening the validations if the configuration used is indicating that external load balancer is used.
Closes: OCPBUGS-23140
Closes: OCPBUGS-23305
=> OCPBUGS-23140, OCPBUGS-23305: Soften VIP validations for external load-balancer

data/data/nutanix/bootstrap/main.tf, data/data/nutanix/cluster/main.tf, data/data/nutanix/variables-nutanix.tf, pkg/tfvars/nutanix/nutanix.go
[SPLAT-1272](https://issues.redhat.com//browse/SPLAT-1272): Modify the terraform variables to support Nutanix Failure Domains
For terraform to create the control-plane node VMs with different configurations from the Nutanix Failure Domains, the Nutanix terraform variables need to have the corresponding changes.
Related merged PRs:
https://github.com/openshift/installer/pull/7730
=> SPLAT-1272: Modify the terraform variables to support Nutanix Failure Domains

images/installer/Dockerfile.upi.ci
[CORS-3003](https://issues.redhat.com//browse/CORS-3003) CI implementation: Review and support the work from IBM to enable BYOK in OpenShift on IBM Cloud VPC
=> CORS-3003: [ibmcloud] add key-protect plugin in ibmcloud cli

images/installer-altinfra/Dockerfile.ci
Enable building CAPI providers & dependencies by default in the `installer-altinfra` image.
https://github.com/openshift/release/pull/46602 is enabling a CAPI variant job. 
It seems we should hold off on enabling CAPI builds until we get terraform builds under control in the `installer` image.
/cc @r4f4 
/cc @vincepri
=> CORS-2840: images/altinfra: enable CAPI builds

pkg/asset/installconfig/azure/client.go
When https://github.com/openshift/installer/pull/7778 replaced `errors.Wrap` by `fmt.Errorf` it introduced a bug when retrieving a marketplace image in the client interface because of their different behaviors. `errors.Wrap(err, ...)` returns `nil` when `err` is `nil` whereas `fmt.Errorf` always returns an error. Unfortunately this was not caught in the unit tests since the client calls are mocked.
This bug resulted in the following error:
```
ERROR failed to fetch Master Machines: failed to load asset "Install Config": failed to create install config: [controlPlane.platform.azure.osImage: Invalid value: azure.OSImage{Plan:"", Publisher:"redhat", Offer:"rh-ocp-worker", SKU:"rh-ocp-worker", Version:"413.92.2023101700"}: could not get marketplace image: %!w(<nil>), …
```
=> OCPBUGS-25191: ic: azure: fix retrieving marketplace image

data/data/bootstrap/files/usr/local/bin/bootstrap-pivot.sh.template, data/data/bootstrap/systemd/common/units/kubelet.service.template, data/data/bootstrap/systemd/common/units/release-image-pivot.service.template
OKD/FCOS uses FCOS as its bootimage, i.e. when booting cluster nodes the first time during installation. FCOS does not provide tools such as OpenShift Client (oc) or crio.service which Agent-based Installer uses at the rendezvous host, e.g. to launch the bootstrap control plane.
RHCOS and SCOS include these tools, but [FCOS has to pivot the root fs](https://github.com/openshift/installer/blob/master/data/data/bootstrap/files/usr/local/bin/bootstrap-pivot.sh.template) to [okd-machine-os](https://github.com/openshift/okd-machine-os) first in order to make those tools available.
Pivoting uses 'rpm-ostree rebase' but the rendezvous host is booted the first time the node boots from a FCOS Live ISO where the root fs and /sysroot are mounted read-only. Thus 'rpm-ostree rebase' fails and …
=> OCPBUGS-19303: Changed OKD/FCOS workaround to also support Agent-based Installer

images/installer-altinfra/Dockerfile.ci
This reverts commit 5fb7adccb0e98f00561175f0b981e842a11d8e1e, reversing changes made to cf958f1cc19dc51c1b6b1737dbc29a96618579a1.
It's breaking the release images because downloading binaries is not possible in brew.
=> no-jira: Revert "Merge pull request #7823 from patrickdillon/build-capi-altinfra"

images/installer/Dockerfile.upi.ci.rhel8
manually backport the change from https://github.com/openshift/installer/pull/7245 into 4.12, since there is no ibmcloud cli installed on 4.12 upi-installer image, so only update govc part
-  remove downloading 'govc' and replace with govc docker image, sync with change in Dockerfile.upi.ci https://github.com/openshift/installer/blob/release-4.12/images/installer/Dockerfile.upi.ci#L13
=> OCPBUGS-23379: images: update govc image in upi-installer

pkg/asset/ignition/bootstrap/common.go
This reverts commit ff2ed87a63c3cfe724a1107d2530b51abf2a8b49.
Not needed after all.
=> Revert "OCPBUGS-4038: bootstrap: Skip gatewayd units only on OKD agent-installer"

docs/user/openstack/install_upi.md
When following this guide using RHEL or older Fedora there is an issue with the openstack.cloud with latest version (2.0.0) as it will need openstacksdk in version 1.0 or higher, which is unavailable in mentioned Linux distribution.
=> OCPBUGS-24241: Pin openstack.cloud version.

data/data/ibmcloud/bootstrap/common.tf, data/data/ibmcloud/master/common.tf, data/data/ibmcloud/network/common.tf, data/data/ibmcloud/variables-ibmcloud.tf, pkg/asset/cluster/tfvars.go, pkg/destroy/bootstrap/bootstrap.go, pkg/tfvars/ibmcloud/ibmcloud.go, pkg/types/ibmcloud/platform.go
Set the IBM Cloud Terraform visibility mode based on whether
any ServiceEndpoints are suspected to be private (or direct for COS),
based on their URL's.
Related: https://issues.redhat.com/browse/OCPBUGS-24473
=> OCPBUGS-24473: IBMCloud: Set IBM TF visibility based on URLs

hack/build.sh, images/baremetal/Dockerfile.ci, images/installer-artifacts/Dockerfile.rhel, images/installer/Dockerfile.ci, images/installer/Dockerfile.upi.ci, images/libvirt/Dockerfile.ci, images/openstack/Dockerfile.ci
Look at the Golang module information from the binary to determine whether the providers need to be rebuilt. It'll be useful when we use an external container image for the providers.
=> CORS-2870: build: only rebuild terraform providers if needed

hack/build.sh
Initially we were using the provider's module version in the go.sum file to determine if a provider needed to be rebuilt. Since vsphereprivate is locally developed, not an imported module, it required special treatment. Now that we are using the `go.mod` git hash to check if a terraform provider needs to be rebuilt, we don't need to give vsphereprivate special treatment. Unfortunately, this implementation detail slipped through even though we changed the approach.
If we don't drop the workaround, the build script will think `vsphereprivate` always needs to be rebuilt since it's comparing values that will never match.
=> no-jira: build: drop vsphereprivate build workaround

pkg/asset/manifests/dns.go
When custom-dns is enabled, do not populate the Private and Public zones within the DNS manifest. This will indicate to the Ingress operator to not configure the cloud DNS.
=> CORS-2315: GCP: Skip populating Private/Public Zones within DNS manifest

upi/openstack/security-groups.yaml
This commit changes `ether_type` field to `ethertype` so it will not break on older ansible openstack collections.
Also, fixed condition for IPv6 block.
=> OCPBUGS-25132: Fixes for the OpensStack UPI playbooks.

pkg/asset/installconfig/aws/permissions.go
Since https://github.com/openshift/installer/pull/7510, IPI installs fail if the permission is missing:
```
level=error msg=Error: creating IAM Instance Profile (ci-op-4hw2rz1v-49c30-zt9vx-worker-profile): AccessDenied: User: arn:aws:iam::301721915996:user/ci-op-4hw2rz1v-49c30-minimal-perm is not authorized to perform: iam:TagInstanceProfile on resource: arn:aws:iam::301721915996:instance-profile/ci-op-4hw2rz1v-49c30-zt9vx-worker-profile because no identity-based policy allows the iam:TagInstanceProfile action
```
=> OCPBUGS-25440: ic: aws: add iam:TagInstanceProfile permission requirement

pkg/asset/installconfig/aws/availabilityzones.go, pkg/asset/installconfig/aws/basedomain.go, pkg/asset/installconfig/aws/instancetypes.go, pkg/asset/installconfig/aws/metadata.go, pkg/asset/installconfig/aws/permissions.go, pkg/asset/installconfig/aws/platform.go, pkg/asset/installconfig/aws/route53.go, pkg/asset/installconfig/aws/session.go, pkg/asset/installconfig/aws/subnet.go, pkg/asset/installconfig/aws/validation.go, pkg/asset/installconfig/aws/validation_test.go
Add precheck if node architecture and vm type are consistent for aws as it works on azure.
Also fixed some technical debt along the way:
* replaced deprecated k8s.io/util/pointer package
* replaced deprecated sets syntax
* replaced deprecated errors package usage
=> OCPBUGS-25600: aws: validate instance arch

data/data/manifests/bootkube/cvo-overrides.yaml.template
Prior to the change, the default channel is stable-4.14. The change bumps it to stable-4.16 on master.
```
warning: Cannot display available updates:
Reason: VersionNotFound
Message: Unable to retrieve available updates: currently reconciling cluster version 4.16.0-0.nightly-2024-01-03-193825 not found in the "stable-4.14" channel
Cluster version is 4.16.0-0.nightly-2024-01-03-193825
Upgradeable=False
Reason: MissingUpgradeableAnnotation
Message: Cluster operator cloud-credential should not be upgraded between minor versions: Upgradeable annotation cloudcredential.openshift.io/upgradeable-to on cloudcredential.operator.openshift.io/cluster object needs updating before upgrade. See Manually Creating IAM documentation for instructions on preparing a cluster for upgrade.
Upstream is unset, …
```
=> OCPBUGS-26048: Bump default channel to stable-4.16

docs/user/openstack/customization.md
The recommended minimal value for production cluster is 100 GB.
=> OSASINFRA-3280: OpenStack: clarify root volume size requirements

pkg/types/validation/installconfig.go, pkg/types/validation/installconfig_test.go
Add validation to the installer for CloudCredential capability in order to make it available only for baremetal installs or properly configured cloud credentials mode
=> OCPBUGS-24956: Add cloud credential capability validation

pkg/asset/installconfig/installconfig.go
This validation is performed in the ARO Resource Provider, before the Installer is called. We've had this duplicate validation fail intermittently, and so this PR disables it for ARO specifically.
=> ARO-4744: Do not run platform validation on ARO

data/data/manifests/bootkube/cvo-overrides.yaml.template
Prior to the change, the default channel is stable-4.14 on a 4.15 cluster. The change bumps it to stable-4.15.
=> OCPBUGS-26511: Bump default channel to 4.15

pkg/types/powervs/powervs_regions.go
More regions with Power Edge Router capabilities have come online. This patch adds them to the installer.
=> MULTIARCH-4072: Power VS: Add eu-de-1, eu-de-2, sao04, and wdc07 as supported zones

pkg/terraform/stages/gcp/stages.go, pkg/terraform/stages/ignition.go
** After the internal and external load balancer ip addresses are output from terraform, add this data to the cluster infrastructure manifest. This will ensure that the data is present in the cluster.
[CORS-3190](https://issues.redhat.com//browse/CORS-3190): Spike to generalize the addition of load balancer information to platform status fields in the infrastructure CR.
=> CORS-3190: GCP: Add load balancer info to cluster infra

cmd/openshift-install/testdata/agent/image/configurations/baremetal_host_bmc_config.txt, pkg/asset/agent/manifests/agentclusterinstall.go, pkg/asset/agent/manifests/agentclusterinstall_test.go, pkg/asset/agent/manifests/util_test.go
As the appliance e2e [jobs](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-appliance-master-e2e-compact-ipv4-static) are still deploying OCP 4.14, in which the singular variant of APIVIP/IngressVIP is required, we still need to set these properties in AgentClusterInstall.
We can remove this again later on when the appliance would support newer OCP version.
=> OCPBUGS-26399: Support singular VIP in ACI for BareMetal

pkg/tfvars/baremetal/baremetal.go
Using bmh.Spec.Architecture will be more future proof
=> METAL-829: Set node cpu_arch from bmh

pkg/asset/agent/installconfig_test.go, pkg/types/validation/installconfig.go, pkg/types/validation/installconfig_test.go
The openshift-sdn CNI plug-in will no longer be an install-time option for newly installed 4.15+ clusters across installation options. Note that customer clusters currently using openshift-sdn that upgrade to 4.15 or 4.16 with openshift-sdn will remain fully supported.
=> CORS-2950: Remove openshift-sdn as an install-time option

pkg/asset/cluster/tfvars.go, pkg/tfvars/baremetal/baremetal.go, pkg/tfvars/baremetal/baremetal_test.go
Currently, in v4-primary dual-stack deployments, Ironic always uses its
v4 server URL as the image URL to pass to BMCs. If a BMC only has IPv6
networking, it is not going to work. This change checks the IP family
of the BMC and provides the correct external_http_url.
=> OCPBUGS-25996: baremetal: correct external_http_url for v6-only BMCs

data/data/bootstrap/files/usr/local/bin/installer-gather.sh
After the recent refactoring, the baremetal services log via journald,
not through the podman logging. Collect these logs.
Omitting ironic-inspector on purpose since it's going to be removed.
=> OCPBUGS-27092: baremetal: gather all recently refactored services

data/data/agent/files/usr/local/bin/agent-gather
Redact the platform passwords stored in agent-cluster-install when included in the agent-gather output.
=> OCPBUGS-26434: Redact platform passwords in agent-gather output

pkg/asset/agent/image/agentimage.go
In the previous implementation ABI regenerated the ISO image using the content found in a temporary folder. Some of these files had a `.json` extension, and they were stored with that extension, breaking the compatibility with `coreos-installer` commands, in particular the `kargs` one. The issue was that the `coreos-installer` was looking for a [3-chars extension kargs file](https://github.com/coreos/coreos-installer/blob/bc55e5e43e42a0a8cc1192c1f0ae8ac30b7abc8b/src/live/embed.rs#L45), but that file wasn't found (note: also `FEATURES.JSO` and `IGNINFO.JSO` are looked for using 3-chars ext).
This patch normalizes the content of the temp folder used to reassemble the agent ISO so that the files will be compliant to the 3-chars extension length
=> OCPBUGS-14257: normalize ISO files extensions to three chars

pkg/types/validation/installconfig.go, pkg/types/validation/installconfig_test.go
On a baremetal platform, when baselineCapabilitySet is set to None in install-config, the additionalCapabilities must contain 'baremetal'.
=> OCPBUGS-25835: Validate baremetal capability is set for baremetal platform

images/installer-altinfra/Dockerfile.ci
Allows the OPENSHIFT_INSTALL_CLUSTER_API ARG to be set at a build time. Enabling this as an ARG in the Dockerfile will allow this ARG to be set in CI--but not by ART. Setting OPENSHIFT_INSTALL_CLUSTER_API will currently break ART/OSBS because etcd and kube-apiserver dependencies are being obtained over the network, which is possible in CI but not in ART.
Enabling CI will allow teams to progress while we determine how to obtain the etcd and kube-apiserver dependencies. Handling these dependencies is tracked in:
https://issues.redhat.com/browse/CORS-3191
=> no-jira:  images/altinfra: allow CAPI ARG

docs/user/azure/tested_instance_types_x86_64.md
Based on Azure doc [1], NCv2 series Azure virtual machines (VMs) are retired on September 6, 2023.
Removed it from doc tested_instance_types_x86_64.md on azure platform.
[1] https://learn.microsoft.com/en-us/azure/virtual-machines/ncv2-series
=> OCPBUGS-27192: remove retired serial NCv2 from azure tested instance type list on x86

pkg/asset/cluster/tfvars.go, pkg/tfvars/baremetal/baremetal.go, pkg/tfvars/baremetal/baremetal_test.go
Currently, in v4-primary dual-stack deployments, Ironic always uses its v4 server URL as the image URL to pass to BMCs. If a BMC only has IPv6 networking, it is not going to work. This change checks the IP family of the BMC and provides the correct external_http_url.
=> OCPBUGS-27241: baremetal: correct external_http_url for v6-only BMCs

pkg/asset/machines/master.go, pkg/asset/machines/worker.go, pkg/asset/rhcos/image.go, pkg/destroy/powervs/powervs.go, pkg/tfvars/powervs/powervs.go, pkg/types/powervs/powervs_regions.go
In PowerVS, a region might not support COS objects.  Therefore, introduce a mapping.
Also, in making the Madrid region deployable, a number of bugs were found besides the big one of needing to use a different COS region.
=> OCPBUGS-27788: PowerVS: COS region configurable

data/data/azure/variables-azure.tf, data/data/azure/vnet/main.tf, pkg/asset/cluster/azure/azure.go, pkg/destroy/azure/azure.go, pkg/tfvars/azure/azure.go, pkg/types/azure/metadata.go
When Hive runs the Installer destroy code, they don't always have all
the cluster metadata information the destroyer needs. Adding new fields
to the metadata is also a very painful process for them.
This PR adds some cluster metadata information to the cluster resource
group as tags, so that it can be discovered during destroy even if
azure-specific information is missing from the `metadata.json` file.
For now we are saving "region", "base domain resource group name", and
"network resource group name" but the mechanism will be useful if we
wish to add more data in the future without impacting Hive.
=> no-jira: azure: add metadata info to resource group tags

pkg/asset/agent/image/ignition_test.go
It looks like the error message for an invalid IP is slightly different between `nmstatectl` `2.2.23` (used in base rhel9) and `2.2.12` (used in base rhel8)
=> NO-ISSUE: test fix to support slightly different nmstate error messages

pkg/asset/cluster/cluster.go, pkg/asset/cluster/metadata.go, pkg/asset/cluster/metadata/metadata.go, pkg/asset/cluster/tfvars/tfvars.go, pkg/asset/machines/clusterapi.go, pkg/asset/manifests/capiutils/manifest.go, pkg/asset/manifests/clusterapi/cluster.go, pkg/asset/targets/targets.go, pkg/destroy/bootstrap/bootstrap.go, pkg/destroy/destroyer.go, pkg/gather/gather.go, pkg/infrastructure/aws/aws.go, pkg/infrastructure/clusterapi/clusterapi.go, pkg/infrastructure/clusterapi/helpers.go, pkg/infrastructure/clusterapi/types.go, pkg/infrastructure/provider.go, pkg/terraform/terraform.go
This PR:
- moves the CAPI implementation behind the infrastructure provider interface
- adds an interface/platform for various cloud providers to implement
Moving the CAPI implementation behind the infrastructure provider platform encapsulates CAPI implementation details. It also allows [pkg/infrastructure/platform](https://github.com/openshift/installer/tree/master/pkg/infrastructure/platform) to be the canonical source of truth of which infrastructure provider a cloud platform is using.
The `CAPIInfraHelper` interface provides a simple implementation for cloud platforms to interact with the CAPI provisioning pattern. This is intended to be a baseline interface that can be build upon and extended. It is not intended to be complete, but intends to be flexible enough to allow handling …
=> CORS-3139:  Move CAPI behind infrastructure provider interface

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.13 boot image metadata. Issues resolved in this bootimage are:
OCPBUGS-23501 - Failed to mount gcp volume with "failed to find and re-link disk"
OCPBUGS-23907 - No way to enable FIPS in RHCOS Live ISO
```
--distro rhcos --no-signatures --name 4.13-9.2                    \
x86_64=413.92.202401100947-0                                      \
aarch64=413.92.202401100947-0                                     \
s390x=413.92.202401100947-0                                       \
ppc64le=413.92.202401100947-0
```
=> OCPBUGS-23499: update RHCOS 4.13 bootimage metadata to 413.92.202401100947-0

docs/user/azure/tested_instance_types_x86_64.md
Doc updates:
add new families which are verified on 4.15 nightly build:
- standardHBv4Family
- standardMDSMediumMemoryv3Family
- standardMSMediumMemoryv3Family
=> OCPBUGS-28705: [azure] update tested x86 instance type on 4.15

.ci-operator.yaml, .golangci.yaml, go.mod, go.sum, hack/build.sh, hack/go-fmt.sh, hack/go-genmock.sh, hack/go-sec.sh, hack/go-test.sh, hack/go-vet.sh, hack/verify-codegen.sh, hack/verify-vendor.sh, images/baremetal/Dockerfile.ci, images/infrastructure-providers/Dockerfile, images/installer-altinfra/Dockerfile.ci, images/installer-artifacts/Dockerfile.rhel, images/installer/Dockerfile.ci, images/installer/Dockerfile.upi.ci, images/libvirt/Dockerfile.ci, images/openstack/Dockerfile.ci, terraform/Makefile
Similar to terraform and altinfra images, we want to move all remaining installer images to golang 1.21
Downstream config change https://github.com/openshift-eng/ocp-build-data/pull/4192
=> OCPBUGS-27263: Bump golang 1.21

pkg/asset/cluster/tfvars.go, pkg/tfvars/baremetal/baremetal.go, pkg/tfvars/baremetal/baremetal_test.go
Currently, in v4-primary dual-stack deployments, Ironic always uses its
v4 server URL as the image URL to pass to BMCs. If a BMC only has IPv6
networking, it is not going to work. This change checks the IP family
of the BMC and provides the correct external_http_url.
Differences in the backport:
* getParsedURL copied from baremetal-operator to avoid catching up with
a long history of changes in baremetal-operator before this function
became public.
(cherry picked from commit 99c460281991b7814fa412735fee406571211316)
=> OCPBUGS-27453: baremetal: correct external_http_url for v6-only BMCs

docs/user/azure/tested_instance_types_aarch64.md
Docs update:
add new Arm64 families which are verified on 4.15 nightly build:
- standardBpsv2Family
=> OCPBUGS-28708: update tested Azure Arm64 instance type on 4.15

pkg/asset/cluster/gcp/gcp.go
** The cluster domain was added to the metadata previously to find private zones that were not created by the installer. The records were added to a private zone in this domain. The problem occurs when clusters with the same name are used for installation. The infra ID is not used during the zone creation or zone lookup. The same zone (with the same domain) is assumed to be the one the installer (destroyer) is looking for. The fix includes skipping the addition of the domain to the metadata so that it is not used for comparison on destroy.
=> OCPBUGS-27156: GCP Destroy cleanup correct zones/records

cmd/node-joiner/main.go, cmd/openshift-install/create.go, pkg/asset/store/assetsfetcher.go, pkg/nodejoiner/addnodes.go, pkg/nodejoiner/monitoraddnodes.go
This patch introduces the node-joiner tool main with (empty) commands entry points. Since the commands will reuse the existing assets, a new `AssetsFetcher` interface and struct has been introduced to allow sharing the same asset fetcher code already used by the `create` and `agent` commands in the default installer.
=> AGENT-848: add node-joiner cli tool main

pkg/destroy/gcp/gcp.go
The GCP CAPI provider uses different label for instances than MAPI.
This PR adds the CAPG label to labels we look for when uninstalling.
=> OCPBUGS-2135: Include CAPG objects in uninstall filter

data/data/powervs/cluster/dns/dns.tf, data/data/powervs/cluster/dns/outputs.tf
`primary_ipv4_address` is deprecated in favor of `primary_ip[*].address`. Replace it with the new attribute.
=> CORS-3242: PowerVS: Replace deprecated primary_ipv4_address with primary_ip list item

pkg/infrastructure/clusterapi/clusterapi.go, pkg/infrastructure/clusterapi/types.go
OpenStack in particular needs:
* to upload the RHCOS image to the OpenStack image registry
* to change how security groups are set, depending on whether Control plane nodes are schedulable
Both operations happen in the PreProvision hook in the case of OpenStack, because CAPO is not (yet) capable of performing them.
Alternative solution to https://github.com/openshift/installer/pull/7949
=> OSASINFRA-3371: Pass rhcosImage and manifests to the PreProvision hook

pkg/asset/agent/image/agentimage.go
Avoid renaming `boot.catalog` for arm64 ISO image due [disk creation requirements](https://github.com/openshift/installer/blob/1edc5d439a7a29c296b3bd3d54e010b697c94c17/vendor/github.com/openshift/assisted-image-service/pkg/isoeditor/isoutil.go#L155)
=> OCPBUGS-28827: do not rename boot.catalog for arm64 iso

pkg/destroy/ibmcloud/disk.go
Handle cases when IBM Cloud disk deletion returns an error, without any response data.
=> OCPBUGS-20085: IBMCloud: Handle disk delete errors

pkg/asset/machines/vsphere/machines.go
[OCPBUGS-29114](https://issues.redhat.com/browse/OCPBUGS-29114)
- Fixed logic to set AddressesFromPools and Nameservers only if AddressesFromPools > 0.  Else Nameservers will get set when hosts > 0 but installer is not using AdressesFromPools.
=> OCPBUGS-29114: Fixed control plane machine set handling of static IPs when AddressesFromPools is not in use.

cmd/openshift-install/agent_internal_integration_test.go, cmd/openshift-install/testdata/agent/configimage/manifests/default_manifests.txt, cmd/openshift-install/testdata/agent/image/manifests/default_manifests.txt, cmd/openshift-install/testdata/agent/unconfigured-ignition/configurations/from-ztp-manifests.txt, cmd/openshift-install/testdata/agent/unconfigured-ignition/manifests/default_manifests.txt, cmd/openshift-install/testdata/agent/unconfigured-ignition/validations/missing-cluster-image-set-allowed.txt, cmd/openshift-install/testdata/agent/unconfigured-ignition/validations/missing-infraenv.txt, cmd/openshift-install/testdata/agent/unconfigured-ignition/validations/missing-pull-secret.txt
This patch modifies the integration tests custom comparison functions to allow env vars substitutions into the expected file (in a similar fashion to the standard testscript [cmpenv](https://pkg.go.dev/github.com/rogpeppe/go-internal/testscript) function).
A new custom function `expandFile` has been added to allow en var replacement for the actual files.
In addition, it adds the `RELEASE_IMAGE` env var to the integration tests execution environment referring the current release image pullspec. This will allow to avoid hard-coding the release image pullspec in the integration tests, which is causing a test failure every time the default release image is updated.
Relates to https://github.com/openshift/installer/pull/7874
=> NO-ISSUE: integrationt tests support for env vars substitution

pkg/asset/installconfig/openstack/validation/cloudinfo.go
When the controlPlanePort has no network defined, we attempt to validate the network using the empty name and id, this results in multiple networks found, which breaks the pre-flight validation resulting in it being skipped. This commit fixed the issue, by only running validation on that field if it has content defined.
=> Bug OCPBUGS-29198: OpenStack: fix controlPlanePort validation

pkg/destroy/powervs/cloud-sshkey.go, pkg/destroy/powervs/cloud-transit-gateways.go, pkg/destroy/powervs/publicgateway.go
Some destroy functions for PowerVS objects had an incorrect method to get the next starting point for continuing searching for objects that match the name.
=> OCPBUGS-29425: PowerVS Fix next start search

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.16 boot image metadata. Notable fixes in the boot image for:
fix for unexpected Azure IMDS status codes
```
x86_64=416.94.202402130130-0                                      \
aarch64=416.94.202402130130-0                                     \
s390x=416.94.202402130130-0                                       \
ppc64le=416.94.202402130130-0
```
=> OCPBUGS-29441: update RHCOS 4.16 bootimage metadata to 416.94.202402130130-0

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.15 boot image metadata. Notable fixes in the boot image for:
- fix for unexpected Azure IMDS status codes
- Addition of ca-west-1 AMIs
```
x86_64=415.92.202402130021-0                                      \
aarch64=415.92.202402130021-0                                     \
s390x=415.92.202402130021-0                                       \
ppc64le=415.92.202402130021-0
```
=> OCPBUGS-29442: update RHCOS 4.15 bootimage metadata to 415.92.202402130021-0

pkg/asset/machines/aws/machines.go
Adds filters to the machine api machinesets so they will recognize CAPI-created security groups and subnets. Adds these filters in addition to the Terraform-specific filters, which should be subsequently removed.
=> CORS-2890: aws/machines: add CAPI sg, subnet filters

pkg/asset/manifests/clusterapi/cluster.go, pkg/asset/manifests/gcp/cluster.go
The initial GCP cluster manifest is created when the CAPI Install feature gate is added. The initial state of the cluster manifest is relatively empty, and most of the information will be added to the GCP machine manifest(s).
=> CORS-3213: Create the GCP cluster manifest

pkg/asset/machines/gcp/machines.go
The JSON object is not set when the credentials are loaded from the cli, resulting in an unhelpful message about "unexpected end of JSON input". Let's provide a better error message in that case.
=> OCPBUGS-28590: gcp: better error msg when service accnt missing

pkg/asset/releaseimage/default.go
Updating the release image to the latest stable version 4.16.
=> CORS-3185: update default release image

pkg/infrastructure/aws/clusterapi/aws.go, pkg/infrastructure/platform/platform.go, pkg/infrastructure/platform/platform_altinfra.go
Adds the initial, empty provider for the AWS CAPI install process. This should allow basic running of the CAPI provider and a foundation for building the rest of the supporting infrastructure provisioning. 
Right now this will panic because we're missing the manifests and rhcos image from the `parents` passed to the CAPI provider. Several PRs floating around have fixes. #8011 has the fix and looks ready to merge soon.
=> CORS-2890: pkg/infrastructure/aws: add initial CAPI provider

pkg/destroy/powervs/powervs.go, pkg/destroy/powervs/serviceinstance.go
When the IPI installer creates a service instance for the user, PowerVS will now have the type as composite_instance rather than service_instance.  Fixup delete cluster to account for this change.
=> OCPBUGS-29584: PowerVS: handle composite_instance

pkg/asset/installconfig/vsphere/mock/vsphere_sim.go, pkg/types/vsphere/conversion/installconfig.go, pkg/types/vsphere/conversion/installconfig_test.go
In 4.12 and prior versions of the installer
allowed non-pathed names of vCenter objects.
In 4.13+ that is no longer allowed and absolute full paths are required.
This change is causing issues with ACM/Hive. The
only resolution (not ideal) is to connect
to vCenter and determine from potentially only the objects name to determine the absolute full path.
=> OCPBUGS-22410: vsphere-fix convert if only provided name

pkg/asset/installconfig/powervs/client.go
Due to a change in how Power VS workspaces are cataloged, new service instances are not picked up by the installer.  This patch expands the filter to include the new catalog name.
=> OCPBUGS-29587: Power VS: Fix service instance list

pkg/infrastructure/gcp/clusterapi/clusterapi.go, pkg/infrastructure/gcp/clusterapi/dns.go, pkg/infrastructure/gcp/clusterapi/gcp.go, pkg/infrastructure/gcp/clusterapi/labels.go, pkg/infrastructure/gcp/clusterapi/network.go, pkg/infrastructure/gcp/clusterapi/operation.go, pkg/infrastructure/gcp/clusterapi/service.go
** Create the private DNS zone.
** Create the private dns records in the zone.
** Create the public dns records when the install is set to public/external.
** Create the private load balancer so that the ip address can be used for creating dns records.
** Add operation tracker to ensure that we wait for an operation to conclude before accessing the resource.
** Add function to merge labels.
[CORS-3259](https://issues.redhat.com//browse/CORS-3259)
[CORS-3253](https://issues.redhat.com//browse/CORS-3253)
=> CORS-3259: GCP: Create DNS records and internal load balancer for CAPG Install

data/data/openstack/masters/private-network.tf
When the cluster is created with an external load-balancer, no api or ingress VIP Ports exists, but for dual-stack installations we are expecting those Ports to pre-exists, resulting in failure to add security groups to those Ports. This commit fixes the issue by ensuring to only attach the security group when no external lb is configured and dual-stack is used.
=> Bug OCPBUGS-29084: OpenStack: Fix dualstack with external load-balancer

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.14 boot image metadata. Issues fixed in this bootimage are:
OCPBUGS-29252 - Backport fix for unexpected Azure IMDS status codes
```
x86_64=414.92.202402130420-0                                     \
aarch64=414.92.202402130420-0                                    \
s390x=414.92.202402130420-0                                      \
ppc64le=414.92.202402130420-0
```
=> OCPBUGS-29626: update RHCOS 4.14 bootimage metadata to 414.92.202402130420-0

cmd/openshift-install/create.go
We've noticed a pattern where SNO install rate is struggling to get above 90% and hovers around 85% for 4.15 and 80% on 4.16. This seems to be caused by a race condition where bootstrap finishes but CEO doesn't have enough time to remove the bootstrap etcd member from the pool thus causing etcd to fail to come up since it's looking for the member and since we're in a single node environment that cascades when the API Server can no longer connect to etcd, it reaches an unrecoverable state. 
This PR attempts to resolve that by only declaring we are done when the Bootstrap Member is removed, this signal is better to indicate a stable SNO deployment
=> OCPBUGS-29429: feat: add check for SNO bootstrap condition

pkg/clusterapi/system.go
VSPHERE_USERNAME and VSPHERE_PASSWORD environmental
variables are not required.
`pkg/asset/manifests/vsphere/cluster.go`
is used instead of authentication.
=> SPLAT-1462: capv - Remove unneeded auth env vars

pkg/asset/cluster/tfvars.go, pkg/tfvars/baremetal/baremetal.go, pkg/tfvars/baremetal/baremetal_test.go
Currently, in v4-primary dual-stack deployments, Ironic always uses its
v4 server URL as the image URL to pass to BMCs. If a BMC only has IPv6
networking, it is not going to work. This change checks the IP family
of the BMC and provides the correct external_http_url.
Differences in the backport:
* getParsedURL copied from baremetal-operator to avoid catching up with
a long history of changes in baremetal-operator before this function
became public.
* port 80 was used instead of 6180 before 4.13.
(cherry picked from commit 99c460281991b7814fa412735fee406571211316)
=> OCPBUGS-27454: baremetal: correct external_http_url for v6-only BMCs

pkg/asset/machines/vsphere/capimachines.go
This PR includes two additional extra configs to capv machines:
- guestinfo.domain
- stealclock.enable
These options were set in terraform and need to be enabled for capv-based machines.
=> SPLAT-1465: capv - add additional extra configs

images/libvirt/Dockerfile.ci
For multi-architecture compute deployments for s390x on libvirt, we need to extract cluster state and correct assets for spinning up nodes on a second architecture via oc, then spin up nodes with libvirt client. oc can be helpful for this purpose.
This is analogous to the UPI installer image (images/installer/Dockerfile.upi.ci#L14,L20)
=> no-jira: images: libvirt: add oc to libvirt CI image

data/data/aws/bootstrap/main.tf, data/data/aws/cluster/main.tf, data/data/aws/cluster/vpc/master-elb.tf, data/data/aws/cluster/vpc/variables.tf, data/data/aws/cluster/vpc/vpc-public.tf, data/data/aws/variables-aws.tf, data/data/install.openshift.io_installconfigs.yaml, docs/user/aws/custom_public_ipv4.md, pkg/asset/cluster/tfvars/tfvars.go, pkg/asset/installconfig/aws/ec2.go, pkg/asset/installconfig/aws/validation.go, pkg/asset/installconfig/aws/validation_test.go, pkg/explain/printer_test.go, pkg/tfvars/aws/aws.go, pkg/types/aws/platform.go
Introduce support of AWS BYO IPv4 (Public IPv4 Pool) when creating clusters with publish strategy `External`.
The Public IPv4 Pool is an alternative for customers to mitigate the new AWS charges for Public IPv4 (Elastic IPs) ,provided by Amazon, when the customer has the custom IPv4 pools managed by AWS.
Refs:
- https://issues.redhat.com/browse/SPLAT-1434
- https://issues.redhat.com/browse/OCPSTRAT-1154
- https://github.com/openshift/release/pull/48467
=> SPLAT-1434: aws: add support of BYO public ipv4 pool

pkg/destroy/powervs/powervs.go
A user noticed on delete cluster that the IPI generated service instance was not cleaned up.  Add more debugging statements to find out why.
=> OCPBUGS-29895: PowerVS: Add debugging to ServiceInstanceNameToGUID

pkg/asset/machines/vsphere/capimachines.go
We currently do not support linked-clones and
probably shouldn't only in very certain cases (test/dev). At this time statically defining `FullClone`.
=> SPLAT-1459: capv machines only full clone

pkg/infrastructure/platform/platform.go, pkg/infrastructure/platform/platform_altinfra.go, pkg/infrastructure/powervs/clusterapi/powervs.go
Adds the initial, empty provider for the PowerVS CAPI install process. This should allow basic running of the CAPI provider and a foundation for building the rest of the supporting infrastructure provisioning.
=> MULTIARCH-4158: pkg/infrastructure/powervs: add initial CAPI provider

pkg/clusterapi/system.go
=> CORS-3273: capi system: don't log env vars

pkg/asset/cluster/tfvars/tfvars.go, pkg/asset/machines/master.go, pkg/asset/machines/vsphere/capimachines.go, pkg/asset/machines/vsphere/machines.go, pkg/asset/machines/vsphere/machines_test.go, pkg/asset/machines/vsphere/machinesets.go, pkg/asset/machines/worker.go, pkg/tfvars/vsphere/vsphere.go
[SPLAT-1173](https://issues.redhat.com//browse/SPLAT-1173)
- Enhance installer to generate IPAddress and IPAddressClaim for each IP being associated to device 0
- Enhance terraform logic to leverage the IPAddress object as the source-of-truth for generating the kargs for static IP of each master machine.
- https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/273
- The fix in the [CPMSO](https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/273) is required due to CPMSO not knowing how to handle AddressesFromPools in its comparisons.
=> SPLAT-1173: Enhance vSphere Installer to use IPAddressClaims for static IP

pkg/infrastructure/gcp/clusterapi/dns.go, pkg/infrastructure/gcp/clusterapi/service.go
Adds service-account authentication support in the CAPI infrastructure packages, which prior to this utilize only default application credentials.
=> CORS-3259: GCP CAPI Infra: auth with service account

go.mod, pkg/asset/machines/azure/azuremachines.go, pkg/asset/machines/clusterapi.go, pkg/asset/manifests/azure/cluster.go, pkg/infrastructure/azure/azure.go, pkg/infrastructure/platform/platform.go, pkg/infrastructure/platform/platform_altinfra.go, vendor/modules.txt
Creating machine manifests for azure CAPI implementation.
=> CORS-3251: Create capz machine manifests

pkg/types/gcp/validation/platform.go
Add the africa-south1 GCP region that was not previously listed as a supported region for the installer to use.
=> CORS-3274: GCP: add africa-south1 region to the survey as supported region

pkg/types/validation/installconfig.go, pkg/types/validation/installconfig_test.go
The error message
```
time="2024-03-01T14:37:25Z" level=error msg="failed to fetch Master Machines: failed to load asset \"Install Config\": failed to create install config: invalid \"install-config.yaml\" file: networking.networkType: Invalid value: \"OpenShiftSDN\": networkType OpenShiftSDN is deprecated, please use OVNKubernetes"
```
is misleading, as "deprecated" means "we'll still do it, but we'll grumble about it". Fix.
OCPBUGS-30135
=> OCPBUGS-30135: fix "OpenShiftSDN deprecated" error message

pkg/asset/manifests/gcp/cluster.go
Set the AutoCreateSubnetworks to `false` always (default is `true`) as we don't want to auto create these subnets even when doing a shared VPC install.
=> OCPBUGS-30057: Don't auto create subnets for CAPG

data/data/coreos/rhcos.json
These changes will update the RHCOS 4.13 boot image metadata. Issues resolved in this bootimage are:
OCPBUGS-29252 - Backport fix for unexpected Azure IMDS status codes
```
--distro rhcos --no-signatures --name 4.13-9.2                    \
x86_64=413.92.202402131523-0                                      \
aarch64=413.92.202402131523-0                                     \
s390x=413.92.202402131523-0                                       \
ppc64le=413.92.202402131523-0
```
=> OCPBUGS-29627: update RHCOS 4.13 bootimage metadata to 413.92.202402131523-0

pkg/asset/machines/gcp/gcpmachines.go
** The default bootstrap machine IP is set to private. When the publish strategy is set to external this value should be True to indicate a public ip address.
=> OCPBUGS-30058: GCP: The CAPG bootstrap machine IP should be set according to the publish strategy

images/libvirt/Dockerfile.ci
Blocks: https://github.com/openshift/release/pull/49036
=> MULTIARCH-4159: Updated libvirt installer to include multi-arch yq and symlink for backwards compatibility

pkg/infrastructure/vsphere/clusterapi/import.go
[SPLAT-1468](https://issues.redhat.com/browse/SPLAT-1468)
- Updated vSphere CAPI installer to output each OVA upload to provide feedback to user that upload is in progress
=> SPLAT-1468: Added log message for import vsphere ova progress during CAPI install.

cmd/openshift-install/testdata/agent/image/configurations/vsphere_with-credentials.txt, pkg/asset/agent/installconfig_test.go, pkg/types/vsphere/defaults/platform.go, pkg/types/vsphere/defaults/platform_test.go
[SPLAT-1460](https://issues.redhat.com/browse/SPLAT-1460)
- Modified default ResourcePool definition to prevent double "/" in path
=> SPLAT-1460: Make vSphere default ResourcePool formatting not contain double slash.
