pkg/infrastructure/ibmcloud/clusterapi/clusterapi.go
pkg/infrastructure/platform/platform.go
pkg/infrastructure/platform/platform_altinfra.go

Adds the initial provider and infrastructure framework for the IBM Cloud CAPI install process.
Related: https://issues.redhat.com/browse/CORS-3281

CORS-3281: IBMCloud: initial CAPI infrastructure

---

upi/aws/cloudformation/06_cluster_worker_node.yaml

The description should say "worker" not "master".

OCPBUGS-29388: upi: aws: fix typo in worker templates

---

data/data/bootstrap/baremetal/files/usr/local/bin/master-bmh-update.sh
pkg/asset/machines/baremetal/hosts.go
pkg/asset/machines/baremetal/hosts_test.go

Let's use the new k8s upstream name.
This is a follow-up to #7649

METAL-871: baremetal: bootstrap: rename master label

---

pkg/asset/machines/aws/machines.go

Fixes the comment to correctly identify that the legacy terraform subnet filter does NOT include the 'subnet' string.

no-jira:  machines/aws: fix subnet filter comment

---

pkg/asset/installconfig/powervs/client.go
pkg/asset/installconfig/powervs/metadata.go

With #8025 merged, enabling deploy/destroy by a Service ID turns out to be rather simple by just addressing the below error;
```
FATAL failed to fetch Terraform Variables: failed to fetch dependency of "Terraform Variables": failed to generate asset "Platform Provisioning Check": failed to list resourceGroups: Can not get resource groups without account id in parameter by service id token.
```

OCPBUGS-30641: Enable deploy by Service ID on PowerVS

---

data/data/bootstrap/files/usr/local/bin/kubelet.sh.template
docs/user/customization.md

In https://github.com/openshift/os/pull/1449 we removed hyperkube from RHCOS which was just a shell script that called kubelet. Chase that change in bootstrap assets. For some reason only s390x appears to have been broken by the removal where they're seeing bootstrap failing, maybe they do some special automation to ensure that the bootstrap node is running the latest RHCOS? I suspect without this change the next boot image bump will fail.

OCPBUGS-30547,OCPBUGS-29437: Run kubelet directly

---

pkg/asset/machines/gcp/gcpmachines.go
pkg/asset/machines/gcp/gcpmachines_test.go
pkg/infrastructure/gcp/clusterapi/clusterapi.go
pkg/infrastructure/gcp/clusterapi/iam.go

Create ServiceAccounts for masters and workers and add the corresponding roles. Associate the ServiceAccount with the master machines when they are created, using either this created account, or the derived serviceAccount in an Shared VPC installation.

CORS-3257: Create GCP ServiceAccounts and assign to machines

---

data/data/coreos/rhcos.json

These changes will update the RHCOS 4.16 boot image metadata.
```
x86_64=416.94.202403071059-0                                      \
aarch64=416.94.202403071059-0                                     \
s390x=416.94.202403071059-0                                       \
ppc64le=416.94.202403071059-0
```

OCPBUGS-30600: update RHCOS 4.16 bootimage metadata to 416.94.202403071059-0

---

cmd/openshift-install/testdata/agent/image/validations/compact_invalid_controlPlane_replicas.txt
pkg/asset/agent/installconfig.go
pkg/asset/agent/installconfig_test.go

The number of control plane replicas defined in install-config.yaml (or agent-cluster-install.yaml) are validated to check if they are set to 3, or 1 in the case of SNO. If set to another value the "create image"(and other similar ) command fails.

OCPBUGS-25462: Validate control plane replicas

---

data/data/powervs/cluster/iaas/iaas.tf
data/data/powervs/cluster/iaas/outputs.tf
data/data/powervs/variables-powervs.tf

The terraform used for waiting after a workspace is created was not preventing the DHCP service from getting created. This was the intention of the sleep and should be fixed.

OCPBUGS-30836: Power VS: Fix wait_for_workspace

---

pkg/types/gcp/validation/platform.go

Add the me-central2 GCP region that was not previously listed as a supported region for the installer to use.

CORS-3303: GCP: Add me-central2 (Dammam, Saudi Arabia, Middle East) region to the survey as supported region

---

pkg/types/nutanix/validation/platform.go
pkg/types/nutanix/validation/platform_test.go

As part of https://issues.redhat.com/browse/OPNET-305 we are promoting External Load Balancer to GA. This requires installer to soften validations so that the feature is not any more limited only to TechPreview clusters.
Contributes-to: [OPNET-476](https://issues.redhat.com//browse/OPNET-476)

OPNET-476: GA Load balancer feature for Nutanix

---

data/data/coreos/rhcos.json

These changes will update the RHCOS 4.15 boot image metadata.
```
x86_64=415.92.202402201450-0                                      \
aarch64=415.92.202402201450-0                                     \
s390x=415.92.202402201450-0                                       \
ppc64le=415.92.202402201450-0
```

OCPBUGS-30601: update RHCOS 4.15 bootimage metadata to 415.92.202402201450-0

---

pkg/types/baremetal/validation/platform.go
pkg/types/baremetal/validation/platform_test.go
pkg/types/vsphere/validation/platform.go
pkg/types/vsphere/validation/platform_test.go

As part of https://issues.redhat.com/browse/OPNET-305 we are promoting External Load Balancer to GA. This requires installer to soften validations so that the feature is not any more limited only to TechPreview clusters.
Contributes-to: [OPNET-476](https://issues.redhat.com//browse/OPNET-476)

OPNET-476: GA Load balancer feature for vSphere and Baremetal

---

pkg/infrastructure/openstack/OWNERS

Transfer ownership of OpenStack-specific CAPI code to the ShiftStack team.

NO-JIRA: OWNERS: pkg/infrastructure/openstack

---

pkg/infrastructure/clusterapi/clusterapi.go

By extracting only the "status" stanza from the machine manifests, we are able to parse IP addresses in a provider-agnostic way.

CORS-3215: capi: implement bootstrap gather

---

pkg/asset/manifests/gcp/cluster.go

Updates the failure domain logic for the GCP Cluster manifest so that failure domains are populated only when zones are populated on both machine pools. Prior to this change, we only checked if the machine pools were defined, not that the zones were included.
Depends on #7917

CORS-3213: Tweak GCPCluster  Failure Domain Logic

---

pkg/asset/manifests/aws/cluster.go

This PR makes the internal LB be the primary CAPA load balancer and then adds the external LB as a secondary one when using public endpoints.

CORS-2902: capi/aws: add ext-LB as CAPA secondary LB

---

pkg/asset/installconfig/aws/route53.go
pkg/infrastructure/aws/clusterapi/aws.go

Fixes [CORS-3051](https://issues.redhat.com//browse/CORS-3051) by using CNAME instead of A records for Gov cloud.
Fixes [CORS-2894](https://issues.redhat.com//browse/CORS-2894) by assuming role `installconfig.platform.aws.hostedZoneRole` when creating resources.

CORS-2894,CORS-3051: Create DNS resources and PHZ for CAPI/aws

---

data/data/powervs/cluster/dns/dns.tf
data/data/powervs/cluster/dns/variables.tf

The image we used for booting proxy VMs has been updated and has changed it's name. We need to choose our images in a smarter fashion so this doesn't happen again.

OCPBUGS-31013: Fix vsi image missing

---

pkg/asset/installconfig/ibmcloud/metadata.go
pkg/asset/installconfig/ibmcloud/metadata_test.go

Restrict when the CIS and DNS Service instances are looked up in IBM Cloud, based on the PublishingStrategy, CIS for External, DNS Services for Internal. Preventing a baseDomain in each service resulting in both instances being found for metadata generation.
Related: https://issues.redhat.com/browse/OCPBUGS-28870

OCPBUGS-28870: IBMCloud: Restrict CIS and DNS Service lookup

---

pkg/asset/machines/aws/awsmachines.go
pkg/asset/machines/azure/azuremachines.go
pkg/asset/machines/clusterapi.go
pkg/asset/machines/gcp/gcpmachines.go
pkg/asset/machines/gcp/gcpmachines_test.go
pkg/asset/machines/openstack/openstackmachines.go
pkg/asset/machines/powervs/powervsmachines.go
pkg/asset/machines/vsphere/capimachines.go
pkg/asset/manifests/aws/cluster.go
pkg/asset/manifests/azure/cluster.go
pkg/asset/manifests/clusterapi/cluster.go
pkg/asset/manifests/gcp/cluster.go
pkg/asset/manifests/openstack/cluster.go
pkg/asset/manifests/vsphere/cluster.go
pkg/asset/store/assetcreate_test.go
pkg/asset/targets/targets.go
pkg/infrastructure/clusterapi/clusterapi.go

This PR:
* Changes the location where the capi machine manifests are written
* Adds TypeMeta information to all CAPI manifests
* Uses `.GroupVersion.String()` to retrieve `APIVersion` from the respective libs.
* Adds capi manifests to the output of `create manifests`

CORS-3142: capi: write manifests to disk during create manifests

---

pkg/asset/machines/clusterapi.go
pkg/asset/machines/gcp/gcpmachines.go

** CAPG machines were only being created in a single zone. The instances should be spread across multiple zones based on the availability zones.

OCPBUGS-30882: GCP capg distribute instances across zones

---

upi/openstack/security-groups.yaml

To make nodePort type Service work fine we need to enable the well known 30000:32767 traffic range.

Bug OCPBUGS-30154: OpenStack: enable 30000:32767 nodePort IPv6 traffic

---

pkg/asset/agent/common.go
pkg/asset/agent/image/ignition.go
pkg/asset/agent/image/ignition_test.go
pkg/asset/agent/image/releaseextract.go
pkg/asset/agent/image/releaseimage.go
pkg/asset/agent/image/releaseimage_test.go
pkg/asset/agent/image/unconfigured_ignition.go
pkg/asset/agent/installconfig.go
pkg/asset/agent/installconfig_test.go
pkg/asset/agent/oc.go

Adding additional validation to check that the release payload architecture matches the cluster's architecture.
Also fixes OCPBUGS-27787 - single arch  ABI installs w/multi payload, adding `cpu_architectures` to RELEASE_IMAGES
RELEASE_IMAGES: 
Single arch -
```  
'[{"openshift_version":"4.15","cpu_architecture":"x86_64","cpu_architectures":["x86_64"],"url":"quay.io/openshift-release-dev/ocp-release:4.15.0-rc.4-x86_64","support_level":"beta","version":"4.15.0-rc.4"}]
```
Multi -
```
[{"openshift_version":"4.15-multi","cpu_architecture":"multi","cpu_architectures":["x86_64","arm64","ppc64le","s390x"],"url":"quay.io/openshift-release-dev/ocp-release:4.15.0-rc.4-multi","support_level":"beta","version":"4.15.0-rc.4-multi"}]'
```

OCPBUGS-15941: ABI - Validate release image arch, add cpu_architectures to RELEASE_IMAGES

---

pkg/infrastructure/aws/aws.go
pkg/infrastructure/aws/bootstrap.go
pkg/infrastructure/aws/compute.go
pkg/infrastructure/aws/controlplane.go
pkg/infrastructure/aws/instance.go

When creating the instance role assume policy, we need to take into account that the ec2 service endpoint will differ according to the partition. This should fix the following error when deploying on C2S regions:
```
level=error msg=failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to create bootstrap resources: failed to create bootstrap instance profile: failed to create role (yunjiang-14c2a-t4wp7-bootstrap-role): RequestCanceled: request context canceled
```
because the installer is trying to use the regular `ec2.amazonaws.com` service suffix instead of the appropriate one.

OCPBUGS-26052: aws: altinfra: fix role creation in C2S

---

data/data/openstack/masters/main.tf

Due to a programming error, the server group policy set for the worker machines in install-config was ignored, and the master server group policy was always applied.

OCPBUGS-31050: openstack: Honour worker server group policy

---

pkg/asset/machines/aws/awsmachines.go
pkg/asset/machines/clusterapi.go

There was a lot of common code being duplicated when generating bootstrap vs controlPlane machine manifests.

no-jira: capi/aws: reuse GenerateMachines for bootstrap

---

pkg/asset/cluster/aws/aws.go

Because of how the CCM selects a Load Balancer security group by using the "kubernetes.io/cluster/<infraID>: owned" tag, CAPA removes that tag from all the other security groups [1].
That means that when the Installer is looking for resources to delete with that tag, it will never find those security groups and they'll stay behind. To avoid that, let's also search for resources with the "sigs.k8s.io/cluster-api-provider-aws/cluster/<infraID>: owned" tag during cluster destroy.
[1] https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4571
EDIT: updated with more accurate description.

CORS-2905: capi/aws: destroy CAPA resources

---

pkg/asset/machines/clusterapi.go
pkg/asset/machines/master.go
pkg/asset/machines/openstack/machines.go
pkg/asset/machines/openstack/machinesets.go
pkg/asset/machines/openstack/openstackmachines.go
pkg/asset/machines/worker.go

To make unit tests possible (and separate responsibilities), remove OSP API calls from the functions that generate Machines and MachineSets.

OSASINFRA-3420: openstack: Decouple OpenStack API calls from Machine generation

---

pkg/asset/installconfig/vsphere/validation.go

If a ESXi host is either in maintenancemode,
disconnected or not responding to vCenter
do not check the ESXi version as it may
not be available.

OCPBUGS-27848: If host is offline or disconnected don't check ver

---

data/data/install.openshift.io_installconfigs.yaml
pkg/types/aws/machinepool.go
pkg/types/aws/validation/machinepool.go
pkg/types/aws/validation/machinepool_test.go

AWS has a limit of 16 security groups. This limits the users to supply 10 security groups and reserves the additional 6 for OpenShift, which leaves room for additional features such as using CAPI for installs.

CORS-3428,CORS-2901: pkg/types/aws: limit additionalSecurityGroups to 10

---

pkg/infrastructure/gcp/clusterapi/clusterapi.go
pkg/infrastructure/gcp/clusterapi/firewallrules.go

Worker firewall rules are created to communication between the master and worker nodes including allowing the worker nodes to pull ignition. These match the worker firewall rules that were created by Terraform.
Note that this does not affect the permissive rule created by CAPG to allow traffic between the bootstrap and master nodes.

CORS-3431: CAPI: Add firewall rule for worker nodes

---

pkg/asset/manifests/aws/cluster.go
pkg/asset/manifests/aws/zones.go
pkg/asset/manifests/aws/zones_test.go

[CORS-2895](https://issues.redhat.com//browse/CORS-2895)
This PR create parity support in CAPA of subnet discover based in zones defined in Install Config, setting up CAPA manifests to create subnets into those zones.
The following scenarios are install-config variants to implement/validate parity in CAPA version:
> The region prefix has been removed from the zone name. Eg `a` represents the zone `us-east-1a`
| Scen# | CP[1] | WK[2] | Plat. Def[3] | Machines rendered in zones: | 
| -- | -- | -- | -- | -- |
| 1 | -- | -- | -- | a, b, c, d, f (All zones, except zone "e") |
| 2 | a | -- | -- | a, b, c, d, f (All zones, except zone "e") |
| 3 | --  | b | -- | a, b, c |
| 4 | a | b | -- | a, b |
| 5 | -- | -- | c | c |
| 6 | a | b | c | a, b |
| 7 | a | -- | c | a, c |
| 8 | -- | b | c | b, c …

CORS-2895: aws/capi: setting zones to when creating cluster

---

pkg/asset/machines/master.go

Removes log lines regarding loading static IPs from vsphere manifests. These are info level debug lines. We could downgrade them to debug level but I suspect they were originally included for debugging and it's better to just remove them.
```shell
INFO Loaded 0 ip claims.                          
INFO Loaded 0 ip addresses.                       
WARNING Found override for release image (registry.ci.openshift.org/ocp/release:4.16.0-0.ci-2024-03-18-142209). Please be warned, this is not advised 
INFO Consuming Worker Machines from target directory 
...
```

no-jira: pkg/asset/machines: remove static ip log lines

---

pkg/asset/manifests/cloudproviderconfig.go
pkg/asset/manifests/powervs/cluster.go
pkg/types/powervs/powervs_regions.go

1) We should be passing in a translated VPC region for the COS bucket.
2) The cluster-api-provider-ibmcloud uses a fixed set of subnets per VPC.  So, until we can ask the provider what it is, bring that data in so we can use it.

no-jira: PowerVS: Fix COS region and VPC subnets

---

pkg/asset/machines/openstack/machinesets.go

A nil pointer exception occurs when the OpenStack MachineSets() func is called with `Replicas==nil`, as it would be when hive is attempting to generate autoscaling MachineSets -- we set the replica count later on after we find out how many MachineSets to spread the autoscaling min/max across.
Add a safeguard to default to zero in this scenario.
Needed by [HIVE-2476](https://issues.redhat.com//browse/HIVE-2476)

HIVE-2476: OpenStack.MachineSets(): Allow nil Replicas

---

pkg/asset/cluster/cluster.go
pkg/infrastructure/clusterapi/clusterapi.go
pkg/infrastructure/clusterapi/types.go

This is needed by OpenStack to provision the server group for workers in the CAPI flow, based on the manifests potentially modified by the user.

OSASINFRA-3365: clusterapi: Add worker asset to PreProvision

---

pkg/asset/machines/aws/awsmachines.go
pkg/asset/machines/clusterapi.go

Depends on https://github.com/openshift/installer/pull/8169
/hold

CORS-3417: capi/aws: support ignition proxy and CA bundle

---

cmd/node-joiner/main.go
data/data/agent/files/usr/local/bin/add-node.sh
data/data/agent/systemd/units/agent-add-node.service
data/data/agent/systemd/units/agent-import-cluster.service.template
data/data/agent/systemd/units/agent-register-infraenv.service.template
data/data/agent/systemd/units/apply-host-config.service
hack/build-node-joiner.sh
pkg/asset/agent/image/agentartifacts.go
pkg/asset/agent/image/agentimage.go
pkg/asset/agent/image/baseiso.go
pkg/asset/agent/image/baseiso_test.go
pkg/asset/agent/image/ignition.go
pkg/asset/agent/image/ignition_test.go
pkg/asset/agent/image/releaseextract.go
pkg/asset/agent/image/releaseimage.go
pkg/asset/agent/image/unconfigured_ignition.go
pkg/asset/agent/joiner/clusterinfo.go
pkg/asset/agent/joiner/clusterinfo_test.go
pkg/asset/agent/manifests/common.go
pkg/asset/agent/manifests/nmstateconfig.go
pkg/asset/agent/manifests/nmstateconfig_test.go

This patch is based on PR #8080 (and also reuses service definitions from PR #8051 thanks @rwsu)
In this patch the Ignition asset is modified to enable the required services in case of add-node workflow

AGENT-858: Agent day2 ignition services

---

pkg/hostcrypt/dynamic.go
pkg/hostcrypt/hostcrypt.go
pkg/hostcrypt/static.go

Update the warning message from the hostcrypt check to give more specific instructions on how to obtain the correct binary and where to run it.

CORS-3446: Add instructions for obtaining correct binary

---

pkg/asset/machines/clusterapi.go
pkg/asset/manifests/azure/cluster.go
pkg/infrastructure/azure/azure.go
pkg/infrastructure/azure/dns.go

Use the existing resource group if the user sets the value for CAPI installation.

CORS-3075: Allow for installation in existing resource group

---

data/data/coreos/rhcos.json

[COS-2745](https://issues.redhat.com//browse/COS-2745): Update 4.16 bootimages to RHEL 9.4 Beta
```
x86_64=416.94.202404101051-0                                      \
aarch64=416.94.202404101051-0                                     \
s390x=416.94.202404101051-0                                       \
ppc64le=416.94.202404101051-0
```

OCPBUGS-32041: update RHCOS 4.16 bootimage metadata to 416.94.202404101051-0

---

pkg/infrastructure/azure/azure.go
pkg/infrastructure/azure/loadbalancer.go

Adds tags to the load balancer and public IP created in hooks. Forgot these in #8115

CORS-3270: azure: tag installer-created LB resources

---

images/libvirt/Dockerfile.ci

Multiarch CI jobs in 4.16 and onward are moving to a UPI deployment strategy.  `virt-install` is needed in the CI image to allow us to stand up the libvirt VMs for the cluster nodes.

MULTIARCH-4111: Update the CI image with virt-install

---

pkg/clusterapi/system.go

According to [1] v=4 is debug level.
[1] https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/logger/logger.go#L30

no-jira: capi/aws: bump controller log level to debug

---

pkg/asset/installconfig/powervs/client.go
pkg/asset/installconfig/powervs/mock/powervsclient_generated.go
pkg/infrastructure/powervs/clusterapi/powervs.go

We've asked the CAPI provider cluster-api-provider-ibmcloud to prioritize adding the bootstrap VM to the load balancer pools.  However, they have not done so.  Therefore, we will do it ourselves.

no-jira: PowerVS: add AddIPToLoadBalancerPool

---

cmd/openshift-install/agent.go
cmd/openshift-install/create.go
cmd/openshift-install/gather.go
cmd/openshift-install/main.go
pkg/asset/cluster/cluster.go
pkg/asset/generator.go
pkg/asset/store.go
pkg/asset/store/assetcreate_test.go
pkg/asset/store/assetsfetcher.go
pkg/asset/store/store.go
pkg/asset/store/store_test.go
pkg/infrastructure/aws/sdk/aws.go
pkg/infrastructure/clusterapi/clusterapi.go
pkg/infrastructure/provider.go
pkg/nodejoiner/addnodes.go
pkg/nodejoiner/monitoraddnodes.go
pkg/terraform/terraform.go

Adds a top-level context when running create commands. The context is passed through the asset store and then to any PostRun functions. The main motivation is for a clean shutdown of CAPI controllers, but there are a wide variety of potential use cases.
This PR uses the pattern introduced in #6009 to enable the introduction of a `GenerateWithContext` function for assets and an adapter to drop the context and call the original `Generate` function. Currently only the Cluster asset implements `GenerateWithContext`. 
Currently the PR achieves the primary goal of shutting down capi controllers on interrupt. There are some remaining issues I would like to clear up:

OCPBUGS-32091: Add Top-level Context for Create Commands

---

pkg/destroy/powervs/cloud-subnet.go
pkg/destroy/powervs/power-subnet.go
pkg/destroy/powervs/powervs.go
pkg/destroy/powervs/publicgateway.go

When we cleanup the Power Server DHCP server, it sometimes leaves behind its backing subnet.  If this is left around it will cause network problems for the next cluster.  Therefore, search and clean them up!

no-jira: PowerVS: Add destroy Power Server subnets

---

pkg/clusterapi/system.go

As the controllers' logs say, the arg has been replaced by `--diagnostics-address`:
```
Flag --metrics-bind-addr has been deprecated, Please use --diagnostics-address instead. To continue to servemetrics via http and without authentication/authorization set --insecure-diagnostics as well.
```

no-jira: capi: replace deprecated `--metrics-bind-addr` arg

---

hack/build.sh
images/baremetal/Dockerfile.ci
images/libvirt/Dockerfile.ci
pkg/hostcrypt/dynamic.go
pkg/hostcrypt/static.go

Libvirt IPI was never supported, so remove it from the payload build.

CORS-3420: Remove libvirt platform from openshift-baremetal-install

---

data/data/aws/bootstrap/main.tf
data/data/aws/bootstrap/outputs.tf

When the BYOIPv4 feature was introduced to the terraform provisioning in 50c0a9d8221, a new EIP resource was created unconditionally. The bootstrap VM was first getting a public IP from the `associate_public_ip_address` config in the instance and that IP was then discarded when the EIP was created and associated with the instance.
However, a "race" could happen in which, at the end of the bootstrap stage, we saved the first (and now dead) IP Address:
```
DEBUG Outputs:
DEBUG
DEBUG bootstrap_ip = "18.222.119.149"
DEBUG [INFO] running Terraform command: /c/terraform/bin/terraform output -no-color -json
DEBUG {
DEBUG   "bootstrap_ip": {
DEBUG     "sensitive": false,
DEBUG     "type": "string",
DEBUG     "value": "18.222.119.149"
DEBUG   }
DEBUG }
```
In case of bootstrap failure, the `gather …

OCPBUGS-32174: save correct bootstrap public IP

---

data/data/bootstrap/files/etc/systemd/system.conf.d/10-default-env.conf.template
pkg/asset/ignition/bootstrap/common.go

The 'DefaultEnvironment' config from systemd accepts some % specifiers for expansion [1]. Because of that, proxy configurations that make use of that character need to be escaped with another '%'. However, during proxy validation, the Installer parses the URI and fails when it encounters a "%%" with an `invalid URL escape` error.
To mitigate the problem, we introduce a new `replace` function to the templating system and use it to substitute "%" with "%%" causing the following config:
```
proxy:
httpProxy: http://user%40test:redhat@10.0.0.1:3128
httpsProxy: http://user%40test:redhat@10.0.0.1:3128
```
to become the `10-default-env.conf`:
```
[Manager]
DefaultEnvironment=HTTP_PROXY="http://user%%40test:redhat@10.0.0.1:3128"
DefaultEnvironment=HTTPS_PROXY="http://user%%40test:redhat@10.0.0.1:3 …
```

OCPBUGS-27965: escape '%' in proxy settings

---

data/data/install.openshift.io_installconfigs.yaml
pkg/explain/printer_test.go
pkg/types/aws/platform.go

** The go docs in the install-config's platform.aws.lbType is misleading as well as on the ingress object (oc explain ingresses.config.openshift.io.spec.loadBalancer.platform.aws.type). Update the docs to further explain the ingress controller info.

OCPBUGS-31711: AWS update explain docs

---

data/data/powervs/cluster/loadbalancer/sg.tf

The following testcase is failing:
```
[sig-arch] events should not repeat pathologically for ns/openshift-cloud-controller-manager
event happened 52 times, something is wrong: namespace/openshift-cloud-controller-manager node/p-wdc06-par-orig-416-fccsg-master-2 pod/powervs-cloud-controller-manager-67cdbc4ff-bv5cz hmsg/28f38e6c52 - reason/ProbeError Liveness probe error: Get "https://192.168.228.10:10258/healthz": dial tcp 192.168.228.10:10258: connect: connection refused result=reject
```
The cloud-provider-powervs provides that port, so open up access to it.

no-jira: PowerVS: Open port 10258

---

pkg/asset/machines/gcp/gcpmachines.go

** Add the disk encryption key information for the CAPG machines. The new feature includes the encryption for bootstrap as well as control plane machines created by the gcp cluster api provider.
** Note: CAPG supports Customer Managed (CMEK) and Customer Supplied (CSEK) Keys. The installer only supports Customer Supplied Keys.
** Note: CAPG supports multiple disks through the GCPMachine.Spec.AdditionDisks, but the installer only uses a single disk, so this PR will not fill out the disk encryption data for multiple disks.

CORS-3261: GCP cluster api add disk encryption

---

pkg/infrastructure/aws/sdk/securitygroup.go

Somehow this was missed when the rules were brought over from terraform.

OCPBUGS-31563: sdk/aws: add ssh security group rule for compute

---

pkg/asset/installconfig/aws/permissions.go

When publish == "External", the bootstrap VM will be assigned an EIP. During bootstrap destroy, the `terraform-provider-aws` code might call `DisassociateAddress` on the EIP before deleting the instance.

OCPBUGS-31017: aws: add `ec2:DisassociateAddress` permission

---

cmd/openshift-install/create.go
pkg/utils/baremetal/OWNERS
pkg/utils/baremetal/bootstrap.go
pkg/utils/baremetal/cache.go

We use a dynamic client to poll the API for changes to `baremetalhost` CRs and log provisioning state changes.  When all control plane hosts have finished provisioning, we move on to the next step in the cluster create process. 
An alternative solution would be to use code generation to provide a baremetal-specific clientset.
We will use this present monitoring mechanism in the future to record network information for each master node.  This information will be collected by the mustgather mechanism.

METAL-939: baremetal: monitor bootstrap process

---

data/data/gcp/bootstrap/main.tf
data/data/gcp/variables-gcp.tf
pkg/asset/cluster/tfvars/tfvars.go
pkg/asset/ignition/bootstrap/gcp/storage.go
pkg/infrastructure/clusterapi/clusterapi.go
pkg/infrastructure/clusterapi/types.go
pkg/infrastructure/gcp/clusterapi/clusterapi.go
pkg/terraform/stages/gcp/stages.go
pkg/tfvars/gcp/gcp.go

** Adjusting the use of a presigned url. Passing to terraform. 
** Adding the bucket and bucket object back to terraform 
** Presigned url is created for both capg and terraform installs. 
** CAPG will create and destroy the bucket and bucket object for bootstrap.

OCPBUGS-32133: GCP: Fixing GCP Bootstraping

---

pkg/asset/installconfig/powervs/client.go
pkg/asset/installconfig/powervs/mock/powervsclient_generated.go
pkg/infrastructure/powervs/clusterapi/powervs.go

In order to support `Internal` publishing strategy with CAPI, code must be added to create necessary DNS entries on the private DNS instance.

MULTIARCH-4549: Logic for creating private DNS records for PowerVS CAPI

---

data/data/agent/systemd/units/agent-import-cluster.service.template
data/data/agent/systemd/units/agent-register-cluster.service.template
data/data/agent/systemd/units/assisted-service.service.template
pkg/asset/agent/image/ignition.go
pkg/asset/agent/image/ignition_test.go

This patch fixes the usage of the registry CA bundle when mounted for the assisted-service and the agent-installer-client

OCPBUGS-32042: fix usage of addtionalTrustBundle field

---

pkg/asset/installconfig/installconfig.go
pkg/asset/installconfig/powervs/metadata.go

Implementing the [same fix](#7987) as IBM Cloud proposes for PowerVS.

OCPBUGS-29765: Fills CIS or DNS CRN in Metadata, never both

---

data/data/bootstrap/baremetal/files/usr/local/bin/master-bmh-update.sh

rather the the absense of lines with "provisioned". If the oc command fails the test will still evaluate to False.
Also mask failures from the second "oc get bmh" command so they wont cause the script to exit.

OCPBUGS-32425: Test for the presence of "provisioned" server

---

pkg/destroy/gcp/cloudcontroller.go

** Alter the log when destroying target pools. When the target pool is found but is not part of the cluster it was logging as an issue. It was a bit misleading, so the log is changed to explain that the resource wont be deleted because it is not part of the cluster.

OCPBUGS-32591: GCP Destroy target pools fix misleading log

---

data/data/bootstrap/baremetal/files/usr/local/bin/master-bmh-update.sh

Use a kubeconfig that points to api-int and retry on failure.

OCPBUGS-32517: Ensure worker BMH's get unpaused

---

data/data/install.openshift.io_installconfigs.yaml
pkg/asset/manifests/infrastructure.go
pkg/types/powervs/platform.go
pkg/types/powervs/validation/platform.go
pkg/types/powervs/validation/platform_test.go

Some cluster operators will read the platformStatus for endpoint overrides. Read them from the install config and pass them along through the infrastructure manifest.

MULTIARCH-4616: Power VS: Add ServiceEndpoints for endpoint overrides

---

images/libvirt/Dockerfile.ci

In an effort to convert the libvirt IPI workflows to UPI, I will be using qemu-img to increase the size of a qemu used for cluster node creation.

MULTIARCH-4111: Updating CI image to include qemu-kvm

---

pkg/asset/manifests/azure/cluster.go

Adding the field AdditionalTags to AzureCluster with the user tags from the install config.

CORS-3076: azure: Add additional tags to AzureCluster

---

pkg/asset/installconfig/aws/permissions.go
pkg/asset/installconfig/platformpermscheck.go

We only need this permission when using public IPv4 pool, so change the permissions to reflect that.
This is a follow-up to https://github.com/openshift/installer/pull/8247

OCPBUGS-31017: fix ec2:DisassociateAddress requirement

---

data/data/agent/files/usr/local/bin/agent-gather
data/data/agent/files/usr/local/bin/load-config-iso.sh
data/data/agent/systemd/units/agent-add-node.service
data/data/agent/systemd/units/agent-import-cluster.service.template
data/data/agent/systemd/units/agent-register-cluster.service.template
data/data/agent/systemd/units/agent-register-infraenv.service.template
data/data/agent/systemd/units/apply-host-config.service
data/data/agent/systemd/units/start-cluster-installation.service
pkg/asset/agent/image/ignition.go
pkg/asset/agent/image/ignition_test.go

The `agent-register-cluster` systemd service is disabled in the unconfigured ignition since #8093, which broke the appliance CI jobs.

OCPBUGS-32519: Fix appliance CI jobs

---

pkg/asset/manifests/aws/zones.go
pkg/asset/manifests/aws/zones_test.go

[CORS-2899](https://issues.redhat.com/browse/CORS-2899)
This PR introduce support of AWS Local Zones using CAPA as infrastructure provisioner for managed (automated VPC) and unmanaged (BYO VPC) deployments.
References:
- Jira story on "CAPA moving to Terraform" Epic/Goal: https://issues.redhat.com/browse/CORS-2899
- CAPA feature request: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4874
- CAPA feature PR: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4882
Blocked by:

CORS-2899: AWS/CAPI Local Zones network provisioning 

---

hack/build-cluster-api.sh
images/installer-altinfra/Dockerfile.ci

When building the altinfra image for inclusion in the release payload, we cannot download any binaries as it is currently done for etcd/kas. Instead let's copy those binaries from their existing container images.

CORS-3250: images/altinfra: add etcd/kas binaries from containers

---

pkg/asset/cluster/tfvars/tfvars.go

Add additional checks around detecting 0 worker machinesets when generating terraform.tfvars for compact clusters.
This bug was raised when https://issues.redhat.com/browse/CORS-2420 was tested. The associated feature https://issues.redhat.com/browse/OCPSTRAT-341 had epics for AWS, GCP, Azure and vSphere. Support for compact clusters was not implemented and hence this is a good way error out of the install with an informational message to the customer (instead of crashing).

OCPBUGS-4466: Add check for compact-cluster install on GCP, AWS & Azure

---

pkg/asset/manifests/aws/cluster.go

This feature is needed for customers running installs under systems with policies that prevent S3 objects from being deleted.
The way this was implemented in CAPA, the provider will try to delete the objects but ignore the errors if `BestEffortDeleteObjects` is set in the `AWSCluster` bucket spec.

CORS-2893: capi-aws: implement preserveBootstrapIgnition

---

pkg/types/baremetal/validation/platform.go

For builds with baremetal support (until now only the openshift-baremetal-installer), the agent installer was attempting to validate the bootstrap provisioning network using libvirt. This is not required because the agent installer does not make use of a bootstrap VM.

[4.15] OCPBUGS-30944: Don't run libvirt validations in agent installer

---

upi/vsphere/powercli/upi-functions.ps1
upi/vsphere/powercli/upi.ps1

[SPLAT-1596]([SPLAT-1596](https://issues.redhat.com//browse/SPLAT-1596))
Attempting to fix an issue where in vSphere 8.0, the Set-HardDisk is causing vCenter to crash.
- Created new updateDisk function
It seems that the Set-HardDisk function of vSphere's powercli works fine in our vSphere 7.x instances, but for devqe (which is 8.x), it seems the Set-HardDisk function causes the vCenter instance to stop running.  To workaround this due to time, we quickly created this method to manually attempt to set the disk size using back channels.

SPLAT-1596: Created new function to workaround issue with Set-HardDisk.

---

pkg/infrastructure/clusterapi/clusterapi.go

Implements basic safeguard so that provisioning does not spin indefinitely. A timeout (currently 15m) is set for each provisioning stage.

CORS-3437: infra/capi: add provisioning timeout

---

images/baremetal/Dockerfile.ci
images/installer/Dockerfile.ci

This patch removes the explicit `cli-artifacts` dependency from the images to avoid introducing further complications in the build pipeline (see https://github.com/openshift-eng/ocp-build-data/pull/4751), and switches the approach to directly install `openshift-clients` package just in the `baremetal-installer` image for retrieving the `oc` cli tool, required by [ node-joiner](https://github.com/openshift/installer/blob/c2fa2bfec3b1c0cbeeaa5d6c3486775c8f04d515/docs/user/agent/add-node/node-joiner.sh#L112).

AGENT-863: fix oc dependency in installer images 

---

data/data/agent/files/etc/systemd/system.conf.d/10-default-env.conf.template

The 'DefaultEnvironment' config from systemd accepts some % specifiers for expansion [1]. Because of that, proxy configurations that make use of that character need to be escaped with another '%'.
[1] https://man7.org/linux/man-pages/man5/systemd-system.conf.5.html

OCPBUGS-33024: agent: escape '%' in proxy settings

---

docs/user/agent/add-node/add-nodes.md

AGENT-863: docs fix

---

data/data/bootstrap/baremetal/files/usr/local/bin/master-bmh-update.sh
data/data/bootstrap/baremetal/systemd/units/master-bmh-update.service.template
pkg/asset/ignition/bootstrap/baremetal/template.go
pkg/asset/ignition/bootstrap/baremetal/template_test.go
pkg/asset/ignition/bootstrap/common.go

`*installConfig.ControlPlane.Replicas` is the canonical source of this information and we don't want to rely on the `IsMaster()` function.
We also change how that number gets to the master-bmh-update.sh script. We template the number into the systemd service instead of the shell script.  This gives us shellcheck.
This is a follow-up to #8316

OCPBUGS-32981: baremetal: use ControlPlane.Replicas

---

images/baremetal/Dockerfile.ci

Fix to avoid including the cache in the final image

AGENT-864: cleanup dnf cache after installing node-joiner reqs

---

.ci-operator.yaml
images/baremetal/Dockerfile.ci
images/infrastructure-providers/Dockerfile
images/installer-artifacts/Dockerfile.rhel
images/installer/Dockerfile.ci
images/installer/Dockerfile.upi.ci
images/libvirt/Dockerfile.ci
images/libvirt/google-cloud-sdk.repo
images/openstack/Dockerfile.ci
pkg/hostcrypt/static.go

Use RHEL 9 as a base for all our container images.

CORS-2797: images: move container images to RHEL 9

---

pkg/infrastructure/aws/securitygroup.go

Somehow this was missed when the rules were brought over from terraform.
Manual cherry-pick from https://github.com/openshift/installer/pull/8229

[release-4.15] OCPBUGS-32383: sdk/aws: add ssh security group rule for compute

---

data/data/coreos/rhcos.json

[COS-2744](https://issues.redhat.com//browse/COS-2744): Switch RHCOS from RHEL 9.4 Beta to GA
```
x86_64=416.94.202404301731-0                                      \
aarch64=416.94.202404301731-0                                     \
s390x=416.94.202404301731-0                                       \
ppc64le=416.94.202404301731-0
```

COS-2744: update RHCOS 4.16 bootimage metadata to 416.94.202404301731-0

---

pkg/asset/manifests/cloudproviderconfig.go
pkg/infrastructure/powervs/clusterapi/powervs.go

In the private scenario, both `api` and `api-int` will point to the private loadbalancer. Update the DNS creation call back to support this.

MULTIARCH-4633: Power VS: Configure load balancers for the private scenario

---

images/baremetal/Dockerfile.ci
images/installer-altinfra/Dockerfile.ci
images/installer-artifacts/Dockerfile.rhel
images/installer/Dockerfile.ci
images/installer/Dockerfile.upi.ci
images/libvirt/Dockerfile.ci
images/openstack/Dockerfile.ci

We copy pre-built binaries from the `-artifacts` images when we want statically linked binaries and from the regular etcd/hyperkube images for dynamically linked binaries.
This is necessary to have capi and capi providers included in the installer images both for CI and for the release payload.

CORS-3250: images: use pre-built KAS/etcd binaries

---

go.mod
go.sum
vendor/github.com/openshift/assisted-image-service/pkg/isoeditor/isoutil.go
vendor/modules.txt

This patch bumps the `assisted-image-service` dependency to version [v0.0.0-20240506123319-82517255ca17](https://github.com/openshift/assisted-image-service/commit/82517255ca171cd7351fec9da7107b4c2cdcac07), since it contains the required bug fix.
Requires https://github.com/openshift/assisted-image-service/pull/201

OCPBUGS-33240: avoid FAT32 error messages when generating the agent ISO

---

data/data/bootstrap/baremetal/files/etc/containers/systemd/metal3-baremetal-operator.container

Needed by https://github.com/openshift/baremetal-operator/pull/335

NO-ISSUE: baremetal: disable bmo webhook on bootstrap

---

pkg/clusterapi/localcontrolplane.go
pkg/clusterapi/system.go
pkg/destroy/bootstrap/bootstrap.go
pkg/infrastructure/aws/sdk/aws.go
pkg/infrastructure/baremetal/baremetal.go
pkg/infrastructure/clusterapi/clusterapi.go
pkg/infrastructure/provider.go
pkg/terraform/terraform.go

Sets the etcd data dir in envtest so that etcd state is written to disk, allowing the local CAPI control plane to be restarted, particularly for the support of the `openshift install destroy bootstrap` command.
Tested locally by starting an installation:
```shell
[root@41b49ed47ee7 /]# ./openshift-install create cluster --dir c
INFO Credentials loaded from the "default" profile in file "/root/.aws/credentials" 
WARNING Found override for release image (quay.io/openshift-release-dev/ocp-release:4.16.0-ec.6-x86_64). Please be warned, this is not advised 
INFO Consuming Install Config from target directory 
WARNING FeatureSet "CustomNoUpgrade" is enabled. This FeatureSet does not allow upgrades and may affect the supportability of the cluster. 
INFO Creating infrastructure resources... …
```

CORS-3471: standalone destroy bootstrap support with capi

---

pkg/infrastructure/clusterapi/clusterapi.go

This is just a minor typo, but since its in an Info message that will appear on every installation, it should be fixed.

OCPBUGS-33430: Fix CAPI installation typo

---

docs/user/agent/add-node/add-nodes.md
docs/user/agent/add-node/node-joiner-monitor.sh

Derived from a similar script by Andrea Fasano to generate the add-nodes ISO.
https://github.com/openshift/installer/pull/8242
This script tweaks it and creates a node-joiner-monitor pod to monitor adding nodes to a cluster.

AGENT-906: Script to run monitor-add-nodes in cluster

---

pkg/asset/machines/vsphere/machines.go

OCPBUGS-32947
- Modified vSphere logic when generating the control plane machine set (CPMS) to not include the following if FailureDomain count >= 1
- Network
- Template
- Workspace

OCPBUGS-32947: Changed vsphere CPMS to not include fields controlled by failure domains.

---

pkg/asset/machines/aws/awsmachines.go
pkg/asset/machines/aws/awsmachines_test.go
pkg/asset/machines/clusterapi.go

Nodes must be correctly distributed among zones in the default deployment, Manage VPC and no zones is set in the install-config.yaml.
Additionally, when the zones is set, the control plane nodes must follow the user-defined configuration, placing nodes correctly in the zones, considering the "subnet internet facing", when the PublicIP is set to the machine.
This change changes the behavior not letting CAPA decide which zones will be placed when no subnets are set, keeping the terraform parity which is distributing control plane nodes between zones, preventing nodes in the same zone when there are available.

CORS-2895: capa/machines: fix zone placement for control planes

---

docs/user/agent/add-node/node-joiner-monitor.sh

ipAddresses should be a string containing a space delimited list of IP addresses to be monitored.

AGENT-863: Change $@ to "$*" to fix shellcheck

---

pkg/asset/machines/azure/azuremachines.go

CAPZ equivalent for #8380 
Change Azure Masters to use ReadWrite cache.
The write is then lazily written to the disk when the cache is flushed periodically. Customers can additionally force a flush by issuing an f/sync or fua command.
etcd should be ok with this change since etcd does fsyncs when needed.
https://learn.microsoft.com/en-us/azure/virtual-machines/disks-performance
/cc @rphillips @jhixson74 @rna-afk

no-jira: AzureMachines: set disk caching to ReadWrite

---

data/data/azure/cluster/master/master.tf

Change Azure Masters to use ReadWrite cache.
```The write is then lazily written to the disk when the cache is flushed periodically. Customers can additionally force a flush by issuing an f/sync or fua command.```
etcd should be ok with this change since etcd does fsyncs when needed.
https://learn.microsoft.com/en-us/azure/virtual-machines/disks-performance

OCPBUGS-33470: use read/write cache on azure masters

---

data/data/bootstrap/files/usr/local/bin/bootstrap-pivot.sh.template

Align with the version-less-ness of `rhel-coreos` and `fedora-coreos` and shorten the overall tag.
Both tags are currently aliases, `centos-stream-coreos-9` will be removed in the future.

OKD-213: Reference stream-coreos instead of centos-stream-coreos-9

---

pkg/asset/installconfig/aws/route53.go
pkg/infrastructure/aws/clusterapi/aws.go

Fallback to querying the LB if the region is not in the lookup table. Which is the case, e.g., with C2S/SC2S regions.

OCPBUGS-33578: capi/aws: fix HostedZone ID lookup

---

hack/build-cluster-api.sh

We cannot execute cross-compiled binaries, otherwise we get an error saying:
```
hack/build-cluster-api.sh: line 26: /go/src/github.com/openshift/installer/cluster-api/bin/darwin_amd64/kube-apiserver: cannot execute binary file: Exec format error
```
The check should be skipped in those cases.

CORS-3516: hack: do not execute cross-compiled binaries 

---

pkg/asset/machines/aws/awsmachines.go
pkg/asset/machines/aws/awsmachines_test.go

Convert from Installer type to CAPA type instead of relying on the string value, otherwise we'll fail with:
```
INFO Creating Route53 records for control plane load balancer
ERROR failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to create control-plane manifest: AWSMachine.infrastructure.cluster.x-k8s.io "yunjiang-cap4-fp88c-bootstrap" is invalid: spec.instanceMetadataOptions.httpTokens: Unsupported value: "Required": supported values: "optional", "required"
```

OCPBUGS-33502: capi/aws: fix setting IMDSv2 value

---

cmd/openshift-install/create.go
data/data/azure/bootstrap/main.tf
data/data/bootstrap/files/usr/local/bin/bootstrap-verify-api-server-urls.sh

In some instances we see bootkube.sh completing and writing the bootstrap complete configmap when the script has failed to detect the API servers. There is a separate case where the API up detection can timeout, but the error handling is bypassed.
```
May 08 15:59:54 kwilczynski-dev2-bgvpw-bootstrap bootkube.sh[2748]: Unable to reach API_URL's https endpoint at https://api.kwilczynski-dev2.catchall.azure.devcluster.openshift.com:6443/version
May 08 15:59:54 kwilczynski-dev2-bgvpw-bootstrap bootkube.sh[2748]: Unable to validate. https://api.kwilczynski-dev2.catchall.azure.devcluster.openshift.com:6443/version is currently unreachable.
May 08 15:59:54 kwilczynski-dev2-bgvpw-bootstrap bootkube.sh[2748]: Checking if api-int.kwilczynski-dev2.catchall.azure.devcluster.openshift.com of type …
```

OCPBUGS-33610: fix API detection, azure bootstrap disk size, and use get to verify endpoint

---

pkg/quota/aws/limits.go

We missed this when support to ca-west-1 region was added.

OCPBUGS-33649: add quota support to ca-west-1

---

pkg/asset/installconfig/aws/permissions.go

We need to retrieve the IPv4 pools to validate them before the install, so we need the `ec2:DescribePublicIpv4Pools` permission when the feature is enabled.

OCPBUGS-31017: aws: add missing permission for IPv4 pools

---

go.mod
go.sum
vendor/github.com/openshift/api/features/features.go
vendor/modules.txt

Vendoring openshift API changes to include tech preview feature set for gcp capi installs

no-jira: Vendor api changes for tech preview with capg

---

data/data/coreos/rhcos.json

OCPBUGS-33528:RHCOS root reprovisioning went from ~5 mins to ~11 mins in Azure
```
x86_64=416.94.202405132047-0                                      \
aarch64=416.94.202405132047-0                                     \
s390x=416.94.202405132047-0                                       \
ppc64le=416.94.202405132047-0
```

OCPBUGS-33531: update RHCOS 4.16 bootimage metadata to 416.94.202405132047-0

---

pkg/utils/baremetal/bootstrap.go

Even if some masters didn't finish provisioning and we had to exit due to context cancel, we should still write the state to disk.

OCPBUGS-33370: baremetal: always write masters file

---

pkg/asset/manifests/aws/cluster.go
pkg/infrastructure/aws/clusterapi/aws.go
pkg/infrastructure/clusterapi/clusterapi.go
pkg/infrastructure/clusterapi/types.go

Extends the capi provider interface with a boostrap destroy hook and implements logic for aws to delete the bootstrap ssh rule by updating the ingress rules on the awscluster. 
Depends on #8350 which pipes the context into the bootstrap destroy logic
Tested locally and this works fine. I removed the debug logging, so there is not much to point to in ci logs.

CORS-2905: capi-aws delete bootstrap ssh rule

---

pkg/infrastructure/gcp/clusterapi/clusterapi.go
pkg/infrastructure/gcp/clusterapi/firewallrules.go

Add a rule to ssh into the bootstrap node. Node that this rule will need to be deleted when the bootstrap is deleted. The deletion fix depends on https://github.com/openshift/installer/pull/8359 and will be made after that merges.

CORS-3297: Add GCP firewall rule to access bootstrap node via ssh

---

images/infrastructure-providers/Dockerfile

They should be dynamically linked as the rest of the binaries for FIPS support.

OCPBUGS-33542: images: do not force terraform-providers to be statically linked

---

data/data/gcp/bootstrap/main.tf

** Ignition was being given the signed url, but the url does not point to ignition data that contains the proxy information. The ignition shim contains the url and should be supplied as metadata to the bootstrap node. The shim will contain the url as well as proxy data, and the url will point to the bucket that contains the actual ignition bootstrap data.

OCPBUGS-33709: GCP mixup when using the ignition shim vs the signed url

---

pkg/clusterapi/localcontrolplane.go
pkg/infrastructure/clusterapi/clusterapi.go

Depends on #8387 
Currently, we're only collecting the manifests for the capi-created resources when provisioning is successful. This changes the behavior so we also collect the logs in case of failure.  
Also, I noticed we're leaking the `<clusterdir>/bin` directory because the capi system creates `<clusterdir>/bin/cluster-api` but only deletes the `cluster-api` dir. I think the simplest fix is to just not create the `/bin/` dir 
/cc @r4f4 
Not sure I love the implementation (using the `finish` method), but my alternate experiments with `defer` were clunky and didn't work.

CORS-3460: Always collect clusterapi manifests

---

cmd/node-joiner/main.go
cmd/openshift-install/agent/waitfor.go
pkg/agent/cluster.go
pkg/agent/kube.go
pkg/agent/monitoraddnodes.go
pkg/agent/monitoraddnodes_test.go
pkg/agent/ocp.go
pkg/agent/rest.go
pkg/agent/validations.go
pkg/nodejoiner/addnodes.go
pkg/nodejoiner/monitoraddnodes.go

The first and second CSRs pending approval have the node name (hostname) embedded in their specs. monitor-add-nodes should only show CSRs pending approval for a specific node. Currently it shows all CSRs pending approval for all nodes.
If the IP address of the node cannot be resolved to a hostname, we will not be able to determine if there are any CSRs pending approval for that node. The monitoring command will skip showing CSRs pending approval. In this case, users can still approve the CSRs, and the monitoring command will continue to check if the node has joined the cluster and has become Ready.

AGENT-903: monitor-add-nodes should only show CSRs matching node

---

upi/vsphere/powercli/upi-functions.ps1
upi/vsphere/powercli/upi.ps1

OCPBUGS-33668
- Updated powercli script to use cluster name as folder name instead of infra-id.

OCPBUGS-33668: Changed folder name to match cluster name instead of infra-id.

---

pkg/asset/manifests/infrastructure.go

When custom endpoints are passed into install config, we also need to fill out 
```
config.Spec.PlatformSpec.PowerVS.ServiceEndpoints
```
as the PowerVS machine provider checks there for the values.

OCPBUGS-33995: PowerVS: Also fill out PlatformSpec for custom endpoints

---

data/data/bootstrap/files/usr/local/bin/bootstrap-verify-api-server-urls.sh

Improve API server readiness before leaving bootstrap

OCPBUGS-30860: bootstrap: hit readyz when checking LB status

---

docs/user/agent/add-node/node-joiner-monitor.sh

The containerized monitor-add-nodes does not have the correct permissions to write to the current working directory. Set the working directory to /tmp in the container command.

OCPBUGS-34040: Add --dir /tmp to node-joiner-monitor.sh

---

pkg/asset/manifests/aws/cluster.go
pkg/types/installconfig.go

Prior to this change, SSH was open to the public internet when installing on a private cluster. This restricts SSH to the machine network.

OCPBUGS-34389: aws/cluster: restrict SSH on private clusters

---

pkg/asset/machines/nutanix/capimachines.go

OCPBUGS-33570: Nutanix IPI install with capi failed to set bootType

OCPBUGS-33570: Nutanix IPI install with capi failed to set bootType

---

images/installer/Dockerfile.upi.ci.rhel8

This is now just a symlink to `Dockerfile.upi.ci` and it was first created during the transition from rhel7 to rhel9. All our images are now rhel9 based.
All the 4.16+ references to this symlink have been removed by https://github.com/openshift/release/pull/50359.

no-jira: images: delete Dockerfile.upi.ci.rhel8

---

pkg/asset/installconfig/aws/route53.go

The CallerReference used when creating an AWS Hosted Zone should be unqiue, as stated in the docs:
> A unique string that identifies the request
https://docs.aws.amazon.com/cli/latest/reference/route53/create-hosted-zone.html
Prior to this commit, the Caller Reference is simply a timestamp. We have seen an issue, when batch launching multiple simultaneous installs in CI that the call may happen at the same time and therefore have the same Caller Reference, which leads to the failure:
> failed to create private hosted zone: error creating private hosted zone:
> HostedZoneAlreadyExists: A hosted zone has already been created with
> the specified caller reference.
Instead, let's use the infraid, which is our typical way of distinguishing clusters and contains a short unique-ish id to
avoid …

OCPBUGS-34243: unique AWS HostedZone Caller Ref

---

pkg/asset/installconfig/powervs/regions.go

If I press the enter key at the first option in the region survey
? Region  [Use arrows to move, type to filter, ? for more help]
\> Account Region 1
\> Account Region 2
I get the following error
X Sorry, your reply was invalid: invalid region ""
This patch fixes this error.

MULTIARCH-4076: PowerVS: Default region bug fix

---

pkg/asset/agent/common.go

Adding `--insecure=true` to enable detecting a release images' architecture instead of failing silently when the local registry doesn't have a valid cert.

MGMT-17468: Detect Release Image Arch in a Disconnected Env.

---

pkg/asset/cluster/tfvars/tfvars.go

Now that some platforms are using CAPI by default, an error during the tfvars asset generation can be confusing by making it look like we're still using terraform:
```
05-19 17:36:32.935  level=fatal msg=failed to fetch Terraform Variables: failed to fetch dependency of "Terraform Variables": failed to generate asset "Platform Provisioning Check": baseDomain: Invalid value: "qe.devcluster.openshift.com": the zone already has record sets for the domain of the cluster: [api.gpei-0519a.qe.devcluster.openshift.com. (A)]
```
By changing the asset's name and leaving the rest unchanged, we can eliminate such confusion and avoid breaking other platforms still using terraform, until we're ready to stop generating tfvars json files altogether.

OCPBUGS-33925: tfvars: change asset's name

---

pkg/asset/installconfig/clusterid.go

Long cluster names get trimmed by the installer if they're greater than `maxBaseLen`. The user needs to be warned about this behavior so that they don't create say, two clusters with similar names distinguished only towards the ending such as `verylongclustername1` and `verylongclustername2`. Although these two clusters won't create conflicting resources as they're suffixed by alphanumeric characters, this can still lead to the user getting confused.

OCPBUGS-33840: Warn before trimming cluster name

---

pkg/destroy/vsphere/client.go
pkg/infrastructure/vsphere/clusterapi/clusterapi.go

We missed tagging a folder while creating the
vsphere infrastucture in the capv/capi flow.
This PR adds the attachment.

OCPBUGS-33410: attach tag to folder,fix folder destroy

---

cmd/openshift-install/features.go
cmd/openshift-install/main.go
data/data/aws/bootstrap/main.tf
data/data/aws/cluster/main.tf
data/data/aws/cluster/master/main.tf
data/data/aws/cluster/master/variables.tf
data/data/aws/variables-aws.tf
pkg/tfvars/aws/aws.go

Spot instances can result on savings for short-lived clusters. If the control plane machine manifests have been edited with spot instance information, enable the use of spot instances in the terraform config. Notice that max price information is ignored, since it's not advised for it to be set.

CORS-3524, CORS-3523: aws: terraform: add spot instance support for masters

---

pkg/types/validation/installconfig.go
pkg/types/validation/installconfig_test.go

This PR aims at bringing an early warning about the fact that the ingress capability should be enabled. This PR is additional to https://github.com/openshift/cluster-version-operator/pull/946 which always enables the ingress capability on any cluster managed by CVO.
Initial EP: https://github.com/openshift/enhancements/blob/master/enhancements/ingress/optional-ingress-hypershift.md.

OCPBUGS-33793: Make Ingress capability required for standalone OpenShift

---

pkg/infrastructure/aws/clusterapi/ami.go
pkg/infrastructure/aws/clusterapi/aws.go

When I introduced the AMI copying functionality, I inadvertently broke the custom AMI logic, causing the code to always use the default RHCOS AMI.
This PR fixes the issue and adds some comments to explain the AMI selection logic which spans multiple files and is not easy to follow.

OCPBUGS-33508: capi/aws: fix setting custom AMI

---

data/data/install.openshift.io_installconfigs.yaml
data/data/openstack/masters/private-network.tf
data/data/openstack/variables-openstack.tf
pkg/asset/machines/clusterapi.go
pkg/asset/machines/master.go
pkg/asset/machines/openstack/machines.go
pkg/asset/machines/openstack/machinesets.go
pkg/asset/machines/openstack/openstackmachines.go
pkg/asset/machines/worker.go
pkg/tfvars/openstack/openstack.go
pkg/types/openstack/platform.go

As Kuryr is removed the creation of trunks for the machines is not a requirement anymore. To reduce the amount of resources we manage by default, let's avoid creating it as is not a requirement. This commit will disable trunk creation by default and let the user enable trunk by modifying the generated Machine manifests. Also, the terraform support for creation of Machines with Trunk is being removed.

OSASINFRA-3456: OpenStack: do not use trunk for the Machines by default

---

pkg/types/validation/installconfig.go
pkg/types/validation/installconfig_test.go

OpenShiftSDN CNI plugin will no longer be supported from 4.15. Add deprecation notice for 4.14 users to swicth to OVNKubernetes.

CORS-2951: Add deprecation notice for OpenShiftSDN for 4.14 users

---

data/data/coreos/rhcos.json

OCPBUGS-32466 - Agent service fails to start since cannot pull assisted-installer-agent image
```
x86_64=416.94.202405291527-0                                      \
aarch64=416.94.202405291527-0                                     \
s390x=416.94.202405291527-0                                       \
ppc64le=416.94.202405291527-0
```

OCPBUGS-34693: update RHCOS 4.16 bootimage metadata to 416.94.202405291527-0

---

data/data/coreos/rhcos.json

These changes will update the RHCOS 4.17 boot image metadata from 4.16.
```
--distro rhcos --no-signatures --name 4.17-9.4                   \
x86_64=417.94.202405291927-0                                      \
aarch64=417.94.202405291927-0                                     \
s390x=417.94.202405291927-0                                       \
ppc64le=417.94.202405291927-0
```

OCPBUGS-34692: update RHCOS 4.17 bootimage metadata to 417.94.202405291927-0

---

pkg/types/validation/installconfig.go
pkg/types/validation/installconfig_test.go

Follow up of https://github.com/openshift/installer/pull/8502. The Ingress should be required for all the baselines not only for the one it was introduced in: `v4.16`.

OCPBUGS-33793: Make Ingress capability required for all baselines

---

pkg/asset/installconfig/powervs/client.go
pkg/destroy/powervs/serviceinstance.go

Issue observed:
`level=fatal msg=failed to fetch Terraform Variables: failed to fetch dependency of "Terraform Variables": failed to generate asset "Platform Provisioning Check": platform:powervs:serviceinstance has an invalid guid `
Cause:
The new workspaces that are created has resource instance type as "composite_instance" whereas for the older ones its "service_instance", due to this change the above error was seen. This PR checks for composite_instances also while listing service instances

[release-4.14] OCPBUGS-33401: PowerVS: Add composite_instance to listServiceInstances

---

data/data/bootstrap/baremetal/files/etc/containers/systemd/ironic-dnsmasq.container
data/data/bootstrap/baremetal/systemd/units/provisioning-interface.service.template

In the baremetal bootstrap it is not sufficient to make ironic.service conditionally Require provisioning-interface.service, as 104eae17b879b84700c31072c3a6eba40fc5e8a1 attempted to do, when the latter is already enabled because it is WantedBy multi-user.target. As long as it is enabled, systemd will try to start it.
Do not install provisioning-interface.service, so that it will only be enabled when ironic.service requires it (i.e. when the provisioning network is not disabled). Similarly, do not install ironic-dnsmasq.service, so that it will only be enabled when ironic.service wants it (i.e. when the provisioning network is not disabled or unmanaged).

OCPBUGS-34493: baremetal: Don't always enable provisioning-interface.service

---

pkg/types/validation/installconfig.go
pkg/types/validation/installconfig_test.go

Backport of https://github.com/openshift/installer/pull/8502 and https://github.com/openshift/installer/pull/8525.

[release-4.16] OCPBUGS-33794: Make Ingress capability required for standalone OpenShift

---

cmd/openshift-install/create.go

241ec4efe4cc1e4d90c1a8d5d8b2200701e53a9f introduced a new step that causes the `report-progress.sh` script to wait for the cluster to stabilize and have at least 2 API endpoint. On an observed OpenStack cluster, this added 8 minutes to the bootstrap phase, between when `bootkube.service` reported completion and when the `kube-system/bootstrap` config map was created. The wait for bootstrap to complete took 32 min, instead of 24 had it not waited for the cluster to have multiple API endpoints.
This commit bumps the timeout inside the `waitForBootstrapComplete()` function from 30 min to 45 min to account for this new step.

OCPBUGS-34900: Increase timeout for bootstrap complete

---

pkg/infrastructure/powervs/clusterapi/powervs.go

When the publish strategy is Internal, we'll need to allow some extra ports.

OCPBUGS-34969: Power VS: Add ports needed for private clusters to security group

---

pkg/asset/installconfig/aws/permissions.go
pkg/asset/installconfig/platformpermscheck.go

They shouldn't be required when `preserveBootstrapIgnition` is set in the install-config.yaml. Otherwise, the install fails with:
```
INFO Credentials loaded from the "denys3" profile in file "/home/cloud-user/.aws/credentials"
INFO Consuming Install Config from target directory
WARNING Action not allowed with tested creds          action=s3:DeleteBucket
WARNING Action not allowed with tested creds          action=s3:DeleteObject
WARNING Action not allowed with tested creds          action=s3:DeleteObject
WARNING Tested creds not able to perform all requested actions
FATAL failed to fetch Cluster: failed to fetch dependency of "Cluster": failed to generate asset "Platform Permissions Check": validate AWS credentials: current credentials insufficient for performing cluster installation
```

OCPBUGS-33662: aws: don't always require s3:Delete* permissions

---

pkg/asset/machines/aws/awsmachines.go
pkg/asset/machines/aws/awsmachines_test.go

They should get their ignition from the MCS running on the bootstrap node. The s3 stub is only needed for bootstrap.

OCPBUGS-35020: capi/aws: don't use S3 stub for masters

---

pkg/asset/machines/gcp/gcpmachines.go

Add the network tags to the control plane machines

OCPBUGS-34915: Add network tags to capg control plane machines

---

pkg/infrastructure/aws/clusterapi/aws.go

Otherwise we might silently ignore the AWS destroy hook and not realize it.
Fallout from https://github.com/openshift/installer/pull/8359

OCPBUGS-35038: capi/aws: add BootstrapDestroyer guard

---

pkg/asset/cluster/tfvars/tfvars.go

This is updating the fix introduced in https://github.com/openshift/installer/pull/8226.
Based on https://docs.openshift.com/container-platform/4.13/installing/installing_gcp/installing-gcp-three-node.html, compact clusters on GCP are actually supported so the fix has been updated to disallow only incorrect states that we may end up in with incorrect manipulation of generated assets as detailed in the big.
Also, limiting the fix to just the GCP platform.

OCPBUGS-35099: OCPBUGS-4466: Prevent cluster installation with mismatched worker assets and worker replicas

---

pkg/infrastructure/aws/clusterapi/aws.go
pkg/infrastructure/azure/azure.go
pkg/infrastructure/clusterapi/clusterapi.go
pkg/infrastructure/clusterapi/types.go
pkg/infrastructure/gcp/clusterapi/clusterapi.go
pkg/infrastructure/ibmcloud/clusterapi/clusterapi.go
pkg/infrastructure/nutanix/clusterapi/clusterapi.go
pkg/infrastructure/openstack/clusterapi/clusterapi.go
pkg/infrastructure/powervs/clusterapi/powervs.go
pkg/infrastructure/vsphere/clusterapi/clusterapi.go

Often in CI, the capi installer is failing to gather the bootstrap log bundle (see [0] & [1] below) with the error:
```
level=error msg=Attempted to gather debug logs after installation failure: must provide bootstrap host address 
```
This is due to a race condition where we might write the manifests to disk before the ip address is present in the status. This PR updates the logic when waiting for machines  to be ready, first it ensures we check all machines, not just masters (we were skipping bootstrap unintentionally). It also adds a requirement that IP addresses are present in the status before moving on.
[0] https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-installer-8427-ci-4.17-e2e-aws-ovn/1792972823245885440
[1] …

OCPBUGS-34295: wait for ip addresses to be present on machines

---

data/data/install.openshift.io_installconfigs.yaml
pkg/types/gcp/machinepools.go
pkg/types/gcp/validation/machinepool.go
pkg/types/gcp/validation/machinepool_test.go

** The OnHostMaintenance and ConfidentialCompute values were not validated. 
** The OnHostMaintenance value should be set to Terminate when ConfidentialCompute is Enabled, otherwise the value can be Terminate or Migrate.
** Added default values to the MachinePool for both fields.

OCPBUGS-34416: Validate OnHostMaintenance and ConfidentialCompute

---

hack/go-lint.sh

We are using golangci-lint v1.59.0 in CI, so let's match that in local dev. That version is needed for Golang 1.22 support.
This is a fallout of https://github.com/openshift/installer/pull/8473.

no-jira: hack: bump golangci-lint version

---

hack/build-cluster-api.sh
images/baremetal/Dockerfile.ci
images/installer-altinfra/Dockerfile.ci
images/installer-artifacts/Dockerfile.rhel
images/installer/Dockerfile.ci
images/installer/Dockerfile.upi.ci
images/libvirt/Dockerfile.ci
images/openstack/Dockerfile.ci

We are using 1.30 in CI/release [1], so let's try to match that for local dev.
[1] https://github.com/openshift/kubernetes/pull/1942

OCPBUGS-34456: bump envtest binaries version

---

images/libvirt/Dockerfile.ci
images/libvirt/google-cloud-sdk.repo

Centos Stream 8 is EOL as of 31 May 2024.

OCPBUGS-35059: images: change libvirt-installer base

---

pkg/clusterapi/system.go

Managed clusters might rely on the KUBECONFIG to reach their kube api server. Instead of using the env var and possibly causing issues, we can specify a custom kube config via cmdline argument for the capi controllers. That seems a more appropriate approach for an ephemeral kube API like the one spawned by envtest.

OCPBUGS-35041: capi: do not override KUBECONFIG

---

pkg/asset/machines/aws/machines.go

** Manifests were generated to work for both CAPI and Terraform installs. Now that CAPI is the base, the extra tags for security groups and subnets can be removed from awsmachines.

OCPBUGS-34713: AWS remove extra tags from awsmachines for security groups and subnets

---

pkg/asset/ignition/bootstrap/gcp/storage.go
pkg/infrastructure/gcp/clusterapi/clusterapi.go

** Bootstrap ignition bucket and bucket objects were not cleaned up after bootstrap completion. Now the resources will be removed.

OCPBUGS-33681: Cleanup bootstrap resources for capg install

---

pkg/asset/cluster/cluster.go
pkg/clusterapi/localcontrolplane.go

This PR:
1. moves envtest kubeconfig from `<clusterdir>/auth/envtest.kubeconfig` to the hidden `<clusterdir>/.clusterapi_output/envtest.kubeconfig`
2. Prevents users from running `create cluster` repeatedly, unless they specify an envvar
Local testing.
After running `create cluster` then interrupting shortly after infrastructure provisioning begins, try running create cluster again:
```shell
[root@c5897d69ed85 /]# ./openshift-install create cluster --dir c
FATAL failed to fetch Cluster: failed to load asset "Cluster": local infrastructure provisioning artifacts already exist.  There may already be a running cluster 
```
If we specify `OPENSHIFT_INSTALL_REENTRANT` we can restart the install:
```shell
[root@c5897d69ed85 /]# OPENSHIFT_INSTALL_REENTRANT=true ./openshift-install create cluster …
```

OCPBUGS-35180: Prevent multiple invocations on CAPI

---

data/data/install.openshift.io_installconfigs.yaml
pkg/asset/cluster/tfvars/tfvars.go
pkg/asset/installconfig/platformpermscheck.go
pkg/asset/manifests/aws/cluster.go
pkg/explain/printer_test.go
pkg/types/aws/platform.go
pkg/types/conversion/installconfig.go

The name doesn't really reflect the purpose of the field, but the terraform implementation instead. Since the implementation has changed in capi/capa, let's rename it so users don't expect the ignition object to not be destroyed when there are enough permissions.
The old field is kept for the deprecation period but will be removed in the future in favor of the new `BestEffortDeleteIgnition`.

OCPBUGS-33661: capi/aws: rename `preserveBootstrapIgnition`

---

pkg/asset/installconfig/aws/permissions.go

The installer did not attach an S3 bootstrap bucket policy in the past, this new permission is required because of new functionality in CAPA.
CAPA is placing a policy that denies non SSL encrypted traffic to the bucket, this shouldn't have an effect on installs, adding the IAM policy to allow the policy to be added results in a successful install. 
S3 bootstrap bucket policy example:
```
"Statement": [
{
"Sid": "ForceSSLOnlyAccess",
"Principal": {
"AWS": [
"*"
]
},
"Effect": "Deny",
"Action": [
"s3:*"
],
"Resource": [
"arn:aws:s3:::openshift-bootstrap-data-jamesh-sts-2r5f7/*"
],
"Condition": {
"Bool": {
"aws:SecureTransport": false
}
}
}
]
```
See bug: https://issues.redhat.com/browse/OCPBUGS-35309

OCPBUGS-35309: Add S3 permission to allow attaching S3 bucket policy

---

pkg/asset/machines/aws/awsmachines.go
pkg/asset/machines/clusterapi.go

Ignition proxy should be configured for bootstrap only.

OCPBUGS-35197: capi/aws: do not set proxy for masters

---

pkg/asset/installconfig/aws/permissions.go

Installs with CAPA require a new AWS permission to set Security Groups on load balancers.  This is a new permission that wasn't required in 4.15 and below because we did not attach Security Groups to API server load balancers. 
See https://issues.redhat.com/browse/OCPBUGS-35293

OCPBUGS-35293: Add ELB V2 permission to set security groups on API server load balancer

---

pkg/asset/manifests/aws/cluster.go
pkg/infrastructure/aws/clusterapi/aws.go
pkg/infrastructure/clusterapi/clusterapi.go
pkg/infrastructure/clusterapi/types.go

This change adds a platform-specific post-destroy hook to the cluster-api infra.
For some platforms, it might be necessary to execute destroy tasks _after_ the cluster-api system has stopped so that it won't try to reconcile the changes.
This commits adds a post-destroy hook that runs during the bootstrap  destroy process but after cluster-api has shutdown.
It then leverage the post-destroy hook to delete the S3 ignition bucket after the cluster-api system has stopped running.
Because of the `BestEffortDeleteIgnition` option, we need to save its value to the provider while the cluster-api system is still running during the bootstrap destroy process. While not ideal, this solution offers the least impact to consumers of the Installer code as opposed to saving that value into the metadata.

OCPBUGS-35037: aws: delete ignition bucket on bootstrap destroy

---

pkg/asset/machines/vsphere/capimachines.go

Prior to the capi implementation for vSphere
there was no selector of network path based on
resource pools. This addition has changed
the requirement of the resource pool existing
prior to installation. To maintain backward
compat add a selector base on the cluster name.

OCPBUGS-34618: vsphere - allow network selection on cluster name

---

cmd/openshift-install/destroy.go
pkg/clusterapi/localcontrolplane.go
pkg/clusterapi/system.go
pkg/infrastructure/aws/clusterapi/aws.go
pkg/infrastructure/clusterapi/clusterapi.go

The standalone `openshift-install destroy bootstrap` command is failing because the etcd data directory is being removed whenever we call `Teardown`. This moves the etcd data dir to its own directory. This may create its own problem, though, as the etcd data can be sizable. In my testing it was over 60M:
```
[root@bc12788343a4 /]# du -sh c/etcd
67M	c/etcd
```
So we may want to either stick the etcd data in a /tmp dir or explicitly delete this once bootstrap destroy is complete.

OCPBUGS-33745: save etcd data to its own directory

---

pkg/clusterapi/system.go

Otherwise CAPA will apply tags to BYO subnets.

OCPBUGS-35467: capi/aws: disable CAPA's TagUnmanagedNetworkResources feature gate

---

pkg/asset/machines/aws/awsmachines.go
pkg/asset/machines/clusterapi.go
pkg/asset/manifests/aws/cluster.go

[SPLAT-1437](https://issues.redhat.com/browse/SPLAT-1437)
This PR introduces the support of "BYO IPv4" on CAPA, where it intents to allocate Public IPv4 Address from a custom user-provided Pool for all infra resources created by installer: Nat Gateways, NLBs and Bootstrap node - when using the "External" deployment.
References:
- Terraform support on installer: https://github.com/openshift/installer/pull/7983
- Upstream/CAPA feature support: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4905

SPLAT-1437: CAPI/AWS/BYOIP: supporting Public IPv4 Pool

---

cmd/openshift-install/main.go
data/data/install.openshift.io_installconfigs.yaml
pkg/asset/cluster/vsphere/vsphere.go
pkg/asset/machines/vsphere/capimachines.go
pkg/asset/manifests/aws/cluster.go
pkg/asset/manifests/azure/cluster.go
pkg/asset/manifests/capiutils/manifest.go
pkg/asset/manifests/cloudproviderconfig.go
pkg/asset/manifests/clusterapi/cluster.go
pkg/asset/manifests/gcp/cluster.go
pkg/asset/manifests/nutanix/cluster.go
pkg/asset/manifests/openstack/cluster.go
pkg/asset/manifests/powervs/cluster.go
pkg/asset/manifests/vsphere/cloudproviderconfig.go
pkg/asset/manifests/vsphere/cloudproviderconfig_test.go
pkg/asset/manifests/vsphere/cluster.go
pkg/destroy/vsphere/vsphere.go
pkg/destroy/vsphere/vsphere_test.go
pkg/infrastructure/clusterapi/clusterapi.go
pkg/types/validation/featuregate_test.go
pkg/types/validation/installconfig_test.go
pkg/types/vsphere/metadata.go
pkg/types/vsphere/platform.go
pkg/types/vsphere/validation/featuregates.go
pkg/types/vsphere/validation/platform.go
pkg/types/vsphere/validation/platform_test.go

[SPLAT-1553](https://issues.redhat.com/browse/SPLAT-1553)
- Added logic to create VM components on multiple vCenters
- https://github.com/openshift/api/pull/1842

SPLAT-1553: Added multi vCenter support for capi installer.

---

pkg/asset/machines/gcp/gcpmachines.go

CAPG has a kubebuilder validation for kmsKeyServiceAccount https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/api/v1beta1/gcpmachine_types.go#L207 that is failing when the string is empty (no value is set). This field should only be configured if the ServiceAccount it not empty.

OCPBUGS-35400: For GCP, only configure kmsKeyServiceAccount if set

---

pkg/asset/manifests/aws/cluster.go

This is in line with what was done with terraform/aws. The difference there is that we didn't create a security group for the NLB at all.
With CAPA, we need to allow ingress on 6443 for the NLB for private cluster installs for cases when, e.g., privateLink is used. Otherwise the installer won't be able to reach the kube API and the install will be deemed "failed".

OCPBUGS-35494: capi/aws: allow 6443 for private cluster NLB

---

pkg/infrastructure/openstack/preprovision/securitygroups.go

This prevented the creation of security groups for dualstack compact clusters.

OCPBUGS-35533: Fix ethertype for masters service router SG creation

---

pkg/infrastructure/clusterapi/clusterapi.go
pkg/infrastructure/clusterapi/types.go
pkg/infrastructure/powervs/clusterapi/powervs.go

Query the CAPI provider for the timeouts needed during provisioning.  This is optional to support.
The current default of 15 minutes is sufficient for normal CAPI installations.  However, given how the current PowerVS CAPI provider waits for some resources to be created before creating the load balancers, it is possible that the LBs will not create before the 15 minute timeout. An issue was created to track this [1].
[1] https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/1837

OCPBUGS-35430: Support CAPI provider custom timeouts

---

pkg/types/validation/installconfig.go
pkg/types/validation/installconfig_test.go

updated the validation logic to check for marketplace and olm to cover different capability sets beyond "none"

OCPBUGS-30025: fix: changed validation for olm and marketplace

---

cmd/openshift-install/main.go
data/data/install.openshift.io_installconfigs.yaml
pkg/asset/cluster/vsphere/vsphere.go
pkg/asset/machines/vsphere/capimachines.go
pkg/asset/manifests/aws/cluster.go
pkg/asset/manifests/azure/cluster.go
pkg/asset/manifests/capiutils/manifest.go
pkg/asset/manifests/cloudproviderconfig.go
pkg/asset/manifests/clusterapi/cluster.go
pkg/asset/manifests/gcp/cluster.go
pkg/asset/manifests/nutanix/cluster.go
pkg/asset/manifests/openstack/cluster.go
pkg/asset/manifests/powervs/cluster.go
pkg/asset/manifests/vsphere/cloudproviderconfig.go
pkg/asset/manifests/vsphere/cloudproviderconfig_test.go
pkg/asset/manifests/vsphere/cluster.go
pkg/destroy/vsphere/vsphere.go
pkg/destroy/vsphere/vsphere_test.go
pkg/infrastructure/clusterapi/clusterapi.go
pkg/types/validation/featuregate_test.go
pkg/types/validation/installconfig_test.go
pkg/types/vsphere/metadata.go
pkg/types/vsphere/platform.go
pkg/types/vsphere/validation/featuregates.go
pkg/types/vsphere/validation/platform.go
pkg/types/vsphere/validation/platform_test.go

Reverts #8221 ; tracked by https://issues.redhat.com/browse/OCPBUGS-35766
Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.
Investigating VSphere TechPreview Install Failures
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:
```
/payload-job periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-techpreview
```
CC: @vr4manta
<div align="right">
PR created by <a …

Revert #8221 "SPLAT-1553: Added multi vCenter support for capi installer."

---

images/installer/Dockerfile.upi.ci

* remove terraform and terraform provider binaries: they are leftover from before the time we started building or own
binaries.
* remove alibaba cli: the provider support has been removed.

no-jira: images: upi-installer image cleanup

---

docs/user/gcp/customization.md

Fix examples that didn't conform to the install-config specs.

OCPBUGS-31275: gcp: Validate install-config examples

---

pkg/asset/installconfig/ibmcloud/client.go
pkg/asset/installconfig/ibmcloud/metadata.go

Ignore failures encountered when attempting to check VPC regions for resources. Simply log a warning message and move on, letting such checks fail eventually if the requested resources was in one such failed region.
Related: https://issues.redhat.com/browse/OCPBUGS-14963

OCPBUGS-14963: IBMCloud: Ignore failed VPC regions

---

pkg/asset/installconfig/azure/validation.go
pkg/asset/machines/azure/azuremachines.go
pkg/clusterapi/system.go
pkg/infrastructure/azure/azure.go

Adding option to skip the image upload from the installer if an environment variable is set since it takes a lot of time and the marketplace images can be used to skip this step.

CORS-3434: azure: Skip image upload if env var is set

---

pkg/clusterapi/system.go

This feature gate was set to a default of true upstream via https://github.com/kubernetes-sigs/cluster-api/pull/10141. Setting it to false locally. Will enable this feature gate at a later time.

CORS-3562: azure: Setting experimental MachinePool featuregate to false

---

cmd/openshift-install/main.go

OCPBUGS-35547
- Set logger for controller-runtime package to prevent error output pertaining to:
`[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed`

OCPBUGS-35547: Configured logger for controller-runtime

---

pkg/asset/installconfig/powervs/client.go
pkg/asset/installconfig/powervs/metadata.go
pkg/asset/installconfig/powervs/mock/powervsclient_generated.go
pkg/asset/manifests/powervs/cluster.go

Currently the installer will not add your VPC as a permitted network for private DNS. Adding this ability to the installer will make using private DNS easier.

OCPBUGS-34978: Power VS: Ensure that VPC has prerequesite resources for private

---

pkg/asset/installconfig/openstack/validation/cloudinfo.go
pkg/asset/installconfig/openstack/validation/machinepool.go

Add a pre-flight check that verifies that the networks listed in the machine-pool property `additionalNetworkIDs` actually exist on the cloud.
Add a pre-flight check that verifies that the security groups listed in the machine-pool property `additionalSecurityGroupIDs` actually exist on the cloud.
Implements [OSASINFRA-1962](https://issues.redhat.com//browse/OSASINFRA-1962)

OCPBUGS-35420: OSASINFRA-1962: openstack: Validate additionalNetworkIDs and additionalSecurityGroupIDs

---

cmd/openshift-install/testdata/agent/pxe/configurations/sno_s390x.txt
go.mod
go.sum
pkg/asset/agent/image/agentpxefiles.go
vendor/github.com/openshift/assisted-image-service/pkg/isoeditor/initrd_addrsize.go
vendor/modules.txt

This PR is adding the LPAR support (s390x) for agend-based installer and bump the version dependencies.
For LPAR support two additional files are needed: ins-file (generic.ins) and initrd.addrsize. Both files are generated for s390x only.
How was this PR tested:
- Build locally ("/hack/build.sh")
- create install-config.yaml and agent-config.yaml (use iPXE script)
- Create installer files (new files are created)
`-rw-r--r--. 1 root root       149 Jun  7 17:48 agent.s390x-generic.ins`
`-rw-r--r--. 1 root root        16 Jun  7 17:48 agent.s390x-initrd.addrsize`

MULTIARCH-4515: Add new files for agent-based installer (LPAR support for s390x)

---

pkg/infrastructure/clusterapi/clusterapi.go

If OPENSHIFT_INSTALL_PRESERVE_BOOTSTRAP is set, we need to make sure the local controlplane shutdown happens as the last step in the defer stack chain, so previous steps that need to access it don't fail.
```
06-20 15:26:51.219  level=warning msg=OPENSHIFT_INSTALL_PRESERVE_BOOTSTRAP is set, shutting down local control plane.
06-20 15:26:51.219  level=info msg=Shutting down local Cluster API control plane...
06-20 15:26:51.473  level=info msg=Stopped controller: Cluster API
06-20 15:26:51.473  level=info msg=Stopped controller: aws infrastructure provider
06-20 15:26:52.830  level=info msg=Local Cluster API system has completed operations
06-20 15:26:52.830  level=debug msg=Collecting applied cluster api manifests...
06-20 15:26:52.831  level=error msg=failed to fetch Cluster: failed to …
```

OCPBUGS-35852: capi: shutdown local controlplane as the last step

---

pkg/asset/machines/gcp/gcpmachines.go

** On default use the RHCOS image, but when the user adds the osimage field to the install config, use the image information for control plane and bootstrap nodes.

OCPBUGS-35382: CAPG marketplace image use for control plane nodes

---

docs/dev/libvirt/README.md

We are not supporting installing on platform 'libvirt' starting 4.16. Updating in-repo documenattion to reflect that.

no-jira: Update documentation on libvirt installs for devs

---

hack/build-cluster-api.sh
images/baremetal/Dockerfile.ci
images/installer-altinfra/Dockerfile.ci
images/installer-artifacts/Dockerfile.rhel
images/installer/Dockerfile.ci
images/installer/Dockerfile.upi.ci
images/libvirt/Dockerfile.ci
images/openstack/Dockerfile.ci

We are using 1.29.5 in CI/release [1], so let's try to match that for local dev. The closest version available in kubebuilder-tools is 1.29.3.
[1] https://github.com/openshift/kubernetes/pull/1972

OCPBUGS-34457: [release-4.16] bump envtest binaries version

---

pkg/asset/installconfig/powervs/client.go

An IBM Cloud DNS zone does not go into "Active" state unless a permitted network is added to it and so if we try to use a DNS Zone which does not have a VPC attached as a permitted network, the installer fails with the error "failed to get DNS Zone id" when such a zone is attempted to be used. We already have code to attach a permitted network to a DNS Zone, but it cannot be used unless the DNS Zone is in "Active" state. The zone does not even show up in the install-config survey

OCPBUGS-36316: Power VS: Allow pending network for internal publishing strategy

---

data/data/coreos/rhcos.json

These changes will update the RHCOS 4.17 boot image metadata from 4.16. Notable changes in the bootimage are:
OCPBUGS-35410 - Resizing LUKS on 512e disk causes ignition-ostree-growfs
to fail with "Device size is not aligned to requested sector size."
```
--distro rhcos --no-signatures --name 4.17-9.4                   \
x86_64=417.94.202407010929-0                                      \
aarch64=417.94.202407010929-0                                     \
s390x=417.94.202407010929-0                                       \
ppc64le=417.94.202407010929-0
```

OCPBUGS-36318: update RHCOS 4.17 bootimage metadata to 417.94.202407010929-0

---

go.mod
go.sum
vendor/modules.txt

This is a no-op change as the `v2.0.0` tag was cut from the same commit as `v2.0.0-rc.3`.

OSASINFRA-3402: Use Gophercloud v2.0.0

---

data/data/agent/systemd/units/agent-import-cluster.service.template
pkg/asset/agent/image/ignition.go
pkg/asset/agent/joiner/clusterinfo.go
pkg/asset/agent/joiner/clusterinfo_test.go

This patch allows using the secure port, if configured, in the target cluster when adding a new node. The information are stored in the agent ISO, to be consumed by the agent-installer-client during the cluster import step.
Required by https://github.com/openshift/assisted-service/pull/6464

AGENT-925: retrieve ignition endpoint to add a new node

---

images/installer/Dockerfile.upi.ci

Now that PowerVS uses the upi-installer image, it is encountering the following error:
```
mkdir: cannot create directory '/output/.ssh': Permission denied
cp: cannot create regular file '/output/.ssh/': Not a directory
```

OCPBUGS-36453: PowerVS: add .ssh directory

---

images/installer/Dockerfile.upi.ci

installs image which is mirrored and build based on:
- https://github.com/openshift-splat-team/pwsh
- https://quay.io/repository/ocp-splat/pwsh

SPLAT-1670: install pwsh from ci mirrored image

---

data/data/agent/files/usr/local/bin/add-node.sh
data/data/agent/files/usr/local/bin/common.sh
data/data/agent/files/usr/local/bin/start-cluster-installation.sh
data/data/agent/files/usr/local/bin/wait-for-assisted-service.sh
data/data/agent/files/usr/local/share/assisted-service/assisted-service.env.template
data/data/agent/systemd/units/agent-register-cluster.service.template
data/data/agent/systemd/units/agent-register-infraenv.service.template
data/data/agent/systemd/units/apply-host-config.service
pkg/asset/agent/image/ignition.go
pkg/asset/agent/image/ignition_test.go

- Set JWT token in the expected env var AGENT_AUTH_TOKEN as needed by assisted service
- Set authorization header in the API requests
- Pass AGENT_AUTH_TOKEN env var to required systemd services

AGENT-876: Authenticate systemd services and curl requests

---

data/data/manifests/bootkube/cvo-overrides.yaml.template

a reoccurring issue, reported by me in the past in OCPBUGS-889, and by @shellyyang1989 in OCPBUGS-26511   
while branching to the next release, default channel must be updated to match, otherwise it will be impossible for the cluster to search for updates in the update graph, unless corrected manually. 
this PR updates the channel of the current master, from which 4.17.0-ec.x builds are currently delivered.
/cc @gpei @r4f4 
for review. thanks!

OCPBUGS-36660: CORS-3591: 4.17 default channel incorrectly points to stable-4.16

---

data/data/coreos/rhcos.json

OCPBUGS-36147 - Resizing LUKS on 512e disk causes ignition-ostree-growfs
to fail with "Device size is not aligned to requested sector size."
```
x86_64=416.94.202406282145-0                                      \
aarch64=416.94.202406282145-0                                     \
s390x=416.94.202406282145-0                                       \
ppc64le=416.94.202406282145-0
```

OCPBUGS-36324: update RHCOS 4.16 bootimage metadata to 416.94.202406282145-0

---

data/data/agent/files/usr/local/bin/start-agent.sh
pkg/asset/agent/image/ignition.go
pkg/asset/agent/image/ignition_test.go

- Set JWT token in the expected env var AGENT_AUTH_TOKEN
- Set authorization header in the API requests

AGENT-875: Authenticate agents

---

cmd/openshift-install/destroy.go

** The .cluster_api directory and the auth directory contain extra artifacts that should be removed on cluster destroy.

OCPBUGS-35542: Cleanup capi artifacts

---

pkg/infrastructure/azure/azure.go

Fixing HyperVGeneration version for gen 2 images.

OCPBUGS-36142: azure: Fix HyperVGeneration for gen2 images.

---

pkg/infrastructure/gcp/clusterapi/firewallrules.go

** When the "compute.firewalls.create" permission is missing, do not fail. Instead, skip the creation of firewall rules during xpn installs with capg.

OCPBUGS-35262: Skip firewall rule creation if permission is missing

---

cmd/openshift-install/version.go
pkg/version/version.go

In parallel with: https://github.com/openshift/oc/pull/1792

MULTIARCH-4568: Print release image arch and default arch when the payload is multi

---

docs/user/openstack/install_upi.md
upi/openstack/bootstrap.yaml
upi/openstack/common.yaml
upi/openstack/compute-nodes.yaml
upi/openstack/control-plane.yaml
upi/openstack/inventory.yaml
upi/openstack/network.yaml
upi/openstack/security-groups.yaml
upi/openstack/update-network-resources.yaml

We experienced issues caused by network resources created with the same name, which makes ansible playbooks to behave differently.
Due to fact, that there is not yet OpenShift infraID accessible on the stage of creating network resources, there is a need to create deployment unique identifier in some other way. This patch implements generating such identifier independent from OpenShift deployment id.

OCPBUGS-33973: Openstack UPI - Reintroduce unique resource names.

---

pkg/clusterapi/system.go
pkg/infrastructure/clusterapi/clusterapi.go

This PR introduces 2 changes to fix capi binaries running after the openshift-installer exits in case of failures:
1. [do not exit if controller fails to extract.](https://github.com/openshift/installer/commit/2e34347dfe43e1eb0e7eb60f39185c4d37229e62): doing `logrus.Fatal` when a controller fails to be extracted means that we abort the installer process without giving it a chance to stop the capi-related processes that are still running.
2. [capi: start controllers after WaitGroup is created](https://github.com/openshift/installer/commit/b8df7d43770d95d4b67486219649d8cdd10c7bea): so the installer has a chance to stop controllers that are already running.

OCPBUGS-36378: capi: start controllers after WaitGroup is created

---

OWNERS_ALIASES
cmd/openshift-install/imagebased.go
cmd/openshift-install/main.go
cmd/openshift-install/testdata/imagebased/OWNERS
data/data/imagebased/OWNERS
pkg/asset/imagebased/OWNERS
pkg/types/imagebased/OWNERS

This PR adds the image-based installer (IBI) skeleton folders and {,sub}commands, as well as the respective owner aliases and `OWNERS`.
For a detailed description of this feature please see the respective enhancement: https://github.com/openshift/enhancements/blob/master/enhancements/installer/image-based-installer.md.
@zaneb @patrickdillon @eranco74

MGMT-17226: Add imagebased installer skeleton

---

pkg/asset/manifests/gcp/cluster.go

** Subnets were only using the network project ID when that was missing it would fail to find the correct subnets.

OCPBUGS-36713: CAPG use existing subnets and VPC

---

pkg/destroy/gcp/instance.go

Instance types for which `OnHostMaintenance` is set to `Terminate`, GCP requires the `DiscardLocalSsd` value to be defined, otherwise we get the following error when destroying a cluster:
```
WARNING failed to stop instance jiwei-0530b-q9t8w-worker-c-ck6s8 in zone us-central1-c: googleapi: Error 400: VM has a Local SSD attached but an undefined value for `discard-local-ssd`. If using gcloud, please add `--discard-local-ssd=false` or `--discard-local-ssd=true` to your command., badRequest
```
We are setting the value to `true` because we are about to destroy the cluster, which means destroying the instances and all cluster-owned resources.

OCPBUGS-34638: destroy/gcp: set value for DiscardLocalSsd

---

images/installer/Dockerfile.upi.ci

While new steps are being implemented in Prow, users may want to pivot to yq-v4. This commit installs yq-v4 in the upi-installer image.
Moreover, by copying the yq-v3 and yq-v4 binaries from previous stages based on manifest-list images, we guarantee the yq binaries are the ones for the architecture of the upi image being built.

OCPBUGS-36748: Add yq-v4 to the upi-installer image for CI

---

pkg/asset/manifests/powervs/cluster.go

When doing a disconnected deploy we'll need to disable SNAT

OCPBUGS-37107: Power VS: Disable SNAT when specifying imageContentSources

---

pkg/asset/imagebased/image/ignition.go
pkg/asset/imagebased/image/registriesconf.go

This PR fixes the `openshift-install image-based create image --dir assets` command panicking when there is no `image-based-installation-config.yaml` supplied.
/cc @eranco74 @tsorya

OCPBUGS-37164: Handle empty config for image-based create image

---

data/data/coreos/rhcos.json

These changes will update the RHCOS 4.15 boot image metadata. Notable fixes are:
OCPBUGS-36815 - ISO image boot of OpenShift 4.14 causes kernel panic during SNO cluster installation on the QuantaEdge EGX77B-1U server
```
x86_64=415.92.202407091355-0                                      \
aarch64=415.92.202407091355-0                                     \
s390x=415.92.202407091355-0                                       \
ppc64le=415.92.202407091355-0
```

OCPBUGS-37067: update RHCOS 4.15 bootimage metadata to 415.92.202407091355-0

---

pkg/types/openstack/validation/platform.go
pkg/types/openstack/validation/platform_test.go

Reject a controlPlanePort where the subnet filter is not set.
The rest of the code (both in pre-flight validation and in machine generation) assumes that a subnet filter is set on the controlPlanePort.

OCPBUGS-37104: openstack: Validate controlPlanePort has subnet

---

pkg/asset/cluster/openstack/openstack.go
pkg/asset/cluster/tfvars/tfvars.go
pkg/asset/ignition/bootstrap/common.go
pkg/asset/machines/clusterapi.go
pkg/asset/machines/master.go
pkg/asset/machines/master_test.go
pkg/asset/machines/worker.go
pkg/asset/machines/worker_test.go
pkg/asset/manifests/clusterapi/cluster.go
pkg/asset/manifests/openshift.go
pkg/asset/rhcos/bootstrap_image.go
pkg/asset/rhcos/image.go
pkg/infrastructure/aws/clusterapi/ami.go
pkg/infrastructure/nutanix/clusterapi/clusterapi.go
pkg/infrastructure/openstack/clusterapi/clusterapi.go
pkg/infrastructure/vsphere/clusterapi/clusterapi.go
pkg/types/installconfig.go
pkg/types/validation/installconfig.go
pkg/types/validation/installconfig_test.go

This PR adds support for multi-arch nodes (amd64 controlPlane and arm64 compute, or vice-versa). To accomplish that we:
1. Add a new feature gate to enable the feature: `MultiArchInstallAWS`
2. Add support for multi-arch RHCOS images in the Image asset.
3. Make sure compute nodes use their own architecture for RHCOS image and instance type.
/hold
Depends on:

MULTIARCH-4569: aws: support multi-arch nodes

---

pkg/asset/manifests/azure/cluster.go
pkg/infrastructure/azure/azure.go
pkg/infrastructure/azure/network.go

When user defined routing is configured, don't create an outbound load
balancer with outbound rules. Since a public load balancer isn't being
created, we create one for public API access.
https://issues.redhat.com/browse/CORS-3569

CORS-3569: UDR for Capz

---

data/unpack_test.go
pkg/asset/installconfig/platformprovisioncheck.go
pkg/asset/machines/master.go
pkg/asset/machines/worker.go
pkg/types/baremetal/validation/platform.go
pkg/types/baremetal/validation/platform_test.go
pkg/types/installconfig.go
pkg/types/validation/installconfig.go
pkg/types/validation/installconfig_test.go

There are use cases for using the baremetal platform while disabling MAPI (for example to use CAPI).
The installer will skip rendering BMH, Machine and MachineSet CRs in case MAPI is disabled
This also removes the validation preventing this configuration to allow users to `create ignition-configs`.
The validations still apply for the `create cluster` target
Fixes [METAL-1039](https://issues.redhat.com//browse/METAL-1039)

METAL-1039: Allow baremetal platform without MAPI

---

pkg/asset/agent/joiner/addnodesconfig.go
pkg/asset/agent/joiner/clusterinfo.go
pkg/asset/agent/joiner/clusterinfo_test.go

Allow the CPU architecture to be specified in nodes-config.yaml.

AGENT-910: node-joiner multi-arch support

---

pkg/asset/ignition/bootstrap/common.go

#4756 used the apiVIPs to decide whether to make the bootstrap kubelet be prefer-ipv4 or prefer-ipv6, but that won't work if the apiVIPs aren't specified. The validation already ensures that all of the fields that _are_ specified agree about the primary IP family, so we can just switch to using one of the required config values instead of an optional one.
/cc @celebdor @staebler

OCPBUGS-35406: Use service CIDRs to determine bootstrap kubelet IP family

---

pkg/asset/cluster/tfvars/tfvars.go
pkg/types/installconfig.go
pkg/types/validation/installconfig_test.go

This PR adds support for multi-arch nodes in GCP (amd64 controlPlane and arm64 compute, or vice-versa).
/hold
Depends on:

MULTIARCH-4777: gcp: support multi-arch nodes 

---

docs/user/azure/customization.md

Our in-repo docs indicate that the installer will not create security groups, but that is inaccurate. The official docs are correct:
https://docs.openshift.com/container-platform/4.15/installing/installing_azure/installing-azure-vnet.html
This commit updates the in-repo docs to match the official docs.
I am not creating a bug for this, as the official docs are already correct.

no-jira: docs/user/azure: fix byo vnet security groups

---

cmd/openshift-install/integration_test.go
cmd/openshift-install/internal_integration_test.go
cmd/openshift-install/testdata/imagebased/configimage/assets/default_assets.txt
cmd/openshift-install/testdata/imagebased/configtemplate/config-template.txt

This PR adds integration tests via [testscript](https://pkg.go.dev/github.com/rogpeppe/go-internal/testscript) (much like the respective `agent` integration tests) for the `openshift-install image-based {config-image,config-template}` subcommands. It also renames the integration tests source files to better reflect the fact that the latter now include tests additional to `agent` ones.

MGMT-18364: Add image-based config ISO integration tests

---

data/data/coreos/rhcos.json

These changes will update the RHCOS 4.14 boot image metadata. Notable fixes are:
OCPBUGS-36815 - ISO image boot of OpenShift 4.14 causes kernel panic during SNO cluster installation on the QuantaEdge EGX77B-1U server
```
x86_64=414.92.202407091253-0                                      \
aarch64=414.92.202407091253-0                                     \
s390x=414.92.202407091253-0                                       \
ppc64le=414.92.202407091253-0
```

OCPBUGS-37068: update RHCOS 4.14 bootimage metadata to 414.92.202407091253-0

---

pkg/asset/imagebased/configimage/configiso.go
pkg/asset/imagebased/configimage/imagebased_config.go
pkg/asset/imagebased/image/ignition.go
pkg/asset/imagebased/image/image.go
pkg/asset/imagebased/image/imagebased_config.go

This PR enhances the user experience of the `openshift-install image-based create {image-config,config}-template --dir assets` commands, by not emptying the respective `image-based-installation-config.yaml` and `image-based-config.yaml` when the afore-mentioned commands are run twice.
Although this doesn't impact the respective ISO generation, as the config manifests seem to be empty but kept in the openshift-install state, i.e. trying to generate the ISOs will work as expected.

OCPBUGS-37226: Persist image-based config manifests from state instead of template

---

pkg/asset/imagebased/configimage/imagebased_config_test.go
pkg/asset/imagebased/image/imagebased_config_test.go

This PR replaces `assert.Equal` with `assert.ErrorContains` for the `image-based` tests that require `nmstatectl`. This fixes the respective broken unit tests because of an `nmstatectl` version update, which changed the error message we were relying on absolute instead of partial matching.
Example of such broken unit tests: [https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_inst[…]ull-ci-openshift-installer-master-unit/1815798740611502080](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_installer/8235/pull-ci-openshift-installer-master-unit/1815798740611502080)

no-jira: Replace Equal with ErrorContains for image-based nmstatectl unit tests

---

pkg/agent/kube.go
pkg/agent/ocp.go

Remove the "Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work." warning because it does work and would confuse the user when the monitor-add-nodes command is run in cluster.

AGENT-922: Remove misleading inClusterConfig warning

---

pkg/asset/cluster/aws/aws.go
pkg/asset/installconfig/aws/permissions.go
pkg/asset/installconfig/aws/permissions_test.go
pkg/asset/installconfig/platformpermscheck.go

The Installer is unconditionally requiring permissions needed to create IAM roles even when the users use existing roles. They should be included only when needed.
This PR kind of reverts https://github.com/openshift/installer/pull/5286. IAM roles created by the Installer are now consistently tagged with "owned". We should also tag BYO roles so we know which clusters are using them, and so that it's
not deleted by the installer during cluster destroy.

OCPBUGS-36390: aws: do not require create permissions when BYO IAM role 

---

pkg/types/validation/installconfig.go

The field name is ImageDigestSources.

OCPBUGS-36780: ic: fix typo in warning message

---

pkg/asset/manifests/azure/cluster.go

Setting the ID on the Subnet disables natgw creation. See: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/21479a9a4c640b43e0bef028487c522c55605d06/api/v1beta1/azurecluster_default.go#L160
Because the node subnet does not already exist, we are using an arbitrary value. We could populate this with the proper subnet ID in the case of BYO VNET, but the value currently has no practical effect.

CORS-3566: Azure CAPI: disable natgw by setting node subnet id

---

pkg/asset/machines/azure/azuremachines.go

The disk encryption set ID was getting set to nil before being passed to the bootstrap machine struct. Since the managed disk properties is a pointer, it was nil before the manifests were being written to disk.
https://issues.redhat.com/browse/OCPBUGS-36302

OCPBUGS-36302: pkg/asset/machines/azure: Don't set disk encryption set to nil

---

data/data/install.openshift.io_installconfigs.yaml
pkg/asset/machines/gcp/gcpmachines.go
pkg/asset/machines/gcp/gcpmachines_test.go
pkg/asset/machines/gcp/machines.go
pkg/infrastructure/gcp/clusterapi/clusterapi.go
pkg/types/gcp/machinepools.go
pkg/types/gcp/platform.go
pkg/types/gcp/validation/machinepool.go
pkg/types/validation/machinepools_test.go

Support the configuration of pre-created Service Accounts for control plane and compute machines.

CORS-3568: Support GCP pre-created Service Accounts for CAPG

---

hack/build-node-joiner.sh
pkg/asset/agent/image/kargs.go
pkg/asset/agent/image/kargs_test.go
pkg/asset/agent/joiner/clusterinfo.go
pkg/asset/agent/joiner/clusterinfo_test.go

If the target cluster had fips enabled, then it will be set also for the live ISO

AGENT-900: enable fips for add-nodes workflow

---

pkg/asset/agent/installconfig.go
pkg/asset/agent/joiner/clusterinfo.go
pkg/asset/agent/joiner/clusterinfo_test.go
pkg/asset/agent/manifests/nmstateconfig.go
pkg/asset/agent/manifests/nmstateconfig_test.go

This patch introduces a set of validations required when running the `ClusterInfo` asset as part of the day2 add-nodes workflow

AGENT-854: day2 add-nodes workflow validations

---

pkg/agent/cluster.go
pkg/agent/monitoraddnodes.go
pkg/agent/rest.go
pkg/nodejoiner/monitoraddnodes.go

Multiple IP addresses can now be specified for monitoring at the same time.

AGENT-862: Extend monitor-add-nodes to support multiple nodes

---

docs/user/gcp/install_upi.md
upi/gcp/02_lb_int.py

** Updated the UPI references in docs and scripts to use api-internal to the name to match those of the capg and terraform resources.

OCPBUGS-35366: Update upi references to api-internal

---

pkg/types/vsphere/validation/platform.go
pkg/types/vsphere/validation/platform_test.go

Since the regex strips the `/` from `datacenterName` the equality will never be true in the case of a datacenter that is contained in a folder. This PR replaces the equality with a strings.Contains.

OCPBUGS-37356: vSphere validation fails if dc is in a folder

---

pkg/infrastructure/clusterapi/clusterapi.go
pkg/infrastructure/clusterapi/helpers.go

The machine manifests from capi have multiple addresses including ipv4 and ipv6. In vSphere CI specifically ipv6 is non-routed and since that is the first address in the list is being used by default. This causes bootstrap gather failures.
This PR returns all available addresses from the machine manifest and for vSphere only prioritizes the IPv4 address.

OCPBUGS-37427: bootstrap gather fails in vsphere, only ipv6 address used

---

data/data/install.openshift.io_installconfigs.yaml
go.mod
go.sum
pkg/asset/installconfig/gcp/validation.go
pkg/asset/installconfig/gcp/validation_test.go
pkg/destroy/gcp/gcp.go
pkg/types/gcp/machinepools.go
pkg/types/gcp/validation/machinepool.go
pkg/types/gcp/validation/machinepool_test.go
vendor/modules.txt

** Update the version of the machine api so that the validation for the new gcp machine types are included.
** Update the enumeration for GCP disks to include hyperdisk-balanced.
** Update the allowed disk types of compute nodes for gcp. This will now include hyperdisk-balanced.

CORS-3580: Update GCP Disk Types

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
data/data/bootstrap/files/usr/local/bin/kubelet.sh.template

Just noticed this while hacking on the installer code; shellcheck has a `source=` directive that allows it to follow which file is being sourced in the git repo. This gets rid of one `disable` directive in the process.

no-jira: bootstrap: add shellcheck directives to follow sourced files

---

pkg/asset/machines/gcp/gcpmachines.go
pkg/asset/machines/gcp/gcpmachines_test.go
pkg/asset/manifests/gcp/cluster.go

Set the UserTags from install-config.yaml on the machine and cluster resources in CAPG.

CORS-3209: Set UserTags on CAPG resources

---

pkg/asset/machines/azure/azuremachines.go
pkg/asset/machines/clusterapi.go

Aligning the CAPI installs with terraform installs by setting Accelerated Network to true if no vmNetworkingType is set or vmNetworkingType is set to Accelerated.

OCPBUGS-35959: azure: Fix Accelerated network enablement

---

pkg/agent/monitoraddnodes.go

It was mistakenly changed to 1 minute.

AGENT-862: Change day-2 monitor timeout back to 90 minutes

---

pkg/asset/agent/joiner/addnodesconfig.go
pkg/asset/agent/joiner/addnodesconfig_test.go
pkg/asset/agent/joiner/clusterinfo.go
pkg/asset/agent/joiner/clusterinfo_test.go

This patch adds a new optional field for the nodes-config.yaml, so that the user will be able to configure the ssh key used fo adding the nodes (instead of reusing the one found in the cluster for the initial installation)

AGENT-928: allow user to specify sshKey via config file

---

pkg/gather/service/analyze.go
pkg/gather/service/analyze_test.go

Give a better error message when the gather logs are not collected rather than
```
time="2024-06-05T08:34:45-04:00" level=error msg="The bootstrap machine did not execute the release-image.service systemd unit"
```
The release-image service could have been executed but we don't know if the installer cannot connect to the bootstrap node (e.g, in a private install).

OCPBUGS-34953: fix bogus analyze message when gather fails

---

pkg/asset/machines/azure/azuremachines.go
pkg/asset/machines/clusterapi.go
pkg/asset/manifests/azure/cluster.go
pkg/infrastructure/azure/azure.go

No public endpoints are created. If the outbound type if load balancer, we still create a public load balancer with a public IP for egress.  I refactored GetMachines a bit while here. 
https://issues.redhat.com/browse/CORS-3565

CORS-3565: CAPZ private clusters

---

cmd/openshift-install/testdata/imagebased/image/assets/default_assets.txt
cmd/openshift-install/testdata/imagebased/image/validations/invalid-image-digest-sources.txt
cmd/openshift-install/testdata/imagebased/image/validations/invalid-proxy.txt
cmd/openshift-install/testdata/imagebased/image/validations/no-installation-disk.txt
cmd/openshift-install/testdata/imagebased/image/validations/no-pull-secret.txt
cmd/openshift-install/testdata/imagebased/image/validations/no-seed-image.txt
cmd/openshift-install/testdata/imagebased/image/validations/no-seed-version.txt
cmd/openshift-install/testdata/imagebased/imageconfigtemplate/image-config-template.txt

This PR adds [testscript](https://pkg.go.dev/github.com/rogpeppe/go-internal/testscript) integration tests for the `image-based` installer, specifically for the installation ISO and its configuration template creation.

MGMT-18364: add image-based installation ISO integration tests

---

pkg/asset/cluster/powervs/powervs.go
pkg/asset/installconfig/powervs/session.go
pkg/clusterapi/system.go
pkg/types/powervs/metadata.go

IBM Cloud CAPI would fail and abort if we pass in any service endpoint that's not supported. Therefore, we are adding extra logic before setting up the `--service-endpoint=` arg to CAPI so we can check what's supported and what's not supported, though we still let everything through to `metadata.json`.

MULTIARCH-4828: Pass ServiceEndpoints from install-config to CAPI for PowerVS

---

data/data/install.openshift.io_installconfigs.yaml
pkg/asset/cluster/aws/aws.go
pkg/asset/installconfig/aws/permissions.go
pkg/asset/installconfig/aws/permissions_test.go
pkg/asset/installconfig/aws/validation.go
pkg/asset/machines/aws/awsmachines.go
pkg/asset/machines/aws/machines.go
pkg/asset/machines/aws/machinesets.go
pkg/destroy/aws/ec2helpers.go
pkg/explain/printer_test.go
pkg/infrastructure/aws/clusterapi/iam.go
pkg/types/aws/machinepool.go

Allow a user to use an existing IAM instance profile while deploying  OpenShift on AWS.
This is important not only for self-managed customers who want to reduce the required permissions needed for IAM accounts but also for IC regions.
Depends on https://github.com/openshift/installer/pull/8688 for the BYO roles permission fixes.

CORS-3609: aws: support existing IAM instance profiles

---

data/data/agent/files/usr/local/share/assisted-service/assisted-service.env.template
pkg/asset/agent/gencrypto/authconfig.go
pkg/asset/agent/image/ignition.go
pkg/asset/agent/image/ignition_test.go

Enable the new auth type `agent-installer-local`

AGENT-870: Update AUTH_TYPE

---

data/data/agent/systemd/units/agent-register-cluster.service.template
data/data/agent/systemd/units/assisted-service.service.template
pkg/asset/agent/image/ignition.go
pkg/asset/agent/image/ignition_test.go

This patch ensures to generate a smaller user-ca-bundle configmap when the mirror config is provided, along with the additionalTrustBundle content
(cherry picked from commit ecd5df4bc1811905742c7249209e5ea1af0ac547)

[release-4.15] OCPBUGS-34721: fix usage of host and user CA bundle in the agent ignition

---

pkg/infrastructure/openstack/preprovision/securitygroups.go

Backport of https://github.com/openshift/installer/pull/8757
Before this patch, we used the Neutron call to add tags to the newly created security groups. However, that API doesn't accept tags containing special characters such as slash (`/`), even when url-encoded.
With this change, the security groups are tagged with an alternative API call (replace-all-tags) which accepts the tags in a JSON object. Apparently, Neutron accepts special characters (including slash) when they come in a JSON object.

OCPBUGS-37492: openstack: Fix security group tagging

---

pkg/asset/machines/aws/machinesets.go

Setting edge compute pool  must use the same IAM Profile as `worker` when a BYO IAM Profile isn't set.
Reference:
- [IAM Profile update](https://github.com/openshift/installer/pull/8689/files#diff-e46d61c55e5e276e3c264d18cba0346777fe3e662d0180a173001b8282af7c6eR51-R54)
- [CI failures](https://sippy.dptools.openshift.org/sippy-ng/jobs/Presubmits/analysis?filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22pull-ci-openshift-origin-master-e2e-aws-ovn-edge-zones%22%7D%5D%7D)
- [Sippy](https://sippy.dptools.openshift.org/sippy-ng/jobs/4.17/runs?filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-ovn-edge-zon …

OCPBUGS-38055: fix/aws/edge: IAM profile must be same of workers

---

data/data/install.openshift.io_installconfigs.yaml
pkg/asset/installconfig/nutanix/validation.go
pkg/asset/machines/clusterapi.go
pkg/asset/machines/master.go
pkg/asset/machines/nutanix/machines.go
pkg/asset/machines/worker.go
pkg/types/nutanix/helpers.go
pkg/types/nutanix/machinepool.go
pkg/types/nutanix/platform.go
pkg/types/nutanix/validation/machinepool.go
pkg/types/nutanix/validation/machinepool_test.go
pkg/types/nutanix/validation/platform.go

Add suport for the feature stories:
[OCPSTRAT-1314](https://issues.redhat.com//browse/OCPSTRAT-1314): Allow creating Nutanix worker VMs with GPUs
[OCPSTRAT-1394](https://issues.redhat.com//browse/OCPSTRAT-1394): Allow creating Nutanix VMs with multiple disks
The api changes are in https://github.com/openshift/api/pull/1935
I did the manual testing and passed.

CORS-3546: Nutanix: add gpus and dataDisks support

---

pkg/asset/agent/image/agentartifacts.go
pkg/asset/agent/image/agentimage.go
pkg/asset/agent/image/kargs.go
pkg/asset/agent/image/kargs_test.go

Defer to the implementation provided by assisted-image-service in
NewKargsReader(), so that we do not need to maintain any knowledge of
how kernel args are implemented in the installer.

AGENT-890: Simplify Agent ISO kargs setting

---

data/data/install.openshift.io_installconfigs.yaml
docs/user/aws/customization.md
pkg/asset/rhcos/image.go
pkg/explain/printer_test.go
pkg/types/aws/platform.go
pkg/types/conversion/installconfig.go
pkg/types/conversion/installconfig_test.go

This field was introduced [1] before the Installer had support for custom AMIs in machine pools [2]. Now that it does, the same functionality is achieved via the defaultMachinePlatform field `platform.aws.defaultMachinePlatform.amiID`
[1] fdf94e39ee0226b152b6739a0dad848a005a5c26
[2] bc4722257643dd0d643564c686ecd5ea421f947b

CORS-3608: aws: deprecate platform.aws.amiID field

---

pkg/asset/manifests/powervs/cluster.go

Disconnected with CAPI will not work in 4.17, error out explaining how to get a 4.17 disconnected cluster.

no-jira: PowerVS: Block disconnected deploys in 4.17

---

go.mod
go.sum
pkg/types/validation/installconfig_test.go
vendor/github.com/openshift/api/features/features.go
vendor/modules.txt

The MultiArchInstallAWS and MultiArchInstallGCP feature gates have been moved into the Default feature set.

MULTIARCH-4770: MULTIARCH-4776: bump o/api for MultiArchInstall FGs

---

data/data/install.openshift.io_installconfigs.yaml
pkg/asset/cluster/vsphere/vsphere.go
pkg/asset/machines/vsphere/capimachines.go
pkg/asset/manifests/aws/cluster.go
pkg/asset/manifests/azure/cluster.go
pkg/asset/manifests/capiutils/manifest.go
pkg/asset/manifests/cloudproviderconfig.go
pkg/asset/manifests/clusterapi/cluster.go
pkg/asset/manifests/gcp/cluster.go
pkg/asset/manifests/nutanix/cluster.go
pkg/asset/manifests/openstack/cluster.go
pkg/asset/manifests/powervs/cluster.go
pkg/asset/manifests/vsphere/cloudproviderconfig.go
pkg/asset/manifests/vsphere/cloudproviderconfig_test.go
pkg/asset/manifests/vsphere/cluster.go
pkg/destroy/vsphere/vsphere.go
pkg/destroy/vsphere/vsphere_test.go
pkg/infrastructure/clusterapi/clusterapi.go
pkg/types/validation/featuregate_test.go
pkg/types/validation/installconfig_test.go
pkg/types/vsphere/conversion/installconfig.go
pkg/types/vsphere/conversion/installconfig_test.go
pkg/types/vsphere/metadata.go
pkg/types/vsphere/platform.go
pkg/types/vsphere/validation/featuregates.go
pkg/types/vsphere/validation/platform.go
pkg/types/vsphere/validation/platform_test.go

Reverts openshift/installer#8630
Note 1:
Original PR was reverted due to existing yaml logic in the installer always setting the labels in the config.  This PR will revert the revert and fix the yaml config logic to no longer include labels if failure domain list is not greater than 1.
Note 2:
Due to the nature of how the TechPreview jobs are (TechPreview enables all feature gates), the VSphereMultiVCenters feature gate still has several PRs that need to merged to prevent any installation issues.
- https://github.com/openshift/vmware-vsphere-csi-driver-operator/pull/228
- https://github.com/openshift/vsphere-problem-detector/pull/158
The CSO was updated to allow multiple vCenters, but the vSphere CSI driver operator needs a config update to complete install.
This PR will stay in draft …

Revert "Revert #8221 "SPLAT-1553: Added multi vCenter support for capi installer.""

---

data/data/agent/files/usr/local/bin/agent-auth-token-status.sh
data/data/agent/systemd/units/agent-auth-token-status.service
pkg/asset/agent/gencrypto/authconfig.go
pkg/asset/agent/image/ignition.go
pkg/asset/agent/image/ignition_test.go

- Adds a new systemd service `agent-auth-token-status.service`.
- The new service checks if token is valid.
- If expired, display a message on the boot window. `The authentication token has expired. Please generate a new ISO using the "oc adm node-image create" command, then reboot the node.`
- This new service is only run on addnodes workflow i.e. adding a node on day2.
- This new service runs after the TUI and helps users know what corrective action ( re-generate ISO) to be taken.

AGENT-937: Check Authentication Token for Node Boot-Up on day2

---

pkg/infrastructure/aws/clusterapi/aws.go
pkg/infrastructure/azure/azure.go
pkg/infrastructure/clusterapi/clusterapi.go
pkg/infrastructure/clusterapi/types.go
pkg/infrastructure/gcp/clusterapi/clusterapi.go
pkg/infrastructure/ibmcloud/clusterapi/clusterapi.go
pkg/infrastructure/nutanix/clusterapi/clusterapi.go
pkg/infrastructure/openstack/clusterapi/clusterapi.go
pkg/infrastructure/powervs/clusterapi/powervs.go
pkg/infrastructure/vsphere/clusterapi/clusterapi.go

The Azure bootstrap node cannot have a public IP address, as
Azure does not allow a public IP when the VM is attached to a load
balancer with an outbound rule. Instead, CAPZ creates an inbound
nat rule to allow SSH access through the load balancer.
This PR encapsulates the logic for gathering the bootstrap
host address into its own function and adds a condition to use
the API LB hostname when the bootstrap node cannot have a public ip.

OCPBUGS-37540: Gather Azure Logs through load balancer

---

pkg/asset/ignition/bootstrap/gcp/storage.go
pkg/infrastructure/gcp/clusterapi/clusterapi.go

** removing the timeout for a client that is causing failures when we return from the
function that creates a signed url.
** Update the gcp cluster api reference to bucket creation that takes away the need for a client context.

OCPBUGS-37821: Remove timed context for gcp client

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

Populating the new option from openshift/cluster-version-operator#1078 with [the manifest we generate in `pkg/asset/manifests/featuregate.go`][1].  This allows the cluster-version operator to  render manifests appropriate to the configured feature set.
/hold until the CVO pull merges
[1]: https://github.com/openshift/installer/blob/fe126cafe857fa5e4e7f88a2134a19ae2f089b85/pkg/asset/manifests/featuregate.go#L17

OCPBUGS-37770: data/bootstrap/files/usr/local/bin/bootkube: Pass CVO render --feature-gate-manifest-path

---

data/data/agent/files/usr/local/share/assisted-service/assisted-service.env.template

Since the assisted-service API will be more difficult for users to access with the API authentication changes, enable debug logging so additional messages will be available in the assisted-service logs.

AGENT-944: Enable assisted-service debug logging

---

data/data/install.openshift.io_installconfigs.yaml
go.mod
go.sum
pkg/types/gcp/platform.go
pkg/types/validation/featuregate_test.go
vendor/github.com/openshift/api/features/features.go
vendor/modules.txt

Updated GCP userLabels and userTags configs description to indicate feature is enabled by default but still can be managed through `GCPLabelsTags` feature gate.

CFE-920: Update GCP userLabels and userTags configs description

---

pkg/asset/machines/gcp/machines.go

With CAPI, the control plane machines are expected to have two tags, one that is just the clusterID and one that is the clusterID suffixed with `-control-plane`. These tags are used in the network firewall rules to apply the correct rules to the instances. Without this, the existing tags cause the Machine to have no firewall rules and therefore cannot boot (can't even fetch ignition)

OCPBUGS-38241: Update control plane tags to match CAPI networks

---

pkg/asset/installconfig/aws/validation.go
pkg/asset/installconfig/aws/validation_test.go

When we enabled the multi-arch day0 feature via the MultiArchInstallAWS feature gate, we inadvertently allowed "worker" and "edge" compute machine pools to have different architectures.
This change introduces a validation to check all the compute pools use the same architecture and errors out otherwise.

OCPBUGS-37780: aws: do not allow edge pools of different arch

---

pkg/types/powervs/powervs_regions.go

Add system type e980 to the list of allowed system types for the Madrid region.

OCPBUGS-38436: PowerVS: Fix mad system pool

---

pkg/asset/machines/clusterapi.go
pkg/asset/manifests/aws/cluster.go
pkg/asset/manifests/aws/zones.go

We lost support to this internal feature when we move from terraform to CAPI. Although it's still possible to get a cluster with public-only subnets by editing the AWSCluster manifest before install, it's more convenient to have a fully automated process to be used in CI.

OCPBUGS-38114:  aws: add support for clusters with public-only subnets

---

pkg/infrastructure/gcp/clusterapi/clusterapi.go
pkg/infrastructure/gcp/clusterapi/firewallrules.go

** Bootstrap firewall rules should not be created when the user does not have the permission to do so (during capg xpn installs).

OCPBUGS-35262: Do not create firewall rules for xpn installs

---

pkg/destroy/gcp/address.go
pkg/destroy/gcp/backendservice.go
pkg/destroy/gcp/cloudcontroller.go
pkg/destroy/gcp/targetTCPProxies.go

** The Address, backend service, and tcp proxies were not found and deleted properly. This was holding up the deletion of certain other resources such as health checks.

OCPBUGS-37683: Resource deletion is holding up deletion process

---

pkg/infrastructure/vsphere/clusterapi/import.go

This PR resolves two issues:
1. if a standard port group is
used and does not exist on each ESXi host in
the defined cluster.
2. if the cluster contains multiple esxi hosts
without shared storage and the host is selected
that does not contain the datastore provided by the
platform spec
This changes the `findAvailableHostSystems` to
include two checks: one for the network existing and
the other that the datastore exists on the ESXi host
that is selected for the import process

OCPBUGS-37945: import failure when esxi config is not the same in the cluster

---

pkg/types/vsphere/validation/platform.go

Description:
If multiple networks are configured, the installer will progress but fail very early in bootstrap due to API validation.
Test of this PR with multiple NICs:
```
$ ./bin/openshift-install create cluster --dir inst
ERROR failed to fetch Metadata: failed to load asset "Install Config": failed to create install config: invalid "install-config.yaml" file: platform.vsphere.failureDomains.topology.networks: Required value: must specify a single network
```

OCPBUGS-38551: only allow a single network in failure domain topology

---

data/data/bootstrap/files/usr/local/bin/release-image.sh.template

We want to use the manifest-listed RepoDigest that matches the Digest, instead of the first one. 
Its confusing for a user to install with one payload, and then observe (what looks like) a different payload once the cluster is provisioned.

OCPBUGS-38552: Use ManifestListed Digest for multi payload installs

---

pkg/infrastructure/gcp/clusterapi/clusterapi.go
pkg/infrastructure/gcp/clusterapi/iam.go

Add additional role needed for shared VPC to the network project to allow creation of firewalls.

OCPBUGS-38152: Add roles needed for shared VPC

---

pkg/infrastructure/vsphere/clusterapi/clusterapi.go
pkg/infrastructure/vsphere/clusterapi/folder.go

This PR resolves an issue when `folder` is undefined and datacenter exists as a child of a datacenter folder. instead of using DatacenterFolders.VmFolder we
replace that with a path.Join of the datacenter InventoryPath, vm and the clusterID. This will provide the entire correct path to the hidden `/vm/` folder in vCenter.

OCPBUGS-38599: incorrect folder gen, workaround govmomi vm folder path bug

---

pkg/destroy/gcp/address.go

** The installer was only destroying internal addresses. CAPI installs are producing external addresses that were filtered out. This was not causing issues on destroy, but artifacts were left over.

OCPBUGS-38571: GCP Global Address failed to destroy

---

pkg/infrastructure/azure/azure.go
pkg/infrastructure/azure/dns.go

While creating the DNS and External LB for APIServer, add check to make sure APIServer's OperatorPublishingStrategy is `External` when publishing strategy is `Mixed`. This is to
augment the existing check that looked at only the `PublishingStrategy`.

OCPBUGS-38070: Azure CAPI: Add check for APIServer OperatorPublishingStrategy

---

pkg/clusterapi/system.go

Until we can bump capv to the latest version
disable session keep alive that causes session
timeout and deadlocks as described in the links
attached to the bug.

OCPBUGS-38657: upstream capv bug causes session timeout

---

cmd/openshift-install/create.go

A long time ago I submitted a PR (#6018) to change the installer output from
```
INFO To access the cluster as the system:admin user when using 'oc',
run 'export KUBECONFIG=/path/to/installer/auth/kubeconfig'
```
to
```
INFO To access the cluster as the system:admin user when using 'oc', run
export KUBECONFIG=/path/to/installer/auth/kubeconfig
```
for ease of cut-and-pasting, but then a few months later it accidentally got reverted due to a badly-resolved merge conflict in #5336.
This just puts it back to how it was in #6018 (which, FTR, is how README.md still claims it prints it).

NO-JIRA: Print the "export KUBECONFIG=..." command on its own line for easier cut-and-paste

---

pkg/asset/ignition/bootstrap/gcp/storage.go
pkg/infrastructure/gcp/clusterapi/clusterapi.go

** removing the timeout for a client that is causing failures when we return from the
function that creates a signed url.
** Update the gcp cluster api reference to bucket creation that takes away the need for a client context.

OCPBUGS-38196: Remove timed context for gcp client

---

pkg/asset/installconfig/aws/subnet.go
pkg/asset/installconfig/aws/validation.go
pkg/asset/installconfig/aws/validation_test.go
pkg/asset/machines/clusterapi.go
pkg/asset/manifests/aws/cluster.go
pkg/asset/manifests/aws/zones.go
pkg/types/aws/platform.go

A public-only subnets cluster install requires:
1. publish method to not be "Internal"
2. a BYO VPC with public subnets

OCPBUGS-38722: aws: validate public-only subnets configs

---

data/data/agent/files/usr/local/bin/install-status.sh

Updated install-status.sh to check agent-import-cluster.service and agent-add-node.service for day 2 add nodes workflow.
agent-register-cluster.service and start-cluster-installation.service are classified as install workflow only services.

OCPBUGS-38177: install-status reflects day 2 services

---

pkg/asset/ignition/bootstrap/common.go
pkg/asset/machines/nutanix/capimachines.go
pkg/infrastructure/azure/azure.go
pkg/infrastructure/clusterapi/clusterapi.go
pkg/infrastructure/clusterapi/types.go
pkg/infrastructure/gcp/clusterapi/clusterapi.go
pkg/infrastructure/nutanix/clusterapi/clusterapi.go
pkg/infrastructure/openstack/clusterapi/clusterapi.go
pkg/types/nutanix/helpers.go

To fix the 4.16 installer regression issue when installing a Nutanix OCP cluster with DHCP network. The issue was hit by the customer:
https://issues.redhat.com/browse/OCPBUGS-38118
The workaround fix is to add the file "/etc/hostname" with the Machine name to the master and bootstrap ignition data.
1. clusterapi: ignition interface returns secrets
Updates the clusterapi ignition interface so that it returns
all ignition secrets. Prior to this commit, the ignition interface
returned the bootstrap ignition data, and the provision method
turned this data into secrets. Updating the interface to return
all secrets, gives greater flexibility to the platform to completely
control the ignition secrets that are created for that platform.
The motivation is that some platforms such as Nutanix may …

OCPBUGS-38118: failed to install Nutanix OCP 4.16 cluster with DHCP network

---

upi/aws/cloudformation/02_cluster_infra.yaml

The usage of python3.8 in lambda runtimes is being deprecated soon (Oct 14, 2024) [1]. This change updates it to python3.9 which is the default version in RHEL 9.
[1] https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

OCPBUGS-38235: upi/aws: update lambda runtime python version

---

data/data/install.openshift.io_installconfigs.yaml
pkg/asset/installconfig/gcp/validation.go
pkg/types/gcp/machinepools.go
pkg/types/gcp/validation/machinepool.go
pkg/types/validation/machinepools_test.go

** GCP Control Plane Nodes should now be allowed to use pd-balanced and hyperdisk-balanced. The IOPS rating is sufficient for both disk types to be used for control plane nodes, but pd-standard still falls short.

CORS-3561: Add new disk types GCP Control Plane nodes

---

pkg/asset/ignition/bootstrap/gcp/storage.go

** removing the timeout for a client that is causing failures when we return from the function that creates a signed url.

OCPBUGS-38198: Remove timed context for gcp client

---

data/data/install.openshift.io_installconfigs.yaml
pkg/asset/installconfig/gcp/validation.go
pkg/types/gcp/machinepools.go
pkg/types/gcp/validation/machinepool.go
pkg/types/validation/machinepools_test.go

** GCP Control Plane Nodes should now be allowed to use pd-balanced and hyperdisk-balanced. The IOPS rating is sufficient for both disk types to be used for control plane nodes, but pd-standard still falls short.
** Update installer explain to provide the correct information

OCPBUGS-39002: Add new disk types GCP Control Plane nodes

---

pkg/asset/installconfig/aws/validation.go

Add a warning that public subnets can not be set when publish is set to
internal

OCPBUGS-33308: IngressController subnet selection in AWS

---

data/data/bootstrap/baremetal/files/etc/containers/systemd/ironic-dnsmasq.container
data/data/bootstrap/baremetal/systemd/units/provisioning-interface.service.template

This a cherry-pick of  https://github.com/openshift/installer/pull/8580/commits/a89f0c74676c0a4189a41e3da27ff28f749d1d7d and https://github.com/openshift/installer/pull/8580/commits/bb91cde94317d1f782b7c511b7532a83028b35fa

[release-4.14] OCPBUGS-36180:  baremetal IPI without provisioning network failing on provisioning-interface.service

---

pkg/destroy/gcp/address.go

** The installer was only destroying internal addresses. CAPI installs are producing external addresses that were filtered out. This was not causing issues on destroy, but artifacts were left over.

OCPBUGS-38600: GCP Global Address failed to destroy

---

pkg/asset/installconfig/gcp/client.go
pkg/asset/installconfig/gcp/validation.go

Need to add in the credentials if provided when creating the IAM service, consistent with other service creation. In addition there should not be a check for shared VPC since SAs can be provided even when not using shared VPCs.

OCPBUGS-39299: Fix to validation for GCP pre-created ServiceAccount

---

data/data/install.openshift.io_installconfigs.yaml
pkg/asset/installconfig/gcp/validation.go
pkg/asset/installconfig/gcp/validation_test.go
pkg/destroy/gcp/gcp.go
pkg/types/gcp/machinepools.go
pkg/types/gcp/validation/machinepool.go
pkg/types/gcp/validation/machinepool_test.go
pkg/types/validation/machinepools_test.go

** Update the enumeration for GCP disks to include hyperdisk-balanced.
** Update the allowed disk types of compute nodes for gcp. This will now include hyperdisk-balanced.
** GCP Control Plane Nodes should now be allowed to use pd-balanced and
hyperdisk-balanced. The IOPS rating is sufficient for both disk types
to be used for control plane nodes, but pd-standard still falls short.
** Update installer explain to provide the correct information

OCPBUGS-39206: Update GCP Disk Types 4.16

---

upi/openstack/common.yaml

On ansible-core 2.14 and below, `var_files` chokes on missing file. This
is no longer the case with ansible-core 2.15. We need a different
strategy so that ansible ignores non-existent files.

OCPBUGS-39285: Fix var_files syntax to work on older version of ansible

---

pkg/asset/manifests/aws/cluster.go

[OCPBUGS-35054](https://issues.redhat.com/browse/OCPBUGS-35054)
Added security group ingress rule to satisfy the ingress traffic
from internal network when the installation is BYO VPC where the machine
CIDR, provided in install config, isn't the primary for the VPC.
To recap the current CAPA provisioning:
- The SGs with suffix `node`, `lb` and `controlplane` are created and
attached to the control plane nodes
- The SGs 'lb' is intended to create ingress rules from listeners (API,
MCS, etc), but CAPA enforces the Primary CIDR block of VPC[1]
- When deploying BYO VPC with multi-CIDR (managed multi-cidr isn't
supported), CAPA creates ingress rules in `lb` with primary CIDR of
VPC, then the control plane instances tries to access the MCS endpoint
in the first boot to load ignitions from …

OCPBUGS-35054: capi/aws/byo-vpc/multi-cidr: fix group rules

---

pkg/infrastructure/gcp/clusterapi/clusterapi.go
pkg/infrastructure/gcp/clusterapi/firewallrules.go

Remove the overly permissive firewall rules created by cluster-api-provider-gcp.

OCPBUGS-38069: Remove firewall rules created by CAPG

---

pkg/asset/installconfig/azure/client.go
pkg/asset/manifests/azure/cluster.go

If a cluster is installed in an existing vnet, since CAPI hardcodes
the internal LB IP to 10.0.0.100, there is a chance of conflict
if there was a cluster already installed. Added a check to see
if the default internal LB is available, else pick the next
available IP.
Also added a field in the install config "InternalLBIP" that the
users can set for the internal LB to use.

OCPBUGS-37442: azure: Pick the next available IP address for internal LB

---

data/data/bootstrap/baremetal/files/etc/containers/systemd/ironic-httpd.container.template
data/data/bootstrap/baremetal/files/etc/containers/systemd/ironic.container.template
pkg/asset/ignition/bootstrap/baremetal/template.go
pkg/asset/ignition/bootstrap/baremetal/template_test.go
pkg/asset/ignition/bootstrap/common.go
pkg/asset/tls/ironictls.go

This is a cherry-pick of https://github.com/openshift/installer/pull/8819

[release-4.16] OCPBUGS-39468: Enable TLS for virtual media in initial ironic deployment

---

data/data/bootstrap/baremetal/systemd/units/extract-machine-os.service

This service has to download a large container image,
bump update the timout to allow for a slow download rate.

OCPBUGS-39081: Bump extract-machine-os timout to 20m

---

upi/openstack/security-groups.yaml

There was a typo and we were trying to match an IPv6 network for remote IP prefix instead of an IPv6 one.

OCPBUGS-39402: Fix IPv6 security group rule for schedulable master

---

pkg/asset/machines/openstack/machines.go
pkg/asset/machines/openstack/machinesets.go
pkg/asset/machines/openstack/openstackmachines.go
pkg/asset/machines/openstack/openstackmachines_test.go

* Create a function to figure out whether IPv6 single stack is enabled
and that will activate ConfigDrive.
* Enable ConfigDrive for workers as well, not just masters.

OSASINFRA-3571: openstack: refactor ConfigDrive & add it for workers

---

pkg/infrastructure/azure/azure.go

Cloud configuration wasn't being set when an existing vnet was set.

OCPBUGS-36196: pkg/infrastructure/azure: set correct cloud for BYO vnet

---

data/data/coreos/rhcos.json

These changes will update the RHCOS 4.18 boot image metadata. Notable changes in the bootimage are:
OCPBUGS-39536 -  RHCOS boot fails with fips=0
```
--distro rhcos --no-signatures --name 4.18-9.4                   \
x86_64=418.94.202409050217-0                                      \
aarch64=418.94.202409050217-0                                     \
s390x=418.94.202409050217-0                                       \
ppc64le=418.94.202409050217-0
```

OCPBUGS-41259: update RHCOS 4.18 bootimage metadata to 418.94.202409050217-0

---

pkg/asset/ignition/bootstrap/common.go
pkg/asset/machines/nutanix/capimachines.go
pkg/infrastructure/azure/azure.go
pkg/infrastructure/clusterapi/clusterapi.go
pkg/infrastructure/clusterapi/types.go
pkg/infrastructure/gcp/clusterapi/clusterapi.go
pkg/infrastructure/nutanix/clusterapi/clusterapi.go
pkg/infrastructure/openstack/clusterapi/clusterapi.go
pkg/types/nutanix/helpers.go

This is a manual cherry-pick of https://github.com/openshift/installer/pull/8806. 
To fix the 4.16 installer regression issue when installing a Nutanix OCP cluster with DHCP network, when the installer uses the nutanix-capi to provision the master/bootstrap Machines/Nodes, instead of using the pre-4.16 nutanix-terraform.

[release-4.16] OCPBUGS-38956: failed to install Nutanix OCP 4.16 cluster with DHCP

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

to allow enabling different API groups versions according to the k8s version

OCPBUGS-41257: pass k8s version to kube-apiserver render during bootstrap

---

data/data/gcp/cluster/iam/main.tf

This change updates the GCP terraform worker role to include permissions to pull from the artifact registry.
This ensures that new .pkg.dev images can be pulled and that once GCR is decomissioned, .gcr.io images can still be pulled.

OCPBUGS-36861: Updates GCP terraform worker role

---

data/data/coreos/rhcos.json

These changes will update the RHCOS 4.17 boot image metadata.
```
--distro rhcos --no-signatures --name 4.17-9.4                   \
x86_64=417.94.202408270355-0                                      \
aarch64=417.94.202408270355-0                                     \
s390x=417.94.202408270355-0                                       \
ppc64le=417.94.202408270355-0
```

OCPBUGS-41283: update RHCOS 4.17 bootimage metadata to 417.94.202408270355-0

---

pkg/infrastructure/azure/azure.go
pkg/infrastructure/azure/storage.go

While creating the Azure Storage account, give it public access only when CustomerManaged Key is present. Similarly, create Blob containers for Ignition and vhd with no public access by default unless CustomerManagedKey is present. 
See: https://github.com/openshift/installer/blob/d570c0561c0763f95b3eee6f80c7a84653db818a/data/data/azure/vnet/main.tf#L75

OCPBUGS-37506: Fix Azure storage account's public access

---

pkg/asset/installconfig/azure/client.go
pkg/asset/manifests/azure/cluster.go

If a cluster is installed in an existing vnet, since CAPI hardcodes the internal LB IP to 10.0.0.100, there is a chance of conflict if there was a cluster already installed. Added a check to see if the default internal LB is available, else pick the next available IP.

[release-4.17] OCPBUGS-41539: Pick the next available IP address for internal LB

---

pkg/infrastructure/azure/azure.go
pkg/infrastructure/azure/storage.go

Setup the storage account and Blob containers for Ignition and vhd with no public access unless CustomerManagedKey is configured.
This is a manual backport of https://github.com/openshift/installer/pull/8944.

[release-4.17] OCPBUGS-41542: Azure CAPI: Fix storage account and vhd container public access

---

pkg/infrastructure/gcp/clusterapi/iam.go

This change updates the GCP CAPI worker role to include permissions to pull from the artifact registry.
This ensures that new `.pkg.dev` images can be pulled and that once GCR is decomissioned, `.gcr.io` images can still be pulled.

OCPBUGS-36861: Updates GCP CAPI worker role

---

data/data/install.openshift.io_installconfigs.yaml
pkg/types/gcp/platform.go
pkg/types/gcp/validation/featuregates.go
pkg/types/validation/featuregate_test.go

`GCPLabelsTags` feature gate was enabled by default in 4.17 release. In 4.18 the feature gate and the checks will be removed.

CFE-1105: Remove featureGate checks on GCP userLabels and userTags configs

---

pkg/infrastructure/azure/azure.go

Always set public access to Blob containers to `PublicAccessNone` even when Customer Managed Keys are configured.

OCPBUGS-37506: Azure CAPI: Update publicAccess for Blob Containers

---

docs/dev/dependencies.md

Catching up with c1dbb138f8 (#3515), to make it easier for first-time or occasional contributors to figure out how to update that file, after I had some trouble figuring this step out in #9002.

NO-ISSUE: docs/dev/dependencies: Mention install-config YAML generation

---

cmd/openshift-install/internal_integration_test.go
cmd/openshift-install/testdata/agent/configimage/manifests/default_manifests.txt
cmd/openshift-install/testdata/agent/image/manifests/default_manifests.txt
cmd/openshift-install/testdata/agent/unconfigured-ignition/configurations/from-ztp-manifests.txt
cmd/openshift-install/testdata/agent/unconfigured-ignition/manifests/default_manifests.txt
pkg/asset/agent/manifests/clusterimageset.go
pkg/asset/agent/manifests/clusterimageset_test.go

- Use $AUTH_FILE for the valid pullSecret in CI.
- Update the pull secret in the expected install-config file when AUTH_FILE is set.
- Check if the image files contain the pull-secret.yaml file.
- Use $OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE to replace test data and pass it to the test script environment. - This is typically set in a CI job to reference the ephemeral payload release.
- Skip errors when the test does not require reading install-config.yaml.

OCPBUGS-38499: Fix integration tests

---

pkg/destroy/gcp/policybinding.go
pkg/destroy/gcp/serviceaccount.go

** During XPN installs bindings are created in the host project to the service account used to perform actions in the host project. These bindings are left over during the destruction process if they are not explicitly found and removed in the host project rather than the default (service) project.

OCPBUGS-41538: Remove bindings for XPN installs

---

data/data/coreos/rhcos.json

These changes will update the RHCOS 4.18 boot image metadata. Notable change in this bootimage bump is adding the IDPF guest os feature in GCP.
```
--distro rhcos --no-signatures --name 4.18-9.4                   \
x86_64=418.94.202409162337-0                                      \
aarch64=418.94.202409162337-0                                     \
s390x=418.94.202409162337-0                                       \
ppc64le=418.94.202409162337-0
```

OCPBUGS-42086: update RHCOS 4.18 bootimage metadata to 418.94.202409162337-0

---

upi/openstack/common.yaml

On ansible-core 2.14 and below, `var_files` chokes on missing file. This is no longer the case with ansible-core 2.15. We need a different strategy so that ansible ignores non-existent files.

OCPBUGS-39287: Fix var_files syntax to work on older version of ansible

---

pkg/asset/agent/gencrypto/auth_utils_test.go
pkg/asset/agent/gencrypto/authconfig.go
pkg/asset/agent/gencrypto/authconfig_test.go

The agent installer does not require the infra-env id to be present in the claim to perform the authentication.
/depends on https://github.com/openshift/assisted-service/pull/6697

CORS-3663: Authentication tech debt for agent based installer

---

data/data/install.openshift.io_installconfigs.yaml
pkg/asset/cluster/powervs/powervs.go
pkg/asset/installconfig/platformprovisioncheck.go
pkg/asset/installconfig/powervs/client.go
pkg/asset/installconfig/powervs/mock/powervsclient_generated.go
pkg/asset/installconfig/powervs/validation.go
pkg/asset/manifests/powervs/cluster.go
pkg/destroy/powervs/cloud-instance.go
pkg/destroy/powervs/cloud-sshkey.go
pkg/destroy/powervs/cloud-subnet.go
pkg/destroy/powervs/cloud-transit-gateways.go
pkg/destroy/powervs/cloudobjectstorage.go
pkg/destroy/powervs/dhcp.go
pkg/destroy/powervs/dns-dns.go
pkg/destroy/powervs/dns-resource.go
pkg/destroy/powervs/image.go
pkg/destroy/powervs/job.go
pkg/destroy/powervs/loadbalancer.go
pkg/destroy/powervs/power-instance.go
pkg/destroy/powervs/power-sshkey.go
pkg/destroy/powervs/power-subnet.go
pkg/destroy/powervs/powervs.go
pkg/destroy/powervs/publicgateway.go
pkg/destroy/powervs/securitygroup.go
pkg/destroy/powervs/serviceinstance.go
pkg/destroy/powervs/vpc.go
pkg/types/powervs/metadata.go
pkg/types/powervs/platform.go

Creating and destroying transit gateways (TG) during CI testing is costing an abnormal amount of money.  Since the monetary cost for creating a TG is high, provide support for a user created TG when creating an OpenShift cluster.

OCPBUGS-37588: PowerVS: Add support for persistent Transit Gateways

---

pkg/infrastructure/openstack/preprovision/securitygroups.go

When using single stack IPv6 there is no need to create IPv4 rules. This commit restricts the creation of IPv4 rules for when the IPv4 Machine Networks exists in the cluster.

OSASINFRA-3614: OpenStack: remove creation of IPv4 rules on Single stack IPv6 cluster 

---

pkg/asset/machines/powervs/machines.go

CPMSO support for Power VS was added via PR: https://github.com/openshift/installer/pull/7226
It was in inactive state and now we have done enough testing by making it active and wants to make it active by default.

MULTIARCH-4813: Make CPMS active by default for Power VS platform

---

pkg/asset/releaseimage/default.go

Branching checklist: bumps default release image to 4.18.

CORS-3598: bump release image to 4.18

---

pkg/asset/agent/gencrypto/authconfig.go
pkg/asset/agent/gencrypto/authconfig_test.go
pkg/asset/agent/image/ignition.go
pkg/asset/agent/image/ignition_test.go

Base64 encode public key to fix systemd parsing issues; remove unused field

OCPBUGS-42012:  Systemd Fails to Parse Multiline EC Keys

---

pkg/infrastructure/azure/azure.go
pkg/infrastructure/azure/compute.go

Only when securityType "ConfidentialVM" is configured, provide Image ID as Source ID while creating different Image versions.

OCPBUGS-36670: Azure CAPI: Provide Image ID while creating different image versions

---

data/data/coreos/rhcos.json

These changes will update the RHCOS 4.17 boot image metadata. The following issues were addressed by this update:
OCPBUGS-41621 - rpm-ostree-fix-shadow-mode.service is failing after reboot.
```
--distro rhcos --no-signatures --name 4.17-9.4                   \
x86_64=417.94.202409120353-0                                      \
aarch64=417.94.202409120353-0                                     \
s390x=417.94.202409120353-0                                       \
ppc64le=417.94.202409120353-0
```

OCPBUGS-41622: update RHCOS 4.17 bootimage metadata to 417.94.202409120353-0

---

pkg/asset/installconfig/gcp/validation.go
pkg/asset/installconfig/gcp/validation_test.go
pkg/types/gcp/machinepools.go

** Update the error text and the way that disks and instances are validated. Before, the error message was backwards on indicating if the instance type or the disk type was the problem. Now, the disk type is validated against the instance type (rather than the opposite).

OCPBUGS-41184: GCP Validate Disk and Instance Type

---

pkg/infrastructure/gcp/clusterapi/ignition.go

** The api and api-int addresses are coming from the capi gcp provider. The addresses must be added to the Load Balancer Config and to the ignition config for the bootstrap node.

CORS-3702: Add api and api-int ips to bootstrap node

---

pkg/asset/machines/azure/machines.go
pkg/asset/machines/gcp/machines.go

When sorting the availability zones before creating the CPMS manifest, we are inadvertently changing the backing array that is used by the MAPI machine manifests for controlPlane nodes, thus creating a discrepancy between which zones capi creates the machines in and where they are assigned to in the mapi manifests.
The CPMS operator sorts the failure domains before using them [1], so there is no reason for the installer to do that.
[1] https://github.com/openshift/cluster-control-plane-machine-set-operator/blob/611636f48fc87bb09c95121d228697cee72fc118/pkg/machineproviders/providers/openshift/machine/v1beta1/mapping.go#L114-L122

OCPBUGS-42563: machines: don't sort mpool zones

---

hack/go-integration-test-nodejoiner.sh

By default in the CI the `-mod=vendor` is set, preventing the script to install (donwload) the `setup-envtest` tool, which is required to download the apiserver and etcd binaries used by [envtest](https://github.com/kubernetes-sigs/controller-runtime/tree/main/tools/setup-envtest#where-does-it-put-all-those-binaries)

AGENT-998: allow node-joiner hack script to run in the CI

---

pkg/asset/ignition/bootstrap/common.go
pkg/asset/imagebased/image/ignition.go

The if chain just after this expects the final filename and not the
possibly templated version. Strip the suffix in case it's a templated
file.
This notably fixes the mode for `registries.conf`, which became a
templated file and so went from 0644 to 0600. This patch brings it back
to 0644.

NO-JIRA: ignition/bootstrap/common: account for templated files when setting mode

---

pkg/asset/installconfig/aws/route53.go
pkg/infrastructure/aws/clusterapi/aws.go

This PR bumps CAPA to incorporate a fix for creating NLBs in secret regions [1], which do not support security groups.
It also uses the opportunity to do some refactoring in the part of the code that creates route53 records.
[1] https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5030

OCPBUGS-33311: aws: fix NLB creation in secret regions

---

pkg/gather/service/analyze.go

By running `openshift-install gather bootstrap --dir path/to/workdir` outside of the `workdir`, the logs from the bootstrap VM are saved with `log-bundle-XXXX/` prefix path but compared against the full path `path/to/workdir` during path substitution for the final log bundle archive:
```
DEBUG Log bundle written to /var/home/core/log-bundle-20241004145703.tar.gz
DEBUG combinedDirectory: c/log-bundle-20241004145703
[...]
DEBUG oldHeaderName: log-bundle-20241004145703/bootstrap/services/approve-csr.json
DEBUG replacing '/c/cluster-log-bundle-20241004145703/' by '' in log-bundle-20241004145703/bootstrap/services/approve-csr.json
DEBUG newHeaderName: log-bundle-20241004145703/bootstrap/services/approve-csr.json
DEBUG no log-bundle-XXXX prefix, adding: …
```

OCPBUGS-39339: gather: simplify service regex for analyze

---

pkg/asset/installconfig/openstack/validation/cloudinfo.go
pkg/asset/installconfig/openstack/validation/platform.go

The minimum MTU for the IPv6 network was previously only enforced when the controlPlanePort used the Network filter. This commit change the validation to also work when using the Subnet filter from FixedIPs.
This commit does two things:
- populate the ControlPlanePortNetwork struct in CloudInfo even when using the Subnet filter and not the Network one.
- move the validation for MTU out of the branch for Network filter from the install-config.yaml

OCPBUGS-41785: Validate MTU when controlPlanePort uses FixedIPs

---

pkg/destroy/gcp/forwardingrule.go

** The destroy code was stuck, thinking there were more forwarding rules to delete. There are not but it never removed them from the pending list.

OCPBUGS-42789: Update forwarding rules destroy

---

pkg/asset/installconfig/aws/subnet.go
pkg/asset/installconfig/gcp/client.go
pkg/destroy/aws/ec2helpers.go

The intention here should be to initialize a slice with a capacity of length rather than initializing the length of this slice. 
The online demo: https://go.dev/play/p/q1BcVCmvidW

OCPBUGS-43041: fix slice init length

---

data/data/bootstrap/baremetal/files/usr/local/bin/extract-machine-os.sh
data/data/bootstrap/baremetal/systemd/units/build-metal3-env.service.template
data/data/bootstrap/baremetal/systemd/units/extract-machine-os.service

Normally in baremetal IPI the bootstrap VM's provisioning-interface service operates on the provisioning interface. However, in the case that the provisioning network is disabled but a `bootstrapProvisioningIP` is still specified, it will operate on the external network interface. Since this service involves restarting the interface, if it runs at the same time as other services it disrupts the network connectivity for those services, which can cause them to fail. This typically causes the whole installation to fail, as other units that Require the failed ones are never started by systemd (even after a successful retry of the failure).
This change adds ordering dependencies to prevent other services from running in parallel.

OCPBUGS-36869: Prevent race with provisioning-interface service

---

data/data/coreos/rhcos.json

The changes done here will update the RHCOS 4.18 bootimage metadata
OCPBUGS-42637 - /boot/efi and /sysroot dir and subfiles are unlabeled_t
```
plume cosa2stream --target data/data/coreos/rhcos.json                    
--distro rhcos --no-signatures --name 4.18-9.4                                        
--url https://rhcos.mirror.openshift.com/art/storage/prod/streams   
x86_64=418.94.202410090804-0                                                               
aarch64=418.94.202410090804-0                                                              
s390x=418.94.202410090804-0                                                                  
ppc64le=418.94.202410090804-0 
```

OCPBUGS-42637: Update RHCOS 4.18 bootimage metadata to 418.94.202410090804-0

---

data/data/coreos/rhcos.json

The changes done here will update the RHCOS 4.17 bootimage metadata
OCPBUGS-42638 - [4.17] /boot/efi and /sysroot dir and subfiles are unlabeled_t
```
--distro rhcos --no-signatures --name 4.17-9.4                    \
x86_64=417.94.202410090854-0                                      \
aarch64=417.94.202410090854-0                                     \
s390x=417.94.202410090854-0                                       \
ppc64le=417.94.202410090854-0
```

OCPBUGS-42716: Update RHCOS 4.17 bootimage metadata to 417.94.202410090854-0

---

hack/go-integration-test-nodejoiner.sh

This patch pins the setup-envtest version to v0.19. Previous usage of  `@latest` required go 1.23+, resulting then in broken CI jobs, since the CI environment is currently running with `go 1.22.7` and `GOTOOLCHAIN=local`

AGENT-988: fix node-joiner integration tests

---

cmd/openshift-install/testdata/agent/image/configurations/compact.txt
data/data/agent/files/etc/systemd/system.conf.d/10-default-env.conf.template
pkg/asset/agent/image/ignition.go
pkg/asset/agent/image/ignition_test.go

If a proxy is configured, ensure that the RendezvousIP is included in NO_PROXY setting in assisted. Not setting this value can result in hard to debug issues.

OCPBUGS-30292: For agent installer, add RendezvousIP to NO_PROXY

---

go.mod
pkg/asset/agent/manifests/nmstateconfig_test.go
pkg/asset/agent/manifests/staticnetworkconfig/generator.go
pkg/asset/agent/manifests/util_test.go

Add checks for the host interface table to validate:
- at least one entry is defined in the interface table when using network configuration
- the MAC addresses in the interface table are using the expected format

OCPBUGS-41834: Add agent installer checks for hosts interface table

---

cmd/openshift-install/testdata/agent/image/assets/with_additional_ntp_sources.txt
pkg/asset/agent/image/ignition.go
pkg/asset/agent/image/ignition_test.go

This patch introduces the support of `additionalNTPSources` also for the ABI bootstrap ephemeral environment, required to properly sync'up the time of the current instance

OCPBUGS-39231: add chrony.conf file when additional NTP sources are configured

---

cmd/openshift-install/testdata/agent/agentconfigtemplate/agent-config-template.txt
pkg/asset/agent/agentconfig/agent_config.go
pkg/asset/agent/image/agentartifacts.go
pkg/asset/agent/image/agentimage.go
pkg/asset/agent/image/ignition.go
pkg/types/agent/agent_config_type.go

Add the ability to enable minimal ISO support for all platform types, not just External. Adds a new flag to the 'agent create image' command.

AGENT-972, AGENT-973: Agent minimal ISO support for all platforms

---

pkg/asset/installconfig/gcp/validation.go
pkg/asset/installconfig/gcp/validation_test.go
pkg/types/gcp/machinepools.go

** Validation for gcp machine types (and disk types) did not allow custom machine types. GCP adds "custom" to the machine type when custom machine types are created, search for the word custom in the machine type. This skips the validation of disk type to instance type correlation, but this does not skip the validation of minimum requirements.

OCPBUGS-43279: Allow custom machine types

---

pkg/infrastructure/azure/azure.go
pkg/infrastructure/azure/compute.go

Information for creating Gen 2 images with support for `TrustedLaunch` and `ConfidentalVM` was obtained from:
1.  Trusted launch - https://learn.microsoft.com/en-us/azure/virtual-machines/trusted-launch-portal?tabs=portal%2Cportal3%2Cportal2#trusted-launch-vm-supported-images
2. ConfidentialVM - https://learn.microsoft.com/en-us/azure/confidential-computing/create-confidential-vm-from-compute-gallery#confidential-vm-supported-images

OCPBUGS-36670: Update SecurityType for Image used by ConfidentialVMs

---

pkg/asset/installconfig/gcp/validation.go
pkg/asset/installconfig/gcp/validation_test.go
pkg/types/gcp/machinepools.go

** Update the error text and the way that disks and instances are validated. Before, the error message was backwards on indicating if the instance type or the disk type was the problem. Now, the disk type is validated against the instance type (rather than the opposite).

OCPBUGS-43088: GCP Validate Disk and Instance Type

---

pkg/asset/installconfig/azure/session.go

- Send full certificate chain when using certificates for credentials
https://issues.redhat.com/browse/OCPBUGS-43567

OCPBUGS-43567: pkg/asset/installconfig/azure: send full certifcate chain

---

pkg/types/gcp/machinepools.go

** Allow Users to select C4 instance types. These instances are only valid with hyperdisk-balanced disk types.

OCPBUGS-39585: Add C4 instance validation

---

data/data/install.openshift.io_installconfigs.yaml
pkg/asset/installconfig/nutanix/validation.go
pkg/asset/machines/clusterapi.go
pkg/asset/machines/master.go
pkg/asset/machines/worker.go
pkg/infrastructure/nutanix/clusterapi/clusterapi.go
pkg/types/nutanix/helpers.go
pkg/types/nutanix/platform.go

[CORS-3706](https://issues.redhat.com//browse/CORS-3706): 
Allow users to optionally use an existing RHCOS image from Prism-Central to install an OCP Nutanix cluster. This feature is requested by customer, for the use-case of creating a large number of OCP clusters with a Nutanix PC. Instead of creating an RHCOS image object for each OCP cluster, these clusters can share a preloaded RHCOS image object in PC, so as to save network bandwidth and PC storage.

CORS-3706: allow to install an OCP Nutanix cluster using PC's existing RHCOS image

---

pkg/asset/imagebased/configimage/clusterconfiguration.go
pkg/asset/imagebased/configimage/clusterconfiguration_test.go
pkg/asset/imagebased/configimage/ingressoperatorsigner.go
pkg/types/imagebased/seedreconfiguration.go

This PR adds the ingress CA certificate `Subject.CN` to the cluster configuration manifest included in the image-based configuration ISO, in addition to the respective ingress CA private key. This CN will be used by recert during an IBI configuration to replace the seed's CN with this one, in order for the kubeconfig certificate-authority-data ingress CA to match the one in the newly created cluster.

MGMT-19151: Add ingress CN to cluster configuration for image-based installer

---

data/data/coreos/rhcos.json

The changes done here will update the RHCOS 4.16 bootimage metadata
OCPBUGS-42649 - [4.16] /boot/efi and /sysroot dir and subfiles are unlabeled_t
OCPBUGS-36806 - [4.16] rpm-ostree-fix-shadow-mode.service is failing after reboot.
```
--distro rhcos --no-signatures --name 4.16-9.4                    \
x86_64=416.94.202410172137-0                                      \
aarch64=416.94.202410172137-0                                     \
s390x=416.94.202410172137-0                                       \
ppc64le=416.94.202410172137-0

OCPBUGS-41490: Update RHCOS 4.16 bootimage metadata to 416.94.202410172137-0

---

data/data/agent/files/usr/local/bin/common.sh

Added support for PATCH in curl_assisted_service func.
Needed for the appliance flow: https://github.com/openshift/appliance/blob/1c405b5cc722b29edcf4bb6bbe14e44d21a4c066/data/scripts/bin/update-hosts.sh.template#L29-L30

AGENT-1023: support patch in curl_assisted_service

---

cmd/openshift-install/testdata/agent/image/configurations/external_with_bootArtifactsBaseURL_minimal_iso.txt
cmd/openshift-install/testdata/agent/image/configurations/external_without_bootArtifactsBaseURL_minimal_iso.txt
pkg/asset/agent/manifests/agentclusterinstall.go
pkg/asset/agent/manifests/agentclusterinstall_test.go

- Correctly maps agentClusterInstall with cloudControllerManager value 
- Updated integrations tests

OCPBUGS-43674: ABI cluster installation fails for external OCI platform

---

data/data/coreos/rhcos.json

The last boot image bump did not contain the fix for OCPBUGS-42649. This newer version of RHCOS does.
The changes done here will update the RHCOS 4.16 bootimage metadata
OCPBUGS-42649 - [4.16] /boot/efi and /sysroot dir and subfiles are unlabeled_t
```
--distro rhcos --no-signatures --name 4.16-9.4                    \
x86_64=416.94.202410211619-0                                      \
aarch64=416.94.202410211619-0                                     \
s390x=416.94.202410211619-0                                       \
ppc64le=416.94.202410211619-0
```

OCPBUGS-41490: Update RHCOS 4.16 bootimage metadata to 416.94.202410211619-0

---

pkg/agent/validations.go

The log prefix was getting set the first time through the host loop and not getting modified for subsequent hosts. We need to calculate it anew for each host.

OCPBUGS-43768: Log correct hostname for validation status

---

pkg/infrastructure/powervs/clusterapi/powervs.go

When the user provides an existing VPC, the IBM CAPI will not add ports 443, 5000, and 6443 to the VPC's security group. It is safe to always check for these ports since we only add them if they are missing.

OCPBUGS-44068: PowerVS: Fix MissingSecurityGroupRules

---

cmd/openshift-install/create.go
cmd/openshift-install/gather.go
pkg/asset/asset.go
pkg/infrastructure/clusterapi/clusterapi.go
pkg/utils/baremetal/bootstrap.go

This updates the installer to gather and analyze logs from the bootstrap node (and serial nodes) when provisioning of control plane machines fail. Investigating [OCPBUGS-43625](https://issues.redhat.com/browse/OCPBUGS-43625), it would be helpful to have the logs from the bootstrap machine. So let's do this automatically

no-jira: Collect bootstrap logs when control plane provisioning fails

---

cmd/node-joiner/testdata/add-nodes-chrony-conf.txt
pkg/asset/agent/image/ignition.go
pkg/asset/agent/joiner/clusterinfo.go
pkg/asset/agent/joiner/clusterinfo_test.go

This patch fixes the issue of adding a new node with an inaccurate date/time by reusing for the installation the same NTP servers applied by the machine config operator, found in the target cluster.
(note: no additional configuration is required by the user in nodes-config.yaml)

OCPBUGS-42544: support additionalNTPSources in node-joiner tool

---

pkg/destroy/powervs/cloud-transit-gateways.go

We were told that adding connections to a Transit Gateway also costs an exorbitant amount of money.  So the create option tgName now means that we will not clean up the connections during destroy cluster.

OCPBUGS-44162: PowerVS: Fix destroy persistent TG

---

OWNERS_ALIASES

This change adds `mresvanis` to the `imagebased` installer approvers.

NO-ISSUE: Add mresvanis to imagebased approvers

---

go.mod
pkg/asset/imagebased/image/ignition.go
pkg/asset/imagebased/image/imagebased_config.go
pkg/asset/imagebased/image/imagebased_config_test.go
pkg/types/imagebased/imagebased_config_types.go

[MGMT-19191](https://issues.redhat.com//browse/MGMT-19191): Provide a way to add coreos installer params for installation phase
Adding new field CoreosInstallerParams to image based install command to customize coreos installer command in lca cli

MGMT-19191: Provide a way to add coreos installer params for installation phase

---

pkg/infrastructure/vsphere/clusterapi/clusterapi.go

This is a backport of #8926 
Description:
In the event that all defined failure domains specify a template, the ova does not need to be downloaded. If any failure domain fails to specify a template, an attempt will be made to download the template.
This is a continuation of work started in https://github.com/openshift/installer/pull/8729

[release-4.16] OCPBUGS-41885: vSphere - If template is defined skip downloading

---

cmd/openshift-install/internal_integration_test.go
cmd/openshift-install/testdata/agent/image/configurations/compact_minimal_iso.txt
internal/tshelpers/custom_commands.go

Add some new integration functions to check minimum and maximum ISO file size along with a new integration test for the agent minimal ISO support.

AGENT-974: Add integration test for agent minimal ISO

---

pkg/asset/agent/agentconfig/agenthosts.go
pkg/asset/agent/agentconfig/agenthosts_test.go
pkg/asset/agent/common.go
pkg/asset/agent/manifests/nmstateconfig.go

The rendezvousIP is currently checked against any substring in the nmstate configuration which can result in validation failure if the next-hop-address matches the rendezvousIP. Ensure that the check is against the host IP.

OCPBUGS-44167: Ensure rendezvousIP is checked against host IP

---

pkg/asset/agent/installconfig.go
pkg/asset/agent/manifests/agentclusterinstall.go
pkg/asset/agent/manifests/agentclusterinstall_test.go

For the agent-based installer, allow the setting of AdditionalTrustBundlePolicy via the install-config overrides.

OCPBUGS-42670: Allow AdditionalTrustBundlePolicy to be set

---

data/data/install.openshift.io_installconfigs.yaml
go.mod
go.sum
vendor/github.com/openshift/api/config/v1/types_cluster_version.go
vendor/github.com/openshift/api/config/v1/types_network.go
vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
vendor/github.com/openshift/api/features/features.go
vendor/github.com/openshift/api/operator/v1/types_network.go
vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
vendor/github.com/openshift/api/route/v1/generated.proto
vendor/github.com/openshift/api/route/v1/types.go
vendor/github.com/openshift/api/route/v1/zz_generated.featuregated-crd-manifests.yaml
vendor/modules.txt

Catching up with openshift/api/pull/2023, and a backport-ish of 9d1f82a8ec (#9002). Generated with:
```console
$ GOPROXY=direct go get github.com/openshift/api@release-4.17
$ go mod tidy
$ go mod vendor
$ go generate ./pkg/types/installconfig.go
$ git add -A go.* vendor data/data/install.openshift.io_installconfigs.yaml
```
all using:
```console
$ go version
go version go1.23.1 linux/amd64
```
where `GOPROXY=direct` avoids [a caching delay][2]:
> *I committed a new change (or released a new version) to a repository, why isn't it showing up when I run `go get -u` or `go list -m --versions`?*
>
> In order to improve our services' caching and serving latencies, new versions may not show up right away. If you want new code to be immediately available in the mirror, then first make sure there …

OCPBUGS-41642: vendor: Update openshift/api to pick up v4.17 capability sets

---

pkg/asset/manifests/cloudproviderconfig.go
pkg/asset/manifests/powervs/cloudproviderconfig.go

MULTIARCH-5150: Pass IAM endpoint override to PowerVS CloudProviderConfig

---

pkg/asset/ignition/bootstrap/baremetal/template.go

We need to enable TLS between the BMC and the Metal3's httpd server for OCP 4.18+, for consistency with CBO-deployed Metal3.

OCPBUGS-39404: Enable TLS by default between Metal3's httpd server and the BMC (for serving virtual media images)

---

cmd/node-joiner/main.go
cmd/node-joiner/testdata/add-nodes-pxe.txt
internal/tshelpers/fakeregistry.go
pkg/asset/agent/image/agentartifacts.go
pkg/asset/agent/joiner/addnodesconfig.go
pkg/asset/agent/joiner/clusterinfo.go
pkg/nodejoiner/addnodes.go
pkg/nodejoiner/monitoraddnodes.go

Adding --pxe flag to "node-joiner add-nodes" generates PXE boot artificats instead of an ISO.

AGENT-859: Support for PXE files in day 2

---

cmd/openshift-install/testdata/agent/image/configurations/compact.txt
cmd/openshift-install/testdata/agent/image/configurations/control-plane-4-replicas.txt
cmd/openshift-install/testdata/agent/image/configurations/control-plane-5-replicas.txt
cmd/openshift-install/testdata/agent/image/manifests/default_manifests.txt
data/data/agent/files/etc/systemd/system.conf.d/10-default-env.conf.template
pkg/asset/agent/image/ignition.go
pkg/asset/agent/image/ignition_test.go
pkg/asset/agent/manifests/agentclusterinstall.go
pkg/asset/agent/manifests/agentclusterinstall_test.go
pkg/asset/agent/manifests/common.go
pkg/asset/agent/manifests/infraenv.go
pkg/asset/agent/manifests/infraenv_test.go
pkg/asset/agent/manifests/util_test.go

If proxy is defined in install-config, add the MachineNetwork that contains the RendezvousIP to the noproxy field in the generated manifests to ensure the Rendezvous host can be accessed.
This is an additional fix beyond https://github.com/openshift/installer/pull/9083 as it was found that when just setting the IP in 10-default-env.conf it did not get passed to the assisted-installer when it was started.

OCPBUGS-30292: If agent proxy defined, add MachineNetwork to noProxy

---

cmd/node-joiner/main.go
pkg/agent/cluster.go
pkg/agent/logging.go
pkg/agent/monitoraddnodes.go
pkg/agent/monitoraddnodes_test.go
pkg/agent/validations.go
pkg/agent/validations_test.go

Monitoring output are now batched and displayed every 5 seconds for each node. This makes the logs easier to read because the logs for each node are more likely to be grouped together.

AGENT-967: Improve monitoring output for multi-node

---

pkg/types/aws/validation/platform.go
pkg/types/aws/validation/platform_test.go

** AWS User tags support white space as valid characters. 
** User tags should be validated every time that they are supplied not only when propagateTags is True.

OCPBUGS-44171: Validate aws userTags when supplied

---

pkg/types/aws/validation/platform.go
pkg/types/aws/validation/platform_test.go

** White space should be allowed in aws tags.

OCPBUGS-44199: Allow spaces in the aws tags

---

pkg/asset/installconfig/aws/permissions.go
pkg/asset/installconfig/aws/permissions_test.go

If an instance type is specified in the install-config.yaml, the installer requires the `ec2:DescribeInstanceTypes` so it can validate instance availability in the given region as well as it satisfies the minimum requirements for OCP nodes.

OCPBUGS-43439: permissions: add ec2:DescribeInstanceTypes requirement

---

pkg/asset/installconfig/ibmcloud/client.go
pkg/asset/installconfig/ibmcloud/ibmcloud.go
pkg/asset/installconfig/ibmcloud/metadata.go
pkg/asset/installconfig/ibmcloud/metadata_test.go
pkg/asset/installconfig/ibmcloud/mock/ibmcloudclient_generated.go
pkg/asset/manifests/ibmcloud/loadbalancers.go
pkg/infrastructure/ibmcloud/clusterapi/clusterapi.go

Configure InfraReady to create DNS Records for Infrastructure Load Balancers.
Related: https://issues.redhat.com/browse/CORS-3748

CORS-3748: IBMCloud: Setup IBM Cloud CAPI InfraReady step

---

pkg/asset/agent/agentconfig/agenthosts.go
pkg/asset/agent/agentconfig/agenthosts_test.go
pkg/asset/agent/common.go
pkg/asset/agent/manifests/nmstateconfig.go

The rendezvousIP is currently checked against any substring in the nmstate configuration which can result in validation failure if the next-hop-address matches the rendezvousIP. Ensure that the check is against the host IP.
Manual cherry-pick of https://github.com/openshift/installer/pull/9167

OCPBUGS-44261: Ensure rendezvousIP is checked against host IP

---

pkg/agent/cluster.go

IPv6 was not being handled correctly when calling this function. Use net.JoinHostPort.
From the docs:
`JoinHostPort combines host and port into a network address of the form "host:port". If host contains a colon, as found in literal IPv6 addresses, then JoinHostPort returns "[host]:port".`

OCPBUGS-44580: Agent handle IPv6 correctly in net.Dial

---

cmd/node-joiner/testdata/add-nodes.txt
data/data/agent/files/usr/local/bin/add-node.sh
data/data/agent/files/usr/local/bin/agent-auth-token-status.sh
data/data/agent/files/usr/local/bin/common.sh
data/data/agent/files/usr/local/bin/start-agent.sh
data/data/agent/files/usr/local/bin/start-cluster-installation.sh
data/data/agent/files/usr/local/bin/wait-for-assisted-service.sh
data/data/agent/files/usr/local/share/assisted-service/assisted-service.env.template
data/data/agent/systemd/units/agent-auth-token-status.service
data/data/agent/systemd/units/agent-import-cluster.service.template
data/data/agent/systemd/units/agent-register-cluster.service.template
data/data/agent/systemd/units/agent-register-infraenv.service.template
data/data/agent/systemd/units/apply-host-config.service
pkg/agent/cluster.go
pkg/agent/rest.go
pkg/asset/agent/gencrypto/auth_utils.go
pkg/asset/agent/gencrypto/auth_utils_test.go
pkg/asset/agent/gencrypto/authconfig.go
pkg/asset/agent/gencrypto/authconfig_test.go
pkg/asset/agent/image/agentimage.go
pkg/asset/agent/image/ignition.go
pkg/asset/agent/image/ignition_test.go

- Create 3 seperate JWT tokens- AGENT_AUTH_TOKEN, USER_AUTH_TOKEN, WATCHER_AUTH_TOKEN 
- Update the claim to set 'auth_scheme' to identify the user persona 
-  Assisted service checks the `auth_scheme` to determine which user persona is allowed to access an endpoint
- WATCHER_AUTH_TOKEN is used with header `Watcher-Authorization` and is used by wait-for command ( watcher persona)
- USER_AUTH_TOKEN is used with header `Authorization` and is used by curl API requests, systemd services ( user persona)
- AGENT_AUTH_TOKEN is used with header `X-Secret-Key` and is used by agent service ( agent persona)
- Day2 monitor use case. Save WATCHER_AUTH_TOKEN in the secret
- Rename var to a common name AUTH_TOKEN_EXPIRY. All the 3 tokens expire at the same time.

AGENT-950: Implement Separate JWT Tokens for Different User Personas

---

pkg/asset/ignition/bootstrap/ibmcloud/storage.go
pkg/asset/installconfig/ibmcloud/client.go
pkg/asset/installconfig/ibmcloud/metadata.go
pkg/infrastructure/ibmcloud/clusterapi/clusterapi.go

IBM Cloud VPC has a limit for userdata allowed for VPC Instances. Bootstrap Ignition data must be uploaded to a COS Bucket and retrieved via Ignition configuration instead.
Related: https://issues.redhat.com/browse/CORS-3474

CORS-3474: IBMCloud: Add CAPI Ignition for bootstrap node.

---

pkg/asset/cluster/tfvars/tfvars.go
pkg/asset/installconfig/azure/client.go
pkg/asset/installconfig/azure/metadata.go
pkg/asset/installconfig/azure/mock/azureclient_generated.go
pkg/asset/machines/clusterapi.go
pkg/asset/machines/master.go
pkg/asset/machines/worker.go
pkg/asset/manifests/azure/cluster.go

Currently the Azure client can only be mocked in unit tests of the `pkg/asset/installconfig/azure` package. Using the mockable interface consistently and adding a public interface to set it up will allow other packages to write unit tests for code involving the Azure client.

CORS-3753: Allow mocking of the Azure client everywhere

---

pkg/asset/cluster/cluster.go
pkg/asset/tls/certkey.go
pkg/asset/tls/mcscertkey.go
pkg/infrastructure/aws/clusterapi/aws.go
pkg/infrastructure/aws/clusterapi/ignition.go
pkg/infrastructure/clusterapi/clusterapi.go
pkg/infrastructure/clusterapi/ignition.go
pkg/infrastructure/clusterapi/types.go
pkg/infrastructure/gcp/clusterapi/clusterapi.go
pkg/infrastructure/gcp/clusterapi/ignition.go

When userProvisionedDNS(custom-dns) is configured, the Master Pointer Ignition is updated with the API-INT IP in place of the API-Int URL because at this stage, the in-cluster DNS is not running yet.
Also, for control plane nodes to be able to pull ignition from the machine-config-server, its tls cert is updated to accept the LB IPs and not just the API-Int URL.

CORS-3709: GCP: Update Master pointer Ignition with API-Int IP

---

pkg/asset/cluster/metadata.go
pkg/asset/cluster/powervs/powervs.go
pkg/asset/installconfig/powervs/client.go
pkg/asset/installconfig/powervs/metadata.go
pkg/asset/installconfig/powervs/mock/powervsclient_generated.go
pkg/asset/installconfig/powervs/session.go
pkg/asset/manifests/cloudproviderconfig.go
pkg/asset/manifests/infrastructure.go
pkg/asset/manifests/powervs/cloudproviderconfig.go
pkg/clusterapi/system.go
pkg/infrastructure/powervs/clusterapi/powervs.go

For Disconnected install on PowerVS, Virtual Private Endpoint Gateways (VPEs) must be created in the VPC that would be part of the infrastructure to allow traffic to the following private IBM Cloud endpoints;
- IAM
- COS (in the region)
- DNS services
Proposed code would first check if the necessary VPEs are already in place, comparing the target's CRN, and create one only when missing. 
Destroy logic for the below resources need to be developed (later);
- Reserved IPs (on the subnet)
- VPEs (in the VPC)

MULTIARCH-5161: Power VS: Create VPEs as needed for Disconnected install

---

go.mod
go.sum
pkg/types/nutanix/validation/platform.go
pkg/types/nutanix/validation/platform_test.go
vendor/github.com/openshift/api/config/v1/types_infrastructure.go
vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
vendor/github.com/openshift/api/features/features.go
vendor/github.com/openshift/api/machineconfiguration/v1/zz_generated.featuregated-crd-manifests.yaml
vendor/github.com/openshift/api/operator/v1/register.go
vendor/github.com/openshift/api/operator/v1/types_olm.go
vendor/github.com/openshift/api/operator/v1/zz_generated.featuregated-crd-manifests.yaml
vendor/modules.txt

[CORS-3741](https://issues.redhat.com//browse/CORS-3741)
Allow users to configure multiple subnets via platform.nutanix.subnetUUIDs in the install-config.yaml.
Depends on https://github.com/openshift/api/pull/2077

CORS-3741: [Nutanix] support multiple subnets

---

pkg/asset/installconfig/aws/permissions.go
pkg/asset/installconfig/aws/permissions_test.go

The permission is required if the Installer has to derive the available zones.

OCPBUGS-43453: permissions: add ec2:DescribeInstanceTypeOfferings req

---

pkg/agent/cluster.go
pkg/asset/agent/gencrypto/authconfig.go

- Store the three authentication tokens (userAuth, agentAuth, watcherAuth) as a secret in the cluster when creating the node ISO.
- Automatically regenerate expired tokens and refresh the asset store to maintain valid authentication credentials in the cluster secret.

AGENT-1028: Day2 - Save and manage authentication tokens as cluster secrets

---

cmd/node-joiner/main.go
pkg/asset/agent/joiner/addnodesconfig.go
pkg/nodejoiner/addnodes.go
pkg/nodejoiner/monitoraddnodes.go

This patch introduces a new node-joiner flag to explicitly generate the config ISO, instead of the regular one. 
It will also fix the `oc adm node-image create` command, since right now the config ISO is generated even when not really requested by the user.

AGENT-1022: add node-joiner --config-iso flag

---

pkg/asset/imagebased/image/ignition_test.go
pkg/asset/imagebased/image/imagebased_config.go
pkg/asset/imagebased/image/imagebased_config_test.go
pkg/types/imagebased/imagebased_config_types.go

[MGMT-19292](https://issues.redhat.com//browse/MGMT-19292): align image based extraPartitionlabel with var-lib-containers partition label

MGMT-19292: align image based extraPartitionlabel with var-lib-containers partition label

---

pkg/destroy/gcp/address.go
pkg/destroy/gcp/backendservice.go
pkg/destroy/gcp/bucket.go
pkg/destroy/gcp/bucketobject.go
pkg/destroy/gcp/cloudcontroller.go
pkg/destroy/gcp/disk.go
pkg/destroy/gcp/filestore.go
pkg/destroy/gcp/firewall.go
pkg/destroy/gcp/forwardingrule.go
pkg/destroy/gcp/gcp.go
pkg/destroy/gcp/healthcheck.go
pkg/destroy/gcp/httphealthcheck.go
pkg/destroy/gcp/image.go
pkg/destroy/gcp/instance.go
pkg/destroy/gcp/instancegroup.go
pkg/destroy/gcp/network.go
pkg/destroy/gcp/route.go
pkg/destroy/gcp/router.go
pkg/destroy/gcp/subnetwork.go
pkg/destroy/gcp/targetTCPProxies.go
pkg/destroy/gcp/targetpool.go

The destroy code is using server side filtering on resources. The number of resources that
are filtered out (server side) are causing quota limits to be reached. Moving the filtering
to the client side will limit quota max errors.

OCPBUGS-44193: Reduce Server Side Filtering of Resources

---

pkg/infrastructure/azure/azure.go

We're seeing sporadic cases of Azure control plane machines failing to provision. In some of those cases ignition pulling times out but eventually succeeds soon after the provisioning timeout fails, so we can try to alleviate this by bumping the azure timeout.

OCPBUGS-43625: Bump Azure Machine Timeout

---

pkg/asset/manifests/aws/cluster.go

If we don't, CAPA will use "0.0.0.0/0", which is too permissive. Let's use the cluster's CIDR block instead.
Manual cherry-pick of https://github.com/openshift/installer/pull/9127

OCPBUGS-44611: [release-4.17] capi/aws: set Node Port Service CIDR override

---

pkg/asset/cluster/tfvars/tfvars.go
pkg/asset/installconfig/azure/client.go
pkg/asset/installconfig/azure/metadata.go
pkg/asset/installconfig/azure/mock/azureclient_generated.go
pkg/asset/machines/clusterapi.go
pkg/asset/machines/master.go
pkg/asset/machines/worker.go
pkg/asset/manifests/azure/cluster.go

Currently the Azure client can only be mocked in unit tests of the `pkg/asset/installconfig/azure` package. Using the mockable interface consistently and adding a public interface to set it up will allow other packages to write unit tests for code involving the Azure client.
This is a backport from #9201

[release-4.17] CORS-3753: Allow mocking of the Azure client everywhere

---

data/data/tools.go

The ARO wrapper needs to vendor the static assets from the data/data directory in order to generate manifest and ignition assets. This PR Adds a data/data package and uses a side effect of `//go:embed` to include specific data directories in our go module.
The aro-wrapper can vendor these assets simply by doing something like:
```go
package main
import (
_ "github.com/openshift/installer/data/data"
)
func main() {
}
```
In my testing that resulted in the top-level files from /data/data and the embedded directories being included in the vendor directory:
```shell
ls vendor/github.com/openshift/installer/data/data/
bootstrap  config.tf  install.openshift.io_installconfigs.yaml  manifests  terraform.rc  tools.go
```
This is intended to be temporary. The installer does not use this package. …

ARO-12457: data/data: include bootkube files in go module

---

pkg/asset/cluster/tfvars/tfvars.go
pkg/asset/installconfig/azure/metadata.go
pkg/asset/machines/clusterapi.go
pkg/asset/machines/master.go
pkg/asset/machines/worker.go

Currently the Azure client can only be mocked in unit tests of the `pkg/asset/installconfig/azure` package. Using the mockable interface consistently and adding a public interface to set it up will allow other packages to write unit tests for code involving the Azure client.
This is a backport from #9219

[release-4.16] CORS-3753: Allow mocking of the Azure client everywhere

---

pkg/asset/cluster/tfvars.go
pkg/asset/installconfig/azure/metadata.go
pkg/asset/machines/master.go
pkg/asset/machines/worker.go

Currently the Azure client can only be mocked in unit tests of the `pkg/asset/installconfig/azure` package. Using the mockable interface consistently and adding a public interface to set it up will allow other packages to write unit tests for code involving the Azure client.
This is a backport from #9220

[release-4.15] CORS-3753: Allow mocking of the Azure client everywhere

---

cmd/openshift-install/completions.go

[openshift-install-completion-zsh.txt](https://github.com/user-attachments/files/17437686/openshift-install-completion-zsh.txt)
Fixes #9115 
Seems to work
```zsh
~/git/installer zshcompletion*
❯ openshift-install create i
completions
ignition-configs  -- Generates the Ignition Config asset
install-config    -- Generates the Install Config asset
```
Signed-off-by: Tiger Kaovilai <tkaovila@redhat.com>

OCPBUGS-43561: add zsh completion

---

pkg/asset/installconfig/gcp/client.go
pkg/asset/installconfig/gcp/validation.go
pkg/asset/machines/gcp/zones.go

This commit removes GCP server-side filtering when listing zones. GCP imposes a "filtered list cost overhead quota" which limits the amount of server-side filtering we can utilize. More information can be found here:
https://cloud.google.com/compute/api-quota
We have seen CI jobs failing due to:
> level=fatal msg=failed to fetch Cluster API Machine Manifests: failed to generate asset "Cluster API Machine Manifests": failed to fetch availability zones: failed to get zones for project: failed to get zones from project XXXXXXXXXXXXXXXXXXXXXXXX: googleapi: Error 403: Quota exceeded for quota metric 'Filtered list cost overhead' and limit 'Filtered list cost overhead per minute' of service 'compute.googleapis.com' for consumer 'project_number:711936183532'.
GCP recommends utilizing client-side …

OCPBUGS-44193: move GCP zone filtering client-side

---

pkg/asset/installconfig/aws/permissions.go

The permission is needed when bootstrapping fails and the installer tries to gather the VM console logs.

OCPBUGS-44924: aws: add missing ec2:GetConsoleOutput perm requirement 

---

cmd/openshift-install/testdata/imagebased/configimage/manifests/extra_manifests.txt
pkg/asset/imagebased/configimage/extramanifests.go
pkg/asset/imagebased/configimage/extramanifests_test.go

Added support for `.json` files in the extra-manifests directory when creating a config-image using the "image-based" installer. Updated test cases as well to test added functionality.
Fixes #9134

NO-ISSUE: imagebasedinstaller:  support json files in extramanifests directory

---

pkg/asset/ignition/bootstrap/baremetal/template.go
pkg/asset/ignition/bootstrap/baremetal/template_test.go

Default port for ironic is 6180 but it's not configured for TLS
The secure port for ironic TLS connection is 6183
Change the port value based on the protocol used

OCPBUGS-45175: Ironic external url port should change based on protocol

---

data/data/tools.go

The /root/.docker/config.json.template file was not included because there was an invisible directory in the path. Without this file there will be no pull secret in the bootstrap node.

ARO-12457: Include bootstrap docker config file in go module

---

pkg/asset/manifests/powervs/cluster.go
pkg/types/defaults/installconfig.go

In CAPI, we use a random machineNetwork instead of using the one passed in by the user.

OCPBUGS-45286: PowerVS: Listen to machineNetwork

---

pkg/asset/agent/image/ignition_test.go
pkg/asset/agent/image/oc_test.go
pkg/asset/agent/image/releaseextract.go
pkg/asset/agent/image/unconfigured_ignition_test.go
pkg/asset/agent/mirror/registriesconf.go
pkg/asset/agent/mirror/registriesconf_test.go

If a mirror source contains multiple mirror entries, the tmp icsp file created for the agent-based installer 'oc' commands would only contain the first entry. This could cause a failure of the 'oc' command in a disconnected environment with multiple entries. Fix to handle multiple mirrors properly.

OCPBUGS-44938: Handle multiple mirror entries for source

---

upi/vsphere/lb/haproxy.erb.tmpl
upi/vsphere/lb/haproxy.tmpl

We are experiencing the following test failure:
API LBs follow /readyz of kube-apiserver and stop sending requests before server shutdowns for external clients
Updating haproxy configuration to match IPI in the hopes of resolving the issue

OCPBUGS-45491: Align vSphere UPI haproxy config with IPI

---

upi/azurestack/06_workers.json

The content of arm template 06_workers.json in installer repo is shown in [official azure stack hub upi installation doc](https://docs.openshift.com/container-platform/4.17/installing/installing_azure/upi/installing-azure-user-infra.html#installation-creating-azure-worker_installing-azure-user-infra),  variables `identityName` is not being used, remove it to avoid confusion from user when creating UPI cluster on azure stack hub.

OCPBUGS-44523: Remove unused variable from ASH arm template 06_workers.json

---

pkg/asset/installconfig/aws/permissions.go

It's needed by CAPA when Ipv4Pools are supplied.

OCPBUGS-44925: aws: add ec2:AllocateAddress perm requirement.

---

data/data/coreos/rhcos.json

The changes done here will update the RHCOS 4.18 bootimage metadata and address the following issues:
OCPBUGS-44310 - Request to update RHCOS bootimage for nmstate [COS-2993](https://issues.redhat.com//browse/COS-2993) - Stop publishing Alibaba RHCOS images
```
--distro rhcos --no-signatures --name 4.18-9.4                    \
x86_64=418.94.202411221729-0                                      \
aarch64=418.94.202411221729-0                                     \
s390x=418.94.202411221729-0                                       \
ppc64le=418.94.202411221729-0
```

OCPBUGS-44327: Update RHCOS 4.18 bootimage metadata to 418.94.202411221729-0

---

pkg/infrastructure/aws/clusterapi/aws.go

We should use the LB name, not its DNS name, when listing load balancers with the AWS SDK otherwise the following error will happen:
```
failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed provisioning resources after infrastructure ready: failed to find HostedZone ID for NLB: failed to list load balancers: ValidationError: The load balancer name 'yunjiang-ap55-sk6jl-ext-a6aae262b13b0580.elb.ap-southeast-5.amazonaws.com' cannot be longer than '32' characters\n\tstatus code: 400, request id: f8adce67-d844-4088-9289-4950ce4d0c83
```

OCPBUGS-45289: capi/aws: use LB name when finding Hosted Zone ID

---

pkg/asset/cluster/tfvars/tfvars.go
pkg/asset/installconfig/platformprovisioncheck.go
pkg/asset/installconfig/powervs/regions.go
pkg/asset/installconfig/powervs/validation.go
pkg/asset/installconfig/powervs/validation_test.go
pkg/asset/machines/worker.go
pkg/types/powervs/powervs_regions.go

Currently, every region is assigned a set of system types. However, system types can be different for different zones within a region. Hence, move sysTypes as children of zones rather than siblings of zones.

OCPBUGS-45685: Power VS: Create region-zone-sysType hierarchy

---

pkg/destroy/gcp/disk.go

** When querying for disk information, the labels need to be grabbed from the api. The installer was searching for the label information, but the information was blank when returned by the API so it would never find the correct label (to be used during cluster resource deletion).

OCPBUGS-45162: Delete tagged disks

---

pkg/asset/installconfig/openstack/validation/cloudinfo.go
pkg/asset/installconfig/openstack/validation/platform.go
pkg/asset/installconfig/openstack/validation/platform_test.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/mtu/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/mtu/results.go
vendor/modules.txt

This is manual cherry-pick of https://github.com/openshift/installer/pull/8988 and https://github.com/openshift/installer/pull/9081.

[release-4.16] OCPBUGS-41813: Validate MTU for custom network

---

pkg/destroy/gcp/cloudcontroller.go

** When a private cluster was created, the destroy process would not find and destroy the backend services. This was happening specifically when no backends were created/found. The backend service could not be 100% associated with the cluster so it was skipped. Now, when the backend service is found, check the associated resources (for example the health checks or forwarding rules) for their tags/labels. If the resource(s) have tags that contain the cluster ID then the group of resources is considered part of the cluster and should be deleted.

OCPBUGS-43779: Destroy all private cluster backend service resources

---

pkg/asset/installconfig/aws/permissions.go
pkg/asset/installconfig/aws/permissions_test.go

If a custom IAM role is specified, the installer needs the `sts:AssumeRole` to be able to use that role.
This fixes the following error:
```
level=fatal msg=failed to fetch Cluster Infrastructure Variables: failed to fetch dependency of "Cluster Infrastructure Variables": failed to generate asset "Platform Provisioning Check": aws.hostedZone: Invalid value: "Z01991651G3UXC4ZFDNDU": unable to retrieve hosted zone: could not get hosted zone: Z01991651G3UXC4ZFDNDU: AccessDenied: User: arn:aws:iam::<redacted>:user/ci-op-1c2w7jv2-ef4fe-minimal-perm-installer is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::<redacted>:role/ci-op-1c2w7jv2-ef4fe-shared-role
level=fatal msg=	status code: 403, request id: ab7160fa-ade9-4afe-aacd-782495dc9978
Installer exit with code 1
```

OCPBUGS-45807: aws: fix sts:AssumeRole perm requirement

---

pkg/infrastructure/vsphere/clusterapi/import.go

Currently if a cluster doesn't have
any ESXi hosts assigned the import
fails with a non-specific error.
This commit adds a proper error message.

OCPBUGS-45855: If vCenter cluster has no esxi hosts fail with sane msg

---

cmd/node-joiner/testdata/add-nodes-pxe.txt
pkg/asset/agent/image/agentartifacts.go
pkg/asset/agent/image/agentimage.go
pkg/asset/agent/image/agentpxefiles.go

instead of "agent".
The "agent" prefix is used for the day 1 agent ISO.
The "node" prefix is used for day-2 artifacts, both ISO and PXE.

OCPBUGS-45317: node-joiner PXE artifacts should be prefixed "node"

---

pkg/infrastructure/ibmcloud/clusterapi/clusterapi.go

Fix the IAM Authorization between IBM Cloud VPC and IBM Cloud COS, to allow for VPC Custom Image creation as part of CAPI Infrastructure support.
Related: https://issues.redhat.com/browse/OCPBUGS-45984

OCPBUGS-45984: IBMCloud Fix VPC-COS IAM Auth

---

pkg/asset/installconfig/aws/permissions.go
pkg/asset/installconfig/aws/permissions_test.go

When the installer has to create edge machinepools, extra permissions are needed regarding Carrier Gateways.

OCPBUGS-44834: aws: include permissions for edge compute

---

cmd/openshift-install/create.go

Waiting for the etcd bootstrap member to be removed from the etcd cluster has a timeout of five minutes, unless the overall timeout is reached first. This was apparently sufficient for most cases when the check was only in effect for single-node clusters, but it occasionally times out on HA clusters. Enforcing a timeout for this step alone is fragile. It is important to guarantee that the bootstrap resources are not torn before the etcd bootstrap member has been removed from the etcd cluster. The time spent waiting for it to happen will fluctuate based on how long it takes for the etcd operator to observe that it is safe to proceed without losing quorum.

OCPBUGS-46363: Remove narrow timeout from etcd bootstrap member removal gate.

---

pkg/infrastructure/gcp/clusterapi/iam.go

** GCP Service accounts were created correctly (and they could be found in the api), but Google states (https://cloud.google.com/iam/docs/retry-strategy) that it could take up to 60 seconds before the service account is able to be used. The exponential backoff is adjusted to actually increase in time each iteration. The context was also adjusted to ensure that we give the backoff enough time to finish. Google sends a 400 Error when the service account policies could NOT be applied, if this happens DURING the policy setting attempt again as long as we have time left in the context.

OCPBUGS-45280: Allow more time for Service Account Creation

---

pkg/infrastructure/aws/clusterapi/aws.go

This is a fallout from https://github.com/openshift/installer/pull/9281
By including the Ipv6 params I've made it so AWS would only return a result if a rule satisfying both the Ipv4 and Ipv6 params was present, which is not the case currently.
Dropping the Ipv6 part as Ipv6 is not supported in 4.16.

OCPBUGS-45669: aws: fix Node Port Service rule removal

---

docs/user/openstack/deploy_dual_stack_cluster.md
docs/user/openstack/deploy_single_stack_ipv6_cluster.md

When using a network as an additional network in the OCP cluster that has an IPv6 Subnet, that subnet must be included in the router to provide router advertisements, otherwise the interface wouldn't get an address configured. This happens because the network manager is configured with method=auto.

OCPBUGS-44560: Add note about additional networks using IPv6

---

pkg/asset/agent/joiner/clusterinfo.go
pkg/asset/agent/joiner/clusterinfo_test.go

This patch allows to run the `oc adm node-image` commands using oc 4.17.x against a cluster 4.18

OCPBUGS-46035: fix skew support for node-joiner

---

pkg/asset/installconfig/powervs/metadata.go
pkg/asset/installconfig/powervs/session.go
pkg/asset/manifests/infrastructure.go
pkg/asset/manifests/powervs/cloudproviderconfig.go

Further debugging revealed `ResourceManager` endpoint must also be overridden for Disconnected deploy on PowerVS with CAPI. Like #9143, this PR starts setting/passing `ResourceManager` override to CCM. 
One thing that's perhaps noteworthy is that we are adding logic of those endpoint overrides to be in `platformStatus` as well (as in `platformSpec`) in `pkg/asset/manifests/infrastructure.go`, which should be the way, rather than `machine-controller` container in `machine-api-controllers` pod trying to update `platformStatus` which RBAC blocks.

OCPBUGS-46470: Power VS: ResourceManager also to override for Internal deploy

---

pkg/asset/installconfig/aws/permissions.go
pkg/asset/installconfig/aws/permissions_test.go
pkg/asset/machines/worker.go

If an edge machine pool is specified without an instance type, the installer needs the `ec2:DescribeInstanceTypeOfferings` permission to derive the correct instance type available according to the local/wavelength zones being used.
Before this change, the permission was optional and its absence would result in the installer picking a hard-coded non-edge pool instance type which can cause unsupported configuration issues in mapi's output:
```
providerStatus:
conditions:
- lastTransitionTime: "2024-11-28T15:32:09Z"
message: 'error launching instance: The requested configuration is currently
not supported. Please check the documentation for supported configurations.'
reason: MachineCreationFailed
status: "False"
type: MachineCreation
```

OCPBUGS-45218: aws: fix perm requirement for edge nodes

---

pkg/asset/ignition/bootstrap/common.go
pkg/asset/ignition/machine/master.go
pkg/asset/ignition/node.go

Using the workaround of a separate /var partition until the issue is fixed in RHCOS.

OCPBUGS-46144: azure: use separate /var to avoid growfs timeouts

---

pkg/asset/installconfig/powervs/metadata.go

What we set as `DNSServices` URL (for PowerVS) in the installer gets used in `ingress-operator` as base URL that must include `/v1` at the end. See;
- https://github.com/openshift/cluster-ingress-operator/blob/dbdff16b1173dd3992e5be42203e8afbae1cb06f/pkg/dns/ibm/private/dnssvcs_provider.go#L53
- https://github.com/IBM/networking-go-sdk/blob/074bbdabd90ee37195d8fb620cbd823cdbb2751a/dnssvcsv1/dns_svcs_v1.go#L47

OCPBUGS-47504: Power VS: Private DNS service endpoint URL must end with /v1

---

docs/user/agent/add-node/add-nodes.md
docs/user/agent/add-node/node-joiner-monitor.sh
docs/user/agent/add-node/node-joiner.sh

The scripts should only be used with OpenShift 4.16 and as a dev preview.
They have been replaced by the "oc adm node-image" command.

NO-ISSUE: Deprecate node-joiner scripts

---

pkg/infrastructure/clusterapi/ignition.go

When UserProvisineDNS is enabled, the machine-config-server
cert is regenerated to respond to both the API-Int URL and API-Int LB IPs. This updated cert and key are added to `machine-config-server-tls-secret.yaml` within the bootstrap Ignition (as part of https://issues.redhat.com/browse/CORS-3709).
This PR updates the individual machine-config-server cert and key files generated also in the bootstrap ignition.

OCPBUGS-29067: Update MCS Cert and Key files within bootstrap Ignition with UserProvisionedDNS

---

data/data/manifests/bootkube/machine-config-server-ca-configmap.yaml.template
data/data/manifests/bootkube/machine-config-server-ca-secret.yaml.template
data/data/manifests/bootkube/machine-config-server-tls-secret.yaml.template

Minor follow-up to https://github.com/openshift/installer/pull/9309. The string used for owning component name wasn't accurate and is fixed now.

NO-ISSUE: Fix owning component name in machine config templates

---

go.mod
go.sum
vendor/golang.org/x/net/html/doctype.go
vendor/golang.org/x/net/html/foreign.go
vendor/golang.org/x/net/html/parse.go
vendor/golang.org/x/net/http2/frame.go
vendor/golang.org/x/net/http2/http2.go
vendor/golang.org/x/net/http2/server.go
vendor/golang.org/x/net/http2/transport.go
vendor/modules.txt

The installer is not affected by the vulnerability CVE-2024-45338 and only use the golang.org/x/net indirectly and do not use golang.org/x/net/html at all. Fixing this at main branch as a good measure and will not be backported.

OCPBUGS-47156: Bump golang.org/x/net to 0.33.0

---

pkg/asset/cluster/tfvars/tfvars.go
pkg/asset/installconfig/platformprovisioncheck.go
pkg/asset/installconfig/powervs/regions.go
pkg/asset/installconfig/powervs/validation.go
pkg/asset/installconfig/powervs/validation_test.go
pkg/asset/machines/worker.go
pkg/types/powervs/powervs_regions.go

This is a manual cherry-pick of https://github.com/openshift/installer/pull/9245

[release-4.17] OCPBUGS-46432: Power VS: Create region-zone-sysType hierarchy

---

pkg/infrastructure/azure/storage.go

** force set AllowCrossTenantReplication to false during azure service account creation. ** This security voilation blocks using and scaling Clusters in Public cloud environments for the Banking and Financial industry which need to comply to BAFIN and PCI-DSS regulations.

OCPBUGS-48119: Always set AllowCrossTenantReplication parameter to false

---

data/data/azure/vnet/main.tf

** The new versions default to false for cross_tenant_replication_enabled. This change is required for security purposes. ** This security voilation blocks using and scaling Clusters in Public cloud environments for the Banking and Financial industry which need to comply to BAFIN and PCI-DSS regulations.

OCPBUGS-45999: Always set cross_tenant_replication_enabled parameter to false

---

pkg/asset/agent/image/ignition.go
pkg/asset/agent/joiner/clusterinfo.go

This is a manual backport of https://github.com/openshift/installer/pull/9108.
Note: to avoid vendoring 2k+ files, a dynamic client has been used instead of the typed one as in the original PR.

[release-4.17] OCPBUGS-45344: support additionalNTPSources in node-joiner tool

---

images/installer/Dockerfile.upi.ci

Updates UPI image to install gcloud repos in correct dir based on https://github.com/openshift-eng/ocp-build-data/pull/5974

no-jira: images: UPI: use ART repo dir

---

cmd/openshift-install/create.go

In CI, we want to collect an installer log bundle so we can examine bootstrap logs that aren't retrievable from anywhere else. This is especially important for problems that might happen during early install.
Release PR: https://github.com/openshift/release/pull/60534

no-jira: gather: allow unconditional gather in CI

---

pkg/asset/agent/agentconfig/agenthosts.go
pkg/asset/agent/agentconfig/agenthosts_test.go
pkg/asset/agent/common.go
pkg/asset/agent/manifests/nmstateconfig.go

The rendezvousIP is currently checked against any substring in the nmstate configuration which can result in validation failure if the next-hop-address matches the rendezvousIP. Ensure that the check is against the host IP.

[release-4.16] OCPBUGS-48442: Ensure rendezvousIP is checked against host IP

---

data/data/manifests/bootkube/cvo-overrides.yaml.template

So we can stop adding 4.12.z releases to `stable-4.12`, while it's in the EUS phase.  We'd ordinarily do that when the 4.y entered the EUS phase, which for [4.12 was on 2024-07-17][1].  But for 4.12 there was some agreement with Service Delivery to delay until whenever this commit merges :).  See openshift/cincinnati-graph-data#1173,  openshift/cincinnati-graph-data#1712, and #5765 for 4.6 precedent.  4.8 and 4.10 never had an EUS-only phase, so that's why 4.12 is the next 4.y taking a run at this.  The goal is to help folks who don't meet the EUS qualifications stay on releases that they have support for.
[1]: https://access.redhat.com/support/policy/updates/openshift#dates
[2]: https://github.com/openshift/cincinnati-graph-data/pull/1173
[3]: …

OTA-1310: data/manifests/bootkube/cvo-overrides: Default to eus-4.12

---

pkg/asset/releaseimage/default.go

Branching checklist: bumps default release image to 4.19

CORS-3721: bump default release image to 4.19

---

pkg/asset/installconfig/aws/permissions.go

https://issues.redhat.com/browse/OCPBUGS-46596
Added AWS permission ec2:DescribeInstanceTypeOfferings to the default list to create cluster / PermissionCreateBase group.

OCPBUGS-46596: aws/permissions - defaults ec2:DescribeInstanceTypeOfferings

---

docs/user/azure/tested_instance_types_aarch64.md

Following arm instance type families are detected during 4.18 full function test, and verified by QE, append them into azure arm doc.
* StandardDpdsv6Family
* StandardDpldsv6Family
* StandardDplsv6Family
* StandardDpsv6Family
* StandardEpdsv6Family
* StandardEpsv6Family

OCPBUGS-48719: Add new tested azure arm instance type to doc

---

data/data/install.openshift.io_installconfigs.yaml
pkg/infrastructure/nutanix/clusterapi/clusterapi.go
pkg/types/nutanix/defaults/platform.go
pkg/types/nutanix/defaults/platform_test.go
pkg/types/nutanix/helpers.go
pkg/types/nutanix/platform.go
pkg/types/nutanix/validation/platform.go
pkg/types/nutanix/validation/platform_test.go

OCPBUGS-48570
[Nutanix] Installation failed with timeout when uploading images to PC
Fix this customer hit issue by making the prism-api call timeout value a configurable parameter in the install-config.yaml as platform.nutanix.prismAPICallTimeout (with the default value of 5 minutes).

OCPBUGS-48570:[Nutanix] Installation failed with timeout when uploading images to PC

---

pkg/asset/installconfig/aws/availabilityzones.go
pkg/types/aws/defaults/platform.go

This PR introduce zone skip when installer discover the zones from metadata/AWS API.
The `us-east-1e` is a dead zone in US Virginia, create network resources on that zone is useless as it does not offers supported instance types. That zone was causing the `WARNING`/failure when installing a cluster without setting the zone in IC:
```
WARNING failed to find default instance type for worker pool: no instance type found for the zone constraint 
WARNING failed to find default instance type: no instance type found for the zone constraint 
```

OCPBUGS-47477: aws: skip dead zones on us-east-1 when discovering AZs

---

pkg/destroy/gcp/address.go
pkg/destroy/gcp/backendservice.go
pkg/destroy/gcp/cloudresource.go
pkg/destroy/gcp/disk.go
pkg/destroy/gcp/firewall.go
pkg/destroy/gcp/forwardingrule.go
pkg/destroy/gcp/gcp.go
pkg/destroy/gcp/healthcheck.go
pkg/destroy/gcp/httphealthcheck.go
pkg/destroy/gcp/image.go
pkg/destroy/gcp/instance.go
pkg/destroy/gcp/instancegroup.go
pkg/destroy/gcp/network.go
pkg/destroy/gcp/route.go
pkg/destroy/gcp/router.go
pkg/destroy/gcp/subnetwork.go
pkg/destroy/gcp/targetTCPProxies.go
pkg/destroy/gcp/targetpool.go

We're slowly leaking backend services. This PR adds waits to make sure the operation is done before proceeding.  This refactors the destroy code to add a central operation handling function to facilitate this change.

OCPBUGS-47489: pkg/gcp/destroy: add waits to prevent leaks during heavy load

---

pkg/asset/ignition/bootstrap/common.go
pkg/asset/ignition/machine/master.go
pkg/asset/ignition/node.go

Manual cherry-pick of #9378
Using the workaround of a separate /var partition until the issue is fixed in RHCOS.
/jira cherry-pick OCPBUGS-48576

OCPBUGS-48645:  azure: use separate /var to avoid growfs timeouts

---

pkg/clusterapi/localcontrolplane.go
pkg/clusterapi/system.go

When the host that runs the OpenShift install is configured with IPv6 only, the kube-apiserver created with envtest would fail as the service-cluster-ip-range would be configured with a default IPv4 CIDR and the public address family, which is the host address, would be configured with an IPv6. This commit fixes the issue by setting a default IPv6 CIDR to service-cluster-ip-range, in case the host has no IPv4 available.

OCPBUGS-48228: Envtest: Configure IPv6 service network for API Service

---

data/data/install.openshift.io_installconfigs.yaml
docs/user/customization.md
pkg/types/installconfig.go
pkg/types/validation/installconfig.go
pkg/types/validation/installconfig_test.go

When multiple clusternetwork CIDRs are present, hostPrefix fields must be specified with the same value. If not, it can impact traffic between pods in different subnets.
The patch applies validation for IPv4 CIDR. For IPv6, the only option for hostPrefix is 64, thus naturally satisfying the requirement.
Other related changes:
- Only validate for negative host prefix when the prefix is actually used. 
- Added a test case for negative host prefix.
- https://issues.redhat.com/browse/OCPBUGS-46514 (debug steps and explanation for root cause)
- https://access.redhat.com/solutions/7100460 (temporary solution for existing cluster)

OCPBUGS-48089: validate hostPrefix to be the same when multiple  clusternetwork CIDRs are present

---

data/data/coreos/rhcos.json

[COS-3014](https://issues.redhat.com//browse/COS-3014) - Move OpenShift installer to use pure RHEL bootimages
```
x86_64=9.6.20250121-0                                     \
aarch64=9.6.20250121-0                                     \
s390x=9.6.20250121-0                                       \
ppc64le=9.6.20250121-0
```

OCPBUGS-46549: Update RHCOS 4.19 bootimage metadata to 9.6.20250121-0

---

pkg/asset/installconfig/aws/permissions.go

Previously clusters created with minimum permissions in existing VPC (unmanaged VPC or BYO VPC) and BYO Public IPv4 Pool address (BYO IP) on AWS failed to de-provision cluster without permissions to release EIP address (ec2:ReleaseAddress).
This change ensures ec2:ReleaseAddress permission is exported to the install-generated IAM policy when deploying a cluster on AWS with BYO VPC and BYO Public IPv4 Pool.
Blocks https://github.com/openshift/installer/pull/9413

OCPBUGS-49594: aws/byo-ip added required permission ec2:ReleaseAddress

---

pkg/asset/cluster/aws/aws.go

Previously the subnets created by user (BYO VPC) on edge zones (Local or
Wavelength zones) were not tagged with
kubernetes.io/cluster/<InfraID>:shared.
This change ensures installer is also setting the same cluster tag as
regular zones.

OCPBUGS-48827: aws/edge/byovpc: subnets tag kube cluster tag to shared

---

pkg/types/validation/installconfig.go
pkg/types/validation/installconfig_test.go

When a clusternetwork entry has an invalid hostPrefix, which is <= CIDR mask and the custom IPv4 join subnet is provided in the install-config, the installer gives a runtime panic error: negative shift amount.
This introduces a check to return a more user-friendly and descriptive error message instead of runtime panic.

OCPBUGS-49784: handle runtime panic when validating ovnKubernetesConfig

---

data/data/coreos/rhcos.json

The changes done here will update the RHCOS 4.18 bootimage metadata and address the following issues:
[COS-3107](https://issues.redhat.com//browse/COS-3107) - Add support for Mexico (Central) in AWS 
[COS-3104](https://issues.redhat.com//browse/COS-3104) - Add support for Asia Pacific (Thailand) in AWS 
[COS-2892](https://issues.redhat.com//browse/COS-2892) - Add support for Asia Pacific (Malaysia) in AWS
```
--distro rhcos --no-signatures --name 4.18-9.4                    \
x86_64=418.94.202501221327-0                                      \
aarch64=418.94.202501221327-0                                     \ …
```

OCPBUGS-46548: Update RHCOS 4.18 bootimage metadata to 418.94.202501221327-0

---

pkg/asset/imagebased/image/ignition.go
pkg/asset/imagebased/image/ignition_test.go
pkg/asset/imagebased/image/imagebased_config_test.go
pkg/types/imagebased/imagebased_config_types.go

This change adds the optional `ReleaseRegistry` field in the IBI installation config. This field is used as a replacement for the seed release registry in the seed cluster's image pull-specs, when the seed container image is generated in a disconnected SNO (i.e. with mirror registries configured).
It is related to: https://github.com/openshift-kni/lifecycle-agent/pull/727.

MGMT-19545: add optional release registry field to the IBI installation config

---

pkg/asset/cluster/cluster.go
pkg/infrastructure/aws/clusterapi/aws.go
pkg/infrastructure/aws/clusterapi/ignition.go
pkg/infrastructure/clusterapi/clusterapi.go
pkg/infrastructure/clusterapi/ignition.go
pkg/infrastructure/clusterapi/types.go
pkg/infrastructure/gcp/clusterapi/clusterapi.go
pkg/infrastructure/gcp/clusterapi/ignition.go

Update the worker pointer ignition with the api-int LB IP in place of the api-int URL when userProvisionedDNS is enabled.

OCPBUGS-49737: Custom-DNS: GCP, AWS: Update worker pointer Ignition

---

pkg/infrastructure/azure/compute.go

Updates the installer-generated image definition to indicate support for NVME (and SCSI) disk controllers. Without this feature on the image definition, certain VM families will fail to provision with a message such as:
> The VM size 'Standard_D8ds_v6' cannot boot with OS image or disk. Please check that disk controller types supported by the OS image or disk is one of the supported disk controller types for the VM size 'Standard_D8ds_v6'.
With the change in this commit, the VM will successfully provision.

CORS-3825: pkg/infrastructure/azure: support nvme

---

docs/user/openstack/observability.md

The `cluster:master_nodes` metric needs to be added to the scrapeconfig match query so it can be scraped from the shift-on-stack cluster.
It's required for running the correlated query defined at [1].
[1] https://github.com/openshift/installer/blob/main/docs/user/openstack/observability.md#example

OCPBUGS-50004: Add cluster:master_nodes metric retrieval in docs

---

pkg/types/ibmcloud/validation/platform.go
pkg/types/ibmcloud/validation/platform_test.go

Relax endpoint regex validation to accept new endpoints from IBM services matching /api/v* or /v*

no-jira: Relax serviceEndpoint URL validation for IBMCloud platform

---

pkg/clusterapi/system.go

Drop the metrics-bind-addr flag for the IBM Cloud CAPI deployment, as it does not appear to be supported in newer cluster-api releases.
Related: https://issues.redhat.com/browse/OCPBUGS-49319

OCPBUGS-49319: IBMCloud: Drop CAPI metrics-bind-addr

---

pkg/infrastructure/vsphere/clusterapi/import.go

We have intermittent issues with IPI Installations because it seems that the Installer does not check if a Host is in an unsuitable state (in this case Powered Off or StandBy, caused by VMware DPM).
This PR fixes that problem by checking for both states and including them in the decision.
When using the unpatched installer the following happens:
```
[snip]
level=info msg=Creating infrastructure resources...
level=debug msg=Obtaining RHCOS image file from '[https://rhcos.mirror.openshift.com/art/storage/prod/streams/4.16-9.4/builds/416.94.202410211619-0/x86_64/rhcos-416.94.202410211619-0-vmware.x86_64.ova?sha256=6e4af5d1f51156e496d712ab1d386a96311cdd15392c63721e2dd4485bc07c29'](https://rhcos.mirror.openshift.com/art/storage/prod/streams/4.16-9.4/builds/416.94.202410211619-0/x86_64/rhcos-416 …
```

OCPBUGS-50649: vsphere - check if host is powered down or on standby before uploading template

---

pkg/asset/manifests/azure/cluster.go

Adding a fix to check if ips are available to prevent a panic.

OCPBUGS-50534: Fix panic when there are no available IPs

---

pkg/destroy/powervs/dhcp.go
pkg/destroy/powervs/powervs.go

We are changing the destroy cluster slightly when deleting DHCP networks to also wait for the subnet to no longer exist.

OCPBUGS-50657: PowerVS: destroy dhcp hack

---

data/data/coreos/rhcos.json

Update RHCOS release-4.16 bootimage metadata to 416.94.202501270445-0
The changes done here will update the RHCOS release-4.16 bootimage metadata and address the following issues:
[COS-3107](https://issues.redhat.com//browse/COS-3107) - Add support for Mexico (Central) in AWS
[COS-3104](https://issues.redhat.com//browse/COS-3104) - Add support for Asia Pacific (Thailand) in AWS
[COS-2892](https://issues.redhat.com//browse/COS-2892) - Add support for Asia Pacific (Malaysia) in AWS
Note: This is the first boot image bump where we have dropped the support for Aliyun images.
```
plume cosa2stream --target data/data/coreos/rhcos.json       
--distro rhcos --no-signatures --name 4.16-9.4       
--url https://rhcos.mirror.openshift.com/art/storage/prod/streams …
```

OCPBUGS-48762: Update RHCOS-release-4.16 bootimage metadata to 416.94.202501270445-0

---

pkg/asset/cluster/azure/azure.go
pkg/destroy/azure/azure.go
pkg/infrastructure/azure/dns.go
pkg/types/azure/metadata.go

The azure destroyer checks for all the record sets present in the resource group and deletes them. But in the case where the resource group is destroyed before the destroy cluster is called, there will be stray record sets that don't get cleaned up. This frequently occurs in the azure test environment where the reaper deletes the resource group after sometime but fails to clean up these stray record sets.
Adding the fix in the off chance this scenario happens in the customer world.

OCPBUGS-44507: Check public zone for stray record set

---

pkg/asset/installconfig/powervs/regions.go
pkg/types/powervs/powervs_regions.go
pkg/types/powervs/validation/machinepool.go
pkg/types/powervs/validation/machinepool_test.go

This is a manual cherry-pick of https://github.com/openshift/installer/pull/9245

[release-4.14] OCPBUGS-46606: Power VS: Create region-zone-sysType hierarchy

---

data/data/install.openshift.io_installconfigs.yaml
pkg/types/gcp/platform.go
pkg/types/gcp/validation/platform.go
pkg/types/gcp/validation/platform_test.go

** Added the endpoints including the name and url to the install config.
** Added Specific endpoint names that able to be used/customized.
** Added validation for the GCP Service Endpoints.

CORS-3835: Add gcp endpoints to the installer config

---

pkg/infrastructure/azure/azure.go

Setting the right resource group by checking if the user has provided an existing resource group for installation and have the bootstrap destroy use it to clean resources properly.

OCPBUGS-45429: Set the right resource group in bootstrap destroy

---

images/baremetal/Dockerfile.ci
images/installer-altinfra/Dockerfile.ci
images/installer/Dockerfile.ci
images/installer/Dockerfile.upi.ci
images/libvirt/Dockerfile.ci
images/openstack/Dockerfile.ci

Starting with 4.19, the PATH environment variable is actively used in CI to manage idempotent repositories that work both in CI as locally. By overriding the PATH environment variable, machine-os-images gets unfortunate repositories as a result. I suspect this path override can just disappear.

OCPBUGS-50920: Rely on path declaration of base image

---

pkg/asset/manifests/powervs/cluster.go

If the COS location to use is different than the VPC region, then we need to rename the bucket name to correctly download the image.

OCPBUGS-50899: PowerVS: COS eu-es hack

---

data/data/install.openshift.io_installconfigs.yaml
pkg/asset/cluster/aws/aws.go
pkg/asset/cluster/tfvars/tfvars.go
pkg/asset/installconfig/aws/metadata.go
pkg/asset/installconfig/aws/permissions.go
pkg/asset/installconfig/aws/permissions_test.go
pkg/asset/installconfig/aws/validation.go
pkg/asset/installconfig/aws/validation_test.go
pkg/asset/installconfig/installconfig.go
pkg/asset/machines/clusterapi.go
pkg/asset/machines/master.go
pkg/asset/machines/worker.go
pkg/asset/manifests/aws/zones.go
pkg/asset/quota/aws/aws.go
pkg/explain/fields_lookup_test.go
pkg/explain/printer_test.go
pkg/types/aws/platform.go
pkg/types/aws/validation/machinepool.go
pkg/types/aws/validation/machinepool_test.go
pkg/types/aws/validation/platform.go
pkg/types/aws/validation/platform_test.go
pkg/types/conversion/installconfig.go
pkg/types/conversion/installconfig_test.go

Following proposal for selecting LB subnets, the field platform.vpc.subnets will be introduced for more flexible configurations. This enhancement proposal is available reference [0].
There are some adjustments to the API markers and descriptions in comparison to the proposal.
- Organize field description for easier read.
- Correct kubebuilder:validation:MaxItems on array field
This field is dropped in place of the deprecated `platform.subnets` field.
Part of [CORS-3440](https://issues.redhat.com//browse/CORS-3440)
References:
[0] https://github.com/openshift/enhancements/blob/2890cccf20ebcb94fce901f7afb170ca680aa2d9/enhancements/installer/aws-lb-subnet-selection.md

CORS-3867 CORS-3868: deprecate platform.subnets and introduce platform.vpc.subnets field in install-config

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

Adds a new bootstrapping stage for the cluster-authentication-operator to render the `RoleBindingRestriction` CRD to the set of bootstrap manifests.
We are working on moving the management of the `RoleBindingRestriction` CRD to the cluster-authentication-operator instead of it being managed by CVO as outlined in https://github.com/openshift/enhancements/pull/1726. The `RoleBindingRestriction` CRD is required in the bootstrapping manifests as the `authorization.openshift.io/RestrictSubjectBindings` admission plugin will reject creation of `system:*` RoleBinding resources during the installation process if the `RoleBindingRestriction` API does not exist.
I did some testing to ensure that we can gradually transition ownership without clashing with CVO by merging, in order:
- …

CNTRLPLANE-194: add auth-api-bootstrap stage to bootkube.sh template

---

pkg/asset/machines/vsphere/capimachines.go

This commit adds an additional check for
the providerSpec workspace vmgroup if its not empty. If it is non-empty then add the failure domain name to the VSphereMachineSpec otherwise do not define and leave empty.
This solves two problems:
- Excessive alerting from capv that the failure domain doesn't exist
- capv unable to delete bootstrap node

OCPBUGS-50574: Check for vmgroup when create capv machine fd name

---

pkg/asset/installconfig/gcp/usertags.go
pkg/asset/installconfig/gcp/usertags_test.go

PR fixes the panic observed when fetching the GCP tags during `create` stage of installation. The issue was happening because of referencing the empty google API error, which could be because of the unstable network and since the call was not reaching the server.
/cc @jianli-wei @barbacbd

OCPBUGS-50919: Fixes panic during GCP tags fetch due to unstable network

---

pkg/asset/machines/machineconfig/chrony.go
pkg/asset/machines/master.go
pkg/asset/machines/worker.go
pkg/types/powervs/defaults/platform.go

In Disconnected scenario, the VMs won't have free access to the standard NTP server/pool. Therefore, they need a custom NTP server that PowerVS specifically permits access to via special routing for disconnected VMs/workspace. This PR introduces an ability to lay down `/etc/chrony.conf` with the provided NTP server name, which has been verified working as intended on PowerVS.

OCPBUGS-51084: PowerVS: Specify chrony config for Disconnected deploy

---

data/data/install.openshift.io_installconfigs.yaml
pkg/asset/manifests/infrastructure.go
pkg/asset/manifests/infrastructure_test.go
pkg/types/gcp/platform.go
pkg/types/gcp/validation/platform.go
pkg/types/gcp/validation/platform_test.go
pkg/types/validation/featuregate_test.go

** The manifest will contain the service endpoints originally in the install config. 
** Validation for these service endpoint additions to the manifests will occur.

CORS-3919: Add GCP service endpoints to the infrastructure manifest

---

data/data/bootstrap/files/usr/local/bin/node-image-pull.sh.template

For the live logic, we were checking for the `coreos.liveiso` karg but that doesn't handle the PXE case. Instead, use the CoreOS API `/run/ostree-live`, which exists in both the ISO and PXE case.
Fixes OCPBUGS-51204.

OCPBUGS-51204: bootstrap/node-image-pull.sh: handle PXE boots as well

---

pkg/asset/manifests/azure/cluster.go

Fixing the error messages in the check for available IPs. The error message is always empty since there was no error but there are no IPs available.

OCPBUGS-50534: Fix error messages in available IP code

---

pkg/asset/manifests/ibmcloud/cluster.go

Use AZ's provided for controlPlane or compute nodes, if provided in those blocks. Also, check defaultMachinePlatform for zones before defaulting to all AZ's in IBM Cloud Region.
Related: https://issues.redhat.com/browse/OCPBUGS-46051

OCPBUGS-46051: IBMCloud: Fix CAPI AZ handling

---

pkg/types/aws/platform.go
pkg/types/aws/validation/platform.go
pkg/types/aws/validation/platform_test.go
pkg/types/validation/installconfig.go

This include static validations for the vpc.subnets field (no call to AWS API is performed). The validation criteria can be found at jira ticket [0] and enhancement proposal [1]. Summary of validation criteria:
- The subnet IDs must not include duplicates
- There can only be maximum 10 subnets assigned IngressControllerLB role.
- Either all subnets must have roles assigned or none at all.
- For a subnet that has defined roles
- Roles must be of supported types (i.e. from a set of defined roles)
- Roles must not be duplicate. This and * check naturally validates that a subnet can only have max 5 roles
- EdgeNode cannot be combined with any other roles
- ClusterNode, IngressControllerLB, ControlPlaneExternalLB (if cluster is external), and ControlPlaneInternalLB must be assigned to at least …

CORS-3869: static validation for new vpc.subnets field

---

pkg/asset/machines/ibmcloud/capimachines.go

IBM Cloud CAPI machine boot volumes must have a size set, for now default to 100 GB, until an option is available to configure the size is available via the machinepool.
Related: https://issues.redhat.com/browse/OCPBUGS-47652

OCPBUGS-47652: IBMCloud: Set CAPI boot volumes

---

pkg/asset/installconfig/ibmcloud/client.go
pkg/asset/installconfig/ibmcloud/metadata.go
pkg/asset/installconfig/ibmcloud/metadata_test.go
pkg/asset/installconfig/ibmcloud/mock/ibmcloudclient_generated.go
pkg/infrastructure/ibmcloud/clusterapi/clusterapi.go

For Internal/Private clusters deployed using CAPI, we must make sure the VPC is a Permitted Network in the DNS Services Zone.
Related: https://issues.redhat.com/browse/OCPBUGS-47459

OCPBUGS-47459: IBMCloud: CAPI add permitted network

---

pkg/asset/installconfig/powervs/metadata.go
pkg/asset/manifests/powervs/cluster.go

When deploying a cluster with an internal publishing strategy with no `vpcName` key in the install-configuration, manifest files cannot be generated, and the following error is shown: `failed to find VPC`. Given that no `vpcName` key was specified in the first place, this error is inaccurate. Correct the error message to reflect the actual requirement in this case, which is to specify a `vpcName: name` key-value pair.

OCPBUGS-50961: Power VS: Log accurate error when deploying Internal with no vpcName

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

This should resolve https://github.com/openshift/installer/pull/9424#discussion_r1967214153
I haven't been able to identify any permafailing nightlies to signal that this variable definition being missing is causing nightly failures, but I do have a slack thread open with TRT here: https://redhat-internal.slack.com/archives/C01CQA76KMX/p1740402125911299

NO-JIRA: bootstrap: add CLUSTER_PROFILE_ANNOTATION variable to auth-api bootstrapping stage

---

pkg/asset/machines/machineconfig/routes.go
pkg/asset/machines/master.go
pkg/asset/machines/worker.go
pkg/types/powervs/defaults/platform.go

When SNAT is disabled (for disconnected setup), there must be some extra routes set up on the VMs for them to be able to reach private API endpoints (eg. PowerVS, NTP) for the installer itself and other runtime components to work as intended.
This PR proposes an additional ignition manifest (`99-[master|worker]-routes`) to do just that on PowerVS.
Rebooting a master and a worker of the installed cluster has also been tested, and CO's get degrated temporarily (as expected), but it's been verified that they all recover once the rebooted node is back to `Ready` state.

OCPBUGS-51350: PowerVS: Extra network routes for disconnected install

---

pkg/asset/agent/image/agentpxefiles.go

Remove the tmp directory that is created when running the command: 'openshift-install agent create pxe-files'

OCPBUGS-39583: Remove tmp directory used for agent pxe files

---

pkg/types/defaults/installconfig.go
pkg/types/defaults/installconfig_test.go
pkg/types/defaults/machinepools.go
pkg/types/defaults/machinepools_test.go

If arbiter is set in the install config, then we want to set it's default values.

OCPEDGE-1635: Set default values for arbiter

---

data/data/coreos/scos.json
data/data/libvirt/bootstrap/main.tf
hack/build-coreos-manifest.go
pkg/rhcos/stream_scos.go

OKD will now use centos pure os bootimages
```
plume cosa2stream \
--distro rhcos --no-signatures --name c9s \
x86_64=9.0.20250222-0 \
aarch64=9.0.20250222-0 \
ppc64le=9.0.20250222-0 \
s390x=9.0.20250222-0
```

OKD-235: Add stream metadata for scos to be used by OKD

---

data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

Copy AWS static resources for the bootstrap instance of MCO.

OCPBUGS-47724: AWS: Copy static MCO resources needed for custom-dns

---

pkg/asset/agent/common.go

In a disconnected environment the check for image architecture generates an error message since the icsp info is not checked, even though the image create succeeds. This has caused multiple customer cases to be generated.

OCPBUGS-50637: Remove error logging when determining image arch

---

pkg/types/vsphere/conversion/installconfig.go

This commit changes the govmomi error to be more clear in scenarios of UPI, AI and Assisted.

OCPBUGS-51378: Change vsphere conversion govmomi err to be clear

---

pkg/asset/installconfig/aws/permissions.go

With the analysis from https://issues.redhat.com/browse/SPLAT-1844, the permission is required by the installer but never used.

CORS-2508: aws: remove unused autoscaling:DescribeAutoScalingGroups perm

---

pkg/asset/machines/arbiter.go
pkg/asset/machines/master.go
pkg/asset/machines/userdata.go
pkg/asset/machines/worker.go
pkg/infrastructure/clusterapi/ignition.go

When the master and worker pointer ignitions are updated, also update the user data secret for each of these roles with their respective pointer ignition contents.
Update Bootstrap ignition with updated user data secret files for master and worker.

OCPBUGS-49737: Custom-DNS: Update master and worker user data secrets

---

pkg/asset/manifests/infrastructure.go
pkg/asset/manifests/infrastructure_test.go
pkg/asset/manifests/vsphere/infrastructure.go

Appends the ingress and api vips to the machinenetworks in the cluster infrastructure object, because the cluster network operator checks to ensure that the machinenetwork contains those vips. In some edge cases we have seen valid configurations fail when the VIPs appear to be outside the valid range.
Here are some dumps of what the infrastructure manifest looks like (these were captured during unit tests):
```
APIServerInternalIPs: ([]v1.IP) (len=1 cap=1) {
(v1.IP) (len=11) "192.168.1.0"
},
IngressIPs: ([]v1.IP) (len=1 cap=1) {
(v1.IP) (len=13) "192.168.222.4"
},
MachineNetworks: ([]v1.CIDR) (len=3 cap=4) {
(v1.CIDR) (len=11) "10.0.0.0/16",
(v1.CIDR) (len=14) "192.168.1.0/32",
(v1.CIDR) (len=16) "192.168.222.4/32"
}
```
```
APIServerInternalIP: (string) (len=11) "192.168.1.0", …
```

OCPBUGS-36553: VSphere: add vips to machinenetwork

---

pkg/infrastructure/baremetal/variables.go

masters.json is only written when bootstrap runs.  Provide a hint that if the file is missing, perhaps there were errors that prevented bootstrap from starting.

OCPBUGS-33370: Improve baremetal gather error message

---

pkg/asset/machines/clusterapi.go
pkg/asset/machines/master.go
pkg/asset/machines/vsphere/capimachines.go
pkg/asset/machines/vsphere/machines.go
pkg/asset/machines/vsphere/machines_test.go
pkg/asset/machines/vsphere/machinesets.go
pkg/asset/machines/vsphere/machinesets_test.go
pkg/asset/machines/worker.go
pkg/asset/manifests/vsphere/infrastructure.go
pkg/infrastructure/vsphere/clusterapi/import.go
pkg/utils/vmware.go

OCPBUGS-45692
- Modified importRhcosOva() to check for max length
- Modified importRhcosOva() to use failure domain name as part of OVA filename instead of region and zone.

OCPBUGS-45692: Modified ova template name to use failure domain name

---

data/data/install.openshift.io_installconfigs.yaml
pkg/asset/manifests/cloudproviderconfig.go
pkg/types/validation/featuregate_test.go
pkg/types/vsphere/platform.go
pkg/types/vsphere/validation/featuregates.go

[SPLAT-2072](https://issues.redhat.com//browse/SPLAT-2072)
- Removed usage of feature gate VSphereMultiVCenter for multiple vCenter configurations since its now GA.
- Removed legacy ini configuration from installer now that multi vCenter is GA.
After a feature gate has been GA in an OCP release, we are supposed to clean up feature gate usage in the next release.  Multi vCenter support GA'd in 4.18, so the intention is to remove the feature gate as part of 4.19.

SPLAT-2072: Removed VSphereMultiVCenters feature gate

---

pkg/asset/imagebased/image/imagebased_config.go
pkg/asset/imagebased/image/imagebased_config_test.go

This change adds a validation for the [sgdisk](https://linux.die.net/man/8/sgdisk) partition start sector in the image based installer config.
According to sgdisk's man page: 
> Both start and end sectors can be specified in absolute terms as sector numbers or as positions measured in kibibytes (K), mebibytes (M), gibibytes (G), tebibytes (T), or pebibytes (P); for instance, 40M specifies a position 40MiB from the start of the disk. You can specify locations relative to the start or end of the specified default range by preceding the number by a '+' or '-' symbol, as in +2G to specify a point 2GiB after the default start sector, or -200M to specify a point 200MiB before the last available sector. A start or end value of 0 specifies the default value, which is the start of the largest …

OCPBUGS-39146: Validate sgdisk partition start in image based installer config

---

cmd/openshift-install/agent.go
cmd/openshift-install/testdata/agent/image/assets/tls_assets.txt

Add a new hidden agent-based-installer command to generate tls certificates. This will be used by the agent UI.
```
$ ./bin/openshift-install agent create certificates
INFO Certificates created in: tls 
$ ls tls
admin-kubeconfig-signer.crt  kube-apiserver-lb-signer.crt  kube-apiserver-localhost-signer.crt  kube-apiserver-service-network-signer.crt
admin-kubeconfig-signer.key  kube-apiserver-lb-signer.key  kube-apiserver-localhost-signer.key  kube-apiserver-service-network-signer.key
```

AGENT-537: Add agent command to generate certificates

---

pkg/asset/manifests/powervs/cluster.go

With the Disconnected install all worked out with CAPI, it is time to revert and drop the check that has been blocking "direct disconnected install" on PowerVS (#8798)

OCPBUGS-53280: PowerVS: Re-enable disconnected installs

---

pkg/types/validation/featuregate_test.go
pkg/types/vsphere/validation/featuregates.go

[SPLAT-2078](https://issues.redhat.com//browse/SPLAT-2078)
- Removed references to VSphereStaticIPs feature gate
Notes
After a feature gate has been GA in an OCP release, we are supposed to clean up feature gate usage in the next release. VSphere static IP support GA'd in 4.16, so the intention is to remove the feature gate as part of 4.19.

SPLAT-2078: Removed VSphereStaticIPs feature gate

---

data/data/agent/files/usr/local/bin/set-node-zero.sh

If the agent tls certificates have not been created yet, i.e. when using the agent UI, use the installer command to create the certs prior to running the assisted-service.
Requires https://github.com/openshift/installer/pull/9557

AGENT-537: Run agent installer command to create certificates

---

data/data/coreos/rhcos.json

- Add AWS support in mx-central1, ap-southeast-5, and ap-southeast-7
- OCPBUGS-48614 - Allow Kubelet Credential Provider to run on Node ignition
```
x86_64=9.6.20250319-0                                     \
aarch64=9.6.20250319-0                                     \
s390x=9.6.20250319-0                                       \
ppc64le=9.6.20250319-0
```

OCPBUGS-53379: Update RHCOS 4.19 bootimage metadata to 9.6.20250319-0

---

pkg/asset/manifests/topologies.go
pkg/asset/manifests/topologies_test.go

infraTopology for Arbiter and DualReplica needs to be HA, as it currently stands the infraTopology value does not have the same enums as controlPlaneTopology so the validation will fail during install if infraTopology is not a valid enum of either HA or Single, for Arbiter and DualReplica we use HA.

OCPEDGE-1513: Fixed topology logic for 2-node installs and added unit tests

---

data/data/coreos/rhcos.json

OCPBUGS-49394 - afterburn-hostname service fails on openstack cluster
```
x86_64=9.6.20250321-0                                     \
aarch64=9.6.20250321-0                                     \
s390x=9.6.20250321-0                                       \
ppc64le=9.6.20250321-0
```

 OCPBUGS-53465: Update RHCOS 4.19 bootimage metadata to 9.6.20250321-0

---

pkg/asset/cluster/aws/aws.go

Previously the subnets created by user (BYO VPC) on edge zones (Local or Wavelength zones) were not tagged with
kubernetes.io/cluster/<InfraID>:shared.
This change ensures installer is also setting the same cluster tag as regular zones.
This PR is a manual backport of https://github.com/openshift/installer/pull/9452, fixing a typo found on https://github.com/openshift/installer/pull/9480

[release-4.16] OCPBUGS-50547: aws/edge/byovpc: tag edge subnets with shared value

---

data/data/manifests/openshift/cloud-creds-secret.yaml.template
pkg/asset/manifests/openshift.go
pkg/asset/manifests/openstack/cloudproviderconfig.go
pkg/asset/manifests/template.go

If a CA bundle is required to talk to your OpenStack then obviously all services that talk to the cloud need to have both credentials and said bundle. Currently, these users can get their credentials via cloud credential operator, but they need to source their CA bundle from elsewhere (typically by extracting it from the cloud controller manager's configuration). This makes configuration of services more complicated than necessary.
Continue the resolution of the issue by storing the CA bundle, if any, in the root secret on OpenStack. When coupled with the changes introduced in openshift/cloud-credential-operator#780, this allows us to dole out the bundle to anyone who asks for it via a `CredentialsRequest`.
~While we're here, we also tweak the configuration for the cloud provider to (a) …

OSASINFRA-3730: Add support for storing OpenStack CA bundles

---

terraform/providers/ibm/go.mod
terraform/providers/ibm/go.sum
terraform/providers/ibm/vendor/github.com/IBM-Cloud/terraform-provider-ibm/.travis.yml
terraform/providers/ibm/vendor/github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cis/data_source_ibm_cis_dns_records.go
terraform/providers/ibm/vendor/github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cis/resource_ibm_cis_dns_record.go
terraform/providers/ibm/vendor/modules.txt

Use the openshift org fork of IBM Cloud Terraform provider to pick up the fix for CIS API changes. This bump cannot be directly backported due to golang version requirements by the TF provider.
Related: https://issues.redhat.com/browse/OCPBUGS-54263
Related: https://issues.redhat.com/browse/OCPBUGS-53258

OCPBUGS-54263: IBMCloud: Move to IBM TF openshift fork

---

pkg/asset/installconfig/vsphere/mock/vsphere_sim.go
pkg/types/vsphere/conversion/installconfig.go
pkg/types/vsphere/conversion/installconfig_test.go

In 4.12 and prior versions of the installer
allowed non-pathed names of vCenter objects.
In 4.13+ that is no longer allowed and absolute full paths are required.
This change is causing issues with ACM/Hive. The
only resolution (not ideal) is to connect
to vCenter and determine from potentially only the objects name to determine the absolute full path.
If there is no available connection to vCenter in the case of AI or Agent installer this fails back to
only merging paths.
Move existing functions from private to public
to assist hive - reducing copy and paste.

OCPBUGS-54260: vsphere-fix convert if only provided name

---

data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh

This took several iterations to get right. I've combined the extra services into the existing journal gather logic, and then collected the complete pacemaker log files into a separate directory and compressed each of the files.
The only one that needs compression is the pacemaker log, but it felt cleaner to do it this way.
Finally, the pacemaker log had an issue where it couldn't be copied to the bootstrap host because the read flag wasn't set in the other permission group. Fixing this addressed the copy-over issue.

OCPEDGE-1496: [TNF] Collect pacemaker, pcsd, and corosync logs and journals in installer-masters-gather.sh

---

data/data/install.openshift.io_installconfigs.yaml
pkg/types/gcp/machinepools.go
pkg/types/gcp/validation/machinepool.go
pkg/types/gcp/validation/machinepool_test.go

This patch series aims to support installing a cluster on AMD SEV SNP or TDX confidential nodes on GCP.
Previously, only AMD SEV nodes were supported, which were configured through the `confidentialCompute: Enabled` configuration flag.
Now that GCP supports specifying the confidential instance type, we are letting users specify which node type (SEV/SEV-SNP/TDX) they would like to deploy the cluster on.
This can be done by using any of the new available values in `condidentialCompute` such as `AMDEncryptedVirtualization` (similar to `Enabled`), `AMDEncryptedVirtualizationNestedPaging` (AMD SEV-SNP) or `IntelTrustedDomainExtensions` (Intel TDX).
This series depend on the following patches:
- https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/1410
- …

CORS-3923, CORS-3927: Support confidential cluster installation on SEV-SNP and TDX nodes on GCP

---

pkg/types/openstack/defaults/platform.go
pkg/types/openstack/defaults/platform_test.go
scripts/openstack/manifest-tests/lb-default-stable/test_cluster-infra.py
scripts/openstack/manifest-tests/lb-unmanaged/install-config.yaml

- Currently when no API and Ingress VIPs are provided defaults are generated based on the available machine network CIDR.
- The change skips the above step if a user-managed load balancer is provided.

OCPBUGS-53140: Validation for API and Ingress VIPs when using user-managed load balancer

---

terraform/providers/ibm/go.mod
terraform/providers/ibm/go.sum
terraform/providers/ibm/vendor/github.com/IBM-Cloud/terraform-provider-ibm/.travis.yml
terraform/providers/ibm/vendor/github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cis/data_source_ibm_cis_dns_records.go
terraform/providers/ibm/vendor/github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cis/resource_ibm_cis_dns_record.go
terraform/providers/ibm/vendor/modules.txt

Use the openshift org fork of IBM Cloud Terraform provider to pick up the fix for CIS API changes. This bump cannot be directly backported due to golang version requirements by the TF provider.
Related: https://issues.redhat.com/browse/OCPBUGS-54367
Related: https://issues.redhat.com/browse/OCPBUGS-53258

OCPBUGS-54367: IBMCloud: Move to IBM TF openshift fork

---

upi/azure/04_bootstrap.json
upi/azure/05_masters.json
upi/azure/06_workers.json

For UPI, user-assigned identity attached on each node is also not required, remove it.

CORS-3883: Remove user-assigned identity from ARM template

---

OWNERS_ALIASES

Add a new team member user as coreos-approvers / coreos-reviwers in the OWNERS_ALIASES file

NO-JIRA: OWNERS_ALIASES - Add user as coreos-approvers / coreos-reviewers

---

terraform/providers/ibm/go.mod
terraform/providers/ibm/go.sum
terraform/providers/ibm/vendor/github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cis/data_source_ibm_cis_dns_records.go
terraform/providers/ibm/vendor/github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cis/resource_ibm_cis_dns_record.go
terraform/providers/ibm/vendor/modules.txt

Use the openshift org fork of IBM Cloud Terraform provider to pick up the fix for CIS API changes. This bump cannot be directly backported due to golang version requirements by the TF provider.
Related: https://issues.redhat.com/browse/OCPBUGS-54264
Related: https://issues.redhat.com/browse/OCPBUGS-53258

OCPBUGS-54264: IBMCloud: Move to IBM TF openshift fork

---

pkg/asset/manifests/azure/cluster.go

Fixing the issue where the load balancer IP was not set in the range of the machine network CIDRs by setting it to the first IP in the CIDR range.
Also extending this logic to non-existing vnet installs since the problem can happen even during normal installs.

OCPBUGS-43724: Fix Load balancer IP setup

---

data/data/coreos/rhcos.json

- Add pkey_cca kernel module to detect CEX domain for LUKS encryption
```
x86_64=9.6.20250402-0                                     \
aarch64=9.6.20250402-0                                     \
s390x=9.6.20250402-0                                       \
ppc64le=9.6.20250402-0
```

OCPBUGS-54541: Update RHCOS 4.19 bootimage metadata to 9.6.20250402-0

---

data/data/install.openshift.io_installconfigs.yaml
pkg/asset/machines/azure/azuremachines.go
pkg/types/azure/machinepool.go
pkg/types/azure/validation/featuregates.go
pkg/types/azure/validation/machinepool.go
pkg/types/azure/validation/machinepool_test.go
pkg/types/validation/featuregate_test.go

SystemAssigned Identities are not supported in any capacity in MAPZ. Due to that they were feature gated for future CAPZ->MAPZ transition. The CAPZ Identity API creates further issues in that, the value to be used for name/scope is unclear and when deleting clusters the role assignment of the identity is leaked.
No users have asked for this functionality, so lets remove it to reduce our complexity and load.

CORS-3883:  remove SystemAssigned ID

---

pkg/asset/installconfig/vsphere/validation.go
pkg/asset/installconfig/vsphere/validation_test.go

This commit adds the missing error if the group
loop does not find a host group with the
defined failure domain hostGroup param.

SPLAT-2121: vsphere - if no host group found, append not found

---

pkg/asset/manifests/cloudproviderconfig.go
pkg/asset/manifests/gcp/cloudproviderconfig.go
pkg/asset/manifests/gcp/cloudproviderconfig_test.go

** manifests/gcp/cloudproviderconfig: The GCP cloud provider config will now be supplied with the api-endpoint and container-api-endpoint. The GCP Cloud provider (and upstream) can accept a config with the api-endpoint (compute) and container-api-endpoint (container) values to override the endpoints for the services.
** See https://github.com/kubernetes/cloud-provider-gcp/blob/master/providers/gce/gce.go#L231 and https://github.com/kubernetes/cloud-provider-gcp/blob/master/providers/gce/gce.go#L234.

CORS-3908: Update gcp cloud provider config map to include new endpoints

---

data/data/install.openshift.io_installconfigs.yaml
pkg/types/aws/platform.go
pkg/types/aws/validation/platform.go
pkg/types/aws/validation/platform_test.go
pkg/types/conversion/installconfig.go

The PR fixed the platform test assertions to compare expected err message. Previously, it is using the incorrect field (i.e. `credMode`). I think it causes actually failed unit tests to pass.
This is a also follow-up PR to CORS-3867, [CORS-3868](https://issues.redhat.com//browse/CORS-3868) and [CORS-3869](https://issues.redhat.com//browse/CORS-3869) with the following changes:
- Fix a typo in the err message for static validations of the `aws.vpc.subnets` field. It should have failed previously but due to the issue above, it passed :sweat: 
- Handled empty `vpc.subnets` value case (i.e. same as nil).
- Reworded CRD marker description about untagged subnets to be clearer.

NO-JIRA: fix the platform test assertions to check expected err message

---

data/data/install.openshift.io_installconfigs.yaml
pkg/types/aws/platform.go

Previously, the installer supports role BootstrapNode but the CRD descriptor says Bootstrap.

OCPBUGS-53439: fix inconsistent subnet role name for bootstrap node

---

pkg/types/aws/validation/platform.go
pkg/types/aws/validation/platform_test.go

Manual cherry-pick of #9197 
** White space should be allowed in aws tags.

OCPBUGS-46375: Allow spaces in the aws tags [release-4.17]

---

data/data/agent/files/usr/local/bin/oci-eval-user-data.sh

OCPBUGS-54319: oci-eval-user-data uses dmidecode which is not supported on ppc64le or s390x

---

pkg/asset/manifests/azure/cloudproviderconfig.go
pkg/asset/manifests/azure/cloudproviderconfig_test.go

Setting the use managed identity extension to false considering installer does not rely on this for now.

CORS-3886: azure: Set use managed identity to false

---

data/data/install.openshift.io_installconfigs.yaml
pkg/types/aws/platform.go
pkg/types/aws/validation/platform.go

This is a follow-up to https://github.com/openshift/installer/pull/9443. In manual role selection, BootstrapNode role is required. This should be reflected in the CRD descriptor (i.e. `openshift-install explain`).

CORS-3867: fix CRD descriptor to mention required BootstrapNode role

---

pkg/infrastructure/platform/platform.go
pkg/infrastructure/platform/platform_altinfra.go
pkg/types/installconfig.go

Sets IBMCloud to default to using CAPI--not Terraform for installs.

CORS-3278: Switch IBMCloud to CAPI

---

pkg/types/conversion/installconfig.go
pkg/types/conversion/installconfig_test.go

The installer is quite lenient about case sensitivity of networkType values. We do have existing logic to convert this field value to the correct format [[0]](https://github.com/openshift/installer/blob/7867e67e84f38f33016c1506764770982cfee503/pkg/types/conversion/installconfig.go#L99-L103.). That only applies to OpenShiftSDN.
This PR extends that logic to handle OVNKubernetes.

OCPBUGS-54606: convert OVNKubernetes networkType to correct format

---

pkg/asset/installconfig/aws/metadata.go
pkg/asset/installconfig/aws/permissions_test.go
pkg/asset/installconfig/aws/subnet.go
pkg/asset/installconfig/aws/tags.go
pkg/asset/installconfig/aws/validation.go
pkg/asset/installconfig/aws/validation_test.go

**Description**
This include validations for the vpc.subnets field with AWS API to conform to the specifications for subnet role assignment in the case of BYO subnets. The validation criteria can be found at jira ticket [0] and enhancement proposal [1].
For automatic role selection (i.e. no subnets have roles assigned), the installer rejects BYO VPC with untagged subnets (i.e. those without tag `kubernetes.io/cluster/<cluster-id>`) and suggests users to add a tag `kubernetes.io/cluster/unmanaged` to those subnets.
**Other changes**
Other related changes include:
- Refactored AWS API helper to be reusable without different query input (i.e. by vpcID, or subnetIDs) and migrated them to sdk v2 if possible.
- Refactored and improved test structures.
**References**
[0] …

CORS-3870: add validations for subnets field with AWS API

---

data/data/bootstrap/baremetal/files/usr/local/bin/master-bmh-update.sh
pkg/types/validation/installconfig.go
pkg/types/validation/installconfig_test.go

Two Node OpenShift (TNF) is DevPreview in 4.19. In order to ensure that ironic doesn't try to manage the power state of the nodes, we add a check for the DualReplica topology after the control-plane nodes are provisioned during bootstrapping and detach them from ironic. In a future release, when fencing is enabled, it will be important to enforce that this remains an invariant for the DualReplica control-plane topology. There is currently nothing preventing the annotation that detaches these nodes from being removed.
See https://redhat-internal.slack.com/archives/CFP6ST0A3/p1744635159894649

OCPEDGE-1749: [TNF] Updated bare-metal init sequence to detach control-plane nodes in Two Node OpenShift.

---

data/data/coreos/scos.json

Update to a newer bootimage before we release OKD for 4.19. This change was generated using:
```
plume cosa2stream --target data/data/coreos/scos.json                \
--distro rhcos --no-signatures --name c9s                        \
x86_64=9.0.20250411-0                                     \
aarch64=9.0.20250411-0                                     \
s390x=9.0.20250411-0                                       \
ppc64le=9.0.20250411-0
```

NO-JIRA: Update SCOS 4.19 bootimage metadata to 9.0.20250411-0

---

cmd/openshift-install/create.go
pkg/infrastructure/aws/clusterapi/ignition.go
pkg/infrastructure/gcp/clusterapi/ignition.go

Update Kubeconfig with API or API-Int LB IP based on whether the cluster is public or private respectively. This updated Kubeconfig can be used to reach API server from the install host when cutsom-DNS is enabled and there is no external DNS yet.

OCPBUGS-54902: Custom-DNS: Update Kubeconfig and Infra CR based on private or public cluster

---

pkg/asset/installconfig/azure/client.go
pkg/asset/installconfig/azure/validation.go
pkg/asset/installconfig/azure/validation_test.go
pkg/asset/installconfig/installconfig.go
pkg/asset/manifests/cloudproviderconfig.go
pkg/asset/manifests/openshift.go
pkg/types/azure/platform.go
pkg/types/azure/validation/platform.go
pkg/types/azure/validation/platform_test.go

Removing the ARO build flag from the installer to achieve the goal of moving ARO installs closer to the installer. Ideally, these ARO specific changes to the installs/installer need to be done either in the wrapper or hive.

CORS-3855: Remove ARO build flag from installer

---

pkg/asset/installconfig/gcp/client.go
pkg/asset/installconfig/gcp/mock/gcpclient_generated.go
pkg/asset/installconfig/gcp/validation.go
pkg/asset/installconfig/gcp/validation_test.go

** The gcp validation and client in the installconfig asset was not able to find the KMS key ring. This was including keys with global and regional locations. 
** The key rings should be serachable via the GetKeyRingRequest struct, but the resource name projects/*/locations/*/keyRings/* was not finding any key rings. 
** The user must have the cloudkms.keyRings.list permission to list the key rings.

OCPBUGS-52203: Find GCP KMS keys

---

data/data/manifests/bootkube/cvo-overrides.yaml.template

Like 12e711edb2 (#9373), but for 4.14.  Timing on this one has [4.14 leaving the maintenance phase and entering the EUS phase on 2025-05-01][1].  We want 4.14.z that enter `fast-4.14` up through that time to keep being added to `stable-4.14`, but `4.14.z` that enter `fast-4.14` after that date to only be added to `eus-4.14` (and no longer get added to `stable-4.14`), to help folks who don't meet the EUS qualifications stay on releases that they have support for.  Landing this change on 2025-04-28 or so should get us into that position, because 4.14.z built the week of 2025-04-21 through 2025-04-25 would likely be entering `fast-4.14` on the week of 2025-04-28 through 2025-05-02.
[1]: https://access.redhat.com/support/policy/updates/openshift#dates

OCPBUGS-55193: data/manifests/bootkube/cvo-overrides: Default to eus-4.14

---

pkg/asset/imagebased/configimage/imagebased_config_test.go
pkg/asset/imagebased/image/imagebased_config_test.go

It appears that nmstatectl version 2.44 has additional error output which causes the unit test string compare to fail. Use a string subset to ensure the error is captured.

no-jira: IBI nmstate unit test fix

---

pkg/asset/machines/clusterapi.go
pkg/asset/machines/master.go

Previously, since zones are extracted from map keys, order is not guaranteed. This can lead to an issue where master CAPI machine manifest is configured with a different subnet ID than MAPI machine manifest as they are handled separately.
Thist PR ensures the zones are sorted by lexical order before processing CAPI/MAP machine manifests so that zones are distributed in the same order.

OCPBUGS-55492:  sort zone slices extracted from map of byo subnets

---

images/installer-artifacts/Dockerfile.rhel
images/installer/Dockerfile.ci
images/installer/Dockerfile.upi.ci
images/openstack/Dockerfile.ci

Removes all dependencies for the Terraform providers image from the Dockerfiles. We want to do this separately from removing all the build artifacts, so that the image can stop being built by ART without breaking anything, then remove the build artifacts.

CORS-3960: Remove Terraform from Dockerfiles

---

pkg/destroy/azure/azure.go

In case the proxy is brought down, the installer tries to destroy cluster that was behind the proxy and ends up panicking. Adding a small nil check to avoid this.

OCPBUGS-45805: Check for nil in case of proxy crash/deleted

---

docs/user/azure/tested_instance_types_x86_64.md

Add following instance types which are tested.
- [CORS-3634](https://issues.redhat.com/browse/CORS-3634) List Azure's NDs-series and NV-series as tested instance type
- StandardNVadsV710v5Family
- Standard NDASv4_A100 Family
- [CORS-3771](https://issues.redhat.com/browse/CORS-3771) Azure - Add support for Dxv6 machine series
- StandardDsv6Family
- StandardDdsv6Family
- StandardDlsv6Family
- StandardDldsv6Family

no-jira: azure: add tested instance types for CORS-3634 and CORS-3771

---

data/data/install.openshift.io_installconfigs.yaml
pkg/types/machinepools.go
pkg/types/validation/installconfig_test.go

Adding an API to disable SSL certification, one use case for this being relevant  is a customer setting up redfish fencing on their internal network.

OCPEDGE-1707: Add Disable Certificate Verification API

---

pkg/destroy/aws/aws.go
pkg/destroy/aws/ec2helpers.go

** Update the EC2 destroy code to use the v2 SDK.
** Add to the cluster uninstaller the EC2 Client. This will ensure that the client is not recreated each time.
** Add functions to the cluster uninstaller instead of passing around more parameters.
** Transition all IAM functions and clients over to the SDK v2.
** Update vendor for new package "elasticloadbalancing" rather than "elb" for sdk v2.
** Update ELB and ELBv2 to use the packages associated with elastic load balancing for SDK V2.

OCPBUGS-53116: AWS Destroy use AWS SDK v2

---

pkg/asset/manifests/azure/cloudproviderconfig.go

Azure Stack is now using standard LBs (rather than basic): https://learn.microsoft.com/en-us/azure-stack/user/standard-load-balancer-considerations?view=azs-2501 Update the cloud provider config to expect a standard LB and avoid
```
level=error msg=--------------------------------------------------------------------------------
level=error msg=RESPONSE 400: 400 Bad Request
level=error msg=ERROR CODE: PublicIPAndLBSkuDoNotMatch
level=error msg=--------------------------------------------------------------------------------
level=error msg={
level=error msg=  "error": {
level=error msg=    "code": "PublicIPAndLBSkuDoNotMatch",
level=error msg=    "message": "Standard sku load balancer /subscriptions/de7e09c3-b59a-4c7d-9c77-439c11b92879/resourceGroups/ci-op-xsi7s39l-4055a/providers/Microsoft. …
```

OCPBUGS-55722: azure stack: switch cloud provider to standard lb

---

pkg/asset/manifests/aws/cluster.go

When using BYO subnets, users might define subnets in aws.vpc.subnets and define the machineCIDRs in the installconfig from those subnets.
Previously, an SG is attached to api lb that only allows ingress to tcp/22623 (MCS) from the only the first machineCIDR, which blocks master nodes from reaching MCS on bootstrap node.
This commit adjusts the source for the SG to allow ingress from control plane nodes via SG reference instead of relying on the machineCIDR field.

OCPBUGS-54502: ensure ctrplane nodes can access bootstrap MCS

---

pkg/asset/installconfig/azure/validation.go
pkg/asset/installconfig/azure/validation_test.go

This change adds support for [Azure Intel TDX confidential computing VM sizes](https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/general-purpose/dcesv6-series?tabs=sizebasic).

OCPBUGS-55772: Add support for Azure TDX confidential VM type

---

docs/user/azure/tested_instance_types_x86_64.md

Lsv4 and Lasv4 series are already tested by QE on 4.19, and they are preview in Azure now.
But based on Mak's comment https://issues.redhat.com/browse/CORS-3772?focusedId=27122387&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-27122387, they will be GA in Azure by mid-May which is before 4.19 release on June.

OCPBUGS-55817: add Lsv4 and Lasv4 series as tested

---

pkg/types/nutanix/helpers.go

Fix OCPBUGS-47719: 
[Nutanix] nil error displayed when setting a non-existing value in the preloadedOSImageName field

OCPBUGS-47719: [Nutanix] nil error displayed when setting a not exist value in preloadedOSImageName field

---

cmd/openshift-install/agent.go
pkg/asset/agent/image/agentpassword.go
pkg/asset/imagebased/image/imagebased_config_test.go
pkg/asset/password/password.go

For the agent-based installer OVE UI, the password files should also be created at boot via the 'agent create certificates' command. The kubeadmin-password and hash will be stored in the tls dir so that assisted-service does not regenerate them each time the call to GenerateInstallConfig is invoked.

OCPBUGS-55683: Pre-create password files for agent installer OVE

---

data/data/agent/systemd/units/agent-add-node.service
data/data/agent/systemd/units/agent-import-cluster.service.template
data/data/agent/systemd/units/agent-register-cluster.service.template
data/data/agent/systemd/units/agent-register-infraenv.service.template
data/data/agent/systemd/units/agent-start-ui.service.template
data/data/agent/systemd/units/apply-host-config.service
data/data/agent/systemd/units/pre-network-manager-config.service
data/data/agent/systemd/units/set-hostname.service
data/data/agent/systemd/units/start-cluster-installation.service
data/data/bootstrap/baremetal/systemd/units/extract-machine-os.service

It looks like the practice of setting `KillMode: none` began with podman-generate-systemd, and was copied and pasted into virtually every service. This could cause some weird behaviour when services were stopped.

OCPBUGS-53107: Set appropriate KillMode for systemd services

---

.golangci.yaml
scripts/openstack/manifest-tests/lb-unmanaged/install-config.yaml

Notes: there are other yaml-lint warnings but they've been there for a long time. This commit only focuses on the errors introduced during 4.19 cycle.

OCPBUGS-56079: apply fixes for yaml-lint errors

---

data/data/coreos/scos.json

Pulls in this fix: https://github.com/coreos/coreos-assembler/pull/4100 to update the live media.
Update to a newer bootimage before we release OKD for 4.19. This change was generated using:
```
plume cosa2stream --target data/data/coreos/scos.json                \
--distro rhcos --no-signatures --name c9s                        \
x86_64=9.0.20250510-0                                    \
aarch64=9.0.20250510-0                                    \
s390x=9.0.20250510-0                                      \
ppc64le=9.0.20250510-0
```

OKD-251: Update SCOS 4.19 bootimage metadata to 9.0.20250510-0

---

pkg/destroy/vsphere/client.go
pkg/destroy/vsphere/mock/vsphereclient_generated.go
pkg/destroy/vsphere/vsphere.go
pkg/destroy/vsphere/vsphere_test.go

[OCPBUGS-56262](https://issues.redhat.com/browse/OCPBUGS-56262)
- Enhanced logging to log creating client for each vCenter
- Enhanced logging to include vCenter name for each vCenter specific cleanup activity
- Enhanced logging to show when attempts start for each process
- Added log warning if no VMs are found during stop or destroy for virtual machines
- Fixed issue where the properties for VM were not including power state causing an issue where destroy would loop.

OCPBUGS-56262: Added better logging for vSphere destroy

---

docs/user/azure/tested_instance_types_x86_64.md

Manual backport the change for https://github.com/openshift/installer/pull/9696 and https://github.com/openshift/installer/pull/9696

OCPBUGS-56006: [release-4.19] CORS-3634, CORS-3771, CORS-3772: Azure doc: add support for Lsv4, Lasv4, Dxv6, NDs and NV series

---

data/data/coreos/rhcos.json

- Update to RHEL 9.6 GA Content
- OCPBUGS-55460 - [4.19] Enable RHCOS IBM Secure Execution installation on IBM Z17
```
x86_64=9.6.20250513-0                                     \
aarch64=9.6.20250513-0                                     \
s390x=9.6.20250513-0                                       \
ppc64le=9.6.20250513-0
```

OCPBUGS-55068: Update RHCOS 4.19 bootimage metadata to 9.6.20250513-0

---

data/data/coreos/rhcos.json

The changes done here will update the RHCOS 4.20 bootimage metadata. Notable changes in the boot image are:
- Update to RHEL 9.6 GA Content
- OCPBUGS-55906: Enable RHCOS IBM Secure Execution installation on IBM Z17
```
x86_64=9.6.20250513-0                                     \
aarch64=9.6.20250513-0                                     \
s390x=9.6.20250513-0                                       \
ppc64le=9.6.20250513-0
```

OCPBUGS-55905: Update RHCOS 4.20 bootimage metadata to 9.6.20250513-0

---

pkg/types/utils.go

On AzureStack, we don't expect a user-assigned
identity to be assigned to nodes. This updates the create identity helper function to reflect that.

OCPBUGS-56008: don't expect identity on ASH

---

pkg/infrastructure/azure/azure.go
pkg/types/azure/validation/machinepool.go

Removes unnecessary validation that prevents setting the None identity type on compute nodes.

OCPBUGS-56008: Remove unnecessary validation

---

data/data/coreos/rhcos.json

The changes done here will update the RHCOS 4.20 bootimage metadata.
```
x86_64=9.6.20250523-0                                     \
aarch64=9.6.20250523-0                                     \
s390x=9.6.20250523-0                                       \
ppc64le=9.6.20250523-0
```

OCPBUGS-56645: Update RHCOS 4.20 bootimage metadata to 9.6.20250523-0

---

pkg/types/installconfig.go

** The MultiArchInstallGCP feature gate has been enabled by default. This change removes the check for the feature gate during gcp installs, and the feature gate is treated as enabled by default.

OCPBUGS-55672: Remove MultiArchInstallGCP featuregate

---

pkg/asset/machines/master.go
pkg/asset/machines/master_test.go

Installer can be used to provision Single Node OpenShift(SNO) only for AWS, GCP, Azure, PowerVS and Baremetal.
SNO is not supported on all on-prem platforms yet. Even on the platforms that support SNO installs, the install method currently supported are assisted/agent/ZTP.
Since, other install methods like ABI (agent based install) layer their install config validation over the Installer's own validation, this validation (that is sensitive to install method) was added while generating manifests in the IPI path.

OCPBUGS-6508: Update Control Plane replica validation for Single Node OpenShift

---

pkg/asset/manifests/infrastructure_test.go

Adds unit tests for the problems addressed by #9743
/hold
for #9743 merge

no-jira: add unit tests for vsphere VIPS/machinenetworks population

---

pkg/types/gcp/validation/platform.go

The `GCPServiceEndpointNameTagManager` is removed from API, so the reference(s) should be removed from the installer.

OCPBUGS-56808: Remove configv1.GCPServiceEndpointNameTagManager references

---

upi/openstack/down-containers.yaml

When there is OpenStack deployment, which doesn't have swift services, or there are no containers used at all, listing them will fail the playbook and leave exit code other than 0, which may interrupt CI.
With this commit, errors from listing containers will be ignored, which will cover both cases.

OCPBUGS-54413: Make swift containers removal not fatal for UPI.

---

pkg/asset/manifests/clustercsidriver.go

pkg/asset/manifests/clustercsidriver.go:
** When the default GCP Platform KMS Key info does not include the location and/or Porject ID, default to using the values set in the installconfig under the GCP platform.

OCPBUGS-51299: Set default project and location for KMS key manifest

---

data/data/bootstrap/bootstrap-in-place/files/opt/openshift/bootstrap-in-place/master-update.fcc

With multi-node installations the settings for /var/lib/etcd are 0700. This should be the same from SNO but the bootstrap-in-place ignition is setting it to 0755.

OCPBUGS-57021: Use less permissive access for /var/lib/etcd for SNO

---

pkg/asset/quota/aws/instancetypes.go
pkg/asset/quota/quota.go

Part of CORS-3819, this focuses on the quote checking code for EC2 instance types.
**Note**: This only upgrades code for fetching instance types during quota check. Full quote code upgrades to v2 is being tracked in [CORS-4061](https://issues.redhat.com/browse/CORS-4061).
**Questions**: User-provided service endpoints were never considered here. Is this intentional?

CORS-4057: migrate EC2 quota checking code AWS SDK v2

---

pkg/asset/installconfig/nutanix/nutanix.go

`pe.UUID = *pesMap[selectedPe].Metadata.UUID
pe.Endpoint.Address = *pesMap[selectedPe].Spec.Resources.Network.ExternalIP`
Can cause panic if the chained values are not present.
Adding check for the chained fields and return the meaningful errors.

OCPBUGS-57192: Checking for selected PE retrieved data and returning errors for missing values

---

pkg/types/vsphere/validation/platform.go
pkg/types/vsphere/validation/platform_test.go

If the vsphere failure domain region names are the same across multiples the zones cannot be duplicated.
This commit adds this validation and unit tests.

OCPBUGS-41879: vSphere - if regions are the same cannot dup zones

---

pkg/asset/machines/master.go

This PR allows back deployment of single node openshift using UPI with platform None and without bootstrap in place, since it has worked fine for ever and is used at least internally

OCPBUGS-58216: allow to deploy single nodes with UPI

---

pkg/asset/installconfig/aws/ec2.go

** The credentials changed in AWS SDK V2. When the AWS_PROFILE environment variable was set to an invalid value the install would not proceed through the failure. The inention was to ask for the aws key and id information. Now the information will be added to the survey, and the information will be added to the config in .aws.

OCPBUGS-57923: When AWS_PROFILE is invalid ask for credentials

---

cmd/openshift-install/agent/waitfor.go
cmd/openshift-install/command/gather.go
cmd/openshift-install/command/waitfor.go
cmd/openshift-install/create.go
cmd/openshift-install/gather.go
cmd/openshift-install/main.go
cmd/openshift-install/waitfor.go
pkg/agent/cluster.go
pkg/agent/kube.go
pkg/agent/ocp.go
pkg/agent/waitfor.go

Removed custom agent wait-for install-complete code.
Moved installer WaitForInstallComplete function from cmd/openshift-install/main to cmd/openshift-install/command so that the function can be made public.
Modified agent.newWaitForInstallCompleted() to use the common WaitForInstallComplete function.
The benefit of moving agent over to the common WaitForInstallComplete function is that the common function has a step to wait for operators to be in a stable state before calling the cluster installation complete.

OCPBUGS-18658 OCPBUGS-45256: Unify agent install-complete with installer

---

data/data/install.openshift.io_installconfigs.yaml
pkg/asset/machines/azure/azuremachines.go
pkg/asset/machines/azure/machines.go
pkg/types/azure/machinepool.go
pkg/types/azure/validation/featuregates.go
pkg/types/azure/validation/machinepool.go
pkg/types/azure/validation/machinepool_test.go
pkg/types/azure/validation/platform.go
pkg/types/validation/machinepools.go

This PR adds to the machinepool a new field datadisks to allow a user to add additional disks at installation time.
- Adds capz DataDisks slice to the machine pool
- Convert capz datadisk to mapi datadisk
- Adds new feature gate for azure multi disk
- Adds validation for datadisks
- Adds machine pool testing
- https://github.com/openshift/installer/pull/9706/files
- https://github.com/openshift/api/pull/2289
- https://github.com/openshift/enhancements/pull/1779

SPLAT-2294: Azure - add mpool datadisks

---

data/data/powervs/cluster/loadbalancer/sg.tf
data/data/powervs/cluster/loadbalancer/variables.tf
data/data/powervs/cluster/main.tf

If source network address translation is not allowed, i.e. during an installation in a restricted network, incoming traffic on port 5000 should be allowed as the user created image registry is accessible on this port. Allow it.

OCPBUGS-36677: Power VS: Enable incoming traffic on port 5000 during installation in a restricted network 

---

pkg/asset/agent/installconfig_test.go
pkg/types/validation/installconfig.go
pkg/types/validation/installconfig_test.go

• This commit enhances VIPs validation to ensure the primary IP family of the VIPs matches the primary IP family of all the network fields. 
• Code repurposed from prior closed PR (#7504)

OSASINFRA-3238: Improve API and Ingress VIPs validation

---

pkg/infrastructure/gcp/clusterapi/operation.go

** The child context was set at 1 minute. This should be long enough to determine if an operation has completed. However, the HIVE team noticed a timeout. Increasing the timeout to 2 minutes for the wait for operation.

OCPBUGS-58352: Increase timeout on gcp wait for operation

---

pkg/asset/installconfig/basedomain.go

** Update the vendor code to include aws/retry. This package will be
used for throttling error checks.
pkg/asset/installconfig/basedomain.go:
** Use the sdk v2 to check whether the error is a throttle error.

CORS-4054: Migrate from SDK v1 to v2 in installconfig

---

go.mod
pkg/asset/cluster/aws/aws.go

** The IAM, EC2, and Route53 clients were moved to SDK v2. This included migration from session to config (and use of endpoints).

CORS-4053: Migrate AWS SDK to v2 in cluster/aws

---

pkg/asset/installconfig/aws/permissions.go
pkg/asset/installconfig/aws/regions.go
pkg/asset/manifests/cloudproviderconfig.go
pkg/asset/tls/cloudprovidercabundle.go
pkg/types/aws/platform.go

pkg/types/aws:
** Remove the endpoints package from aws sdk v1.
** Remove the function to check for secret regions
pkg/asset/installconfig/aws:
** Add a function to check for secret regions.
** The function was moved here (and changed) because the types package should not make api calls. As we migrated to aws sdk v2 the partitions are no longer publicly available BUT we can access them through endpoints. To get the partition we go through the ec2 api (make a proxy call) and get the endpoint from that call then the endpoint will provide us with the partition.

CORS-4062: Migrate endpoints in pkg/types/aws/platform.go to sdk v2

---

pkg/asset/installconfig/aws/platform.go
pkg/types/aws/regions.go

pkg/types/aws/regions.go: Create a map of the region to the descriptive name
pkg/asset/installconfig/aws/platform.go: Add the description information to the survey.

OCPBUGS-57527: Add descriptions back to the aws survey

---

pkg/destroy/gcp/gcp.go

pkg/destroy/gcp/gcp.go:
** In the case where no error exists but the operation is nil when passed into gcp.go:handleOperation the destroy process would cause a system panic. Now create an error in this case so that the destroy process will continue and retry if there are more pending items.

OCPBUGS-57732: Catch gcp destroy cases where the operation is nil

---

data/data/install.openshift.io_installconfigs.yaml
pkg/asset/cluster/powervs/powervs.go
pkg/asset/installconfig/powervs/client.go
pkg/asset/installconfig/powervs/metadata.go
pkg/asset/installconfig/powervs/mock/powervsclient_generated.go
pkg/asset/installconfig/powervs/mock/powervsmetadata_generated.go
pkg/asset/installconfig/powervs/validation.go
pkg/asset/installconfig/powervs/validation_test.go
pkg/asset/manifests/cloudproviderconfig.go
pkg/asset/manifests/powervs/cluster.go
pkg/destroy/powervs/cloud-transit-gateways.go
pkg/destroy/powervs/powervs.go
pkg/types/powervs/metadata.go
pkg/types/powervs/platform.go
pkg/types/powervs/validation/machinepool_test.go

Currently you can only specify a name for an existing Transit Gateway or Virtual Private Cloud.  This can lead to issues since names are not guaranteed to be unique.  So allow a UUID instead of a name.

OCPBUGS-59678: PowerVS Support VPC and TG ids

---

docs/user/openstack/install_upi.md
images/openstack/Dockerfile.ci
upi/openstack/inventory.yaml
upi/openstack/network.yaml

Prefer RPM over dependencies coming from pip or ansible galaxy.
Manual cherry-pick of https://github.com/openshift/installer/pull/8830.

OCPBUGS-39416: OpenStack: Install CI dependencies from rpm

---

images/installer-altinfra/Dockerfile.ci
images/installer/Dockerfile.upi.ci
images/libvirt/Dockerfile.ci
images/openstack/Dockerfile.ci

openshift-bot created PRs to bump several images:
https://github.com/openshift/installer/pull/9801
https://github.com/openshift/installer/pull/9800
https://github.com/openshift/installer/pull/9799
But those didn't get all images. Bumping the rest here.

no-jira: images: bump images to go 1.24

---

data/data/coreos/rhcos.json

The changes done here will update the RHCOS 4.20 bootimage metadata. A notable change is adding the kubevirt artifact for s390x.
```
x86_64=9.6.20250701-0                                     \
aarch64=9.6.20250701-0                                     \
s390x=9.6.20250701-0                                       \
ppc64le=9.6.20250701-0
```

OCPBUGS-59630: Update RHCOS 4.20 bootimage metadata to 9.6.20250701-0

---

pkg/asset/installconfig/gcp/validation.go
pkg/asset/installconfig/gcp/validation_test.go

1c9589a21f816b317628b85412acf3fdda3893f6 added validation to require an existing DNS zone matching the base domain before installation. In custom DNS scenarios, it is valid to create the zone after install, so we should relax the validation in those cases.

CORS-3992: skip dns zone validation with custom DNS

---

OWNERS
OWNERS_ALIASES

SPLAT team should be approvers in the installer repo, as well as CI.

no-jira: OWNERS: add splat team as approvers

---

pkg/asset/machines/nutanix/machinesets.go
pkg/asset/machines/nutanix/machinesets_test.go

The Machinesets were not generated for Autoscaling i.e. when replica is nil.
Fix:
Creating and distributing machinesets across failureDomains even if replica is nil.

OCPBUGS-59542: Generated Nutanix MachineSets for Autoscaling with Failure Domains

---

pkg/asset/ignition/bootstrap/baremetal/template.go

Previously, we did not set this parameter on v6-primary stacks, wrongly
assuming that the Ironic container would pick up the right stack.
It wouldn't. Presenting with both IP addresses, the networking logic in
the container picks up the first one, which is usually IPv4.
This breaks virtual media on BMC's that cannot access IPv4 addresses.

OCPBUGS-60240: baremetal: always set external v6 URL on dualstack

---

docs/dev/rr-debugging.md
docs/dev/rr-debugging.patch

This is some quick docs to allow the
use of `rr` to troubleshoot and trace
difficult cluster api provider problems.
Assisted-by: cursor

no-jira: dev docs - add rr capi debugging

---

pkg/asset/agent/manifests/agentclusterinstall.go
pkg/asset/agent/manifests/agentclusterinstall_test.go
pkg/asset/agent/manifests/util_test.go

Fail immediately when generating the Agent ISO if the clusterNetworks
will not pass muster with assisted-service.

OCPBUGS-53473: Validate clusterNetwork hostPrefix

---

data/data/agent/systemd/units/agent-extract-tui.service

The tar file path was changed in https://github.com/openshift/agent-installer-utils/pull/132 when the image was switched to agent-installer-ui.
The path to the tar file in agent-extract-tui.service now needs to be updated.

AGENT-1205: Update agent-installer-ui tar path

---

data/data/coreos/rhcos.json

Address the following issues:
OCPBUGS-55840 - [4.18] Enable RHCOS IBM Secure Execution installation on IBM Z17
```
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --no-signatures \
--name 4.18-9.4 \
x86_64=418.94.202508060022-0 \
aarch64=418.94.202508060022-0 \
s390x=418.94.202508060022-0 \
ppc64le=418.94.202508060022-0
```

OCPBUGS-54598: Update the RHCOS 4.18 bootimage metadata

---

upi/azurestack/03_infra.json
upi/azurestack/04_bootstrap.json
upi/azurestack/05_masters.json
upi/azurestack/06_workers.json

4.19 UPI installation on Azure Stack Hub failed when waiting for cluster completed, ingress operator was degraded, see below error reported from ingress operator:
```
2025-08-18T07:31:57.379Z        ERROR   operator.ingress_controller     controller/controller.go:118    got retryable error; requeueing {"after": "1m0s", "error": "IngressController is degraded: LoadBalancerReady=False (SyncLoadBalancerFailed: The service-controller component is reporting SyncLoadBalancerFailed events like: Error syncing load balancer: failed to ensure load balancer: PUT https://management.mtcazs.wwtatc.com/subscriptions/d751283a-64fa-401b-92a1-58f1750ac0a7/resourceGroups/jima419-xwlcj-rg/providers/Microsoft.Network/loadBalancers/jima419-xwlcj\n----------------------------------------------------------------- …
```

OCPBUGS-60545: Azure: change LB and pubic IP skus to Standard

---

data/data/coreos/rhcos.json

Address the following issues:
- OCPBUGS-54596 [4.17] Need to update Base ISO 'discovery ISO' image for 4.17
- OCPBUGS-55841 [4.17] Enable RHCOS IBM Secure Execution installation on IBM Z17
```
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos --no-signatures \
--name 4.17-9.4 \
x86_64=417.94.202507291008-0 \
aarch64=417.94.202507291008-0 \
s390x=417.94.202507291008-0 \
ppc64le=417.94.202507291008-0
```

OCPBUGS-54599: Update the RHCOS 4.17 bootimage metadata

---

pkg/asset/ignition/bootstrap/baremetal/template.go

Previously, we did not set this parameter on v6-primary stacks, wrongly assuming that the Ironic container would pick up the right stack. It wouldn't. Presenting with both IP addresses, the networking logic in the container picks up the first one, which is usually IPv4. This breaks virtual media on BMC's that cannot access IPv4 addresses.
(cherry picked from commit 4aa85eec233aab1a843dbb7144450854fe7fb28f)

[4.18] OCPBUGS-60592: baremetal: always set external v6 URL on dualstack

---

data/data/coreos/rhcos.json

This reverts commit 702c738be06c962d5f13614fcbf051092ae41044.
The live ISO in that bootimage set contains a change to the volume ID which would break the Assisted Image Service:
https://github.com/openshift/assisted-image-service/pull/477
We're working on pushing out new ISOs with the reverted volume ID in: https://github.com/coreos/coreos-assembler/pull/4276
But for now revert this to ensure it doesn't slip into the next z-stream release.

[release-4.19] Revert "Update RHCOS 4.19 bootimage metadata to 9.6.20250811-0"

---

upi/vsphere/powercli/upi-functions.ps1
upi/vsphere/powercli/upi.ps1

[SPLAT-2463](https://issues.redhat.com//browse/SPLAT-2463)
- Enhanced UPI powercli scripts to support configuring CoresPerSocket
Originally the scripts did not pass in a value for CoresPerSocket and just set it to 4 by default.  This is an issue if you want to do a non multiple of 4 for the NumCpu

SPLAT-2463: Added ability to configure CoresPerSocket

---

data/data/coreos/rhcos.json

The changes done here will update the RHCOS 4.19 bootimage metadata and address the following issues:
OCPBUGS-60664 - [4.19] linux-firmware updates required for GNR-D hardware
```
plume cosa2stream --target data/data/coreos/rhcos.json                     \
--distro rhcos --no-signatures --name rhel-9.6 \
--url https://rhcos.mirror.openshift.com/art/storage/prod/streams                                               \
x86_64=9.6.20250826-1                                    \
aarch64=9.6.20250826-1                                   \
s390x=9.6.20250826-1                                     \
ppc64le=9.6.20250826-1
```

OCPBUGS-60925: Update the RHCOS 4.19 bootimage metadata

---

data/data/install.openshift.io_installconfigs.yaml
pkg/asset/cluster/gcp/gcp.go
pkg/asset/cluster/tfvars/tfvars.go
pkg/asset/installconfig/gcp/client.go
pkg/asset/installconfig/gcp/dns.go
pkg/asset/installconfig/gcp/mock/gcpclient_generated.go
pkg/asset/installconfig/gcp/validation.go
pkg/asset/installconfig/gcp/validation_test.go
pkg/asset/manifests/dns.go
pkg/destroy/gcp/dns.go
pkg/destroy/gcp/gcp.go
pkg/infrastructure/gcp/clusterapi/dns.go
pkg/infrastructure/gcp/clusterapi/labels.go
pkg/types/gcp/dns.go
pkg/types/gcp/metadata.go
pkg/types/gcp/platform.go
pkg/types/gcp/validation/platform.go
pkg/types/gcp/validation/platform_test.go

install.openshift.io_installconfigs.yaml:
** Updated fields from the types/installconfig/gcp
pkg/types/gcp/platform.go:
** Add the user specified private dns zone
** Add static validation
pkg/asset/installconfig/gcp/validation.go:
** When private dns zone information is provided, ensure that the project and zone are used for validation.
** The public zone should be in the same project as the private zone. When the private zone is provided, assume the same project for public zone validation.

CORS-4044, CORS-4045, CORS-4046, CORS-4047, CORS-4048, CORS-4049, CORS-4050, CORS-4051: Add private dns zone section to GCP install config

---

pkg/asset/cluster/tfvars/tfvars.go
pkg/asset/manifests/dns.go
pkg/infrastructure/gcp/clusterapi/clusterapi.go
pkg/infrastructure/gcp/clusterapi/dns.go
pkg/types/gcp/dns.go

pkg/asset/manifests/dns.go:
** Find private DNS zone for XPN installs even when the user did not specify one. If there is an existing private DNS zone then the user can bring that for XPN installs. This fixes a regression that forced users to enter the name or use the default name for private zones.

OCPBUGS-61111: Allow user to BYO private zone without specifying name

---

data/data/bootstrap/baremetal/files/usr/local/bin/build-metal3-env.sh
data/data/bootstrap/files/usr/local/bin/bootstrap-verify-api-server-urls.sh
data/data/bootstrap/files/usr/local/bin/installer-gather.sh
data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh

This patch addresses these shellcheck errors:
```
./data/data/bootstrap/baremetal/files/usr/local/bin/build-metal3-env.sh:3:10: warning: In POSIX sh, set option pipefail is undefined. [SC3040]
./data/data/bootstrap/files/usr/local/bin/bootstrap-verify-api-server-urls.sh:13:11: note: Use -n instead of ! -z. [SC2236]
./data/data/bootstrap/files/usr/local/bin/installer-gather.sh:9:9: note: Avoid x-prefix in comparisons as it no longer serves a purpose. [SC2268]
./data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh:6:9: note: Avoid x-prefix in comparisons as it no longer serves a purpose. [SC2268]
```
Seen in https://storage.googleapis.com/test-platform-results/pr-logs/pull/openshift_release/67587/rehearse-67587-pull-ci-openshift-installer-main-shellcheck/1964017457890856960/bu …

OCPBUGS-61373: Fix shellcheck issues in bootstrap

---

pkg/asset/imagebased/image/baseiso.go
pkg/asset/imagebased/image/baseiso_test.go
pkg/asset/imagebased/image/imagebased_config.go
pkg/asset/imagebased/image/imagebased_config_test.go
pkg/types/imagebased/imagebased_config_types.go

Recently LCA operator added support for ARM-based clusters, and we want to extend that support to image-based installations.
This PR adds the option for users to choose the architecture they want and specify arm64 as it's value.

MGMT-21586: Add an option in image-based installation to specify architecture

---

pkg/types/gcp/validation/featuregates.go
pkg/types/validation/featuregate_test.go

Remove check for this featuregate since the feature has been promoted to GA. 
openshift/api version update is going to be part of a larger effort to update several packages.

CORS-4162: Remove GCPClusterHostedDNSInstall featuregate

---

data/data/install.openshift.io_installconfigs.yaml
pkg/explain/fields_lookup_test.go
pkg/explain/printer_test.go
pkg/types/installconfig.go

Update the publish strategy to include "Mixed" (it was left out of the kube enum). 
Update the explain commands to ensure the Mixed info is present.

OCPBUGS-61901: Update explain for Publish

---

pkg/destroy/gcp/gcp.go

** On upgrades, the PrivateZonePRojectID in the metadata will be left empty. This caused the deletion of Private DNS Zones to fail during an install from 4.19 that was upgrade to 4.20. In 4.20+ the field is expected and would contain the correct default value, but this field was unknown to 4.19. The field is now filled with the ProjectID when one does not exist.

OCPBUGS-62293: Set default for PrivateDNSZone Project ID

---

pkg/destroy/gcp/gcp.go

Picks #9967 
** On upgrades, the PrivateZonePRojectID in the metadata will be left empty. This caused the deletion of Private DNS Zones to fail during an install from 4.19 that was upgrade to 4.20. In 4.20+ the field is expected and would contain the correct default value, but this field was unknown to 4.19. The field is now filled with the ProjectID when one does not exist.

OCPBUGS-62297: Set default for PrivateDNSZone Project ID

---

pkg/infrastructure/gcp/clusterapi/clusterapi.go
pkg/infrastructure/gcp/clusterapi/firewallrules.go

** If the user did not have the firewall create permission it was possible for the user to skip the creation of gcp firewall rules and their creation is left to the user. When the user does have the firewall create permission but is missing the delete permission it was possible for the bootstrap firewall rules to be skipped leaking resources. Typically these permissions should be paired together, but if a user accidentally left the destroy out we were failing to check for this permission. Now the permission is checked to ensure that any resource created by the installer is also destroyed.

OCPBUGS-61514: Add check for gcp firewall deletion permission

---

pkg/asset/releaseimage/default.go

Updating default release image to latest version 4.21.

CORS-4107: Update default release image to 4.21

---

data/data/install.openshift.io_installconfigs.yaml
pkg/types/gcp/platform.go

** Provide the user with the ability to specify the name of the private service connect endpoint and the location. When the region is empty it is assumed to be a global location.

CORS-4256: Add PSC Endpoint to the installconfig
