openshift/installer

- tests/jenkins-jobs/README.md
- tests/jenkins-jobs/openshift_installer_nightly_trigger.groovy
- tests/jenkins-jobs/openshift_installer_public_pr_trigger.groovy
This synchronizes config from Jenkins with one stored in code.
> cleanup names in jenkins files and in readme

- installer/pkg/config-generator/tls.go
- installer/pkg/config-generator/utils.go
- installer/pkg/tls/BUILD.bazel
- installer/pkg/tls/tls.go
- installer/pkg/tls/tls_test.go
- installer/pkg/tls/utils.go
- installer/pkg/validate/validate_test.go
> installer/pkg/config-generator/tls: generate intermediate CAs

- tests/smoke/cluster_test.go
Comment-out flaky killAPI test.
> disable killAPI test

- installer/pkg/config-generator/tls.go
> installer/pkg/config-generator/tls: add certificate validity

- installer/pkg/tls/tls.go
The subject key id is used to later populate the "Authority Key Identifier" in the certificate (https://tools.ietf.org/html/rfc5280#page-27). This PR adds this field.
> installer/pkg/tls: add missing cert flags

- installer/pkg/config-generator/tls.go
This commit adds TLS artifact generation for etcd to the installer.
/cc @trawler @spangenberg @enxebre
> config-generator: add etcd TLS

- images/tectonic-installer/Dockerfile.ci
Change workdir path from coreos to openshift one.
> Change workdir in Dockerfile for prow CI

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.md
- Documentation/dev/libvirt-howto.md
- builder-run
- images/tectonic-builder/Dockerfile
Run simple `grep "tectonic-installer" -R .` and changed couple of names. Mostly in docs, but also in builder dockerfile.
> update tectonic-installer -> openshift installer in docs and builder img

- Documentation/design/renderphase.md
Adds design doc for render.
NOTE: update installer-operator render interface decisions and design later.
> Documentation/design: add render design

- Documentation/design/initphase.md
> Documentation/design: add init phase design

- .travis.yml
- hack/test-bazel-build-tarball.sh
CORS-751
This PR moves the current travis test 'bazel build tarball' to Prow
> Move bazel build tarball test to prow

- Documentation/dev/libvirt-howto.md
If you destroy and re-init a bunch, it does go faster.
> Add note about how to cache terraform plugins

- steps/bootstrap/libvirt/main.tf
> steps/bootstrap/libvirt: add pty to bootstrap node

- OWNERS_ALIASES
At @yifan-gu's [request][1].
/assign @yifan-gu
[1]: https://github.com/openshift/installer/pull/184#discussion_r214209420
> OWNERS_ALIASES: Add rajatchopra and staebler as approvers

- OWNERS_ALIASES
Welcome (back) aboard, @steveeJ :).
/assign @yifan-gu
> OWNERS_ALIASES: Add steveeJ to installer-approvers

- config.tf
- modules/bootkube/resources/manifests/machine-config-operator-01-images-configmap.yaml
need this for cri-o pull to work with default settings
@abhinavdahiya
> fully qualify mco images

- config.tf
- modules/ignition/assets.tf
- modules/ignition/outputs.tf
- modules/ignition/resources/files/crio-network
- modules/ignition/resources/services/kubelet.service
@abhinavdahiya @mrunalp @derekwaynecarr @rphillips
xref https://github.com/openshift/machine-config-operator/pull/62
> switch to crio

- pkg/asset/manifests/kube-addon-operator.go
This re-uses the rand.String() implementation from Kubernetes instead of
Base64-encoding some random bytes.
> asset/manifests: remove custom password generation

- modules/ignition/resources/services/kubelet.service
See for details: https://github.com/openshift/openshift-ansible/pull/10177
Doing this now so we don't get hung up on it again.
/cc @sjenning @mrunalp
> Fix stats summary endpoint for kubelet

- examples/aws.yaml
> examples/aws: Show how to list public Route 53 zones

- README.md
@wking this should prevent a few questions in slack.
> README add to run hack/get-terraform.sh

- docs/dev/libvirt-howto.md
These changes catch us up with the recent shift from `tectonic` to `openshift-install`.
I also:
* Dropped the section numbers, since these are tedious to maintain.  The ordering should be clear enough from whether a section is above or below in the file ;).
* Dropped/adjusted references for settings which are no longer configurable, although we might restore the ability to configure IP ranges, RHCOS image, etc., in the future.
* Dropped the 30-min caveat.  The cluster comes up faster now, but I don't have a more accurate time to plug in, so I've just dropped that line.
CC @crawford, @ashcrow, @aveshagarwal, @vikaschoudhary16
Partial fix for #368.
> docs/dev/libvirt-howto: Reroll for openshift-install

- docs/user/environment-variables.md
- pkg/asset/installconfig/platform.go
Add prompt for libvirt image, no change in default.
/cc @wking @crawford
> installconfig: libvirt image prompt

- README.md
List the supported platforms in the README.  I wanted to note that the
OpenStack support is still experimental and needs more work and didn't
see an obvious other place to do that.
> README.md: Document supported platforms.

- pkg/types/config/libvirt/cache.go
Libvirt can't use the HTTP cache directly, because the cached content contains HTTP headers and other metadata.  Rather than writing our own [HTTP cache][1] to perform this unpacking, I've just added a separate cache layer for the unpacked images.
I'm currently trusting upstream ETags as cache keys, but if we want to be paranoid at the expense of hashing a gigabyte or two of data, we could use SHA1 sums of the payload or similar.
I'm using [`Flock`][2] to protect against parallel calls racing unpacks. My intention is to have:
1. Alice gets the lock, starts unpacking into the image cache.
2. Bob blocks on the lock.
3. Alice finishes unpacking and renames to the final filename.
4. Charlie hits the same ETag and grabs the unpacked image without even checking the lock.
5. Alice releases the …
> pkg/types/config/libvirt/cache: Cache unpacked files as well

- data/data/openstack/topology/sg-master.tf
- data/data/openstack/topology/sg-worker.tf
Adds egresses to the worker and master security groups
> openstack: Adds egresses to the worker and master

- pkg/asset/manifests/content/bootkube/etcd-service-endpoints.go
- pkg/asset/manifests/content/bootkube/etcd-service.go
- pkg/asset/manifests/operators.go
- pkg/asset/manifests/template.go
> assets/bootkube: add etcd service and endpoints for apiservers.

- pkg/asset/store.go
Before this change, when the installer found an asset in both the target
directory and the state file, it assumed that the asset should be dirty,
causing the asset and all of its dependants to be regenerated. This is a
small optimization that prevents regenerating dependant assets when the
provided asset is identical to the one in the state file.
> asset/store: try to reuse assets from state file

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/openshift/hive/contrib/pkg/awstagdeprovision/awstagdeprovision.go
The latest code contains some fixes for teardown which will hopefully
address the race condition where hive and Machine API operator compete
to destroy and create resources.
> vendor: bump github.com/openshift/hive

- data/data/aws/main.tf
- data/data/libvirt/main.tf
This requires: https://github.com/openshift/installer/pull/596; https://github.com/openshift/machine-config-operator/pull/155
/cc @crawford
>  data/data: remove old unused etcd srvs records 

- OWNERS_ALIASES
CC @yifan-gu, because I think we'd be happy to keep you in here if you want to keep contributing on the side ;).
> OWNERS_ALIASES: Yifan has moved on to other things :(

- pkg/asset/manifests/content/bootkube/cvo-overrides.go
The name changed between when this PR was created and the newer CVO
PR was updated.
> assets: The CVO object name has changed

- .github/ISSUE_TEMPLATE.md
platform is `openstack` not `openshift`
> fix issue template

- data/data/bootstrap/files/opt/tectonic/bootkube-config-overrides/kube-scheduler-config-overrides.yaml
- data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
>  Drop phase 2 for kube-scheduler.

- docs/user/troubleshooting.md
Because this is the next step beyond "my cluster didn't install, here's the `--log-level=debug` output", for folks working up bug reports that don't match one of the common failures.
CC @crawford
> docs/user/troubleshooting: Add generic advice for getting pod details

- data/data/bootstrap/files/etc/motd
- data/data/bootstrap/files/home/core/.bash_history
- pkg/asset/ignition/bootstrap/bootstrap.go
The intention here is to help people debug.  If you like this
I may also try to do something similar for masters.
> bootkube: Add info to /etc/motd and a bit to /root/.bash_history

- data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
- pkg/asset/installconfig/installconfig.go
Follow-up of https://github.com/openshift/installer/pull/658 with necessary kube-apiserver flag.
> installconfig: change default network blocks

- pkg/asset/manifests/ingress.go
Fixes https://github.com/openshift/installer/pull/717#issuecomment-442245982
> asset/manifests: fix filepath for ingress crd

- data/data/bootstrap/systemd/units/kubelet.service.template
> data: do not use kubelet lock file and boost log level

- cmd/openshift-install/create.go
First, print the total amount of time we're going to wait.
Now, I had an issue where my cluster was fine but my dev container's
DNS didn't have `127.0.0.1` for my dnsmasq; it would have been a lot more obvious
to me if I clearly saw DNS errors.
Tweak the logging here so that we log when the error message
changes, but only do it after 30 seconds have elapsed.
This seems to work fairly well for me except that we flap a bit
because we alternate between the bootstrap/master.
But still I think this is worth it for the debugging/info value.
> Log more verbosely when waiting for bootstrap completion

- docs/dev/libvirt-howto.md
> docs: dns is required for libvirt clusters

- README.md
> README.md: Pedantic capitalization nit.

- pkg/asset/installconfig/installconfig.go
- pkg/asset/installconfig/installconfig_test.go
Rename install-config.yml to install-config.yaml.
Deprecate installconfig.yml. The InstallConfig asset will attempt to load install-config.yaml first. If that file does not exist, then the asset will attempt to load the install-config.yml file. If that file exists, the asset will generate a warning log entry informing the user that the install-config.yml file is deprecated.
> asset/installconfig: rename install-config.yml to install-config.yaml

- README.md
Catching up with 6be4c253 (#861).
Also link to the troubleshooting docs, since the easier it is to discover those, the fewer bug reports we'll get with insufficient detail ;).
> README: Replace stale environment variable reference

- pkg/terraform/exec/exec.go
- pkg/terraform/exec/plugin.go
- pkg/terraform/exec/plugin_release.go
> terraform: only use embedded plugins when `release` tag is set

- pkg/asset/installconfig/basedomain.go
/cc @wking @staebler 
Fixes #957
> asset/installconfig: fallback to freeform basedomain on aws on throttle error

- CONTRIBUTING.md
- hack/go-genmock.sh
- images/mock/Dockerfile
- pkg/asset/mock/filefetcher_generated.go
- pkg/types/openstack/validation/mock/validvaluesfetcher_generated.go
Create a script for generating the test mocks.
> script for generating mock

- CHANGELOG.md
Through c0104bd6 (#970).
CC @abhinavdahiya, @crawford
> CHANGELOG: Document changes since v0.7.0

- .gitignore
This was erroneously added way back in 06c5fd36.
> git: remove log from gitignore

- pkg/destroy/aws/aws.go
Builds on #1037; review that first.
Also alphabetize all the non-stdlib imports in a single block.
The logrus import change is similar to our earlier 54ba6a75 (#534).
> pkg/destroy/aws: "log" -> "logrus" and use pkg/errors

- docs/user/openstack/README.md
Update the user docs with the currently necessary step of manually
creating the openstack-credentials Secret.
> openstack: Document creation of openstack-credentials.

- data/data/openstack/lb/main.tf
We need this so that we inject the SSH key into the service VM.
> openstack: append to bootstrap ignition for the service vm config

- docs/user/troubleshooting.md
These landed recently in openshift/machine-config-operator@45beeccd (openshift/machine-config-operator#286).
> docs/user/troubleshooting: Link to MCD SSH-key docs

- docs/user/troubleshooting.md
> docs/user/troubleshooting: Link Knowledgebase article

- CHANGELOG.md
> CHANGELOG: Document changes since v0.10.0

- docs/user/troubleshooting.md
Update for https://github.com/openshift/cluster-network-operator/pull/68
> Update network troubleshooting docs for naming changes

- data/data/openstack/service/main.tf
Commit #1180 changed the MCO port from 4900 to 22623, which broke
OpenStack deployments as the replace didn't catch 2 places where the
port was still hardcoded.
In addition, I've decoded the data URL to make the maintenance of this
script easier.
> openstack: Change MCO port

- docs/user/aws/customization.md
docs/user/aws: update customization for controlPlane/compute
The machine field in install-config.yaml has been replaced with the controlPlane
and compute fields. The docs/user/aws/customization.md file needs to be updated
to reflect the change in the structure of install-config.yaml.
> update doc to use new customization yaml format

- OWNERS_ALIASES
Rajat has moved onto another project.
> OWNERS_ALIASES: remove Rajat

- CHANGELOG.md
Through 6b6b55bd (#1270), following up on #1270 since we didn't end up cutting a release on top of that commit.
> CHANGELOG: Document changes since 8f08508

- pkg/asset/machines/aws/machines.go
- pkg/asset/machines/aws/machinesets.go
- pkg/asset/machines/libvirt/machines.go
- pkg/asset/machines/libvirt/machinesets.go
- pkg/asset/machines/openstack/machines.go
- pkg/asset/machines/openstack/machinesets.go
> Rename labels from sigs.k8s.io to machine.openshift.io

- pkg/asset/installconfig/aws/permissions.go
Save an API request if we already know we have sufficient authorization.
> pkg/asset/installconfig/aws/permissions: If we can mint, skip passthrough check

- pkg/rhcos/ami.go
- pkg/rhcos/qemu.go
Update code references to RHCOS to use the full, proper name.
/cc @mrguitar @jlebon @miabbott @darkmuggle
Related: https://github.com/openshift/installer/pull/1358
> Update code references to rhcos

- docs/user/openstack/README.md
- docs/user/troubleshooting.md
Update `troubleshooting.md` and the openstack `README.md` to use the full, proper name of RHCOS.
/cc @mrguitar @jlebon @miabbott @darkmuggle 
Related: https://github.com/openshift/installer/pull/1359
> Update name of RHCOS

- pkg/destroy/aws/aws.go
Currently this is a somewhat-warm loop while we wait for Amazon to reap dependencies that have already had successful "deleted" calls.  For example:
```console
$ curl -s  https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1346/pull-ci-openshift-installer-master-e2e-aws/4324/artifacts/e2e-aws/installer/.openshift_install.log| grep '[Dd]elet.*vpc-08dc4aea3c1c2db8f' | tail -n4
time="2019-03-01T15:21:47Z" level=debug msg="deleting arn:aws:ec2:us-east-1:460538899914:vpc/vpc-08dc4aea3c1c2db8f: DependencyViolation: The vpc 'vpc-08dc4aea3c1c2db8f' has dependencies and cannot be deleted.\n\tstatus code: 400, request id: 0c437bd8-ed5f-4989-abda-987aefdac6ce"
time="2019-03-01T15:21:50Z" level=debug msg="deleting arn:aws:ec2:us-east-1:460538899914:vpc/vpc-08dc4aea3c1c2db8f: …
```
> pkg/destroy/aws: 10-second lower bound for deletion period

- cmd/openshift-install/create.go
At @staebler's [suggestion][1], allowing us to offload some boilerplate to [an upstream library][2] (although it is a bit sad to drop the typed client :p).
Also fix an "an" -> "a" typo and consolidate the debug logging to avoid claiming "added" for modifications.
CC @sttts
[1]: https://github.com/openshift/installer/pull/1375#discussion_r263145567
[2]: https://godoc.org/k8s.io/client-go/tools/cache#NewListWatchFromClient
> cmd/openshift-install/create: Use NewListWatchFromClient

- pkg/asset/manifests/operators.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1686119
install-config is stores as a config map in the cluster, but the pull-secret in the install-config is a secret that
shouldn't be stores as config map.
The pull-secret is already available to cluster as secret `kube-system/coreos-pull-secret`.
> asset/manifests: redact the pull-secret from the cluster object of the install-config

- pkg/destroy/aws/aws.go
Today the code only deletes running and pending instances. Not stopped,
stopping, or shutting down. Those still cause dependency problem and
should be cleaned up just like termineted. Instead of writing out
the full list (and having to keep it up to date) instead I just skip
termineted instances in code instead of tryin to filter during the API
call.
> pkg/destroy/aws: Destroy all instances not terminated

- data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
This reverts commit ad05a33abc8eee3a1bb9560e52e8253860877abf.
> Revert "data/data/bootstrap: add kube-client-agent-image flag"

- pkg/destroy/aws/aws.go
In 200f0c907 (#1434), I removed some local `lastError` variables that masked the function-level variable.  But @staebler [points out][1] that we were still clobbering that function-level variable with the loop-level value, so a successful loop iteration might silently clear a previously-set `lastError`.  This commit goes through and uses `err` for consistently for the loop-level variable.  When we have an error, we log any previous `lastError` value before clobbering that value with the new error.  It's up to the caller to decide how they want to handle any final `lastError`; they can log it or not as they see fit.
I've demoted the `lastError` logging from `Info` to `Debug`, because the destroy logic usually uses debug for errors (e.g. `DependencyViolation` errors), and I don't see a …
> pkg/destroy/aws: Remove lastError value masking

- cmd/openshift-install/create.go
Since fd1349ce31 (#1432), we log progress messages while waiting.  But I'd forgotten to log them in the timeout message, which could lead to logs like:
```console
$ curl -s https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.0/5971/artifacts/e2e-aws/installer/.openshift_install.log | grep -B3 level=fatal
time="2019-03-21T02:17:31Z" level=debug msg="Still waiting for the cluster to initialize: Working towards 4.0.0-0.ci-2019-03-21-015242: 95% complete"
time="2019-03-21T02:36:11Z" level=debug msg="Still waiting for the cluster to initialize: Could not update rolebinding \"openshift-cluster-storage-operator/cluster-storage-operator\" (231 of 310): the server has forbidden updates to this resource"
time="2019-03-21T02:36:41Z" level=debug msg="Still …
```
> cmd/openshift-install/create: Log progress on timeout too

- Gopkg.lock
- pkg/asset/machines/openstack/machines.go
- vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/apis/openstackproviderconfig/v1alpha1/types.go
- vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/apis/openstackproviderconfig/v1alpha1/zz_generated.deepcopy.go
- Tags workers with Name, and openstack cluster id
- Pulls in changes to capo from upstream
> [openstack] Support for tagging workers

- pkg/asset/cluster/metadata.go
- pkg/asset/cluster/tfvars.go
- pkg/asset/installconfig/installconfig.go
- pkg/asset/installconfig/platform.go
- pkg/asset/installconfig/platformcredscheck.go
- pkg/asset/installconfig/vsphere/vsphere.go
- pkg/asset/machines/master.go
- pkg/asset/machines/worker.go
- pkg/asset/manifests/dns.go
- pkg/asset/manifests/infrastructure.go
- pkg/asset/rhcos/image.go
- pkg/asset/store/assetcreate_test.go
- pkg/types/installconfig.go
- pkg/types/machinepools.go
- pkg/types/validation/installconfig_test.go
- pkg/types/vsphere/defaults/platform.go
- pkg/types/vsphere/defaults/platform_test.go
- pkg/types/vsphere/doc.go
- pkg/types/vsphere/machinepool.go
- pkg/types/vsphere/platform.go
- pkg/types/vsphere/validation/machinepool.go
- pkg/types/vsphere/validation/machinepool_test.go
- pkg/types/vsphere/validation/platform.go
- pkg/types/vsphere/validation/platform_test.go
- upi/vsphere/README.md
Add a platform used for UPI installation on vSphere.
> pkg/types: add vsphere platform

- docs/dev/openstack-howto.md
- docs/user/openstack/README.md
A couple of OpenStack documentation fixes.
> Openstack doc

- hack/build.sh
Catching up with a31e12fc4c (#1422).
> hack/build: Update release-pin location to defaultReleaseImageOriginal

- pkg/types/azure/defaults/platform.go
- pkg/types/azure/doc.go
- pkg/types/azure/machinepool.go
- pkg/types/azure/metadata.go
- pkg/types/azure/platform.go
- pkg/types/azure/platform_test.go
- pkg/types/azure/validation/machinepool.go
- pkg/types/azure/validation/machinepool_test.go
- pkg/types/azure/validation/platform.go
- pkg/types/azure/validation/platform_test.go
- pkg/types/clustermetadata.go
- pkg/types/defaults/installconfig.go
- pkg/types/defaults/installconfig_test.go
- pkg/types/installconfig.go
- pkg/types/machinepools.go
- pkg/types/validation/installconfig.go
- pkg/types/validation/installconfig_test.go
- pkg/types/validation/machinepools.go
- pkg/types/validation/machinepools_test.go
This PR is a subset of #1460 to make review and progress easier.
The azure platform is not enabled in the CLI so it has no functional impact.
The hope is that this can be merged, and that I can rebase #1460 or split it further to facilitate your reviews.
/assign @abhinavdahiya  @enxebre @wking
> pkg/types: Add required azure types

- pkg/types/validation/installconfig.go
- pkg/types/validation/installconfig_test.go
The validation of install-config was not validating the vsphere platform.
> types/validation: enable validation of vsphere platform

- docs/user/aws/install_upi.md
> BUG 1696216: docs/aws/upi: add info on approving csr for manually added nodes to cluster

- upi/vsphere/machine/cidr_to_ip.sh
* Timeout IP reservation after 1 minute with a more meaningful error message.
* Stop leaking an error message back to terraform when there are no reservations for a hostname.
> upi/vsphere: improve robustness of ip reservation

- docs/user/vsphere/install_upi.md
- upi/vsphere/route53/main.tf
> upi/vsphere: add the api-int dns

- pkg/asset/installconfig/aws/basedomain.go
The previous pagination seems to have been working, but having the vendored code handle this for us saves some local complication.
> pkg/asset/installconfig/aws/basedomain: Use ListHostedZonesPages to collect public zones

- pkg/asset/machines/openstack/machines.go
- pkg/destroy/openstack/openstack_deprovision.go
Dependant on https://github.com/openshift/cluster-api-provider-openstack/pull/32
Fixes Destroy script
> [openstack] Tags Worker resources to ensure succesful Destroy 

- docs/user/vsphere/install_upi.md
Add instructions in the documentation for setting the hostname and static IP address of a machine.
> docs/vsphere: add instructions for hostname and static IP

- OWNERS_ALIASES
> Add reviewers

- data/data/aws/master/main.tf
- upi/aws/cloudformation/05_cluster_master_nodes.yaml
- upi/aws/cloudformation/06_cluster_worker_node.yaml
/cc @enxebre
https://github.com/openshift/cluster-api-provider-aws/pull/192
> Remove clusterid tag

- data/data/openstack/service/main.tf
Same as #1601 but for OpenStack.
> data/openstack: add `api-int` DNS A record

- data/data/rhcos.json
This includes https://github.com/openshift/pivot/pull/51
> Bug 1702519: rhcos: Bump to 410.8.20190425.0

- docs/dev/libvirt/README.md
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>
> libvirt/README: fix broken links due to doc move

- pkg/asset/ignition/machine/node.go
- pkg/asset/tls/mcscertkey.go
Catching up with 13e4b702f7 (#1601) and 052fceeeaf (#1633).
> pkg/asset/ignition/machine/node: Move pointer Ignition configs to api-int

- pkg/destroy/aws/aws.go
We create a lot of these in a given 24 hour period, because we try to delete them before their consumer has been reaped:
```console
$ LOG="$(curl -s https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.1/509/artifacts/e2e-aws/installer/.openshift_install.log | grep InvalidParameterValue)"
$ echo "${LOG}" | wc -l
75
$ echo "${LOG}" | grep -v 'Network interface'
...no matches...
```
This will cool us off a bit, partly by limiting us to one `ByVPC` failure in a given destroy cycle, vs. our current:
```console
$ echo "${LOG}" | head -n3
time="2019-05-02T21:31:18Z" level=debug msg="deleting EC2 network interface eni-03b0e0c93880c0640: InvalidParameterValue: Network interface 'eni-03b0e0c93880c0640' is currently in use.\n\tstatus code: 400, request id: …
```
> pkg/destroy/aws: Skip direct tag deletion for network interfaces

- data/data/bootstrap/files/usr/local/bin/installer-gather.sh
This lists all secret names and then annotations for all but the SA token and dockercfg secrets.
Related to https://bugzilla.redhat.com/show_bug.cgi?id=1707096
> BUG 1707096: gather: collect secret names for failure analysis

- data/data/bootstrap/files/usr/local/bin/installer-gather.sh
This change adds sudo when gathering rendered-assets within
/usr/local/bin/installer-gather.sh. It also changes the owner and
permissions on the copied files so that the core user has access to
read them. In addition, the method used to retrieve assets from the
control-plane nodes has been modified to make it less noisy on error.
> Bug 1708307: bootstrap/files: installer-gather.sh to gather more rendered-assets

- data/data/bootstrap/files/usr/local/bin/installer-gather.sh
- data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh
related to Related to https://bugzilla.redhat.com/show_bug.cgi?id=1707096
> Bug 1707096: gather: suffix container logs with container ids for uniqueness

- pkg/destroy/openstack/openstack_deprovision.go
Testing agains upshift revealed a flaw in our deprovisoin strategy
Changes:
- Dissociate all floating IP's that are still associated with a router when it is time to delete routers
- Check ALL ports for subnets that are connected to the router via an interface, rather than just ports created by HA or non-HA router configurations.
In reference to https://jira.coreos.com/browse/OSASINFRA-417
> [openstack] More robust deprovision strategy

- pkg/types/installconfig.go
Move the azure platform from hidden platform,
into the visibly-supported platform
> pkg/types: enable azure platform

- pkg/asset/machines/worker.go
Fixes https://github.com/openshift/installer/issues/1749
/cc @wking @jstuever
> asset/machines: set the instance type for workers on azure

- docs/dev/libvirt/README.md
Some improvements to libvirt first time setup documentation
> Doc changes for libvirt backend

- README.md
- pkg/asset/installconfig/platform.go
I've marked them expermental until we have blocking CI tests for them, but we still want to let users know that these are options.
> README: Reference vSphere and metal from the platform section

- docs/user/azure/install.md
Fixes https://github.com/openshift/installer/issues/1783
> docs/azure: include step to create vhd container in storage account

- OWNERS_ALIASES
Removed Flavio from `openstack-approvers` and added myself instead.
> Refresh openstack-approvers group

- docs/user/openstack/README.md
1) add rhcos info
2) add trunk port info
> [openstack] enhance doc for openstack readme

- pkg/destroy/openstack/openstack_deprovision.go
some action unsuccessful but no log at all, this is not helpful
for debug, we need log those information.
> openstack:Add log for delete unsuccessful action

- pkg/types/conversion/installconfig_test.go
Adds a unit test for 4bea183e19d4ebaed34f1f5f0ef5a005e2ad4584. Adds further logic to conversion testing to allow for expected errors vs expected configs.
This is required because we are backporting #1760 to 4.1.z
See https://github.com/openshift/installer/pull/1764#issuecomment-505136339
> Add conversion test when no API version is specified.

- pkg/types/validation/installconfig.go
- pkg/types/validation/installconfig_test.go
/cc @jcpowermac @patrickdillon
> pkg/types/validation: fix proxy validations to drop incorrect requirements on scheme

- cmd/openshift-install/gather.go
- data/data/azure/bootstrap/main.tf
- data/data/azure/bootstrap/variables.tf
- data/data/azure/main.tf
- data/data/azure/master/master.tf
- data/data/azure/master/variables.tf
- data/data/azure/vnet/nsg.tf
- data/data/azure/vnet/outputs.tf
- data/data/azure/vnet/public-lb.tf
- data/data/azure/vnet/variables.tf
- pkg/terraform/gather/azure/ip.go
This PR attempts to create a public IP address on the bootstrap node. 
https://jira.coreos.com/browse/CORS-1093
> azure: public IP for bootstrap node

- pkg/destroy/libvirt/libvirt.go
- pkg/destroy/libvirt/register.go
Fixes: https://github.com/openshift/installer/issues/1931
> Fix the build issue

- pkg/asset/manifests/proxy.go
- Checks the platform if it is not vSphere or None will include 169.254.169.254 to the NO_PROXY list
> Add cloud providers metadata ip address to no proxy

- data/data/gcp/bootstrap/main.tf
Moves bootstrap ignition to gcs bucket.
> [gcp] data/data: use gcs bucket for bootstrap ignition and expose bootstrap node

- Gopkg.lock
- data/data/openstack/main.tf
- data/data/openstack/topology/variables.tf
- data/data/openstack/variables-openstack.tf
- pkg/asset/cluster/tfvars.go
- pkg/asset/installconfig/openstack/openstack.go
- pkg/tfvars/openstack/openstack.go
- pkg/types/openstack/platform.go
- pkg/types/openstack/validation/mock/validvaluesfetcher_generated.go
- pkg/types/openstack/validation/platform.go
- pkg/types/openstack/validation/platform_test.go
- pkg/types/openstack/validation/realvalidvaluesfetcher.go
- pkg/types/openstack/validation/validvaluesfetcher.go
- pkg/types/validation/installconfig_test.go
This PR checks if the OpenStack environment has Octavia
support
> OpenStack: Check octavia support

- docs/design/baremetal/networking-infrastructure.md
Describe API load balancing flow for internal and external clients.
> Baremetal:  update networking documentation - API LB

- OWNERS_ALIASES
Adding `sdodson` to installer-approvers
Removing `staebler`, `steveeJ` from installer-approvers
Removing `vrutkovs` from installer-reviewers
/cc @sdodson
> OWNERS_ALIASES: update the installer-approvers

- docs/user/azure/install.md
Remove azure documentation that is not longer relevant.
https://jira.coreos.com/browse/CORS-1172
> Azure: update install documentation to reflect current reality

- images/openstack/Dockerfile.ci
This should give us access to some new CLI features to gather logs.
> Bump openstack image to use cli 4.1

- OWNERS_ALIASES
> OpenStack: update approvers

- pkg/destroy/gcp/compute.go
The current fields filter is not returning the expected fields for
disks. The zone also needs to be converted from URL to a regular zone
name.
> [gcp] pkg/destroy/gcp: Fix disk deletion

- docs/user/gcp/iam.md
> [gcp] docs/user/gcp: document required services

- docs/user/gcp/install_upi.md
- upi/gcp/01_vpc.py
- upi/gcp/02_infra.py
- upi/gcp/03_security.py
- upi/gcp/04_bootstrap.py
- upi/gcp/05_control_plane.py
- upi/gcp/06_worker.py
This change adds the initial upi/gcp templates for ci.
> upi/gcp: initial deployment manager templates

- data/data/gcp/main.tf
> gcp: correctly wire up the root volume type/size

- data/data/bootstrap/gcp/files/usr/local/bin/report-progress.sh
- data/data/gcp/network/lb.tf
/cc @csrwng 
/hold
requires https://gitlab.cee.redhat.com/openshift-art/rhcos-upshift/merge_requests/61 and https://github.com/openshift/machine-config-operator/pull/1031
>  gcp: include all hosts in the LB backend 

- pkg/asset/manifests/scheduler.go
- fix typo in message with MastersSchedulabe
> fix typo in message with MastersSchedulabe

- docs/user/openstack/README.md
This PR updates the installer information for OpenStack to include
information about how to set Kuryr SDN as well as its requirements
> OpenStack: Add Kuryr information to the OpenStack README file

- docs/user/openstack/README.md
- docs/user/openstack/kuryr.md
Adds a table of contents, sorts sections by type of activity, created a whole new doc for Kuryr related info, and links important reference docs.
> OpenStack: Better Docs Organization and Linking

- pkg/asset/manifests/proxy.go
machineCIDR is required by MCO. Node subdomain is required to bypass proxy for functionality such as apiserver fetching container logs.
/assign @abhinavdahiya @jcpowermac 
/cc @bparees @runcom
> Adds additional default proxy noProxy entries

- docs/dev/libvirt/README.md
Fix relative links for the new directory layout.
> docs/dev/libvirt: update links in customizing install note

- docs/user/gcp/README.md
- docs/user/gcp/limits.md
> Adding a note about quota on GCP

- pkg/asset/manifests/openstack/cloudproviderconfig.go
- pkg/asset/manifests/openstack/cloudproviderconfig_test.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1747474
> Bug 1747474: OpenStack: Escape special characters in cloud provider password

- Gopkg.lock
- pkg/destroy/openstack/openstack.go
- vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/doc.go
- vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/requests.go
- vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/results.go
- vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/urls.go
- vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/util.go
At the time of deleting the cluster, we also need to delete all cluster volumes.
> Bug 1749276: OpenStack: remove volumes along with other resources

- docs/user/metal/install_upi.md
> docs/user/metal: Fix link to SDN ports

- pkg/destroy/openstack/openstack.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1750636
> Bug 1750636: OpenStack: delete floating ips

- OWNERS_ALIASES
the openstack org owners are out of date
> update openstack owner aliases

- docs/user/openstack/README.md
- docs/user/openstack/known-issues.md
Docs that provide customers with info/transparency into disk speed requirements, and what we are doing to address it.
> Document disk speed requirements

- Gopkg.lock
- Gopkg.toml
- vendor/gopkg.in/AlecAivazis/survey.v1/multiselect.go
- vendor/gopkg.in/AlecAivazis/survey.v1/select.go
- vendor/gopkg.in/AlecAivazis/survey.v1/terminal/cursor.go
- vendor/gopkg.in/AlecAivazis/survey.v1/terminal/output.go
- vendor/gopkg.in/AlecAivazis/survey.v1/terminal/runereader_linux.go
- vendor/gopkg.in/AlecAivazis/survey.v1/terminal/runereader_ppc64le.go
Fixes: https://github.com/openshift/installer/issues/2290
> [4.3] vendor: update gopkg.in/AlecAivazis/survey to v1.8.7

- data/data/azure/main.tf
- data/data/azure/master/variables.tf
- data/data/azure/vnet/internal-lb.tf
xref: https://jira.coreos.com/browse/CORS-1097
/cc @jhixson74 
/test e2e-azure
> data/azure: remove the hard-coded ip for the ILB

- CONTRIBUTING.md
We need to mention podman was requested by local development.
Fixed https://github.com/openshift/installer/issues/2508
> Document: podman was requested by local dev environment.

- data/data/azure/vnet/variables.tf
These were added without a consumer in 2c40ae8dcf (#1454).
> data/azure/vnet/variables: Drop *_master_endpoints

- docs/user/openstack/install_upi.md
This adds a document describing how to do UPI on OpenStack. There is no automation yet, all the steps described here are using the standard `openstack` command.
We plan to add automation (using Ansible) in follow-up pull requests.
This is enough to do a full UPI deployment.
> Openstack UPI docs

- pkg/destroy/openstack/openstack.go
Now, if some error occurs during the deletion process, it immediately terminates with code 1 instead of trying to perform the failed action again.
We must be tolerant of errors and end the process only by timeout.
> OpenStack: do not interrupt the deletion process in case of an error

- docs/user/openstack/README.md
Provide further advice on how to measure and correct disk latency.
Implements https://jira.coreos.com/browse/OSASINFRA-900
> openstack: Add detail to disk requirements

- upi/openstack/01_network.yaml
- upi/openstack/README.md
- upi/openstack/down-01_network.yaml
- upi/openstack/inventory.yaml
- upi/openstack/requirements.txt
Create an Ansible playbook for deploying the Networks required for a
User Provided Infrastructure installation.
Implements https://jira.coreos.com/browse/OSASINFRA-784
> openstack UPI: Automate Network creation

- docs/user/openstack/customization.md
- docs/user/openstack/known-issues.md
Updates the known Issues Doc to reflect features that merged for 4.3
> Bug 1768639: OpenStack Known issues

- pkg/types/openstack/validation/realvalidvaluesfetcher.go
Fixes: https://github.com/openshift/installer/issues/2409
> OpenStack: return correct error if no flavors were found

- README.md
IPI is now fully supported as of 4.2, and added UPI as experimental.
> Update README for OpenStack platform status

- docs/user/openstack/README.md
> nit: fix doc link issue

- docs/user/customization.md
Now that we have day 1 support for kernel arguments, add a snippet
documenting how to apply them during install time.
cc @ericavonb @sinnykumari
> docs/customization.md: add snippet on setting kernel arguments

- upi/openstack/README.md
Provide an alternative to pip for installing requirements.
> openstack: Install UPI requirements using yum

- pkg/destroy/gcp/cloudcontroller.go
k8s uses k8s-<controller-id>-node health checks (one legacy, one latest generation) and corresponding firewall rules k8s-<controller-id>-node-hc (for latest generation), k8s-<controller-id>-node-http-hc (for legacy generation)
> Bug 1762413: destroy/gcp/cloudcontroller.go: cleanup the shared firewalls and health checks

- docs/user/openstack/known-issues.md
Updating the FAQ/Known Issue page with the latest info about ss certs
> Docs: OpenStack ss certs status update

- pkg/asset/cluster/tfvars.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1776466
> bug 1776466: use correct length for worker node configs

- upi/openstack/03_bootstrap.yaml
- upi/openstack/down-03_bootstrap.yaml
- upi/openstack/inventory.yaml
Create an Ansible playbook for deploying the Bootstrap server required
for a User Provided Infrastructure installation.
Implements https://jira.coreos.com/browse/OSASINFRA-786
> openstack UPI: Automate Bootstrap server creation

- pkg/destroy/openstack/openstack.go
This patch contains improvements for the destroy module from PRs https://github.com/openshift/installer/pull/2408
> Bug 1773909: OpenStack: Fix destroy module

- .yamllint
> .yamllint: Exclude vendor/

- data/data/rhcos.json
This has encryption/FIPS fixes.
> Bug 1775388: rhcos: Bump to latest RHCOS

- OWNERS_ALIASES
/assign @sdodson 
/cc @jstuever
> OWNERS_ALIASES: add jstuever to aws approvers

- docs/design/openstack/OWNERS
- docs/user/metal/OWNERS
- docs/user/openstack/OWNERS
This adds an OWNERS file to docs/user/metal.
> docs: update OWNERS for baremetal and openstack docs

- pkg/destroy/aws/aws.go
If a VPC Peering Connection has been created for the cluster, then the destroyer will hang indefinitely since the destroyer does not know how to delete the VPC Peering Connection. These changes will give the destroyer the capability to delete VPC Peering Connections.
https://jira.coreos.com/browse/CO-671
> destroy: clean up tagged vpc peering connections

- upi/openstack/03_bootstrap.yaml
ref: https://github.com/openshift/installer/pull/2681
Extracted from https://github.com/openshift/installer/pull/2823
> openstack UPI: Remove unneeded allowed IP

- upi/openstack/01_security-groups.yaml
- upi/openstack/02_network.yaml
- upi/openstack/03_bootstrap.yaml
- upi/openstack/04_control-plane.yaml
- upi/openstack/05_compute-nodes.yaml
- upi/openstack/common.yaml
- upi/openstack/down-01_security-groups.yaml
- upi/openstack/down-02_network.yaml
- upi/openstack/down-03_bootstrap.yaml
- upi/openstack/down-04_control-plane.yaml
- upi/openstack/down-05_compute-nodes.yaml
The common playbook reads the infraID from metadata.json and computes
the resource names needed by other playbooks.
> OpenStack UPI: introduce common playbook

- pkg/types/vsphere/platform.go
Add additional fields required for IPI.
Tested with UPI - no issues when new fields undefined.
> Update vSphere platform struct for IPI

- data/data/openstack/topology/sg-master.tf
- data/data/openstack/topology/sg-worker.tf
Terraform tries to create all rules at once, sending multiple requests simultaneously. While this can reduce installation time a bit, it also can lead to conflicts. It is especially evident on high loaded systems.
Terraform developers recommend a workaround to create rules sequentially by setting explicit dependencies between them:
https://github.com/hashicorp/terraform/issues/7519
This commit fixes the issue according to the workaround recommendation.
When https://github.com/terraform-providers/terraform-provider-openstack/issues/952 is fixed in the to the OpenStack Terraform provider, we can revert this patch.
> Bug 1786675: OpenStack: create security rules sequentially

- images/libvirt/Dockerfile.ci
- images/libvirt/README.md
- images/libvirt/google-cloud-sdk.repo
- images/libvirt/mock-nss.sh
A libvirt image to support both nested libvirt through GCE and remote libvirt directly.
> Generic libvirt installer image for CI

- hack/shellcheck.sh
Causing test failures
Specifically on PR #2897
> Add terraform vendor path to shellcheck

- data/data/rhcos.json
> [FCOS] use stable Fedora CoreOS boot images

- upi/openstack/02_network.yaml
- upi/openstack/common.yaml
- upi/openstack/inventory.yaml
- upi/openstack/library/os_create_svc_subnet.py
Update UPI playbook to account for user provided service
network when Kuryr SDN is used.
> OpenStack: Add support to user provided service network

- pkg/destroy/openstack/openstack.go
Now we delete user-provisioned api fips, which is wrong, because these resources do not belong to the cloud.
This PR dissociates api fips instead of deleting them.
> Bug 1796479: OpenStack: dissociate api fips instead of deleting them

- data/data/aws/vpc/sg-master.tf
- data/data/aws/vpc/sg-worker.tf
- data/data/gcp/network/firewall.tf
- data/data/openstack/topology/sg-master.tf
- data/data/openstack/topology/sg-worker.tf
- docs/user/openstack/install_upi.md
- upi/aws/cloudformation/03_cluster_security.yaml
Backports #2983 #2984 #2985 #3027
> Bug 1779469: Fix node ports

- pkg/asset/cluster/tfvars.go
- pkg/asset/installconfig/ovirt/client.go
- pkg/asset/installconfig/ovirt/cluster.go
- pkg/asset/installconfig/ovirt/config.go
- pkg/asset/installconfig/ovirt/credentials.go
- pkg/asset/installconfig/ovirt/network.go
- pkg/asset/installconfig/ovirt/ovirt.go
- pkg/asset/installconfig/ovirt/storage.go
- pkg/asset/installconfig/ovirt/validators.go
- pkg/asset/installconfig/ovirt/validators_test.go
- pkg/asset/installconfig/platform.go
- pkg/asset/installconfig/platformcredscheck.go
- pkg/asset/manifests/openshift.go
- pkg/destroy/ovirt/destroyer.go
- pkg/types/installconfig.go
- move ovirt from `HiddenPlatformNames` to `PlatformsNames`    
- ask for credentials      
- ask for a cluster   
- ask for a storage domain
- ask for a network     
- recommend not to use default network
> ovirt: Add survey

- docs/user/openstack/README.md
Documents how to refresh certs post install
> Bug 1801799: openstack docs day 2 ssc refresh

- docs/user/azure/install_upi.md
Makes it clear the ARM templates should be copied from the upi/azure folder in the repo.
Fixes https://github.com/openshift/installer/issues/3121
> Make the location of Azure ARM templates clear in UPI docs

- pkg/asset/installconfig/aws/permissions.go
these calls are made during uninstall
> add iam:DeleteAccessKey and iam:DeleteUser to perm list

- pkg/asset/machines/master.go
- pkg/asset/machines/worker.go
Follow-up PR after https://github.com/openshift/installer/pull/1948#issuecomment-573212184
@patrickdillon PTAL
> Add ovirt's cluster api provider schemas to UniversalDecoder

- data/data/azure/dns/dns.tf
- data/data/gcp/dns/base.tf
similar motivation to ae9cbaf [1]
[1]: https://github.com/openshift/installer/commit/ae9cbafafaaefd931339fd6ccb0b60e366ed5ffe
/cc @jhixson74 @jstuever
> bug 1775873: data/data/gcp,azure: block private dns zone on public record

- data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Cherry-picked commits from #3076 to start `gcp-routes` services on bootstrap
> [fcos] start GCP services on bootstrap

- docs/user/openstack/install_upi.md
This commit adds documentation describing how to use Glance service to store bootstrap ignition configs for OpenStack UPI.
> OpenStack: UPI: Glance for storing ignition configs

- pkg/destroy/openstack/openstack.go
Now if there was a failure during load balancer deletion, we do not return anything and continue the execution, which leads to a runtime error later.
This commit changes this behavior and returns an error immediately if something bad happens.
> Bug 1809187: OpenStack: return an error if load balancer deletion fails

- Gopkg.lock
- Gopkg.toml
- vendor/gopkg.in/AlecAivazis/survey.v1/multiselect.go
- vendor/gopkg.in/AlecAivazis/survey.v1/select.go
Upstream fix PR: AlecAivazis/survey#271
> [release-4.3] Bug 1808095: Bump survey vendor for panic

- pkg/destroy/openstack/openstack.go
Now when Swift is deployed with internal Swift Auth (Swauth) and if the user doesn't have `swiftoperator role`, instead of 403 Swift returns 401 for each request.
This commit catches 401 errors from Swift and skips container deletion in this case.
> Bug 1810489: Ignore 401 error when deleting containers

- images/openstack/Dockerfile.ci
patch adds upi support to the openstack-installer image
> Installs upi support on openstack-installer image

- images/baremetal/Dockerfile.ci
We want to be able to log into a remote host to execute commands.
> baremetal: Add nss mock, ssh to Dockerfile

- docs/user/openstack/install_upi.md
The Boostrap Ignition file needs to be edited before it's uploaded.
Before this change, the documentation described the "upload" step before
the "edit" step.
> Bug 1818590: openstack UPI fix order of steps

- pkg/asset/releaseimage/default.go
> [FCOS] pkg/asset/releaseimage/default: use OKD 4.4 as default release

- pkg/asset/installconfig/ovirt/config.go
> Bug 1814172: [ovirt] Cannot run openshift-install as a non-root user 

- OWNERS
xref: http://post-office.corp.redhat.com/archives/aos-leads/2020-March/msg00122.html
> OWNERS: include component for image tracking by ART

- data/data/bootstrap/gcp/files/usr/local/bin/gcp-routes.sh
Using routing tables means that existing connections are immediately
severed when the vip is removed from the node. By using conntrack
instead, existing connections are gracefully preserved.
This commit has been ported from the redhat-coreos repo.
The original author is @squeed
/cc @vrutkovs
> [fcos] GCP-routes: switch to using conntrack instead of route tables

- pkg/types/config/openstack/OWNERS
This seems to be a relic of 619db9259e (#412) and 5192edd08b (#428) coming in close proximity.
> pkg/types/config: Remove unused directory

- data/data/rhcos-amd64.json
- data/data/rhcos.json
- hack/update-rhcos-bootimage.py
> [fcos] Update base image to 31.20200323.3.2

- docs/user/openstack/README.md
A Server group will be created during the installation on OpenStack.
/cc @mandre @Fedosin @adduarte 
> openstack: Mention Server group requirement

- docs/user/metal/install_upi.md
A minor improvement to baremetal UPI docs.
> baremetal: Clarify install config needs to be hand-written in the docs

- cmd/openshift-install/create.go
previously all the errors were context Deadline exceeded, with this change the error returned is the last tracked error.
This is useful as the user has more information about what the failure could be.
For example, BZ https://bugzilla.redhat.com/show_bug.cgi?id=1810318#c8
the `.openshift_install.log` had the following debug log.
```
time="2020-03-04T21:08:13Z" level=debug msg="Still waiting for the Kubernetes API: Get https://api.openshift10.az.test-am-cloudpak.io:6443/version?timeout=32s: dial tcp: lookup api.openshift10.az.test-am-cloudpak.io on 127.0.0.53:53: no such host"
```
but the error returned to the use was
```
FATAL Bootstrap failed to complete: waiting for Kubernetes API: context deadline exceeded
```
returning the last tracked error would help users as they don't have to look …
> Bug 1828947: cmd/openshift-install/create.go: return lastErr when waiting API fails

- cmd/openshift-install/create.go
previously all the errors were context Deadline exceeded, with this change the error returned is the last tracked error.
This is useful as the user has more information about what the failure could be.
For example, BZ https://bugzilla.redhat.com/show_bug.cgi?id=1810318#c8
the `.openshift_install.log` had the following debug log.
```
time="2020-03-04T21:08:13Z" level=debug msg="Still waiting for the Kubernetes API: Get https://api.openshift10.az.test-am-cloudpak.io:6443/version?timeout=32s: dial tcp: lookup api.openshift10.az.test-am-cloudpak.io on 127.0.0.53:53: no such host"
```
but the error returned to the use was
```
FATAL Bootstrap failed to complete: waiting for Kubernetes API: context deadline exceeded
```
returning the last tracked error would help users as they don't have to look …
> Bug 1828948: cmd/openshift-install/create.go: return lastErr when waiting API fails

- pkg/destroy/gcp/policybinding.go
- pkg/destroy/gcp/serviceaccount.go
service account names or the name in it's email has max length of 30 and therefore using it for identifying makes it difficult as the creator will probably have to truncate the infra-id prefix to fit as the name.
service account's displayName has 100 char limit and therefore using that ensure we can identity the service accounts much better.
The change checks both the email, and displayName to figure out if cluster id is prefixed.
secondly project iam policy only have service account email, and therefore to clean up members correctly, the change now lists the service accounts in the project for the cluster and
then uses that to check if a member of the policy maps to service account of the cluster.
> Bug 1839268: pkg/destroy/gcp: ensure cluster service accounts and policy bindings are removed

- OWNERS_ALIASES
- Add cfergeau (Christophe) for libvirt approver and reviewer
- Remove zeenix (Zeeshan) from the this roles
> Update libvirt approver and reviewer

- OWNERS_ALIASES
Add the entire team as reviewers.
> Add openstack reviewers

- data/data/rhcos-amd64.json
- data/data/rhcos.json
/approve
/cc @LorbusChris 
Fixes https://github.com/openshift/okd/issues/153
> Update initial FCOS to 31.20200505.3.0

- pkg/asset/installconfig/vsphere/vsphere.go
Adds error handling for vSphere survey questions. This is particularly noticeable for handling user interrupts (CTRL C). Without error handling the interrupts cause survey to skip to the next question and will ultimately panic when no values have been assigned to the pointers.
> Bug 1841118: add error handling to vSphere survey

- docs/user/customization.md
> Add links from customization.md to ovirt/customization.md topic

- data/data/bootstrap/openstack/OWNERS
- data/data/openstack/OWNERS
- images/openstack/OWNERS
- pkg/asset/cluster/openstack/OWNERS
- pkg/asset/installconfig/openstack/OWNERS
- pkg/asset/machines/openstack/OWNERS
- pkg/asset/manifests/openstack/OWNERS
- pkg/destroy/openstack/OWNERS
- pkg/tfvars/openstack/OWNERS
- pkg/types/openstack/OWNERS
- upi/openstack/OWNERS
Ref.: https://github.com/openshift/installer/pull/3640
> Add reviewers to the OpenStack directories

- pkg/types/baremetal/validation/libvirt.go
baremetal: allow bootstrap vm to use libvirt nat networks
This allows to have the bootstrap created using regular libvirt networks and not only manually created bridges, which makes things easier for dev and lab setups.
> baremetal: allow bootstrap vm to use libvirt nat networks

- OWNERS
Removed the rest of the team to avoid unnecessary review requests
> [fcos] add vrutkovs and LorbusChris to owners

- README.md
This PR is being used to test out a new feature in the release-controller's automation. The change is an invisible dummy comment in the README.
> Bug 1848080: README.md: dummy change to test new automation feature

- go.mod
- go.sum
- vendor/modules.txt
Refer to mco's `fcos` branch in go.mod
> [FCOS] go.mod: update MCO to latest commit in `fcos` branch

- upi/openstack/down-containers.yaml
Only attempt deleting containers if a container is found.
/cc @MaysaMacedo
> Bug 1848988: os UPI: Make down-containers idempotent

- data/data/fcos-amd64.json
- data/data/fcos.json
- hack/update-fcos-bootimage.py
> [FCOS] Update to bootimage to 32.20200601.3.0

- README.md
This PR is being used to test out a new feature in the release-controller's automation. This PR is an empty commit, so it shouldn't affect this repo other than the extra commit.
> Bug 1850235: empty commit: dummy change to test new automation feature

- data/data/azure/vnet/public-lb.tf
- data/data/baremetal/main.tf
- data/data/bootstrap/files/usr/local/bin/kubelet-pause-image.sh.template
- data/data/bootstrap/systemd/units/kubelet.service.template
- data/data/openstack/topology/private-network.tf
- data/data/rhcos-amd64.json
- data/data/rhcos.json
- docs/user/vsphere/install_upi.md
- pkg/asset/installconfig/vsphere/vsphere.go
/cc @LorbusChris 
Created using:
```
$ TARGET_COMMIT=$(git describe --tags fcos | sed 's/.*-//')
$ git checkout -b fcos-rebase-jun23 origin/release-4.5
$ git rebase --onto fcos $TARGET_COMMIT
```
> [FCOS] Periodic rebase on release-4.5 branch

- data/data/rhcos-ppc64le.json
- data/data/rhcos-s390x.json
> Bug 1851067: rhcos/ppc64le,s390x: Bump to 46.82.202006241544-0 and 46.82.202006241639-0

- pkg/tfvars/libvirt/libvirt.go
It is convenient to test local RHCOS images through the file protocol rather than having to setup a local server and then download the file from there.
> libvirt: support using the file:// URI scheme for OS image overrides

- go.mod
- go.sum
- vendor/github.com/ovirt/go-ovirt/connection.go
- vendor/github.com/ovirt/go-ovirt/reader.go
- vendor/modules.txt
Solve an issue related to RHV network parsing
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1852722
Fixes https://github.com/openshift/okd/issues/161
> [fcos] Bump go-ovirt

- data/data/fcos-amd64.json
- data/data/fcos.json
> [FCOS] update to 32.20200615.3.0

- data/data/fcos-amd64.json
- data/data/fcos.json
- data/data/libvirt/main.tf
- data/data/libvirt/variables-libvirt.tf
- data/data/rhcos-amd64.json
- data/data/rhcos-ppc64le.json
- data/data/rhcos-s390x.json
- data/data/rhcos.json
- pkg/tfvars/libvirt/libvirt.go
Rebase `fcos` on latest commits from release-4.5
```
TARGET_COMMIT=$(git describe --tags fcos | sed 's/.*-g//')
git checkout -b fcos-rebase-jul06 origin/release-4.5
git rebase --onto fcos $TARGET_COMMIT
```
Also includes bump to latest stable FCOS
> [fcos] rebase july 11

- docs/user/metal/install_ipi.md
And remove example of hardwareProfile as it is deprecated.
> baremetal: Add example of rootDeviceHints usage

- docs/user/ovirt/install_ipi.md
- remove dns vip (bz#1846330)
- update documentation regarding TUI
> ovirt: update documentation

- pkg/asset/installconfig/ovirt/credentials.go
Add hint message to notify the user that with Ctrl+C is possible to
switch the username already choosen
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1848987
> Bug 1848987: Add hint to switch username

- go.mod
- go.sum
- vendor/github.com/hashicorp/terraform/helper/wrappedstreams/streams.go
- vendor/github.com/hashicorp/terraform/helper/wrappedstreams/streams_other.go
- vendor/modules.txt
Brings in vendor update for https://github.com/openshift/hashicorp-terraform/pull/4
/cc @jhixson74
> Bug 1854115: vendor: bump to fix tf panic on mac OS

- pkg/types/baremetal/validation/platform.go
- pkg/types/baremetal/validation/platform_test.go
Currently there's no verification that user-supplied bootstrap or
cluster provisionig IP's don't overlap with the DHCP range. This would
allow a user to incorrectly consume the entire subnet for DHCP leases,
and cause a conflict between the IP's used for provisioning services.
> Bug 1843587: baremetal: verify that provisioning IP's are not in DHCP range

- pkg/asset/quota/aws/OWNERS
- pkg/asset/quota/aws/aws.go
- pkg/asset/quota/aws/aws_test.go
- pkg/asset/quota/aws/instancetypes.go
- pkg/asset/quota/quota.go
- pkg/quota/aws/aws.go
- pkg/quota/aws/limits.go
depends on https://github.com/openshift/installer/pull/3819
> aws: check quotas for services before creating cluster

- pkg/asset/quota/quota.go
To make sure we are not blocking users on quota errors like when quota information is not availble
for a specific region, we now warn and skip unknown type failures
> asset/quota: warn and skip when all quota errors are type unknown

- docs/user/ovirt/install_ipi.md
We had users requesting to document ovirt-config.yaml.
This patch adds a description about the file.
Bug-URL: https://bugzilla.redhat.com/show_bug.cgi?id=1838682
> Bug 1838682: ovirt: document ovirt-config.yaml

- docs/user/ovirt/install_ipi.md
This patch describes the minimum permission for installation.
> ovirt: docs - minimum permissions for installation

- pkg/asset/installconfig/openstack/openstack.go
- pkg/asset/installconfig/openstack/validate.go
- pkg/asset/installconfig/openstack/validation/cloudinfo.go
- pkg/asset/installconfig/openstack/validation/machinepool.go
- pkg/asset/installconfig/openstack/validation/machinepool_test.go
- pkg/asset/installconfig/openstack/validation/platform.go
- pkg/asset/installconfig/openstack/validation/platform_test.go
Add unit tests and defaults to OpenStack Validations, and refactor for easier testing and reading
/cc @Fedosin @abhinavdahiya
> pkg/asset/installconfig/openstack: Cleaner and Tested Validation Code

- README.md
Link the UPI documentation in the README.
> README: add oVirt UPI link

- pkg/asset/installconfig/openstack/validation/cloudinfo.go
This commit:
1. Adds better errors messages
2. Starts using errors.As() to check 404 errors since gophercloud returns pointers
3. Returns nil if external network is not set in the config
> improve cloud info generation

- docs/user/ovirt/install_upi.md
Fix some typos and better specify the oVirt roles needed
> Ovirt Upi docs fix

- docs/user/ovirt/install_ipi.md
Adding the knowledge about ovirt-credentials.
> ovirt: docs - add info about ovirt-credentials

- pkg/tfvars/baremetal/baremetal.go
Reverse part of the work from
https://github.com/openshift/installer/pull/3952 based on new feedback
from the ironic team and the realization that the deploy boot mode
only controls the mode used during deploying and not introspection.
> baremetal: ensure boot mode is set before introspection begins

- pkg/destroy/azure/azure.go
First stab at adding a bit of resiliency to the Azure cluster destroy code. 
Wrap up destroy code in a polled wait for up to 30 minutes to make sure all
resources are removed.
https://jira.coreos.com/browse/CORS-1226
> Azure: make cluster destroy code more robust

- docs/user/customization.md
We need to support this for cases such as `nosmt` and others.
Clarify that it's supported and elaborate on that a bit.
> docs/customization: Clarify "day 1" MachineConfigs are supported

- data/data/rhcos-amd64.json
- data/data/rhcos.json
- pkg/asset/installconfig/vsphere/vsphere.go
- pkg/asset/machines/vsphere/machines.go
- pkg/types/vsphere/validation/platform.go
- pkg/types/vsphere/validation/platform_test.go
- upi/azure/05_masters.json
Rebase fcos on latest commits from release-4.5
```
TARGET_COMMIT=$(git describe --tags fcos | sed 's/.*-g//')
git checkout -b fcos-rebase-aug12 origin/release-4.5
git rebase --onto fcos $TARGET_COMMIT
```
> [FCOS] Rebase Aug 12

- data/data/rhcos-s390x.json
Bump RHCOS images for s390x with the latest pipeline image similar to #4021
> Bump rhcos images for s390x

- docs/user/openstack/README.md
- docs/user/openstack/deploy_baremetal_workers.md
/cc @luis5tb @adduarte @mandre @maxwelldb
> openstack: Known issue: no BMs on Kuryr

- docs/user/openstack/install_upi.md
A fixup of https://github.com/openshift/installer/pull/4047
> Bug 1868439: openstack UPI: Fix Ignition v3

- pkg/destroy/aws/aws.go
Managed policies could be attached after initial installation. In order
to delete the IAM roles created during install, these custom managed
polices should be detached allowing the role to be deleted.
> Bug 1871712: pkg/destroy/aws: Detach attached policies during destroy

- docs/user/ovirt/install_upi.md
Moving Network Requirements upper to keep all the requirements at the
beginning
> Bug 1876792: oVirt UPI Move Network Requirements section

- docs/user/openstack/install_upi.md
Added required documentation describing the roles
and requirements of apiVIP and ingressVIP fields in install-config.yaml
> Bug 1873125: OpenStack:  UPI missing instructions to update apiVIP and ingressVIP

- data/data/bootstrap/files/usr/local/bin/installer-masters-gather.sh
Needed to get insights into https://github.com/openshift/machine-config-operator/pull/2011.
> Bug 1877741: installer-masters-gather.sh: gather openshift-{azure,gcp}-routes logs

- docs/user/ovirt/install_upi.md
Add RHCOS better explanations, introduce assets directory env variables
to be used by python scripts and inventory.
Better clarify that api vip and ingress vip can be the same.
> Bug 1877436: oVirt UPI RHCOS explanations, assets env var

- pkg/destroy/openstack/openstack.go
To support a fip less installation and bring your
own network when using Kuryr, new interfaces are
added to a custom Router that may exist, enabling
traffic between Pods, Services and VMs. As the
Router is not created by the installer its interfaces
must be cleaned up upon cluster Destroy.
This commit solves the issue by discovering the
Router through the Primary Network and the gateway
interface attached to the Router.
> Bug 1874457: Add support to clean custom router

- docs/user/ovirt/install_upi.md
Remove unnecessary semicolons from python code snippets
> Bug 1877763: oVirt UPI - python code snippets without semicolons

- docs/user/ovirt/install_upi.md
Add a doc section to provide a command to download Ansible playbooks
> Bug 1877885: oVirt UPI - Add Ansible playbooks download

- data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
Follow up to https://github.com/openshift/installer/pull/4131
Requires:
/hold
> Bug 1861917: Add cpc config to bootstrap

- data/data/bootstrap/openstack/OWNERS
- data/data/openstack/OWNERS
- images/openstack/Dockerfile.ci
- images/openstack/OWNERS
- pkg/asset/cluster/openstack/OWNERS
- pkg/asset/installconfig/openstack/OWNERS
- pkg/asset/machines/openstack/OWNERS
- pkg/asset/manifests/openstack/OWNERS
- pkg/destroy/openstack/OWNERS
- pkg/tfvars/openstack/OWNERS
- pkg/types/openstack/OWNERS
- upi/openstack/OWNERS
cf https://github.com/openshift/installer/pull/4161
Also set reviewers for the OpenStack folders.
> Bug 1878369: openstack: Upgrade the CI build image

- docs/user/ovirt/install_upi.md
Adds a working inventory.yml example and better explanations to that
> Bug 1879533: oVirt UPI - Better explanation of the inventory

- data/data/fcos-amd64.json
- data/data/fcos.json
> [FCOS] Update FCOS to 32.20200907.3.0 

- data/data/rhcos-amd64.json
- data/data/rhcos.json
This fixes numerous bugs, such as:
- https://bugzilla.redhat.com/show_bug.cgi?id=1879690
- https://github.com/coreos/ignition/issues/1081
- https://bugzilla.redhat.com/show_bug.cgi?id=1875567
> Bug 1881487: data/rhcos.json: Update to 46.82.202009220041-0

- OWNERS_ALIASES
- data/data/bootstrap/openstack/OWNERS
- data/data/openstack/OWNERS
- images/openstack/Dockerfile.ci
- images/openstack/OWNERS
- pkg/asset/cluster/openstack/OWNERS
- pkg/asset/installconfig/openstack/OWNERS
- pkg/asset/machines/openstack/OWNERS
- pkg/asset/manifests/openstack/OWNERS
- pkg/destroy/openstack/OWNERS
- pkg/tfvars/openstack/OWNERS
- pkg/types/openstack/OWNERS
- upi/openstack/OWNERS
cf #4161
cf #4164
Also set reviewers for the OpenStack folders.
/cc mandre adduarte Fedosin iamemilio
> Bug 1880988: openstack: Upgrade the CI build image

- pkg/tfvars/gcp/gcp.go
Fix json tag for GCP auth service account.
> Fix json tag for GCP auth service account

- data/data/fcos-amd64.json
- data/data/fcos.json
Update base image to latest stable FCOS
> [FCOS] Update FCOS to 32.20200923.3.0

- pkg/tfvars/openstack/openstack.go
Previously we validate overriden Glance images during generation of tfvars variables. This is not a correct place to do it, so we
implemented the check in the "validation" module:
https://github.com/openshift/installer/pull/3964
To prevent code duplication we should remove the legacy code.
> OpenStack: remove legacy image validation

- upi/ovirt/README.md
Broken link. Fixed the spelling.
> Update README.md - Broken Link - Spelling

- OWNERS_ALIASES
> openstack: Add a new team member

- pkg/asset/ignition/bootstrap/bootstrap.go
When loading bootstrap.ign, check if there are expired certificates and display a warning if so.
https://bugzilla.redhat.com/show_bug.cgi?id=1870728
> bug 1870728: pkg/asset/ignition/bootstrap: Display warning if certificates are expired

- go.mod
- vendor/modules.txt
go mod tidy && go mod vendor to fix issue with missing klog
> go.mod Update

- data/data/fcos-amd64.json
- data/data/fcos.json
- images/installer/Dockerfile.upi.ci
> [FCOS] update base FCOS to 32.20201004.3.0

- OWNERS_ALIASES
Make sure @staebler can help approve the PRs in case others (like me :P) are not available.
/assign @sdodson
> install-approvers: add staebler

- cmd/openshift-install/migrate/azure/migrate.go
- pkg/asset/ignition/node.go
- pkg/asset/installconfig/aws/subnet.go
- pkg/asset/installconfig/azure/dns.go
- pkg/asset/installconfig/gcp/client.go
- pkg/asset/installconfig/gcp/session.go
- pkg/asset/installconfig/ovirt/credentials.go
- pkg/asset/kubeconfig/kubeconfig.go
- pkg/destroy/aws/aws.go
- pkg/destroy/azure/azure.go
- pkg/destroy/gcp/gcp.go
- pkg/destroy/gcp/instancegroup.go
- pkg/destroy/openstack/openstack.go
- pkg/gather/ssh/ssh.go
- pkg/metrics/timer/timer_test.go
- pkg/migrate/azure/privatedns.go
- pkg/tfvars/openstack/openstack.go
- pkg/types/baremetal/rootdevice.go
- pkg/types/conversion/installconfig.go
This commit fixes issues that were found by:
`golangci-lint run pkg/... --disable-all -E gosimple -E unused`
> Code cleanup and optimizations

- OWNERS_ALIASES
> owners: Add mdbooth to openstack-approvers

- docs/user/ovirt/install_ipi.md
Following https://bugzilla.redhat.com/show_bug.cgi?id=1804230#c7
> Small corrections in ovirt/install_ipi.md

- data/data/manifests/bootkube/etcd-client-secret.yaml.template
- data/data/manifests/bootkube/etcd-metric-client-secret.yaml.template
- data/data/manifests/bootkube/etcd-metric-signer-secret.yaml.template
- data/data/manifests/bootkube/etcd-signer-secret.yaml.template
> Use 'kubernetes.io/tls' instead of SecretTypeTLS which is not being substituted

- pkg/asset/installconfig/aws/basedomain.go
- pkg/asset/installconfig/azure/dns.go
- pkg/asset/installconfig/basedomain.go
- pkg/asset/installconfig/clustername.go
- pkg/asset/installconfig/gcp/dns.go
- pkg/asset/installconfig/libvirt/libvirt.go
- pkg/asset/installconfig/openstack/openstack.go
- pkg/asset/installconfig/ovirt/cluster.go
- pkg/asset/installconfig/ovirt/network.go
- pkg/asset/installconfig/ovirt/ovirt.go
- pkg/asset/installconfig/ovirt/storage.go
- pkg/asset/installconfig/pullsecret.go
- pkg/asset/installconfig/ssh.go
- pkg/asset/installconfig/vsphere/vsphere.go
Standardizes error messages when encountered in survey.
> Bug 1855351: standardize interrupt error messages

- pkg/tfvars/azure/azure.go
> [OKD] pkg/tfvars/azure: cache FCOS image

- pkg/asset/quota/quota.go
> make sure you have `servicequotas:ListAWSDefaultServiceQuotas`
> persmission available to the user`
^
> pkg/asset/quota: Typo in warning message presented to user

- docs/user/openstack/install_upi.md
Adds docs for manually creating worker nodes with SR-IOV NICs attached. These
docs walk users through what basic components are needed and why, as well as
providing examples using the openstack command line client.
Fixes: [OSASINFRA-2159](https://issues.redhat.com/browse/OSASINFRA-2159)
> Create SR-IOV UPI Docs

- hack/openstack/test-manifests.sh
- images/openstack/Dockerfile.ci
- scripts/openstack/manifest-tests/additional-security-group/test_masters.sh
- scripts/openstack/manifest-tests/additional-security-group/test_workers.sh
- scripts/openstack/manifest-tests/nova-availability-zones/install-config.yaml
- scripts/openstack/manifest-tests/nova-availability-zones/test_machinesets.py
* instrument the manifest-generation test-framework to execute Python
testfiles
* test machinesets with availability zones
only)
> openstack: Test Nova AZ manifest generation

- OWNERS_ALIASES
adding: janoszen and dougsland
> oVirt: update team members

- docs/user/gcp/customization.md
This is a follow up to #4318 to add the new fields to the customization document for GCP
> [OCRS-1577] Update GCP Customization doc to reflect CMEK additions

- pkg/asset/installconfig/aws/permissions.go
- pkg/asset/installconfig/platformpermscheck.go
- upi/openstack/bootstrap.yaml
Cherrypick fresh fixes in `fcos` branch.
> [FCOS] Periodic rebase on release-4.6

- pkg/asset/installconfig/vsphere/vsphere.go
This change modifies the vsphere prompt behavior for both datacenter and
cluster inputs. When these items exist within one or more folders in
the vsphere infrastructure, the folder names will be added as a prefix
to the item in the list of choices. As a result, this folder information
will now be saved into the install-config.yaml and used to deploy the
cluster.
> Bug 1882022: installconfig: enable vsphere folders for datacenters and clusters.

- data/data/fcos-amd64.json
- data/data/fcos.json
> [FCOS] Update base image to 33.20201201.3.0

- data/data/fcos-amd64.json
- data/data/fcos.json
Updates base FCOS to latest stable
> [FCOS] Update FCOS to 33.20201214.3.1

- data/data/fcos-amd64.json
- data/data/fcos.json
Update base FCOS image to latest stable
> [fcos] Update FCOS to 33.20210104.3.0

- data/data/rhcos-amd64.json
- data/data/rhcos-ppc64le.json
- data/data/rhcos-s390x.json
- data/data/rhcos.json
See the dependencies of [RHBZ 1915617](https://bugzilla.redhat.com/show_bug.cgi?id=1915617) for the list of fixes.
| Platform | Version |
| - | - |
| amd64 | 47.83.202101161239-0 |
| ppc64le | 47.83.202101161312-0 |
| s390x | 47.83.202101160310-0 |
> Bug 1915617: update boot images for various fixes

- pkg/asset/installconfig/openstack/validation/cloudinfo.go
- pkg/asset/installconfig/openstack/validation/machinepool.go
- pkg/asset/installconfig/openstack/validation/machinepool_test.go
- pkg/asset/quota/openstack/openstack.go
Fixes https://bugzilla.redhat.com/1907822
> Bug 1907822: Don't panic on bad data in quota validations

- upi/aws/cloudformation/03_cluster_security.yaml
Signed-off-by: Mark Gray <mark.d.gray@redhat.com>
> Bug 1919072: AWS cloudformation change protocol from ESP to 50

- pkg/terraform/exec/plugins/vsphereprivate/resource_vsphereprivate_import_ova.go
This change modifies the vsphereprivate terraform provider to ignore
all hosts in maintenance mode when importing the rhcos ova. As a result,
it will no longer throw an error when selecting a host in maintenance
mode to upload the ova to.
> Bug 1893117: terraform/vsphereprivate: ignore hosts in maintenance mode

- data/data/openstack/main.tf
- data/data/openstack/topology/private-network.tf
- data/data/openstack/topology/variables.tf
- docs/user/openstack/README.md
- docs/user/openstack/customization.md
- pkg/asset/installconfig/openstack/validation/cloudinfo.go
- pkg/asset/installconfig/openstack/validation/machinepool.go
- pkg/asset/installconfig/openstack/validation/machinepool_test.go
Periodic rebase of OKD installer on `release-4.6` branch
> [FCOS] Rebase on release-4.6

- pkg/asset/installconfig/openstack/validation/cloudinfo.go
Now we check wrong error types and therefore sometimes validation may fail.
This commit fixes it by unifing all error types in `isNotFoundError` function.
> Bug 1921655: OpenStack: fix error handling for cloudinfo

- pkg/destroy/openstack/openstack.go
When using byo the cluster destroy was relying on the
primary network tag to identify the router used and remove
the extra interfaces. As the provided network is not tagged
anymore the cluster is not able to get cleaned up. This commit
fixes the issue by relying on the network used by the Servers
to identify the router used.
> Bug 1924701: Fix cluster destroy when byo is used with Kuryr

- data/data/fcos-amd64.json
- data/data/fcos.json
Update to latest stable with CVE fixes
> [FCOS] Update FCOS to 33.20210117.3.2

- docs/user/vsphere/privileges.md
> vSphere: Updating Privileges, roles and permissions

- pkg/destroy/openstack/openstack.go
During a FIP less installation VMs that were not
created by the installer can get a FIP detached when
the cluster in being destroyed. This commit fixes the
issue by detaching only FIPs that were created by
installer or Kuryr during a FIP less installation.
> bug 1924701: Fix FIP detach from Router

- docs/dev/libvirt/README.md
quick fix to add sudo to iptables command in libvirt docs
> update iptables call with sudo

- pkg/types/validation/installconfig.go
- pkg/types/validation/installconfig_test.go
Adding a validation to check if the provided httpProxy and
httpsProxy are not a part of the service or cluster networks
to prevent customers from trying to proxy into those networks.
> proxy: Check if proxies are in cluster and service networks

- upi/openstack/control-plane.yaml
- upi/openstack/down-control-plane.yaml
Fix https://github.com/openshift/installer/issues/4374
> Bug 1910067: openstack UPI: Set the API microversion when operating openstack server groups

- docs/user/kubevirt/role.yaml
- pkg/asset/installconfig/kubevirt/client.go
- pkg/asset/installconfig/kubevirt/mock/client_generated.go
- pkg/asset/installconfig/kubevirt/validation.go
- pkg/asset/installconfig/kubevirt/validation_test.go
- pkg/asset/installconfig/platformpermscheck.go
Added validation of user permissions for platform kubevirt
https://issues.redhat.com/browse/CNV-10142
> kubevirt platfrom validate permissions

- pkg/asset/installconfig/aws/validation.go
This change ensures any provided endpoints can be resolved via
DNS and connected to while parsing the install config.
https://issues.redhat.com/browse/CORS-1546
> installconfig/aws: validate connectivity to service endpoints.

- pkg/tfvars/libvirt/libvirt.go
As per https://github.com/hashicorp/terraform/issues/3287 terraform requires that libvirt_master_size be specified as a number denominated in bytes rather than the canonical bytes (e.g. 1024M) returned by kube's Quantity.String() method. This change ensures that overriding the libvirt master volumeSize in generated install manifests will result in valid terraform configuration. This allows a libvirt SNO cluster to run more than just the control plane (i.e. making it more useful for developers).
/cc @romfreiman @praveenkumar @staebler
> Support configurable libvirt disk size

- README.md
there is no `install` command, the command is `create`
> README: change install to create

- OWNERS_ALIASES
Add @e-tienne and @rna-afk to the reviewer rotation.
/assign @staebler
> Update owners with new Installer Team members

- pkg/asset/installconfig/kubevirt/client.go
- pkg/asset/installconfig/kubevirt/mock/client_generated.go
- pkg/asset/installconfig/kubevirt/validation.go
- pkg/asset/installconfig/kubevirt/validation_test.go
- pkg/asset/installconfig/platformprovisioncheck.go
In Kubevirt platform the CSI driver requires this feature gate
https://issues.redhat.com/browse/CNV-9820
> Validate HotplugVolumes feature gate in Kubevirt

- pkg/asset/installconfig/aws/validation.go
Allow the user to specify a region that is not known to the instatller but does match the regex of a known partition without requiring the user to specify custom service endpoints. This is needed to support new regions that are added to known partitions.
Without this, it is not possible to use an unknown region is the standard partition. Terraform will not create the IAM roles correctly when specifying custom endpoints for a region in the standard partition because the request will try to create the role in the cluster's region rather than in us-east-1.
This seems like the behavior that was desired when the check for whether custom service endpoints are needed was added in https://github.com/openshift/installer/commit/cf79a75308faf38e11f758457ca40748b797e56a.
In addition to relaxing the …
> Bug 1944268: aws: allow use of unknown regions in known partitions

- images/installer/Dockerfile.upi.ci
Testing to see if this can help unblock the GCP issue with yum.
> Test GCP versioned binary

- data/data/ovirt/main.tf
- data/data/ovirt/variables-ovirt.tf
- go.mod
- go.sum
- pkg/asset/cluster/tfvars.go
- pkg/tfvars/ovirt/ovirt.go
- vendor/github.com/ovirt/go-ovirt/CHANGES.adoc
- vendor/github.com/ovirt/go-ovirt/readers.go
- vendor/github.com/ovirt/go-ovirt/services.go
- vendor/github.com/ovirt/go-ovirt/types.go
- vendor/github.com/ovirt/go-ovirt/writers.go
- vendor/github.com/ovirt/terraform-provider-ovirt/ovirt/provider.go
- vendor/github.com/ovirt/terraform-provider-ovirt/ovirt/resource_ovirt_host.go
- vendor/github.com/ovirt/terraform-provider-ovirt/ovirt/resource_ovirt_vm.go
- vendor/modules.txt
This PR fixes BZ 1937722. Please see that BZ for details.
> Bug 1937722: OCP 4.8: Passing oVirt certificate information to Terraform

- pkg/asset/installconfig/aws/permissions.go
iam:ListAttachedRolePolicies
Permission required since #4126
> Bug 1938131: pkg/asset/installconfig/aws: Add iam permission for destorying clusters

- go.mod
- go.sum
- vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/data_source_ironic_introspection.go
- vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/provider.go
- vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/resource_ironic_allocation_v1.go
- vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/resource_ironic_deployment.go
- vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/resource_ironic_node_v1.go
- vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/resource_ironic_port_v1.go
- vendor/github.com/openshift-metal3/terraform-provider-ironic/ironic/workflow.go
- vendor/modules.txt
> update terraform-provider-ironic to v0.2.5 to get better error handling

- docs/user/ovirt/install_upi.md
Add a note about requiring set ASSET_DIR.
> Bug 1923786: UPI oVirt - replace word in docs

- pkg/destroy/openstack/openstack.go
Now installer deletes only volumes created by the in-tree provisioner, omitting those created by the CSI driver, which leads to resource leakage.
This commit starts deleting CSI volumes and snapshots as well.
> Bug 1909136: destroy volumes and snapshots created by Cinder CSI driver

- data/data/rhcos-amd64.json
- data/data/rhcos-ppc64le.json
- data/data/rhcos-s390x.json
- data/data/rhcos-stream.json
- data/data/rhcos.json
```
x86_64  48.84.202104271417-0
s390x   48.84.202104271619-0
ppc64le 48.84.202104261624-0
```
> Bug 1955701: Bump boot images for RHEL 8.4 Beta

- pkg/destroy/aws/aws.go
During AWS destroy cluster sequence, the instances are requested
to be shut down but they do not get terminated for a long time.
The installer ignores all the EC2 instances that are in "shut-down"
status as they take a long time to complete but sometimes these
instances are stuck at the same status for a long time.
A fresh termination request has a more better chance at destroying
these stuck instances and hence changing the code to send the
termination request even for the instances in "shut-down" status.
> Bug 1957951: AWS: Periodically send shut down requests for stuck EC2 instances

- pkg/destroy/openstack/openstack.go
When using your own Network for the Machines
connected to a tagged Router created by CNO
on an installation with Kuryr, the Subnet of
that Network is not tagged and consequently
not identified by installer when destroying
the Router. This commit fixes the issue by
ensuring all Subnetes connected to a Router
created by Installer or CNO are removed.
> Bug 1940159: Fix Routers destroy with BYO

- pkg/types/gcp/validation/platform.go
Add new region europe-central (zone europe-central2)
https://issues.redhat.com/browse/CORS-1673
> Bug 1957260: gcp: add new region europe-central2

- pkg/destroy/openstack/openstack.go
It turned out that Cinder CSI driver doesn't attach cluster id to volume snapshot metadata. To workaround this we delete snapshots based on their volume IDs.
This is a workaround PR to support volume snapshot deletion in 4.8. It should be reverted when the upstream fix is merged: https://github.com/kubernetes/cloud-provider-openstack/pull/1544
> Bug 1909136: OpenStack: delete volume snapshots

- pkg/destroy/openstack/openstack.go
This commit adds a function that deletes manila shares and their snapshots when the cluster is being destroyed.
> Bug 1820238: delete manila shares and snapshots along with the cluster

- data/data/rhcos-aarch64.json
- data/data/rhcos-amd64.json
- data/data/rhcos-ppc64le.json
- data/data/rhcos-s390x.json
- data/data/rhcos-stream.json
- data/data/rhcos.json
See https://github.com/openshift/release/pull/18496
and https://issues.redhat.com/browse/DPTP-2198
This is not the final location, but it's better than the previous
version on the old cluster.
> Bug 1963205: rhcos: Use ART redirector

- pkg/tfvars/vsphere/OWNERS
> /pkg/tfvars/vsphere: add OWNERS

- docs/user/openstack/deploy_sriov_workers.md
This use case requires a unique usage pattern in comparison to what the
customer may be use to, so we chose to document it in its entirety to
avoid any confusion down the line.
> Bug 1970415: Document SR-IOV use case: using network with port security disabled

- upi/metal/bootstrap/packet.tf
- upi/metal/bootstrap/variables.tf
- upi/metal/config.tf
- upi/metal/main.tf
- upi/metal/terraform.tfvars.example
Allow facilities, plan and hardware_reservation_id to be configured.
> bug 1925343: upi/metal: add more configuration options for bare metal

- docs/dev/pinned-coreos.md
> fixing a link

- OWNERS_ALIASES
Add jhixson74, jstuever, and patrickdillon as installer-approvers.
> OWNERS: add more core team members as approvers

- pkg/asset/installconfig/openstack/validation/platform.go
- pkg/asset/installconfig/openstack/validation/platform_test.go
https://github.com/openshift/installer/issues/4945
> Openstack IPI: Validate API and Ingress VIPs are not the same

- pkg/destroy/openstack/openstack.go
There could be cases where the trunk is not properly tagged, for
example the UPI scripts do not set tags to trunk since the openstack
client doesn't support it.
Failure to delete trunks could result in the destroy command stuck in
a loop until it hits the timeout.
In these cases, the cluster destroy should be smart enough to try
deleting trunks for which the tagged port is a parent.
> Bug 1971518: Try deleting associated trunk after port delete failure

- docs/user/gcp/install_upi.md
Removing etcd DNS records related stuff, which is no longer needed in 4.4 and above.
> doc/gcp: remove no-longer-needed etcd records

- images/baremetal/Dockerfile.ci
Backport of https://github.com/openshift/installer/pull/4854
> Bug 1977481: Dockerfile: repin libvirt

- pkg/asset/cluster/tfvars.go
- pkg/tfvars/openstack/bootstrap_ignition.go
- pkg/tfvars/openstack/openstack.go
This is an manual cherry-pick of #4804
> [release-4.6] Bug 1949150: add proxy params to bootstrap ignition

- pkg/destroy/openstack/openstack.go
To implement `LoadBalancer` `Services` OpenStack Cloud Provider creates an
LB in Octavia for each of them. Those LBs have floating IPs associated
to the LB VIPs. As this is handled by the Cloud Provider itself,
Octavia's cascade delete will not remove those FIPs and we need to take
care of that ourselves.
This commit adds deleting of the FIPs associated to the LBs on
destroying cluster. In order to do that correctly it was required to
split deleting routers into two separate functions and make sure that
FIP detach and actual removal of the routers is happening after all the
delete functions finished (meaning that LBs are gone too). This is
because if FIP detach happens before we lose information about which FIP
was attached to which LB effectively preventing us from handling
deletion of …
> OpenStack: Remove FIPs of LBs created by cloud-provider

- docs/user/openstack/known-issues.md
> Bug 1969374: document how to update domain for image registry in versions <4.8

- go.mod
- go.sum
- pkg/asset/machines/master.go
- pkg/asset/machines/worker.go
- pkg/asset/quota/quota.go
- vendor/github.com/IBM/platform-services-go-sdk/catalogmanagementv1/catalog_management_v1.go
- vendor/github.com/IBM/platform-services-go-sdk/common/version.go
- vendor/github.com/IBM/platform-services-go-sdk/resourcecontrollerv2/resource_controller_v2.go
- vendor/github.com/openshift/cluster-api-provider-ibmcloud/pkg/apis/addtoschema_ibmcloudprovider_v1beta1.go
- vendor/github.com/openshift/cluster-api-provider-ibmcloud/pkg/apis/apis.go
- vendor/modules.txt
IBM Cloud platform will not have any quota checks for now. Removing placeholders in code.
> ibmcloud: Remove quota check placeholders

- pkg/asset/manifests/ibmcloud/cloudproviderconfig.go
- pkg/asset/manifests/ibmcloud/cloudproviderconfig_test.go
Updating IBM Cloud provider config to add/remove required conf fields.
> ibmcloud: Update cloud provider config

- OWNERS_ALIASES
> release-4.6: Update OpenStack approvers

- pkg/asset/installconfig/openstack/validation/cloudinfo.go
Before this patch, the OpenStack usage fetcher ("cloudinfo") conflates
the number of in-use resources with the quota and passes that to the
generic checker.
With this patch, the OpenStack usage fetcher ("cloudinfo") collects
usage and limit data in separate fields, so that the generic checker
outputs a more precise error message when the installation fails due to
insufficient resources. For example: "the required number of resources
(1499) is more than remaining quota of 1498" instead of "the required
number of resources (1499) is more than the limit of 1498".
> Bug 2001317: openstack: Inaccurate MissingQuota error

- OWNERS_ALIASES
Update to reflect the currently-active team after discussions with @patrickdillon
> Update baremetal approvers/reviewers

- data/data/ibmcloud/network/vpc/security-groups.tf
Allow access to Kubernetes NodePorts from within both the control plane and compute subnets. This will allow for cloud provider (CCM) managed LBs to reach to the cluster nodes.
> fix(ibmcloud): Allow NodePort access from all subnets

- pkg/destroy/quota/quota.go
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
/assign @jstuever @patrickdillon
> pkg/destroy: log when writing quota for visibility

- pkg/asset/cluster/tfvars.go
- pkg/tfvars/ibmcloud/ibmcloud.go
Add support for IBM Cloud to use configuration values for install
resources, such as from install-config.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2009791
> Bug 2009791: Fix IBM Cloud config usage

- data/data/ibmcloud/network/image/main.tf
This change resolves a formatting error in the ibmcloud terraform code.
> ibmcloud: fix terraform formatting error from #5147

- pkg/types/alibabacloud/validation/platform.go
- pkg/types/alibabacloud/validation/platform_test.go
- pkg/types/validation/installconfig.go
Validate if  machine, service and cluster networking CIDR  contains metadata server IP
> Alibaba:  add metadata server IP validation

- images/installer/Dockerfile.ci.rhel7
- images/installer/Dockerfile.upi.ci
- images/installer/Dockerfile.upi.ci.rhel8
- images/libvirt/Dockerfile.ci
- images/openstack/Dockerfile.ci
- pkg/asset/releaseimage/default.go
Update the default release payload to 4.10
> update registry.ci.openshift.org/ocp and origin images to 4.10

- data/data/alibabacloud/cluster/vpc/vpc.tf
Use the max function is a lot easier to read
> Alibaba: fix: use the max function

- data/data/alibabacloud/bootstrap/main.tf
- data/data/alibabacloud/cluster/main.tf
- pkg/asset/machines/alibabacloud/machines.go
Add a tag sigs.k8s.io/cloud-provider-alibaba/origin for cloud resources, this helps Alibaba Cloud to count the data of cloud resources
> Alibaba: update tags for cloud resources

- pkg/destroy/openstack/openstack.go
OpenStack Neutron is slow but it's sometimes able to handle quite a few
requests in parallel. This commit splits the operation of Neutron port
deletion into 10 concurrent goroutines to speed it up. This mostly aids
Kuryr case when we can have hundreds of ports created that block
deletion of other resources.
> OpenStack: Parallelize port deletion

- pkg/asset/cluster/alibabacloud/alibabacloud.go
- pkg/types/alibabacloud/metadata.go
Remove unused ResourceGroupID in metadata
> Alibaba: fix: remove unused ResourceGroupID

- upi/azure/05_masters.json
Bug 1964380 [DOC] Remove the etcd DNS records
> Bug 1964380: azure upi: do not create etcd DNS records

- docs/user/azure/install_upi.md
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1968364#c17
> Bug 1968364: azure: Update upi docs to remove mentions of sshKeyData

- docs/user/azure/install_upi.md
[Remove the etcd DNS records from the Azure ARM templates](https://bugzilla.redhat.com/show_bug.cgi?id=1964380)
> Bug 1964380: remove privateDNSZoneName

- docs/user/azure/install_upi.md
To avoid changing the VHD_URL with the release version, get VHD_URL with "openshift-install coreos print-stream-json"
> azure upi: get VHD_URL with openshift-install coreos print-stream-json

- docs/user/openstack/README.md
Implements [OSASINFRA-2380](https://issues.redhat.com/browse/OSASINFRA-2380)
> openstack: Document credential rotation

- pkg/destroy/alibabacloud/alibabacloud.go
Format the log of the destroyer and output more resource information
> Alibaba: format the log of the destroyer

- docs/user/openstack/README.md
Provide an example script.
The script is a combination of:
* [OpenStack node migration][1]
* [OpenShift graceful node reboot][2]
Implements [OSASINFRA-2508](https://issues.redhat.com/browse/OSASINFRA-2508)
[1]: https://docs.openstack.org/nova/latest/admin/migration.html
[2]: https://docs.openshift.com/container-platform/4.9/nodes/nodes/nodes-nodes-rebooting.html#nodes-nodes-rebooting-gracefully_nodes-nodes-rebooting
> openstack: Document Control plane node migration

- pkg/asset/installconfig/ibmcloud/ibmcloud.go
The installer supports creating a resource group for the user wheninstalling to ibmcloud. This should be the default, opinionated way that the installer in which the installer is configured. As such,the installer should not be asking in the survey for the user to provide an existing resource group to use.
> ibmcloud: remove resource group question from survey

- pkg/asset/installconfig/alibabacloud/alibabacloud.go
Because the `defaultRegion` is `cn-hangzhou`, so when the step
of selecting the region is executed, if you do nothing and just
press enter, the default value `cn-hangzhou` will be displayed,
although it seems to be the first choice options.
Signed-off-by: sunhui <wb-sh373163@alibaba-inc.com>
> Bug 2033239: Alibaba: fix the wrong default region

- pkg/types/gcp/validation/platform.go
Add northamerica-northeast-2 region to GCP validation
> Bug 2039408: Add northamerica-northeast-2 region to GCP validation

- pkg/destroy/alibabacloud/alibabacloud.go
Search and delete the OSS bucket by tag, otherwise the OSS bucket created during installation for image registry will be missed
> Bug 2035454: [alibaba] fix deletion of the OSS bucket

- pkg/asset/installconfig/alibabacloud/basedomain.go
- pkg/asset/installconfig/alibabacloud/client.go
- pkg/asset/installconfig/basedomain.go
Existing base domains should be automatically listed.
> Bug 2033524: [Alibaba] support for list existing domains

- data/data/alibabacloud/cluster/vpc/slb.tf
Disable session persistence and removebBandwidth peak of listener
> Bug 2041361: [Alibaba] fix load balance listener strategy

- pkg/asset/quota/aws/aws.go
The AWS ec2 instances with instance types of G and VT were being
treated as type X instance and are not treated as their own
individual instances. Adding G and VT as valid instance types
in the quota check for AWS.
> Bug 2017874: Check quota for G and VT instances

- docs/user/openstack/invalid-https-certificates.md
Fix the reference to an unbound variable; avoid incrementing the invalid
certificate counter in a subshell.
/cc mandre
> Bug 2038166: openstack: Fix invalid-https-certificate detection

- data/data/alibabacloud/cluster/vpc/vpc.tf
Fix the overlapping problem of the VSwitch subnet of the Nat gateway with the master node VSwitch subnets
> Bug 2041319: [Alibaba] fix VSwitch subnets overlap

- pkg/asset/installconfig/alibabacloud/validation.go
And add NAT gateway validation to check the region whether support NAT gateway
> Bug 2042370: [Alibaba] fix installer index panic

- pkg/destroy/alibabacloud/alibabacloud.go
The destroyer should not error when it attempts to delete a security group that does not exist.
> Bug 2043003: [Alibaba] fix destroy not exist security group

- pkg/asset/installconfig/alibabacloud/client.go
- pkg/asset/installconfig/alibabacloud/validation.go
Fix resource group ID validation errors caused by pagination issues
> Bug 2047255: [Alibaba] fix validation of resource group ID

- OWNERS_ALIASES
Remove Caleb Boylan from core installer reviewers
> Remove Caleb Boylan from core installer reviewers

- pkg/destroy/vsphere/vsphere.go
While https://github.com/vmware/govmomi/issues/2710 is not fixed
upstream, let's carry our own fixed version: try out all the category
ids before erroring out.
Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>
> Bug 2021041: vsphere: Not found TagCategory when destroying ipi cluster

- docs/user/azure/install_upi_azurestack.md
06_workers.json from azure will not work here
> point 06_workers.json to azurestack version

- docs/dev/terraform.md
Add a dev document for describing how to maintain the terraform binaries embedded in the installer.
> doc: terraform maintenance document

- data/data/azure/bootstrap/main.tf
- data/data/azure/cluster/main.tf
- data/data/azure/cluster/master/master.tf
- data/data/azure/cluster/master/variables.tf
- data/data/azure/variables-azure.tf
- data/data/install.openshift.io_installconfigs.yaml
- docs/user/azure/customization.md
- pkg/asset/installconfig/azure/mock/azureclient_generated.go
- pkg/asset/installconfig/azure/validation_test.go
- pkg/asset/machines/azure/machines.go
- pkg/asset/machines/master.go
- pkg/asset/machines/worker.go
- pkg/tfvars/azure/azure.go
- pkg/types/azure/disk.go
- pkg/types/azure/machinepool.go
- pkg/types/azure/validation/disk.go
- pkg/types/azure/validation/disk_test.go
- pkg/types/azure/validation/platform.go
Add support for encryption at host and disk encryption with a disk encryption set ID. 
https://issues.redhat.com/browse/CORS-1889
https://issues.redhat.com/browse/CORS-1890
https://issues.redhat.com/browse/CORS-1891
> Azure disk encryption support

- pkg/asset/installconfig/aws/validation.go
This was keeping ValidateForProvisioning from checking if the zone was
associated with a VPC or not.
https://issues.redhat.com/browse/OCPBUGSM-40036
> Bug 2047670: aws: remove validation check for internal publish strategy

- pkg/asset/cluster/metadata.go
- pkg/asset/cluster/powervs/powervs.go
For more background on IPI on Power VS, refer to the enhancement
proposal here: openshift/enhancements#736
> Add IBM Power VS: cluster assets

- data/data/install.openshift.io_installconfigs.yaml
- pkg/explain/printer_test.go
- pkg/types/installconfig.go
- pkg/types/validation/installconfig.go
Co-authored-by: Joel Diaz <jdiaz@redhat.com>
> Bug 2065808: stop considering Mint mode as supported on Azure (#5699)

- data/data/install.openshift.io_installconfigs.yaml
- pkg/explain/printer_test.go
- pkg/types/installconfig.go
- pkg/types/validation/installconfig.go
Co-authored-by: Joel Diaz <jdiaz@redhat.com>
> Bug 2067092: stop considering Mint mode as supported on Azure (#5699)

- pkg/asset/installconfig/alibabacloud/client.go
Add LocationProduct, LocationEndpointType and CommonApi paramaters to use the LocationResolver get endpoint.
> Bug 2048067: [Alibaba] fix location service endpoint

- pkg/asset/cluster/metadata.go
- pkg/asset/cluster/nutanix/nutanix.go
- pkg/asset/ignition/bootstrap/common.go
- pkg/asset/quota/quota.go
- pkg/asset/rhcos/image.go
Add nutanix platform customizations in:
- pkg/asset/cluster
- pkg/asset/ignition
- pkg/asset/quota
- pkg/asset/rhcos
> Add nutanix-specific customizations for assorted  assets

- pkg/destroy/vsphere/virtualmachines.go
- pkg/destroy/vsphere/vsphere.go
Trying to find/delete a resource may fail, so keep trying until it
succeeds or the user stops the application.
> vsphere: make cluster destroy more resilient to api failures

- pkg/tfvars/azure/azure.go
Noticed a refactoring opportunity when reviewing #5756.
Depends on #5756
> Refactor UltraSSD tfvars

- pkg/asset/releaseimage/default.go
This change updates the default release image to use version 4.11.
> Update default releaseimage to 4.11

- pkg/asset/installconfig/installconfig.go
- pkg/asset/installconfig/nutanix/OWNERS
- pkg/asset/installconfig/nutanix/nutanix.go
- pkg/asset/installconfig/nutanix/validation.go
- pkg/asset/installconfig/platform.go
- pkg/asset/installconfig/platformcredscheck.go
- pkg/asset/installconfig/platformpermscheck.go
- pkg/asset/installconfig/platformprovisioncheck.go
- pkg/types/nutanix/client.go
Add nutanix platform customizations in pkg/asset/installconfig.
> Add nutanix-specific customizations to installconfig

- upi/aws/cloudformation/05_cluster_master_nodes.yaml
This PR supersedes broken https://github.com/openshift/installer/pull/4795
cc @staebler
> Removing no-longer-needed DNS etcd stuff

- data/data/install.openshift.io_installconfigs.yaml
- pkg/explain/printer_test.go
- pkg/types/installconfig.go
- pkg/types/validation/installconfig.go
Co-authored-by: Joel Diaz <jdiaz@redhat.com>
> Bug 2069166: stop considering Mint mode as supported on Azure (#5699)

- data/data/install.openshift.io_installconfigs.yaml
- pkg/explain/printer_test.go
- pkg/types/installconfig.go
- pkg/types/validation/installconfig.go
- pkg/types/validation/installconfig_test.go
Expect credentialsMode for Nutanix to be Manual.
> Update installconfig validation for Nutanix

- pkg/types/powervs/powervs_regions.go
- pkg/types/powervs/validation/platform.go
- pkg/types/powervs/validation/platform_test.go
- pkg/types/validation/installconfig_test.go
Validation testcases for the IBM PowerVS platform
> Added platform validation testcases for IBM PowerVS platform

- pkg/asset/quota/quota.go
Adding in the Power VS type to the quota asset
> Power VS quota asset

- pkg/asset/installconfig/vsphere/vsphere.go
Recent changes were applied that enabled the vsphere client to logout
when it was finished. However, in the case of the platform client usage,
it was logging out after validating the credentials but before it was
finished using the client. This was causing an issue when attempting to
connect to the cluster to prodvide additional prompt values.
This change moves the logout to the end of the platform usage so that it
only logs out when the platform is finished using the client.
> Bug 2076393: vsphere: no longer logout of platform client before finished

- data/data/azure/cluster/main.tf
- data/data/azure/cluster/master/master.tf
- data/data/azure/cluster/master/variables.tf
- data/data/azure/variables-azure.tf
- data/data/install.openshift.io_installconfigs.yaml
- docs/user/azure/customization.md
- pkg/asset/installconfig/azure/validation.go
- pkg/asset/installconfig/azure/validation_test.go
- pkg/asset/machines/azure/machines.go
- pkg/tfvars/azure/azure.go
- pkg/types/azure/machinepool.go
- pkg/types/azure/validation/machinepool.go
This code introduces the ability to create control plane nodes with accelerated networking. This feature improves network traffic and adds no additional costs.
> Provider Azure: Enable accelerated networking on control plane nodes 

- cmd/openshift-install/create.go
- pkg/asset/cluster/cluster.go
- pkg/destroy/bootstrap/bootstrap.go
- pkg/terraform/init.go
- pkg/terraform/stage.go
- pkg/terraform/stages/alibabacloud/stages.go
- pkg/terraform/stages/gcp/stages.go
- pkg/terraform/stages/split.go
- pkg/terraform/state.go
- pkg/terraform/terraform.go
PR https://github.com/openshift/installer/pull/5715 with fixes for terraform path. 
https://issues.redhat.com/browse/CORS-1952
> Unpack to install dir

- upi/vsphere/vm/variables.tf
We are spewing out the ignition string
in CI.
> vsphere: upi ignition leak

- data/data/install.openshift.io_installconfigs.yaml
- pkg/types/nutanix/machinepool.go
The earlier comment was erroneous and not reflective of how
Nutanix CPU calculations work.
> Update the comment explaining vCPUs on Nutanix

- data/data/coreos/fcos.json
Cherry-pick of https://github.com/openshift/installer/pull/5817 on release-4.10
> Bug 2076613: [release-4.10] data/data/coreos/fcos.json: update initial FCOS to 35.20220327.3.0

- data/data/powervs/cluster/bootstrap/variables.tf
- data/data/powervs/cluster/master/lb/variables.tf
looks like when i added descriptions to all these variables i bungled a couple, and somehow the terraform provider version isn't new enough. how that was missed is a complete mystery
> Power VS: fix terraform vars 

- upi/azure/03_infra.json
- upi/azure/04_bootstrap.json
- upi/azure/05_masters.json
- upi/azure/06_workers.json
To resolve https://github.com/openshift/release/pull/27977#discussion_r867916077
> update azure arm templates to support customer provided vnet

- pkg/asset/installconfig/azure/validation.go
- pkg/asset/installconfig/azure/validation_test.go
By moving it inside ValidateInstanceType.
> azure: validation: dedup getting the capabilities

- upi/azure/03_infra.json
- upi/azure/04_bootstrap.json
- upi/azure/05_masters.json
- upi/azure/06_workers.json
cherry-pick https://github.com/openshift/installer/pull/5880 to 4.10, so that now the PR landed into the 4.10 upi-installer in prow ci.
> Bug 2084547: update azure arm templates to support customer provided vnet

- cmd/openshift-install/gather.go
- pkg/gather/aws/aws.go
- pkg/gather/aws/register.go
- pkg/gather/doc.go
- pkg/gather/gather.go
- pkg/gather/providers/registry.go
- pkg/gather/providers/types.go
Depends on https://github.com/openshift/installer/pull/5697
https://issues.redhat.com/browse/CORS-1945
> Aws console logs

- data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
The ICC has been renamed to machine-image-customization-controller
> Bug 2085721:  Fix name for customization controller image

- docs/user/openstack/README.md
- docs/user/openstack/deploy_sriov_workers.md
* doc for OVS HW offload
* add a link in README for OVS DPDK
> Bug 2086056: openstack: add doc for OVS HW offload

- pkg/destroy/openstack/openstack.go
This reverts commit a272e59b99f8549a0ad4371151222c0f309b759b. As noted in the corresponding bug [1], the expectation was always to revert this once cloud-provided-openstack started providing cluster ID information in snapshot metadata, which has been the case for some time now [2].
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1965468
[2] https://github.com/kubernetes/cloud-provider-openstack/pull/1544
> Bug 1965468: Revert "Bug 1909136: OpenStack: delete volume snapshots"

- pkg/types/nutanix/helpers.go
- ensure that folder exists before file creation
> Bug 2088660: Fix for absence folder for bootstrap ignition iso

- upi/metal/bootstrap/main.tf
- upi/metal/bootstrap/packet.tf
- upi/metal/main.tf
Update terraform provider source and versions for ignition, matchbox and metal
> Bug 2057582: For metal upi update source and versions of terraform providers

- pkg/destroy/openstack/openstack.go
d2630f299503305d6689bfcb50bfc04e20099c80 implemented deleting ports from
networks even if they're untagged. The motivation was to not block
destroy when some untagged ports were orphaned on the network (in
Neutron tagging is a separate operation that can fail).
As this was always done before deleting the network, we also deleted the
LoadBalancer Services VIP ports (untagged). This means that we couldn't
track down FIPs created for these Services and these were orphaned.
This commit makes sure that we only attempt to delete untagged ports on
409 failure to delete the network. We also do that only after successful
deletion of the LBs to make sure all the Service FIPs are already
tracked down and taken care of.
> Bug 2093368: OpenStack: Fix LoadBalancer FIP deletion on destroy

- pkg/destroy/gcp/cloudcontroller.go
destroy/gcp: Clean target pools, Added Log statements
** Provide a bit more insight through log statements into the actions that the
installer is taking.
** Cleaned up the targetpools by finding all instances then using
the instances names (including the `owned` labeled instances) to
compare to values in the target pools. Valid target pools can be found
and destroyed, causing other resources to be released.
> Bug 2090049: GCP Destroy resources that are owned by cluster

- cmd/openshift-install/create.go
This is a baremetal-specific alternative to #5979
> Bug 2090816: baremetal: wait longer for bootstrap to complete

- pkg/types/powervs/validation/machinepool.go
- pkg/types/powervs/validation/machinepool_test.go
1. Changed Lower limit of CPU
2. Fixes the comment from the PR 5609: https://github.com/openshift/installer/pull/5609/files#r814418626
> [release-4.11.0] Bug 2097239: Changed Lower limits of CPU for PowerVS Cloud

- pkg/asset/installconfig/powervs/session.go
- pkg/asset/quota/quota.go
Added changes for verifying the cloudconnection and dhcpserverinstance details of a powervs instance in the ibm cloud
> [release-4.11.0] Bug 2095226: Added changes to verify cloud connection and dhcp serviceinstance details of a  powervs instance

- pkg/asset/installconfig/ibmcloud/client.go
- pkg/asset/installconfig/ibmcloud/metadata.go
- pkg/asset/installconfig/ibmcloud/mock/ibmcloudclient_generated.go
- pkg/asset/installconfig/ibmcloud/validation_test.go
- pkg/asset/installconfig/installconfig.go
This is PR #6032 but with generated mocks.
> Bug 2099401: IBMCloud: Set regional URL for ibmcloud client

- docs/user/openstack/install_upi.md
This PR adds:
* explanation on how the name of the RHCOS image on Glance must match
the content of inventory.yaml;
* instructions for removing the image after use.
* a scripted unique name for the RHCOS image in Glance, so that the UPI
tests can be run in parallel.
Blocks https://github.com/openshift/release/pull/29672
> openstack UPI: clarify naming of RHCOS image

- docs/user/openstack/install_upi.md
The UPI workflow needs the bootstrap ignition file to be hosted
somewhere. Prior to this patch, the first proposed example used Swift.
However, the example was using commands that are not available in the
openstack client shipped with the recommended operating systems and
repositories.
This patch removes the Swift example and focuses the workflow on using
Glance instead, along the lines of what the IPI installer does. The UPI
docs still mention that any hosting system can be used, including Swift.
> openstack UPI: Remove Swift example, use Glance

- pkg/agent/cluster.go
- pkg/agent/validations.go
- pkg/agent/validations_test.go
This patch enhances the `agent wait-for` commands by reporting any eventual host validation failure (detected by the assisted-service) that could happen during the installation (in particular the bootstrap phase).
Following an example of output: 
```
time="2022-06-20T10:51:34-04:00" level=error msg="Validation failure found for master-0.ostest.test.metalkube.org" category=hardware label="Minimum disks of required size" message="No eligible disks were found, please check specific disks to see why they are not eligible"
time="2022-06-20T10:51:34-04:00" level=error msg="Validation failure found for master-0.ostest.test.metalkube.org" category=hardware label="Installation disk speed" message="Error occurred while getting boot device"
time="2022-06-20T10:51:34-04:00" level=error …
```
> AGENT-172: Monitor hosts validation during installation process

- data/data/ibmcloud/network/main.tf
- data/data/ibmcloud/network/vpc/common.tf
- data/data/ibmcloud/network/vpc/lb-private.tf
- data/data/ibmcloud/network/vpc/lb-public.tf
- data/data/ibmcloud/network/vpc/outputs.tf
- data/data/ibmcloud/network/vpc/security-groups.tf
- data/data/ibmcloud/network/vpc/variables.tf
- data/data/ibmcloud/network/vpc/vpc.tf
- data/data/ibmcloud/variables-ibmcloud.tf
Setup enablement for Bring Your Own Network support on IBM Cloud
using IPI. This portion focuses on adding support in Terraform for
the use of existing network resources.
> IBMCloud: BYON Enablement - Terraform

- cmd/openshift-install/gather.go
- pkg/gather/gcp/gcp.go
- pkg/gather/gcp/register.go
https://github.com/openshift/installer/pull/5807 should merge first.
> Gcp console logs gathering

- data/data/install.openshift.io_installconfigs.yaml
- pkg/asset/installconfig/installconfig_test.go
- pkg/asset/manifests/infrastructure.go
- pkg/explain/printer_test.go
- pkg/types/aws/platform.go
- pkg/types/aws/validation/platform.go
- pkg/types/conversion/installconfig.go
Updated the experimental field for to use a formal field _propagateUserTag_
> [CFE-509] As a developer I want to update installer to use propagateUserFlags for GA

- pkg/asset/agent/mirror/registriesconf.go
This means that validation will happen automatically, and it copes with
empty files.
> AGENT-280: Use toml.Unmarshal to parse registries.conf

- data/data/powervs/cluster/main.tf
- data/data/powervs/cluster/vpc/variables.tf
- data/data/powervs/cluster/vpc/vpc.tf
- data/data/powervs/variables-powervs.tf
Signed-off-by: CS Zhang <zhangcho@us.ibm.com>
> PowerVS: Add 60 sec wait time after VPC creation.

- cmd/openshift-install/agent/waitfor.go
- pkg/agent/cluster.go
- pkg/agent/ocp.go
- pkg/agent/waitfor.go
[AGENT-173](https://issues.redhat.com//browse/AGENT-173)
Add functionality for `openshift-install agent wait-for install-complete`.
> AGENT-173: Add agent wait-for install-complete

- pkg/gather/gcp/gcp.go
> Bug 2114754: gather: properly delete serial log dir

- data/data/coreos/fcos.json
Update FCOS used by OKD to latest stable
> Bug 2105933: data/data/coreos: update FCOS to 36.20220716.3.1

- pkg/asset/releaseimage/default.go
** Update the default release image in master to point to the 4.12 image.
> CORS-2009: Update default release image

- OWNERS_ALIASES
Modified content as instructed by provided documentation
> OWNERS_ALIASES: Add Adam Piasecki (c4rt0)

- OWNERS_ALIASES
Installer team is happy to collaborate with you!
> Add SPLAT members to platform reviewer/approver aliases

- data/data/powervs/variables-powervs.tf
this should speed up our deploys a bit
> powervs: default to tier1 storage

- pkg/types/powervs/validation/machinepool.go
- pkg/types/powervs/validation/machinepool_test.go
To update Max and Min limits for Memory and Processors of the powervs
> IBMCLOUD Power VS: Updated Max and Min machinepool resource limits

- data/data/rhcos-stream.json
Inside the rhcos-stream.json file the locations needed to be updated to the most current version
> Bug 2098252: locations fix

- data/data/bootstrap/files/usr/local/bin/kubelet.sh.template
- pkg/asset/ignition/bootstrap/common.go
This is a manual cherry-pick of #6240
> [release-4.8] OCPBUGS-448: Allow setting bootstrap kubelet ip

- pkg/destroy/aws/shared.go
If AWS fails to untag a resource, it ends up going into an
infinite loop of querying tag client for resources and
retrying the untag process.
Removing the part that adds the tag client back to the list
and causes the retries.
> Bug 2070744: Fix infinite loop when failing to untag resources

- docs/dev/terraform.md
- terraform/Makefile
- terraform/providers/alicloud/go.mod
- terraform/providers/aws/go.mod
- terraform/providers/azurerm/go.mod
- terraform/providers/azurestack/go.mod
- terraform/providers/google/go.mod
- terraform/providers/ibm/go.mod
- terraform/providers/ignition/go.mod
- terraform/providers/ironic/go.mod
- terraform/providers/libvirt/go.mod
- terraform/providers/local/go.mod
- terraform/providers/nutanix/go.mod
- terraform/providers/openstack/go.mod
- terraform/providers/ovirt/go.mod
- terraform/providers/random/go.mod
- terraform/providers/time/go.mod
- terraform/providers/vsphere/go.mod
- terraform/providers/vsphereprivate/go.mod
- terraform/terraform/go.mod
- terraform/terraform/go.sum
Update terraform and providers to use golang 1.18
> Terraform go 1.18

- data/data/vspherezoning/bootstrap/main.tf
- data/data/vspherezoning/bootstrap/outputs.tf
- data/data/vspherezoning/bootstrap/variables.tf
- data/data/vspherezoning/master/main.tf
- data/data/vspherezoning/master/outputs.tf
- data/data/vspherezoning/master/variables.tf
- data/data/vspherezoning/pre-bootstrap/main.tf
- data/data/vspherezoning/pre-bootstrap/outputs.tf
- data/data/vspherezoning/variables-vspherezoning.tf
- pkg/asset/cluster/cluster.go
- pkg/asset/cluster/tfvars.go
- pkg/asset/cluster/vsphere/vsphere.go
- pkg/destroy/bootstrap/bootstrap.go
- pkg/destroy/vsphere/vsphere.go
- pkg/terraform/stages/platform/stages.go
- pkg/terraform/stages/vsphere/stages.go
- pkg/tfvars/vsphere/vsphere.go
- pkg/types/vsphere/defaults/platform.go
- pkg/types/vsphere/doc.go
- pkg/types/vsphere/metadata.go
This PR adds an additional terraform workflow
and variables to allow for the provisioning
of the RHCOS OVA (template), bootstrap and
control plane nodes into a zonal installation.
> vSphere: Zonal Terraform

- pkg/types/aws/validation/platform.go
Removed error condition that blocks update in https://github.com/openshift/installer/pull/6345/
> OCPBUGS-1234 : [CFE-580] Fixed error condition for user tag validation

- data/data/agent/systemd/units/apply-host-config.service.template
- data/data/agent/systemd/units/assisted-service-db.service
- data/data/agent/systemd/units/assisted-service-pod.service
- data/data/agent/systemd/units/assisted-service.service.template
- data/data/agent/systemd/units/create-cluster-and-infraenv.service.template
Add ipv6 support by using host network in corresponding podman based services
> AGENT: add ipv6 support

- pkg/asset/installconfig/aws/subnet.go
This change allows us to have clusters with public-only subnets without having to introduce a lot of changes in the installer. Such clusters can be used in a NAT-less gateway scenario, therefore decreasing costs in cases where node security is not a concern (e.g, ephemeral clusters in CI).
It's gated through an env var since it's supposed to be only used in CI for the time being, where an appropriate VPC must be created and passed to the installer.
> aws: allow clusters with public only subnets

- docs/user/aws/install.md
Fully air-gapped installation is not possible.
> Bug 2094716: docs: fully air-gapped AWS IPI install

- pkg/asset/agent/image/oc.go
When in completely disconnected environments, we need to get the image pullspec information using the icsp file, otherwise it will attempt to reach out to quay to find out the image for the base rhcos image.
> OCPBUGS-1231: disconnected machine-os-images info

- data/data/agent/systemd/units/assisted-service-pod.service
Longer timeouts, better restarts.
> Agent installer: try to make systemd services more robust

- pkg/asset/agent/manifests/agentclusterinstall.go
- pkg/asset/agent/manifests/agentclusterinstall_test.go
- pkg/asset/agent/manifests/util_test.go
Dual-stack support in the assisted-service requires that both the IPv4 and IPv6 networks have entries in the MachineNetwork. For either IPv4 or IPv6 support an entry is not required but its accepted. Add support for the MachineNetwork to the Generate() for agent-cluster-install.
> AGENT-351: Add MachineNetwork to agent-cluster-install for dual stack

- pkg/types/vsphere/platform.go
cleanup unused types and constants left behind after the platform spec refactor.
> [vsphere] cleanup unused types and constants after platform spec refactor

- docs/user/agent/mce-integration.md
Adds the disconnected steps to the MCE integration documentation.
> AGENT-330: Add disconnected instructions to MCE integration doc

- pkg/asset/installconfig/gcp/dns.go
- pkg/asset/installconfig/gcp/validation.go
- pkg/asset/installconfig/gcp/validation_test.go
- pkg/asset/installconfig/platformprovisioncheck.go
** Skip base public zone validation against base domain when the public managed zone is set to "None"
** Log and skip base domain validation when error indications permissions forbidden.
> CORS 2046: GCP Add base domain validation when DNS zone is specified

- docs/user/openstack/connect_nodes_to_ipv6_network.md
This doc includes limitation and steps to get additional IPv6 Networks to worker nodes and pods.
> Add docs about IPv6 on the additional Networks

- pkg/types/powervs/powervs_regions.go
> Adding "syd05" as a choice for zones in PowerVS

- pkg/destroy/vsphere/vsphere.go
If the folder is not empty and it contains anything other than "virtualmachine" objects, the installer might be stuck in a loop and the only message we get about it is:
level=debug msg="Folder: Expected Folder $folder to be empty"
Let's improve that message by expanding on which objects in the folder are preventing the installer from destroying the cluster.
> OCPBUGS-1881: vsphere/destroy: improve logs when folder is not empty

- pkg/agent/cluster.go
- pkg/agent/waitfor.go
If a cluster moves from "preparing-for-installation" back to "ready" it indicates that a failure has occurred and installation will not continue. Note that in order to check the status the return from the validation check is moved to after the handling of the status errors.
> OCPBUGS-2086: Detect failure in wait-for on transition back to ready

- docs/user/customization.md
Add install config docs for feature sets.
> docs: feature sets

- pkg/asset/agent/image/agentimage.go
- pkg/asset/agent/image/ignition.go
Corresponding dev-scripts change: https://github.com/openshift-metal3/dev-scripts/pull/1464
> AGENT-390: Include CPU Architecture in ISO filename

- pkg/agent/cluster.go
After the merge of these two PRs I noticed that some these if statements were nested incorrectly.
The outer if statements in IsBootstrapComplete should be:
```
// Both API's are not available
if !agentRestAPILive && !clusterKubeAPILive {
...
}
// Kube API is available
if clusterKubeAPILive {
...
}
// Agent Rest API is available
if agentRestAPILive {
...
}
```
I moved the check when both aren't available to the top to exit out early.
Also to reduce the number of times the error "cluster has stopped installing... working to recover installation" is printed I flipped the status `models.ClusterStatusInsufficient` to false in `HasErrored()`. This is the cluster status when validations are failing.. and now we are printing the validations themselves so it isn't required in that case anymore.
I …
> Fix unexpected behavior from merging #6470 and #6500

- data/data/bootstrap/bootstrap-in-place/files/opt/openshift/bootstrap-in-place/bootstrap-in-place-post-reboot.sh
The `bootstrap` configmap it's consumed by external consumers, such as the `openshift-install wait-for`-like commands, to detect the successfull completion of the bootstrap phase.
The task of creating is it's usually carried on by the [progress service](https://github.com/openshift/installer/blob/3d80765f1833f757acc1b1b644ba8661fb26e3be/data/data/bootstrap/files/usr/local/bin/report-progress.sh#L22-L33), but in case of a SNO deployment it won't work due the lack of a control plane when the action is issued.
This patch thus adds a specific extra step for creating the bootstrap cm during the bootstrap in place flow - which is enabled for every SNO deployment.
**Reviewers notes** 
This code can be tested using https://github.com/openshift-metal3/dev-scripts/pull/1472, with the following …
> OCPBUGS-1791: add bootstrap configmap during the SNO reboot

- data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
- pkg/asset/ignition/bootstrap/common.go
- add FeatureSet to bootstrap template data
- pass FeatureSet to cluster config render
> OCPBUGS-3123: Pass FeatureSet to cluster config render

- data/data/alibabacloud/cluster/dns/privatezone.tf
When the publish is 'Internal', need not to create public record
> OCPBUGS-2384: [Alibaba] fix the creation of public record

- data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
cargo culted from https://github.com/openshift/installer/pull/6576, created for https://github.com/openshift/cluster-kube-apiserver-operator/pull/1403
> OCPBUGS-3985: Pass featureset to kas

- data/data/gcp/cluster/dns/base.tf
- data/data/gcp/cluster/dns/variables.tf
- data/data/gcp/cluster/main.tf
- data/data/gcp/variables-gcp.tf
- pkg/asset/cluster/tfvars.go
- pkg/asset/installconfig/gcp/validation.go
- pkg/asset/installconfig/gcp/validation_test.go
- pkg/asset/installconfig/platformprovisioncheck.go
- pkg/asset/manifests/dns.go
- pkg/tfvars/gcp/gcp.go
- pkg/types/gcp/validation/platform.go
- pkg/types/gcp/validation/platform_test.go
- pkg/types/validation/installconfig_test.go
** Should not specify the privatezone for GCP installations.
https://issues.redhat.com/browse/CORS-2409
> GCP: remove private zone manipulation

- pkg/asset/installconfig/vsphere/validation.go
The PR:
https://github.com/openshift/installer/pull/5798
Introduced the ability to install with
the VIPs unset.
This PR adds validation to the vSphere
zonal installation for DNS and LB
existence.
It will query DNS for api and api-int.
If either fail a error will be provided.
It will perform a TCP/6443 port connection
to the `api.ClusterDomain()`. If not
available will emit a warning only.
> [SPLAT-877] vSphere Zonal: validate dns and external load balancer

- .ci-operator.yaml
- images/baremetal/Dockerfile.ci
- images/installer-artifacts/Dockerfile.rhel
- images/installer/Dockerfile.ci
Manual PR for https://github.com/openshift/installer/pull/6449 https://github.com/openshift/installer/pull/6448 https://github.com/openshift/installer/pull/6447 against master (4.13)
> OCPBUGS-4328:  images: updating images to be consistent with ART

- pkg/tfvars/openstack/openstack.go
- pkg/tfvars/openstack/rhcos_image.go
This is expected to be pure refactoring without any functional change.
> openstack: Refactor TFVars generation

- data/data/alibabacloud/bootstrap/main.tf
- data/data/alibabacloud/cluster/main.tf
- pkg/asset/machines/alibabacloud/machines.go
- pkg/destroy/alibabacloud/alibabacloud.go
Add the tag 'ack.aliyun.com'  required by the ACK component
> Alibaba: add the tags of the machine nodes

- pkg/asset/agent/manifests/nmstateconfig.go
- pkg/asset/agent/manifests/nmstateconfig_test.go
- pkg/asset/agent/manifests/util_test.go
The NMStateConfig data in agent-config.yaml was not being validated, it was only checked in the Load() i.e. the data in nmstateconfig.yaml. This can result in invalid configurations being stored in ignition and then the install would fail when these configs were validated by assisted-service.
The change is to do the same checks in Load() and Generate().
> OCPBUGS-3987: Check nmstateconfig content in agent-config.yaml

- pkg/asset/agent/image/agentimage.go
- pkg/asset/agent/image/ignition.go
> Save rendezvous IP in a file 'rendezvousIP' alongside the ISO

- pkg/destroy/powervs/powervs.go
Merge all of the debug output statements into one defer code block.
> Consolidate loadsdk debug statements

- pkg/destroy/aws/elbhelpers.go
There can be situations in which the listeners are not deleted with the ELB. In such cases, the installer will print the following message
level=warning msg=unrecognized elastic load balancing resource type listener arn=arn:aws:elasticloadbalancing:us-west-2:460538899914:listener/net/a9ac9f1b3019c4d1299e7ededc92b42b/a6f0655da877ddd4/45e05ee69d99bab0
and the ELB listeners will be leaked. Let's make sure to delete them instead.
> OCPBUGS-2891: aws: destroy: delete ELB listeners

- docs/user/openstack/README.md
- docs/user/openstack/image-registry-storage-swift.md
Relates to [OCPBUGS-4090](https://issues.redhat.com//browse/OCPBUGS-4090)
> OSASINFRA-3057: openstack: Document Image Registry migration to Swift

- data/data/bootstrap/baremetal/files/usr/local/bin/startironic.sh.template
Allow some extra time for the provisioning interface to come up https://issues.redhat.com/browse/OCPBUGS-5151
> OCPBUGS-5151: baremetal: Extra time for provisioning interface

- pkg/asset/manifests/cloudproviderconfig.go
- pkg/asset/manifests/nutanix/cloudproviderconfig.go
Generate the cloudproviderconfig manifests for integration of nutanix-ccm to OCP
> Generate the cloudproviderconfig manifests for integration of nutanix-ccm to OCP

- pkg/destroy/aws/shared.go
There is an infinite loop if the resource is not untagged during AWS destroy. This needs to be checked for an InvalidParameterException and if it is, we should not retry the same client again.
> Bug 2070744: Fix infinite loop error

- pkg/types/vsphere/defaults/platform.go
- pkg/types/vsphere/validation/platform.go
- pkg/types/vsphere/validation/platform_test.go
Backport of https://github.com/openshift/installer/pull/6409 to 4.12
> [release-4.12] OCPBUGS-5996: vsphere: set default resource pool when missing failure domain topology

- data/data/install.openshift.io_installconfigs.yaml
- pkg/types/validation/installconfig.go
- pkg/types/vsphere/platform.go
Removing tech preview feature gate from multi-zone install-config spec.
> SPLAT-820: multi-zone is no longer tech preview

- pkg/destroy/gcp/disk.go
** The Length of the disks can be less than the 22 char max. In the case that the cluster name is very small and a minimal name for disks is generated an error was thrown, this will fix that error.
** Altered comment for uses to destroying from creating.
> OCPBUGS-6697: destroy/gcp: Use min length for destroying disks

- pkg/asset/machines/master.go
- pkg/asset/machines/worker.go
* Starting with version 4.13 OCP is going to officially support Single
Node clusters on AWS.
* The minimum documented OCP requirement for single-node control plane
nodes is 8-cores and 16GiB of RAM
* The current default instance type chosen for AWS clusters by the
installer is `xlarge` which is 4 cores and 16GiB of RAM
The default instance type the installer currently chooses for Single
Node Openshift clusters doesn't follow our documented minimum
requirements
When the number of replicas of the ControlPlane pool is 1, the installer
will now choose `2xlarge` instead of `xlarge`.
`2xlarge` has 32GiB of RAM, which is twice as much as we need, but it's
the best we can do to meet the minimum single-node requirements, because
AWS doesn't offer a 16GiB RAM instance type with 8 cores.
> CORS-2496: Default `2xlarge` instead of `xlarge` in AWS when the control-plane is single-node

- OWNERS_ALIASES
This is to reflect the current team composition
> Update alias for Metal Platform

- data/data/install.openshift.io_installconfigs.yaml
- pkg/asset/machines/azure/machines.go
- pkg/asset/machines/azure/machinesets.go
- pkg/asset/machines/master.go
- pkg/asset/machines/worker.go
- pkg/explain/printer_test.go
- pkg/types/azure/platform.go
- pkg/types/azure/validation/platform.go
- pkg/types/azure/validation/platform_test.go
> CFE-757 : Fix issues reported by QE

- pkg/types/validation/installconfig.go
Previously we only supported ipv4-primary dual stack clusters due to some limitations in our infrastructure. We are now making the necessary changes to run ipv6-primary dual stack clusters so we no longer need to enforce the ordering on baremetal. Note also that although we are adding support for dual stack to other platforms too, at this time they will not support v6-primary dual stack so I'm limiting this change to baremetal.
> OPNET-199: Allow v6-primary dual stack on baremetal

- hack/openstack/test-manifests.sh
> openstack-manifest: Show assets dir if persisted

- docs/user/openstack/invalid-https-certificates.md
Provide manual instructions to check the HTTPS certificates of the OpenStack endpoints for systems where the required tools for the provided script aren't available.
> OCPBUGS-7954: openstack: Provide manual instructions for invalid certificates

- pkg/asset/machines/master.go
When generating the openshift manifests, it tries to load the dependency control plane asset that creates files in the openshift directory. It then checks to see if the openshift manifest is actually already generated before this by checking the openshift directory for files that are not generated by the machine asset.
The newly created CPMS file was missing from the check, hence the asset loader always thought the asset was generated since there are files that exist other than the machine files and exits but it actually had to be newly generated with 4 files that were crucial to installation.
Adding the CPMS files to the list of machine asset files.
> [release-4.12] OCPBUGS-7481: Fix file check for loading openshift manifests

- data/data/coreos/rhcos.json
> OCPBUGS-10585: rhcos: Update to 413.92.202303190222-0

- data/data/agent/systemd/units/agent-interactive-console.service
- data/data/agent/systemd/units/agent-tui.path
- pkg/asset/agent/image/ignition.go
This patch is to verify the changes initially published in https://github.com/openshift/installer/pull/6977 on the 4.13 branch (specifically the `e2e-agent-*` jobs)
/draft
>  [release-4.13] OCPBUGS-10597: fix agent tui showing up multiple times

- data/data/nutanix/cluster/main.tf
- pkg/terraform/stages/nutanix/stages.go
Fix OCPBUGS-6727: Nutanix Hostname of the VM is not set when using DHCP network config
> OCPBUGS-6727: Nutanix Hostname of the VM is not set when using DHCP network config

- data/data/coreos/rhcos.json
This is the 4.13 version of https://github.com/openshift/installer/pull/7038
> rhcos: Bump to 413.92.202303281804-0

- pkg/asset/agent/manifests/network-scripts.go
Presently, in the PreNetworkConfig script, we are removing the default network manager configuration for a host in every case. This should be altered so that the default configuration is deleted only if custom nmstate configuration has been provided for the host.
> OCPBUGS-7966: Do not remove host default configuration unless network configuration is provided for it

- data/data/install.openshift.io_installconfigs.yaml
- pkg/types/azure/disk.go
Set the subscriptionID in the Azure defaultMachinePlatform.
https://issues.redhat.com/browse/OCPBUGS-8449
> OCPBUGS-8449: pkg/asset/installconfig: set subscriptionID

- pkg/asset/installconfig/platformcredscheck.go
- pkg/asset/installconfig/platformpermscheck.go
- pkg/asset/installconfig/platformprovisioncheck.go
- pkg/asset/installconfig/powervs/client.go
- pkg/asset/installconfig/powervs/mock/powervsclient_generated.go
- pkg/asset/installconfig/powervs/platform.go
- pkg/asset/installconfig/powervs/regions.go
- pkg/asset/installconfig/powervs/session.go
- pkg/asset/installconfig/powervs/validation.go
- pkg/asset/quota/quota.go
- pkg/destroy/powervs/powervs.go
default to ~/.powervs, otherwise prompt for
zone
service instance id
resource group (handle "Default" if a default group exists)
https://issues.redhat.com/browse/MULTIARCH-2517
> MULTIARCH-2517: PowerVS: create install-config improvements

- pkg/asset/installconfig/powervs/client.go
If the user passes in a human readable group id, then the create cluster will fail with the following error:
level=fatal msg=failed to fetch Terraform Variables: failed to fetch dependency of "Terraform Variables": failed to generate asset "Platform Provisioning Check": Failed to list resource instance: A dependent service error occurred, Error: Failed to get a resource group.
> PowerVS: fix human readable group-id

- pkg/asset/machines/master.go
- pkg/asset/machines/worker.go
- pkg/types/azure/validation/disk.go
https://issues.redhat.com/browse/OCPBUGS-8449
> OCPBUGS-8449: Azure: don't set default subscriptionID for disk encryption sets

- pkg/destroy/aws/iamhelpers.go
This is an manual cherry-pick of https://github.com/openshift/installer/pull/6666
> [release-4.12] OCPBUGS-7400: Check for AWS STS installation before trying to get all IAM Roles

- data/data/coreos/fcos.json
Update FCOS to 37.20230401.3.0
> OCPBUGS-7978: FCOS: bump to latest stable version

- data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
reintroduce https://github.com/openshift/installer/pull/7158 since https://github.com/openshift/cluster-config-operator/pull/305 merged
> OCPBUGS-13547: remove special cases for featureset in rendering

- pkg/destroy/aws/ec2helpers.go
The installer fails to destroy VPC endpoint service with active VPC connections to it. It needs to reject all active connections before attempting to destroy the service.
> OCPBUGS-7410: Reject active VPC connections before service destroy

- pkg/destroy/aws/iamhelpers.go
Instead of looking for a specific error code (unreliable), look for "AccessDenied" in the error message
> OCPBUGS-1769: Ignore IAM Roles that the Installer is not authorized to access

- pkg/asset/agent/installconfig.go
- pkg/asset/agent/manifests/nmstateconfig.go
If the number of compute replicas is not configured, a default of 3 will be used. If the number of baremetal hosts configured does not match this, log a warning. This may be a valid configuration if the host configuration is a mix of static and DHCP definitions but it may be indicative of an error if the number if the replicas was not defined and the default is unexpected.
Add a couple messages to help catch config problems with the replicas before installation.
- An info message with the number of replicas being used which is useful if hosts not configured
- An warning message if the number of replicas does not match the number of configured hosts
> OCPBUGS-10342: Check that number of replicas matches hosts

- images/openstack/Dockerfile.ci
This is a manual cherry-pick of e38b029bf526c4f9961d86d87dcf3ca1297e6d75 (https://github.com/openshift/installer/pull/7148)
> OCPBUGS-13104: openstack: Add netcat to the Installer image

- OWNERS
- OWNERS_ALIASES
Merges agent team members into installer team. Add Zane to installer approvers.
/cc @zaneb @rwsu @bfournie @pawanpinjarkar @andfasano
> OWNERS: merge agent/installer

- cmd/openshift-install/testdata/agent/pxe/configurations/sno-arm.txt
- pkg/asset/agent/image/agentpxefiles.go
Decompress kernel for ARM architecture in case of PXE boot.
> AGENT-627: Decompress kernel on ARM

- pkg/asset/installconfig/powervs/session.go
Adding support for shared and capped processors alongside just shared processor.
> PowerVS Add support for Capped processors

- pkg/asset/tls/root.go
Reflect in this my current understanding of reality.
See also https://github.com/openshift/api/pull/1484
> tls/root: Document this more and change friendly name

- hack/go-integration-test.sh
Force the integration tests to run in serial until the function extractFileFromImage in pkg/asset/agent/image/oc.go has been fixed.
> AGENT-678: Fix concurrency issue in agent integration tests

- data/data/agent/files/usr/local/bin/agent-gather
This patch adds the agent-tui log to the agent-gather artifact
> OCPBUGS-15825: Fix agent gather tui logs

- cmd/openshift-install/create.go
This reverts commit 3bc9b245583bdb19b0415b2d5899e1a1a5b8d629, reversing changes made to a4604b060b2abb913926d0485760d069a95d157f.
This change is sometimes failing with
```
E0712 09:14:15.239148    4409 runtime.go:79] Observed a panic: "send on closed channel" (send on closed channel)
```
Let's revert while we investigate.
> Revert "Merge pull request #7289 from r4f4/padillon-settle-ops"

- pkg/destroy/powervs/powervs.go
Since it is easy to not create a new authenticator structure and validate it before every new use, we will create a function which implements this.
> PowerVS: Create new newAuthenticator function

- data/data/gcp/cluster/dns/base.tf
- data/data/gcp/cluster/dns/variables.tf
- data/data/gcp/cluster/iam/main.tf
- data/data/gcp/cluster/main.tf
- data/data/install.openshift.io_installconfigs.yaml
- pkg/asset/installconfig/gcp/client.go
- pkg/asset/installconfig/gcp/mock/gcpclient_generated.go
- pkg/asset/installconfig/gcp/validation.go
- pkg/asset/installconfig/gcp/validation_test.go
- pkg/asset/machines/gcp/machines.go
- pkg/tfvars/gcp/gcp.go
- pkg/types/gcp/machinepools.go
- pkg/types/gcp/validation/machinepool.go
- pkg/types/validation/machinepools.go
- pkg/types/validation/machinepools_test.go
> OCPBUGS-15421: Allow different service account for xpn installs in gcp

- pkg/asset/installconfig/gcp/client.go
- pkg/asset/installconfig/gcp/mock/gcpclient_generated.go
- pkg/asset/installconfig/gcp/validation.go
- pkg/asset/installconfig/gcp/validation_test.go
- pkg/asset/machines/gcp/zones.go
- pkg/asset/machines/master.go
- pkg/asset/machines/worker.go
This reverts commit 76a40181107c3d1ee24a95a29f84faee2c35bf73, reversing changes made to 0b68802de63f046d010e9697df7788bf6546b692.
Seems to be causing https://issues.redhat.com/browse/OCPBUGS-16515
> Revert "Merge pull request #7096 from r4f4/gcp-instance-zones"

- pkg/types/aws/validation/machinepool.go
- pkg/types/aws/validation/machinepool_test.go
According to https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html, the default Security groups number per network interface is 5 and could be 16 at most, so we better have some pre-check on the number of provided custom security groups.
When it's more than 15 (since the maximum is 16, but installer will also create one (`${var.cluster_id}-master-sg/${var.cluster_id}-worker-sg`), installer should quit and warn user about this.
This PR also introduces a unit test for the validation. For now we only test that the validation fails when the number of
security groups exceeds the maximum. We should add more tests in the future when the AWS SDK client calls the validation uses are mockable.
> OCPBUGS-16207: ic: aws: validate max security groups 

- data/data/bootstrap/bootstrap-in-place/files/usr/local/bin/bootstrap-in-place.sh
Add filter by etcd container name regular expression pattern before the grep
https://issues.redhat.com/browse/OCPBUGS-15852
> OCPBUGS-15852: Single node cannot be installed if etcd appears in the hostname

- data/data/azure/vnet/public-lb.tf
When one creates an IPI Azure cluster with an `internal` publishing method, it creates a standard load balancer with an empty definition. This load balancer doesn't serve a purpose since the configuration is completely empty. Because it doesn't have a public IP address and backend pools it's not providing any outbound connectivity, and there are no frontend IP configurations for ingress connectivity to the cluster.
> OCPBUGS-16915: [release-4.11] azure: skip LB creation when not needed

- docs/user/openstack/install_upi.md
- images/openstack/Dockerfile.ci
- upi/openstack/bootstrap.yaml
- upi/openstack/compute-nodes.yaml
- upi/openstack/control-plane.yaml
- upi/openstack/down-bootstrap.yaml
- upi/openstack/down-compute-nodes.yaml
- upi/openstack/down-containers.yaml
- upi/openstack/down-control-plane.yaml
- upi/openstack/down-load-balancers.yaml
- upi/openstack/down-network.yaml
- upi/openstack/down-security-groups.yaml
- upi/openstack/network.yaml
- upi/openstack/security-groups.yaml
Update UPI doc and add missing modules namespaces for Ansible 2.10.
> OCPBUGS-16959: openstack/upi: add missing modules namespaces + doc

- pkg/asset/installconfig/gcp/client.go
- pkg/asset/installconfig/gcp/mock/gcpclient_generated.go
- pkg/asset/installconfig/gcp/validation.go
- pkg/asset/installconfig/gcp/validation_test.go
This is a manual cherry-pick of https://github.com/openshift/installer/pull/7272 including https://github.com/openshift/installer/pull/7290.
> [release-4.13] OCPBUGS-15290: GCP: ic: improve project validation

- data/data/coreos/fcos.json
Use latest stable FCOS for OKD builds
> data/data/coreos: bump FCOS to F38 stable

- docs/user/openstack/install_upi.md
- images/openstack/Dockerfile.ci
- upi/openstack/bootstrap.yaml
- upi/openstack/compute-nodes.yaml
- upi/openstack/control-plane.yaml
- upi/openstack/down-bootstrap.yaml
- upi/openstack/down-compute-nodes.yaml
- upi/openstack/down-containers.yaml
- upi/openstack/down-control-plane.yaml
- upi/openstack/down-load-balancers.yaml
- upi/openstack/down-network.yaml
- upi/openstack/down-security-groups.yaml
- upi/openstack/inventory.yaml
- upi/openstack/network.yaml
- upi/openstack/security-groups.yaml
- openstack/upi: update doc for CCPMSO
- openstack/upi: add missing modules namespaces
- images/openstack/Dockerfile.ci: remove unused collections
- openstack/upi: doc updates
> OCPBUGS-17397: backport openstack UPI for ansible 2.10

- cmd/openshift-install/testdata/agent/agentconfigtemplate/agent-config-template.txt
- pkg/asset/agent/agentconfig/agent_config.go
Log message and add integration test for `openshift-install agent create agent-config-template` command
Signed-Off by:
@marcbrown2024
@pawanpinjarkar
> OCPBUGS-13408: Log message and add integration test

- data/data/install.openshift.io_installconfigs.yaml
- pkg/explain/printer_test.go
- pkg/types/azure/platform.go
- pkg/types/azure/validation/platform.go
- pkg/types/azure/validation/platform_test.go
- pkg/types/validation/installconfig.go
The feature is not fully implemented thus not supported yet. Also validate that it cannot be selected for AzureStack.
> OCPBUGS-17869: azure: put NAT gateway behind TechPreviewNoUpgrade

- pkg/destroy/azure/azure.go
If the Service Principal destroying an Azure cluster lacks the permissions to list DNS records, the Installer will complete the destroy but leave public DNS records behind.
Unfortunately the Azure SDK doesn't return any errors when permissions are missing neither does it offer a way for us to check if the required permissions are present. As an in-between solution, let's log a warning when we can't find any DNS records so users know to check for any records being leaked.
> OCPBUGS-7690: azure: destroy: dns records leak if permissions missing

- pkg/asset/machines/azure/machines.go
When there's only a single zone, we do not need to use the `failureDomains` feature of CPMS. In particular, this is causing issue for the westus region where it has no zones, but the CPMS is being created with a single failure domain `zone: ""`. We have a few changes going in that should help to resolve this but we shouldn't really be using the failure domains at all for single zones clusters.
> OCPBUGS-18113: Do not set FailureDomains on CPMS when in a single zone Azure region

- pkg/asset/machines/master.go
- pkg/asset/machines/worker.go
- pkg/types/azure/validation/disk.go
https://issues.redhat.com/browse/OCPBUGS-8449
https://issues.redhat.com/browse/OCPBUGS-11093
(cherry picked from commit b77d2e3b7ed22361fca3becf930dcbd97e5c189c)
> OCPBUGS-11093: Azure: don't set default subscriptionID for disk encryption sets

- go.mod
- go.sum
- vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
- vendor/github.com/gophercloud/gophercloud/README.md
- vendor/github.com/gophercloud/gophercloud/errors.go
- vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/snapshots/requests.go
- vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/snapshots/results.go
- vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/snapshots/urls.go
- vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumetypes/doc.go
- vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumetypes/requests.go
- vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumetypes/results.go
- vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumetypes/urls.go
- vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/requests.go
- vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/requests.go
- vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/snapshots/requests.go
- vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/snapshots/results.go
- vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/snapshots/urls.go
- vendor/github.com/gophercloud/gophercloud/provider_client.go
- vendor/github.com/gophercloud/utils/openstack/clientconfig/requests.go
- vendor/github.com/hashicorp/go-uuid/.travis.yml
- vendor/github.com/hashicorp/go-uuid/LICENSE
- vendor/github.com/hashicorp/go-uuid/README.md
- vendor/github.com/hashicorp/go-uuid/uuid.go
- vendor/modules.txt
Among other changes: use faster object-storage bulk-deletion.
> OSASINFRA-3236: deps: Bump gophercloud to v1.6.0

- pkg/destroy/aws/iamhelpers.go
**The getUser role validation can be skipped during manual mode installations. During the uninstall process, fail gracefully when the role is not found.
> OCPBUGS-17724: Graceful fail for AWS getUser on destroy

- LICENSE
Updates license to include year and company.
> LICENSE: Update

- pkg/asset/agent/agentconfig/agent_config.go
- pkg/asset/agent/agentconfig/agent_config_test.go
Fix spelling and make code and error messages clearer.
> Tweaks to validateRendezvousIPNotWorker

- pkg/asset/agent/manifests/network-scripts.go
Include the assisted-service change https://github.com/openshift/assisted-service/pull/5389 to ensure that vlan names don't exceed 15 chars into the agent-based installer.
> OCPBUGS-18552: Truncate vlan names defined in nmstate if > 15 chars

- pkg/asset/agent/image/agentartifacts.go
Network configuration of any kind is rarely needed in the cloud, anyway. So on OCI specifically we mostly are slowing boot down by 20s for no real reason. Disable agent-tui for the external OCI platform by simply not adding the binary to the ISO image.
> OCPBUGS-19093: skip agent-tui on OCI

- pkg/asset/installconfig/vsphere/validation.go
In some scenario vCenter does not have defined
the `HostSystem.Config.Product.Version`
This causes a segfault in the installer.
Adding a check to potentially resolve.
> OCPBUGS-20350: vSphere,segfault on version check

- pkg/asset/agent/image/baseiso.go
- pkg/asset/agent/image/oc.go
This patch verifies that the extracted `machine-os-images` coreos image version is matching the one stored in the currently embedded medata, when generating a new image through the `agent create image` command.
This sanity check avoids that out-of-sync scenarios may slip through the cracks silently.
> OCPBUGS-10906: check extracted base iso coreos version is in sync

- data/data/install.openshift.io_installconfigs.yaml
- go.mod
- go.sum
- vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
- vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
- vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
- vendor/github.com/openshift/api/config/v1/0000_10_openshift-controller-manager-operator_01_build.crd.yaml
- vendor/github.com/openshift/api/config/v1/feature_gates.go
- vendor/github.com/openshift/api/config/v1/stable.build.testsuite.yaml
- vendor/github.com/openshift/api/config/v1/types_cluster_version.go
- vendor/github.com/openshift/api/config/v1/types_feature.go
- vendor/github.com/openshift/api/config/v1/types_infrastructure.go
- vendor/modules.txt
Bump openshift/api version with new capability set
> OCPVE-740: bump openshift/api

- .golangci.yaml
- hack/go-lint.sh
Related to https://github.com/openshift/release/pull/44928
> hack/go-lint: update golanci-lint to v1.53.1

- pkg/destroy/aws/aws.go
** Partially overrides https://github.com/openshift/installer/pull/7510 to ensure that instance profiles that are tagged as shared do not get deleted. This fix will be combined with https://github.com/openshift/installer/pull/7510 to ensure that the solution can be backported.
> OCPBUGS-18986: Skip the deletion of instance profiles marked shared

- pkg/asset/agent/image/agentartifacts.go
- pkg/asset/agent/image/kargs.go
- pkg/asset/agent/manifests/agent.go
- pkg/asset/agent/manifests/agentclusterinstall.go
Manual cherrypick of https://github.com/openshift/installer/pull/7512
> OCPBUGS-19922: Release 4.14 skip agent tui on external oci platform

- pkg/destroy/azure/azure.go
Instead of using `wait.UntilWithContext` and cancelling than recreating the main context, let's use `wait.PollUntilContextCancel` which takes a callback function returning true/false to signify whether the callback is done.
> no-jira: destroy/azure: avoid cancelling main context

- data/data/manifests/bootkube/machine-config-server-tls-secret.yaml.template
- pkg/asset/manifests/additionaltrustbundleconfig.go
- vendor/github.com/openshift/api/annotations/annotations.go
- vendor/modules.txt
Reroll of https://github.com/openshift/installer/pull/7742 with proper api bump
> OCPBUGS-24026: Add owner for user provided client CA bundle

- pkg/destroy/azure/azure.go
We are using most of the fields from the Session object, so instead of duplicating them, let's just store the session itself.
> no-jira:  destroy: azure: store session in the destroy object

- cmd/openshift-install/create.go
Currently, the PostRun command does a number of operations and calls either logrus.Fatal or logrus.Exit which force-exit the program with an error. With these changes we retain the exit codes and error messages while ensuring that cancellation and cleanup functions are always called.
/assign @patrickdillon
> CORS-2852: cmd/create: ensure proper cleanup on exit

- pkg/asset/installconfig/aws/permissions.go
- pkg/asset/installconfig/platformpermscheck.go
Manual cherry-pick of https://github.com/openshift/installer/pull/7659
> [release-4.12] OCPBUGS-22116: Add KMS encryption keys if provided

- pkg/asset/agent/installconfig.go
Add a warning if FeatureSet is set to a value other than Default ("").
> OCPBUGS-19054: Warn that FeatureSet is not supported

- cmd/openshift-install/create.go
- pkg/asset/cluster/cluster.go
> CORS-2852: cmd/create: allow clean shutdown of resources

- pkg/types/validation/installconfig.go
- pkg/types/validation/installconfig_test.go
Manual backport of https://github.com/openshift/installer/pull/7884 and https://github.com/openshift/installer/pull/7875
> [release-4.15]OCPBUGS-26495: Add cloud credential capability validation

- pkg/types/validation/installconfig.go
- pkg/types/validation/installconfig_test.go
Wrong capability name in error message
> OCPBUGS-24956: Fix typo in CloudCredential validation

- data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
requires https://github.com/openshift/api/pull/1734
> OCPBUGS-27366: set the --cluster-profile flag for openshift/api rendering

- pkg/asset/machines/vsphere/machines.go
- pkg/asset/machines/vsphere/machines_test.go
- pkg/types/vsphere/validation/machinepool.go
- pkg/types/vsphere/validation/machinepool_test.go
- pkg/types/vsphere/validation/platform.go
- pkg/types/vsphere/validation/platform_test.go
Added check to prevent duplicate failure domains in CPMS.
> OCPBUGS-25453: duplicate failure domains in CMPS

- data/data/manifests/openshift/90-okd-sca-pull-disable.yaml.template
- data/data/manifests/openshift/cloud-creds-secret.yaml.template
- data/data/manifests/openshift/kubeadmin-password-secret.yaml.template
- data/data/manifests/openshift/role-cloud-creds-secret-reader.yaml.template
- docs/dev/cluster-api.md
- pkg/asset/machines/clusterapi.go
- pkg/asset/manifests/clusterapi/cluster.go
- pkg/clusterapi/system.go
A collection of small changes we made while working on the CAPI implementation, that could be extracted without conflicts with the current main branch.
> NO-JIRA: Minor fixes

- pkg/asset/manifests/azure/cloudproviderconfig.go
- pkg/asset/manifests/azure/cloudproviderconfig_test.go
- pkg/asset/manifests/azure/types.go
> OCPBUGS-24521: set vmType in azure cloud config [release-4.14]

- pkg/types/powervs/powervs_regions.go
Add the dal12 region to the PowerVS installer.
> OCPBUGS-28643: PowerVS: Add dal12 region

- pkg/asset/installconfig/aws/availabilityzones.go
Allow all edge zones be discovered before invalidating the configuration.
This bug caused a regression for Local Zones feature and was introduced when Wavelength zone has been added in 4.15.
Additionally, I am creating new e2e to cover manifest situations across all regions which support Local Zones and/or Wavelength Zones: https://github.com/openshift/release/pull/47996
> OCPBUGS-27737: aws-edge-zones preventing err before discovering

- pkg/clusterapi/system.go
** Add the GCP controller to the list of controllers.
> CORS-3208: Create the GCP infrastructure controller

- pkg/asset/machines/clusterapi.go
- pkg/asset/machines/gcp/gcpmachines.go
- pkg/asset/machines/gcp/gcpmachines_test.go
- pkg/types/gcp/platform.go
Generate the GCP master and bootstrap machine manifests for CAPI.
> CORS-3207: Generate GCP machine manifests for CAPI

- data/data/install.openshift.io_installconfigs.yaml
- go.mod
- go.sum
- pkg/asset/machines/vsphere/machines.go
- pkg/types/vsphere/platform.go
- pkg/types/vsphere/validation/platform.go
- pkg/types/vsphere/validation/platform_test.go
- vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd-CustomNoUpgrade.yaml
- vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd-TechPreviewNoUpgrade.yaml
- vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
- vendor/github.com/openshift/api/config/v1/custom.authentication.testsuite.yaml
- vendor/github.com/openshift/api/config/v1/stable.authentication.testsuite.yaml
- vendor/github.com/openshift/api/config/v1/techpreview.authentication.testsuite.yaml
- vendor/github.com/openshift/api/config/v1/types_authentication.go
- vendor/github.com/openshift/api/config/v1alpha1/register.go
- vendor/github.com/openshift/api/machine/v1beta1/types_vsphereprovider.go
- vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
- vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
- vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01-CustomNoUpgrade.crd.yaml
- vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01-Default.crd.yaml
- vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01-TechPreviewNoUpgrade.crd.yaml
- vendor/github.com/openshift/api/operator/v1/stable.network.testsuite.yaml
- vendor/github.com/openshift/api/operator/v1/types_network.go
- vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
- vendor/modules.txt
> SPLAT-1387: enable additional tags to be associated with vsphere machines

- pkg/asset/cluster/tfvars/tfvars.go
** During the GCP installation with custom dns configuration enabled, the private and public zones should not be validated (skip them), so that there are not errors when they cannot be found.
> OCPBUGS-29068: GCP: Skip validation of public and private zones for terraform vars

- pkg/asset/cluster/cluster.go
- pkg/infrastructure/clusterapi/clusterapi.go
- pkg/infrastructure/clusterapi/types.go
- pkg/infrastructure/gcp/clusterapi/clusterapi.go
- pkg/infrastructure/platform/platform.go
- pkg/infrastructure/platform/platform_altinfra.go
** Added the base functions for the CAPG Installation 
** Allow the provider to be selected in ProviderForPlatform, when the feature gate exists 
** Updated the cluster to create two assets that would cause issues during install when they can not be retrieved
> CORS-3220: Initiate CAPG installation

- pkg/asset/installconfig/azure/client.go
If the API call to list SKUs times out, we don't get a context error (e.g., "context deadline exceeded") from Azure, just an empty response. The problem with that is that we return the following errors to the user:
```
ERROR failed to fetch Master Machines: failed to load asset "Install Config": failed to create install config: [controlPlane.platform.azure.type: Invalid value: "Standard_D8s_v3": not found in region eastus, controlPlane.platform.azure.type: Invalid value: "Standard_D8s_v3": unable to determine HyperVGeneration version, compute[0].platform.azure.type: Invalid value: "Standard_D4s_v3": not found in region eastus]
```
which confuses them when they verify that information with the az client
```
$ az vm list-sizes --location  "eastus" | grep -i Standard_D8s_v3
"name": …
```
> OCPBUGS-29469: fix Azure API SKU calls timing out

- docs/user/vsphere/privileges.md
This change updates the documentation to note the required `StorageProfile.Update` permission.
No other code changes are made.
> no-jira: Missing permission from vsphere docs

- pkg/asset/installconfig/azure/client.go
I erroneously assumed that Azure was not returning context errors but that was not actually the case. It was happening as a result of the way we structured the API call:
```
for page, err := client.List(ctx); page.NotDone(); err =
page.NextWithContext(ctx) {
if err != nil {
return nil, fmt.Errorf("failed to list SKUs: %w", err)
}
}
```
If the `client.List` call fails (e.g, context deadline, auth error), `page.NotDone()` will return `false` and we'll never enter the `for` loop to check for `err`. Instead, we should make the `List` call and check for error *before* entering the loop.
> OCPBUGS-29469: fix Azure API SKU calls timing out - part 2

- pkg/asset/machines/aws/awsmachines.go
Returning an error for each tag means a user would have to run the Installer multiple times to find out all the clobbered tags. Let's include all the conflicts at once in the error message.
Also changed from the deprecated set syntax to the new generics style.
> no-jira: capi: aws: report all conflicting user tags at once

- pkg/infrastructure/clusterapi/clusterapi.go
The tear down of local capi controller is happening
right after triggering the deletion of the
bootstrap machine, leaving almost no time
for the machine deletion event to be handled
resulting in a leftover bootstrap machine.
This commit fixes the issue by checking up to
2 minutes if the bootstrap machine was deleted
prior to destroy the local control plane.
> OSASINFRA-3362: Fix CAPI bootstrap deletion

- pkg/asset/installconfig/azure/client.go
If the API call to list SKUs times out, we don't get a context error (e.g., "context deadline exceeded") from Azure as a result of the way we structured the API call:
```
for page, err := client.List(ctx); page.NotDone(); err =
page.NextWithContext(ctx) {
if err != nil {
return nil, fmt.Errorf("failed to list SKUs: %w", err)
}
}
```
If the `client.List` call fails (e.g, context deadline, auth error), `page.NotDone()` will return `false` and we'll never enter the `for` loop to check for `err`. Instead, we should make the `List` call and check for error *before* entering the loop.
The problem with that is that we return the following errors to the user:
```
ERROR failed to fetch Master Machines: failed to load asset "Install Config": failed to create install config: …
```
> [release-4.15] OCPBUGS-29964: fix Azure API SKU calls timing out

- data/data/powervs/cluster/iaas/iaas.tf
- data/data/powervs/cluster/iaas/outputs.tf
- data/data/powervs/variables-powervs.tf
This is a manual cherry-pick of #8145 and #8158
> [release-4.15] OCPBUGS-30854: Power VS: Fix wait_for_workspace

- pkg/infrastructure/gcp/clusterapi/iam.go
When using the CAPG provider, the ServiceAccounts created for master and worker nodes did not have the role bindings set because the policy was not updated.
> OCPBUGS-31209: CAPG - Fix setting ServiceAccount role bindings for GCP

- cluster-api/providers/ibmcloud/go.mod
- cluster-api/providers/ibmcloud/go.sum
- cluster-api/providers/ibmcloud/vendor/github.com/IBM/platform-services-go-sdk/common/version.go
- cluster-api/providers/ibmcloud/vendor/github.com/IBM/vpc-go-sdk/common/version.go
- cluster-api/providers/ibmcloud/vendor/modules.txt
- cluster-api/providers/ibmcloud/vendor/sigs.k8s.io/cluster-api-provider-ibmcloud/api/v1beta2/ibmpowervscluster_webhook.go
- cluster-api/providers/ibmcloud/vendor/sigs.k8s.io/cluster-api-provider-ibmcloud/api/v1beta2/types.go
- cluster-api/providers/ibmcloud/vendor/sigs.k8s.io/cluster-api-provider-ibmcloud/cloud/scope/powervs_cluster.go
- cluster-api/providers/ibmcloud/vendor/sigs.k8s.io/cluster-api-provider-ibmcloud/cloud/scope/powervs_image.go
- cluster-api/providers/ibmcloud/vendor/sigs.k8s.io/cluster-api-provider-ibmcloud/cloud/scope/powervs_machine.go
- cluster-api/providers/ibmcloud/vendor/sigs.k8s.io/cluster-api-provider-ibmcloud/controllers/ibmpowervscluster_controller.go
- data/data/cluster-api/ibmcloud-infrastructure-components.yaml
- go.mod
- go.sum
- pkg/asset/installconfig/powervs/client.go
- pkg/asset/installconfig/powervs/mock/powervsclient_generated.go
- pkg/asset/machines/powervs/powervsmachines.go
- pkg/asset/manifests/powervs/cluster.go
- pkg/infrastructure/powervs/clusterapi/powervs.go
- vendor/github.com/IBM/platform-services-go-sdk/common/version.go
- vendor/github.com/IBM/platform-services-go-sdk/iamidentityv1/iam_identity_v1.go
- vendor/github.com/IBM/vpc-go-sdk/common/version.go
- vendor/modules.txt
- vendor/sigs.k8s.io/cluster-api-provider-ibmcloud/api/v1beta2/ibmpowervscluster_webhook.go
- vendor/sigs.k8s.io/cluster-api-provider-ibmcloud/api/v1beta2/types.go
We should be passing in the ServiceInstance structure which handles
both pre-existing and CAPI created versions.  Also we did not properly
get the service instance GUID.
> no-jira: PowerVS: Fix CAPI created service instance case

- pkg/asset/agent/image/agentimage.go
This patch is a manual cherry-pick of commits 6748cdd1780de2987b21a06eeef418b7ddedc92f (OCPBUGS-14257) and d3ffa4f6e9c6135240fdb73b645f1cb55dfae2d0 (OCPBUGS-28827)
See #7896 and #7972
> [release-4.15] OCPBUGS-30922: coreos-installer iso kargs show broken on Agent ISO

- pkg/infrastructure/powervs/clusterapi/powervs.go
1) We need to set the region in the client library before making calls like AddSecurityGroupRule.
2) Also cleaned up the code which decided which set of ports need to be added in case they already had been added.
> no-jira: PowerVS: Set VPC service region

- pkg/infrastructure/powervs/clusterapi/powervs.go
Wait for the bootstrap node and master nodes to have IP addresses before continuing.
> no-jira:PowerVS: Wait for IPs

- cmd/openshift-install/testdata/agent/image/validations/compact_invalid_controlPlane_replicas.txt
- pkg/asset/agent/installconfig.go
- pkg/asset/agent/installconfig_test.go
This is a manual cherry-pick of https://github.com/openshift/installer/pull/8082
/assign pawanpinjarkar
> [release-4.14] OCPBUGS-31885: Validate control plane replicas

- pkg/clusterapi/system.go
The same way we save installer log output to
`$workdir/.openshift_install.log`, this change proposes saving the CAPI output to `$workdir/.openshift_cluster_api.log` besides stdout/stderr.
> CORS-3436: capi: save log output to file

- cmd/openshift-install/gather.go
When the installer gathers a log bundle after failure (either automatically or with gather bootstrap), the installer fails to return serial console logs if an SSH connection to the bootstrap node is refused.
Instead let's always save the console serial logs if they were collected.
> OCPBUGS-30774: always save serial logs if they were gathered 

- cmd/openshift-install/gather.go
Use instead `fmt.Errorf` and `errors` from the stdlib.
> no-jira: gather: replace deprecated errors package

- pkg/asset/installconfig/vsphere/metadata.go
- pkg/asset/machines/clusterapi.go
The assisted installer has no connection to vCenter until day 2. Make sure that assets generation functions for vSphere if there is no connection to vCenter.
> SPLAT-1585: capv - allow no auth to vcenter

- .golangci.yaml
- hack/go-lint.sh
- pkg/asset/machines/clusterapi.go
- pkg/asset/manifests/aws/zones_test.go
- pkg/asset/manifests/clusterapi/cluster.go
- pkg/infrastructure/aws/sdk/provision_test.go
- pkg/types/ibmcloud/platform.go
Also fix the new linting errors found.
> no-jira: bump golangci lint to 1.54.2

- pkg/clusterapi/system.go
The service endpoints need to be passed to the CAPA controller via the `--service-endpoints` argument.
> CORS-3470: capi/aws: add custom endpoint support.

- upi/vsphere/powercli/upi-destroy.ps1
- upi/vsphere/powercli/upi-functions.ps1
- upi/vsphere/powercli/upi.ps1
- upi/vsphere/variables.ps1.example
[SPLAT-1599](https://issues.redhat.com//browse/SPLAT-1599)
- Added new function to set the secure boot flags
- Added ability to set StoragePolicy
> SPLAT-1599: Added support for secure boot and storage policies to UPI pwsh.

- pkg/asset/installconfig/powervs/metadata.go
- pkg/infrastructure/powervs/clusterapi/powervs.go
`InfraReady` recently triggered the gocyclo linter. This patch refactors it.
> no-jira: Power VS: Refactor `InfraReady` to use metadata client

- upi/vsphere/powercli/upi-functions.ps1
[SPLAT-1599](https://issues.redhat.com//browse/SPLAT-1599)
- Fixed New-OpenShiftVM to convert inbound StoragePolicy parameter from Id to SpbmStoragePolicy for New-VM call.
> SPLAT-1599: Convert storage policy id to SpbmStoragePolicy.

- pkg/infrastructure/baremetal/bootstrap.go
The libvirt code that creates the bootstrap VM was mistakenly ported from openshift/terraform-provider-libvirt while the installer imports dmacvicar/terraform-provider-libvirt at v0.6.12.
This has caused at least two bugs:
- selinux labeling issues
- booting problems on aarch64
This change corrects both of those.
> OCPBUGS-33189: OCPBUGS-33006: baremetal: correct libvirt defaults

- data/data/aws/variables-aws.tf
- data/data/azure/variables-azure.tf
- data/data/gcp/variables-gcp.tf
** Removed unused teraform variables in aws terraform variables file.
** Removed unsued variables in gcp terraform variables file.
** Removed unsued variables in azure terraform variables file.
> no-jira: Removing unused terraform variables

- data/data/bootstrap/baremetal/files/etc/containers/systemd/metal3-baremetal-operator.container
- data/data/bootstrap/baremetal/files/usr/local/bin/master-bmh-update.sh
- data/data/manifests/openshift/baremetal-provisioning-config.yaml.template
This requires:
* ~https://github.com/openshift/baremetal-operator/pull/353~
* https://github.com/openshift/cluster-baremetal-operator/pull/416
Opening this to try it out in CI
We also revert the provisioning CR pause.
> OCPBUGS-33493: Enable leader election for baremetal operator

- pkg/asset/manifests/powervs/cluster.go
We are seeing:
```
dhcp server failed to create private network: unable to retrieve active status for new PER connection information after create private network
```
This error might be alleviated by not conflicting the CIDR when we create the DHCP network.  One way to mitigate this is to use a random subnet address.
> OCPBUGS-33912: PowerVS: Use random subnet

- pkg/infrastructure/aws/clusterapi/iam.go
We should only add a role policy to roles we create ourselves, not BYO roles from users. This is in line with what terraform did.
> OCPBUGS-33926: capi/aws: don't modify BYO role's policy

- pkg/infrastructure/nutanix/clusterapi/clusterapi.go
OCPBUGS-33789
[Nutanix] installer intermittent failed to upload bootstrap image data to prism-central when CAPI enabled
My investigation shows this intermittent image uploading issue is at the prism-api server side with some older version of the prism-central server. Since the issue is intermittent, we can workaround it by retrying a number of times if uploading image fails.
> OCPBUGS-33789: [Nutanix] installer intermittent failed at uploading the bootstrap image to PC when CAPI enabled

- pkg/asset/installconfig/powervs/client.go
It is possible that the load balancer is currently busy. So wrap it in a PollUntilContextCancel loop.
> OCPBUGS-34869: PowerVS: fix AddIPToLoadBalancerPool

- pkg/agent/cluster.go
- pkg/asset/agent/image/ignition_test.go
- pkg/asset/manifests/aws/zones_test.go
The Linter is upgraded in https://github.com/openshift/release/pull/52723. The linter caught 3 issues that are addressed here (including name change, potential secret exposed, and unnecessary newline).
> no-jira: Minor updates to fix linting issues.

- pkg/destroy/powervs/dhcp.go
Add a test to see if the DHCP backing VM is in ERROR state.  And, if so, delete it.
> OCPBUGS-35039: PowerVS: Destroy DHCP in ERROR state

- cmd/openshift-install/features.go
- cmd/openshift-install/main.go
- data/data/aws/bootstrap/main.tf
- data/data/aws/cluster/main.tf
- data/data/aws/cluster/master/main.tf
- data/data/aws/cluster/master/variables.tf
- data/data/aws/variables-aws.tf
- pkg/tfvars/aws/aws.go
Manual cherry-pick of https://github.com/openshift/installer/pull/8526
> OCPBUGS-35032: [release-4.15] aws: terraform: add spot instance support for masters

- pkg/infrastructure/openstack/postprovision/floatingips.go
Before this patch, the bootstrap FIP was attached to the first available port attached to the bootstrap server. As a consequence, the Installer sometimes tried to attach the FIP to a port that was created on an additional network.
With this patch, the bootstrap FIP is only attached to the bootstrap port that exists on the cluster network.
> OCPBUGS-34005: openstack: Attach a bootstrap FIP to the cluster network port

- pkg/infrastructure/clusterapi/clusterapi.go
When performing checks to see if machines/infrastructure are ready or bootstrap destroy has completed, we should poll instead of doing an exponential backoff. With the exponential backoff, the intervals between checks become too great. Our use case is better suited for checking at a constant interval.
During local testing, I have seen that with the AWS SSH bootstrap destroy we are waiting quite a while (a minute or two) before rechecking.
This seems it may also be causing issues when waiting for PowerVS network infrastructure to be ready.
> OCPBUGS-35315: capi: use polling instead of exponential backoff

- OWNERS_ALIASES
> NO-JIRA: Remove dulek from openstack-{approvers,reviewers}

- cmd/openshift-install/destroy.go
- pkg/clusterapi/localcontrolplane.go
- pkg/clusterapi/system.go
- pkg/infrastructure/aws/clusterapi/aws.go
- pkg/infrastructure/clusterapi/clusterapi.go
Manual cherry-pick of #8424
/jira cherry-pick OCPBUGS-33745
> OCPBUGS-35460: save etcd data to its own directory

- pkg/asset/installconfig/aws/route53.go
CallerReference needs to be a unique string. We include the infra id, which is unique, in case that is helpful for human debugging. A random string of an arbitrary length is appended in case the infra id is reused which is generally not supposed to happen but does in some edge cases.
> OCPBUGS-35511: capi aws: append random string in caller ref

- pkg/infrastructure/aws/clusterapi/aws.go
It's possible that the cluster object is changed in between we request the object from the client and we try to update it. When that happens, instead of failing we should retry the update.
This change moves the retry logic from the checking that the rule was removed to encompass the whole operation, including retrieving the cluster object. This logic resembles more closely the reconcile loop logic used internally by CAPA.
This should fix the following bootstrap destroy failure:
```
level=fatal msg=error destroying bootstrap resources failed during the destroy bootstrap hook: failed to remove bootstrap SSH rule: failed to update AWSCluster during bootstrap destroy: Operation cannot be fulfilled on awsclusters.infrastructure.cluster.x-k8s.io "ci-op-nk1s6685-77004-4gb4d": the object has been …
```
> OCPBUGS-35530: capi/aws: retry SSH ingress rule removal

- cmd/openshift-install/features.go
- cmd/openshift-install/main.go
- data/data/aws/bootstrap/main.tf
- data/data/aws/cluster/main.tf
- data/data/aws/cluster/master/main.tf
- data/data/aws/cluster/master/variables.tf
- data/data/aws/variables-aws.tf
- pkg/tfvars/aws/aws.go
Manual cherry-pick of https://github.com/openshift/installer/pull/8540
/jira cherrypick OCPBUGS-35032
> OCPBUGS-35485: [release-4.14] aws: terraform: add spot instance support for masters

- pkg/asset/machines/azure/azuremachines.go
Adding the option to enable AcceleratedNetworking in control-plane.
> CORS-3265: capz: Add Accelerated Networking

- data/data/bootstrap/baremetal/files/etc/containers/systemd/image-customization.container
This fixes deployments with proxy enabled.
> OCPBUGS-33702: baremetal: bootstrap: bind icc to localhost

- pkg/asset/cluster/tfvars.go
Add checks around number of compute replicas requested, the number of worker manifests and whether masters are schedulable. These are useful especially for compact cluster installs.
Manual backport of https://github.com/openshift/installer/pull/8553.
> [release-4.15] OCPBUGS-35359: GCP: Prevent cluster installation with mismatched worker assets and worker replicas

- images/installer/Dockerfile.upi.ci
Add ibmcloud plugins used by the PowerVS CI.
> OCPBUGS-36176: PowerVS: Add ibmcloud plugins

- data/data/bootstrap/baremetal/files/etc/containers/systemd/image-customization.container
This fixes deployments with proxy enabled.
(cherry picked from commit fa42f0535f550c6f9319ddbcd3fa37ec4f4b39d1)
> OCPBUGS-35818: baremetal: bootstrap: bind icc to localhost

- images/installer/Dockerfile.upi.ci
Add ibmcloud plugins used by the PowerVS CI.
> [release-4.15]: OCPBUGS-36400: PowerVS: add ibmcloud plugins

- pkg/asset/releaseimage/default.go
> CORS-3590: releaseimage: update default version

- cmd/openshift-install/destroy.go
Also fix linting issue and remove a redundant line of code.
> CORS-2775: cmd: destroy: remove deprecated github.com/pkg/errors

- pkg/asset/manifests/azure/cluster.go
- pkg/infrastructure/azure/azure.go
- pkg/infrastructure/azure/network.go
https://issues.redhat.com/browse/CORS-3485
> CORS-3485: Azure: modify control plane outbound LB into submission as an API LB

- pkg/asset/installconfig/azure/session.go
- pkg/asset/machines/azure/azuremachines.go
- pkg/asset/machines/azure/machines.go
- pkg/infrastructure/azure/azure.go
- pkg/infrastructure/azure/network.go
- pkg/infrastructure/azure/storage.go
Depends on https://github.com/openshift/installer/pull/8652
https://issues.redhat.com/browse/CORS-3302
> CORS-3302: port forward SSH to bootstrap host

- pkg/clusterapi/system.go
- pkg/infrastructure/clusterapi/clusterapi.go
Manual cherry-pick of https://github.com/openshift/installer/pull/8693
> OCPBUGS-36890: [release-4.16] capi: start controllers after WaitGroup is created

- pkg/asset/manifests/azure/cluster.go
- pkg/infrastructure/azure/azure.go
Adding the option to allow for existing vnets installation in CAPZ.
> CORS-3073: azure: Allow for installs in existing vnets

- pkg/asset/releaseimage/default.go
This reverts commit 5b289b758fb2b1bee6c2579ecdf5eb7c2a6641f8, reversing changes made to a8b4b1cc6baef97f3dfe16cd4f2eb35fe0374f80.
Until the agent-integration-tests are fixed.
> no-jira: Revert "Merge pull request #8714 from r4f4/bump-default-release-4.17"

- docs/user/openstack/customization.md
These fields were not mentioned in the docs.
> OCPBUGS-36917: openstack: Fix apiVIPs and ingressVIPs docs

- pkg/types/validation/installconfig.go
If a multi-arch cluster is configured, check that the release payload is multi arch or return an error otherwise.
> MULTIARCH-4814: ic: add release arch validation for multi-arch clusters

- pkg/infrastructure/openstack/preprovision/securitygroups.go
Before this patch, we used the Neutron call to add tags to the newly created security groups. However, that API doesn't accept tags containing special characters such as slash (`/`), even when url-encoded.
With this change, the security groups are tagged with an alternative API call (replace-all-tags) which accepts the tags in a JSON object. Apparently, Neutron accepts special characters (including slash) when they come in a JSON object.
> OCPBUGS-36913: openstack: Fix security group tagging

- pkg/infrastructure/gcp/clusterapi/iam.go
When running concurrent installs its possible that the SetIAMPolicy() will fail with the error:
"There were concurrent policy changes. Please retry the whole read-modify-write with exponential backoff."
Add a retry mechanism similar to what is done with Terraform.
> OCPBUGS-37217: CAPI GCP - retry SetIAMPolicy

- pkg/infrastructure/azure/azure.go
- pkg/infrastructure/azure/compute.go
https://issues.redhat.com/browse/OCPBUGS-37594
> OCPBUGS-37594: pkg/infrastructure/azure: Set architecture when creating gallery image

- docs/dev/dependencies.md
- docs/dev/libvirt/README.md
- docs/user/openstack/README.md
1. Replace yum by dnf.
2. Add zip to installation dependencies as it's really needed and not installed by default.
3. Update requitred golang version in does base what is currently in go.mod.
> no-jira: doc: minor update to installation doc

- data/data/agent/systemd/units/agent-auth-token-status.service
- pkg/asset/agent/gencrypto/authconfig.go
- pkg/asset/agent/image/agentimage.go
Enhance console logging to display node ISO expiry date during addNodes workflow
> AGENT-938: Enhance console logging to display node ISO expiry date during addNodes workflow

- images/installer/Dockerfile.upi.ci
FYI
- https://aicli.readthedocs.io/en/latest/
- https://github.com/faermanj/lab-aliyun (or my fork https://github.com/jianli-wei/lab-aliyun/tree/main)
> SPLAT-1560: set up 'aicli' & 'qemu-img' to use Assisted Installer to install OCP on Alibaba Cloud

- pkg/asset/machines/clusterapi.go
https://issues.redhat.com/browse/OCPBUGS-35947
> OCPBUGS-35947: pkg/asset/machines: fix Azure zones

- upi/vsphere/powercli/upi-destroy.ps1
- upi/vsphere/powercli/upi-functions.ps1
- upi/vsphere/powercli/upi.ps1
[SPLAT-1713](https://issues.redhat.com//browse/SPLAT-1713)
- Enhanced UPI powercli scripts to handle multiple vCenter
> SPLAT-1713: Enhanced vSphere UPI scripts for multi vcenter support

- pkg/infrastructure/azure/azure.go
https://issues.redhat.com/browse/OCPBUGS-37953
> OCPBUGS-37953: pkg/infrastructure/azure: limit storage account to 24 characters or less

- upi/vsphere/powercli/upi-destroy.ps1
- upi/vsphere/powercli/upi.ps1
[SPLAT-1713](https://issues.redhat.com//browse/SPLAT-1713)
- Updated upi and upi-destroy ps1 files to configure runtime to default to multiple vcenter mode
> SPLAT-1713: Updated powercli configuration to allow multi vcenters

- pkg/infrastructure/azure/azure.go
- pkg/infrastructure/azure/storage.go
https://issues.redhat.com/browse/OCPBUGS-37543
> OCPBUGS-37543: Azure: Disable shared key access when using managed identity

- pkg/clusterapi/system.go
- pkg/infrastructure/azure/azure.go
https://issues.redhat.com/browse/OCPBUGS-36196
> OCPBUGS-36196: CAPZ USGovernmentCloud fixes

- pkg/asset/manifests/azure/cluster.go
Adding virtual network ID value of the AzureCluster to the existing vnet specified during install config to avoid CAPI setting the "managed" tag to the resources resulting in an empty route table being created.
> OCPBUGS-37663: azure: Fix empty route table being created.

- pkg/types/validation/installconfig.go
- pkg/types/validation/installconfig_test.go
Check that the release payload can be used to create nodes from the specified architecture during install-config validation. If we don't do that, the install will fail with the error:
```
ERROR Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get "https://api.build11.ci.devcluster.openshift.com:6443/apis/config.openshift.io/v1/clusteroperators": dial tcp 13.59.207.137:6443: connect: connection refused
```
while the real reason is in the bootstrap bootkube logs:
```
Release image arch amd64 does not match host arch arm64
```
> OCPBUGS-38479: ic: validate release arch is compatible with cluster arch

- pkg/infrastructure/gcp/clusterapi/dns.go
** Skip the creation of private zone when a private zone already exists in the domain provided. This only applies to shared vpc installs.
> OCPBUGS-38966: Skip private managed zone creation for xpn installs

- data/data/azure/bootstrap/main.tf
- data/data/azure/cluster/main.tf
- data/data/azure/vnet/main.tf
https://issues.redhat.com/browse/OCPBUGS-37587
> OCPBUGS-38821: [release-4.16] Azure: Disable shared key access when using a managed identity

- pkg/infrastructure/vsphere/clusterapi/clusterapi.go
**Description:**
In the event that all defined failure domains specify a template, the ova does not need to be downloaded. If any failure domain fails to specify a template, an attempt will be made to download the template.
This is a continuation of work started in openshift/installer#8729
> OCPBUGS-38918,OCPBUGS-36494: vSphere - If template is defined skip downloading

- images/installer/Dockerfile.upi.ci.rhel8
OCPBUGS-39217
- Add yq to ci image
> OCPBUGS-39217: Add yq v4 to ci image

- images/installer/Dockerfile.upi.ci.rhel8
> OCPBUGS-39411: Added yq to ci image

- pkg/asset/machines/openstack/openstackmachines.go
Since metadata is not working over IPv6 for OpenStack[1] and also CoreOS image[2], let's use config-drive for the ignition.
[1] https://issues.redhat.com/browse/OSP-28056
[2] https://issues.redhat.com/browse/COS-2850
> OSASINFRA-3571: OpenStack: enable config-drive for single-stack IPv6

- pkg/infrastructure/azure/azure.go
- pkg/infrastructure/azure/compute.go
```
TrustedLaunch SecurityType can be configured in install-config:
==================
controlPlane:
architecture: amd64
hyperthreading: Enabled
name: master
platform:
azure: 
encryptionAtHost: true
settings:
securityType: TrustedLaunch
trustedLaunch:
uefiSettings:
secureBoot: Enabled
virtualizedTrustedPlatformModule: Enabled
```
Only Gen V2 images can be used to boot these Control Plane VMs with this security feature enabled.
When a Gallery Image resource is being created for the Gen V2 image, set the `Features` parameter to indicate that it can support the "SecurityType" "TrustedLaunch" Feature. That way this image is chosen to boot the control plane machines.
> OCPBUGS-36670: Azure CAPI: Set SecurityType as a Feature while creating Gallery Image

- pkg/infrastructure/azure/azure.go
When SecurityType is not set in the ControlPlane Machine Pool settings, check if it is set in the Default Machine Pool.
> OCPBUGS-36670: Azure CAPI: Look for SecuirtyType in DefaultMachinePlatform

- pkg/asset/installconfig/gcp/client.go
** In GCP, a peering zone can be created and act as a private zone only. Searching for zones based only on their type (public or private) was causing peering zones to appear. Peering zones are not currently supported in openshift. When searching for available dns zones filter out the peering zones if the peering zone config is available (according to the comments, a non null struct indicates a peering zone).
> OCPBUGS-38719: Filter peering zones out

- docs/user/openstack/install_upi.md
- images/openstack/Dockerfile.ci
- upi/openstack/inventory.yaml
- upi/openstack/network.yaml
Prefer RPM over dependencies coming from pip or ansible galaxy.
> OCPBUGS-30811: OpenStack: Install CI dependencies from rpm

- pkg/asset/installconfig/openstack/validation/platform.go
- pkg/asset/installconfig/openstack/validation/platform_test.go
When configuring a single stack IPv6 cluster there is no need to specify an external network, as it's not possible to create floating IP with IPv6. This commits adds a validation to ensure that is not specifed when the machine network only has IPv6.
> OSASINFRA-3607: OpenStack: validate combination of externalNetwotk with single stack v6

- pkg/asset/installconfig/gcp/validation.go
- pkg/asset/installconfig/gcp/validation_test.go
- pkg/types/gcp/machinepools.go
** Validate the disk and instance type combinations for gcp installs.
> OCPBUGS-41184: Add validation for gcp disk and instance types

- pkg/destroy/gcp/targetTCPProxies.go
** The addition of capg required the destroy process to clean up regional and global resources. The search for regional Target TCP proxies are not needed as these resources were never created by the installer. This fix only searches for global target tcp proxies, and it does not require updates to the minimum permissions.
> OCPBUGS-39340: Remove destroy search for regional target tcp proxies

- docs/user/openstack/install_upi.md
- upi/openstack/bootstrap.yaml
- upi/openstack/common.yaml
- upi/openstack/compute-nodes.yaml
- upi/openstack/control-plane.yaml
- upi/openstack/inventory.yaml
- upi/openstack/network.yaml
- upi/openstack/security-groups.yaml
- upi/openstack/update-network-resources.yaml
Manual backport of https://github.com/openshift/installer/pull/8724 and https://github.com/openshift/installer/pull/8936.
> [release-4.15] OCPBUGS-42011 OCPBUGS-39288: Openstack UPI - Reintroduce unique resource names

- pkg/asset/installconfig/powervs/metadata.go
> OCPBUGS-42717: Power VS Ensure Metadata populated for CAPI/private cluster case on PowerVS

- pkg/asset/installconfig/openstack/validation/cloudinfo.go
- pkg/asset/installconfig/openstack/validation/platform.go
- pkg/asset/installconfig/openstack/validation/platform_test.go
- vendor/github.com/gophercloud/gophercloud/v2/openstack/networking/v2/extensions/mtu/requests.go
- vendor/github.com/gophercloud/gophercloud/v2/openstack/networking/v2/extensions/mtu/results.go
- vendor/modules.txt
This is manual cherry-pick of https://github.com/openshift/installer/pull/8988 and https://github.com/openshift/installer/pull/9081.
> [release-4.17] OCPBUGS-41812: Validate MTU for custom network

- pkg/asset/installconfig/ibmcloud/client.go
- pkg/destroy/ibmcloud/subnet.go
Add pagination support for subnet lookups as part of BYON for IBM Cloud.
Related: https://issues.redhat.com/browse/OCPBUGS-36236
> OCPBUGS-36236: IBMCloud: Handle pagination for subnets

- pkg/agent/cluster.go
In the agent wait-for, when the APIs are not available, an attempt is made to check the host by ssh'ing to it. This results in confusing debug messages if the keys aren't present. This changes the check to just test connectivity to the host.
> OCPBUGS-36532: Agent installer wait-for, just test connectivity to host

- pkg/infrastructure/gcp/clusterapi/firewallrules.go
For internal published clusters, the API firewall rule source should be limited to the machine network CIDR.
> OCPBUGS-43520: Limit GCP API firewall rule for internal clusters

- pkg/clusterapi/system.go
Decrease the verbosity level for the IBM CAPI module.
> OCPBUGS-44022: PowerVS: Change CAPI verbosity level

- cmd/openshift-install/testdata/agent/image/configurations/external_with_bootArtifactsBaseURL_minimal_iso.txt
- cmd/openshift-install/testdata/agent/image/configurations/external_without_bootArtifactsBaseURL_minimal_iso.txt
- pkg/asset/agent/manifests/agentclusterinstall.go
- pkg/asset/agent/manifests/agentclusterinstall_test.go
Manual cherry-pick of https://github.com/openshift/installer/pull/9141
> [release-4.17] OCPBUGS-43972: Cherrypick oci ccm fix to 4.17

- cmd/openshift-install/testdata/agent/image/configurations/external_with_bootArtifactsBaseURL_minimal_iso.txt
- cmd/openshift-install/testdata/agent/image/configurations/external_without_bootArtifactsBaseURL_minimal_iso.txt
- pkg/asset/agent/manifests/agentclusterinstall.go
- pkg/asset/agent/manifests/agentclusterinstall_test.go
Manual cherry-pick of https://github.com/openshift/installer/pull/9141
> [release-4.16] OCPBUGS-44348: Cherrypick oci ccm fix to 4.16

- pkg/destroy/ibmcloud/resourcegroup.go
Provide additional details on potential blocking resource or service-instances for ResourceGroup deletion during cluster cleanup.
Related: https://issues.redhat.com/browse/OCPBUGS-29109
> OCPBUGS-29109: IBMCloud: RG delete failure details

- pkg/asset/agent/joiner/clusterinfo.go
This patch adds some basic troubleshooting info for the ClusterInfo asset, as a workflow report result (`add-nodes-cluster-inspection` stage).
If the asset completes successfully, a result like the following will be added:
```
"stages": [
{
"id": "add-nodes-cluster-inspection",
"description": "Gathering additional information from the target cluster",
"start_time": "2024-11-19T11:17:29.611381277Z",
"end_time": "2024-11-19T11:17:29.796955835Z",
"result": "{\"Architecture\":\"amd64\",\"OSImage\":\"https://rhcos.mirror.openshift.com/art/storage/prod/streams/4.18-9.4/builds/418.94.202410090804-0/x86_64/rhcos-418.94.202410090804-0-live.x86_64.iso\",\"PlatformType\":\"BareMetal\",\"ReleaseImage\":\"virthost.ostest.test.metalkube.org:5000/localimages/local-release-image@sha256:879ed85a63eb6ff7cda …
```
> AGENT-965: add ClusterInfo report result

- pkg/asset/manifests/cloudproviderconfig.go
In #9165, the default set of endpoint overrides necessary for `Internal` deploy was set for `External` as well for CCM. This PR properly conditionalizes the behavior.
> OCPBUGS-44922: Power VS: SetDefaultPrivateServiceEndpoints mistakenly called for External deploys

- cmd/openshift-install/testdata/agent/image/assets/with_additional_ntp_sources.txt
- pkg/asset/agent/image/ignition.go
- pkg/asset/agent/image/ignition_test.go
This a manual cherry-pick of #9142
> [release-4.16] OCPBUGS-45181: add chrony.conf file when additional NTP sources are configured

- pkg/infrastructure/aws/clusterapi/aws.go
Upstream capa is adding an extra Node Port Service ingress rule allowing any IPs. We already add our own rule restricted to the cluster's node security groups. While there is a fix upstream it requires updates to Golang and CAPI. Let's remove this extra rule in our bootstrap post-destroy stage instead.
This is a manual cherry-pick of https://github.com/openshift/installer/pull/9209 with a change in approach since we cannot bump Golang/CAPI/CAPA in 4.16.
> OCPBUGS-45669: [release-4.16] capi/aws: remove allow-all Node Port Service

- pkg/destroy/powervs/cloud-instance.go
- pkg/destroy/powervs/cloud-sshkey.go
- pkg/destroy/powervs/cloud-subnet.go
- pkg/destroy/powervs/cloudobjectstorage.go
- pkg/destroy/powervs/powervs.go
- pkg/destroy/powervs/publicgateway.go
- pkg/destroy/powervs/securitygroup.go
- pkg/destroy/powervs/serviceinstance.go
- pkg/destroy/powervs/vpc.go
Limit searching for resources to destroy to a specific resource group.
> OCPBUGS-48437: PowerVS: limit by resourceGroupID

- data/data/manifests/bootkube/cvo-overrides.yaml.template
cvo: bump default channel to stable-4.19
> CORS-3722: bump default channel to stable-4.19

- pkg/asset/cluster/tfvars/tfvars.go
- pkg/asset/installconfig/platformprovisioncheck.go
- pkg/asset/installconfig/powervs/regions.go
- pkg/asset/installconfig/powervs/validation.go
- pkg/asset/installconfig/powervs/validation_test.go
- pkg/asset/machines/worker.go
- pkg/types/powervs/powervs_regions.go
This is a manual cherry-pick of https://github.com/openshift/installer/pull/9319
> OCPBUGS-47663: [release-4.16] Power VS: Create region-zone-sysType hierarchy

- data/data/install.openshift.io_installconfigs.yaml
- pkg/infrastructure/nutanix/clusterapi/clusterapi.go
- pkg/types/nutanix/defaults/platform.go
- pkg/types/nutanix/defaults/platform_test.go
- pkg/types/nutanix/helpers.go
- pkg/types/nutanix/platform.go
- pkg/types/nutanix/validation/platform.go
- pkg/types/nutanix/validation/platform_test.go
[release-4.17] OCPBUGS-49362:
[Nutanix] Installation failed with timeout when uploading images to PC
> OCPBUGS-49362: [Nutanix] Installation failed with timeout when uploading images to PC

- pkg/infrastructure/azure/azure.go
Update SecurityType supported when creating Genv2 Image. 
Partial fix for OCPBUGS-41300.
Manual backport of https://github.com/openshift/installer/pull/9021 and https://github.com/openshift/installer/pull/9101.
> [release-4.17] OCPBUGS-41300: Azure: Update SecurityType passed in at Image creation

- pkg/asset/cluster/tfvars.go
- pkg/asset/installconfig/platformprovisioncheck.go
- pkg/asset/installconfig/powervs/regions.go
- pkg/asset/installconfig/powervs/validation.go
- pkg/asset/installconfig/powervs/validation_test.go
- pkg/asset/machines/worker.go
- pkg/types/powervs/powervs_regions.go
This is a manual cherry-pick of https://github.com/openshift/installer/pull/9338
> OCPBUGS-47716: [release-4.15] Power VS: Create region-zone-sysType hierarchy

- data/data/install.openshift.io_installconfigs.yaml
- pkg/infrastructure/nutanix/clusterapi/clusterapi.go
- pkg/types/nutanix/defaults/platform.go
- pkg/types/nutanix/defaults/platform_test.go
- pkg/types/nutanix/helpers.go
- pkg/types/nutanix/platform.go
- pkg/types/nutanix/validation/platform.go
- pkg/types/nutanix/validation/platform_test.go
[release-4.16] OCPBUGS-49416:
[Nutanix] Installation failed with timeout when uploading images to PC
This PR is manually cherrypick-ed from the PRs #9406 (for release-4.17), #9399 (for release-4.18) and #9377 (for master branch)
> OCPBUGS-49416: [Nutanix] Installation failed with timeout when uploading images to PC

- pkg/asset/cluster/aws/aws.go
Follow up https://github.com/openshift/installer/pull/9413 to correct a typo
> OCPBUGS-50839: correct typo

- pkg/asset/installconfig/powervs/client.go
- pkg/asset/installconfig/powervs/mock/powervsclient_generated.go
- pkg/asset/installconfig/powervs/validation.go
- pkg/asset/installconfig/powervs/validation_test.go
- pkg/asset/machines/worker.go
- pkg/types/powervs/validation/machinepool.go
- pkg/types/powervs/validation/machinepool_test.go
- pkg/types/powervs/validation/platform.go
- pkg/types/validation/machinepools.go
Use an API to query the datacenter what supported machine types are available.
> OCPBUGS-49940: PowerVS: datacenter supported systems

- pkg/asset/installconfig/ibmcloud/client.go
- pkg/asset/installconfig/ibmcloud/ibmcloud.go
- pkg/asset/installconfig/ibmcloud/mock/ibmcloudclient_generated.go
- pkg/types/ibmcloud/validation/platform.go
- pkg/types/ibmcloud/validation/platform_test.go
- vendor/github.com/IBM/platform-services-go-sdk/globalcatalogv1/global_catalog_v1.go
- vendor/modules.txt
Dynamically lookup the available IBM Cloud Regions, using Global Catalog, rather than maintaining a hardcoded list.
> OCPBUGS-49623: IBMCloud: Missing ca-mon region due to static region list

- data/data/bootstrap/baremetal/files/etc/containers/systemd/image-customization.container
The ICC will then add it to the custom image in order to pull down the IPA image.
> OCPBUGS-44840: Mount the user-ca-bundle into ICC

- OWNERS_ALIASES
> NO-JIRA: OWNERS: add thuan

- cmd/openshift-install/testdata/agent/unconfigured-ignition/configurations/interactive.txt
- data/data/agent/files/usr/local/bin/install-status.sh
- data/data/agent/systemd/units/agent-start-ui.service.template
- data/data/agent/systemd/units/install-status.service
- pkg/asset/agent/image/ignition.go
This patch shows the UI url in the rendezvous node console when available.
> AGENT-467: show the agent ui url when available

- OWNERS_ALIASES
AWS updates:
- add tthvo
Azure updates:
- remove mtulio
- add rna-afk and sadasu
/assign patrickdillon
> NO-JIRA: update OWNER_ALIASES for azure and aws

- pkg/asset/installconfig/platformprovisioncheck.go
- pkg/asset/installconfig/powervs/validation.go
- pkg/asset/machines/powervs/machines.go
- pkg/asset/rhcos/image.go
Reverts https://github.com/openshift/installer/pull/9417
> OCPBUGS-53303: Revert: Power VS: Disallow platform.powervs.clusterOSImage in install-config

- pkg/infrastructure/azure/azure.go
Moves the dummy SG created for BYO vnet installs to the InfraReady
hook, rather than preprovision. A previous commit, https://github.com/openshift/installer/commit/0779504264628a523690a3e4a5dd12d3a3152bcb,
moved resource group creation to be handled by CAPZ. So the SG
creation needs to be done after CAPZ has created the resource group.
Fixes: OCPBUGS-54232
> OCPBUGS-54232:  Azure Move BYO VNET SG creation to InfraReady

- pkg/asset/installconfig/aws/validation.go
- pkg/asset/installconfig/aws/validation_test.go
We should only validate duplicate AZs for provided subnets if no roles are explicitly specified. This allows us to support the following user stories (see EP [[0]]( https://github.com/openshift/enhancements/blob/ea465e192bfb58ec8654f1c904a4af68777f68ec/enhancements/installer/aws-lb-subnet-selection.md)):
- Dedicated Load Balancer Subnets User Story
- Cluster Nodes on Different Private Subnets User Story
However, we will still validation the duplicate AZs for subnets of the same roles.
> CORS-3870: validate duplicate AZs if no subnet roles at all or only for subnets of the same role

- pkg/asset/installconfig/aws/validation.go
Previously, call to DescribeSecurityGroups accesses the session field from metadata, which depends on call to VPC to populate that field. However, function VPC, which internally call populateSubnets is now constructing the ec2 client differently so session is field not initialized there, causing nil access.
The PR ensures the session field is initialized by using getting func Session instead.
> OCPBUGS-55324: fix nil field access when describing security groups

- pkg/asset/ignition/bootstrap/common.go
** When the user creates the ignition configs and a failure or some time goes by before cluster creation occurs, the certs could go bad/expire. The installer can warn of expired certs, but it does not fail. These warnings are often overlooked and pass by too quickly during the installation process. The changes here will cause an immediate failure.
> CORS-3633: Fail the install when there are expired certs

- OWNERS_ALIASES
> no-jira: Update team osasinfra

- pkg/asset/installconfig/aws/ec2.go
pkg/asset/installconfig/aws/ec2.go
** During the partial migration for SDK v2 (aws) to allow the MX-Central-1 region, the session was no longer used and the config was used. The use of the global session was removed in AWS and the config must be used each time the clients are created. This change caused the use of user-entered credentials to be lost (when none were found). This change adds this ability back.
** Note: the credentials file will be created in ~/.aws when the credentials are entered.
> OCPBUGS-56658: Prompt User for AWS Creds when none are found

- pkg/asset/releaseimage/default.go
Updating release image to the latest version 4.20
> CORS-3795: Updating the release image to 4.20

- data/data/manifests/bootkube/cvo-overrides.yaml.template
Updating CVO channel to the latest 4.20 version.
> CORS-3796: Update CVO channel to latest

- pkg/asset/manifests/topologies.go
- pkg/asset/manifests/topologies_test.go
updated the topology determination logic to correctly apply the HighlyAvailableArbiter controlPlaneTopology when an arbiter node is included
> MGMT-20992: feat: update determineTopologies function

- pkg/asset/ignition/bootstrap/cvoignore.go
This PR introduces `OPENSHIFT_INSTALL_EXPERIMENTAL_DISABLE_IMAGE_POLICY` environment variable. When set non-empty, it instructs the installer to include an entry for ClusterImagePolicy `openshift` in the CVO overrides. This override enables opting out of the sigstore signing requirement for release images.
The change is part of OpenShift Image Policy EP [[1]](https://github.com/openshift/enhancements/blob/0f1e5f130b6b4d99e99d35191ea18b41ddef4168/enhancements/security/openshift-image-policy.md#installer).
The CVO overrides are only visible in the `create ignition-configs` and `create cluster` sub-command as `cvoignore` asset is only generated during ignition-config phase. This means generated manifests (i.e. `create manifests`) does not reflect the override, which can be a confusing UX. …
> CORS-3550: add ability to opt out of the sigstore signing requirement
